### ISSUE TITLE
support additional capabilities of jslider

### ISSUE THREAD

**Issue by jjallaire** [rstudio/shiny#1]
Our slider control is based on the jslider component: https://github.com/egorkhmelev/jslider

There are several additional capabilities of this component which we should expose:

1) Ability to input two values simultaneously as a range
2) Non-linear scales (via the heterogeneity property)
3) Tick labels (note we'd need to add code to do snapping to ticks since it doesn't do this by default)
4) Additional display formats (e.g. currency)
5) Custom input types (e.g. time -- this requires a custom calculate function)

**Comment by bborgesr** [comment]
Wow, Shiny's very first issue was still open... This is kinda historic, Joe!
