### ISSUE TITLE
Some Shiny Image / Plot Interaction Features Fail With Univariate Plots

### ISSUE THREAD

**Issue by codoremifa** [rstudio/shiny#1001]
The 
```r
"if (is.null(yvar)) 
        stop("nearPoints: not able to automatically infer `yvar` from coordinfo")"
```
bits in the Shiny interaction functions causes issues when interacting with the plot in the below app -
```r
ui <- basicPage(
    plotOutput("plot1", click = "plot_click"),
    verbatimTextOutput("info")
)

server <- function(input, output) {
    output$plot1 <- renderPlot({
        ggplot(mtcars) + geom_density(aes(x = wt))
    })
    
    output$info <- renderPrint({
        nearPoints(mtcars, input$plot_click,)
    })
}

shinyApp(ui, server)
```
In this plot there is no Y variable defined as it isn't needed. The interaction functions still look for a Y variable though which causes the error.

**Comment by wch** [comment]
The `nearPoints` function is designed only to work when x and y values are present. In this case, you would need to filter the data manually.
