### ISSUE TITLE
updateSliderInput doesn't update the value until the input is in view, which can cause problems

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1010]
When using `updateSliderInput()` on a `sliderInput` that is in a tab that isn't currently visible, the slider doesn't actually get updated until it is visible.  This is not the case with other inputs I tested and causing problems if another input/output depends on that slider.

Example: this app has two tabs, each with a slider input. There is an output specifying what the value of the slider in tab2 is. Whenever the slider in tab1 is changed, the slider in tab2 is updated to match it. Note that the output *should* change whenever tab1 slider is moved, but it only gets updated after seeing tab2 slider.

```
library(shiny)
runApp(shinyApp(
  ui = 
    navbarPage(
      "title",
      tabPanel(
        "tab1",
        sliderInput("num1", "Set slider in tab2 to:", 1, 10, 1),
        textOutput("foo")
      ),
      tabPanel(
        "tab2",
        sliderInput("num2", "num", 1, 10, 1)
      )
    )
  ,
  server = function(input, output, session) {
    output$foo <- renderText(sprintf("Number in tab2 is: %s", input$num2))
    observe({
      updateSliderInput(session, "num2", value = input$num1)
    })
  }
))
```

Note that if you put both sliders in the same tab, things work as expected. Also, if you change the slider input to a numeric input, then again things work as expected.

**Comment by taunometsalu** [comment]
I also encountered the same issue, here is a slightly different minimal example (with conditionalPanel). The slider only gets updated if it is shown. 

My typical use case would be having many widgets controlling appearance of the plot, grouped by checkboxes using conditionalPanel ("show coloring options", "show text options" etc.). If some of the groups has sliderInput and the default value of it is calculated from data, it is not immediately updated. Any solutions?

```
library(shiny)

runApp(shinyApp(
  ui = shinyUI(fluidPage(
	titlePanel("Slider input"),
	sidebarLayout(
	  sidebarPanel(
	    actionButton("updateSlider", "Update slider"),
	    checkboxInput("showSlider", "show slider", value = FALSE),
	    conditionalPanel(condition = "input.showSlider == true",
	                     sliderInput("slider", "Slider", value = 2, min = 1, max = 10)
	    )
	  ),
	  mainPanel(
	    verbatimTextOutput("test")
	  )
	)
  )),
  
  server = function(input, output, session) {  
    output$test = renderPrint({
      input$slider
    })
    
    observeEvent(input$updateSlider, {
      updateSliderInput(session, "slider", value = 10)
    })
  }
))
```

**Comment by daattali** [comment]
That's a similar usecase to my use as well, I'm glad to see I'm not alone in having this problem.

**Comment by jcheng5** [comment]
Sorry, I've been swamped with new feature development. I'll try to take a look at this tomorrow but if I don't get to it, I think you could work around it for now by proxying a reactive value in front of the slider. 

```
v <- reactiveValues(sliderVal=NULL)
observe({ v$sliderVal <- input$slider }, priority = 10)
updateSliderVal <- function(val) {
  updateSliderInput(...)
  v$sliderVal <- val
}
```

Then refer to v$sliderVal instead of input$slider in all your other code.

**Comment by daattali** [comment]
That workaround would probably work, thanks. This is in no way a priority so no worries if this won't get looked at for a while

**Comment by daattali** [comment]
Tested in my real life app and works great, thanks Joe!

**Comment by taunometsalu** [comment]
If I am not mistaken, it seems that the simpler fix (#1034) broke it again. The previous fix (#1026) worked. See my example above.

**Comment by wch** [comment]
It looks like the simpler fix (4e1caee) actually did work, but there's been some change since then that made it stop working. 

I bisected it to 2da9bc0

**Comment by wch** [comment]
Actually, it looks like my simpler fix didn't actually work. When I was testing the fix, I didn't do a `grunt clean` before `grunt`, so it didn't actually rebuild `shiny.js`. :(

I'll switch it back to the previous fix.

**Comment by taunometsalu** [comment]
Thanks again!
