### ISSUE TITLE
Suggestion: add shinyapp code snippet to RStudio

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1016]
I find it useful to have a code snippet that initialized an empty Shiny app template.  It'd be nice to have it by default in RStudio, it will make it easier for beginners to create tiny Shiny apps on the fly without having to go through *File > New Project > Shiny app*

```
snippet shinyapp
	library(shiny)
	
	ui <- fluidPage(
		${0}
	)
	
	server <- function(input, output, session) {
	
	}
	
	shinyApp(ui = ui, server = server)

```

**Comment by jcheng5** [comment]
We just did something close to this--the New File menu now lets you make a new Shiny app (but it does insist that you put it in a dedicated directory as app.R or ui.R/server.R). https://dailies.rstudio.com
