### ISSUE TITLE
Selection update of server side selectize input elements with more than 1000 choices

### ISSUE THREAD

**Issue by akaever** [rstudio/shiny#1018]
There seems to be an issue when updating the selection of server side selectize input elements with more than 1000 choices. When trying to set the selection to the 1001 (or larger) choice, the input element is not updated. Selecting one of the first 1-1000 choices works fine (see example).

Seems to be related to initially displaying the first 1000 choices. In case this cannot be solved easily, a workaround would be to put the selected choices at the beginning of the choices vector.

```
library(shiny)

runApp(list(
	ui = bootstrapPage(
		selectizeInput("testSel", label="Test selectize", choices=NULL, 
									 multiple = TRUE)
	),
	server = function(session, input, output) {
		nValues <- 1002
		choices <- as.character(1:nValues)
		
		# does not work
		selectionIndex <- 1001
		# works
		# selectionIndex <- 1000
		
		updateSelectizeInput(session, "testSel", choices=choices, selected=choices[selectionIndex], 
												 server = TRUE)
		
		observe({
			print(input$testSel)
		})
	}
))
```

**Comment by yihui** [comment]
Should be fixed by #1023. Thanks!
