### ISSUE TITLE
Small doc improvement: mention that downloadHandler does not work in RStudio viewer

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1033]
I just looked at Shiny apps built for the first time by ~30 students, and most of them who tried using a download button complained that it took them a very very long time to "debug" download buttons until they realized that they actually work if they open the app in the browser.

I think it should be mentioned in the function documentation to save a lot of frustration from future newbies.

**Comment by wch** [comment]
It does work for me running RStudio Desktop (with the daily preview) on my Mac, and with RStudio Server. Do you remember whether your were using Desktop or Server?

**Comment by daattali** [comment]
It was definitely Desktop on Windows 7. I can check again

**Comment by daattali** [comment]
Using RStudio 0.99.1251, it still doesn't work for me. A window pops up momentarily but disappears immediately and nothing happens. Alternatively, maybe it does get downloaded but the file is going to somewhere that I can't find and I don't get any confirmation that it worked

I just used the example code from the documentation:

```
ui <- fluidPage(
  downloadLink("downloadData", "Download")
)

server <- function(input, output) {
  # Our dataset
  data <- mtcars

  output$downloadData <- downloadHandler(
    filename = function() {
      paste("data-", Sys.Date(), ".csv", sep="")
    },
    content = function(file) {
      write.csv(data, file)
    }
  )
}

shinyApp(ui, server)
```

**Comment by jcheng5** [comment]
cc @jmcphers Any chance of Qt-based RStudio Desktop builds supporting file downloads?

**Comment by jmcphers** [comment]
It's on our backlog but probably not for this release as we're closing it down soon.

**Comment by jmcphers** [comment]
For anyone affected by this: I've just fixed the issue on the RStudio side; the fix will be available starting in build 1.1.69.

**Comment by daattali** [comment]
Both Windows and Mac?

**Comment by jmcphers** [comment]
Yep. It's largely worked on Mac since we did the Cocoa port; it's just the Qt platforms (Windows and  Linux) that needed fixing.
