### ISSUE TITLE
Access to the `session` environment in interactive documents

### ISSUE THREAD

**Issue by aoles** [rstudio/shiny#1040]
Hi,
is there a way to access `clientData` from the `session` environment for apps running in an interactive document, e.g. in the sample document below? 

Thanks for any input,
Andrzej

    ---
    title: "Untitled"
    author: "Andrzej Oleś"
    date: "December 18, 2015"
    output: html_document
    runtime: shiny
    ---

    This R Markdown document is made interactive using Shiny. Unlike the more traditional workflow of creating static reports, you can now create documents that allow your readers to change the assumptions underlying your analysis and see the results immediately. 

    ## Inputs and Outputs

    You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

    ```{r, echo=FALSE}
    inputPanel(
      selectInput("n_breaks", label = "Number of bins:",
		  choices = c(10, 20, 35, 50), selected = 20),
      
      sliderInput("bw_adjust", label = "Bandwidth adjustment:",
		  min = 0.2, max = 2, value = 1, step = 0.2)
    )

    renderPlot({
      hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
	  xlab = "Duration (minutes)", main = "Geyser eruption duration")
      
      dens <- density(faithful$eruptions, adjust = input$bw_adjust)
      lines(dens, col = "blue")
    })
    ```

**Comment by jcheng5** [comment]
Hmmm, we should probably just make it automatically available like we do with output and input. But if that doesn't work, you can try calling getDefaultReactiveDomain(), that should return the session.

**Comment by aoles** [comment]
Hi Joe,
many thanks for answering so quickly! Indeed, the `session` object is available.

However, I'm still struggling to get my app to work. I want to create an interactive rmardown document with [shinyURL](https://github.com/aoles/shinyURL) enabled. When I define the app explicitly using `shinyApp`, it works just fine.

    ---
    title: "Embedded Shiny Application"
    output: html_document
    runtime: shiny
    ---
      
      ```{r, echo=FALSE}
    shinyApp(
      ui = fluidPage(
        fluidRow(
          column(6, sliderInput("bins", "Number of bins:", min=1, max=50, value=30, width="100%")),
          column(6, shinyURL::shinyURL.ui()),
          plotOutput("plot")
        )
      ),
      server = function(input, output, session) {
        shinyURL::shinyURL.server(session)
        output$plot <- renderPlot({
          x <- faithful[, 2]
          bins <- seq(min(x), max(x), length.out = input$bins + 1)
          hist(x, breaks = bins, col = 'darkgray', border = 'white')
        })
      },
      options = list(height = 520)
    )
    ```

However, when I include the apps code directly

    ---
    title: "Interactive Shiny Document"
    output: html_document
    runtime: shiny
    ---

    ```{r, echo=FALSE}
    inputPanel(
      sliderInput("bins", "Number of bins:", min = 1,  max = 50, value = 30, width="100%"),
      shinyURL::shinyURL.ui()
    )

    renderPlot({
      x <- faithful[, 2]
      bins <- seq(min(x), max(x), length.out = input$bins + 1)
      hist(x, breaks = bins, col = 'darkgray', border = 'white')
    })

    shinyURL::shinyURL.server(session)  
    ```

it fails with the following error:

    Warning: Unhandled error in observer: invalid argument type
    observe({
	inputValues = reactiveValuesToList(session$input, all.names = FALSE)
	inputValues = inputValues[!unlist(lapply(inputValues, function(x) inherits(x, 
	    "shinyActionButtonValue")), use.names = FALSE)]
	idx = grep("_mouse_(over|out)$", names(inputValues))
	if (length(idx) > 0) 
	    inputValues = inputValues[-idx]
	names = sort(names(inputValues))
	addValues = NULL
	i = 1L
	while (i <= length(names)) {
	    n = names[i]
	    idx = grep(sprintf("^%s[0-9]+", n), names)
	    if (length(idx) == 0L) {
		i = i + 1L
	    }
	    else {
		value = inputValues[[n]]
		names = names[-c(i, idx)]
		if (is.null(value)) 
		    value = ""
		values = as.list(value)
		names(values) = sprintf("%s[%s]", n, seq_along(value))
		addValues = c(values, addValues)
	    }
	}
	inputValues = inputValues[names]
	inputValu [... truncated]

Do you have any suggestions what could be the problem here?

Thanks for any help,
Andrzej

**Comment by zippeurfou** [comment]
@jcheng5 Any progress in making it automatically available?

**Comment by aoles** [comment]
Hi @jcheng5,
I've managed to fix the issue with using [shinyURL](https://github.com/aoles/shinyURL) with interactive rmarkdown documents, see: https://github.com/aoles/shinyURL/commit/09eda18c13f41082df2b236048f90055bb1dd67e. The problem was caused by the fact that immediately after the app starts `session$input` is empty, and the inputs seem to appear semi-dynamically. I didn't experience this before in standalone apps or apps embedded using `shinyApp*`. Do you have any comments on the different behaviour of interactive rmarkdown documents?

**Comment by jcheng5** [comment]
Yes, rmarkdown documents are quite different. It's because the entire app is contained in a big renderUI. I think you'd have similar issues with any app that has inputs in a renderUI. This is one of the big challenges we need to address if we want bookmarkable state as a built-in feature in Shiny.

**Comment by aoles** [comment]
Thanks @jcheng5, this makes sense. I use an observer which waits until the inputs appear, so it plays nice with `renderUI`. The original issue was due to the fact that I didn't account for the situation when all inputs are dynamic, so that `session$input` is empty at the beginning.

**Comment by moocunsw** [comment]
hi folks, i've been scouting for a while to no avail. following the thread above, i'm trying to get the session$user from within a markdown document which is setup as runtime:shiny.
Basically i need this value before running a query to prep the dataframe, but i can't seem to make it work at all.  Have you got a working example of how to access the user and/or the current url to parse values from?

thanks!

**Comment by moocunsw** [comment]
in case anyone is interested this works:
`currentUser <- session$user`

however i had to make sure that the library loading chunk contains shiny, rmarkdown and knitr and only then it would work for me
