### ISSUE TITLE
reactivity fails in inputPanel environment

### ISSUE THREAD

**Issue by Nicktz** [rstudio/shiny#1041]
Hi guys,

reactive data seems to fail in inputPanel environments, unless I am doing something wrong?

Please see [this](http://stackoverflow.com/questions/34354327/using-reactive-calls-in-a-tabpanel-environment-in-shiny?noredirect=1#comment56455877_34354327) stackoverflow issue. Not sure if it is a shiny problem or a me understanding the environments incorrectly?

**Comment by wch** [comment]
It look like this was answered on SO.
