### ISSUE TITLE
"Build custom output objects" article still refers to RJSONIO

### ISSUE THREAD

**Issue by mmuurr** [rstudio/shiny#1045]
Article at http://shiny.rstudio.com/articles/building-outputs.html refers to **RJSONIO**, though Shiny uses **jsonlite** as of 0.12.0, correct?

Are the articles living in a separate github repo somewhere?
If so, I'd be happy to make the text changes and submit a pull request (I just couldn't find the articles in any of rstudio's repos).

**Comment by jcheng5** [comment]
Thanks! I've updated the article.
