### ISSUE TITLE
function reference page no longer grouped by category

### ISSUE THREAD

**Issue by mmuurr** [rstudio/shiny#1046]
The function reference page (http://shiny.rstudio.com/reference/shiny/latest/) was previously organized such that functions were grouped by 'category' (e.g. HTML wrappers, render functions, low-level reactivity functions).
In the current version, the groupings have been removed.

Feature request: can the groupings be reinstated?
It made browsing much easier (and implicitly helped provide a high-level overview of Shiny's architecture).

**Comment by jcheng5** [comment]
Thank you! This wasn't intentional; that page is built by a script and one of the libraries we use changed its behavior. It should be fixed now.
