### ISSUE TITLE
Show warn message to the user.

### ISSUE THREAD

**Issue by zhilongjia** [rstudio/shiny#1050]
An enhancement. So far, `warning()` only show it in the console, not to users. And `validate` will stop not just a warning. It is useful in the situation where a subset table or figure is shown although user requires a whole one, which is large.

A related question at [SO](http://stackoverflow.com/questions/34422342/show-warning-to-user-in-shiny-in-r). Thank you.

**Comment by wch** [comment]
I think this is a duplicate of #899.
