### ISSUE TITLE
Unable to view map in Window and Viewer Pane but it is working properly with Browser

### ISSUE THREAD

**Issue by cryptomanic** [rstudio/shiny#1055]
This is my first time reporting an issue. If I am wrong somewhere please help me.
My Shiny Project Structure : 
---`www/ui.html`
---`ui.R`
---`server.R`
In the main panel of ui.R I have added `includeHTML("www/ui.html")`. When I am running the app by selecting Run External it is working properly (displaying google maps on the page).  But no map is displayed while running in Window mode or Viewer Pane mode.

**Comment by wch** [comment]
This is probably related to #1148.

**Comment by wch** [comment]
@cryptomanic Any chance you still have the code that causes this problem? We need that in order to reproduce the issue and debug it. Also, are you running on Windows?

**Comment by wch** [comment]
Closing this now. If you have updates, we can reopen this issue.
