### ISSUE TITLE
Can't modify `imageOutput` defaults if using `uiOutput`

### ISSUE THREAD

**Issue by fmichonneau** [rstudio/shiny#1058]
I'm creating an app with photo thumbnails and use a combination of `renderUI`, `renderImage` and `uiOutput`. It works well but the spacing between the photo is too large, and it seems that it's not possible to pass arguments to change the default values of `imageOutput` (that hard code the height of the enclosing `div` for the image at 400px).

Is there a way to change it?

I have the following in the `server`;

```r
....
output$gallery <- renderUI({
      lst_files <- list.files(path = img_path(), pattern = "JPG$",
                              full.names = TRUE)
        num <- length(lst_files)
        lapply(seq_len(num), function(i) {
            output[[paste0("images", i)]] <- renderImage({
                return(list(
                    src = lst_files[i],
                    filetype = "image/jpeg",
                    height = 200,
                    width = 300
                ))
            }, deleteFile = FALSE)
      })
 })
....
```

and in the `ui`;

```r
.... uiOutput("gallery") ....
```

**Comment by wch** [comment]
It's not clear to me what you expect to show up in the `gallery` output... It looks like you're setting `output$image1`, `output$image2`, and so on, which you could do outside of the `renderUI()`.

I think that what you want is something like this:

```R
lst_files <- list.files(path = img_path(), pattern = "JPG$",
  full.names = TRUE)

# Do the renderImage calls
lapply(seq_along(lst_files), function(i) {
  output[[paste0("images", i)]] <- renderImage({
    return(list(
      src = lst_files[i],
      filetype = "image/jpeg",
      height = 200,
      width = 300
    ))
  }, deleteFile = FALSE)
})

# Send the imageOutputs to the client
output$gallery <- renderUI({
  lapply(seq_along(lst_files), function(i) {
    imageOutput(paste0("images", i))
  })
})
```

**Comment by fmichonneau** [comment]
Thanks @wch! It's what I was looking for. It wasn't clear to me that I could take the generation of the output$image1, ... could be done outside.
