### ISSUE TITLE
Are there any changes in using selectInput (selectizeInput) with shiny 0.12.2.9007 ?

### ISSUE THREAD

**Issue by frajuegies** [rstudio/shiny#1060]
Hi,

the following UI is working w/o any problems in 0.12.2 but not in 0.12.2.9007:

output$s_x_column <- renderUI ({
  if (is.null(inData())) return (NULL)
  table <- inData()
  
  col_all <- colnames(table)
  col_char <- colnames(table[sapply(table,is.character)])
  entries <- as.list(setdiff(col_all,col_char))
  ### I have as well used entries <- setdiff(col_all,, col_char) with the same result

print (entries)
  ### entries are shown as expected
  
selectizeInput("s_x_column",label="Numerical Filter Variable",choices = entries,selected="ROWID",multiple=FALSE) 
})

Thank you very much for any hint

Jürgen

**Comment by wch** [comment]
Could you provide a reproducible example app?

**Comment by frajuegies** [comment]
Hi Winston,

sorry for coming back to your question so lately. 
I have not found the reason yet, but it seems to be independent of the shiny version.

So, I would close that ticket.
All the best for 2016
Jürgen

**Comment by yihui** [comment]
If you mean the issue exists for all shiny versions, we'd like to fix it if you can provide a minimal reproducible example. Thanks!

**Comment by frajuegies** [comment]
As of now I think it is a error in my data frame. I will come back to the issue if I would be able to create an example (of course).

Best regards, Jürgen
