### ISSUE TITLE
renderTable buggy print

### ISSUE THREAD

**Issue by 3manuek** [rstudio/shiny#1065]
Hi folks,

I'm not sure if this is a bug or not. I googled it and I'm not sure if I doing something wrong.

If I use a reactive expression and try to pass rotate.colnames like this:

```
 output$tableResults <- renderTable({DataResults()}, rotate.colnames = TRUE)
```

It prints the Latex code on each column name the following:
```
\begin{sideways} 
content 
\end{sideways}
```

Regards,

**Comment by wch** [comment]
I think you're trying to use a LaTeX option (from xtable) and it unfortunately won't work with HTML table output. It should be possible to rotate them using CSS.
