### ISSUE TITLE
Small suggestion: make the custom JavaScript messages use more unique names to avoid collisions with users calling their own JS

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1077]
I just looked at how `session$reload` [is implemented](https://github.com/rstudio/shiny/blob/877d7451ddc3a051450ae7965f0ed6885ecbd1d1/R/shiny.R#L723) (which is a great addition, thank you), and saw that it sends a message with the name `reload`.  I think it'd be a bit safer to use a name that's a bit more unique like `shiny:reload`, just to make sure that if a user ever tries writing a JavaScript function called `reload`, they wouldn't run into weird problems and be able to call their version.

Same goes for the other messages

**Comment by wch** [comment]
I was recently looking at this code, and I think these internal (to Shiny) messages should be implemented with `private$write` instead of `self$sendCustomMessage`. This is because `sendCustomMessage` is intended to be used for external code.
