### ISSUE TITLE
Shiny : variable height of renderplot

### ISSUE THREAD

**Issue by lucie777777** [rstudio/shiny#1078]
Hello !

I would like to take the height of my plot reactive because sometimes I have to draw just one graph and sometimes two or three graphs. Here my code :

        output$myplot<-renderPlot({
     
        plot_to_draw <- data[data$code==input$code,"River_name"]

        plot(plot_to_draw)   
                               
        number_of_plot <- length(plot_to_draw)

        },height = 500*number_of_plot)

But shiny reads the height of the plot just one time so that it's not reactive. 
Thank you for your answers !

**Comment by wch** [comment]
Hi, the shiny-discuss list is the right place to ask this, and I see that you've already asked there, so I'll close this.
