### ISSUE TITLE
Build dependency on development Rmarkdown

### ISSUE THREAD

**Issue by cfhammill** [rstudio/shiny#1079]
I was trying to install the development version of shiny and I got:

* creating vignettes ... ERROR
Error: processing vignette 'events.Rmd' failed with diagnostics:
object 'html_vignette' not found
Execution halted

I fixed the problem by first installing the development version of Rmarkdown from github, but there's no reference to this dependency in the install instructions.

**Comment by jcheng5** [comment]
cc @yihui. Is there any way to avoid this?

**Comment by yihui** [comment]
That is weird. You should not need the development version of rmarkdown. The CRAN version should work fine. Could you double check if `install.packages('rmarkdown')` really does not work?

On the other hand, if you install shiny from Github using devtools, the vignettes will not be built by default. Can you show us how exactly you installed shiny from Github?

**Comment by cfhammill** [comment]
hmm, I just removed the shiny and rmarkdown, reinstalled CRAN rmarkdown and github shiny without issue. I had rmarkdown available on the system already, it may have just been too out of date.

I ran devtools::install_github("rstudio/shiny") as per the README. My bet is the old version of rmarkdown was the issue.
