### ISSUE TITLE
Passing arbitrary handlers/expression to callModule does not execute properly.

### ISSUE THREAD

**Issue by VermillionAzure** [rstudio/shiny#1083]
It would be beneficial to Shiny modules if servers could execute code given to them in the appropriate scope. Here, I try to embed a `observeEvent()` function inside of a module server function and then attempt it to run it in the context as if it were inlined into the function. It does not work.

    core_env <- new.env()
    core_env$rval <- reactiveValues()
    core_env$rval$module_choices <- c('A', 'B', 'C')
    core_env$rval$module_tags_category <- c('a', 'b', 'c')
    core_env$rval$module_tags_workflow <- c('1', '2', '3')
    core_env$rval$module_tags_function <- c('z', 'x', 'y')

    core_env$rval$status_text <- 'Idle.'

    coreStatusText <- function(string, core_env, session, style='warning') {
      core_env$rval$status_text <- string
      updateCollapse(session=session, id='Status', open='Status', style=list(Status=style))
    }

    moduleCoreUI <- function(id, title, core_env, ...) {
      # Create the namespace.
      ns <- shiny::NS(id)
      # Get the elements; THESE MUST BE bsCollapsePanel
      elements <- eval(substitute(...))
      
      div(
        bsCollapse(
          bsCollapsePanel(title='Status', value='status_open', style='info',
            p('\n'),
            p(core_env$rval$status_text)
          )
        ),
        wellPanel(
          elements
        )
      )
    }

    moduleCoreServer <- function(input, output, session, core_env, expr) {
      browser()
      ns <- session$ns
      
      # Create a shorthand for the module environment.
      e <- core_env
      # Preserve the executed expression.
      expr <- base::substitute(expr)
      
      # Execute the expression in a reactive context.
      expr
    }

    moduleContentsUI <- function(id, title, core_env, ...) {
      # Create the namespace.
      ns <- shiny::NS(id)
      # Get the elements; THESE MUST BE bsCollapsePanel
      elements <- eval(substitute(...))
      
      div(
        fluidRow(
          column(6,
            selectInput(ns('module_select'),
              label='Select module',
              multiple = FALSE,
              choices = core_env$rval$module_choices,
              selectize = TRUE)
          ),
          column(2,
            selectInput(ns('module_select_category'),
              label='Category',
              multiple = FALSE,
              choices = core_env$rval$module_tags_category,
              selectize = TRUE)
          ),
          column(2,
            selectInput(ns('module_search_workflow'),
              label='Workflow',
              multiple = FALSE,
              choices = core_env$rval$module_tags_workflow,
              selectize = TRUE)
          ),
          column(2,
            selectInput(ns('module_select_function'),
              label='Function',
              multiple = FALSE,
              choices = core_env$rval$module_tags_function,
              selectize = TRUE)
          )
        ),
        fluidRow(
          column(4,
            h4('Options')
            #optionElements
          ),
          column(8,
            h4('Preview')
            #previewElements
          )
        )
      )
    }

    server <- function(input, output, session) {
      output$ui_core <- renderUI({
        ns <- session$ns
        moduleCoreUI('granatum_core', 'Core', core_env,
          actionButton(ns('button'), 'Change message')  
        )
      })
      
      output$ui_module <- renderUI({
        ns <- session$ns
        moduleContentsUI('module', 'Module', core_env)
      })
      
      observeEvent(input$button, {
        browser()
      })
      
      callModule(moduleCoreServer, 'core', core_env=core_env, expr= 
        observeEvent(input$button, {
          coreStatusText('Help!', core_env, session, 'warning')
        })
      )
    }

    shinyApp(ui, server)

This is a self-contained example of an app that wants to nest modules and also pass on arbitrary elements and handlers into the `callModule` function as well. For some reason, even though the correct handler ID is specified for the UI and supposedly the `callModule`, the button inside of` `callModule` gives no response.

**Comment by wch** [comment]
I think you need `eval(expr)` in your `moduleCoreServer` function.
