### ISSUE TITLE
imageOutput does not show PDF in Chrome

### ISSUE THREAD

**Issue by scottkall** [rstudio/shiny#1084]
I used the following code to make a PDF show up in a Shiny app, but it only works in the RStudio viewer and a Safari browser, not in Chrome. My Chrome version is 47.0.2526, but I tested on two different computers. Could be a Chrome issue. May try to render PDF as PNG or use an inline viewer as a non-ideal workaround.

```r
# from server.R:
output$line_report_PDF <- renderImage({
    PDFfile="www/test.pdf"
    print(paste("file exists:",file.exists(PDFfile)))
    list(src = PDFfile)
  }, deleteFile = FALSE)

# from ui.R:
tabPanel("Line Report",
    basicPage(
        imageOutput("line_report_PDF")
    )
)
```

**Comment by shrektan** [comment]
Why not use an iframe directly, instead of render image?


发自网易邮箱大师
在2016年01月18日 11:53，scottkall 写道:

I used the following code to make a PDF show up in a Shiny app, but it only works in the RStudio viewer and a Safari browser, not in Chrome. My Chrome version is 47.0.2526, but I tested on two different computers. Could be a Chrome issue. May try to render PDF as PNG or use an inline viewer as a non-ideal workaround.

# from server.R:output$line_report_PDF<- renderImage({
    PDFfile="www/test.pdf"
    print(paste("file exists:",file.exists(PDFfile)))
    list(src=PDFfile)
  }, deleteFile=FALSE)

# from ui.R:
tabPanel("Line Report",
    basicPage(
        imageOutput("line_report_PDF")
    )
)

**Comment by scottkall** [comment]
Hi @shrektan, thanks much for the suggestion. My main reason for creating this issue was so the Shiny developers were made aware of different behavior of common functions in different browsers. I was wondering if this was known and also whether it is just typical behavior in Chrome.

From your suggestion I've done the following workaround. This creates fully zoomable versions of the PDFs, which will be fine, but just isn't what I was looking to do at the beginning.

```r
# from server.R
output$line_report_PDF <- renderUI({
    PDFfile="test.pdf"
    tags$iframe(
        src=PDFfile,
        width="100%",
        height="800px")
})

# from ui.R
uiOutput("line_report_PDF")
```

**Comment by shrektan** [comment]
@scottkall I tried your code. It doesn't work in Chrome, but fine in Safari.

**Comment by wch** [comment]
This is just how Chome behaves: it won't display PDFs in `<img>` tags. I know Safari will do it, and I think that Firefox will not. I assume you're running on a Mac, which would explain why it displays in the RStudio viewer -- on Mac, RStudio uses the same rendering engine as Safari.

You can test it browser support by creating and viewing a simple web page like this:

```html
<html>
<body>
<img src = "file.pdf">
</body>
</html>
```
