### ISSUE TITLE
Progress Bars Associated with Reactive Blocks

### ISSUE THREAD

**Issue by kmader** [rstudio/shiny#1085]
For many of the shiny workflows I make, I chain reactive blocks together. It would be great if there was a ```status.reactive``` which could show indicate what it is doing with a progress message without having all the extra code hanging around with different progress bars

```r
status.reactive<-function(x,status="Loading...",...) {
  reactive({
    withProgress(message = status, value = 0, {
      x
    })
  },...)
}
```

**Comment by wch** [comment]
I think that function is a good idea for your situation, but it's not a common enough situation to add to Shiny itself.
