### ISSUE TITLE
no leaflet maps in Shiny 0.13

### ISSUE THREAD

**Issue by jacob-ogre** [rstudio/shiny#1089]
I could not track down the cause, but I haven't gotten leaflet maps to render using Shiny 0.13 and there were no errors returned in R console.  (Unfortunately, I forgot to check the js console while I had 0.13 installed.)  When I rolled back to 0.12.2 the map rendered just fine.

**Comment by jcheng5** [comment]
Can you give us a repro case? That would be super helpful. Thanks...

**Comment by jacob-ogre** [comment]
It will be a few days before I can get to it...the app is in a private repo at the moment.  A minimal example using `bootstrapPage` works with 0.13, e.g., 
```
bootstrapPage(
    tags$style(type = "text/css", "html, body {width:100%;height:100%}"),
        leafletOutput("map", width = "100%", height = "100%")
)
```
but doesn't work with a vanilla app using `fluidPage` and `shinyUI`, e.g.,
```
shinyUI(fluidPage(
    tags$style(type = "text/css", "html, body {width:100%;height:100%}"),
        leafletOutput("map", width = "100%", height = "100%")
))
```
The server.R for both of the above is simply:
```
shinyServer(function(input, output) {
    output$map <- renderLeaflet({ 
        leaflet() %>%
            setView(lng=-95, lat=38, zoom = 4) %>%
            addTiles()
    })
})
```
Unfortunately my app, which includes shinydashboard and many other packages, does not with 0.13 but does with 0.12.2.  Here's the js console output after reinstalling 0.13 and running my app:
```
2jquery.min.js:2 Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'destroy'

shiny.min.js:3 Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '3' is not a valid attribute name.

2leaflet.js:1628 Couldn't find map with id map

http://127.0.0.1:6993/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

3leaflet.js:1628 Couldn't find map with id map
```

Sorry I don't have more to to provide at the moment.

**Comment by jcheng5** [comment]
In your `output$defenders` definition, you've got a stray `a()` call in there, around the href argument. That is causing a JavaScript error to be thrown, so that the Leaflet code never even gets called.

There are also unrelated errors happening in JavaScript, one about a shinyBS tooltip being destroyed before it is initialized, and the other because you have an observer calling fitBounds() with null values. See [req](http://shiny.rstudio.com/articles/req.html) for a fix for the latter problem.
