### ISSUE TITLE
using index.html as UI doesn't work with eventReactive

### ISSUE THREAD

**Issue by natnguyenau** [rstudio/shiny#1092]
Hi Shiny admins/users

I've been struggling with this issue in the last 2 days and nothing seems to work for me so far. I'm creating a web app which allows users to input a search phrase then some actions would be carried out.

eventReactive works fine for me on normal UI.R but when I tried to use index.html it doesn't work. My code is below:

Server.R:
```
   new_search <- eventReactive(input$searchButton, {
            search_term <<- input$searchText
   test <- data.frame()
  })
```

Index.html
```
 <!-- Search bar -->
      <form class="sidebar-form">
                    <div class="input-group">
                      <input id="searchText" type="text" class="form-control" placeholder="Ask me anything..">
                      <span class="input-group-btn">
                        <button id="searchButton" type="button" class="btn btn-flat action-button">
                          <i class="fa fa-microphone"></i>
                        </button>
                      </span>
                    </div>
      </form>
```
 
Please help :( Thank you so much

**Comment by jcheng5** [comment]
That should work, I did something similar last week. Is there a submit button anywhere on the page by chance? Either a <button type="submit"> or <input type="submit">? If so can you try removing it?

**Comment by jcheng5** [comment]
GitHub stripped part of my comment. Either an input type="submit", or button type="submit", is what I tried to say.
