### ISSUE TITLE
updateRadioButtons errors if numeric vector used as choices

### ISSUE THREAD

**Issue by pete900** [rstudio/shiny#1093]
There seems be a problem with using multiple updateRadioButtons, see my question here:

[http://stackoverflow.com/questions/35056668/update-two-sets-of-radiobuttons-shiny/35061269?noredirect=1#comment57845550_35061269]

In short, if there are more than one set of radioButtons to update reactively you must explicitly state selected=" " in the updateRadioButtons argument. This isn't a big deal but it took me a day to figure out why I couldn't seem to render to sets of radioButtons reactively.

**Comment by jcheng5** [comment]
Updated the title--it's not about the multiple updates, it's because a JS error occurs if the `choices` argument isn't a character vector. We should probably cast both `choices` and `selected` (possibly with a warning, in case you were expecting a numeric value to come back in the input object).

**Comment by mczapanskiy-usgs** [comment]
I just ran into this problem, too. Had a radio button input with numeric options (e.g. `choices = c(a = 1, b = 2)`) and updateRadioButtons failed silently. Took me a day to figure it out as well.
