### ISSUE TITLE
Potential bug in data transport from JS to R using Shiny.onInputChange

### ISSUE THREAD

**Issue by ramnathv** [rstudio/shiny#1098]
Here is a repro case. I am trying to return an array of objects back to R, which I would have expected to be unpacked either to a list or a data frame. However, it seems to be getting unpacked to a vector. Am I doing something wrong, or is this behavior a bug?

```r
library(shiny)
ui <- fluidPage(
  p("Hello World"),
  textOutput("out"),
  tags$script("
    var dat = 'hello'
    $('p').on('click', function(){
      console.log('Hello')
      var d = [{x: 1, y: 2}, {x: 3, y: 4}]
      //var d = {x: 1, y: 2}
      Shiny.onInputChange('dat', d)
    })            
  ")
)

server <- function(input, output, session){
  output$out <- renderText({
     if (!is.null(input$dat)){
       print(input$dat)
       print(str(input$dat))
       capture.output(input$dat)
     } else {
       "Click to Reveal"
     }
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by wch** [comment]
It's being flattened by this line of code:
https://github.com/rstudio/shiny/blob/686390c/R/server.R#L257

I don't think it's a bug -- more like "accessing a not-really-public API".

If memory serves, you could use `registerInputHandler("myInputType", ...)` and, from the Javascript side, call `onInputChange('dat:myInputType', d)` -- but this isn't completely public stuff.

Are you avoiding writing a fully-fledged input binding for this use case?

**Comment by ramnathv** [comment]
Thanks @wch. That makes sense. I was just trying to return a selection of points from a mouseover on an interactive plot. I could just return an array of ids, but it was more natural to return an array of objects. Not a show-stopper, but this is good to know.

**Comment by ramnathv** [comment]
So, question. In the long run what do you see as a natural mechanism to pass data back from the client to the server, when dealing with interactive visualizations and related events (mouseover, click, selection etc.) This use case is going to be a very common one, so I am curious what we should expect.

**Comment by fbreitwieser** [comment]
I also just came across this. It would be very convenient for me (and more what I would expect) if Shiny server receives a list. 

Note that the following blog post - which albeit old is still in the top search results, and also mentioned in some issues here (#1103 #585) - claims that this does happens:

https://ryouready.wordpress.com/2013/11/20/sending-data-from-client-to-server-and-back-using-shiny/

> The two functions also do a good job passing more complex JS or R objects. If you modify your code to send a JS object to shiny, it will be converted into an R list object on the server side. Let’s replace the JS object we send to the server (in ui.R) with following lines. On the server side, we will get a list.
```
document.getElementById("mydiv").onclick = function() {
  var obj = {one: [1,2,3,4],
             two: ["a", "b", "c"]};
  Shiny.onInputChange("mydata", obj);
};

```

**Comment by harveyl888** [comment]
One workaround that I sometimes use is to return a JSON object.
For @ramnathv's code if you return

`Shiny.onInputChange('dat', JSON.stringify(d))`

then 

`jsonlite::fromJSON(input$dat)`

returns a data frame.  In the wordpress example above it will return a list containing two vectors.

**Comment by daattali** [comment]
I agree with @ramnathv , I'm building my very first htmlwidget right now and I also already came across a similar situation where I wanted to pass data from a visualization back to the server (I also opened a similar bug #1247 )

**Comment by wch** [comment]
I think my answer above and Joe's answer in #1247 address the issue.
