### ISSUE TITLE
Potential bug in runApp(launch.browser = FALSE) 

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1101]
Suppose I'm in RStudio and the default app launcher is set to the Viewer Pane.  If I use `runApp(app)` then the app runs in the viewer pane. If I use `runApp(app, launch.browser = TRUE)` then the app runs in my browser. But if I use `runApp(app, launch.browser = FALSE)` then the app doesn't launch in my browser or in the viewer pane. I can still access it if I type in the URL into my browser manually.  But I would assume that `launch.browser = FALSE` would be the same as just `runApp()` without that argument at all.

Maybe this is intended behaviour?  If it is, it seems confusing that `runApp()` vs `runApp(launch.browser = TRUE)` vs `runApp(launch.browser = FALSE)` all have different behaviour

**Comment by jcheng5** [comment]
This is the intended behavior. Look at the default argument--it's a getOption call that defaults to interactive(). I wouldn't equate that with false. The possible values are TRUE for external browser, FALSE for don't launch anything, or a function if you want to do something special. And the default is to look for an option set by RStudio or potentially another IDE, and if not, then interactive().
