### ISSUE TITLE
Bringing value from js to server

### ISSUE THREAD

**Issue by natnguyenau** [rstudio/shiny#1103]
Hi there,

I'm writing a Shiny App with UI entirely using HTML. I want to pass some data on whether an user has clicked a button and then create a log for this. My code doesn't seem to work in passing variable for JS to R. Could someone help me please?

**HTML**
`    <script src="logging_java.js"></script>  `

**logging_java.js**
```
$(document).ready(function() {
    $('.fa-remove').click(function(){
    target_num = $(this).attr('id').split('-')[1];
    plot_id = '#plot_'.concat(target_num);
    tasktitle = $(plot_id).children('div').attr('id')
    Shiny.onInputChange("delete_chart", tasktitle);
    });
});

```
**server.R**
```
  output$out <- renderText({
    delete_test <<- input$delete_chart
  })
```

**Comment by natnguyenau** [comment]
Could someone please help me with this? I've been trying to solve this for 2 days without luck. Thank you so much

**Comment by Stophface** [comment]
Check that out: https://ryouready.wordpress.com/2013/11/20/sending-data-from-client-to-server-and-back-using-shiny/ Might help you!

**Comment by wch** [comment]
Shiny doesn't get initialized immediately on document load; it happens after the minimal delay (1ms):
https://github.com/rstudio/shiny/blob/1f823d2a1b0110b175832177e248b71183257209/srcjs/init_shiny.js#L462-L466

You can listen for the `shiny:connected` event:

```js
$(document).on('shiny:connected', function(event) {
   // Do stuff here
})
```
