### ISSUE TITLE
[Conflict] Shiny & jQuery-ui

### ISSUE THREAD

**Issue by The-Dub** [rstudio/shiny#1107]
Hello everybody,

I wanted to report a bug/conflict I encountered between jQuery ui and shiny date inputs (dateInput and dateRangeInput).  For a reason that i don't fully understand, if you load jquery ui and have a date inputs, the server will not load, and won't return any error message. This drove me crazy for a minute because i couldn't understand what was going on here.

A quick turnaround is to download a version of jQuery without the daterange widget, and everything will work fine. Below a quick snippet of code that illustrate the problem.

```
library(shiny)

ui <- fluidPage(
  # singleton(tags$head(tags$script(src="//code.jquery.com/ui/1.11.4/jquery-ui.js"))), #comment /uncomment out this line
  dateRangeInput("ricky", "this is a daterangeinput"),
  uiOutput("bobby")
  
)

server <- function(input, output) {
  output$bobby <- renderUI({
    HTML('<p>this will render if server.R loads properly</p>')
  })
}

shinyApp(ui=ui, server=server)
```

I don't really know if it's a bug per se or an expected behavior, so if anybody has more information on that, i'll take it!

**Comment by wch** [comment]
Unfortunately, there's a conflict between jQuery UI's datepicker and Shiny's datepicker, which also comes up here:
https://github.com/rstudio/shiny/blob/68b85bd/R/jqueryui.R#L83-L86


We don't really have a good solution at this point.

**Comment by The-Dub** [comment]
Ok, didn't know that!
Now, I do, thanks for the explanation. :+1:
