### ISSUE TITLE
using req to pause estimation while still showing previous results

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#1108]
@jcheng5 We discussed `req` at the shiny dev conference and you mentioned that a "4-line PR" would allow pause-estimation with `req` while still showing the output from the last run. It that doesn't ring a bell ... please take a look at the link below and click the `pause estimation` check-box. What would be great is if the previous output could be shown until the user un-checks the pause estimation box again.

http://vnijs.rady.ucsd.edu:3838/analytics/?SSUID=de2e9b641e

Thanks

**Comment by daattali** [comment]
@vnijs I was curious so I clicked the link and couldn't find that checkbox. Now going to that session URL will go back to where I went... just FYI that link is now "outdated", oops.

**Comment by vnijs** [comment]
Addressed in https://github.com/rstudio/shiny/pull/1117#issuecomment-187276597
