### ISSUE TITLE
is shiny:busy session based?

### ISSUE THREAD

**Issue by shrektan** [rstudio/shiny#1111]
Hi, thanks for the new feature of [JavaScript Events](http://shiny.rstudio.com/articles/js-events.html).

It seems that the JS events is session based, even for events like `shiny:busy`?

I'm trying to build a status bar for a shiny app, whenever the server is busy, other users would get informed. However, I find when user B causes server busy, user A will receive no info.

Is it a desired feature?

**Comment by shrektan** [comment]
Can anyone give me some hint about this?  Thanks :smile:

**Comment by jcheng5** [comment]
Sorry, the built-in JS events don't support this. There are also cases where it wouldn't help, such as when a user arrives while the server is busy, the HTML won't even load.

**Comment by shrektan** [comment]
thanks, I get it. Just think it's better have users informed the server is busy, in case they click multiple times on the inputs…

I'll see if I can find other solution in the Google discuss or stackoverflow.

**Comment by jcheng5** [comment]
Yeah, that feedback is fair.
