### ISSUE TITLE
 Cyrillic does not work in code

### ISSUE THREAD

**Issue by Lapchenkov** [rstudio/shiny#1113]
Cyrillic does not work in ui.R in  shiny_0.13.0.   version shiny_0.12.2. works fine

**Comment by wch** [comment]
Can you supply a simple reproducible example, and the output of `sessionInfo()`?

**Comment by Lapchenkov** [comment]
Hi! 

sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows XP (build 2600) Service Pack 3

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251   
[3] LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C                   
[5] LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.13.0 arules_1.3-1 Matrix_1.2-3

loaded via a namespace (and not attached):
 [1] R6_2.1.2        htmltools_0.3   tools_3.2.3     Rcpp_0.12.3     grid_3.2.3     
 [6] digest_0.6.9    xtable_1.8-2    httpuv_1.3.3    mime_0.4        lattice_0.20-33

ui.R in attach

and error is:
ERROR: C:\Documents and Settings\Lapchenkov_d\Мои документы\L\pyton\R\work\TS/ui.R:20:70: unexpected INCOMPLETE_STRING
19:                             column(3,
20:                                    selectInput("sel_rtk", label = h5("

from this part start cirilic text:

column(3,
                                   selectInput("sel_rtk", label = h5("Выбирите РТК"), 
                                               choices = c("Москва", "Челябинск"
[ui.zip](https://github.com/rstudio/shiny/files/133770/ui.zip)

), selected = 1))

**Comment by wch** [comment]
For the record, when I run this with Shiny 0.12.2 in Windows, it runs but I get this warning about UTF-8. Do you see that warning when you run your app with Shiny 0.12.2?

```
> devtools::install_version('shiny', '0.12.2')
> library(shiny)
> packageVersion('shiny')
[1] ‘0.12.2’
> runApp()

Listening on http://127.0.0.1:7971
Warning in checkEncoding(file) :
  The file "Z:\cyrillic/ui.R" is not encoded in UTF-8. Please convert its encoding to UTF-8 (e.g. use the menu `File -> Save with Encoding` in RStudio). See http://shiny.rstudio.com/articles/unicode.html for more info. Falling back to the encoding "native.enc".
```




When I run it with Shiny 0.13.0:

```
> install.packages('shiny')
> library(shiny)
> packageVersion('shiny')
[1] ‘0.13.0’
> runApp()

Listening on http://127.0.0.1:4758
Warning: invalid input found on input connection 'Z:\cyrillic/ui.R'
Warning: Error in parse: Z:\cyrillic/ui.R:20:70: unexpected INCOMPLETE_STRING
19:                             column(3,
20:                                    selectInput("sel_rtk", label = h5("
                                                                         ^
Stack trace (innermost first):
    1: runApp
Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
  Z:\cyrillic/ui.R:20:70: unexpected INCOMPLETE_STRING
19:                             column(3,
20:                                    selectInput("sel_rtk", label = h5("
                                                                         ^

                                                                         ^
```

The `sessionInfo()` (this is with a US locale, not Russian):

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.13.0

loaded via a namespace (and not attached):
[1] R6_2.1.2      htmltools_0.3 tools_3.2.3   Rcpp_0.12.3   digest_0.6.9 
[6] xtable_1.8-2  httpuv_1.3.3  mime_0.4     
```

First, you should re-save the file with UTF-8. If you're using RStudio, select File -> Save with encoding,  and choose UTF-8. Again, please let me know if you do (or don't) get the UTF-8 warning when running your app.

That said, Shiny should not error if the input file is saved with a non-UTF-8 encoding, so I'll look into that.

**Comment by wch** [comment]
@yihui I think this is related to #968. Could we at least reinstate the message about saving as UTF-8?

**Comment by Lapchenkov** [comment]
Thank you! I will try in Friday  (Russia ) and send result for you.

**Comment by yihui** [comment]
Yes, after #968, it is **required** that the Shiny app scripts (such as ui.R / server.R) are encoded in UTF-8. This is documented in the article http://shiny.rstudio.com/articles/unicode.html. I have added a warning message in #1116 if the input is not encoded in UTF-8.

**Comment by Lapchenkov** [comment]
thank you!  with UTF-8 works fine.
