### ISSUE TITLE
GEOS C library is outdated – please update

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/shiny#1114]
As several users have [already pointed out](https://groups.google.com/forum/#!topic/shinyapps-users/E1tWRLaU3kM), the version of the GEOS C library that Shinyapps.io uses is out of date (GEOS runtime version: 3.2.2-CAPI-1.6.2). This library is used by the `rgeos` package and without GEOS version > 3.3 the following error is returned when apps are run by the Shiny server:
`ERROR: No UnaryUnion in this version of GEOS`

Can we get the latest version of GEOS (3.4.2-CAPI-1.8.2 r3921) installed in the Shiny server?

**Comment by jcheng5** [comment]
Thanks for the comment. This issue tracker is for the shiny R package, so I'm going to close the issue; the shinyapps-users list you also posted to is the right place to send this feedback.
