### ISSUE TITLE
stopApp() not killing R process upon closing browser window 

### ISSUE THREAD

**Issue by jinhseok** [rstudio/shiny#1118]
All of my apps on shinyapps.io appear to keep running for at least 10 minutes after closing out of the browser window running the app (according to my shinyapps.io dashboard). This is problematic because it's eating up all my active hours. I embedded the following code in my server.R file, but it doesn't seem to make a difference. Am I doing something wrong here or is there an issue with how stopApp() works on shinyapps servers? Thanks.

shinyServer(function(input, output, session) {
  session$onSessionEnded(function() {
    stopApp()
    #q() #tried this too and it didn't work either
  })
})

**Comment by jcheng5** [comment]
This question is better posed to the [shinyapps-users group](https://groups.google.com/forum/#!forum/shinyapps-users). But my understanding is that while your code is indeed killing the R process, the instance-hours is not tied to the R process specifically but the container (akin to a virtual machine) in which the R process runs.

I believe you can shorten the default 15 minute window from your application's settings panel at shinyapps.io; look for the "Instance idle timeout" setting (the minimum is 5 minutes).
