### ISSUE TITLE
install.packages('Rsymphony')

### ISSUE THREAD

**Issue by arjn1472** [rstudio/shiny#1119]
Error While deploying application:
** package �Rsymphony� successfully unpacked and MD5 sums checked
Cannot find SYMPHONY libraries and headers.
See <https://projects.coin-or.org/SYMPHONY>.
ERROR: configuration failed for package �Rsymphony�

**Comment by wch** [comment]
This issue tracker is for this Shiny package itself. If you're deploying to shinyapps.io, the right place to ask is the shinyapps-users list:
https://groups.google.com/forum/?hl=en#!forum/shinyapps-users
