### ISSUE TITLE
Suppress error messages

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#1123]
For security reasons, have an option to prevent any raw error messages from getting to the client--make them sanitized. Raw error messages can contain file paths, internal hostnames, argument values, and sometimes even source code snippets.

(Let the user throw "trusted" exceptions and turn all other exceptions into generic exceptions?)

Currently you can work around this by throwing a generic exception in `options(shiny.error = function() { ... })` but that means even logging doesn't occur (you can't get the error from within shiny.error--seems perverse, but it's modeled on `options(error)`).

We should at least have shiny.error functions with at least one argument, be passed the error. This would allow a complete workaround.

We should also consider building our own version of this and sticking it directly into our server products, so you can opt into this behavior across an entire server (or override on a per-app basis) with a config file.

Ref: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/shiny-discuss/FyMGa2R_Mgs/FNyusgdxBgAJ

cc @benb111

**Comment by jcheng5** [comment]
Places to test: downloadHandler, ui.R itself

**Comment by bborgesr** [comment]
Closed via #1156
