### ISSUE TITLE
Shiny and Jsonlite

### ISSUE THREAD

**Issue by felloumi** [rstudio/shiny#1124]
Hello,
Running a shiny app using Rstudio with R.3.2.2, I got the following message:

Listening on http://127.0.0.1:4654
Note: the specification for S3 class “AsIs” in package ‘jsonlite’ seems equivalent to one from package ‘BiocGenerics’: not turning on duplicate class definitions for this class.

The app is not working. I am only using the packages: Limma, gplots, oligo , geneplotter, pd.mogene.2.0.st , mogene20sttranscriptcluster.db and DT.

I'll appreciate your help.

Thanks,
FE

**Comment by wch** [comment]
This sounds like a conflict between jsonlite and one of those other packages. cc @jeroenooms

**Comment by jeroenooms** [comment]
I guess both packages have `setOldClass("AsIs")`. It should be harmless though. What error do you get?
