### ISSUE TITLE
problems with shiny / diveRsity

### ISSUE THREAD

**Issue by ebegeebege** [rstudio/shiny#1127]
I am trying to start package diveRsity but I get the following message missing function "progressInit"; any suggestion to overcome this issue?:
Thanks,

Warning: Error in tag: could not find function "progressInit"
Stack trace (innermost first):
    54: tag
    53: tags$div
    52: div
    51: mainPanel
    50: tag
    49: tags$div
    48: div
    47: tag
    46: tags$div
    45: div
    44: tagList
    43: attachDependencies
    42: bootstrapPage
    41: pageWithSidebar
    40: shinyUI
     1: runApp
Error in tag("div", list(...)) : could not find function "progressInit"

**Comment by wch** [comment]
Can you supply a small reproducible example?

**Comment by ebegeebege** [comment]
I just installed the package as described by the developer (http://diversityinlife.weebly.com/diversity-online.html) but I can't even load the infile.
Thank you

> library("shiny", lib.loc="C:/Program Files/R/R-3.2.3/library")
> setwd("C:/Users/enriqueb/diveRsity")
> runApp(getwd())

Listening on http://127.0.0.1:5700
Warning: Error in tag: could not find function "progressInit"
....

**Comment by wch** [comment]
It's possible you need to install a newer version of Shiny.

If that doesn't fix it, this sounds like an issue you need to take up with the diveRsity developers.

**Comment by ebegeebege** [comment]
I downloaded the latest version of shiny, I am afraid that it may be a problem in diveRsity.
Thanks,
