### ISSUE TITLE
Upload Shiny App to shinyapps.io in Showcase Mode

### ISSUE THREAD

**Issue by jrosen48** [rstudio/shiny#1131]
When trying to upload a Shiny App to shinyapps.io in Showcase mode, I included a text file named DESCRIPTION (no extension) as follows when publishing the app to shinyapps.io:

```
Title: Hello Shiny!
Author: RStudio, Inc.
AuthorUrl: http://www.rstudio.com/
License: GPL-3
DisplayMode: Showcase
Tags: getting-started
Type: Shiny
```

However, the following error is returned:

```
Preparing to deploy application...DONE
Uploading bundle for application: 88219...Error in readDcf(file.path(project, "DESCRIPTION"))[, "Package"] : 
  subscript out of bounds
Calls: <Anonymous> ... suppressMessages -> withCallingHandlers -> <Anonymous> -> unname
Execution halted
```

[This Google Groups thread](https://groups.google.com/forum/#!topic/shinyapps-users/xq-p2_nTPAE) seems to suggest the same problem. I asked a [Stack Exchange question about it here](http://stackoverflow.com/questions/35928758/upload-shiny-app-to-shinyapps-io-in-showcase-mode).

**Comment by wch** [comment]
Could you file it in the [shinyapps repo](https://github.com/rstudio/shinyapps/issues)? You should also include the output of `sessionInfo()`, or better yet, `devtools::session_info()` -- that'll help diagnose the problem.

**Comment by jrosen48** [comment]
Done.
