### ISSUE TITLE
[Feature Request] Dynamically duplicating Modules

### ISSUE THREAD

**Issue by ziyadsaeed** [rstudio/shiny#1135]
Modules come in two parts one part to add to the UI function and another to the server function (callModule). If that same module has to be used twice in the app it has to be added twice manually. There doesn't seem to be any way to dynamically duplicate a module. For eg duplicate a module 10 times, or when a button is clicked.

The visual below will clarify. 

![image 2](https://cloud.githubusercontent.com/assets/12503225/13887175/29e2bcce-ed5c-11e5-8dd7-4fa6cd03a6ab.png)

Or if adding/duplicating different modules on demand
![image 1](https://cloud.githubusercontent.com/assets/12503225/13887189/3342abc6-ed5c-11e5-909f-f9f58663c595.jpg)

This feature request is the outcome of this [stackoverflow question](http://stackoverflow.com/questions/36043032/dynamically-adding-modules-in-shiny)

**Comment by ziyadsaeed** [comment]
on going discussion with JoeCheng suggest a new [appendUI](https://groups.google.com/d/msg/shiny-discuss/BMZR3_MH0S4/ZZp5hdIGAwAJ) is being discussed.

**Comment by bborgesr** [comment]
Happy to report that an `insertUI` and a `removeUI` functions are now available on the master branch. Hopefully, this is what you need to get your app working the way you want it :) [Here's](https://groups.google.com/forum/#!topic/shiny-discuss/PsmyRgjiLkU) a link to the announcement on shiny-discuss.
