### ISSUE TITLE
update*Input function examples should use shinyApp()

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#1137]
The examples for `update*Input` functions use the outdated `shinyServer(function(input, output, session))` syntax. They should be changed to use `shinyApp()`, which also has the benefit of yielding a full working example.

It would be nice if we could also switch to `session = getDefaultReactiveDomain()`, but since it's the first argument, this won't make a difference in usability for most users.

**Comment by daattali** [comment]
Agreed about the session issue, too bad that's going to cause enormous regression issues if you just move the parameter to not be the first.  Of course you could do the @hadley solution and just start a `shiny2` package :)
