### ISSUE TITLE
Accessing shinyViewerType option

### ISSUE THREAD

**Issue by carlganz** [rstudio/shiny#1146]
Hello,

I am distributing a shiny app as a package, and I want to ensure that the app is opened in a new window within RStudio rather than using a browser or `rstudio::viewer`

It would appear when `attr(options("shiny.launch.browser")[[1]],"shinyViewerType")` equals 3 the shiny app will run in a window in RStudio like I want, but there doesn't appear to be a way for me to change the value of this attribute with code since `attr(options("shiny.launch.browser")[[1]],"shinyViewerType") <- 3` spits out an error "target of assignment expands to non-language object"

I get the same issue if I replace `options` with `getOption`. Is there a way to set the "shinyViewerType" attribute of the "shiny.launch.browser" option within your code? 

Thanks

**Comment by wch** [comment]
I don't know for sure about how RStudio handles the option, so I can't comment on that. But as for your immediate problem, modifying the value of the option, I think you need to get the option, modify it, and then save it back. Something like:


```R
x <- getOption("shiny.launch.browser")
attr(x, "shinyViewerType") <- 3
options(shiny.launch.browser = x)
```

**Comment by carlganz** [comment]
Thanks @wch. After some more investigation, I realize that the "shiny.launch.browser" option is a function and the attribute isn't what determines how Shiny is displayed in RStudio. [The RStudio source code](https://github.com/rstudio/rstudio/blob/d5ab5dfa53c057a289179826a94622b715146e79/src/cpp/session/modules/SessionShinyViewer.R) shows the option is set to one of three functions, so you can force an app to run in an RStudio window with this hack:
```{r}
x= function(url) {
  invisible(.Call("rs_shinyviewer", url, getwd(), 3))
}
# Create ui and server
# Set Rstudio to run external
shinyApp(ui = ui, server = server) # runs externally
# run with hack
shinyApp(ui = ui, server = server,options=list(launch.browser=x)) # runs in RStudio
```
This is clearly an RStudio issue and not a shiny issue so I'll go ahead and close this.
