### ISSUE TITLE
Using an https source for an image doesn't work in the RStudio viewer

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1148]
For example, the following tag doesn't show up in the RStudio viewers

`img(src = "https://www.rstudio.com/wp-content/uploads/2014/03/blue-125.png")`

This never bothered me in shiny apps, but now that we have gadgets+addins that run in RStudio, I'm noticing this more.  I don't plan on having production code use remote URLs, but for development purposes I often want to use images I find online

**edit**: it looks like not all images are affected. Maybe it's http vs https

**Comment by jcheng5** [comment]
Huh, I would expect all images to be affected--this is a security feature of RStudio.

**Comment by jcheng5** [comment]
OK @daattali I think we'll need to see the specific code that's working/not working for you

**Comment by daattali** [comment]
The code I have in the first comment still doesn't work for me inside RStudio

```
library(shiny)

ui <- fluidPage(
  img(src = "https://www.rstudio.com/wp-content/uploads/2014/03/blue-125.png")
)

server <- function(input, output, session) {
  
}

shinyApp(ui = ui, server = server)
```

It works with `http`, and with `https` it works in a browser but not in RStudio

**Comment by wch** [comment]
With RStudio 0.99.1288 and Shiny 0.13.2, I can see images that are from http, but not those that are https.

http:
![image-http](https://cloud.githubusercontent.com/assets/86978/17823936/a4c790a4-6624-11e6-87e7-0d7d92a81a41.png)


https:
![image-https](https://cloud.githubusercontent.com/assets/86978/17823940/abf9fb3c-6624-11e6-892b-07d90004c167.png)

**Comment by wch** [comment]
This is confirmed as a bug in the IDE by @jmcphers, so I'll close this issue.

**Comment by yonicd** [comment]
i just ran into the same type of problem, but not only in image files. i am able to GET `XMLHttpRequest()` on mac/unix but not in windows rstudio internal viewer.

applied in [jsTree](https://github.com/yonicd/jsTree) package

```

var previewDiv = document.createElement("DIV");
var previewPre = document.createElement("PRE");
previewPre.id='preview';
previewDiv.appendChild(previewPre);
document.body.appendChild(previewDiv);

//example uri
var uri='https://raw.githubusercontent.com/tidyverse/reprex/master/cran-comments.md?raw=true';
loadXMLDoc(uri);

function loadXMLDoc(uri) {
  var xmlhttp = new XMLHttpRequest();
  xmlhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      document.getElementById("preview").innerHTML =
      this.responseText;
    }
  };
  xmlhttp.open("GET", uri, true);
  xmlhttp.send();
}

```
