### ISSUE TITLE
Can't install shiny in R 3.2.3 on CentOS 7.2

### ISSUE THREAD

**Issue by devharsh** [rstudio/shiny#1154]
> install.packages('shiny')
Warning: unable to access index for repository https://mran.revolutionanalytics.com/snapshot/2016-01-01/src/contrib:
    Couldn't connect to server

Warning message:
package ‘shiny’ is not available (for R version 3.2.3)

**Comment by wch** [comment]
This sounds like it's not a problem with Shiny, but with the Revolution Analytics MRAN server.

**Comment by kantasa** [comment]
Hi ,

I'm using Rstudio version 3.2.3 and I have installed shiny package.  while running Shiny app, I'm getting below error.
RUNNINH SHINY APPLICATIONS REQUIRES INSTALLATION OF AN UPDATED VERSION OF SHINY PACKAGE.

I clicked on yes, installing packages and I didn't get any result. every time I run shiny app, I'm getting the same message.

Please help me. I'm very new to Rstudio world.

Many thanks in advance.
Satheesh K

**Comment by devharsh** [comment]
try installing it manually with install.packages command
