### ISSUE TITLE
Feature request: Drag and drop file upload

### ISSUE THREAD

**Issue by fbreitwieser** [rstudio/shiny#1155]
It would be great if it was possible to drag and drop and drop files onto a Shiny web application to upload them. 

This requires to establish a drop zone that listens to events dragenter, dragover and drop.
(https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications)

Link to Shiny user group message: https://groups.google.com/forum/#!topic/shiny-discuss/19C5eQ2neQ8

**Comment by fbreitwieser** [comment]
An implementation: http://stackoverflow.com/questions/36108705/drag-and-drop-data-into-shiny-app

**Comment by wch** [comment]
When dragging a file, it should show some visual indication when over the fileInput, like a change of color and/or some text that says "drop file here". If the file is dragged and the user drops it outside of  the fileInput, then it should prevent the browser from opening the file; nothing should happen.

**Comment by wch** [comment]
Closed by #1782.
