### ISSUE TITLE
Can't install shiny in R 3.2.3 on CentOS 7.2

### ISSUE THREAD

**Issue by devharsh** [rstudio/shiny#1162]
> install.packages('shiny', repos='http://cran.rstudio.com/')
Warning: unable to access index for repository http://cran.rstudio.com/src/contrib:
    Couldn't connect to server

Warning message:
package ‘shiny’ is not available (for R version 3.2.3) 
>

**Comment by daattali** [comment]
Are you able to install other packages? This error makes it sound like there was a connection problem with the repository, not a shiny issue
