### ISSUE TITLE
New version of shiny has issues

### ISSUE THREAD

**Issue by debsush** [rstudio/shiny#1164]
Following issues being faced:
1. Installed the latest version of shiny and now the runApp command opens the pop-up window for a few second and then automatically closes it.  This issue was not prevalent in the earlier versions.  I am using in EC2.
2. devtools::install_github("rstudio/shiny") gives error "unloadNamespace("shiny") not successful. Forcing unload.
Error in get(Info[i, 1], envir = env)"
3. Also unable to reinstall the older versions like devtools::install_version("shiny", version = "0.12.0")
Error: Error in devtools::install_version("shiny", version = "0.12.0") : 
  version '0.12.0' is invalid for package 'shiny'

Please help

**Comment by wch** [comment]
For 2, you simply need to restart R before installing. For 3, this is due to a new bug in devtools: hadley/devtools#1150.

As for the 1, we would need more information about the environment that you're running in.
