### ISSUE TITLE
Error when using runGitHub

### ISSUE THREAD

**Issue by GtheSheep** [rstudio/shiny#1167]
Error in untar2(filePath, list = TRUE) : incomplete block on file

When running from a private github repo, reproducible example found online:
https://groups.google.com/forum/#!topic/shiny-discuss/3ytmA8DMayQ

Many thanks for any help, happy to provide more details!

**Comment by jcheng5** [comment]
Sorry, private repos are not supported by runGitHub--you'll have to clone or download it yourself and then run it fron disk.

**Comment by nick-youngblut** [comment]
> Sorry, private repos are not supported by runGitHub--you'll have to clone or download it yourself and then run it fron disk.

Could this be revisited? It seems that runGitHub would just require a GitHub PAT, as [done for renv](https://rstudio.github.io/renv/articles/renv.html#authentication)
