### ISSUE TITLE
downloadHandler works in Chrome but not in Firefox

### ISSUE THREAD

**Issue by pvermees** [rstudio/shiny#1171]
I have created a very simple illustration of a problem that has been really bugging me in a much larger project. The demo contains a simple download button which works fine in Chrome but not in Firefox or Safari. Here's a live example of the problem:

https://pvermees.shinyapps.io/demo/

When I run the code offline, Firefox gives me the following error message: "The connection to ws://127.0.0.1:3094/websocket/ was interrupted while the page was loading."

Here's the self-contained example code (html-only ui):

index.html:

```
<html>
    <head>
        <link href="https://rawgit.com/rstudio/shiny/master/inst/www/shared/jqueryui/jquery-ui.css" rel="stylesheet"/>
        <script src="https://rawgit.com/rstudio/shiny/master/inst/www/shared/jqueryui/jquery-ui.js"></script>
        <script src="https://rawgit.com/rstudio/shiny/master/inst/www/shared/jquery.js"></script>
        <script src="https://rawgit.com/rstudio/shiny/master/inst/www/shared/shiny.js"></script>
        <script>
            $(function(){ $("#SAVE").button(); });
        </script>
    </head>
    <body>
        <a id="SAVE" class="shiny-download-link">Save</a>
    </body>
</html>
```

server.R:

```
library(shiny)

shinyServer(function(input,output,session){

    getPlot <- function(){
        plot(c(0,1),c(0,1),type='l')
    }

    output$SAVE <- downloadHandler(
        filename = 'test.pdf',
        content = function(file) {
            pdf(file=file)
            getPlot()
            dev.off()
        }
    )

});
```

**Comment by jcheng5** [comment]
You need to add `target="_blank"` to the anchor tag, otherwise navigating to the file download will leave the current page and kill the Shiny session that was going to provide the file download data.

**Comment by PaulinCharliquart** [comment]
Hi,

With latest version of shiny `1.7.5.1`, downloading pdf (using `downloadHandler `) does not work with edge but works with firefox.

Here a short snippet:

```
output$downloadReportPDF <- downloadHandler(
    filename = "report0.pdf",
    content = function(file) { 
      tempReport <- file.path(tempdir(), "report0.Rmd")
      file.copy("report0.Rmd", tempReport, overwrite = TRUE)
      output <- rmarkdown::render(tempReport, 
                        output_file = file,
                        output_format = "pdf_document",
                        params= params,
                        run_pandoc = TRUE,
                        envir = new.env(parent = globalenv())
          )
      file.copy(output, file) 
    }
  )

```

Any ideas how to resolve this?

thanks

**Comment by gadenbuie** [comment]
Hi @PaulinCharliquart, since this issue was closed 8 years ago, I'd recommend you start a new issue and link back to this one. When you do that, it would be very helpful if you could include a complete but minimal example that reproduces the error you're experiencing. We wrote an article with [some tips about creating a reproducible example](https://community.rstudio.com/t/shiny-debugging-and-reprex-guide/10001).
