### ISSUE TITLE
Warning: Error in checkName: Must use single string to index into reactivevalues

### ISSUE THREAD

**Issue by kmezhoud** [rstudio/shiny#1172]
Dear All,
I am having a warning message when my shiny app when is loading rda file. Before the function working well. I did not change any things in indicated functions by the warning message.
The message is coming from checkName function in reactive.R file.
 
Any suggestion?
Thanks

```
Listening on http://127.0.0.1:7190
Warning: Error in checkName: Must use single string to index into reactivevalues
Stack trace (innermost first):
    86: checkName
    85: [[.reactivevalues
    84: [[
    83: match
    82: %in%
    81: reactive .getdata [../base/bioCancerInit.R#122]
    70: .getdata
    69: renderText [../base/tools/data/manage_ui.R#442]
    68: func
    67: output$htmlDataExample
     1: runApp
```

**Comment by jcheng5** [comment]
I'd look at bioCancerInit.R line 122. You will probably find that whatever is between the double square brackets, is either `NULL` or a character vector of length > 1.

**Comment by jcheng5** [comment]
(If not, please reopen the issue with more info, thanks)
