### ISSUE TITLE
withProgress in Rmd with runtime: shiny prevents initial rendering

### ISSUE THREAD

**Issue by jjallaire** [rstudio/shiny#1173]
Using a `withProgress` call in an interactive documents results in no rendering of any content until the call to `withProgress` terminates. See the behavior of this example:

    ---
    title: "Untitled"
    output: html_document
    runtime: shiny
    ---

    ```{r, echo = FALSE}
    numericInput("rows", "How many cars?", 5)

    withProgress(message = 'Making plot', {
      for (i in 1:10)
        Sys.sleep(0.5)
    })

    renderTable({
      head(cars, input$rows)
    })
    ```

@jcheng5 This is the follow up to the discussion on withProgress in flexdashboard. If we can get this working then I think it's acceptable for shipping (some additional appearance tweaks would be desirable but not strictly required). @jmcphers You may have some insight based on your knowledge of interactive documents.

**Comment by jcheng5** [comment]
Isn't this the expected behavior? If you took the `withProgress` line away (so it just did the for-loop with the sleep) I believe you'd also get no content rendered until you exit the for-loop (actually until the entire document finishes rendering).

**Comment by jcheng5** [comment]
On the other hand, I'd expect moving the `withProgress` into the `renderTable` block would give you a nice experience.

**Comment by jjallaire** [comment]
Okay, sorry I don't fully understand the progress mechanism (thought that
the expression might have been evaluated later). I just took the progress
example off of the shiny dev center and tried it in an interactive
document: http://shiny.rstudio.com/articles/progress.html

The difference may be that in the ui.R case the UI "frame" has already
fully rendered.

So maybe we should just tell people that anything which takes a long time
at startup should go in render_delayed?

**Comment by jjallaire** [comment]
Okay, bad user on device :-\ 

I noticed that in the dev center example the code was in the renderPlot block. I'll try that.
