### ISSUE TITLE
updateDateInput

### ISSUE THREAD

**Issue by gmeurice** [rstudio/shiny#1179]
I 'm facing a problem with "updateDateInput" :

for example, while trying to update my dateInput with the value "2016-04-02" :

updateDateInput(session, "date.ddn" , label = NULL, min=NULL, max=NULL, value="2016-04-02")

The display within the shiny application correspond to the "2016-04-01"

This bug doesn't exist in shiny 0.13.1 (which I'm using for developpement, on another device that run macosx Yosemite with R.3.2.2), but there, I'm trying to deploy my shiny app on a shiny 0.13.2, on macOSX leopard (R 3.2.1)

Thanks

**Comment by hamsternik** [comment]
If look at this more accurately, the problem applies only for numbers, from 1 to 9, getting from *sliderInput*. But, after setting number, more or equal than 10, this problem disappears.

I, actually, found this bug on R, ver. 3.2.4 & Shiny ver. 0.13.2

**Comment by hamsternik** [comment]
I'm using example from [this](https://github.com/rstudio/shiny/blob/master/R/update-input.R) shiny sources: 

> ui <- fluidPage(
  sliderInput("controller", "Controller", 1, 30, 10),
  dateInput("inDate", "Input date")
)
#'
server <- function(input, output, session) {
  observe({
    # We'll use the input$controller variable multiple times, so save it as x
    # for convenience.
    x <- input$controller
#'
    updateDateInput(session, "inDate",
      label = paste("Date label", x),
      value = paste("2013-04-", x, sep=""),
      min   = paste("2013-04-", x-1, sep=""),
      max   = paste("2013-04-", x+1, sep="")
    )
  })
}
#'
shinyApp(ui, server)
}

**Comment by wch** [comment]
This sounds like it's related to #987.

**Comment by wch** [comment]
It looks like the problem was that the min string being sent was `"2013-04-9"` instead of `"2013-04-09"`, and this probably confused the date parser in the client.
