### ISSUE TITLE
fread allows excecution of arbitrary code

### ISSUE THREAD

**Issue by edwardabraham** [rstudio/shiny#1187]
I have raised an [issue over on data.tables](https://github.com/Rdatatable/data.table/issues/1702), and thought I would mention it here. The short story is that a filename with spaces passed in to fread will allow for arbitrary code to be run (including, say, deleting all the files). I have found an example of this in the wild, where someone is passing [input to shinyServer in to fread](https://github.com/martinbel/shiny_lesson/blob/6fab248aab577a12e202076bdbbef998841f4fb2/OEM_app/server.R).  Looks like it could be dangerous.

**Comment by wch** [comment]
There are any number of R functions that could be used to run arbitrary code -- for example, `eval` and `system`. I suppose with `fread`, though, it's surprising that it could be used this way.

This isn't really a Shiny bug though, and there's not much we can do to stop people from doing it, other than educating them about this potential danger with `fread`.

**Comment by edwardabraham** [comment]
I agree, it isn't really a Shiny issue. Just an FYI.
