### ISSUE TITLE
brushedPoints() does not work on geom_jitter()

### ISSUE THREAD

**Issue by ying-w** [rstudio/shiny#1188]
When I have use ggplot_jitter() the brush will only capture the original location of the point, not the jittered location.

Sample code for jitter:
```
ggplot(mtcars, aes(am, vs)) + geom_jitter()
```

I'm guessing this is due to the jitter being computed at plot time. i was wondering if there was a way to return the post-jittered values from ggplot2.

I am running shiny_0.13.1 with ggplot2_2.1.0

**Comment by jcheng5** [comment]
Sorry, there isn't a way to do this.

**Comment by wch** [comment]
Unfortunately, ggplot2 doesn't include the post-jitter data coordinates in the object, so there's not really a way to do this.
