### ISSUE TITLE
UpdateSelectInput does not have a multiple = TRUE function

### ISSUE THREAD

**Issue by Nicktz** [rstudio/shiny#1192]
It seems the UpdateSelectInput funcionality in Shiny cannot take the argument: multiple = TRUE.

I tried the following in rmarkdown (Factornames() is a reactive variable):

updateSelectInput(session = session, inputId = "Columns",
                    choices = isolate(Factornames()),
                    selected = isolate(Factornames())[1:3], multiple = T)

When I try to update it it gives me an error:
updateSelectInput: unused argument (multiple = T)

It works perfectly when I do not add multiple = T, but then it only uses the inputs [1:3] and cannot accept anything else.

Is this a known limitation or should I specify multiple differently?

**Comment by wch** [comment]
It's true that the `updateSelectInput` currently doesn't take a `multiple` argument. If the original `selectInput` was created with `multiple=TRUE`, then `updateSelectInput` will automatically allow selecting multiple items. For example:

```R
items <- c("Item A", "Item B", "Item C")

ui <- fluidPage(
  p("The checkbox group controls the select input"),
  checkboxGroupInput("inCheckboxGroup", "Input checkbox",
    choices = items),
  selectInput("inSelect", "Select input",
    choices = items,
    multiple = TRUE
  )
)

server <- function(input, output, session) {
  observe({
    x <- input$inCheckboxGroup

    # Can use character(0) to remove all choices
    if (is.null(x))
      x <- character(0)

    # Can also set the label and select items
    updateSelectInput(session, "inSelect",
      choices = items,
      selected = x
    )
  })
}

shinyApp(ui, server)
```

Is it that you want to convert a selectInput that was created with `multiple=FALSE` into one that allows multiple selection?

**Comment by bogdanrau** [comment]
Following this. @wch, I think the original intent (and my own intent) was YES, have the ability to turn a multiple = FALSE into multiple = TRUE through the updateSelectInput.

**Comment by lvandersypen** [comment]
Yes, I want this functionality to be added as well, where I can use updateSelectInput to switch multiple = TRUE to multiple = FALSE (and vice versa), based on the value of another input (i.e. using observeEvent to trigger the updateSelectInput).

**Comment by aolow** [comment]
A workaround would be to use
options = list(maxItems = 1) 
argument inside updateSelectizeInput() instead of multiple  = FALSE and then e.g.
options = list(maxItems = 9999) 
instead of multiple = TRUE.
This worked for me.
