### ISSUE TITLE
Cannot find function: "..stacktraceon.."

### ISSUE THREAD

**Issue by Eflores89** [rstudio/shiny#1194]
After updating Rstudio (to version 0.99.902) and updating shiny package the following comes up at the browser on a local app that was working fine: 

`ERROR: no se pudo encontrar la función "..stacktraceon.."` 

Which basically translates into: "cannot find "..stacktraceon.." function".

The app is very straightforward: 

**ui.R**
```
shinyUI(pageWithSidebar(
  headerPanel('Visualización'),
  sidebarPanel(
    helptext('Para más información: www.enelmargen.org/inegiR'),
    selectInput('xcol', 'X Variable', names(iris)),
    selectInput('ycol', 'Y Variable', names(iris),
                selected=names(iris)[[2]]),
    numericInput('clusters', 'Cluster count', 3,
                 min = 1, max = 9)
  ),
  mainPanel(
    plotOutput('plot1')
  )
))
```
**server.R**
```
pal <- palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
          "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))

shinyServer(function(input, output, session) {
  
  # Combine the selected variables into a new data frame
  selectedData <- reactive({
    iris[, c(input$xcol, input$ycol)]
  })
  
  clusters <- reactive({
    kmeans(selectedData(), input$clusters)
  })
  
  output$plot1 <- renderPlot({
    par(mar = c(5.1, 4.1, 0, 1))
    plot(selectedData(),
         col = clusters()$cluster,
         pch = 20, cex = 3)
    points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
  })
  
})
```

And `sessionInfo()`:
```
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] es_ES.UTF-8/es_ES.UTF-8/es_ES.UTF-8/C/es_ES.UTF-8/es_ES.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] shinyjs_0.6

loaded via a namespace (and not attached):
 [1] shiny_0.13.2    R6_2.1.2        rsconnect_0.4.3
 [4] htmltools_0.3.5 tools_3.2.3     yaml_2.1.13    
 [7] Rcpp_0.12.5     digest_0.6.9    xtable_1.8-2   
[10] httpuv_1.3.3    miniUI_0.1.1    mime_0.4  
``

**Comment by bborgesr** [comment]
From a quick first glance: are you actually doing `require(shiny)` anywhere? It seems like the only attached package is `shinyjs` and not `shiny` (which is only loaded). You could have had `shiny` attached (through `require()` or `library()`) in a previous R session and that is why you didn't see this error previously.

**Comment by Eflores89** [comment]
Thanks. I added `library(shiny)` and I get the same error. 

The console writes this though, before the error: 
```
Loading required package: shiny
Warning: package ‘shiny’ was built under R version 3.2.4
Error in unloadNamespace(package) : 
  namespace ‘shiny’ is imported by ‘shinyjs’, ‘miniUI’ so cannot be unloaded
Failed with error:  ‘Package ‘shiny’ version 0.13.1 cannot be unloaded’

Listening on http://127.0.0.1:5730
```
Maybe something related to compatibility of versions?

**Comment by bborgesr** [comment]
Are you actually using `shinyjs` in this app? If so, are you requiring it from within the app? (if you are using it, but not requiring it from within the app, you should change that). Restart your RStudio session to make sure you're working with a clean environment and then run your app immediately (which means that you must `require()` all needed packages somewhere inside the app itself). What do you get?

**Comment by bborgesr** [comment]
also, you're probably getting that error because you are doing `require(shiny)` after `require(shinyjs)` -- it should be the other way around

**Comment by wch** [comment]
It looks like you're trying to unload and the reload Shiny without restarting R. Try starting a clean R session and run it again.

**Comment by Eflores89** [comment]
Thanks it was the order of loading. 

I was doing `require(shiny)` after `require(shinyjs)`. I did it the other way around and it works.
