### ISSUE TITLE
Closing or Reloading app preview window crashes

### ISSUE THREAD

**Issue by kissmygritts** [rstudio/shiny#1195]
R studio crashes, and if it doesn't the R session is aborted. I recently updated to R 3.3.0 and RStudio 0.99.902

Any advice on pinpointing whether it is R, RStudio or Shiny?

**Comment by wch** [comment]
Can you post the output of `devtools::session_info`?

**Comment by kissmygritts** [comment]
I fixed this by uninstalling and reinstalling both R and RStudio... It hasn't happened since.

**Comment by wch** [comment]
Great, that's good to hear!
