### ISSUE TITLE
download button without handler creates a new instance of app

### ISSUE THREAD

**Issue by ByronAnalytics** [rstudio/shiny#1196]
If you haven't wired up `downloadHandler()`, then the `dowwnloadButton()` button creates a new instance of the shiny application. Behavior is consistent for apps run in widow or in Firefox. 
R version 3.3.0 (2016-05-03), which I'm told is the educational version.
shiny v 0.13.2
RStudio Version 0.99.1197 - also occurs on last stable release.

```R
library(shiny)
ui <- fluidPage(
  titlePanel("This is a fun quirk"),
  downloadButton("downloadData", "duplicator"),
  hr(),
  sliderInput("bins", "Number of bins:", min = 1, max = 50, value = 30),
  plotOutput("distPlot")
)
server <- function(input, output) {
  output$distPlot <- renderPlot({
    x    <- faithful[, 2]
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    hist(x, breaks = bins, col = 'darkgray', border = 'white')
  })
}
shinyApp(ui = ui, server = server)
```
  
Not sure it qualifies as an issue, just a quirk. Found it while working out module logic and commented out everything but that section.

**Comment by daattali** [comment]
I'll just offer my two cents: I don't believe this qualifies as an issue. A download button should not exist without its corresponding handler so the behaviour for it is not too relevant IMO.
