### ISSUE TITLE
Double-ended Range Slider Colouring

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1198]
Currently, the range colouring is between the two points. Could you provide an option to make the two ranges (min, lower) point and (upper point, max) coloured, with the middle range remaining grey, instead ? Also, the minimum and maximum values at the ends of the slider should also use the same style. This would be useful for choosing two groups of extreme values.

**Comment by wch** [comment]
Sorry, I don't think the underlying slider widget (https://github.com/IonDen/ion.rangeSlider) that we're using supports that.
