### ISSUE TITLE
segfault on OS X when closing shiny app

### ISSUE THREAD

**Issue by jotsetung** [rstudio/shiny#1200]
Hi,
I frequently stumble over the problem that I get a segfault whenever I want to close running shiny app. The apps run without problems but when it gets to closing either the browser tab or hitting Ctrl-C on the R-terminal I get the segfault.
Example:

> runExample("03_reactivity")

Listening on http://127.0.0.1:4435
^C

 *** caught segfault ***
address 0xfffffffd0ba655ac, cause 'memory not mapped'

Traceback:
 1: order(x, na.last = na.last, decreasing = decreasing, method = "radix")
 2: sort.int(x, na.last = na.last, decreasing = decreasing, ...)
 3: sort.default(as.integer(.callbacks$keys()), decreasing = TRUE)
 4: sort(as.integer(.callbacks$keys()), decreasing = TRUE)
 5: private$closedCallbacks$invoke(onError = printError, ..stacktraceon = TRUE)
 6: shinysession$wsClosed()
 7: handler()
 8: (function (handle) {    ws <- .wsconns[[as.character(handle)]]    ws$.handle <- NULL    rm(list = as.character(handle), pos = .wsconns)    for (handler in ws$.closeCallbacks) {        handler()    }})("140212578892336")
 9: eval(substitute(expr), envir, enclos)
10: evalq((function (handle) {    ws <- .wsconns[[as.character(handle)]]    ws$.handle <- NULL    rm(list = as.character(handle), pos = .wsconns)    for (handler in ws$.closeCallbacks) {        handler()    }})("140212578892336"), <environment>)
11: doTryCatch(return(expr), name, parentenv, handler)
12: tryCatchOne(expr, names, parentenv, handlers[[1L]])
13: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
14: doTryCatch(return(expr), name, parentenv, handler)
15: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
16: tryCatchList(expr, classes, parentenv, handlers)
17: tryCatch(evalq((function (handle) {    ws <- .wsconns[[as.character(handle)]]    ws$.handle <- NULL    rm(list = as.character(handle), pos = .wsconns)    for (handler in ws$.closeCallbacks) {        handler()    }})("140212578892336"), <environment>), error = function (x) x, interrupt = function (x) x)
18: .Call("httpuv_destroyServer", PACKAGE = "httpuv", handle)
19: destroyServer(handle)
20: stopServer(server)
21: runApp(dir, port = port, host = host, launch.browser = launch.browser,     display.mode = display.mode)
22: runExample("03_reactivity")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 

My session info:

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin15.5.0/x86_64 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.13.2

loaded via a namespace (and not attached):
[1] R6_2.1.2        htmltools_0.3.5 Rcpp_0.12.5     digest_0.6.9   
[5] xtable_1.8-2    httpuv_1.3.3    mime_0.4       

Thanks in advance for any input.

cheers, jo

**Comment by wch** [comment]
Hm, can you include the output of `devtools::session_info`?

**Comment by yihui** [comment]
I just ran into the same problem on OS X.

```r
> library(shiny)
> devtools::session_info()
Session info -----------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.0 (2016-05-03)
 system   x86_64, darwin15.4.0        
 ui       RStudio (0.99.1200)         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Asia/Shanghai               
 date     2016-05-28                  

Packages ---------------------------------------------------------------------------------
 package   * version date       source        
 devtools    1.11.1  2016-04-21 CRAN (R 3.2.4)
 digest      0.6.9   2016-01-08 CRAN (R 3.2.3)
 htmltools   0.3.5   2016-03-21 CRAN (R 3.2.5)
 httpuv      1.3.3   2015-08-04 CRAN (R 3.2.1)
 memoise     1.0.0   2016-01-29 CRAN (R 3.2.3)
 mime        0.4     2015-09-03 CRAN (R 3.2.3)
 R6          2.1.2   2016-01-26 CRAN (R 3.2.3)
 Rcpp        0.12.5  2016-05-14 CRAN (R 3.3.0)
 shiny     * 0.13.2  2016-03-28 CRAN (R 3.2.4)
 withr       1.0.1   2016-02-04 CRAN (R 3.2.3)
 xtable      1.8-2   2016-02-05 CRAN (R 3.2.3)
```

**Comment by kevinushey** [comment]
Is there an easy way to debug / check what values are being sorted in the call to

```
 order(x, na.last = na.last, decreasing = decreasing, method = "radix")
```

?

**Comment by yihui** [comment]
Unfortunately I discovered this when it was too late at night, and I have a 3-hour talk tomorrow morning, so I don't have time to debug the issue now. It probably has something to do with the fact that I installed R from Homebrew.

**Comment by kevinushey** [comment]
@yihui Could it be related to the fact that you're using R 3.3.0 with a version of Shiny build against R 3.2.4? (If I'm reading the sessionInfo correctly)

**Comment by kevinushey** [comment]
Ah, that could be it as well -- FWIW someone else reported this at https://github.com/rstudio/shiny/issues/1191 too.

**Comment by jotsetung** [comment]
My session info:
I have shiny build against R 3.3.0, so that should rule that out. However, I've compiled R from source myself; I'll check what happens if I use the pre-compiled R.

> devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.0 (2016-05-03)
 system   x86_64, darwin15.5.0        
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Rome                 
 date     2016-05-27                  

Packages -----------------------------------------------------------------------
 package    * version    date       source                          
 devtools   * 1.11.1     2016-04-21 CRAN (R 3.3.0)                  
 digest       0.6.9      2016-01-08 CRAN (R 3.3.0)                  
 htmltools    0.3.5      2016-03-21 CRAN (R 3.3.0)                  
 httpuv       1.3.3      2016-05-27 Github (rstudio/httpuv@6aeca57) 
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.0)                  
 mime         0.4        2015-09-03 CRAN (R 3.3.0)                  
 R6           2.1.2      2016-01-26 CRAN (R 3.3.0)                  
 Rcpp         0.12.5     2016-05-14 CRAN (R 3.3.0)                  
 rstudioapi   0.5        2016-01-24 CRAN (R 3.3.0)                  
 shiny      * 0.13.2     2016-03-28 CRAN (R 3.3.0)                  
 withr        1.0.1.9000 2016-05-09 Github (jimhester/withr@bd42181)
 xtable       1.8-2      2016-02-05 CRAN (R 3.3.0)

**Comment by kevinushey** [comment]
How did you compile R? (What optimization flags, what configure flags, and so on)

FWIW, I can't reproduce on my own locally-built version of R (from R-devel, not R-3.3.0, though)

**Comment by jotsetung** [comment]
```
./configure SHELL='/bin/bash' \
	    --prefix=$PREFIX \
	    r_arch=x86_64 \
	    --x-includes=/usr/X11/include/ \
	    --x-libraries=/usr/X11/lib/ \
	    CC="clang" \
	    CXX="clang++" \
	    OBJC="clang" \
	    F77="gfortran -arch x86_64" \
	    FC="gfortran -arch x86_64" \
	    --with-blas='-framework Accelerate' \
	    --with-lapack \
	    CPPFLAGS="-D__ACCELERATE__ -I/usr/local/opt/sqlite/include" \
	    LDFLAGS="-L/usr/local/opt/sqlite/lib" \
	    --enable-R-framework=no \
	    --enable-memory-profiling \
	    --enable-R-shlib
```

**Comment by kevinushey** [comment]
Thanks -- FWIW, I can now reproduce this using Homebrew R. I'll see if I can learn anything more...

**Comment by jotsetung** [comment]
thanks for the info; yes, seems to have to do with the custom compilation. The "official" pre-compiled version works without problems. Still, I would prefer to have my compiled version...

**Comment by kevinushey** [comment]
Here's a reproducible example (reproduces on my Homebrew R):

```
data <- c(2147483645L, 2147483646L, 2147483647L, 2147483644L)
sort(data, decreasing = TRUE, method = "radix")
```

Note that the `radix` sort method implementation is new in R 3.3.0 and this segfault doesn't occur with e.g. `method = "shell"` so that may be the culprit.

**Comment by kevinushey** [comment]
I've filed a bug against R for this issue: https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16925

The ASAN error indicates that it's likely an issue in the new radix sort implementation.

**Comment by kevinushey** [comment]
@jcheng5 any thoughts on whether this could be worked around in Shiny? (As far as I can tell, callbacks get keys trailing down from `2^31 - 1`; it's possible the error could be avoided by beginning key generation from a slightly smaller value or something to that effect). E.g. here:

https://github.com/rstudio/shiny/blob/master/R/utils.R#L630

We might want to give that some wiggle room to avoid the crash here.

**Comment by wch** [comment]
Nice sleuthing @kevinushey! Do you know what values are safe to use?

**Comment by kevinushey** [comment]
From what I can tell, the overflow only occurs when attempting to sort an integer vector that contains `.Machine$integer.max`, so I think just ensuring keys are less than that value should ensure we're safe.

**Comment by lawremi** [comment]
I agree that wiggle room would be a good idea. There is a bug in the new radix sort that seems compiler specific. Even after that is fixed though, the algorithm will not be able to use the optimal mode (counting sort) when sorting the maximum integer. This is because it needs space to count the `NA`s. Perhaps it could be made smart enough not to take the suboptimal branch when `na.last=NA` (or when there are no `NA`s but that would take time to check), so that is another option here.

**Comment by lawremi** [comment]
Actually, `na.last=NA` or `na.last=FALSE` should do the right thing already.

**Comment by mattdowle** [comment]
Oops. Sorry for the hassle there all. Well found @kevinushey.
Found, fixed, simplified and test added : https://github.com/Rdatatable/data.table/commit/95400c804b110dc0f3f6aee7cf0da748ff036959
I let @lawremi know for his review.

**Comment by kevinushey** [comment]
Thanks for the quick fix @mattdowle!

**Comment by jotsetung** [comment]
thanks guys! you're great!
