### ISSUE TITLE
Official Support for Images as radioButtons Choices

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1202]
I searched online and found that [another user had the same question as I do](http://stackoverflow.com/questions/35783446/can-you-have-an-image-as-a-radiobutton-choice-in-shiny). The solution was to hack an alternative version of the `radioButtons` which supports HTML elements. Can this use case be officially supported in the next version of shiny, so that no user workarounds are required? I also wonder if it could be generalised so that each radio button could have more than one HTML element associated with it. For example, a text option next to each button and a `selectizeInput` box directly below the text.

Currently, the documentation of `choices` for `radioButtons` doesn't specify what data type it should be, although it only works when it is a character vector. This is a more general request than #1093.

**Comment by wch** [comment]
Sorry, we're not likely to implement this.
