### ISSUE TITLE
shiny 0.13.2 needs Rcpp

### ISSUE THREAD

**Issue by micstr** [rstudio/shiny#1203]
In Rstudio `install.packages("shiny")` did not bring in Rcpp which is now needed. It gives illusion installation seems to work okay, i.e.

>   install.packages("shiny")
Installing package into ‘C:/.../R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/shiny_0.13.2.zip'
Content type 'application/zip' length 2257623 bytes (2.2 MB)
downloaded 2.2 MB

*package ‘shiny’ successfully unpacked and MD5 sums checked*

BUT when ticking shiny as a package User gets this message:

> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘Rcpp’

**Please can this be added as a dependency or a more descriptive warning be given to the user.** 

I am using R 3.2.4.

(My workaround was to get the latest version from github not Rstudio so this issue may have already been closed. Selecting devtools package and then using this `devtools::install_github("rstudio/shiny")`

Thanks devs we love shiny!)

**Comment by wch** [comment]
R should automatically install Rcpp, because shiny imports httpuv, and httpuv imports Rcpp. If you have a `.Rprofile` file, do you have any installation-related options set in it?

**Comment by micstr** [comment]
Thanks Winston. No I don't have a `.Rprofile` file. Try testing if this works on other machines with no Rcpp loaded.

**Comment by wch** [comment]
This is what it does for me on a clean install:

```
> install.packages('shiny')
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘Rcpp’, ‘httpuv’, ‘mime’, ‘jsonlite’, ‘xtable’, ‘digest’, ‘htmltools’, ‘R6’
```

**Comment by micstr** [comment]
Winston I am happy for you to close this issue - I just wanted to report it if others were stuck  as it was a real curve ball. I also fully expected it to load all the dependencies!

**Comment by wch** [comment]
Great! I think there must be something unusual about the way your system is configured, since we've never heard of this problem before.
