### ISSUE TITLE
let JavaScript Variable Declaration Is Not Supported

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1206]
The following example causes a JavaScript error:

    ui <- fluidPage(  
                     tags$head(tags$script("let x = 10;")),
                     titlePanel("Example") 
                   )
    
    
    server <- function(input, output, session) { }
    
    runApp(list(ui = ui, server = server))

The error message in the console is `SyntaxError: missing ; before statement`.

Changing `let` to `var` fixes the problem. Can Shiny be updated to work with the ECMAScript 6 version of JavaScript ? Using `let` to create variables in the console's command line causes no errors, so I don't think this error is related to the web browser I use.

**Comment by jcheng5** [comment]
Chrome doesn't currently support let unless you enter strict mode; google `"use strict"` if you're not familiar with that.
