### ISSUE TITLE
Enhancements for passwordInput

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1207]
To make `passwordInput` consistent with `textInput` and to allow a common style of password boxes on many websites to easily be made with Shiny, could `passwordInput` gain a `placeholder` parameter, which `textInput` already has?

Also, there is sometimes a little icon at the side of the password input box which allows the letters typed to be visible when it is clicked on. Could that also become an option?

**Comment by daattali** [comment]
The dev version of shiny already has a placeholder for passwordinputs, see https://github.com/rstudio/shiny/pull/1152

**Comment by wch** [comment]
As @daattali noted, the placeholder option is there already. I think that having a button that shows password text is out of scope for Shiny. But you could write some simple Javascript to do that.
