### ISSUE TITLE
Possible memory leak deploying R shiny on Google Chrome

### ISSUE THREAD

**Issue by komalsrathi** [rstudio/shiny#1210]
Hi,

I have been testing my R shiny app on Google Chrome since past one month and it worked fine until this morning. I did not update R or Chrome or anything else whatsoever. Whenever I am trying to deploy it - locally or using the shinyapps.io server - it is getting unresponsive after a few seconds and suggests that I either wait or kill the page. I deployed the same app locally as well as via shinyapps.io in Safari and it worked absolutely fine.

Here is the link to a subset of my app which exhibits similar behavior - https://rathik.shinyapps.io/data_marislab/

Following is the code snippet where the problem is encountered:

ui.R
```
tabItem(tabName = "clge",
              fluidRow(
                box(selectInput(inputId = "clgeselectInput1", label = "Select dataset", 
                                choices = c('Neuroblastoma RNAseq data'='rnaseqcelllinedata',
                                            'Neuroblastoma Microarray data'='celllinedata')),
                    actionButton(inputId = "clgesubmit1", label = "Load dataset"), width = 4, background = "navy"),
                box(selectInput(inputId = "clgeselectInput2", label = "Select Gene", choices = "none"), width = 3, background = "navy"),
                box(checkboxInput(inputId = "clgecheckboxInput1", label = "Log", value = TRUE), width = 2, background = "navy"),
                box(selectInput(inputId = "clgeselectInput3", label = "Sort by", choices = c('Variable', 'Value')), width = 3, background = 'navy')
              ),
              fluidRow(column(5, actionButton(inputId = 'clgesubmit2', label = "Get Expression Plot"))), br(), br(),
              plotlyOutput(outputId = "clgeplot1", width = 800, height = 800)
      )
```

server.R
 ```
# select dataset from clgeselectInput1, when clgesubmit1 is clicked, a second selectInput clgeselectInput2 is updated with the rownames of selected dataset
# This is where the problem is. When I select the dataset (clgeselectInput1) and hit load dataset (clgesubmit1), it does not update clgeselectInput2 and after a few seconds Chrome asks me to kill the unresponsive page.
  observe({
    if(input$clgesubmit1 == 0){
      return()
    }
    isolate({
      ####### this is exactly where the problem is ########
      dat <- as.character(input$clgeselectInput1)
      dat <- get(load(paste0('data/',dat,'.RData')))
      num <- as.character(rownames(dat))
      updateSelectInput(session = session, inputId = "clgeselectInput2", choices = num)
      ####### this is exactly where the problem is ########
      # when I replace the above snippet with the below, it works fine!
      updateSelectInput(session = session, inputId = "clgeselectInput2", choices = c('MYC','MYCN'))
    })
  })
  
# after clgeselectInput2 is updated with rownames, you can select and click on clgesubmit2 to output expression plot for selected gene.
  output$clgeplot1 <- renderPlotly({
    if(input$clgesubmit2 == 0){
      return()
    }
    isolate({
      dat <- as.character(input$clgeselectInput1)
      dat <- get(load(paste0('data/',dat,'.RData')))
      gene1 <- as.character(input$clgeselectInput2)
      logvalue <- input$clgecheckboxInput1
      sortby <- input$clgeselectInput3
      plotGeneBar(dat = dat, gene1 = gene1, log = logvalue, sortby)
    })
  })
```

Also tried changing the observe event like this, but it doesn't work:

```
# reactive function
  clge <- reactive({
    dat <- as.character(input$clgeselectInput1)
    dat <- get(load(paste0('data/',dat,'.RData')))
    num <- as.character(rownames(dat))
  })
  
  # output expression plot for selected gene
  observe({
    if(input$clgesubmit1 == 0){
      return()
    }
    isolate({
      updateSelectInput(session = session, inputId = "clgeselectInput2", choices = clge())
    })
  })
```

Here is the screenshot where I have selected the Neuroblastoma RNAseq data and hit Load dataset. On hitting Load dataset, after a few seconds, the selectInput with label Select Gene is updated with the rownames of the dataset. This is working fine in Safari but not in Google chrome. 

![screen shot 2016-06-13 at 3 03 37 pm](https://cloud.githubusercontent.com/assets/7000615/16019665/0e4a7c6c-3178-11e6-89bf-de0a5cd2ddea.png)

**Comment by jcheng5** [comment]
Almost certainly Plotly, which currently inherently leaks memory. See https://github.com/rstudio/shiny/issues/1151

**Comment by komalsrathi** [comment]
I am having trouble understanding why it would work on Safari and why it wouldn't on Chrome? Another thing that is bothering me is that I have been working and testing my app everyday on Chrome since the past month and faced no issues until today morning. There is no consistency to this problem.

**Comment by jcheng5** [comment]
Wait, the description doesn't seem to match the title--is there a memory leak or no?

**Comment by jcheng5** [comment]
Sorry, let's try this again. How many choices are you attempting to send to the selectInput? What happens if you replace

`updateSelectInput(session = session, inputId = "clgeselectInput2", choices = num)`

with

`updateSelectizeInput(session = session, inputId = "clgeselectInput2", choices = num, server = TRUE)`

?

**Comment by komalsrathi** [comment]
Thank you! As suggested by you, this works absolutely fine on Chrome as well.

```
updateSelectizeInput(session = session, inputId = "clgeselectInput2", choices = num, server = TRUE)
```

What does `server = TRUE` mean? Why `updateSelectizeInput` works and not `updateSelectInput`?

However, I am really having a hard time understanding why did it even work on Chrome until yesterday and then suddenly it started being unresponsive on Chrome but was working fine on Safari.

**Comment by jcheng5** [comment]
I think updateSelectInput probably was sending so much data that the browser was overwhelmed trying to insert into the page. I'm not sure why this would work one day and not the next though--did the size of your dataset change?

You can learn more about select vs selective here: http://shiny.rstudio.com/articles/selectize.html Note that by default selectInput uses selectize.js so the distinction between selectInput and selectizeInput is usually not important. However updateSelectInput vs updateSelectizeInput is important because only the latter has the server argument.
