### ISSUE TITLE
Shiny app is not working

### ISSUE THREAD

**Issue by kantasa** [rstudio/shiny#1212]
Hi,

I'm new to Rstudio, I have installed 3.2.3 version and I installed Shiny package. While running shiny app I'm getting a message for asking updated version of shiny packages. I clicked on yes, installing same package, I'm not getting any ouput..

Can someone help me, where I'm doing wrong?

Many thanks in advance.

Satheesh K

**Comment by pan0ramic** [comment]
That's not going to be enough to go on. Did you get any error messages? What do you mean by "not getting any output"?
