### ISSUE TITLE
Newline in navlistPanel Creates An Empty tabPanel

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1215]
Could `<br>` elements, using `br()`, be handled appropriately by `navlistPanel` ? Currently, the result is undesirable and creates a link to an empty `tabPanel`. Basic lists in HTML allow newlines :

    <ul>
    <li>A</li>
    <br>
    <li>B</li>
    </ul>

creates space between the two list elements :

<ul>
<li>A</li>
<br>
<li>B</li>
</ul>

Although the documentation suggests that only `tabPanel`s can be provided to the `...` parameter, the function already handles headings between list elements, such as `"Header"`.

**Comment by wch** [comment]
The browser may render a `<br>` in a `<ul>` that way, but strictly speaking, that's not a valid HTML structure.

You can just use an empty string to achieve what you're trying to do:

```R
shinyApp(fluidPage(
  navlistPanel(
    tabPanel("First"),
    tabPanel("Second"),
    "",
    tabPanel("Third")
  )
), 
function(input, output) {}
)
``
