### ISSUE TITLE
Distinguishing Classes for Labels Are Lacking

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1216]
Both the list items of checkbox groups and radio button groups, as well as text and password input box heading labels don't have any associated class and are simply `<label>`s in the resulting HTML. This prevents giving them distinct styles using CSS class selectors. It would be desirable to style selection list items differently to box headings. If Shiny could add distinctive classes (e.g.`choice-label` and `textbox-label`) to them, this would assist in differentiating their styling.

**Comment by wch** [comment]
You could use use sibling and child selectors to do this. See:
* https://developer.mozilla.org/en-US/docs/Web/CSS/Child_selectors
* https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_selectors
* https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors

**Comment by DarioS** [comment]
Good point. I also noticed a class `shiny-options-group` I didn't previously know about, which achieves the same result in a simpler way.
