### ISSUE TITLE
navlistPanel Should Allow Fixed Width Value

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1217]
The navigation bar of a `navlistPanel` contains text links to tab panels, so the text is not something which should expand to take up more size when the browser window is enlarged. It creates unnecessary horizontal whitespace in the navigation list. Currently, only relative widths are acceptable to `widths` e.g. `c(3, 9)`. It should be possible to easily specify a fixed width (e.g. `200px`) for the list panel and allow the tab panels to consume the remainder of the space, which changes according to the width of the browser, since they would contain items, such as plots, more suitable to resizing.

**Comment by wch** [comment]
You can do this by setting the width of the div using CSS.
