### ISSUE TITLE
observeEvent Initally Fails with Complex eventExpr

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1219]
No events are triggered by clicks in the first `checkboxGroup` until at least one click is done in the second `checkboxGroup`. Then, events from both `checkboxGroup`s work. A small test case is:

    ui <- fluidPage(
      checkboxGroupInput("first", "Choose Datasets", c("A", "B", "C")),
      checkboxGroupInput("second", "Choose Annotations", c("D", "E", "F"))
    )
    
    server <- function(input, output)
    {
      observeEvent({
                     input[["first"]]
                     input[["second"]]
                   },
                   {
                     print("Load/unload RData of modified list item")
                   })
    }
    
    shinyApp(ui=ui, server=server)

This test case only demonstrates the event-handling problem. This example `observeEvent` wouldn't be useful in a real program, because it's not possible to determine which of the two input widgets fired the event, nor the input element that was selected or deselected (without additional code for set-differencing the selected element vectors before and after the fired event).

**Comment by jcheng5** [comment]
observeEvent only fires by default if the result from evaluating eventExpr is "truthy" (see ?req). You can change this by passing ignoreNULL=FALSE to observeEvent. Does that help?

**Comment by DarioS** [comment]
Interesting to know. Thanks.
