### ISSUE TITLE
removeObserver to Remove Defunct Event Listeners

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1221]
To avoid having `observeEvent`s for user interface elements that have been removed interactively by `removeUI`, could a function such as `removeObserver` be provided in Shiny ? I don't know how it would work, since event listeners don't have unique IDs, at least not user-visible ones.

**Comment by jcheng5** [comment]
The return value of observeEvent is an object you can use to destroy it.
You can call either suspend() or destroy(), which are basically equivalent
except that suspend() can later be resumed and also may run the code one
more time (if it's already invalidated but hasn't run yet). However, they
should be equal in terms of efficiency (i.e. neither will cause any runtime
overhead once you let their objects get garbage collected).
