### ISSUE TITLE
CORS in Shiny

### ISSUE THREAD

**Issue by Stophface** [rstudio/shiny#1225]
Is there a way to make CORS in Shiny, hosted on R Studio Server?
Assuming your App creates files based on user interaction which you then need to load into JavaScript and process it there. Currently there is (to me) no known way to to this because security reasons forbid CORS. Is there a way to set a header or something that would allow this?

**Comment by wch** [comment]
The pro version of Shiny Server does has custom headers: http://docs.rstudio.com/shiny-server/#set-custom-headers

**Comment by Stophface** [comment]
@wch Oh bummer... Thanks!

**Comment by devashishmaurya** [comment]
Is there any custom method to set header for non-pro users.
