### ISSUE TITLE
how can i dynamically display the input dataset variables?

### ISSUE THREAD

**Issue by kantasa** [rstudio/shiny#1227]
Hi All,

I'm creating an app.

sidebarPanel(
    selectInput("dataset", "Choose a dataset", choices = c("rock", "pressure", "cars", "iris", "rock","women" , "trees")),
      selectInput('coloumns1', "Choose a variable", names(iris)),
      selectInput('Coloumns', "choose a variable", names(iris)),
      selected= names(iris),
     actionButton("update", "Run"),
    selected = 'iris'),

EX: Drop down box has to display all the datasets, instead of passing the datasets like(EX: trees, aris, aris3, women,swiss.. etc..)
if  I select aris dataset, it has to show the variable in airs dataset.

Please help me how can I do that.

Many thanks in advance

**Comment by wch** [comment]
This issue tracker is for bugs and feature requests in Shiny. A better place to ask this kind of general help question is the [shiny-discuss](https://groups.google.com/forum/#!forum/shiny-discuss) mailing list.
