### ISSUE TITLE
Incorrect Placement by insertUI After checkboxInput

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1228]
Unlike for `checkboxGroupInput`, using `insertUI` on a `checkboxInput` toggle causes the new user interface control to be placed inside the checkbox's HTML `label` tag. The bug is demonstrated by the following example. The problem can be avoided by putting the `checkboxInput` inside `div` and using that as `insertUI`'s selector, but Shiny should handle this better by default.

    library(shiny)
    
    server <- shinyServer(function(input, output)
    {
      observeEvent(input[["addToGroup"]], {
        insertUI("#datasetChooser", where = "afterEnd", ui = selectInput("aChoiceList", "Choose", 1:5))
      })
      observeEvent(input[["addToSingle"]], {
        # change selector to div's id
        insertUI("#toggleBox", where = "afterEnd", ui = selectInput("anotherChoiceList", "Choose", 1:5))
      })
    })
    
    ui <- fluidPage(
      checkboxGroupInput("datasetChooser", "Choose Dataset", 1:5),
      checkboxInput("toggleBox", "Transform Log2"), # surround with div and provide an id.
      actionButton("addToGroup", "Add Below Group"),
      actionButton("addToSingle", "Add Below Single")
    )
    
    shinyApp(ui = ui, server = server)

**Comment by jcheng5** [comment]
It may sound unintuitive but I don't think we want to guarantee that the selector `#inputid` will be the right target for `insertUI`. What I've been doing is putting an empty `tags$div(id="blah_container")` wherever I want to insert content, and use `beforeEnd`--I recommend you do the same if you can.

**Comment by DarioS** [comment]
That's a good design pattern to use, but, unintuitively, is not used by any examples in the documentation of `insertUI`.
