### ISSUE TITLE
DT Drop Down Menu for SelectInput doesn't scroll to show all choices for long list

### ISSUE THREAD

**Issue by dannc454** [rstudio/shiny#1230]
I find that for filter boxes in DT and also SelectInput drop down menus the scrolling stops before the end of available choices ~ around 1000 entries or so before scrolling stops. Anyway to allow scrolling to continue to exhaust all choices?

**Comment by yihui** [comment]
Unfortunately I don't think there is a way for you to change this behavior. 1000 is the default value of the `maxOptions` option of selectize.js: https://github.com/selectize/selectize.js/blob/master/docs/usage.md You can only type and search through all possible choices.

**Comment by dannc454** [comment]
Thank you very much for the response. I understand now that is the max possible.
