### ISSUE TITLE
Different Return Value Type for Static selectInput and Inserted selectInput

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1232]
If the choices vector is empty, querying the value of a static `selectInput` returns `""` but a dynamically generated one by `insertUI` returns NULL. It would make debugging easier if they both had the same return type. In the example below, first click the Add Select List Button then the Show Values button. The classes of return values are printed in the console.

    library(shiny)
    
    server <- shinyServer(function(input, output, session)
    {
      observeEvent(input[["addPicker"]], {
        insertUI("#row1", where = "afterEnd",
        ui = selectInput("anotherSelect", "Pick A Letter", choices = list()))
      })

      observeEvent(input[["showValues"]], {
        print(paste("Static:", class(input[["aSelect"]])))
        print(paste("Dynamically Added:", class(input[["anotherSelect"]])))
     })
    })
    
    ui <- fluidPage(
      fluidRow(id = "row1", selectInput("aSelect", "Pick A Number", choices = list()),
               actionButton("addPicker", "Add Select List"), actionButton("showValues", "Show Values"))
    )
    
    shinyApp(ui = ui, server = server)

The dynamically-generated drop-down list is missing the class `selectize-input` and the problem is probably similar to #1220 . The static list, however, seems to be missing `shiny-bound-input`, which the dynamic list has.

**Comment by bborgesr** [comment]
Hi Dario, Thanks for spotting these bugs (they were all related to the same thing). It's now fixed in the development version.
