### ISSUE TITLE
Retain Selected Value Where Possible

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1234]
Functions such as `updateSelectInput` and `updateCheckboxGroupInput` reset the selected items if `selected` is not provided. Could they automatically retain selected values, if the old selections are included in the new set of possible values, such as when appending a new choice to the vector of `choices` ? Currently, the functions operate more like a constructor than an updater.

**Comment by jcheng5** [comment]
(Possible workaround: pass `input$id` as the `selected` argument?)

**Comment by DarioS** [comment]
I suppose that would be adequate.
