### ISSUE TITLE
Carriage return in renderTable "\n" being ignored 

### ISSUE THREAD

**Issue by jpf5046** [rstudio/shiny#1235]
The link includes pictures of the code (http://imgur.com/a/uX32m)
Trying to make a renderTable output have two lines. For example the following code

---
title: "MWE for GitHub"
output: 
flexdashboard::flex_dashboard:
runtime: shiny

---
```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(dplyr)
```

```{r load data}

Second.Name <- c("Rodgers","Brady", "Wilson", "Cutler")
Team.City <- c("Green Bay", "New England", "Seattle","Chicago")

quaterbacks_df <- data.frame(Second.Name, Team.City)
```

```{r table}
  renderTable(
      quaterbacks_df %>%
      mutate(twoLineInfo =  paste(Second.Name, "\n", Team.City, sep = "")) %>%
      select(twoLineInfo) %>%
      arrange(twoLineInfo)  
    )

```

gives you an output like this:

Brady New England
Cutler Chicago 
Rodgers Green Bay
Wilson Seattle 

However, by placing the "\n" in the mutate function, I was expecting a result to look like this:

Brady
New England
Cutler
Chicago
Rodgers 
Green Bay
Wilson
Seattle

```
(the following is in code because formatting was reacting to my text) 

> R is recognizing the return function of "\n" because if you replace "\n" with "<br>" you get the 
> following (see link above for screenshot of code) :

> Brady<br>New England
> Cutler<br>Chicago 
> Rodgers<br>Green Bay
> Wilson<br>Seattle 

> RStudio is ignoring "\n" 

```

**Comment by bborgesr** [comment]
This has to do with `xtable`, which is called by `renderTable`, so it's not a shiny bug. I don't think it qualifies as an `xtable` bug either. I think you'd have to do some Latex customization for that behavior because it's not generally supported (or intended to be).

Try these two and see the difference (it places a newline but not as code, so when it's rendered, you don't see the difference -- that is the intended behavior when you hardcode `\n` in `xtable`):

```r
library(xtable)
library(dplyr)

Second.Name <- c("Rodgers","Brady", "Wilson", "Cutler")
Team.City <- c("Green Bay", "New England", "Seattle","Chicago")
quaterbacks_df <- data.frame(Second.Name, Team.City)

xtable( quaterbacks_df %>%
            mutate(twoLineInfo =  paste(Second.Name, Team.City, sep = "")) %>%
            select(twoLineInfo) %>%
            arrange(twoLineInfo)  )

xtable( quaterbacks_df %>%
            mutate(twoLineInfo =  paste(Second.Name, "\n", Team.City, sep = "")) %>%
            select(twoLineInfo) %>%
            arrange(twoLineInfo)  )
```

In any case, if you still want help with this, you should move it to a more appropriate forum, such as stackoverflow.

**Comment by wch** [comment]
You could put the items on separate lines, with something like this. (Note that the development version of shiny has somewhat different table output, and doesn't show row numbers by default.)

```R
Second.Name <- c("Rodgers","Brady", "Wilson", "Cutler")
Team.City <- c("Green Bay", "New England", "Seattle","Chicago")

renderTable({
  # The c(rbind()) is a way to put the two vectors together with alternating
  # entries.
  data.frame(
    info = c(rbind(Second.Name, Team.City))
  )  
})
```


To do what you want, you'd need to be able to pass through raw HTML to xtable, but I'm not sure that's possible. You essentially want this to put raw (unescaped) `<br>`s in the HTML. It's possible there's some option for `xtable` or `print.xtable` that would allow that, but I'm not sure.

```R
library(xtable)
tbl <- quaterbacks_df %>%
      mutate(twoLineInfo =  paste(Second.Name, "<br>", Team.City, sep = "")) %>%
      select(twoLineInfo) %>%
      arrange(twoLineInfo)

print.xtable(xtable(tbl), type = "html")
```
