### ISSUE TITLE
set ..stacktraceon.. to off?

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#1237]
I built a pretty large shiny app that takes a couple of seconds to load. Not horrible by any means but noticeable, at least to me.

I used the (excellent!) profiler in the preview version of Rstudio to determine what takes up most time when starting app and the majority seem attributable to ..stacktraceoff... (i.e., 4620ms out of 5280ms if I'm reading the profile output correctly). The stacktrace feature is amazingly useful but I was wondering if there is a way to turn it off when desired?

If you need to run the app use:

```r
install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/", type = 'binary')
```

**Comment by jcheng5** [comment]
It's almost certainly not the stack trace mechanism itself that's taking the time--just that the real time is being hidden from you by stacktraceoff. How do I run the app to reproduce the issue?

**Comment by wch** [comment]
Have you tried unchecking the "Hide internal function calls" option?

**Comment by vnijs** [comment]
@jcheng6 To run after installing select Radiant from the Addins menu in Rstudio or use radiant::radiant(). Alternatively, open inst/app/ui.R and click Run

FYI I `source` a lot of code in [server.R](https://github.com/radiant-rstats/radiant/blob/master/inst/app/server.R) or import it into the shiny environment and that is where most of the time is spent in startup if I look at the profilers Flame graph. The Data tab seems to assign the time to ..stacktraceon.. but it sounds like that might not be a correct interpretation on my part.

@wch The only `option` I left unchecked was "Hide internal function calls". Screen shot below:

![screen shot 2016-07-06 at 1 33 38 pm](https://cloud.githubusercontent.com/assets/2998956/16633450/4bc69f90-437e-11e6-9e7a-bd2a5994f1dd.png)

**Comment by wch** [comment]
The `..stacktraceon..` and `..stacktraceoff..` functions shouldn't take any time themselves -- their purpose is to just add a call on the stack that lets us know which function calls we can hide. If you expand that `..stacktraceoff..` in the data view, you should see what's actually taking up time, and the same should happen with the flame graph.

If you publish a profile to Rpubs, we might be able to help diagnose the problem.

**Comment by wch** [comment]
Very interesting... it looks like a lot of time is spent in `registerShinyDebugHook`, which only happens when run in RStudio, I believe. Can you try running from an R session outside of RStudio and see how that goes?

In order to save/publish it, I think you can do this:

```R
p <- profvis({ # Code here })
htmlwidgets::saveWidget(p, "profile.profvis")
```

And then you can open that file in RStudio and publish from there.


Another option is to stay in RStudio, but remove that function before running your app, with:

```R
rm("registerShinyDebugHook", envir = as.environment("tools:rstudio"))
```

**Comment by vnijs** [comment]
@wch Wow! I ran the app from R in a terminal and also from Rstudio after `rm(...)` as you suggested. Brings the startup time down from 4900 to 2100 (1980 in terminal). 

Not sure if this is a good idea but when I put the `rm(...)` line in global.R nothing seems to happen when I open ui.R and click Run in Rstudio. However, if I run radiant::radiant() (i.e., function in the Radiant R-package) it does seem to work. 

Is there a better way to turn off `registerShinyDebugHook` when it is not needed (e.g., an option when the package is run by a user)?

**Comment by vnijs** [comment]
Link to updated profile: http://rpubs.com/vnijs/194328

**Comment by wch** [comment]
FWIW, the word from @jmcphers (who implemented `registerShinyDebugHook` in RStudio) is to use `rm("registerShinyDebugHook", envir = as.environment("tools:rstudio"))` until it gets fixed in RStudio. I'm not sure when that will happen, though.

**Comment by vnijs** [comment]
Thanks for the follow up @wch. I'll use `rm(...)` as suggested.
