### ISSUE TITLE
Request: article describing the technical details of how shiny works

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1240]
Not exactly an issue but more of a request to @jcheng5 @wch or any other shiny devs.  It'd be nice to have an article explaining how shiny works for people who are beyond the basics of shiny and want to understand it better. Going through the source code is one option but it requires  alot of time and persistence, it would be helpful to have perhaps a few paragraphs with an associated flowchart that can be used as a starting point to make more sense of the codebase.

Of course you have enough to work on, but I wanted to make this an official request :)

**Comment by comckay** [comment]
+1

**Comment by burgerga** [comment]
Would also make it easier to get involved and make pull requests ;)

**Comment by jcheng5** [comment]
I'm afraid this topic is so broad as to be unactionable (unless we write a whole book)... if you have specific questions about how things work, we are happy to answer as many of those as we can on shiny-discuss.
