### ISSUE TITLE
downloadHandler blank page 

### ISSUE THREAD

**Issue by jepa** [rstudio/shiny#1242]
Hello everyone;

I have a Shiny app that downloads a R Markdown file with the "downloadHandler" function. However, when the download happens a new complete white page pops out, does anyone know how to, a) avoid that, b) automatically close the new pop-out page after downloading or c) write something in that new window?

Thx!

**Comment by burgerga** [comment]
Can you provide a  [minimal example](http://shiny.rstudio.com/articles/help.html) that demonstrates this problem?

**Comment by jepa** [comment]
Hi, I actually solve it, well I did not do anything. Once you upload the app and run it in the browser it automatically closes the download window. 

Thx for the reply!
