### ISSUE TITLE
renderText Delayed Until Another tabPanel Clicked On

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1243]
I have a `renderText` area at the bottom of one `tabPanel` and when I click on the button that does the processing which generates the text to be shown, nothing appears, no matter how long I wait. But, if I click on any other `tabPanel` then return back to the `tabPanel` I was looking at, the text immediately appears. I had the internet browser's Developer Tools open, and I noticed that the text is inserted into the `div` at the moment when I click on the tab which I am returning to, not when I click on the arbitrary other tab. I tried to make a small, runnable example, but did not succeed. Can anyone help me to make a minimal example or perhaps knows what this bug is and can fix it ? I think the bug is in the JavaScript part of Shiny, so would be hard to find. It occurs on both Firefox and Chromium browsers, so I doubt that it's a browser problem.

Another complication is that this problem happens most of the time, but sometimes it renders the text immediately without needing tabs to be switched, so the problem is sometimes not reproducible.

![missingtext](https://cloud.githubusercontent.com/assets/631218/16828880/3b7583c2-49d7-11e6-9337-a7aa6f7d0b4b.png)

**Comment by bborgesr** [comment]
A minimal reproducible example would be best, but if you can't do that, maybe share the whole code with us (link to github repo would be best) if you can. We could try to take a look and understand where the problem is coming from. Otherwise, it's difficult to pin the source of the problem, just going off what you wrote above.

**Comment by DarioS** [comment]
I have provided the Shiny application via e-mail to Barbara.

**Comment by jcheng5** [comment]
Is there any custom JS in your UI? In particular, anything that would cause the div to be hidden other than the tab switching? A core feature of Shiny is that it doesn't attempt to render controls it thinks are hidden--this can get fooled if you mutate the DOM in a way that Shiny isn't made aware of (you can raise a jQuery "shown" event if necessary and that will alert Shiny). You can disable this feature on a per-output basis by calling outputOptions in your server function, in particular you want the option `suspendWhenHidden=FALSE`.

**Comment by jcheng5** [comment]
(Though even if the workaround is successful it would be great to know whether/why we think that div is hidden.)

**Comment by DarioS** [comment]
Yes, the div container around it is initially hidden. The line of code directly above `renderText` uses `session[["sendCustomMessage"]]` to call a JavaScript function which removes a class that styles the border around the text to be invisible. I thought that the JavaScript modification of the DOM would automatically get communicated to Shiny. Are there any application examples on the RStudio website of how to raise the JQuery event in such a case ? `suspendWhenHidden = FALSE` does the trick for my application, though, so it's alright if there aren't.

Strangely, this problem doesn't happen at all if the `selected` value for the `navlistPanel` is set to the `tabPanel` which the text rendering is placed on; only if that `tabPanel` is selected by the user after the application has loaded.

**Comment by wch** [comment]
If you're using your own Javascript code to show/hide the div, you need to also trigger a corresponding `shown` or `hidden` event to make Shiny aware that it is happening.

For showing, you could do something like:

```
$('#mydiv').trigger('shown.bs.tab')
```

And for hiding:

```
$('#mydiv').trigger('hidden.bs.tab')
```

**Comment by DarioS** [comment]
Thanks for the example. Hopefully, it will be included in a Shiny tutorial in the future, to reach more of the Shiny audience.
