### ISSUE TITLE
Is it possible to send a dataframe through Shiny.onInputChange() ?

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1247]
I want to pass a dataframe from JavaScript to R, but I keep getting vectors instead.  In the following sample code, I construct a small JavaScript array containing two objects with 2 elements each having identical keys. It's essentially what I would consider the equivalent of a dataframe in javascript.  But when I inspect it in R, it's just a vector. 

```
library(shiny)

jscode <- '
$(document).on("shiny:connected", function(event) {
  var objects = [
    { id : 1, name : "Dean" },
    { id : 2, name : "Ben" }
  ];  
  Shiny.onInputChange("data", objects);
});
'

ui <- fluidPage(
  tags$script(jscode)
)

server <- function(input, output, session) {
  observe({
    cat(str(input$data))
  })
}

shinyApp(ui = ui, server = server)
```

The value that gets printed in R is a 4-element vector instead of a 2x2 dataframe.

Also note that the object I built in JS does parse out to a dataframe when using jsonlite to convert it (run the `objects` through `JSON.stringify()` in JavaScript, and pass the result to `jsonlite::fromJSON()` in R, and it'll give back a dataframe.

Hopefully I'm just missing something trivial and this is easy to do

**Comment by jcheng5** [comment]
I think you can use [`registerInputHandler`](http://shiny.rstudio.com/reference/shiny/latest/registerInputHandler.html) to do the conversion. The docs don't talk about it but I believe you can specify the type when calling Shiny.onInputChange by prepending the name with a colon and then the type (so maybe `Shiny.onInputChange("data:shinyjs.dataframe", objects")`).

**Comment by daattali** [comment]
That worked perfectly, I would never have found that out. Thanks Joe
