### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#1253]
If you run this app and hit the reload button over and over, the memory usage will keep increasing:

```R
library(shiny)
library(pryr)

vals <- reactiveValues(x = 1)

ui <- fluidPage(
  verbatimTextOutput("memUsed")
)

server <- function(input, output, session) {
  # Allocate a 40MB object in this session
  data <- 1:1e7

  memUsed <- function() {
    paste(round(as.numeric(pryr::mem_used()) / 1024 / 1024), "MB used")
  }

  output$memUsed <- renderText({
    memUsed()
  })
  
  # When this is code is included in the app, memory used will increase with 
  # each reload. When it is commented out, the memory used will NOT increase on
  # each reload.
  valueObserver <- observeEvent(vals$x, {
    print('Reactive values observable event triggered')
  })
  
  session$onSessionEnded(function() {
    print('Session Ended')

    # Another way to prevent memory usage from growing is to uncomment this
    # isolate(vals$x <- runif(1))
    
    gc()
    print(memUsed())
  })
}

shinyApp(ui, server)
```

If the `observeEvent` is commented out, then memory usage will NOT increase with each reload.

Also, if `vals$x` is modified in the `onSessionEnded` function, then the memory will not increase with each reload.

I think the root of the problem is that `vals$x` keeps a reference to the observer which gets cleared only when `vals$x` changes.

**Comment by jcheng5** [comment]
The observer does get destroyed, right? You don't see the "Reactive values
observable event triggered" stacking up?

**Comment by wch** [comment]
Oops, I forgot to comment out the `isolate` part. I'll edit the post.

**Comment by jcheng5** [comment]
OK that was going to be my next question. So we actually never see that print message at all?

**Comment by wch** [comment]
I made another edit. :/ Try again.

**Comment by wch** [comment]
Whether or not it actually gets triggered doesn't seem to matter.

**Comment by jcheng5** [comment]
Oh OK, now I get it. OK, there's an easy fix here. When the observeEvent's observer is destroyed during teardown, it's destroyed, but not invalidated. Invalidating it will free it for gc.

**Comment by jcheng5** [comment]
Interestingly, we don't even bother saving a reference to the most-recent ctx object in the Observer R6 object. I guess we could...? And clear it out during invalidation?
