### ISSUE TITLE
Get no result with fileInput

### ISSUE THREAD

**Issue by zhehao** [rstudio/shiny#1258]
When I try to use file upload widget, I first test the one listed in gallery -- [Uploading Files](http://shiny.rstudio.com/gallery/upload-file.html), it works well online.

But when I copy those codes and runApp on my local PC, it fails as there is no table rendered, and I browser the shiny  environment, there is no varibale names "file1" in `input` list. I wonder whether it is related to the versions of R or Shiny package ?

Here is the info of  R software and Shiny package on my PC, thanks for your time first.

```
R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

> packageVersion("shiny")
[1] ‘0.13.2’
```

**Comment by bborgesr** [comment]
I cannot reproduce your problem (can you provide a minimal reproducible example?) When I ran the the gallery app on my local machine, it works as expected.

One thing to point out is that, `input$file1` is meant to be `NULL` at the start (before you choose a file). But it shouldn't cause the app to fail. For example, usign the slightly modified example below (only difference is that it prints something extra to the console), you should see the following output. 

After you launch the app, but before you select a file to upload:

```
Listening on http://127.0.0.1:5715
$quote
[1] "\""

$file1
NULL

$header
[1] TRUE

$sep
[1] ","

[1] "================================================"
```

Then, after you select a valid file to upload:

```
$quote
[1] "\""

$file1
        name size     type
1 mtcars.csv 1783 text/csv
                                                                                 datapath
1 /var/folders/6b/xmhjngk91hd6d61027q69kz40000gn/T//RtmpcQk04u/b14a1621f8c7efeb08e641c0/0

$header
[1] TRUE

$sep
[1] ","
```

If this produces something different for you, please copy-paste the error message (or try to make a reproducible example).

[app.zip](https://github.com/rstudio/shiny/files/381574/app.zip)

**Comment by zhehao** [comment]
Thank you @bborgesr , I found it is a problem of `Chrome(version - 52.0.2743.82 m)` , after I change the browser to IE and Firefox, fileInput widget works with them. 

When it comes to Chrome, there is no reaction, no matter how I change the csv file input, the listening status stays unchanged as :

```
Listening on http://127.0.0.1:3265
ERROR: [on_request_read] connection reset by peer
$quote
[1] "\""

$file1
NULL

$header
[1] TRUE

$sep
[1] ","

[1] "================================================"
$quote
[1] "\""
```

After I change the default launch browser, everything works well

```
Listening on http://127.0.0.1:3265
$quote
[1] "\""

$file1
          name  size                     type                                                                    datapath
1 IRRs_120.csv 50214 application/vnd.ms-excel C:\\Users\\hzh\\AppData\\Local\\Temp\\RtmpeEzxXD/310eb0be71dfec41a5616cf2/0

$header
[1] TRUE

$sep
[1] ","


[1] "================================================"

```

**Comment by bborgesr** [comment]
The problem must be in your Chrome's configuration then. I just tried on my computer (same version of Chrome) and it works fine. Do you get any error on the JS console?

**Comment by wch** [comment]
Do you have any extensions in Chrome that could be blocking the file transfer?
