### ISSUE TITLE
Shiny app works fine in local machine. When published in shiny website it throws HTTP: 403 Forbidden error

### ISSUE THREAD

**Issue by kreshnaaraamsb** [rstudio/shiny#1269]
I created a shiny app which uses rvest package to scrap a table from google scholars page. It works fine in my local machine. when published in shiny website it shows HTTP:403 forbidden error. Is there a workaround for this?

**Comment by bborgesr** [comment]
From a google search for this issue, I found that someone had a similar problem and Hadley answered it (last comment on [this page](https://blog.rstudio.org/2014/11/24/rvest-easy-web-scraping-with-r/)):

*dimitris1ps*
> When doing a google search web scraping i got “client error: (403) Forbidden”
do we need the API for this.

*hadleywickham*
> Yes, you do need an API, but google doesn’t provide one (and scraping google search pages is against their terms of service)

So, it seems like you really shouldn't be scraping Google Scholars... This [stackexchange post](http://academia.stackexchange.com/questions/2567/api-eula-and-scraping-for-google-scholar) reiterates that. In particular, this excerpt from[ Google's Terms of Service](https://www.google.com/intl/en/policies/terms/) explicitly tell you not to use their Services with something other than the interface they provide (which explains why there is no API):

> Don’t misuse our Services. For example, don’t interfere with our Services or try to access them using a method other than the interface and the instructions that we provide.

**Comment by kreshnaaraamsb** [comment]
Thanks for the update @bborgesr.

**Comment by cimentadaj** [comment]
I'm having a similar issue on a website that **can** be scraped from Google Scholar. For example, I'm trying to scrape website `https://scholar.google.es/citations?user=amYIKXQAAAAJ&hl=en` which according to the robots text is allowed:

```
robotstxt::robotstxt("https://scholar.google.es/")$text
User-agent: *
Disallow: /search
Disallow: /index.html
Disallow: /scholar
Disallow: /citations?
Allow: /citations?user=
Disallow: /citations?*cstart=
Disallow: /citations?user=*%40
Disallow: /citations?user=*@
Allow: /citations?view_op=list_classic_articles
Allow: /citations?view_op=metrics_intro
Allow: /citations?view_op=new_profile
Allow: /citations?view_op=sitemap
Allow: /citations?view_op=top_venues

User-agent: Twitterbot
Disallow:

User-agent: facebookexternalhit
Disallow:
```

Notice that `/citations?user=` is allowed. This works just fine locally but returns 403 status code when deployed in a Shiny application. Any ideas?
