### ISSUE TITLE
cancelOutput() does not behave the same as req(FALSE) when called inside an observer.

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1270]
Which is what the documentation says it does... So we should either fix it or change the documentation (which I think is what makes the most sense) to specify that `cancelOutput()` should only be used in an output context (after all, it *is* right there in the name)...

We should also add some examples to the documentation of both `cancelOutput` and `req`.  I also feel like they should be documented together. And finally, it may be useful to write a small article/app that uses these types of simple examples for people to understand the difference between them. I don’t think it is completely intuitive and these may help. In any case, I didn’t want to move ahead with any of these before we agree on how we want to proceed.

Here is an example of the bug:

```r
ui <- fluidPage(
  textInput('txt', 'Enter text'),
  textOutput('check')
)
server <- function(input, output, session) {
  obs <- observe({
    req(FALSE)  ## this silently throws, does not affect the app
    # req(FALSE, cancelOutput = TRUE) ## but these two end the session
    # cancelOutput()
    input$txt
  })
  
  output$check <- renderText({
    input$txt
  })
}
shinyApp(ui, server)
```

Here are a bunch of examples that work as expected, that we can include in the documentation...

```r
ui <- fluidPage(
  textInput('txt', 'Enter text'),
  textOutput('check')
)
server <- function(input, output, session) {
  output$check <- renderText({
    if (input$txt == 'hi') return('hi')
    else if (input$txt == 'bye') return('bye')
    else cancelOutput()
  })
}
shinyApp(ui, server)

#*******************************#
#*******************************#

ui <- fluidPage(
  textInput('txt', 'Enter text'),
  textOutput('check')
)
server <- function(input, output, session) {
  output$check <- renderText({
    req(input$txt)
    if (input$txt == 'hi') return('hi')
    else if (input$txt == 'bye') return('bye')
  })
}
shinyApp(ui, server)

#*******************************#
#*******************************#

ui <- fluidPage(
  textInput('txt', 'Enter text'),
  textOutput('check')
)
server <- function(input, output, session) {
  output$check <- renderText({
    if (req(input$txt == 'hi')) return('hi')
    else if (req(input$txt == 'bye')) return('bye')
  })
}
shinyApp(ui, server)

#*******************************#
#*******************************#

ui <- fluidPage(
  textInput('txt', 'Enter text'),
  textOutput('check')
)
server <- function(input, output, session) {
  output$check <- renderText({
    req(nchar(input$txt) > 0, cancelOutput = TRUE)
    if (input$txt == 'hi') return('hi')
    else if (input$txt == 'bye') return('bye')
  })
}
shinyApp(ui, server)
```

**Comment by wch** [comment]
The root of the problem is that `req(FALSE)` throws this:

```R
  stopWithCondition(c("validation", "shiny.silent.error"), "")
```

while `cancelOutput` throws:

```R
  stopWithCondition(c("shiny.output.cancel", "shiny.silent.error"), "")
```

And the observer only traps `validation` conditions: https://github.com/rstudio/shiny/blob/c5d5ddd/R/reactives.R#L617

====

@bborgesr and I discussed why one might want to use `cancelOutput()` in an observer, despite the name that implies it should be used with outputs. The use case is a reactive which is called by both an output and regular observer. For example:

```R
ui <- fluidPage(
  textInput('txt', 'Enter text'),
  textOutput('check')
)
server <- function(input, output, session) {
  r <- reactive({
    if (identical(input$txt, "bad")) {
      cancelOutput()
    }
    input$txt
  })

  output$check <- renderText({
    r()
  })

  obs <- observe({
    print(r())
  })
}
shinyApp(ui, server)
```

**Comment by wch** [comment]
Maybe another way to think about this is that there is a class of exceptions that is always caught at the endpoints of the reactive graph, the observers. `req(FALSE)` is one way to raise this type of exception, and `cancelOutput()` is another, but what we want is another lower-level construct that they have in common. This could be called something like `reactiveStop()`.

So `req(FALSE)` and `cancelOutput()` would call `reactiveStop()`, which in turn throws a type of exception that is caught by observers. This would also allow app authors to call `reactiveStop()` if they have their own validation code. For example, right now someone might do this:

```R
server <- function(input, output) {
    observe({
    if (<some complicated condition, possibly with nested ifs>) {
      req(FALSE)
    }
  })
}
```

But it's a little weird to have `req(FALSE)` there -- we already checked the condition, so why call `req(FALSE)`, which is sort of like doing `if (FALSE == FALSE) stop( .... )`.

In cases like this, it makes more sense to explicitly raise an exception with something that's more like `stop()`. For example:

```R
server <- function(input, output) {
    observe({
    if (<some complicated condition, possibly with nested ifs>) {
      reactiveStop()
    }
  })
}
```

**Comment by bborgesr** [comment]
@jcheng5, if you like this idea, I could get started on this (and an accompanying article following and explaining this narrative)

**Comment by jcheng5** [comment]
I like it although I don't think this is worth more than an hour of your time right at this moment, unless there aren't other bugs to fix for the release.

**Comment by bborgesr** [comment]
So, leave all of this on hold, or fix just the original `cancelOutput` bug?

**Comment by jcheng5** [comment]
Introduce reactiveStop but don't bother with an article?

**Comment by bborgesr** [comment]
Got it

**Comment by wch** [comment]
As we discussed, for the next release, we'll just implement this by having `req(FALSE, cancelOutput=TRUE)`, and we'll remove the `cancelOutput()` function.

In the future we'll revisit the idea of adding `reactiveStop()`.

**Comment by bborgesr** [comment]
So, I'm working on nice examples now, so I was reading though the `req` article to try to make it consistent with the exmaples we have there. Came across this comment thread there:

> **Donald Jackson • 3 months ago** 
> *req() is useful - but what if you don't want your app to stop? I often have situations when I want to implement alternative actions based on whether or not an input is defined... It looks like the internal shiny function _isTruthy()_ provides this but isn't exported. Being able to access that function would be helpful!*
> 
> **Nic Crane > Donald Jackson • 24 days ago**
> *Donald - you can access internal functions using the triple colon operator, e.g. shiny:::isTruthy()*
> 
> **Donald Jackson  > Nic Crane • 24 days ago**
> *Awesome- thanks! This does exactly what I needed.*

Obviously, accessing internal functions is not good practice, but maybe he has a point here..? Should we export `isTruthy`?
