### ISSUE TITLE
Streamline Plot Saving

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1271]
Currently, the best way to save a plot, [according to one unofficial tutorial](https://github.com/aagarw30/R-Shinyapp-Tutorial/tree/master/how%20to%20download%20plot), involves code duplication of plotting commands between `renderPlot` and `downloadHandler` sections in the server file. This is not ideal for code maintenance. I'd like a more concise way to be possible. Of course, it's easiest to right-click and Save As for a PNG plot, but I am thinking about saving as PDF, which needs a download button, since browsers don't natively display PDF images.

**Comment by jcheng5** [comment]
The best thing to do is write a function (not a reactive) to do the plotting, and call it from both downloadHandler and output.
