### ISSUE TITLE
Remaining bookmarkable state issues

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#1273]
- [x] The `onBookmark`, `onBookmarked`, `onRestore`, and `onRestored` observers should print errors and stack trace to the console. UPDATE: It turns out that they already do this.
- [x]  In `ReactiveValues`, the `invalidate` and `uninvalidate` should be renamed to something less confusing.
- [x]  Calling `updateXxxInput` functions inside of the `onRestored` callback doesn't work because it puts things the `inputMessageQueue` after `session$flushOutput()` is called, but there's no `msg` to trigger another flush.

**Comment by bborgesr** [comment]
Oh man, more `updateXxxInput` bugs -- do you think this will be easy to fix, Winston? Or should it get added to our ever-increasing `updateXxxInput` bug list?

**Comment by wch** [comment]
The update-input thing has a very cause from other update-input issues, so I wouldn't worry about tagging it.
