### ISSUE TITLE
Improve graph drawing in reactive log visualizer

### ISSUE THREAD

**Issue by mattantaliss** [rstudio/shiny#1279]
I'm attempting to track down some reactive execution order issues in my large (and growing) shiny app. Ideally, I could open the app, let it finish initializing, open the reactive log visualizer to display a graph of all dependencies, and possibly print that graph for easier tracing. As is, the graph I get is too large and messy to be useful (let alone print); see attached screenshot. The visualizer should be improved to produce a more legible graph. 

Off-hand, I think a graph based on a three-column grid --- reactive sources in the left-most column, reactive conductors in the middle column, and reactive endpoints in the right-most column --- would be a good start. Then the number of overlapping edges would need to minimized and, if possible, adjustments may be needed for print-friendliness.

If such changes would be too difficult (or even in addition to these changes), could the "rubber-band" effect be removed so users can manually move nodes around to desired positions?

![reactive-graph](https://cloud.githubusercontent.com/assets/7633746/17530802/5ae34924-5e36-11e6-8b13-7da4595c46d7.png)

**Comment by bborgesr** [comment]
We're planning on improving the react graph in the future, somewhat according to the that same line of thinking (three-column grid, or some similar sort of partition). However, that is still a largish project and it is not in our current priority list, so it may be a while before that happens... In the meantime, you can use the branch `barbara/feature/reactlog` to be able to drag the nodes to a specific position and leave them there (you'll see the border around the node turn black -- that means it is in a fixed position). If you want to release the node back, just double click on it (you'll see the border around it go back to gray). Hope this helps you!

Note: to install `shiny` from a particular branch, you can use `devtools` as follows:

```r
devtools::install_github("rstudio/shiny@barbara/feature/reactlog")
```

cc @jcheng5

**Comment by bborgesr** [comment]
Update: this is now on `master`, so you can just use `devtools::install_github("rstudio/shiny")`

**Comment by bborgesr** [comment]
Closing for now. The sticky/draggable node feature has become part of the Shiny's latest CRAN version. The more ambitious project of experimenting with better visualizations for the reactive graph is certainly in our backlog.
