### ISSUE TITLE
xtable options not passed on

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#1289]
It seems that options passed to xtable no longer work with the development version of Shiny. Working example on shiny apps (click the triangle next to Names):

https://vnijs.shinyapps.io/coldcallr/coldcallr.Rmd

See https://github.com/vnijs/coldcallr/blob/master/coldcallr.R#L52-L58

colnames = FALSE works but include.colnames = FALSE does not
sanitize.text.function = identity does not seem to work

**Comment by vnijs** [comment]
Smaller example: https://gist.github.com/ramnathv/f476dd3751e672a96801

**Comment by bborgesr** [comment]
Oops, sorry about that! Should be fixed now... In the cases when you pass, for example, both `include.colnames` *and* `colnames`, the former takes precedence.

**Comment by vnijs** [comment]
Works! thanks @bborgesr
