### ISSUE TITLE
Non-breaking Spaces Ignored by Shiny but not Bootstrap

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1303]
When using `&nbsp;` in an ordnary HTML page with Bootstrap, it works as expected, but when using them in Shiny widget labels, there is no effect. For example,

    library(shiny)
 
    ui = shinyUI(fluidPage(
      div(id = "one", selectizeInput("columns", "Choose&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;One", LETTERS[1:5])),
      div(id = "two", textInput("values", "Describe:")),
    ))
    
    server = shinyServer(function(input, output, session){})
    
    shinyApp(ui = ui, server = server)

If it worked, it would enable easy alignment of `textInput` elements with and without labels, placed across a row.

The following Bootstrap-styled HTML works with non-breaking spaces in labels.

	<html>

	<head>
	<title>Title</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	</head>

	<body>

	<p>An input is below:</p>

	<label for="basic-url">Your vanity&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;URL</label>
	<div class="input-group">
	  <span class="input-group-addon" id="basic-addon3">https://example.com/users/</span>
	  <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3">
	</div>

	</body>
	</html>

**Comment by wch** [comment]
If you want to use raw HTML, you'll have to wrap it in `HTML()`, as in `selectizeInput("columns", HTML("Choose&nbsp;&nbsp;&nbsp;One"), LETTERS[1:5])`.
