### ISSUE TITLE
Hover is broken on chrome 52.0.2743.116 m

### ISSUE THREAD

**Issue by DavidGriswoldCPM** [rstudio/shiny#1307]
On Chrome version 52.0.2743.116m (current stable), hover is not working on plots. This can be seen in the Shiny gallery, [http://shiny.rstudio.com/gallery/plot-interaction-basic.html]. This may be a Chrome bug, but a google search did not uncover a systemic problem.

**Comment by jcheng5** [comment]
Hmmm, that example is working for me on that exact version of Chrome, on OS X 10.11.6. Does anything change if you make your browser window as wide as you can and try again?

**Comment by DavidGriswoldCPM** [comment]
I'm on Windows. Tried it with a wide variety of window sizes. Nothing. Here's a brief screen capture: I use chrome for the first 30 seconds or show, and you can see it doesn't work, then I show the version number. I then pull up Edge and Firefox to show it works fine there.

[http://www.youtube.com/watch?v=l-vX9N1D2TY]

**Comment by DavidGriswoldCPM** [comment]
I just checked, and it's not working on the latest Chrome Canary 64 bit for windows either. Fresh download. Version 54.0.2831.0 canary (64-bit)

**Comment by wch** [comment]
Hm, I'm not able to reproduce this. I tried it with Version 52.0.2743.116 m (64-bit) in a virtual machine. Here's a screenshot:

![virtualbox_msedge - win10_preview_18_08_2016_12_00_25](https://cloud.githubusercontent.com/assets/86978/17782937/6065e0c6-653b-11e6-82a4-229ec1fd7685.png)

If you open the Javascript console (Ctrl-Shift-J), does it say anything?

Also, if you have another Windows computer available, are you able to reproduce the problem on it?

**Comment by DavidGriswoldCPM** [comment]
I poked around some more and discovered the issue - it was actually a conflict between Chrome and an app I installed for controlling my mouse with a gamepad, gopher. No idea why this breaks chrome and not firefox. Sorry for wasting your time, but if anybody is out there googling for this, try closing gopher out!

**Comment by wch** [comment]
I suspected it had something to do with a mouse driver. Glad it's figured out now!
