### ISSUE TITLE
Process downloadHandler in background to avoid empty window/tab

### ISSUE THREAD

**Issue by fabiangehring** [rstudio/shiny#1326]
When generating and downloading a report with shiny (i.e. http://shiny.rstudio.com/gallery/download-knitr-reports.html) a new blank tab / window is opened in most browsers.

To avoid this, I use "Ctrl + Click" to download in the background. 
An option "background" in downloadHandler would be nice to do this without pressing "Ctrl".

**Comment by bborgesr** [comment]
Note to self: there also seems to be some weird interaction between iframe embedding and download mechanics, i.e. see https://gallery.shinyapps.io/010-download/ (it opens the app in the new tab and then downloads the file)... Not sure if this has always been the case or if we broke this recently...

**Comment by wch** [comment]
It looks like we just need to add `download=NA` to the `a()` call.

**Comment by bborgesr** [comment]
Closed in #1473
