### ISSUE TITLE
Github version breaks my code with dynamic UI rendering

### ISSUE THREAD

**Issue by incivile** [rstudio/shiny#1340]
Hello,

I've just installed the fresh GitHub version (13.2.9005) of Shiny and it broke my code. I'm rendering "wrapper containers" on the fly and right after I'm filling them with plots. With the old (i.e. CRAN) version (0.13.2) everything was working well, but now it seem like the 'renderPlot' is executed before the 'wrap' output is rendered, so it fills the old one and then it's overwritten with an empty 'wrap'.
Can I trigger the "fill" renderPlot somehow else then with a reactive value (something like "onRenderComplete")?

See this simple example:

```
library(shiny)

ui <- fluidPage(
    sliderInput("size", NULL, min = 10, max = 20, value = 15),
    actionButton('print', 'print'),
    uiOutput('wrap')
)

server <- function(session, input, output){
    react_valves <- reactiveValues()
    
    output$wrap <- renderUI({
        input$print
        react_valves$wrap_rendered <- runif(1)
        plotOutput('fill', height = isolate(input$size) * 100, click = clickOpts(id = "fill_click"))
    })
    
    output$fill <- renderPlot({
        react_valves$wrap_rendered
        plot(1:10, cex = 1.2)
    })
}

shinyApp(ui, server)
```

**Comment by bborgesr** [comment]
@wch this was working yesterday... it has to do with plot redrawing, so I'm pretty sure it has to do with what you've been working on. I'm on my phone right now, so can't elaborate a lot. I can either continue to look at it or you can take over if you prefer... Good news is that it doesn't have anything to do with dynamic UI rendering...

**Comment by wch** [comment]
@incivile Can you install the `fix-replay-plot` branch and try the app again?

```R
devtools::install_github('rstudio/shiny@fix-replay-plot')
```

**Comment by bborgesr** [comment]
I can confirm this fixes it.

**Comment by wch** [comment]
Great. @incivile the branch has been merged into master, so you can just install from github the usual way.
