### ISSUE TITLE
jquery-ui 1.11.4 datepicker has bad interaction with bootstrap datepicker

### ISSUE THREAD

**Issue by dvetal** [rstudio/shiny#1346]
We have an app where we are trying to include both a dateRangeInput selector and a ggvisOutput for a graph in the same page.  This seems to not work at this time.  The underlying cause for this is that there seems to be a bad interaction between jquery-ui's datepicker and the bootstrap datepicker.  Below is a minimal example for how to reproduce the problem. As I've not really spent a lot of time in front-end dev I'm just not sure I'm equipped to fix this (yet).

WHAT IS EXPECTED:
Both the date range picker and the ggvis plot should be able to be displayed on the same page with data filled in.

HOW TO REPRODUCE:
server.R file:
```
shinyServer( function(input, output) 
{
  mtcars_reactive <- reactive({ mtcars })
  mtcars_reactive %>% ggvis(~wt, ~mpg) %>% layer_points() %>% bind_shiny("plot")
}
```

ui.R file:
```
shinyUI(fluidPage(
dateRangeInput('dateRange', label = 'Date range: ', start = '2016-08-15', end = '2016-08-25', max = '2016-08-26'),
ggvisOutput('plot')
)
)
```
The effect should be that no data will load in the data range picker and the plot will not show up.  If you remove either component from the ui.R file the remaining component will show up as expected.

Inspecting the DevTools in Chrome I can confirm both jquery-ui's datepicker and bootstrap datepicker are being loaded in this scenario.  Another note is that this app previously worked before 0.13.2

**Comment by dvetal** [comment]
Someone else seems to have been able to reproduce as well https://groups.google.com/forum/#!msg/shiny-discuss/YF_y4Ie53K4/nchrDm6l4jgJ

**Comment by wch** [comment]
This is related to #1107, except that in this case, the jquery-ui is coming from ggvis.

It looks like Bootstrap Datepicker now has a noconflict option, so we may be able to finally fix this. https://bootstrap-datepicker.readthedocs.io/en/stable/index.html#no-conflict-mode

**Comment by wch** [comment]
For future reference, here's the example as a single-file app:

```R
library(shiny)
library(ggvis)

server <- function(input, output) {
  mtcars_reactive <- reactive({ mtcars })
  mtcars_reactive %>% ggvis(~wt, ~mpg) %>% layer_points() %>% bind_shiny("plot")
}

ui <- fluidPage(
  dateRangeInput('dateRange', label = 'Date range: ', 
    start = '2016-08-15', end = '2016-08-25', max = '2016-08-26'),
  ggvisOutput('plot')
)

shinyApp(ui, server)
```
