### ISSUE TITLE
redraw plotly using R shiny

### ISSUE THREAD

**Issue by AleksandrIanevski** [rstudio/shiny#1349]
I recently faced the problem of redrawing 3d surface using R shiny.
The surface is depicted by clicking the button which calls `renderPlotly` function.
Everything works fine until it comes to redrawing the surface.
When I am trying to draw a new surface instead of first one or simply depicting second surface in another box (by calling `renderPlotly` ) something goes wrong.
Even the app is still working, the browser gives infinite number of the same errors, one of which shown below. 
If I draw other plots like ggplot, they are converted to the png pictures and of course no problems occur.
I suppose it could be related to WebGL context, for I am trying to draw more than one plotly surface.

Is it possible to release WebGL context before redrawing plotly graph? or update plotly plot, without drawing a new plotly graph from R shiny.

Thanks.

```
plotly.js:57 Uncaught TypeError: Cannot read property '71' of undefinedattachKey @ plotly.js:57(anonymous function) @ plotly.js:61(anonymous function) @ plotly.js:42n.emit @ plotly-latest.min.js:9t.emit @ plotly-latest.min.js:31n @ plotly-latest.min.js:37b @ plotly-latest.min.js:19x @ plotly-latest.min.js:19
plotly.js:57 Uncaught TypeError: Cannot read property '58' of undefinedattachKey @ plotly.js:57(anonymous function) @ plotly.js:61(anonymous function) @ plotly.js:42n.emit @ plotly-latest.min.js:9t.emit @ plotly-latest.min.js:31n @ plotly-latest.min.js:37b @ plotly-latest.min.js:19x @ plotly-latest.min.js:19
```
The above errors are applicable to Chrome and IE.

In Firefox there is no such a behavior(infinite number of errors) , only one error and few warnings:

`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create `

```
plotly-latest.min.js:8:23171
Error: Permission denied to access property "type" : m.event.add/r.handle()
 jquery.min.js:4:5184
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead. <unknown>

```

**Comment by wch** [comment]
This sounds like a bug that should be filed with plotly at https://github.com/ropensci/plotly/issues. cc @cpsievert

**Comment by AleksandrIanevski** [comment]
I have opened this issue in suggested forum. Thanks
