### ISSUE TITLE
07_widgets example shouldn't use submitButton

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#1355]

**Comment by wch** [comment]
It would also be good to update the `submitButton` documentation to encourage use of `actionButton` instead of `submitButton`.

Also, the corresponding app in shiny-examples should be updated to match.

**Comment by bborgesr** [comment]
Also, update the article http://shiny.rstudio.com/articles/action-buttons.html to include a paragraph of when it *is* appropriate to use a submit button (and include tiny example)
