### ISSUE TITLE
verbatimTextOutput should be hidden if no content

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#1357]
Right now, verbatimTextOutput renders as an empty, squat rounded rectangle if it contains no content (even `req(FALSE)`). Better if it doesn't appear at all if it doesn't contain content. (Though we'd have to make sure it doesn't get accidentally marked as hidden from the shiny perspective, and stop rendering)

**Comment by wch** [comment]
I think it should be an option, in case the app author wants a placeholder to appear even when there's no content.
