### ISSUE TITLE
Give warning when runApp is called within runApp

### ISSUE THREAD

**Issue by burgerga** [rstudio/shiny#1358]
EDIT: sorry, figured out the real problem, the 'Run App' button calls runApp with as argument the directory, however if you have an `app.R` with some custom `shinyApp` calls it fails. So in the example below if you simple select all and execute, it works fine. But you should not use the 'Run App' button. 

In the documentation for `shinyApp` one of the examples  shows how to make a shinyApp from an 'an explicit UI/server pair', however this example doesn't work. The example in question is 

```
app <- shinyApp(
  ui = fluidPage(
    numericInput("n", "n", 1),
    plotOutput("plot")
  ),
  server = function(input, output) {
    output$plot <- renderPlot( plot(head(cars, input$n)) )
  }
)

runApp(app)
```

which fails with 

```
Listening on http://127.0.0.1:3280
Warning: Error in handlers$add: Key / already in use
Stack trace (innermost first):
    43: handlers$add
    42: handlerManager$addHandler
    41: startApp
    40: runApp
     1: shiny::runApp
Error in handlers$add(handler, key, tail) : Key / already in use
```

**Comment by wch** [comment]
This works fine for me. I've seen that error before when reloading shiny in a development session. If you used `install_github`, something similar may have happened. Try restarting your R session and running it again.

**Comment by wch** [comment]
Oh wait, I just saw your edit. So you're calling `runApp()` inside of another `runApp()`? If that's the case, we could provide a more informative error message.

**Comment by burgerga** [comment]
Yes, I think that's what's happening. Would also explain the error the error message, since `/` is the default argument for `uiPattern` and then it tries to start 2 apps, both with `uiPattern = "/"`. But I agree that the error could be clearer. 

PS What I ended up doing is renaming the file (no longer `app.R`, then the button goes away ;) )
