### ISSUE TITLE
shinyApp options argument ignored when passed to runApp

### ISSUE THREAD

**Issue by burgerga** [rstudio/shiny#1359]
In the below example the app is not opened in the external browser, maybe this can be made clear in the documentation for shinyApp, or (preferable IMO, but more work) let runApp read the options from the app if an app object is passed.

```
app <- shinyApp(
  ui = fluidPage(
    numericInput("n", "n", 1),
    plotOutput("plot")
  ),
  server = function(input, output) {
    output$plot <- renderPlot( plot(head(cars, input$n)) )
  },
  options = list(display.mode="showcase", launch.browser=T)
)
runApp(app)
```

**Comment by burgerga** [comment]
alternative is telling people to run it like `app` (print mode)

**Comment by jcheng5** [comment]
Note to implementer:

1. Don't forget to check if runApp has explicit arguments, these should override options in the shinyApp object
2. If this ends up being complicated/risky, punt to v.next
