### ISSUE TITLE
shiny failed to install due to 'sourcetools'

### ISSUE THREAD

**Issue by songyurita** [rstudio/shiny#1366]
This started to happen last Friday:ERROR: dependency 'sourcetools' is not available for package 'shiny'
* removing '/home/rsong/R/x86_64-redhat-linux-gnu-library/3.3/shiny'
Error: Command failed (1)
In addition: Warning message:
In install.packages(deps, dependencies = dependencies) :
  installation of package ‘sourcetools’ had non-zero exit status

I tried both install and git_install. I also tried install and git_install sourcetools, none of them worked. 

We are using shiny app from shiny server and it used to work till last Friday.

**Comment by kevinushey** [comment]
Do you have command line tools (`gcc` / `g++`) installed? What is the output of `g++ -v` on that machine?

You might need to install `sourcetools` from GitHub if your machine is older, e.g.

```
devtools::install_github("kevinushey/sourcetools")
```

**Comment by songyurita** [comment]
I tried devtools::install_github("kevinushey/sourcetools")
got error:
test-Parser.cpp:1:22: error: testthat.h: No such file or directory
test-Parser.cpp:11: error: expected constructor, destructor, or type conversion before '(' token
make: *** [test-Parser.o] Error 1
ERROR: compilation failed for package 'sourcetools'
* removing '/home/rsong/R/x86_64-redhat-linux-gnu-library/3.3/sourcetools'

gcc version:
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)

**Comment by kevinushey** [comment]
Can you execute the following and try once more?

```
install.packages("testthat")
devtools::install_github("kevinushey/sourcetools")
```

**Comment by kevinushey** [comment]
Actually, `sourcetools` successfully installs for me on a VM using gcc-4.4, so I suspect the only issue here was that you did not have `testthat` installed (although I'm surprised it was not installed automatically when attempting to invoke `install_github`).

Either way, I've submitted sourcetools v0.1.3 to CRAN, which will relax the C++11 requirement and make it easier to build on older machines.

**Comment by songyurita** [comment]
looks the problem is solved. Thanks for so fast response!

BTW, I have testthat installed before, but it didn't work until I reinstall the newest version. So I guess it is the version issue.

**Comment by kevinushey** [comment]
Great, thanks! I'll bump the version requirement in `sourcetools` to ensure an updated version of `testthat` is installed alongside as well.
