### ISSUE TITLE
Error after shiny update

### ISSUE THREAD

**Issue by hiltonmbr** [rstudio/shiny#1371]
Warning: Error in build: Tabs should all be unnamed arguments, but some are named: status
Stack trace (innermost first):
    92: build
    91: buildTabset
    90: shiny::tabsetPanel

**Comment by wch** [comment]
That means that you're using a named argument for `tabsetPanel` (or similar, like `navbarPage`) when it should not be a named argument. For example:


```R
# OK:
tabsetPanel(
    tabPanel("Plot", plotOutput("plot")),
    tabPanel("Summary", verbatimTextOutput("summary")),
)

# Not OK
tabsetPanel(
    x = tabPanel("Plot", plotOutput("plot")),
    tabPanel("Summary", verbatimTextOutput("summary")),
)
```

Previous versions of Shiny allowed the syntax used in the second example, but the new version is more stringent about what it allows.

**Comment by hiltonmbr** [comment]
Thanks. It was fixed!

**Comment by kmezhoud** [comment]
Hi,
I have the same issue. Are these wrong?
```
tabsetPanel(id = "tabs_Handle",
              tabPanel(
                "Manage", htmlOutput("htmlDataExample"),
                conditionalPanel("input.man_add_descr == false", uiOutput("dataDescriptionHTML")),

                conditionalPanel("input.man_add_descr == true", uiOutput("dataDescriptionMD"))),
              tabPanel("View",
                       downloadLink("dl_view_tab", "", class = "fa fa-download alignright"),
                       DT::dataTableOutput("dataviewer")),
......
```

````
 navbarMenu("Base",
    tabPanel("Probability calculator", uiOutput("prob_calc")),
    tabPanel("Central Limit Theorem", uiOutput("clt")),
````
Thanks

**Comment by wch** [comment]
@kmezhoud Can you provide a reproducible example?

**Comment by kmezhoud** [comment]
@wch It is a  R/Bioconductor package named [bioCancer](http://bioconductor.org/packages/devel/bioc/html/bioCancer.html). It is not easy to extract a sample of tabs.
Maybe [here](https://github.com/kmezhoud/bioCancer/blob/master/inst/base/tools/data/ui_data.R) is the main ui file where the app calls  all tabsetpanels.
Thanks,
Karim

**Comment by wch** [comment]
Thanks for the link to the code. Can you copy and paste the error message here?

**Comment by kmezhoud** [comment]
The error is also returned with server version : http://46.101.227.144:3838/bioCancer/?SSUID=5234d9e716

**Comment by wch** [comment]
Can you get the error message from the logs?

**Comment by kmezhoud** [comment]
sorry is not the same message
```
ERROR: Tabs should all be unnamed arguments, but some are named: id
```

console
```
Listening on http://127.0.0.1:3394
Warning: Error in build: Tabs should all be unnamed arguments, but some are named: id
Stack trace (innermost first):
    48: build
    47: FUN
    46: lapply
    45: build
    44: buildTabset
    43: <Anonymous>
    42: do.call
    41: shinyUI
     1: runApp
Error : Tabs should all be unnamed arguments, but some are named: id
```
the message comes from [here](https://github.com/rstudio/shiny/blob/master/R/bootstrap.R)

**Comment by wch** [comment]
I think it's because you're calling `navbarMenu()` with an `id` argument, as in:

```R
 navbarMenu(title = "", id = "Help", icon = icon("question-circle"))
```

But it should be:

```R
 navbarMenu(title = "", "Help", icon = icon("question-circle"))
```

**Comment by kmezhoud** [comment]
good catch,
I removed  ```id= ```in all ```navbarMenu```. Now it is OK.
I have to preserve ```id=``` in ```tabPanal``` and ```tabsetPanel```.  
thanks

**Comment by caitiecollins** [comment]
Hello, 

This problem starting happening to my code as well. It was working fine last I checked, but now I'm getting the aforementioned error. 

Here is my code: 
`output$tabBox_rawDataSummary <- shiny::renderUI({

  shinydashboard::tabBox(
    title=NULL,
    status='warning',
    width=12,
    shiny::tabPanel(
      title=HTML('<font size=4>Raw data table</font>'),
      DT::dataTableOutput("rawDataTable")
    ),
    shiny::tabPanel(
      title=HTML('<font size=4>Summary table</font>'),
      DT::dataTableOutput("rawDataSummary")
    )
  )
})`

And this is the error I now get: 
`Warning: Error in build: Tabs should all be unnamed arguments, but some are named: status
Stack trace (innermost first):
85: build
84: buildTabset
83: shiny::tabsetPanel
82: shinydashboard::tabBox
81: shiny::renderUI [server_input_data.R#397]
                     80: func
                     79: origRenderFunc
                     78: output$tabBox_rawDataSummary
                     3: shiny::runApp
`

I can resolve the error by removing the "status" argument line from the shinydashboard::tabBox function. But this means that I can no longer use this argument to select different colors for the sets of tabBox elements in my shiny apps. It was a nice feature and, as I said, this code was working fine previously. Do you know what I might be able to do to get this functionality back? 

Thanks very much,
- CC

**Comment by jcheng5** [comment]
@caitiecollins Do you mind filing an issue on the shinydashboard repo instead, please? https://github.com/rstudio/shinydashboard/issues/new
