### ISSUE TITLE
Numeric input doesn't work when the value contains both a space and a scientific notation number

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1372]
Use this basic app:

```
library(shiny)
ui <- fluidPage(
  numericInput('num', "num", "5")
)

server <- function(input, output, session) {
  observe(cat(input$num))
}

shinyApp(ui = ui, server = server)
```

Type as the value in the box:
- "5" --> "5"
- "1e3" --> "1000"
- "   5" --> "5"
- "   1e3" -->" NA"

Extremely low pri

**Comment by tmastny** [comment]
I think this is intended behavior for [Chrome and Safari browsers](https://stackoverflow.com/questions/18677323/html5-input-type-number-value-is-empty-in-webkit-if-has-spaces-or-non-numeric-ch/18678386). 

For example, on Chrome and Safari this code snippet
```html
<input id='no_space' type='number' value='123'>
<input id='end_space' type='number' value='123 '>
<input id='start_space' type='number' value='123 '>
```
only displays the values with no spaces: http://jsfiddle.net/j4yptbgk/5/

And
```js
>document.getElementById("end_space").value
<""
>document.getElementById("start_space").value
<""
>document.getElementById("no_space").value
<"123"
```

However, even between Chrome and Safari there are differences. For example, Chrome does not allow the user to enter spaces in the number input field. The user input is automatically converted as follows:
  - User input --> html tag value --> R output
  - " 1e3" --> "1e3" --> 1000
 - "1e3 " --> "1e3" --> 1000

On the other hand, Safari allows the user to assign numbers with spaces to the value, producing the expected "" results:
  - " 1e3" --> "" --> NA
  - "1e3 " --> "" --> NA
