### ISSUE TITLE
Shiny app works with "Run App" in RStudio but not with Rscript from Power Shell

### ISSUE THREAD

**Issue by jpmaldonado** [rstudio/shiny#1376]
Hi, 

We're working on a large Shiny app, consisting of several modules bound together in app.R. 

If we run it from RStudio, it works well, without errors. However, calling 

shiny::runApp(
  appDir = getwd(),
  port = getOption("shiny.port", 3503),
  host = getOption("shiny.host", "0.0.0.0"),
  workerId = ""
) 

from a separate script, we get 

Warning: Error in assign: variable names are limited to 10000 bytes
Stack trace (innermost first):
    46: assign
    45: wrapFunctionLabel
    44: public_bind_env$initialize
    43: Observable$new
    42: reactive
    41: templateServer
    40: server [/app/path/here]
     1: runApp
Error in assign(name, func, environment()) : 
  variable names are limited to 10000 bytes

how is it possible that the app runs from RStudio but not from Rscript?

**Comment by wch** [comment]
Could you provide a reproducible example or instructions for how to reproduce it?
