### ISSUE TITLE
Modal not working with shinythemes

### ISSUE THREAD

**Issue by jrowen** [rstudio/shiny#1377]
The new modal functionality isn't working with the `shinythemes` package.  In the example below, the modal box appears after clicking the Bookmark button, but it stays greyed and is not clickable.  The page needs to be refreshed to continue to use the app.

```
library(shiny)
library(shinythemes)

ui <- function(request) {
  navbarPage(title = "",
    theme = shinythemes::shinytheme("cerulean"),
    tabPanel("Plot",
      plotOutput("plot"),
      sliderInput("n", "Number of observations", 1, nrow(faithful), 100),
      bookmarkButton()
    )
  )
}

server <- function(input, output, session) {
  output$plot <- renderPlot({
    hist(faithful$eruptions[seq_len(input$n)], breaks = 40)
  })
}

enableBookmarking(store = "url")
shinyApp(ui, server)
```
![image](https://cloud.githubusercontent.com/assets/1530030/18635781/cf3e79da-7e4b-11e6-9d5f-ac4dd2409299.png)

**Comment by wch** [comment]
I've updated shinythemes to fix this. Can you try installing with:

```
# Restart R first, then:
devtools::install_github('rstudio/shinythemes')
```

And then test your app?

**Comment by jrowen** [comment]
The update fixed the issue.  Thanks.

**Comment by wch** [comment]
Great, glad to hear it. I'll get a release of shinythemes out soon.
