### ISSUE TITLE
Maximum update rate of reactive expressions

### ISSUE THREAD

**Issue by fbreitwieser** [rstudio/shiny#1386]
In my program I have a multi-selectize input to select data, often between 10 and 20 datasets. I merge the selected data, do some calculations on it, and return the results. This process takes a bit of time. When I then add or remove multiple (let's say 5) items from the selectize at once, the calculations are re-done 5 times, instead of waiting for a short while for my input to finish and doing one calculation.

Is there a way to either 
a) make the selectize wait for a certain time (like a second) before submitting the change to the server, or
b) make reactives re-calculate the results only at a certain rate

I tried to implement the later by caching the results, using reactiveValues to record the time of the last call, and invalidateLater if I returned a previous result. However, it does not work yet as I expected it.

**Comment by wch** [comment]
I think the solution for your case is to debounce it on the server side (you probably need to do something different with the `reactiveValues` and `invalidateLater`).

In the future, we'll address this when we do #1087.

**Comment by jcheng5** [comment]
Server-side debounce: https://gist.github.com/jcheng5/6141ea7066e62cafb31c

Or add an action button and force the user to explicitly tell you when they're done changing inputs.
