### ISSUE TITLE
Shiny reuses R process even if it's being killed due to "app_idle_timeout" - ECONNRESET

### ISSUE THREAD

**Issue by janzyka** [rstudio/shiny#1388]
When R process which representing the application is being killed due to "app_idle_timeout" and in the very same time new session gets connected the session is assigned to that process. The process then gets killed (KILL signal was already sent) and the session then gets error:

> The application exited unexpectedly.
> 
> read ECONNRESET

This can be seen in the server log on TRACE level:

> ^[[34m[2016-09-23 08:43:06.751] [TRACE] shiny-server - ^[[39mNo clients connected to worker **#3b701e601a6bd932**. Starting timer
> ^[[34m[2016-09-23 08:43:11.753] [TRACE] shiny-server - ^[[39mTimeout expired. Killing process.
> ^[[34m[2016-09-23 08:43:11.753] [TRACE] shiny-server - ^[[39m**Interrupting process on socket port 41531**
> ^[[34m[2016-09-23 08:43:11.753] [TRACE] shiny-server - ^[[39mSending SIGINT to 8094
> ^[[34m[2016-09-23 08:43:12.203] [TRACE] shiny-server - ^[[39m**Reusing existing instance**
> ^[[34m[2016-09-23 08:43:12.203] [TRACE] shiny-server - ^[[39m**Worker #3b701e601a6bd932 acquiring http port. 1 open HTTP connection(s), 0 open WebSocket connection(s).**
> ^[[34m[2016-09-23 08:43:12.203] [TRACE] shiny-server - ^[[39mProxying request: /?sessionId=54412_44232
> ^[[34m[2016-09-23 08:43:12.205] [TRACE] shiny-server - ^[[39mWorker #3b701e601a6bd932 releasing http port. 0 open HTTP connection(s), 0 open WebSocket connection(s).
> ^[[34m[2016-09-23 08:43:12.205] [TRACE] shiny-server - ^[[39mNo clients connected to worker #3b701e601a6bd932. Starting timer
> ^[[34m[2016-09-23 08:43:12.212] [TRACE] shiny-server - ^[[39m**Port 41531 returned**
> ^[[34m[2016-09-23 08:43:12.212] [TRACE] shiny-server - ^[[39mPort 41531 proxy closed
> ^[[34m[2016-09-23 08:43:12.212] [TRACE] shiny-server - ^[[39mNormal exit, deleting log file /var/log/shiny-server/CMapp3-shiny-20160923-084250-41531.log
> ^[[34m[2016-09-23 08:43:17.210] [TRACE] shiny-server - ^[[39mTimeout expired. Killing process.
> ^[[34m[2016-09-23 08:43:17.210] [TRACE] shiny-server - ^[[39m**Process on port 41531 is already gone**

**Comment by wch** [comment]
Hi, could you file this issue in the shiny-server repo? https://github.com/rstudio/shiny-server/issues

**Comment by janzyka** [comment]
Sure thing: https://github.com/rstudio/shiny-server/issues/246
