### ISSUE TITLE
htmldependency injection is sometimes asynchronous

### ISSUE THREAD

**Issue by bhaskarvk** [rstudio/shiny#1389]
Here's a working e.g. of a standalone htmlwidget (leaflet) with an onRender call.

https://gist.github.com/bhaskarvk/0c665350557e8ff79a9870cecc88f571

The idea is taken from https://gist.github.com/jcheng5/c084a59717f18e947a17955007dc5f92 to add a HTML dependency to leaflet on the fly and use it in `onRender`. 

Same code in Shiny 
https://gist.github.com/bhaskarvk/f3e3a609fa901b4fefea624fcb1d863a

But in this case, the `onRender` function is called before the dependency is attached to the widget, and hence fails. If I remove the `onRender` code then the map displays and the dependency is attached. But that is pointless as I can't use it.

**Comment by jcheng5** [comment]
(Changed title from "Shiny + htmlwidget w/ onRender Call" to "htmldependency injection is sometimes asynchronous")

**Comment by jcheng5** [comment]
It turns out that htmlDependency JS injection at runtime can be synchronous or asynchronous, depending on whether the script is on the same host as the referring page or on a different host. You can see this in the below example, if you toggle the Shiny renderUI between using `helloDepSameDomain` and `helloDepOtherDomain`; you'll see "hello / goodbye" and "goodbye / hello", respectively.

### www/hello.js
```javascript
alert('hello');
```

### app.R
```r
library(shiny)
library(htmltools)

helloDepSameDomain <- htmlDependency("hello", "1.0",
  src = c(href = "./"),
  script = "hello.js"
)

helloDepOtherDomain <- htmlDependency("hello", "1.0",
  src = c(href = "http://joecheng.com/private/"),
  script = "hello.js"
)

ui <- fluidPage(
  uiOutput("ui")
)

server <- function(input, output, session) {
  output$ui <- renderUI({
    attachDependencies(
      tags$script("
        alert('goodbye')
      "),
      helloDepSameDomain
      #helloDepOtherDomain
    )
  })
}

shinyApp(ui, server)
```

**Comment by jcheng5** [comment]
What this means is that it's almost never going to be a good idea to use a `htmlDependency(src = c(href = "http://..."))` for any dependency that's intended to be used with Shiny. I'm of half a mind to simply outlaw this from htmltools, or at least warn by default.

**Comment by hansglick** [comment]
I'm not sure I understand the key, but what would be an interesting alternative to make this kind of script, i.e. onRender function working in Shiny.

**Comment by jcheng5** [comment]
There's two problems today with `onRender` and Shiny. One is that there is simply a bug in htmlwidgets, which I've submitted a PR for: https://github.com/ramnathv/htmlwidgets/pull/237

The second is that if your `onRender` function depends on some `htmlDependency` (i.e. a JS library), you just need to make sure that the `src` of the `htmlDependency` isn't an absolute http URL (they almost never are; they're almost always a path to a directory on disk).

If you use the fixed version of htmlwidgets and don't use a remote `htmlDependency`, then there's no problem--it should all work.

**Comment by bhaskarvk** [comment]
Hmm, makes sense in that case to block URLs.

**Comment by hansglick** [comment]
Hi Joe,
Thanks for you quick answer, yes it's much more clearer to me now. 
If I understood everything, the release of the fixed htmlwidgets package depends on Ramnath Vaidyanathan, the author, right?
Bye!!

**Comment by jcheng5** [comment]
He's one of several people involved, the others are from RStudio.

**Comment by timelyportfolio** [comment]
Please don't disallow this functionality.  I use all the time for both Shiny and non-Shiny.

**Comment by jcheng5** [comment]
@timelyportfolio You're saying you use `htmlDependency` with remote URLs on a regular basis? Have you tried cases where the dependency isn't injected until `renderUI` time?

**Comment by jcheng5** [comment]
(I guess you can work around that with `packagename::dependency()` calls that must be included in the base UI object... gross, but if you really need it...)

**Comment by timelyportfolio** [comment]
@jcheng5, I usually attach `htmlDependency` to my `UI`, so in general in my use cases,  I do not inject at `renderUI`.  In the https://github.com/rstudio/rmarkdown/issues/794 use case, I have created a package [`googlefontR`](https://github.com/timelyportfolio/googlefontR) to ease use of Google Fonts in R.  For this to work correctly, the package relies on `c(href="")` to use the Google Fonts.

**Comment by hansglick** [comment]
Hi, Joe,
Thanks a lot for those precisions.
You re the best!

2016-10-05 15:48 GMT+02:00 timelyportfolio <notifications@github.com>:

**Comment by alandipert** [comment]
Closing because this appears to have been resolved; please don't hesitate to comment further or create an additional issue if I misunderstand.

**Comment by helgasoft** [comment]
A simple workaround for Shiny.  Download remote files first, then define dependency with local files, like so:
```
library(shiny)
library(htmltools)

helloDepSameDomain <- htmlDependency("hello", "1.0", 
     src = c(href = "./"), script = "hello.js"
)
helloDepOtherDomain <- htmlDependency("hello", "1.0",  
     src = c(href = "http://joecheng.com/private/"),  script = "hello.js"
)
# workaround  - substitute remote with local file
download.file('http://joecheng.com/private/hello.js', 'C:/Temp/hello.js', mode="wb")
helloLocalFile <- htmlDependency("hello", "1.0",
    src = c(file = normalizePath('C:/Temp')),  script = "hello.js"
)

ui <- fluidPage(
	uiOutput("ui")
)

server <- function(input, output, session) {
	output$ui <- renderUI({
		attachDependencies(
			tags$script("
        alert('goodbye')
      "),
			#helloDepSameDomain
			#helloDepOtherDomain
			helloLocalFile
		)
	})
}
shinyApp(ui, server)

```
