### ISSUE TITLE
Tab Switching support for menuSubItems

### ISSUE THREAD

**Issue by bairlie** [rstudio/shiny#1391]
When using sub items in a Shiny Sidebar tabs no longer switch when an item is selected in the sidebar. If the tabName is added to menuSubItem then that sub-item will no longer work, encountered this issue when using a fileInput as a menuSubItem. Managed to use a work-around specified in the following link: 

http://stackoverflow.com/questions/37595124/react-to-menuitem-tab-selection

Is it possible for this issue to be looked into at some point? Let me know if you need more information.

**Comment by wch** [comment]
This belongs in the shinydashboard repository. Can you file it there?
 https://github.com/rstudio/shinydashboard/issues
