### ISSUE TITLE
a weird bug related to javascript with non-ASCII chars in win7

### ISSUE THREAD

**Issue by shrektan** [rstudio/shiny#1395]
I will let the example to describe this:

### The chinese chars in the alert can't show correctly
```r
library(shiny)
runApp(
  shinyApp(
    ui = tagList(
      tags$head(tags$script("type = 'javascript/text'", "alert('中文')")), 
      "test"
    ),
    server = function(input, output) {}
  )
)
```
![image](https://cloud.githubusercontent.com/assets/8368933/18938618/793ccddc-862c-11e6-8edb-a8a7fec2927f.png)

### The chinese chars in the alert shows correctly

```r
library(shiny)
runApp(
  shinyApp(
    ui = tagList(
      tags$head(tags$script("type = 'javascript/text'", "alert('中文')")), 
      "中文"
    ),
    server = function(input, output) {}
  )
)
```
![image](https://cloud.githubusercontent.com/assets/8368933/18938631/986eac16-862c-11e6-9427-6c1a8057333b.png)

### my sessionInfo

```
R version 3.3.1 (2016-06-21)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.14

loaded via a namespace (and not attached):
 [1] R6_2.1.3        htmltools_0.3.5 tools_3.3.1     Rcpp_0.12.7     stringi_1.1.1   jsonlite_1.1   
 [7] digest_0.6.10   xtable_1.8-2    httpuv_1.3.3    mime_0.5    
```

**Comment by shrektan** [comment]
That is, if I want to include a script in the head, I have to explicitly include at least one Chinese Char in the `body`. Even if I use `uiOutput` which contains Chinese Chars, it won't work.

**Comment by jcheng5** [comment]
How are you launching the app--what is printed at the R console? (Something
like print(source("app.R")$value), or shiny::runApp("app.R")?)

**Comment by wch** [comment]
I think the root cause is actually a bug in R. I've tested this with R 3.3.1 in Windows with RGui and RStudio. I don't know if it happens in older versions of R.


If we create an ASCII string `x1`, its encoding is marked as `"unknown"`, and doing a `sub()` on that string with a UTF-8 replacement results in weird characters:

```R
x1 <- "a b c"
Encoding(x1)
# [1] "unknown"

replacement <- "中文"
Encoding(replacement)
# [1] "UTF-8"

(y1 <- sub("a", replacement, x1))
#[1] "ä¸­æ–‡ b c"
Encoding(y1)
# [1] "unknown"
```

If the starting string has Chinese characters, it'll be marked as UTF-8, and replacement works fine:

```R
x2 <- "a b c 中文"
Encoding(x2)
# [1] "UTF-8"

(y2 <- sub("a", replacement, x2))
# [1] "中文 b c 中文"
Encoding(y2)
# [1] "UTF-8"
```

It seems like the solution should be to mark the starting string as UTF-8, but apparently it doesn't work, and so the `sub()` gives weird characters:

```R
# Not possible to mark x1 as UTF-8
Encoding(x1) <- "UTF-8"
Encoding(x1)
# [1] "unknown"

(y3 <- sub("a", replacement, x1))
# [1] "ä¸­æ–‡ b c"
Encoding(y3)
# [1] "unknown"
```

I'll email R-devel about this.

**Comment by wch** [comment]
One more piece of info: marking the ending string as UTF-8 does seem to fix it. I think we'll have to add a workaround in htmltools to do this.

```R
x1 <- "a b c"
replacement <- "中文"

(y3 <- sub("a", replacement, x1))
# [1] "ä¸­æ–‡ b c"
Encoding(y3)
# [1] "unknown"

Encoding(y3) <- "UTF-8"
y3
# [1] "中文 b c"
```

**Comment by jcheng5** [comment]
If you do `runApp("app.R")` shouldn't the whole thing be marked as UTF-8 since we source as UTF-8?

**Comment by jcheng5** [comment]
^ `runApp("app.R")` doesn't help

**Comment by wch** [comment]
For future reference: https://stat.ethz.ch/pipermail/r-devel/2016-September/073208.html

**Comment by yihui** [comment]
This is the same problem and @wch provided the same solution that I used in the PR https://github.com/rstudio/htmltools/pull/64

**Comment by wch** [comment]
Looks like we're on the same page then. In this case, I think the fix needs to go into `renderDocument()`.

**Comment by shrektan** [comment]
@yihui I confirm this specific issue solved after updating the latest version of `htmltools`.

**Comment by shrektan** [comment]
However, I find another similar issue related to `bookdown`. When the external css file like abc.css contains Chinese Char, the Chinese Char in the css file copied to `_book/abc.css`, will become weird...

```css
body {
  font-family: "Source Sans Pro", "Helvetica Neue", Helvetica Neue, Helvetica, Arial, "微软雅黑", sans-serif;
}
```

So I will close this issue and file the issue in `bookdown`.

Thanks.
