### ISSUE TITLE
updateRadioButtons: names of choices vector get lost

### ISSUE THREAD

**Issue by scheddy** [rstudio/shiny#1396]
Hi all,
I noticed a problem when updating choices of radio buttons with a named vector: The names do not appear in the user interface. The issue occurred after updating to shiny 0.14.
Example:
```
library(shiny)
ui <- fluidPage(
  radioButtons("RadioButtons", "radio buttons",
               c("Item A"=1, "Item B"=2, "Item C"=3)),
  actionButton("update","update"),
  textOutput("selected")
)

server <- function(input, output, session) {
  observeEvent(input$update, {
    updateRadioButtons(session, "RadioButtons",
                       choices = c("Item X"=1, "Item Y"=2, "Item Z"=3))
  })
  
  output$selected <- renderText(paste("Selected:", input$RadioButtons))
}

shinyApp(ui, server)
```

In fix #1291 the line
`choices <- as.character(choices)`
was added. As far as I understand
`choices <- sapply(choices, as.character)`
would make a better job, since plain `as.character` strips the names.

**Comment by bborgesr** [comment]
Thanks for the great catch and also coming up with the solution!! A fix should be in soon - I'll close this issue when we merged it into master.

**Comment by scheddy** [comment]
Great! Thank you!
