### ISSUE TITLE
Module namespace issue?

### ISSUE THREAD

**Issue by happyshows** [rstudio/shiny#1399]
I'm very confused in the following SO question I encountered, can someone help here?
My code structure is pretty close to the [example](https://gallery.shinyapps.io/insertUI-modules/) , however my code always trigger an error '_Uncaught Duplicate binding for ID_'

[SO Question](http://stackoverflow.com/questions/39737031/improve-the-robustness-of-shiny-module)

**Comment by jcheng5** [comment]
Thanks Shows!

Here's a more minimal repro. It seems to require both `insertUI` and nested `uiOutput`.

```r
library(shiny)

nestedUI <- function(id) {
  ns <- NS(id)
  
  uiOutput(ns("one"))
}

nested <- function(input, output, session) {
  output$one <- renderUI({
    uiOutput(session$ns("two"))
  })
  
  output$two <- renderUI({
    "Hello"
  })
}

ui <- fluidPage(
  actionButton("btn_zero", "zero"),
  div(id = "ui_zero")
)

server <- function(input, output, session) {
  counter <- 1
  
  observeEvent(input$btn_zero, {
    id <- paste0("c", counter)
    counter <<- counter + 1
    insertUI("#ui_zero", "beforeEnd", nestedUI(id))
    callModule(nested, id)
  })
}

shinyApp(ui, server, options = list(launch.browser = TRUE))
```

**Comment by jcheng5** [comment]
I have a feeling it may have something to do with the fact that `shinyapp.bindOutput` calls `onValueChanged` or whatever, before the output element has received the CSS class that indicates it's already bound (that happens in `exports.bindOutput`, which calls `shinyapp.bindOutput`).

**Comment by jcheng5** [comment]
This seems relevant https://github.com/rstudio/shiny/blob/565eb4b450b5f7620d2ca1938374074418b07740/inst/www/shared/shiny.js#L3100-L3109

**Comment by happyshows** [comment]
thanks Joe, could you provide an ETA on this fix? I am having a public showcase on r shiny mid Oct, and the core of my solution design is shiny modules, really appreciate this can be fixed a few days prior to that.

**Comment by jcheng5** [comment]
I'm digging around. If I can figure it out I will fix it immediately.

**Comment by jcheng5** [comment]
@happyshows I have a PR here: https://github.com/rstudio/shiny/pull/1402

It's a quite low-level change though, and @wch is in the final stages of prepping Shiny v0.14.1 for CRAN, so it may not make this release. Is it going to be a problem for you to install from GitHub until the following CRAN release?

**Comment by happyshows** [comment]
I don't have problem in using dev version, thanks for the quick fix.
