### ISSUE TITLE
Bookmark URL won't respond to eventReactive

### ISSUE THREAD

**Issue by cinkie** [rstudio/shiny#1400]
UI of my app is rendered when user clicks the button by using eventReactive.

When adding the bookmark, it only feeds the input text box but the result panel wouldn't show up.

Is there anyway to work around that?

Thanks!

**Comment by jcheng5** [comment]
Thanks for the report. Can you provide a reproducible example?

**Comment by cinkie** [comment]
I was trying to put up a replicate example but it works well in the simple example.  The actual app is much more complicated than that and we also use RSQLite as backend database. The error message I got from the actual app is 

> Error in RestoreContext initialization: Failed to parse URL parameter "output_acsn_search"

But in the server.r there isn't a input or output called `"output_acsn_search"`. There is a DT output called `"output_acsn"` but I don't know where does the `"_search"` coming from.

**Comment by bborgesr** [comment]
If you could somehow give us as small an example as possible where the error occurs, we could try to see where the problem is coming from...

**Comment by cinkie** [comment]
Hi, I found the issue is with a `eventReactive` wrapper function that returns a list of objects. Changing that to `reactive` and bookmark works. Still not sure why it doesn't work with `eventReactive`.

**Comment by wch** [comment]
Ah, the original problem is that the result of `hist()` is not something that can be returned from a function. The image itself is a *side-effect* of calling the `hist()` function.

For example, if you do this from the R console, you'll see that `x` isn't the plot, but instead it's a list (though it happens to have the class `"histogram"`).

```R
x <- hist(rnorm(120))
x
# $breaks
#  [1] -3.0 -2.5 -2.0 -1.5 -1.0 -0.5  0.0  0.5  1.0  1.5  2.0  2.5
# 
# $counts
#  [1]  1  2  5 21 22 17 23 15  7  5  2
# 
# $density
#  [1] 0.01666667 0.03333333 0.08333333 0.35000000 0.36666667 0.28333333 0.38333333
#  [8] 0.25000000 0.11666667 0.08333333 0.03333333
# 
# $mids
#  [1] -2.75 -2.25 -1.75 -1.25 -0.75 -0.25  0.25  0.75  1.25  1.75  2.25
# 
# $xname
# [1] "rnorm(120)"
# 
# $equidist
# [1] TRUE
# 
# attr(,"class")
# [1] "histogram"
```

See #872 and #781 for more information about this, and some workarounds.

**Comment by cinkie** [comment]
@wch  Thanks! The issue wasn't really with `hist`. The `eventReactive` in my app returns a list of dataframes. I think the problem might be the `actionButton` in my app. Also I need to detele a lot of info in the bookmark URL to make the URL work.

This is the closest one I put together with all the dependencies in my app. But the `eventReactive` works with bookmark URL here. So not really sure where the issue coming from.

```
library(shiny)
library(plotly)
library(shinydashboard)
ui <- function(request) {
    dashboardPage(
        dashboardHeader(title = "Test"),
        dashboardSidebar(disable = T),
        dashboardBody(
            fluidPage(
                textInput("n", "Number of observations"),
                actionButton("goButton", "Go!"),
                actionButton("resetButton", "Reset"),
                bookmarkButton(),
                conditionalPanel(
                    condition = "input.goButton",
                    uiOutput("plotArea")
                )
            )
        )
    )
}
server <- function(input, output, session) {
    observeEvent(input$resetButton, {
        updateTextInput(session, "n", "Number of observations", NA)
    })
    
    getN <- eventReactive(input$goButton, {
        new_n = plyr::round_any(as.numeric(input$n), 10)
        return(list(new_n = new_n))
    })
    
    output$plot <- renderPlotly({
        plot_ly(x = faithful$eruptions[seq_len(getN()$new_n)], type = "histogram", nbinsx = 30)
    })
    
    output$table <- DT::renderDataTable(
        data.frame(datapoint = faithful$eruptions[seq_len(getN()$new_n)])
    )
    
    output$plotArea <- renderUI({
        validate(
            need(as.numeric(input$n) < 50,"Please enter a number < 50.")
        )
        list(
            fluidRow(
                box(width = 8, title = "Histogram",plotlyOutput('plot')
                ),
                box(width = 4, title = "Table", DT::dataTableOutput('table'))
            )
        )
    })
}
enableBookmarking(store = "url")
shinyApp(ui, server)
```
