### ISSUE TITLE
HTML5 data-* tag cannot be included in ui.R

### ISSUE THREAD

**Issue by Stophface** [rstudio/shiny#1405]
I want to use the `HTML5 data-*` tag which is, according to the [docs](http://shiny.rstudio.com/articles/tag-glossary.html), supported.
However, when I include

    tags$div(class = "testing-class", data-value = "1", id = "test", "Test")

The app does not start. I get an error 
> Stack trace (innermost first):
>    1: shiny::runApp
> Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
>  .../ui.R:7:61: Unexpected '='
> 6:                 mainPanel(
> 7:                         tags$div(class = "test", data-value =

    ui.R
    library(shiny)
    shinyUI(fluidPage(
        mainPanel(
            tags$div(class = "sweet-little-kitten", data-value = "wuff", id = "my-sweet-little-kitten", "miau")
                )
            )
    )

    server.R
    library(shiny)
    shinyServer(function(input, output) {
    })

**Comment by bborgesr** [comment]
Thanks for the report. Thankfully, the fix is easy: use backticks.

```r
tags$div(class = "testing-class", `data-value` = "1", id = "test", "Test")
```

This is necessary because the attribute name includes a dash -- I'll update the docs to include a sentence about this.

**Comment by jcheng5** [comment]
+1, and single- and double-quotes also work.

**Comment by Stophface** [comment]
Thanks!
