### ISSUE TITLE
ERROR: pandoc document conversion failed with error 1

### ISSUE THREAD

**Issue by happyshows** [rstudio/shiny#1407]
@jcheng5

Hi Joe ,

I encountered an issue when using rmarkdown::render on shiny to create a self contained document.

Firstly, I can run the gist locally on my desktop without any error message and generate html. The issue will appear after I deploy the app to server and run it on web.
The error msg is:
> ERROR: pandoc document conversion failed with error 1

Below is the error log I pulled from shiny server pro:
```
Listening on http://127.0.0.1:45076
processing file: report.Rmd
output file: report.knit.md

pandoc: Could not determine mime type for `/usr/lib64/R/library/rmdformats/templates/bootstrap-3.3.6/css/../fonts/glyphicons-halflings-regular.woff2'
Stack trace (innermost first):
    51: pandoc_convert
    50: convert
    49: rmarkdown::render
    48: download$func [/home/shiny_admin/Dev/ISC/Labs/miniExample/app.R#12]
     1: runApp
Error : pandoc document conversion failed with error 1
Warning in run(timeoutMs) :
  MathJax doesn't work with self_contained when not using the rmarkdown "default" template.
Warning in run(timeoutMs) :
  Error in : pandoc document conversion failed with error 1
```

The package version in my desktop and server are almost identical, except for pandoc, my desktop is running on 1.17 while server is on 1.12, which still meets the minimal requirement of latest rmarkdown.
other attached packages:
```
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmdformats_0.3    knitr_1.14        rmarkdown_1.0     shiny_0.14.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6     bookdown_0.1    digest_0.6.10   mime_0.5       
 [5] R6_2.1.3        xtable_1.8-2    magrittr_1.5    evaluate_0.9   
 [9] highr_0.6       stringi_1.1.1   rstudioapi_0.6  miniUI_0.1.1   
[13] tools_3.3.0     questionr_0.5   stringr_1.1.0   httpuv_1.3.3   
[17] htmltools_0.3.5
```

Initially, I thought it's related to pandoc, but I can knit the same Rmd file properly in R console:
```
> library(rmarkdown)
> render('report.Rmd')


processing file: report.Rmd
  |.................................................................| 100%
  ordinary text without R code


output file: report.knit.md

/tool/pandora64/bin/pandoc +RTS -K512m -RTS report.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output report.html --smart --email-obfuscation none --self-contained --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --variable 'lightbox:true' --variable 'thumbnails:true' --variable 'gallery:false' --standalone --section-divs --template /usr/lib64/R/library/rmdformats/templates/html_docco/html_docco.html --variable 'theme:bootstrap' --include-in-header /tmp/Rtmp37WGzl/rmarkdown-str42371a78e28b.html --highlight-style pygments --variable navigationjs=/usr/lib64/R/library/rmarkdown/rmd/h/navigation-1.1

Output created: report.html
Warning message:
MathJax doesn't work with self_contained when not using the rmarkdown "default" template.
```

When I replace the template from rmdformats::docco to html_document, minimal example renders fine, but in my original case (prior to the minimized example), html_document template runs on my desktop but not on server.

In addition, I have encountered when the log says:
> pandoc: Could not determine mime type for `/usr/lib64/R/library/shiny/www/shared/bootstrap/css/../fonts/glyphicons-halflings-regular.woff2'
https://github.com/juba/rmdformats/issues/20

Hence I'd not conclude it's not related to shiny. I believe it could be hybrid issue between shiny & rmarkdown, but I can't provide more information for debugging beyond this point.

[minimal example code on gist](https://gist.github.com/happyshows/6b86bc553b9432c5dded3c38763897ac#file-report-html)

**Comment by jcheng5** [comment]
Do you know what version of SSP? `shiny-server --version`

**Comment by happyshows** [comment]
I tried on both my dev and prod box, they are on 1.4.4 & 1.4.6 726 respectively

**Comment by jcheng5** [comment]
Hmmm. I don't get a repro on Ubuntu 16.04, SSP 1.4.6.726. Is your rmdformats package the same version that's on CRAN?

Also, are you pointing to some custom build of Pandoc? I'm just using the default configuration, where SSP uses its own bundled Pandoc 1.12.3.

**Comment by happyshows** [comment]
Hi Joe,

My linux version is RHEL and rmdformats 0.3 is from github.
I believe SSP is using the default Pandoc 1.12 as there are 1.17 pandoc on my linux box and not being used. (but I don't know how to change the pointer)

There's an update on the other [ticket](https://github.com/juba/rmdformats/issues/20) but I am not certain it's the root cause.

If this issue is truly because of pandoc version, maybe the default bundle should be upgraded to 1.17 since it's more than 18 months old?

**Comment by happyshows** [comment]
I'm closing this issue after I created a symbolic link to the Pandora version 1.17 that's available on my server box.
It might be a good idea to upgrade the bundled pandoc version to 1.17 so that such confusion could be avoided in future. @jcheng5
