### ISSUE TITLE
dateInput shows behind modalDialog

### ISSUE THREAD

**Issue by jbryer** [rstudio/shiny#1408]
If you put a dateInput in a modalDialog, the calendar overlay will show behind the dialog box. 

![modaldatebug](https://cloud.githubusercontent.com/assets/623759/19121336/0ca5fd5c-8af4-11e6-9c6d-88737a8fb79b.png)

Here is a reproducible example:

```
library(shiny)
server <- function(input, output) {
	observeEvent(input$show, {
		showModal(modalDialog(
			title = "Date Input",
			dateInput('dateinput', 'Select a date', value=Sys.Date()),
			size='s'))
	})
}

ui <- fluidPage(
	actionButton("show", "Show modal dialog")
)

shinyApp(ui = ui, server = server)
```

**Comment by bborgesr** [comment]
@jbryer, thanks for the report. Unfortunately, I cannot reproduce this with either Shiny's CRAN version or the development version. Everything seems to work fine in both cases:

![screen shot 2016-10-18 at 8 47 42 am](https://cloud.githubusercontent.com/assets/6527540/19468698/b7034096-950f-11e6-82c5-cee54ae8d65d.png)

Could you please confirm that you are still getting this behavior and, if so, give me some more details (maybe let's start with `devtools::session_info()`)? Make sure that you are running the app in a clean R session, so we can be certain that there isn't anything weird about your local environment.

Thanks!

**Comment by jbryer** [comment]
Thanks for looking intothis @bborgesr . It looks like the issue has been resolved in the latest version of shiny.

**Comment by vishalsharma3003** [comment]
If it occurs in future, try with the following:

tags$style(type = "text/css", ".datepicker { z-index: 99999 !important; }")

just before the dateinput. This even works for shinyWidgets::airDatepickerInput.

Enjoy!!

**Comment by jordanwebb10** [comment]
@vishalsharma3003 

I'm not able to replicate your suggestion. Do you have any suggestions? 

`library(shiny)
ui <- fluidPage(
  titlePanel("Old Faithful Geyser Data"),
  sidebarLayout(
    sidebarPanel(),
    mainPanel(
      actionButton("button", "Button")
    )
  )
)

server <- function(input, output) {
  observeEvent(input$button, {
    showModal(modalDialog(
      title = "Modal",
      tags$style(type = "text/css", ".datepicker { z-index: 99999 !important; }"),
      shinyWidgets::airDatepickerInput(
        "date", 
        label = NULL, 
        clearButton = T,
        minDate = "2000-01-01", 
        maxDate = Sys.Date()
      )
    ))
  })
}
shinyApp(ui = ui, server = server)`
