### ISSUE TITLE
height="auto" does not work for plotOutput

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1410]
If we specify `height = "auto"` in a `plotOutput`, it will not render anything (no issue with `width = "auto"`). E.g. here nothing appears on the screen:

``` r
library(shiny)

ui <- plotOutput("plt", height = "auto")

server <- function(input, output, session) {
  output$plt <- renderPlot({
    plot(cars)
  })
}

shinyApp(ui = ui, server = server)
```

But if we use "300px" or some other valid css unit, it's fine:

``` r
library(shiny)

ui <- plotOutput("plt", height = "300px")

server <- function(input, output, session) {
  output$plt <- renderPlot({
    plot(cars)
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by bborgesr** [comment]
We just need to make this clear in the documentation and then make sure to fail or at least warn if this is the case.

**Comment by DarioS** [comment]
It already is described in the documentation. `?plotOutput` shows

> Note that, for height, using ‘"auto"’ or ‘"100%"’ generally
          will not work as expected, because of how height is computed
          with HTML/CSS.

It's a weird limitation, though, since it's acceptable for `width`. I can't understand why it's acceptable for the CSS specification of ordinary webpages, but not Shiny applications.

**Comment by shrektan** [comment]
@DarioS I remember it's due to the fluid layout.

**Comment by wch** [comment]
The general problem is that CSS doesn't always make it possible to use 100% height. However, if the container's height is set to a particular value, you can use 100% height. For example:

```R
library(shiny)

ui <- div(style = "height: 300px;",
  plotOutput("plt", height = "100%")
)

server <- function(input, output, session) {
  output$plt <- renderPlot({
    plot(cars)
  })
}

shinyApp(ui = ui, server = server)
```
