### ISSUE TITLE
Add 'override' argument to addCustomMessageHandler to allow overriding existing handler

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1419]
Or perhaps name it `force` to be consistent with `shiny::registerInputHandler()`.

It's not a very important feature and likely won't be useful for too many people, but I've come across it on a few rare occasions. I can submit a PR if a shiny team member thinks this is acceptable.

Currently trying to redefine a JS message handler results in an error via https://github.com/rstudio/shiny/blob/9613c58bf8120bcfdab35801b17167418b5464ac/srcjs/shinyapp.js#L459-L461

**Comment by wch** [comment]
That makes sense to simply allow overriding. I don't think a `force` arg is necessary. I think I wrote that part and don't know why I had it throw an error in the first place. Can you submit a PR?

**Comment by daattali** [comment]
I made a PR #1445

**Comment by jcheng5** [comment]
Just curious--when are you overriding handlers?

**Comment by daattali** [comment]
All my cases are involving shinyjs, hence I said it might not be relevant to too many people...

Previously, I had someone ask me how they can intercept the shinyjs calls because they wanted to run a single line of javascript before the shinyjs::disable() call. So my initial idea was to overwrite the JS message handler, something like this:

```
library(shiny)
library(shinyjs)

jscode <- "
Shiny.addCustomMessageHandler('shinyjs-disable', function(params){
  // do whatever you want here
  alert('Hello');
  shinyjs.disable(params);
});
"

ui <- fluidPage(
  useShinyjs(),
  tags$head(tags$script(HTML(jscode))),
  textInput("text", NULL),
  actionButton("btn", "Disable")
)

server <- function(input, output, session) {
  observeEvent(input$btn, disable("text"))
}

shinyApp(ui = ui, server = server)
```

More recently I was trying to include a piece of code that uses shinyjs inside a larger app that also uses shinyjs, and if I wasn't careful then I'd end up with duplicate message handlers. It wasn't ideal code anyway so I didn't end up with that, but it just reminded me that it shouldn't throw errors if that happens
