### ISSUE TITLE
sliderInput and animation

### ISSUE THREAD

**Issue by leonawicz** [rstudio/shiny#142]
This is more a suggestion than an issue. I apologize if this is not where I should be posting it.

When starting from some selected range of values on the slider, there does not appear to be a possibility of anchoring the lower boundary (or upper) when using animate = T or animate = [insert list of animationOptions] so that the animation may proceed by increasing the selected range instead of just shifting it.

For instance, unveiling a time series plot (using a fixed maximum xlim and ylim of course) as opposed to only being able to view a moving window of the series. This would be a nice feature if possible.

**Comment by alandipert** [comment]
@wch implemented this in https://github.com/wch/shiny/commit/7a5e0e4 but it was not included with #852.

Presumably it would still be easy to add, if we decided to.

**Comment by leonawicz** [comment]
Just got the notification- wow I forgot I even requested this in 2013! 😄 Suffice it to say I must have never really needed the feature that badly because I forgot all about it. This could probably be closed unless it's important to others to keep open.

**Comment by alandipert** [comment]
@leonawicz 😄
