### ISSUE TITLE
shiny::brushedPoints fails to detect axis variables in dev version of ggplot2

### ISSUE THREAD

**Issue by petersmp** [rstudio/shiny#1420]
I am not sure whether this should be considered a bug in `ggplot2` or in `shiny`, so I am filing it in both places ([here is the issue at ggplot](https://github.com/hadley/ggplot2/issues/1850) )

When using the dev version of `ggplot2`, attempts to use `shiny::brushedPoints` leads to the error:

> Error in brushedPoints: brushedPoints: not able to automatically infer `xvar` from brush

I reverted to the stable version of `ggplot2`, and the same code works. I am not clear enough on the structure of the communication to track down what is going wrong. I will try to start digging tomorrow.

Here is minimal code to reproduce the error. Simply brushing on the plot causes the app to crash.

    library(shiny)
    library(tidyverse)
    
    server <- function(input, output, session) {
      
      output$distPlot <- renderPlot({
        iris %>%
          ggplot(aes(x = Sepal.Length
                     , y = Sepal.Width)) +
          geom_point()
      })
      
      observeEvent(input$point_Brush, {
        brushedPoints(iris, input$point_Brush)
      })
      
    }
    
    ui <- fluidPage(
      fluidRow(
        plotOutput("distPlot"
                   , brush = "point_Brush")
      )
      
    )
    
    shinyApp(ui = ui, server = server)

**Comment by wch** [comment]
Have you tried the development version of Shiny? See #1392.

**Comment by wch** [comment]
Oh actually, that fix already made it into the released version of Shiny, 0.14.1. What version are you using?

**Comment by petersmp** [comment]
Well, that is embarrassing -- thank you for such a quick reply. I was apparently still on version 0.14. That fixes it. I had search for `brushedPoints` and not found that one. Thanks again.
