### ISSUE TITLE
When using the `shiny.trace` option, allow specifying to only log SEND or RECV messages (or both)

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1422]
It's great to have the ability to debug apps using `options(shiny.trace=TRUE)`.  But often I find the information to be overwhelming and I'm often only interested in seeing either the RECV or the SEND messages, so it'd be nice if we had a way to specify that.

I  can submit a PR if a shiny team member thinks this is acceptable.

Relevant code: I believe the only changes would happen [here](https://github.com/rstudio/shiny/blob/9613c58bf8120bcfdab35801b17167418b5464ac/R/server.R#L221-L226) and [here](https://github.com/rstudio/shiny/blob/9613c58bf8120bcfdab35801b17167418b5464ac/R/shiny.R#L417)

**Comment by jcheng5** [comment]
I'd love to see a PR for this. Thanks!

**Comment by daattali** [comment]
@jcheng5 any preference for what the triplet of options should be? `shiny.trace=` [1,2,3] vs [TRUE, 'SEND', 'RECV'] vs ['all','SEND','RECV'] vs ?

**Comment by kevinushey** [comment]
What about just accepting a `list` as a potential value for `shiny.trace`, e.g.

```
options(shiny.trace = list(send = TRUE, recv = TRUE)
```

and `shiny.trace = TRUE` could act as a synonym for the above?

**Comment by jcheng5** [comment]
I don't have a strong opinion but prefer TRUE/"send"/"receive". Only reason it's capitalized in the trace output is to make it easy to distinguish from the output payload. And the only reason the trace output abbreviated receive is to make send and recv line up when the trace output is pasted into a text editor without word wrap (quite useful when you have a lot of messages to look at).

Kevin, I'd argue against that just because of the extra typing. This is something you're only really likely to do interactively so I think brevity counts for a lot.

**Comment by daattali** [comment]
@jcheng5 good call on making SEND+RECV all caps and equal length. I also found myself wanting the SEND/RECV text to be followed by a tab instead of just a single space, to give a bit of breathing room and make it more clear where a new message begins vs a very long message is wrapping.  

```
SEND {"config":{"workerId":"","sessionId":"69157bedc359093f3b22ad53b4251e45"}}
RECV {"method":"init","data":
{"runcode_run:shiny.action":0,"runcode_expr":"shinyjs::alert('Hello!')",".clientdata_pixelratio":1,".clientdat
a_url_protocol":"http:",".clientdata_url_hostname":"127.0.0.1",".clientdata_url_port":"4471",".clientdata_ur
l_pathname":"/",".clientdata_url_search":"",".clientdata_url_hash_initial":"",".clientdata_singletons":"12b28
2b6c4e1ec3cee386f4ca6165aafc4731a84,a82a5acc413912857c8eca64a6c1dd9da8f88ef6",".clientdata_al
lowDataUriScheme":true}}
SEND {"busy":"busy"}
```

vs

```
SEND    {"config":{"workerId":"","sessionId":"69157bedc359093f3b22ad53b4251e45"}}
RECV    {"method":"init","data":
{"runcode_run:shiny.action":0,"runcode_expr":"shinyjs::alert('Hello!')",".clientdata_pixelratio":1,".clientdat
a_url_protocol":"http:",".clientdata_url_hostname":"127.0.0.1",".clientdata_url_port":"4471",".clientdata_ur
l_pathname":"/",".clientdata_url_search":"",".clientdata_url_hash_initial":"",".clientdata_singletons":"12b28
2b6c4e1ec3cee386f4ca6165aafc4731a84,a82a5acc413912857c8eca64a6c1dd9da8f88ef6",".clientdata_al
lowDataUriScheme":true}}
SEND    {"busy":"busy"}
```


Can I sneak that into the PR as well or would you prefer to keep the minimal spacing?
