### ISSUE TITLE
Feature request: provide a way to include code in both the UI and the server with only one call

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1424]
Currently, if you write a function for a package that requires some UI code (such as adding javascript to the page or adding UI elements) as well as server logic, you have to expose two functions to the user: one to call in the UI, one to call in the server. It'd be great if there was a way for the user to call one function that would both add code to the UI and to the server portion of the app.

I can provide more details or clarification if needed

**Comment by wch** [comment]
Can you provide an example of what you mean?

**Comment by daattali** [comment]
Example 1: Call a UI function that can have different params, but this function also needs a bit of server code to exist (the server code is always identical)

```
library(shiny)

runcodeUI <- function(code = "showModal(modalDialog('hello'))") {
  tagList(
    textInput("expr", label = "Enter code", value = code),
    actionButton("run", "Run")
  )
}

runcodeServer <- function() {
  parentFrame <- parent.frame(1)
  
  # get the Shiny session
  session <- getDefaultReactiveDomain()
  
  observeEvent(session$input$run, {
    eval(parse(text = session$input$expr), envir = parentFrame)
  })
}

ui <- fluidPage(
  runcodeUI()
)

server <- function(input, output, session) {
  runcodeServer()
}

shinyApp(ui = ui, server = server)
```

Example 2: Call a server function that can have different params, but it requires some UI to exist (for example, because it needs specific javascript/css). I don't have code example, but suppose I wanted to have a function that could show a [sweetalert](https://github.com/t4t5/sweetalert) modal. This would be a server-side function. But in order to use it, I'd need to ensure the UI has the javascript file of sweetalert library. So I would have to make a call like "enablesweetalert" in the UI so that the proper library is loaded, and only then I can use it on the server.

Example 3: in shinyjs it would be awesome, because right now I require users to make a "useShinyjs()" call in the UI so that they'd be able to use all the functions on the server side (useShinyjs injects a lot of javascript code). I've always thought this would be impossible to achieve, but I think I spoke with somebody at RStudio (@jcheng5 maybe?) who told me this would be possible and I should open an issue

Hope that makes sense

**Comment by bborgesr** [comment]
Hmm, can you use `insertUI` for this? If it's not clear how to do so, let me know and I'll try to modify your Example 1 code to do this.

**Comment by daattali** [comment]
Would be nice to see how you would use insertUI to do this nicely

**Comment by bborgesr** [comment]
Example 1:

```r
library(shiny)

runcodeUI <- function(code = "showModal(modalDialog('hello'))") {
  tagList(
    textInput("expr", label = "Enter code", value = code),
    actionButton("run", "Run")
  )
}

runcodeServer <- function() {
  parentFrame <- parent.frame(1)
  
  # get the Shiny session
  session <- getDefaultReactiveDomain()
  
  observeEvent(session$input$run, {
    eval(parse(text = session$input$expr), envir = parentFrame)
  })
}

runCode <- function() {
  insertUI("body", "afterBegin", runcodeUI())
  runcodeServer()
}

ui <- fluidPage()

server <- function(input, output, session) {
  runCode()
}

shinyApp(ui = ui, server = server)
```

*******************

Example 3:

```r
library(shiny)
library(shinyjs)

runCode <- function() {
  insertUI("body", "afterBegin", {
    tags$div(
      useShinyjs(),  # Include shinyjs
      actionButton("button", "Click me"),
      textInput("text", "Text")
    )
  })
  
  observeEvent( getDefaultReactiveDomain()$input$button, {
    eval(parse(text = "toggle('text')"),
         envir = parent.frame(1))
  })
}

ui <- fluidPage()

server <- function(input, output, session) {
  runCode()
}

shinyApp(ui, server)
```

Is this what you wanted?

**Comment by daattali** [comment]
@bborgesr this does work for example 1, but I'm not sure it would make sense for example 2. Correct me if I'm wrong, but this approach would mean that if I call a function multiple times in the server code, it would result in the UI code being inserted multiple times. Here's a sample pseudocode for my example 2, assuming that swal.js and swal.css are 3rd party scripts that expose a function `swal()` that created modals:

```
includeSweetalert <- function() {
  tagList(
    script(src = 'swal.js'),
    style(href = 'swal.css'),
    script('Shiny.onCustomMessageHandler("showmodal", function(message){ swal(message); })')
  )
}
sweetalert <- function(message) {
  getDefaultReactiveDomain()$sendCustomMessage("showmodal", message)
}

ui <- fluidPage(
  includeSweetalert(),
  textInput("text", "text")
)
server <- function(input, output, session) {
  observe( sweetalert(input$text) )
}

shinyApp(ui, server)
```

Does this make sense?

**Comment by jcheng5** [comment]
Use insertUI with either htmltools::htmlDependency or singleton(). Either way it will only be inserted once. I can't give you an example right now as I'm on my phone but let me know if you are not able to figure it out.

**Comment by daattali** [comment]
So `insertUI` is the approach to use if you want to inject UI from the server; is there any way of doing it the other way around? Any way to call a UI function and have it automatically inject some server code into every session that connects?

For example, in @bborgesr 's example 1 code I'd like to make the call from the UI instead of from the server, because I want to place it in the layout where it physically makes sense. When inserting scripts and stylesheets it doesn't matter if you use insertUI from the server, but when inserting actual elements I'd prefer to place it somewhere directly rather than using insertUI's relative before/after/etc. This is now getting to be more about style than functionality

**Comment by jcheng5** [comment]
I don't think it's possible. The problem is not symmetrical because the client is under the (potentially malicious) user's control, so you can't have the client driving arbitrary behavior on the server. I could maybe imagine some ways around this but none of them feel intuitive.

**Comment by daattali** [comment]
Thanks, you guys can close this issue unless there's anything else someone wants to discuss

**Comment by daattali** [comment]
@alandipert FYI this is what I was talking about yesterday
