### ISSUE TITLE
Pressing the "Enter" key in an input inside a form should trigger the submit button

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1425]
It's my understanding that a submit button is supposed to be triggered automatically when "Enter" is pressed while an input in the same form is focused.

For some reason that's not happening in shiny apps - my only guess is that the behaviour is explicitly suppressed by shiny. I'm not sure if this is done purposely or not, but I wanted to mention it in case it's a mistake.

**Comment by daattali** [comment]
I do see now that this was done explicitly as part of https://github.com/rstudio/shiny/issues/64 way back in shiny's early days. My vote would be to reverse that since it goes against standard HTML practices, but it might annoy a lot of people who are used to the current behaviour, so I'll let the shiny team take it from here :)

**Comment by DavidSichau** [comment]
Maybe it would be cool to have an option on actionButtons that they should react on enter events or not. This would allow one to specify which actionButtons should be triggered by enter.

**Comment by daattali** [comment]
That's not really how html works and will be strange to implement. My
original request was just because submit buttons are meant to be triggered
by the Enter key when the focus is inside a form. But regular buttons
shouldn't behave that way

**Comment by jcheng5** [comment]
#64 was necessary because submitting the form actually navigated the whole page away from the Shiny app IIRC. The feature you want is for what we call "submitButton" to be invoked.

You could modify the code introduced in #64 to additionally do:

```javascript
if (inputs === inputsDefer) {
  inputsDefer.submit();
}
```

That does mean that any form on the page being (HTML-)submitted will cause the Shiny submit mechanism to trigger.
