### ISSUE TITLE
Request: Brushing with grid graphics

### ISSUE THREAD

**Issue by pfh** [rstudio/shiny#1431]
This is a feature request. My understanding is that Shiny plotOutput interaction currently supports base graphics and ggplot2. I would like to request support for grid graphics. grid graphics allows multiple named viewports to be created, and it would be useful to be able to map interaction into those named viewports.

Currently, I am using the hack below to set up base graphics to match a grid viewport.

```
output$plot <- renderPlot({

    # ... draw some grid graphics ...

    seekViewport("...someviewport...")
    par(new=T, plt=gridBase::gridPLT())
    plot(1, type="n", axes=F, 
         xlab="", ylab="", 
         xlim=c(0,1), ylim=c(0,1),
         xaxs="i", yaxs="i")
})
```

Thank you for providing this very useful library to the R community.

**Comment by wch** [comment]
@pfh, we're not likely to implement this, since it would be a fairly large project and not a lot of people would use it. But we'll consider pull requests. :)
