### ISSUE TITLE
Interactivity when ggplot output from custom function

### ISSUE THREAD

**Issue by hherrada** [rstudio/shiny#1434]
Hello, I understand that when we use `print` this messes up the coordinates of the chart. In this case it's pretty much impossible to use interactivity at all, which is unfortunate. On the other hand, if you have several parts of a shiny app using the same chart it gets pretty messy to have all the ggplot lines of code in each of those sections.

Is there a way we can have a ggplot output from a function and be able to render it without `print` so that we can use the interactivity features?

Thank you!

**Comment by hherrada** [comment]
My problem was actually because the ggplot generating function was within a `withProgress` function. Once I got rid of it everything started rendering again! As a toy example, this was not working:

`output$GGPLOT <- renderPlot({`

`withProgress(message = 'Loading ...', style = "notification", value = 0.1, {`
      
      `pp <- CustomGGPLOT()`
`pp})`
`})` 

Any work around for this?

**Comment by wch** [comment]
Can you provide a reproducible example?

**Comment by wch** [comment]
`withProgress` doesn't seem to cause any problems in this example:

```R
library(shiny)
library(ggplot2)

ui <- fluidPage(
  actionButton("go", "Go"),
  plotOutput("plot")
)

server <- function(input, output) {
  output$plot <- renderPlot({
    req(input$go)
    withProgress(message = 'Calculating...', value = 0, {
      for (i in 1:10) {
        incProgress(1/10)
        Sys.sleep(0.1)
      }
      ggplot(mtcars, aes(wt, mpg)) + geom_point()
    })
  })
}

shinyApp(ui, server)
```

**Comment by hherrada** [comment]
Ok, I found the issue. I slightly changed your example. The chart does not print in this case:

```
library(shiny)
library(ggplot2)

ui <- fluidPage(
  actionButton("go", "Go"),
  plotOutput("plot")
)

server <- function(input, output) {
  output$plot <- renderPlot({
    req(input$go)
    withProgress(message = 'Calculating...', value = 0.1, {

      ggplot(mtcars, aes(wt, mpg)) + geom_point()
      
      setProgress(1)
      
    })
  })
}

shinyApp(ui, server)
```
