### ISSUE TITLE
Referencing htmlwidgets dependency libraries in onRender

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shiny#1459]
I discovered this in https://github.com/ropensci/plotly/pull/554/commits/2036ace9fb1aad7f06e1a24f42f25b300b2e950c. It seems as though, if you reference an htmlwidget dependency library in `htmlwidgets::onRender()`, it works fine without shiny, but not with shiny (in this case, I'm using the JS library bundled with https://github.com/rstudio/crosstalk).

```r
# devtools::install_github("ropensci/plotly#554")
library(plotly)
# works fine
p <- htmlwidgets::onRender(
  plot_ly(), "function(el, x) { console.log(crosstalk); }"
)
```

However,

```r
library(shiny)

ui <- fluidPage(
  plotlyOutput("plot")
)

server <- function(input, output) {
  output$plot <- renderPlotly({ p })
}

# The plot doesn't appear and the console log says `ReferenceError: Can't find variable: crosstalk`
shinyApp(ui, server)
```

I did a bit of looking around and it seems as though dependencies are resolved correctly [here](https://github.com/ramnathv/htmlwidgets/blob/ec4c137ad35881b56b15edd91a68b8bd63845749/R/htmlwidgets.R#L428-L431), so perhaps shiny is calling the onRender JS function before all the dependencies are loaded?

**Comment by timelyportfolio** [comment]
This might be related to https://github.com/ramnathv/htmlwidgets/issues/179.

**Comment by timelyportfolio** [comment]
I can confirm https://github.com/ramnathv/htmlwidgets/pull/237 fixes the problem.

**Comment by jcheng5** [comment]
I forgot that PR still wasn't merged, I've just posted a reminder.
