### ISSUE TITLE
FR: add class argument to modalButton

### ISSUE THREAD

**Issue by johnpauls** [rstudio/shiny#1462]
It would be nice to have a `class=` argument to `modalButton()`. As it is you can use `tags$div` to do this

`modalButton( label= tags$div("Exit", class="btn btn-primay"))`

but then the "primary" button in wrapped inside of `"btn btn-default"` which in my case puts a white box / border around the button.  Direct access to the class of this button would eliminate this problem.

Thanks.

**Comment by jcheng5** [comment]
You could call `tagAppendAttributes(modalButton(...), class = "btn-primary")`, but that would end up with a button with both `btn-default` and `btn-primary`. That might work, but if it doesn't, then you could also override the class attribute directly.

```r
mymodal <- modalButton(...)
mymodal$attribs$class <- "btn btn-primary"
```

**Comment by johnpauls** [comment]
`tagAppendAttributes` did the trick - thanks!
