### ISSUE TITLE
Progress$set() with no value specified increases progress to 1

### ISSUE THREAD

**Issue by paraviz02** [rstudio/shiny#1472]
When using a progress object, the Progress$set() function will increase the progress value to 1 when there is no value explicitly defined.

This behavior is unlike withProgress(), when using setProgress() without a value (specifically to change the detail or message), the progress value remains the same.

`
ui<-fluidPage(
	tags$div(style="text-align:center;",
		fluidRow(
			column(12,
				uiOutput("demo")
			)
		)
	)
)
server<-function(input,output,session){

	progressMsg<-Progress$new(session)
	progressMsg$set(message="Loading:",detail="Initializing ...",value=.01)

	output$demo<-renderUI({
		thisOut<-tags$div(id="tiles",tags$div(id="one",reactiveOne()),tags$div(id="two",style="display:none;",reactiveTwo()))
		if(!is.null(progressMsg)){
			progressMsg$close()
			progressMsg<<-NULL
		}
	})

	reactiveOne<-reactive({
		totalProgress<-.25
		incAmount<-totalProgress/10
		if(!is.null(progressMsg)){
			progressMsg$inc(detail="Reactive 1, Part 1",amount=incAmount)
		}
		Sys.sleep(1)
		if(!is.null(progressMsg)){
			progressMsg$inc(detail="Reactive 1, Part 2",amount=incAmount)
		}
		Sys.sleep(1)
		if(!is.null(progressMsg)){
			progressMsg$inc(detail="Reactive 1, Part 3",amount=incAmount)
		}
		Sys.sleep(1)
		if(!is.null(progressMsg)){
			progressMsg$inc(detail="Reactive 1, Part 4",amount=incAmount)
		}
		progressInc<-(totalProgress-(incAmount*4))/100
		for(i in 1:100){
			if(!is.null(progressMsg)){
				progressMsg$inc(detail="Reactive 1, Part 5",amount=progressInc)
			}
			pretendFunction(i)
		}
		progressMsg$set(detail="Reactive 1, Finished")
		Sys.sleep(3)
		"Reactive One!"
	})

	reactiveTwo<-reactive({
		totalProgress<-.5
		incAmount<-totalProgress/10
		if(!is.null(progressMsg)){
			progressMsg$inc(detail="Reactive 2, Part 1",amount=incAmount)
		}
		Sys.sleep(1)
		if(!is.null(progressMsg)){
			progressMsg$inc(detail="Reactive 2, Part 2",amount=incAmount)
		}
		Sys.sleep(1)
		if(!is.null(progressMsg)){
			progressMsg$inc(detail="Reactive 2, Part 3",amount=incAmount)
		}
		Sys.sleep(1)
		progressInc<-(totalProgress-(incAmount*3))/750
		for(i in 1:750){
			if(!is.null(progressMsg)){
				progressMsg$inc(detail="Reactive 2, Part 4",amount=progressInc)
			}
			pretendFunction(i)
		}
		progressMsg$inc(detail="Reactive 2, Finished",amount=progressInc)
		Sys.sleep(1)
		"Reactive Two!"
	})

	reactiveThree<-reactive({
		totalProgress<-.15
		incAmount<-totalProgress/8
		progressMsg$inc(detail="Reactive 3, Part 1",amount=incAmount)
		Sys.sleep(1)
		progressMsg$inc(detail="Reactive 3, Part 2",amount=incAmount)
		Sys.sleep(1)
		progressMsg$inc(detail="Reactive 3, Part 3",amount=incAmount)
		Sys.sleep(1)
		progressMsg$inc(detail="Reactive 3, Part 4",amount=incAmount)
		Sys.sleep(1)
		progressInc<-totalProgress-(incAmount*4)
		Sys.sleep(1)
		progressMsg$set(detail="Reactive 3, Finished")
		"Three done!"
	})

	pretendFunction<-function(thisIndex){
		stuff<-reactiveThree()
		"Thing Four"
	}
}
shinyApp(ui,server)
`

**Comment by paraviz02** [comment]
Sorry for the awkward formatting - there seems to be an issue with the way GitHub parses the code.

**Comment by wch** [comment]
Can you provide a *minimal* example?

**Comment by paraviz02** [comment]
Yes, my apologies Winston. Give me a sec.

**Comment by paraviz02** [comment]
Here you go.

`ui<-fluidPage(
	tags$div(style="text-align:center;",
		fluidRow(
			column(12,
				uiOutput("demo")
			)
		)
	)
)`

server<-function(input,output,session) {

	progressMsg<-Progress$new(session)
	progressMsg$set(message="Loading:",detail="Demo ...",value=0)

	output$demo<-renderUI({
		totalProgress<-1
		incAmount<-totalProgress/10
		for(i in 1:4){
			if(!is.null(progressMsg)){
				progressMsg$inc(amount=incAmount)
				Sys.sleep(1)
			}
		}
		progressMsg$set(detail="Updating Detail ...")
		for(i in 1:6){
			if(!is.null(progressMsg)){
				progressMsg$inc(amount=incAmount)
				Sys.sleep(1)
			}
		}
		if(!is.null(progressMsg)){
			progressMsg$close()
			progressMsg<<-NULL
		}
		'Test'
	})

}
shinyApp(ui,server)
`

Not sure what I'm doing wrong, but I can't seem to get the formatting to work properly.

**Comment by wch** [comment]
It looks like the problem happens when `$inc()` is called after `$set(value = NULL)` - it causes the bar to go to 100%. Simplified example:

```R
shinyApp(
  ui = fluidPage(
    plotOutput("plot")
  ),
  server = function(input, output, session) {
    output$plot <- renderPlot({
      progress <- Progress$new(session, min=1, max=10)
      on.exit(progress$close())

      progress$set(message = 'Calculation in progress')
      # Commenting the above line and uncommenting this makes it work properly
      # progress$set(value = 0, message = 'Calculation in progress')

      for (i in 1:10) {
        progress$inc(amount = 1)
        Sys.sleep(0.5)
      }
      plot(cars)
    })
  }
)
```

@paraviz02 You need to surround code blocks with  ```` ``` ````. See https://guides.github.com/features/mastering-markdown/.

**Comment by paraviz02** [comment]
Ah, gotcha. Sorry about that, Winston. (Relative newbie here ... Eek.)
