### ISSUE TITLE
Feature request: allow Shiny.onInputChange() to send a message to R immediately

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1476]
Loosely related to #928 

If I update the same input multiple times within the same function call in JavaScript, then Shiny (on the R side) is only aware of the last value.

I saw there was an `immediate` param in some of the JS code that deals with setting inputs, but I couldn't figure out how to make it work, or if it's even relevant.

Example: whenever you click on the button, an input called "testr" should be updated thrice in succession. But only the last value gets printed in Shiny using the `input$testr` variable  

```
library(shiny)

ui <- fluidPage(
  tags$script("
    Shiny.addCustomMessageHandler('testjs', function(num) {
      Shiny.onInputChange('testr', num);
      Shiny.onInputChange('testr', num+1);
      Shiny.onInputChange('testr', num+10);
    });"
  ),
  actionButton("btn", "Click me")
)

server <- function(input, output, session) {
  observeEvent(input$btn, {
    session$sendCustomMessage('testjs', input$btn)
  })
  
  observe({
    cat(input$testr, "\n")
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by jcheng5** [comment]
Yeah, there's no workaround today that I'm aware of. This is one reason why the method name is `onInputChange` instead of `setValue` or `sendValue`, because there's all this "smart" deduping and batching and other stuff going on, that only really makes perfect sense for traditional inputs.

Well, if you really have to work around this today, you could keep a queue of name/value pairs, and pop them one by one on each tick. That would delay the sending by a few milliseconds but at least they would not be coalesced.

```javascript
function SenderQueue() {
  this.readyToSend = true;
  this.queue = [];
  this.timer = null;
}
SenderQueue.prototype.send = function(name, value) {
  var self = this;
  function go() {
    self.timer = null;
    if (self.queue.length) {
      var msg = self.queue.shift();
      Shiny.onInputChange(msg.name, msg.value);
      self.timer = setTimeout(go, 0);
    } else {
      self.readyToSend = true;
    }
  }
  if (this.readyToSend) {
    this.readyToSend = false;
    Shiny.onInputChange(name, value);
    this.timer = setTimeout(go, 0);
  } else {
    this.queue.push({name: name, value: value});
    if (!this.timer) {
      this.timer = setTimeout(go, 0);
    }
  }
};
```

Example:

```javascript
// Somewhere global-ish
var queue = new SenderQueue();

// Later...
queue.send("testr", 0);
queue.send("testr", 1);
queue.send("testr", 2);
queue.send("testr", 3);
```

**Comment by daattali** [comment]
Thanks Joe, I thought about doing all this setTimeout(0) business but was
hoping to instead fiddle with shiny to figure out a proper solution. Thanks
for taking the time to provide the perfectly functional implementation

---
R-Shiny Consultant
http://deanattali.com/shiny

**Comment by alandipert** [comment]
AFAIK we don't have plans to add this, but Joe provided an acceptable workaround.
