### ISSUE TITLE
Feature request: add `ignoreIdentical` param to `observeEvent()`

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1484]
I often use `observeEvent(x, ...)` when I want to tell shiny that a reactive code block should be executed whenever a specific value `x` changes. Usually `observeEvent()` does exactly what I want it to do, but because it gets fired when `x` gets invalidated, then it can also fire when `x` hasn't changed at all. I realize this is the correct behaviour based on how reactivity works, but in my opinion it's easier for people to think of it as only firing whenever the value changes rather than gets invalidated. So I was wondering if it'd be possible to add a parameter to `observeEvent()` that will do that?

Example:

```
library(shiny)

ui <- fluidPage(
  actionButton("btn", "Button")
)

server <- function(input, output, session) {
  num5 <- reactive({
    input$btn
    5
  })
  observeEvent(num5(), {
    cat("click\n")
  })
}

shinyApp(ui = ui, server = server)
```

It wouldn't be too far-fetched to think that the observer would only get run when `num5()` changes. It's wrong, but it can be useful to want to do that.

I realize this may be a strange request that doesn't really fit the reactivity model, and fully accept any incoming judgment if this is a dumb idea

**Comment by bborgesr** [comment]
Hmm, this seems like a reasonable request IMO. Thoughts, @wch, @jcheng5?

**Comment by jcheng5** [comment]
In the past, I've thought of this as a property of the reactive expression (does it invalidate its dependents if its new value is the same as the old?), not the observer. (This is actually how reactive expressions originally worked in Shiny, but I soon concluded that laziness was more frequently beneficial than this "de-dupe" behavior.)

You can achieve this yourself with a higher order reactive.

```
dedupe <- function(r) {
  makeReactiveBinding("val")
  observe(val <<- r(), priority = 10)
  reactive(val)
}

num5 <- dedupe(reactive({
  input$btn
  5
}))
```

Seems like we might want to start corralling some of these types of things into a shiny reactive extras package (or contribute to Hadley's shinySignals package)...

**Comment by daattali** [comment]
Your beautifully elegant solutions for these things always amaze me.  I agree it'd be nice to have a place that aggregates a lot of these more complex constructs that achieve commonly needed results in shiny. I remember the [`reactiveTrigger` you created](https://github.com/MangoTheCat/dynshiny/compare/master...jcheng5:master#diff-1e678274602e250345bb25d52e7c2d76R4) for @gaborcsardi was also something I'd love to bookmark.  This was sort of the idea behind my repo [advanced-shiny](https://github.com/daattali/advanced-shiny/)...

**Comment by alandipert** [comment]
Closing because a suitable workaround was provided.

**Comment by sanjmeh** [comment]
I thought I understood shiny reactive exressions quite well till I saw this Joe Cheng's master piece snippet in response to @daattali 's equally valuable question.

```
dedupe <- function(r) {
  makeReactiveBinding("val")
  observe(val <<- r(), priority = 10)
  reactive(val)
}

num5 <- dedupe(reactive({
  input$btn
  5
}))
```

I am not sure how this works. How is the invalidation happening here? How does the assignment operator help?
@daattali : could you please please document this on your excellent advanced shiny website?

**Comment by daattali** [comment]
@sanjmeh it's documented https://deanattali.com/blog/advanced-shiny-tips/#reactive-dedupe
