### ISSUE TITLE
downloadHandler Fails if downloadButton Previously Hidden

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1489]
A new tab opens with another instance of the application, but the application never returns to the original tab to display the file saving dialog. This problem doesn't happen if the `downloadButton` was not hidden to begin with.

      library(shiny)
      ui = fluidPage(
      tags$head(tags$script("Shiny.addCustomMessageHandler('showHideContainer', function(action)
                 {
                     document.getElementById('downloadContainer').style.display = 'inline-block';
                 });")),
      div(id = "downloadContainer", downloadButton("aButton", "Download"), style = "display:none"),
      actionButton("revealButton", "Reveal Download")
    )
    
    server = shinyServer(function(input, output, session) {
      output[["aButton"]] <- downloadHandler("test.txt", function(file) write.table(cars, file))
      observeEvent(input[["revealButton"]], session[["sendCustomMessage"]]("showHideContainer", "show"))
    })
    
    shinyApp(ui, server)

**Comment by wch** [comment]
The output `"abutton"` starts hidden and because it's not revealed using a `shown` event, Shiny doesn't know that it is visible, so it continues to treat it as a hidden output, which by default is suspended.

To make it work, you need to add something like this to your server function:

```R
outputOptions(output, "aButton", suspendWhenHidden = FALSE)
```
