### ISSUE TITLE
unable to install a package

### ISSUE THREAD

**Issue by ithenelin** [rstudio/shiny#1493]
When i use install.packages("shiny") to install or use .zip file to install the package, it still said cannot open URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.3/PACKAGES'
even when i use administrator, it's still not work

use Rstudio:
> install.packages("shiny")
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'
Installing package into 慍:/Users/Ithene Lin/Documents/R/win-library/3.3?(as 憀ib?is unspecified)
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'
Warning in install.packages :
  package 憇hiny?is not available (for R version 3.3.2)
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/bin/windows/contrib/3.3:
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/PACKAGES'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.3:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.3/PACKAGES'

**Comment by ithenelin** [comment]
Even when i used administrator, it's still not work

**Comment by shrektan** [comment]
try `install.packages("shiny", repos = "https://cran.rstudio.com")`

**Comment by ithenelin** [comment]
@shrektan still not work

**Comment by ithenelin** [comment]
@shrektan 
the problem is the same:
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'
Installing package into 慍:/Users/Ithene Lin/Documents/R/win-library/3.3?(as 憀ib?is unspecified)
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  package 憇hiny?is not available (for R version 3.3.2)
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  InternetOpenUrl failed: '愷彴'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/bin/windows/contrib/3.3:
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/PACKAGES'

**Comment by wch** [comment]
This is a problem with your computer or R installation, not a problem with Shiny itself. It looks like your computer is having trouble connecting to the CRAN repositories.

**Comment by alirezaa2s** [comment]
Hi there,
I had the same problem. In the first place I thought that drive C is on "read only" or its security is restricted. For which I changed the place of R. However that was not the problem. The problem was beneath of Global option. Here is the rout in RStudio: Tool...Global option...in the left column select Packages...and change the CRAN miror to, for example Sweden or someplace except Global.
I hope it works for you too
