### ISSUE TITLE
purrr::map doesn't work with observeEvents()

### ISSUE THREAD

**Issue by gergness** [rstudio/shiny#1498]
I'm trying to programatically create `observeEvents()` in a shiny app. I originally intended to use purrr, but when I did, only the last value of the list seemed to be created. 

Here is code based on the [Pattern 3 - Dueling buttons](https://shiny.rstudio.com/articles/action-buttons.html) example. 

When using purrr to create the observeEvents, I can only get normal distributions (the runif button doesn't work).

```r
library(shiny)
library(purrr)

dists <- c("runif", "rnorm")
ui <- fluidPage(
  ## Here both purrr::map and lapply work...
  # lapply(dists, function(x) actionButton(x, x)),
  purrr::map(dists, ~actionButton(., .))
  hr(),
  plotOutput("plot")
)

server <- function(input, output){
  v <- reactiveValues(data = NULL)
  
  ## But here, only lapply works. With purrr, only the last button 
  ## makes the plot.
  # lapply(dists, function(x) {
  #   observeEvent(input[[x]], {
  #     v$data <- do.call(x, list(100))
  #   })
  # })
  
  purrr::map(dists, function(x) {
    observeEvent(input[[x]], {
      v$data <- do.call(x, list(100))
    })
  })
  
  output$plot <- renderPlot({
    if (is.null(v$data)) return()
    hist(v$data)
  })
}
    
    shinyApp(ui, server)
```

Any ideas? I assume it is an issue with shiny because the following are identical. Let me know if I should move to the purrr repo.

```r
det_funcs <- c("sqrt", "identity") 
base_way <- lapply(det_funcs, function(x) {
  do.call(x, list(100))
  })
purrr_way <- map(det_funcs, ~do.call(., list(100)))

identical(base_way, purrr_way)
```

**Comment by jcheng5** [comment]
Right inside the map callback function, can you add `force(x)`? I suspect you're getting bitten by delayed evaluation.

**Comment by jcheng5** [comment]
And if that fixes it then it wouldn't be a bad idea to file this as a bug on purrr. The lapply behavior is desired here.

**Comment by gergness** [comment]
Yep, that fixed it. Thanks!
