### ISSUE TITLE
Should update to ionRangeSlider 2.1.5

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#1500]
This version of ionRangeSlider removes the need for the workaround mentioned in #1369. See IonDen/ion.rangeSlider#413.

**Comment by wch** [comment]
Test app:

```R
ui <- fluidPage(
  sliderInput("obs", "Number of observations:",
    min = 0, max = 5000000, value = 1000000, sep = ""
  ),
  plotOutput("distPlot")
)
server <- function(input, output) {
  output$distPlot <- renderPlot({
    hist(rnorm(input$obs))
  })
}
shinyApp(ui, server)
```

**Comment by DarioS** [comment]
Version 2.1.6 was released a fortnight ago. It seems like the last version to be made before the major 3.0 release. Perhaps including version 2.1.6 in Shiny 1.0 before it's released would be better.
