### ISSUE TITLE
File extension and fileInput

### ISSUE THREAD

**Issue by carlganz** [rstudio/shiny#1501]
Related to the issue here: https://github.com/hadley/readxl/issues/85

The temporary files uploaded by `fileInput` have no file extension so some R functions (in particular `readxl::read_excel`) for reading in the file won't work. Currently people can work around this by changing the name of the file in the temp directory, but that seems inelegant. 

Is there a good reason for not including the file extension of the original file?

**Comment by jcheng5** [comment]
Let's also consider preserving the entire filename--there are cases like with [shapefiles](https://en.wikipedia.org/wiki/Shapefile) where the filenames matter.

**Comment by geolauf** [comment]
Hello everybody, 
I am working with GIS ESRI Shapefiles, the files work as a group of .shp, .dbf, .shx and .prj files (minimum) that have the same name (eg. f1.shp, f1.dbf, f1.shx and f1.prj). 
Is there a way to select (and view in the browser) only the file with the .shp extension as inputFile and automatically upload all the other files? 
Thanks in advance
