### ISSUE TITLE
overwrite file in fileInput

### ISSUE THREAD

**Issue by hherrada** [rstudio/shiny#1508]
Today I started using fileInput. I noticed that I am only able to upload a file once. In other words, I am not able to overwrite the resulting data.frame by uploading a second file. I was wondering if the widget can be modified to allow for this situation.

Thank you

**Comment by shrektan** [comment]
Actually, I think you can update it by uploading another file with different name. However, I do expect it could update when uploading the same name file.

**Comment by nzwormgirl** [comment]
I was wondering the same thing - seems to upload a second file (with a different name) okay but doesn't work if you try to upload a file with the same name again.  I'm building 2 apps where clients need to upload data and it would be handy if they didn't need to change the filename.
