### ISSUE TITLE
Any simple clean way to attach info to a session?

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1512]
[x-post from shiny-discuss](https://groups.google.com/forum/#!topic/shiny-discuss/RlFGtOJMKm0)

Suppose I have a package with an exported function that can be called from other people's shiny apps' server code.  I want to know whether it's the first time they call this function or not. What's the best way to do this?

I can add an attribute to the `session` object but that sounds like a bad idea. I feel like there should be a simple solution I'm not seeing

Example pseudocode:

```
# This function would be in a package
myfunc <- function() {
  if (firsttime) {
    ...
  } else {
    ..
  }
}
```

And any shiny app can call it in server code, potentially multiple times

```
ui <- fluidPage()
server <- function(input, output, session) {
  mypkg::myfunc()
}
```

If I was working on a regular R package without a shiny app, I would use a global environment to store this global value. But in this case I want this to be per-session.

This isn't an issue, it's a question that's gotten no response on shiny-discuss. I might be abusing the Issues system, but I thought this would be a bit more considerate than my usual method of personally emailing @jcheng5

**Comment by jcheng5** [comment]
Sorry, I've been busier than usual the last few weeks. This is an important capability (we've needed it ourselves a couple of times recently) and so easy to add.

I'm envisioning `session$userData$foo <- 10`. Only question I have is whether `session$userData` should be a regular environment, or a `reactiveValues`?

**Comment by daattali** [comment]
For my specific case a regular environment is good enough, but I would think making it reactiveValues would be useful. I'd vote for the latter.

This wouldn't be backwards compatible though - for older shiny versions, would attaching an attribute to `session` be the least terrible way of achieving this?

**Comment by jcheng5** [comment]
@daattali Huh, does attaching an attribute work? If so, that's a fine hack. 👍

**Comment by daattali** [comment]
Yup, you can't `session$foo <- "bar"` because of locked environments, but R is perfectly happy with `attr(session, "foo") <- "bar"`.

Wanted to see if you had any reason to discourage me from doing that. I got your thumbs up though so I'm happy

**Comment by bborgesr** [comment]
I like the idea of having this explicitly as a session element. It seems handy. However, I think I'm missing why exactly this isn't possible as of now without tacking an attribute onto the session object.

The scoping rules for shiny:

```r
# shared across all sessions
a <- "all"

ui <- fluidPage()

server <- function(input, output, session) {
  # defined in each session
  s <- "session"

  output$text <- renderText({
    # defined each time this function is called
    f <- "function"
  })
}
```

Why isn't `s` what you need?

In your case:

```r
ui <- fluidPage()
server <- function(input, output, session) {
  wasCalled <- 0
  
 observe({  # or a render func or a reactive
    # the logic / conditionals you need...
    mypkg::myfunc()
    wasCalled <<- wasCalled + 1
  })
}
```

**Comment by daattali** [comment]
That works fine when you're developing the entire shiny app yourself. But
what if I want to do this from a separate package that is called from the
end user's shiny app? I won't have access to the server function.

**Comment by jcheng5** [comment]
Yep, this is for advanced usage by module and package authors.

**Comment by bborgesr** [comment]
Got it, thanks!

**Comment by davidlub** [comment]
Hi,

The shinyStore package for storing local data using the HTML 5 storage is easy to use and works well. You could use it to store info per browser (not per session). 

David
