### ISSUE TITLE
Bookmarking Dynamically Added Input Form Fields

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1524]
`enableBookmarking` saves the *values* of input fields. If a Shiny application contains data filters (i.e. `textInput`s and `selectInput`s) that can be added and removed with `insertUI` and `removeUI` in response to plus and minus labelled `actionButton`s being clicked by the user, could the bookmarking functionality be enhanced to enable not only the values, but the boxes themselves to be restored? Are there plans to support dynamic input forms in Shiny in a more structured way to make it easier for developers?

**Comment by jcheng5** [comment]
That's a great idea, I haven't thought much about that personally but it seems like fertile ground.

**Comment by jfredtx** [comment]
Yes, I would like the functionality also - it seems that it shouldn't be that difficult to bookmark the dynamic ones - just render the page normally, and then set all inputs - dynamic too.   Btw, I really enjoyed your Shiny training at Rstudio::conf this year - still absorbing all the good information. Thanks again Joe.

Regards, Jason

**Comment by alandipert** [comment]
@DarioS it seems like @jfredtx's excellent suggestion might be the answer to your question, in that `onBookmark()` and `onRestored()` together constitute a structured way to save and restore arbitrary values. If you agree, please don't hesitate to close this issue.
