### ISSUE TITLE
Download is weird in IE9

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1527]
Opens a new page with a copy of the same app and only then does it ask you if you want to save/download the file:

https://gallery.shinyapps.io/010-download/
Version: IE9.0.8112.16421

**Comment by wch** [comment]
Any chance this is this related to #1473?

**Comment by wch** [comment]
I just ran it in a VM, with Win 7 and IE 9.0.8112.16421. The behavior doesn't look unusual to me - it does open a new tab briefly, but I think it has always done that. I've attached a screen recording. 

@bborgesr Does it look different on your machine?


![ffmpeg-ogv](https://cloud.githubusercontent.com/assets/86978/21773132/811b0dee-d653-11e6-9b7a-459fd8e0d660.gif)

**Comment by bborgesr** [comment]
Wow, now that I am doing this with the hotel internet, it works like yours. So it must have been an crappy in-flight internet problem, instead of a Shiny problem. I am sorry I wasted your guys' time... I'm never doing testing during a flight again!
