### ISSUE TITLE
Focusing on a single object in the react log

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1532]
(This has been sent to @jcheng5 and @bborgesr as private emails but I wanted to make an official request)

Using `options(shiny.reactlog=TRUE)` is awesome and makes a beautiful and useful graph that helps tracing the reactive values to see all the moving parts. It's great for debugging simple apps.

But in large apps with a lot of reactives, the graph gets overwhelming and very difficult to comprehend. It's especially an issue if there's one particular reactive value or a specific observer that I want to follow.

For example, I could be wondering why my code is entering a reactive context block, so I want to try to trace it to see exactly what value triggers it. It'd be great to be able to tell exactly what value was invalidated, or to be able to filter objects out of the react log.

**Comment by happyshows** [comment]
I'm also a bit confused by this debugging tool. Does it support nested module? The log seems to stop at root level.

**Comment by daattali** [comment]
Just throwing another idea out there: have a dropdown or checkboxes or some sort of UI that lets you enable/disable certain reactives from the graph

**Comment by jcheng5** [comment]
More ideas:

- Jump to next "end of reactive loop" state (i.e. everything is white)
- Zoom/focus on reactive object (eliminate everything that isn't reachable from that object)

**Comment by jcheng5** [comment]
@happyshows, is it different if you run `showReactLog()` from the console instead of Ctrl+F3?

**Comment by happyshows** [comment]
@jcheng5  I tried to launch showReactLog() and runApp, no reactivity was captured. Not sure the correct usage of this approach.

I was trying to debug [this](https://gist.github.com/happyshows/256e226f9479f443f9fde69d55cd07ea) where I saw react log stopped after the level 2 modules. This gist was to illustrate this [issue](https://github.com/rstudio/shiny/issues/1528).

**Comment by jcheng5** [comment]
Ok. I'm not near a computer today but I'll look later.

**Comment by bborgesr** [comment]
internal note: d3 chord example -- http://bl.ocks.org/AndrewRP/7468330

**Comment by yonicd** [comment]
here is a rough attempt at what dean was going for -- (https://github.com/yonicd/shinyProf/tree/master/shiny)

**Comment by aaron-horowitz** [comment]
Something sort of visual code inspection tool like [React-Sight](https://github.com/React-Sight/React-Sight) or [React-Monocle](https://github.com/team-gryff/react-monocle) would be really powerful, especially for large applications where reactLog becomes a nightmare. It appears a similar / same structure to what @yonicd created could be a good solution. A cleaner exposure of `shiny:::.graphStack$as_list()` could even be enough to let the community interrogate the reactlog however they please

**Comment by daattali** [comment]
I believe this is solved with the new reactlog2.0

**Comment by alandipert** [comment]
reactlog has been completely rewritten 🎊  and supports filtering, so closing this. reactlog is also now a separate package, so please file issues and feature requests over here moving forward: https://github.com/rstudio/reactlog
