### ISSUE TITLE
reactlog sometimes shows "time elapsed: NaN ms"

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1536]
Very low pri

I was just playing with a very simple reactlog and noticed that sometimes when I go backwards (left) on the react log I get the time to say "NaN"

Can't figure out exactly what conditions trigger it.

This app:

```
library(shiny)

ui <- fluidPage(
  textInput("text", "Text"),
  numericInput("num", "Number", 5),
  textOutput("out")
)

server <- function(input, output, session) {
  output$out <- renderText({
    paste0(input$text, input$num)
  })
}

shinyApp(ui = ui, server = server)
```

I changed the text to "aaa" and the number to 7, launched reactlog, went all the way to the right, then went back and forth a few times and got some NaNs. 

shiny v 1.0.0

**Comment by alandipert** [comment]
I'm *pretty* sure a bug like this doesn't exist in the new [reactlog](https://github.com/rstudio/reactlog), but if I'm wrong please don't hesitate to comment further or create a new issue.
