### ISSUE TITLE
Do shiny/RStudio support the Selection and execCommand API's?

### ISSUE THREAD

**Issue by sbihorel** [rstudio/shiny#1537]
Hi,

I am working on a small package, called rclipboard (https://github.com/sbihorel/rclipboard), which intends to provide a shiny UI button with copy-to-clipboard functionality. This is achieved by "wrapping" the button code around the HTML5-based clipboard.js (https://www.clipboardjs.com) javascript framework. Essentially, this packages will do with clipboard.js what the zeroclipr R package (https://github.com/smbache/zeroclipr/) does with the Flash-based zeroclipboard.js framework.

clipboard.js relies upon the Selection and execCommand API's, which are supported by most modern web browsers.

Interestingly, my copy-to-clipboard button works just fine when it is included in an app deployed on a Shiny server, but it does not when the same app is run locally from RStudio. While there could be many reasons why this is the case, I wanted to start by asking whether shiny/RStudio support the Selection and execCommand API's.

Thanks for you help.

PS: the same question was posted on Shiny Discuss a while ago but received no reply yet.

**Comment by kevinushey** [comment]
On the RStudio side, unfortunately, the desktop clients for Windows and Linux do not support the `execCommand()` API -- the underlying web engine is quite old and doesn't have these APIs.

Hopefully this will change in a future release of RStudio when the underlying web engines are updated.

**Comment by sbihorel** [comment]
Thank you for your super quick reply and explanations.

**Comment by alandipert** [comment]
Good news, this works for me in RStudio 1.2.1335 on macOS.

I think it probably started working because the RStudio viewer is now based on recent Chromium.

If it still doesn't work for you after upgrading RStudio, don't hesitate to comment further or open a new issue.
