### ISSUE TITLE
When inserting javascript with insertUI, does it have to be wrapped in tags$head()? (Bug or feature?)

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1545]
Consider this code that adds JS code that simply shows an alert box:

```
ui <- fluidPage(
  actionButton("go", "Insert javascript with an alert")
)
server <- function(input, output, session) {
  observeEvent(input$go, {
    insertUI(
      selector = "head", where = "beforeEnd", immediate = TRUE,
      tags$script("alert('hello')")
    )
  })
}
shinyApp(ui = ui, server = server)
```

When you click the button, the javascript is added into the `<head>` tag of the DOM, but nothing happens.

If you wrap the inserted UI in `tags$head(...)`, then you do get the javascript alert to show up.

I don't know how the tags$head() works - I assumed that it simply inserts into the <head> tag, but that would mean that the original code should also work. I guess there is some extra magic that happens for tags$head() that doesn't happen when I add it manually. Is it correct that JS code (and maybe other resources?) have to be wrapped in `tags$head()` in order for them to work?

**Comment by bborgesr** [comment]
This seems to be a minor bug. When you use `tags$head`, [this](https://github.com/rstudio/shiny/blob/master/inst/www/shared/shiny.js#L3396-L3404) is called. This somehow seems to avoid [this problem](http://stackoverflow.com/questions/2592092/executing-script-elements-inserted-with-innerhtml) (script elements inserted using `innerHTML` do not execute when they are inserted.)

**Comment by jcheng5** [comment]
We could reimplement insertAdjacentHTML using jquery's after, before, prepend, and append functions.

**Comment by daattali** [comment]
Sometimes I wonder if I'm the only person who runs into this issue bcause once a year I come across this problem, google for a solution, and always end up back in this thread :)

That's a subtle way to **ping** to see if this would perhaps make it into a future release if the "Effort: Low" label is correct

**Comment by cpsievert** [comment]
> Sometimes I wonder if I'm the only person who runs into this issue 

@daattali not the only one :)

We should probably do what @jcheng5 suggested years ago, but in the meantime, a workaround is to leverage `htmlDependency()`'s `head` argument:

```r
ui <- fluidPage(
  actionButton("go", "Insert javascript with an alert")
)
server <- function(input, output, session) {
  observeEvent(input$go, {
    insertUI(
      selector = "head",
      ui = htmltools::htmlDependency(
        name = "fake-dep",
        version = "1.0",
        src = ".", package = "shiny",
        head = "<script>alert('hello')</script>"
      )
    )
  })
}
shinyApp(ui = ui, server = server)
```
