### ISSUE TITLE
reactivePoll leaks the polling observer

### ISSUE THREAD

**Issue by daemontus** [rstudio/shiny#1548]
(I am going to use reactiveFileReader as an example, since it directly uses reactivePoll and is easier to use as a demonstration)

Imagine this use case:
```
reactiveReader <- reactiveFileReader(100, session, somePath, readLines)
observer <- observe({
   content <- reactiveReader()
   ## do some magic stuff with content here
   if (!is.null(observer)) {
      observer$destroy()
      observer <- NULL
      reactiveReader <- NULL
   }
})
```

After executing this code, the programmer will probably think that the reactiveReader is properly cleaned-up and the polling mechanism has been properly disposed of.

Wrong.

Thanks to the leaked observer on line [1316](https://github.com/rstudio/shiny/blob/19623694f585c8e7a8cf2c38e831a6752e5520c6/R/reactives.R#L1316), the polling function will keep getting executed and as far as I know there is no way to actually cancel it.

If you have a long lasting session, this can and will cause a lot of trouble :)

**Comment by alandipert** [comment]
Thank you for the report, and sorry to take so long to look at this.

Is it correct to say that this is a problem for you because you're dynamically creating many `reactiveFileReader`s within a single session?

**Comment by daemontus** [comment]
Well, it's been a while, so my memory about this is a little hazy, but yeah, you could say it like that. Anyway... we wanted to monitor an ongoing process via file output, but the processes would start/stop based on user input and each would have to use a different file to avoid conflicts. So yeah, if the user started 20 processes, there would be 20 polling readers running in the background even though most of the processes were long gone and the observers were disposed of (not to mention sometimes having several concurrent users doing this - one whole CPU core could be wasted just polling files). In the end, I ended up writing a custom polling reader which we could actually destroy.

At least thats what I remember at this point - if there is any way I can help further, let me know.

**Comment by alandipert** [comment]
OK, thank you very much for elaborating. I would have suggested a custom polling strategy with `invalidateLater` or `later::later`, and it sounds like that's the path you ultimately went down.

It's definitely the case that there isn't a way to destroy a `reactiveFileReader()` before the session ends, so I think that adding a way could be a good enhancement. Thanks again for the report.

**Comment by juanmacarrillo** [comment]
> I ended up writing a custom polling reader which we could actually destroy

I'm having the same issue, but I haven't ended up with any solution yet. How did you manage to destroy `reactivePoll`?

**Comment by daemontus** [comment]
I would very much like to stress that I am by no means very fluent in R or shiny and it was a one-off thing approximately two years ago, so the current API or recommended design practices in general can be very different. That being said, this is the code we ended up using:
```
customReactiveFileReader <- function(intervalMillis, session, path, action) {
  clock <- createCounter(1)
  
  checkFunc <- function() {
    info <- file.info(path)
    return(paste(path, info$mtime, info$size))
  }

  cookie <- checkFunc()
  observe({
    latest <- checkFunc()
    if (latest != cookie || clock() %% 10 == 0) {
      cookie <- latest
      action(readLines(path))
    }
    invalidateLater(intervalMillis, session)
  })
}
```

Note the `clock() %% 10 == 0` condition should not be strictly necessary -- I'm not 100% sure why it got there, but I remember having an issue on some Windows systems where the `file.info` was not updated until other applications writing to `path` closed their streams. This made the reader unusable for progress tracking, as `file.info` would change only once the process we were tracking actually finished, not every time a new progress was written.
 
Anyway, this creates a standard observer which you can `suspend` or `destroy`:

```
observer <- customReactiveFileReader(1000, session$shiny, filePath, function(data) {
   # Do something with file data...
})
# Once file is obsolete:
observer$destroy()
```

Of course, this is specifically designed for files, in case of general `reactivePoll`, you want to replace `checkFunc` with your own implementation (and the extra `clock` condition is probably not relevant).
