### ISSUE TITLE
Incorrect ggplot2 click coordinates when using fixed aspect ratio

### ISSUE THREAD

**Issue by martinblostein** [rstudio/shiny#1554]
When using `coord_fixed()` with ggplot2, the coordinates returned by clicking on the plot do not take into account the fact that ggplot2 has changed the extent of its plotting window.

Minimal example:
```
library(shiny)
library(ggplot2)

ui <- fluidPage(
    plotOutput("mainPlot", click = clickOpts("mainPlotClick")),
    verbatimTextOutput("clickReading")
)

server <- function(input, output) {
    data <- data.frame(x = c(-10,10), y = c(-10,10))
    
    output$mainPlot <- renderPlot(
        ggplot(data, aes(x, y)) + coord_fixed()
    )
    
    output$clickReading <- renderPrint( input$mainPlotClick[1:2] )
}
shinyApp(ui = ui, server = server)
```

Clicking shows that the x coordinate corresponds to where the plot is before the `coord_fixed()` is applied. Commenting out the `coord_fixed()` has everything working properly.

**Comment by wch** [comment]
This is the same as #1121, and was fixed in #1525. You'll need the latest development version of Shiny for it to work.
