### ISSUE TITLE
Bootstrap datepicker crash

### ISSUE THREAD

**Issue by wojciech-ksiazek** [rstudio/shiny#1557]
I host my shiny app on a shiny server on AWS.
The app crashes instantly after start.

Browser console gives:
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 5)
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 5)
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 5)

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap-datepicker3.min.css.map, line 0)

**Comment by wch** [comment]
Can you provide a reproducible example, like a simple app. Also, version information (with `sessionInfo()` or better, `devtools::session_info()`) would be helpful.

**Comment by wojciech-ksiazek** [comment]
`sessionInfo()` dump:

`R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=C                 LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.3`

I'll provide an example as soon as possible

**Comment by wch** [comment]
It would help to have the `sessionInfo()` after you run the app, so that shows which packages are loaded when the app runs. (It looks like you've run it here on a new session.)

**Comment by wch** [comment]
It would help to have the `sessionInfo()` after you run the app, so that shows which packages are loaded when the app runs. (It looks like you've run it here on a new session.)

**Comment by wojciech-ksiazek** [comment]
When running on local machine it gives

> R version 3.3.2 (2016-10-31)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: macOS Sierra 10.12.3
> 
> locale:
> [1] C
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] lubridate_1.6.0 purrr_0.2.2     readr_1.0.0     tidyr_0.6.1     tibble_1.2      ggplot2_2.2.1   tidyverse_1.0.0
> [8] dplyr_0.5.0     shiny_1.0.0    
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.9      magrittr_1.5     munsell_0.4.3    colorspace_1.3-2 xtable_1.8-2     R6_2.2.0         stringr_1.1.0   
>  [8] plyr_1.8.4       tools_3.3.2      grid_3.3.2       gtable_0.2.0     DBI_0.5-1        htmltools_0.3.5  lazyeval_0.2.0  
> [15] assertthat_0.1   digest_0.6.11    mime_0.5         stringi_1.1.2    scales_0.4.1     jsonlite_1.2     httpuv_1.3.3 

I don't know how to give you this info, when running on a shiny server and accessing via browser. Also, there is no problem in running it locally.

**Comment by wch** [comment]
You can make an app like this one: https://gist.github.com/wush978/8db062e86c215345e279

**Comment by wojciech-ksiazek** [comment]
> [1] "R version 3.2.3 (2015-12-10)" [2] "Platform: x86_64-pc-linux-gnu (64-bit)" [3] "Running under: Ubuntu 16.04.1 LTS" [4] "" [5] "locale:" [6] " [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C " [7] " [3] LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 " [8] " [5] LC_MONETARY=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 " [9] " [7] LC_PAPER=en_US.UTF-8 LC_NAME=C " [10] " [9] LC_ADDRESS=C LC_TELEPHONE=C " [11] "[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C " [12] "" [13] "attached base packages:" [14] "[1] stats graphics grDevices utils datasets methods base " [15] "" [16] "other attached packages:" [17] "[1] shiny_1.0.0" [18] "" [19] "loaded via a namespace (and not attached):" [20] "[1] R6_2.2.0 tools_3.2.3 htmltools_0.3.5 Rcpp_0.12.9 " [21] "[5] jsonlite_1.2 digest_0.6.11 xtable_1.8-2 httpuv_1.3.3 " [22] "[9] mime_0.5 "

**Comment by wch** [comment]
Hm, that looks OK to me. It would help if you could run `devtools::session_info()` on both the client and the server, and also provide a reproducible example.

**Comment by wojciech-ksiazek** [comment]
can't provide reproducible example for now, but it seems it's a problem with reactive UI (rendered with `renderUI`). Also, installing RStudio Server on the instance somehow solved the problem
