### ISSUE TITLE
Shiny checks relative paths in .Rmd even if deselected from upload

### ISSUE THREAD

**Issue by martinjhnhadley** [rstudio/shiny#1561]
Create a shiny app directory as follows:

- ui.R
- server.R
- index.Rmd

```R
#ui
shinyUI(
fluidPage()
)
``` 

```R
#server
shinyServer(function(input,output){})
```

```md
# index.Rmd
---
title: "Readme"
author: "Foobar"
output: 
  html_document:
    css: [../../../gh-pages_global/gh-pages_navbar.css, ../../../gh-pages_global/custom-width.css]
    includes:
      in_header: ../../../gh-pages_global/_navbar.html
---
I'm a very thorough documentation for this shiny app
```

Select "Publish" to shinyapps.io, deselect "index.Rmd", press "Publish"

RStudio warns: "Publish content issues found"

```
index.Rmd
Line 6 Paths should be files within the project directory
Line 8 Paths should be files within the project directory
```

Should RStudio not skip checking index.Rmd as it is not being included in the upload to shinyapps.io?

**Comment by jcheng5** [comment]
Thanks for the bug report! @jmcphers, do you know who wrote the linting logic?

**Comment by kevinushey** [comment]
That was me; I can take a look.

**Comment by alandipert** [comment]
Closing because this is an RStudio issue, but I filed a ticket there to continue tracking it.
