### ISSUE TITLE
"Lost" fileextension in downloadHandler

### ISSUE THREAD

**Issue by fabiangehring** [rstudio/shiny#1562]
The example [download-knitr-reports.](http://shiny.rstudio.com/gallery/download-knitr-reports.html ) does not show a file extension nor a content type in the filechooser anymore. 

![image](https://cloud.githubusercontent.com/assets/13698134/22382240/1beb4efe-e4c5-11e6-8b81-b22cee7b5f55.png)

shiny 1.0.0, R 3.3.1,  RStudio 1.0.136  on Win 10

**Comment by jcheng5** [comment]
Thanks. What browser?

**Comment by fabiangehring** [comment]
Rstudio's intregrated browser. Other browsers seem to be fine (Chrome 56.0.2924.76, and IE Edge 25.10586.672.0)

**Comment by VincentLous** [comment]
I have the same issue on Chrome/Windows.

**Comment by wch** [comment]
I just tested with RStudio 1.1.299 and it also loses the extension.

**Comment by alandipert** [comment]
When run inside RStudio 1.0.153 on Windows 10, the downloaded file is called "downloadData". The built-in viewer seems to use the last path component of the link instead of the name and extension as sent by the server.

```R
library(shiny)

ui <- downloadLink('downloadData', 'Download')

server <- function(input, output) {
  output$downloadData <- downloadHandler(
    filename = function() {
      paste('data-', Sys.Date(), '.csv', sep='')
    },
    content = function(con) {
      write.csv(mtcars, con)
    }
  )
}

shinyApp(ui = ui, server = server)
```

**Comment by skhan8** [comment]
This is still happening on Windows 10 and CentOS.

**Comment by alandipert** [comment]
Closing because this is an RStudio issue: rstudio/rstudio#3483
