### ISSUE TITLE
Resources with spaces in their names return HTTP 404

### ISSUE THREAD

**Issue by jmcphers** [rstudio/shiny#1565]
Given this single-page Shiny application:

    library(shiny)

    addResourcePath("foo", "foo")

    ui <- fluidPage(
      img(src="foo/foo.png"),
      img(src="foo/b a r.png"),
      img(src=URLencode("foo/b a r.png")),
      img(src="foo/b%20a%20r.png")
    )

    shinyApp(ui = ui, server = function(input, output) {})

And a folder `foo` containing `foo.png` and `b a r.png`, it's possible to reference `foo.png` easily, but any form of address for `b a r.png` results in 404 (above are the three forms I've tried).

**Comment by jcheng5** [comment]
See the `staticHandler` function in middleware.R. Hard to believe, but we are missing a urldecode...

**Comment by bborgesr** [comment]
@jmcphers This should be fixed now. Let us know if you're still having any problems...
