### ISSUE TITLE
Shiny input controls should have option to record and reconstitute state in hash

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#158]
This would be purely client side - e.g. each input control that opts in to the url hash would add an extra attribute. A js function would look for inputs with matching attribute and add an event handler. Whenever the control changes, the url hash would also be updated.  Finally, when the url is first loaded, a javascript hook would replay the state.

**Comment by jcheng5** [comment]
Life seemed so simple back in 2013...

Closing now that bookmarkable state has landed in master.
