### ISSUE TITLE
Issue with launching the shiny app

### ISSUE THREAD

**Issue by neelan29** [rstudio/shiny#1580]
I have followed the steps for running the Shiny app. At first, I got a warning to install the latest versions for a few packages. But even after having installed them, I keep getting this error:

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object '.setDummyField' not found

It would be very helpful if you could suggest what to do. Thanks.

**Comment by wch** [comment]
What version of R are you using? We saw this previously with R 3.0.1, and it was due to a bug in R.
https://groups.google.com/d/msg/shiny-discuss/o9XAMksRGXY/Za0lBSKQClgJ

**Comment by neelan29** [comment]
I installed both 3.0.0 and 3.3.2 . Not able to fix this bug still .

**Comment by wch** [comment]
Have you tried installing 3.3.2 and then re-installing all of your packages, including Shiny?

**Comment by neelan29** [comment]
Yea jus tried and it worked. Thank you so much.
