### ISSUE TITLE
sliderInput don't show label on updateSliderInput

### ISSUE THREAD

**Issue by kraso** [rstudio/shiny#1587]
I want to change values on sliderInput with updateSliderInput:
`sliderInput("obs", "Number of observations:", min = 0, max = 1000, value = c(100, 200))`

If I set these two values to be the same, then label is not shown until I click on circle:
`updateSliderInput(session, "obs", value=c(500, 500))`

**Comment by bborgesr** [comment]
Here's a minimal repro:

```r
ui <- fluidPage(
  sliderInput("obs", "Number of observations:", min = 0, max = 1000, value = c(100, 200)),
  actionButton("go", "Go")
)

server <- function(input, output, session) {
  observeEvent(input$go, {
    updateSliderInput(session, "obs", value=c(500, 500))
  })
}

shinyApp(ui, server)
```

I only get the behavior you describe in the CRAN version of Shiny. It seems to be working correctly using the devel version (`devtools::install_github("rstudio/shiny")`)

Can you confirm?

**Comment by kraso** [comment]
Yes, I can confirm that github development version works, while CRAN version do not. Thanks!
