### ISSUE TITLE
numericInput only accepting numbers

### ISSUE THREAD

**Issue by bklingen** [rstudio/shiny#1593]
Currently, ``numericInput`` allows to enter (several) characters on which it will return NA. Is there a way to have it not even react when anything other than numbers are supplied? I imagine something like the box flashing when a character is entered and then reverting to the previous value, without throwing any kind of error.

I guess one can capture that using ``updateNumericInput``, but it seems like it should be default behavior to not accept any input other than numeric. (Or maybe make this an option in the function call, such as onlyNumeric=TRUE). 
The only exception is when the box is empty, in which case it should return NA.

If you have several numericInputs in your ui, checking that each of them is not NA and updating them if they are seem tedious.

Thanks!

**Comment by bklingen** [comment]
Actually, a very similar problem (accepting numbers exceeding the given range) is reported in #927

**Comment by albertosantini** [comment]
See also https://github.com/rstudio/shiny/issues/1022#issuecomment-282305308

**Comment by alandipert** [comment]
Thank you for the suggestion. Closing since we're tracking this and other validation ideas on #1656.
