### ISSUE TITLE
global reactivePoll? 

### ISSUE THREAD

**Issue by nikolaypavlov** [rstudio/shiny#1601]
I use reactivePoll() in my app to cover quite costly SQL query. However, every time a new user connects to the Shiny server, I see the query been repeated. Is there any way to make reactivePoll global for all users?

**Comment by stanstrup** [comment]
If you put it in global.R it should do this AFAIK.

**Comment by nikolaypavlov** [comment]
It works. @stanstrup thank you. Also I found this guide very useful: https://shiny.rstudio.com/articles/scoping.html

**Comment by KrushnaOrigoNetworks** [comment]
Hi @nikolaypavlov I have a similar requirement to have reactivePoll in global.r and data needs to be retrieved there and used in server.r.
Can you please share your code snippet?

**Comment by shrektan** [comment]
It should be simply cut and paste the code into global.R. Set the session argument to NULL. That’s it.

**Comment by KrushnaOrigoNetworks** [comment]
Thanks. I did that. I get an error. Here is the code snippet.
`global.r
library(shiny)
#library(plyr)
library(DT)
library(data.table)
library(plotly)
library(MASS)
library(forecast)
library(shinythemes)

ReadTenantData<- function(dataFilePath, ...)
{
        #Some other logic
   #........

   pollData <- reactivePoll(1000*60*10, session,
      checkFunc = function() {
         if (file.exists(dataFilePath))
            file.info(dataFilePath)$mtime[1]
         else
            ""
      },
      valueFunc = function() {
         fread(dataFilePath, ...)
      }
   )
   reactive(pollData())
}

tenant_data <- ReadTenantData("data/tenant_info.csv", autoRefresh=TRUE, header=T, sep=",")
`
`server.r
shinyServer(
  function(input, output, clientData, session) {

    output$table_data <- DT::renderDataTable({
                out = tenant_data
                colnames(out) = c("Env","Tenant","START_TIME","END_TIME","LENGTH_HOURS","VERSION","STATE")
                DT::datatable(out, options = list(orderClasses=TRUE, pageLength=10),rownames= FALSE)
        })
  }      
) `

The code is quite simple. For historical reason, I need to initialize/assign the data variable in global.r.

When I execute, I get an erro
`Listening on http://127.0.0.1:38281
Warning: Error in colnames<-: attempt to set 'colnames' on an object with less than two dimensions
Stack trace (innermost first):
    83: colnames<-
    82: exprFunc [/data/shiny-server/shiny-apps/test-reactive-poll/server.r#14]
    81: widgetFunc
    80: func
    79: origRenderFunc
    78: renderFunc
    77: origRenderFunc
    76: output$table_data
     1: runApp
`
