### ISSUE TITLE
Migration to new Bootstrap v4

### ISSUE THREAD

**Issue by dmpe** [rstudio/shiny#1604]
Hi, 
I know this is something which is described in the contribution guidelines, but a certain point of time, (soon) there will be a new version of bootstrap, now currently in alpha (v6). 
https://v4-alpha.getbootstrap.com/

This will bring a [lot of changes ](https://v4-alpha.getbootstrap.com/migration/) and many breaking ones. E.g.:
>Dropped IE8, IE9, and iOS 6 support. v4 is now only IE10+ and iOS 7+. For sites needing either of those, use v3.
>Dropped the Glyphicons icon font.

I dont think it would be right to incorporate all these changes in the "shiny" library. Instead, better, if a new package is created, e.g. "shiny2" (which would require to adapt it in the rstudio as well). 

Any opinions ?
Just FYI & tracking.

**Comment by nteetor** [comment]
I cannot speak to creating a new package, but I am interested in shiny's migration to bootstrap 4.

**Comment by dmpe** [comment]
@nteetor follow my shiny fork then :)

**Comment by bborgesr** [comment]
Thanks for the note. It will be a while until we start implementing this. So I'll close this issue for now and open an updated issue when we actually have more concrete ideas of how we'll migrate or integrate with Bootstrap v4.

**Comment by rohitjose** [comment]
When is the migration to bootstrap 4 planned for?

**Comment by nteetor** [comment]
For those interested in bootstrap 4 plus shiny you might check out [dull](https://github.com/nteetor/dull).

**Comment by ben519** [comment]
Also interested in seeing this happen.

**Comment by el-mazarol** [comment]
I'm interested too.

**Comment by AlexanderKozhevin** [comment]
+1

**Comment by kevinwtbolger** [comment]
@bborgesr has there been any recent movement on this?

**Comment by kuzmenkov111** [comment]
+1

**Comment by augustohassel** [comment]
+1

**Comment by cpsievert** [comment]
It's currently possible to use Bootstrap 4 with **shiny** via **bootstraplib**  https://rstudio.github.io/bootstraplib

**Comment by GitHunter0** [comment]
Hey @bborgesr , any idea when this thread will be reopened? Thank you
