### ISSUE TITLE
sliderInput unintentional behavior change

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1605]
Repro:

```r
ui <- fluidPage(sliderInput("slidername", NULL, min=0, max=100, value=0))
server <- function(input, output, server) {}
shinyApp(ui, server)
```

Probably an artifact of updating the ion range slider library and not noticing this change... We could just document this change and accept, or we can try to preserve the old behavior...

Origin: http://stackoverflow.com/questions/42764365/shiny-sliderinput-behaviour-change

Working fine in 0.13.2; different/broken behavior in 0.14.

**Comment by wch** [comment]
With a `git bisect` I found that the bad commit was 7510c02d83845d598807edc6f645bb56c8d62217.

Experimenting with ion.rangeSlider a bit, the problem seems to be due to using `data-drag-interval="true"` for a single-value slider (it's only relevant for a range slider).

**Comment by SymbolixAU** [comment]
Has the `dragRange` argument been broken by the updates? I've not tried it before but I've just attempted to use it and setting `dragRange = FALSE` doesn't appear to have any impact

```
ui <- fluidPage(sliderInput("slider",NULL,min = 0,max = 24,value = c(0, 10),dragRange = FALSE))
server <- function(input, output){}
shinyApp(ui, server)
```

**Comment by wch** [comment]
@SymbolixAU `dragRange` is working for me. Can you describe the behavior you're seeing, and open a new issue for it?

**Comment by SymbolixAU** [comment]
my bad - I mis-interpreted what that argument was doing. I thought it was fixing the min & max values to be a constant 'distance' apart.
