### ISSUE TITLE
invalid 'x' type in 'x && y' error

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/shiny#1606]
With a particular development version of `shiny` package on 3/9/2017, we were seeing an issue on RSConnect.  (https://github.com/rstudio/connect/issues/5346) 
This was the warning/error in the log file:

```
2017/03/13 20:42:55.056825478 Warning: Error in &&: invalid 'x' type in 'x && y'
2017/03/13 20:42:55.062866947 Stack trace (innermost first):
2017/03/13 20:42:55.062872573     60: private$shouldSuspend
2017/03/13 20:42:55.062881757     59: .subset2(public_bind_env, "initialize")
2017/03/13 20:42:55.062884757     58: Observer$new
2017/03/13 20:42:55.062892258     57: observe
2017/03/13 20:42:55.062894243     56: .subset2(x, "impl")$defineOutput
2017/03/13 20:42:55.062899199     55: [[<-.shinyoutput
2017/03/13 20:42:55.062900898     54: [[<-
2017/03/13 20:42:55.062906454     53: param.ui
2017/03/13 20:42:55.062908132     52: FUN
2017/03/13 20:42:55.062912906     51: lapply
2017/03/13 20:42:55.062914630     50: server
2017/03/13 20:42:55.062928784      9: <Anonymous>
2017/03/13 20:42:55.062930754      8: do.call
2017/03/13 20:42:55.062935677      7: knit_params_ask
2017/03/13 20:42:55.062937330      6: eval
2017/03/13 20:42:55.062953530      5: eval
2017/03/13 20:42:55.062955535      4: eval
2017/03/13 20:42:55.062960403      3: eval
2017/03/13 20:42:55.062962090      2: eval.parent
2017/03/13 20:42:55.062967281      1: local
2017/03/13 20:42:55.063381227 Error in hidden && private$getOutputOption(name, "suspendWhenHidden",  : 
2017/03/13 20:42:55.063386637   invalid 'x' type in 'x && y'
```

Same error was being reported on the Selenium tests running on Jenkins:

https://buildmaster.rstudioservices.com/job/shiny-local-test/349/label=shinytest/console

I couldn't reproduce it locally that day. And then error was gone on 3/10/2017.

Also on RSConnect, with the very latest development version of `shiny` (as of 3/13/2017) we don't see the issue, but I just wanted to bring this to your attention. Feel free to close.

**Comment by wch** [comment]
I made some changes recently that introduced that error, but it should have been fixed by 7a83345, which was made on 3/10/2017. Thanks for checking in about it though!
