### ISSUE TITLE
Cannot overwrite <title></title>

### ISSUE THREAD

**Issue by cinkie** [rstudio/shiny#1607]
I use `tags$head(tags$title('myTitle'))` in ui.R under `dashboardBody`. The HTML webpage output is still
`<head>`
`<title></title>`
`<title>myTitle</title>`
`</head>`

**Comment by bborgesr** [comment]
This seems like a shinydashboard issues.

Overwrites fine for:
```r
library(shiny)
ui <- fluidPage(tags$head(tags$title('myTitle')))
server <- function(input, output, session) {}
shinyApp(ui, server)
```

But, donesn't overwrite for:
```r
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(tags$head(tags$title('myTitle')))
)
server <- function(input, output, session) {}
shinyApp(ui, server)

```

**Comment by cinkie** [comment]
Yes, I will post this issue to shinydashboard github.
