### ISSUE TITLE
downloadHandler not binding when link in table

### ISSUE THREAD

**Issue by gbisschoff** [rstudio/shiny#1609]
Hi I am trying to create a datatable each with Name of a dataset that the user has uploaded (which is saved server side). I have managed to add an action link in the table that I use to view & delete the dataset. Now I am trying to include a download button in which the user will be able to download the data he/she originally uploaded. I am struggling in setting up the downloadHandler for the dynamically created table with download buttons in it. Here is what I have so far:

```

library(shiny)
library(DT)

ui <- fluidPage(
  dataTableOutput("table")
)

server <- function(input, output,session) {
  v<-reactive({
    temp<-data.frame(TBL.name=paste("Data ",1:10))
    temp<-cbind(
      temp,
      #Dynamically create the download and action links
      Action=sapply(seq(nrow(temp)),function(i){as.character(actionLink(paste0("Action_",i),label = paste0("Action ",i),onclick=paste0('Shiny.onInputChange(\"action_click\", (this.id))'),class="btn"))}),
      Download=sapply(seq(nrow(temp)),function(i){as.character(downloadLink(paste0("downloadData_",i),label = paste0("Download Data ",i)))})
    )
    DT::datatable(temp,rownames = FALSE,options = list(dom = 't'),selection = "none",class='cell-border strip hover',escape = FALSE)
  })

  output$table<-renderDataTable({
    v()
  })

  #Events on view that will bring display a modal and delete that deletes the data
  observeEvent(input$action_click,{print(input$action_click)})

  observe({
    lapply(seq(nrow(v())),function(i){
      output[[paste0("downloadData_",i)]] <- downloadHandler(

        filename = function() {
          paste("data-",i, Sys.Date(), ".csv", sep="")
        },
        content = function(file) {
          write.csv(iris,file)
        }
        
      )

    })
  })    
}

# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by jcheng5** [comment]
I don't think `shiny::downloadLink()` will work inside a DT... @yihui, we don't call bindAll/bindInput/bindOutput in DT, right?

**Comment by yihui** [comment]
That is right.

**Comment by serdar-eric** [comment]
@jcheng5 @yihui That would be great if you have other suggestion to overcome this. I am struggling with the same problem, trying to find a way to place a download button for each row of the DT and let the user to download some content depending on the row.

**Comment by gbisschoff** [comment]
So what I did was add a normal action button, that pops up a modal with
some general information about the download, and then of course the
download button as well.

**Comment by alandipert** [comment]
I'm closing because the original author worked around the problem. It sounds like a possible DT feature idea though, so please don't hesitate to open a new issue on [rstudio/DT](https://github.com/rstudio/DT).
