### ISSUE TITLE
FontAwesome icons specified as unicode not displayed properly

### ISSUE THREAD

**Issue by nteetor** [rstudio/shiny#1611]
I stumbled across this issue when trying to specify a FontAwesome unicode string as an html tag data attribute.

The small shiny app below demos how `icon("square-o")` and a standard unicode symbol &spades; display properly, but a FontAwesome icon specified using unicode does not display correctly. 

```R
library(shiny)

shinyApp(
  ui = fluidPage(
    tags$ol(
      tags$li(
        icon("square-o")
      ),
      tags$li(
        "&#xf096;"
      ),
      tags$li(
        HTML("&#xf096;")
      ),
      tags$li(
        enc2utf8("&#xf096;")
      ),
      tags$li(
        HTML(enc2utf8("&#xf096;"))
      ),
      tags$li(
        HTML(enc2utf8("&#x2660;"))
      ),
      tags$li(
        HTML(enc2utf8("&spades;"))
      )
    )
  ),
  server = function(input, output, session) {
    
  }
)
```

The output: 
![screen shot 2017-03-17 at 11 18 03 am](https://cloud.githubusercontent.com/assets/3228369/24049776/6c21b426-0b03-11e7-8c51-82cf16ea3745.png)

See http://fontawesome.io/cheatsheet/ for `fa-square-o` unicode.

**Comment by jcheng5** [comment]
I think you'd also need to change the font-family using CSS if you want
these to work.

**Comment by jcheng5** [comment]
Yeah, see here: http://stackoverflow.com/questions/17254339/font-awesome-unicode

**Comment by nteetor** [comment]
You are absolutely correct.

My example was not what I meant to put together. I think I was too deep in the weeds by that point. 

The real problem, that I tried to abstract away in my first example application, is shiny does not seem to allow inclusion of FontAwesome icons through CSS `attr()` and tag data attributes. Here is an SO link better illustrating what I am trying to accomplish, http://stackoverflow.com/questions/34596056/how-to-use-data-attributes-with-font-awesome. 

In shiny using a data attribute has not worked. Here is an updated example,
```R
shinyApp(
  ui = fluidPage(
    tags$head(
      tags$style(".marked::before { font-family: FontAwesome; font-style: normal; content: attr(data-icon) }")
    ),
    tags$ol(
      tags$li(
        icon("square-o")
      ),
      tags$li(
        HTML("&spades;")
      ),
      tags$li(
        class = "marked",
        `data-icon` = HTML("&#xf096;")
      )
    )
  ),
  server = function(input, output, session) {
    
  }
)
```

![screen shot 2017-03-17 at 5 53 21 pm](https://cloud.githubusercontent.com/assets/3228369/24064403/a798420e-0b3a-11e7-8278-0acc89336aa7.png)

**Comment by jcheng5** [comment]
Oh OK, that's fair. The reason is because the HTML tag functions always HTML-escape their attributes; `HTML()` is not respected for attributes. In this case, you can use a literal character instead:

```r
`data-icon` = "\uf096"
```

**Comment by nteetor** [comment]
Yes, this worked perfectly, thank you Joe. My apologies for this turning into more of a SO post.
