### ISSUE TITLE
Step in the sliderInput *WITH DATES*

### ISSUE THREAD

**Issue by gsimchoni** [rstudio/shiny#1618]
This is probably related to: https://github.com/rstudio/shiny/issues/199

```
library(dplyr)
ui <- basicPage(sliderInput("week",
                            "week",
                            min = as.Date("2016-05-22"),
                            max = as.Date("2016-12-04"),
                            value = as.Date("2016-05-22"),
                            step = 7),
                textOutput("text")
)
server <- shinyServer(function(input, output, session){
  
  df <- data.frame(week = seq(as.Date("2016-05-22"), as.Date("2016-12-04"), by = "1 weeks"),
                   x = rep(1, 29))
  output$text <- renderText({
    df %>% filter(week == input$week) %>% select(x) %>% unlist
  })
})
shinyApp(ui = ui, server = server)

```

Look what happens when you manually move the slider from "2016-07-03" to the next point. You expect "2016-07-10" (7 days step), but you get "2016-07-09" for some weird reason (6 days step), and 7 days steps onward ("2016-07-16" etc.).

What is going on, am I missing something?

**Comment by wch** [comment]
I'm able to replicate this problem in the latest released version of Shiny (1.0.0) but not in the latest development version on Github. In the dev version we updated the ion.rangeSlider Javascript library, so that's probably what fixed it.
