### ISSUE TITLE
Dragging slider on absolutely positioned panels also moves panel

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#1630]
This app illustrates the problem:
https://github.com/rstudio/shiny-examples/tree/master/027-absolutely-positioned-panels

**Comment by wch** [comment]
Bisected to 9d69ff01b3b5a11fce558908cacc4d6eec8e651e.

**Comment by wch** [comment]
It looks like it's #711 again.

**Comment by jiehu567** [comment]
Hi, might I know how if this has been solved?
If I want to put slideinput in absolutePanel, what I should do to make the slide bar moving smoothly?

Thanks.

**Comment by wch** [comment]
@jiehu567 It should be working now with the current version of Shiny. If you are having problems, you can file a new issue.

**Comment by wch** [comment]
The slider in an absolute panel works for me in this app: http://shiny.rstudio.com/gallery/absolutely-positioned-panels.html

**Comment by jiehu567** [comment]
Thanks!
