### ISSUE TITLE
Problem in rendering table and math in Rmarkdown when called from Shiny App

### ISSUE THREAD

**Issue by gundalav** [rstudio/shiny#1645]
I have a Rmarkdown file (`info.rmd`) that looks like this:

    ---
    title: "Information"
    theme: yeti
    date: "4/1/2017"
    output: html_document
    ---
    
    
    ## R Markdown
    
    This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
    
    
    ```{r echo = FALSE, results = 'asis'}
    library(knitr)
    kable(mtcars[1:5, ], caption = "A knitr kable.")
        ```
    
    ## Formulation
    
    Here is where we formulate
    $$\sum_{i=1}^n X_i$$

And the ShinyApp that calls Rmarkdown like this:

**server.R**

contains this

      output$markdown <- renderUI({
        HTML(markdown::markdownToHTML(knit('info.rmd', quiet = TRUE), fragment.only=TRUE))
      })

**ui.R**

contains this:

     fluidPage(uiOutput('markdown'))

But how come the table and math generated looks like this?

[![enter image description here][1]][1]

What's the right way to do it?

---

When run independently outside Shiny the `info.rmd` produces the table properly:

[![enter image description here][2]][2]

---

I tried this in `ui.R`

 

     includeHTML("info.html")

Which shows the file html correctly, but prevent the plotting
and reactivity in other `tabPanel()` to work.

  [1]: https://i.stack.imgur.com/bn4yQ.jpg
  [2]: https://i.stack.imgur.com/d5s8s.jpg

**Comment by jcheng5** [comment]
What happens if you omit the fluidPage--just have ui <- uiOutput(...)?

Also, try wrapping the inside of your renderUI expression with
withMathJax(); that will cause a MathJax rendering to be triggered (it
normally happens only on page load I believe, which is too early in this
case, since the knitted output isn't shown until later).

Have you considered using rmarkdown's runtime:shiny mode?
http://rmarkdown.rstudio.com/authoring_shiny.html

**Comment by alandipert** [comment]
Closing because a possible workaround was provided and we never heard back. Please don't hesitate to comment further or create a new issue if this is still a problem for you.

**Comment by igmoreiraj** [comment]
I've been having the same output problem, however I am not using shiny, I am just rendering my table using knit and kable and kableExtra and my output looks pretty similar to the one mentioned.
