### ISSUE TITLE
Fix the selection for selectInput

### ISSUE THREAD

**Issue by wenbostar** [rstudio/shiny#1648]
Hi,
In some case, I want to fix the selection for selectInput and don't want user to change the value. Is it possible in shiny?
Best regards!
Bo

**Comment by jcheng5** [comment]
I don't believe it is possible--can you give some more specifics about what you're trying to do? You want it to be fixed just for a period, or permanently?

**Comment by bklingen** [comment]
You could use updateSelectInput to make it impossible to change the value, i.e., every time the user tries to change it, the change doesn't go through:
```{r}
library("shiny")
app <- shinyApp(
  ui = fluidPage(selectInput("myselection", "Select:", choices=list("a","b","c"))),
  server = function(input, output, session) {
    observeEvent(input$myselection, updateSelectInput(session, "myselection", selected="a"))
  }
)
  
runApp(app)
```

**Comment by wenbostar** [comment]
@jcheng5 Thanks a lot. In my case, when a user select the an item in "selectInput", I want to fix some other parameters value.

**Comment by wenbostar** [comment]
@bklingen , thanks a lot. It's a good suggestion.

**Comment by alandipert** [comment]
Closing because it looks like you were able to work around your problem. If you have other questions, don't hesitate to comment further or create a new issue.
