### ISSUE TITLE
Incorrect margin-bottom in #showcase-code-tabs div creates empty space 

### ISSUE THREAD

**Issue by dmpe** [rstudio/shiny#1654]
https://gallery.shinyapps.io/006-tabsets/

Only when the code is shown below (not next to the tabs etc.):

Call me picky but I dont understand why the code should not fill in the whole space ("|" in the picture == empty space).
 
![image](https://cloud.githubusercontent.com/assets/1799661/24707590/85d6fce4-1a14-11e7-9eeb-8484c85acbb5.png)

Can be fixed by adding `margin-bottom: 0px;` to the `pre class="shiny-code"`

![image](https://cloud.githubusercontent.com/assets/1799661/24707695/eff28b52-1a14-11e7-83c3-03a77aaebd53.png)

**Comment by jcheng5** [comment]
Thanks!
