### ISSUE TITLE
Showcase mode: Plot image goes over the code content but is able to get it right after swiching tabs multiple times.

### ISSUE THREAD

**Issue by dmpe** [rstudio/shiny#1659]
Finally was able to reproduce it:

Steps to reproduce:
1. Load https://gallery.shinyapps.io/006-tabsets/

2. Everthing is nice:
![image](https://cloud.githubusercontent.com/assets/1799661/24749843/e2d32188-1ac4-11e7-9f11-6f04d49d8939.png)

3. Click on "show below button"
4. Click again on "show with app"

5. Problem:
![image](https://cloud.githubusercontent.com/assets/1799661/24749821/d5bc04ba-1ac4-11e7-9a9c-b9c48c49e56d.png)

6. And then after you switch tabs several times, the picture will be "normalized"

This also influences in part of what I was writing yesterday: https://github.com/rstudio/shiny/issues/1655

>Basically when a page loads, `<td id="showcase-sxs-code" class="showcase-sxs-code-collapsed" style="">` gets loaded with `display: hidden;` (automatically) resulting into the code panel (tabs + content) not being shown.  :(

is the **second part** of the problem 

This repro in chrome + IE10 on Win 7. (if necessary use only "iframe-xhr-polling"). 
EDIT: Tested in EDGE and same bug
FF works well though

**Comment by alandipert** [comment]
Related to #1636 and probably other showcase mode issues

**Comment by alandipert** [comment]
I wasn't able to repro in Edge 44.17763.1.0 on Windows 10, Chrome 74 on macOS, or Firefox 66 on macOS, so I assume this has since been resolved.
