### ISSUE TITLE
Pasting multiple items into selectizeInput

### ISSUE THREAD

**Issue by b-dawes** [rstudio/shiny#1663]
I'm building an application which uses selectize inputs with multiple = TRUE. I was looking for a way to allow users to paste in a comma separated list of items instead of having to enter each one in individually. It looks like selectize.js supports this as of version 0.12.0 (see [here](https://github.com/selectize/selectize.js/pull/425)).

Is there a way to do this in Shiny? I tried setting both delimiter and splitOn in options but neither seemed to have any effect.

**Comment by corinnend** [comment]
Hello - were you able to find a solution? I'm running into the same issue.

**Comment by wch** [comment]
It looks like you have to add a `create` function, like so:

```R
shinyApp(
  ui = fluidPage(
    selectizeInput("x", "Choose:",
      letters,
      multiple = TRUE,
      options = list(
        delimiter = ',',
        create = I("function(input, callback){
          return {
            value: input,
            text: input
           };
        }")
      )
    )
  ),
  server = function(input, output) { }
)
# Copy and paste a,b,c,d
```

I found this by trying it with just Javascript here: https://jsfiddle.net/winstonchang/462qjrru/1/

Note that this will also attempt to *create* entries that don't exist. That's how the `delimiter` option works, according to https://github.com/selectize/selectize.js/blob/master/docs/usage.md.

Instead of `delimiter`, you can pass a regular expression to `splitOn`: https://jsfiddle.net/winstonchang/462qjrru/3/

However, to get it from R to Javascript takes a little more work - you can't pass a Javascript regex directly, but you can pass an immediately-invoked function that returns a regex.

```R
shinyApp(
  ui = fluidPage(
    selectizeInput("x", "Choose:",
      letters,
      multiple = TRUE,
      options = list(
        splitOn = I("(function() { return /[,;]/; })()"),
        create = I("function(input, callback){
          return {
            value: input,
            text: input
           };
        }")
      )
    )
  ),
  server = function(input, output) {
  }
)

# Copy and paste 1,2,3,4,5;6;7
```

**Comment by saif003** [comment]
@wch This, fails if you try entering case sensitive characters, try entering 'a,b,c,d' to this [fiddle](https://jsfiddle.net/bfo54LLf/).

**Comment by JacobBumgarner** [comment]
Here is an example of built off of @wch's solution that allows paste options input to selectize but only accepts values that are present in the options list.

```r
shinyApp(
  ui = fluidPage(
    actionButton("button", "Input"),
    selectizeInput(
      "x",
      "Choose:",
      letters,
      multiple = TRUE,
      options = list(
        splitOn = I("(function() { return /[,; ]/; })()"),
        create = I("function(input, callback){
                   var selectize_options = $('#x')[0].selectize.options;
                   if (selectize_options[input] == undefined) {
                    return {};
                   } else {
                    return {value: input, label: input};
                   }}")
      )
    )
  ),
server = function(input, output, session) {
  observeEvent(input$button, {
    updateSelectizeInput(
      session = session,
      inputId = "x",
      choices = letters,
      selected = c("a", "1"),
      server = TRUE
    )
  })
}
)

# example paste: a,1,b,2,c,3,d,xyz;f hello g


```
