### ISSUE TITLE
Problem to install shiny on Ubuntu16.04

### ISSUE THREAD

**Issue by agnesols** [rstudio/shiny#1667]
> install.packages("shiny")
Installing package into ‘/home/agnes/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependencies ‘jsonlite’, ‘sourcetools’

downloaded 0 bytes

Warning in install.packages :
  URL 'https://cran.rstudio.com/src/contrib/jsonlite_1.3.tar.gz': status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot download all files
Warning in install.packages :
  download of package ‘jsonlite’ failed

downloaded 0 bytes

Warning in install.packages :
  URL 'https://cran.rstudio.com/src/contrib/sourcetools_0.1.5.tar.gz': status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot download all files
Warning in install.packages :
  download of package ‘sourcetools’ failed
trying URL 'https://cran.rstudio.com/src/contrib/shiny_1.0.1.tar.gz'
Content type 'application/x-gzip' length 2272409 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

ERROR: dependencies ‘jsonlite’, ‘sourcetools’ are not available for package ‘shiny’
* removing ‘/home/agnes/R/x86_64-pc-linux-gnu-library/3.3/shiny’
Warning in install.packages :
  installation of package ‘shiny’ had non-zero exit status
======================
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] class_7.3-14 tm_0.7-1     NLP_0.1-10  

loaded via a namespace (and not attached):
[1] parallel_3.3.3 tools_3.3.3    Rcpp_0.12.10   slam_0.1-40  
===================
$ gcc -v 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by wch** [comment]
Can you try again now? This was probably due to a cache syncing issue on the CRAN mirror.

**Comment by agnesols** [comment]
Great, works now, thanks!
