### ISSUE TITLE
Re-render multiple chunks

### ISSUE THREAD

**Issue by MarkusKonk** [rstudio/shiny#1669]
Hello,
is it possible to re-render multiple chunks after I change, for example, the input file? I hope the following example is understandable:
In a first chunk I load and maybe process a dataset. In second chunk I plot the data by triggering the reactive part. In a third chunk I again try to do something with the dataset but it is not possible because the dataset is not visible `(Error: Object 'CB.dat' not found).` Is there a solution for this problem?

```{r echo=FALSE}
library(shiny)
fileInput('file1', 'Choose your own CSV File instead of provided 
data',accept=c('text/csv', 'text/comma-separated-values,text/plain', 
'.csv'))

go1<-reactive({
  dpath <- "CurrentBiologyData.txt"
  if(!is.null(input$file1)){
     dpath <- input$file1$datapath
  }
  CB.dat <- read.table(dpath, header = TRUE)  #choose 'CurrentBiologyData.txt'
  
  plot(CB.dat)
})
```

```{r echo=FALSE}
renderPlot({
      go1()
})
```

```{r}
renderPlot({
     print(CB.dat)
})
```
Transforming CB.dat to a global variable (<<-) is technically possible but not desireable.

**Comment by mschilli87** [comment]
Why don't you use two `reactive`s, one for each object?

*untested*:

```r
CB.dat <- reactive({
  dpath <- "CurrentBiologyData.txt"
  if(!is.null(input$file1)){
     dpath <- input$file1$datapath
  }
  read.table(dpath, header = TRUE)  #choose 'CurrentBiologyData.txt'
})
```

```r
go <- reactive({
    plot(CB.dat())
})
```

```r
renderPlot({
      go1()
})
```

```r
renderPlot({
     print(CB.dat())
})
```

**Comment by MarkusKonk** [comment]
It solves the problem but requires some code re-arrangement. I am looking for a solution which allows me to automatize the creation of Rmarkdown files including shiny out of static Rmarkdown. So I somehow have to be able to work with whatever I get as an input Rmarkdown file.

**Comment by bborgesr** [comment]
Sorry, can you explain why this is not possible for your use case?

```r
library(shiny)

data <- reactive({
  ...
  read.table(x)
})

renderPlot({
  plot(data())
})

renderPlot({
  print(data())
})
```

**Comment by jcheng5** [comment]
Never plot from within a reactive expression. Plotting is a _side effect_ and those are generally not allowed in reactive expressions.

If you're not able to do as the other commenters have recommended, it'd be really helpful to see the actual code that's presenting a problem.

Also, this kind of conversation should really go on in our [shiny-discuss group](https://groups.google.com/forum/#!forum/shiny-discuss); the Issues tracker is for well-defined feature requests and bug reports. Sorry for the inconvenience but it really helps us to keep it somewhat separated.
