### ISSUE TITLE
Use some coding conversions - as it varies tremendously

### ISSUE THREAD

**Issue by dmpe** [rstudio/shiny#1674]
e.g. 
```
if () 
  else 
```
or "better" (just decide for one and use it everywhere)

```
if () {
} else {
}
```

**Comment by wch** [comment]
We have some general patterns to how code is formatted in Shiny, but we aren't planning on converting all of our code to one format or another.

**Comment by dmpe** [comment]
Then at least to document it would be nice....Or does it already exist somewhere ?
