### ISSUE TITLE
R 3.4.0 gives warning on all Shiny apps

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1676]
The newest stable R version is printing a warning for every shiny app (although they run fine):

```r
R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)
...

> library(shiny)
> ui <- fluidPage()
> server <- function(input, output, session) {}
> shinyApp(ui, server)

Listening on http://127.0.0.1:4737
Warning in body(fun) : argument is not a function

> library(shiny)
> ui <- function() { fluidPage() }
> server <- function(input, output, session) {}
> shinyApp(ui, server)

Listening on http://127.0.0.1:4737
Warning in body(fun) : argument is not a function

> library(shiny)
> ui <- function(req) { fluidPage() }
> server <- function(input, output, session) {}
> shinyApp(ui, server)

Listening on http://127.0.0.1:4737
Warning in body(fun) : argument is not a function
```

The only relevant change is the R version:
```r
> devtools::session_info()
Session info -------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.211)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Lisbon               
 date     2017-04-24                  

Packages -----------------------------------------------------
 package   * version date       source        
 devtools    1.12.0  2016-06-24 CRAN (R 3.4.0)
 digest      0.6.10  2016-08-02 CRAN (R 3.4.0)
 htmltools   0.3.5   2016-03-21 CRAN (R 3.4.0)
 httpuv      1.3.3   2015-08-04 CRAN (R 3.4.0)
 jsonlite    1.1     2016-09-14 CRAN (R 3.4.0)
 memoise     1.0.0   2016-01-29 CRAN (R 3.4.0)
 mime        0.5     2016-07-07 CRAN (R 3.4.0)
 R6          2.2.0   2016-10-05 CRAN (R 3.4.0)
 Rcpp        0.12.8  2016-11-17 CRAN (R 3.4.0)
 shiny     * 1.0.2   2017-04-18 CRAN (R 3.4.0)
 withr       1.0.2   2016-06-20 CRAN (R 3.4.0)
 xtable      1.8-2   2016-02-05 CRAN (R 3.4.0)
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)
```

I was alerted to this by [this shiny-discuss post](https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/shiny-discuss/3FIgWdeZDZU) and looking up more info on the warning, we have actually had [a similar post back in January](https://groups.google.com/forum/#!topic/shiny-discuss/2kVPa8jDooI)...

**Comment by wch** [comment]
It looks like somewhere, `body(NULL)` is getting called. In R < 3.4.0, that just returned NULL, but as of 3.4.0, it issues that warning.

**Comment by kmezhoud** [comment]
Dear @wch ,
I am working on bioconductor package named [bioCancer](https://github.com/kmezhoud/bioCancer).
I am having the same issue with version R.3.4.1 (ubuntu 16.04) and not with version R.3.3.2 (OSX El Capitan) with shiny1.0.3.

```r
runApp('inst/bioCancer')
Listening on http://127.0.0.1:5020
Warning in formals(fun) : argument is not a function
Warning in body(fun) : argument is not a function
```
The running example given by @bborgesr works well without warning message in version R.3.4.1.
Actually, I can't reproduce a simple running example for these warning messages.
From theses messages could it possible to point which package? 
I have a doubt in the bad use of the new functions  like ```mutate_at```  from ```dplyr``` package. But for the two R versions I am using the same code.

Any suggestion is welcome.
thanks,
Karim

**Comment by wch** [comment]
@kmezhoud, it sounds like it is probably a problem in another package, not Shiny. If you put  `options(warn=2, shiny.error=recover)` at the top of your server function, it might help you find the source of the problem, by throwing an error when the warning happens.

**Comment by kmezhoud** [comment]
@wch  Thanks,
I got this message
```
Listening on http://127.0.0.1:4027
Error : (converted from warning) Error in formals: (converted from warning) argument is not a function
```

**Comment by EdwardAndress** [comment]
@kmezhoud - did you find a solution for this?  I have a very similar problem.  The initial warning `Warning in body(fun) : argument is not a function` is the same, but I only see it on Travis (which then hangs until timeout).

@wch I added the debugging line you suggested and got this error: `R ERROR: [on_request_read] connection reset by peer`

Any tips would be most welcome :)

**Comment by kmezhoud** [comment]
Not yet, could you have a simple running example?

**Comment by EdwardAndress** [comment]
@kmezhoud - thanks for getting back to me.  I don't have a simple example to hand but I can point you to the failing Travis build if that helps - 

https://travis-ci.org/moj-analytical-services/PQTool/builds/254820154?utm_source=github_status&utm_medium=notification

I was just hoping that you might have found a solution to your issue which might also fit ours.

All our recent builds which progress far enough yield the same warning and hang, so it is unlikely to be due to a recent change on our part.

**Comment by wch** [comment]
@EdwardAndress Adding the debugging line that I mentioned previously will only work properly in an interactive session; it won't be helpful on Travis. Also, looking at your Travis logs, it seems that you have an old version of Shiny installed, one which doesn't have the fix for the `body(fun)` issue.

**Comment by EdwardAndress** [comment]
@wch - :man_facepalming:  Thanks!  Looks like you're on to something there.  If it turns out that this issue has been brought about by our mistake, and is therefore not a valid 'issue', would you like me to delete my comments?

(Very kind of you to trawl through our Travis logs, BTW).

**Comment by wch** [comment]
@EdwardAndress No worries, and no need to delete the comments.

**Comment by EdwardAndress** [comment]
Fixed! :)
