### ISSUE TITLE
No <svg> tag?

### ISSUE THREAD

**Issue by Stophface** [rstudio/shiny#1683]
Shiny includes various (nearly all?) `html` tags. Is there a reason why the `<svg>` tag is not included?

**Comment by timelyportfolio** [comment]
I wondered the same thing.  I assume you already know that you can

```
tag("svg", list())
```

This doesn't change the fact that `tags$svg()` would be far more convenient and consistent.

**Comment by jcheng5** [comment]
I've moved this to htmltools: https://github.com/rstudio/htmltools/issues/84
