### ISSUE TITLE
Feature request: Add R version info into a shiny page so that debuggining would be easier

### ISSUE THREAD

**Issue by dmpe** [rstudio/shiny#1686]
It would be nice to have something like
```<head rversion = "Example run with R version: xxx">```
in the rendered shiny page. To me this would simplify debugging a bit...

**Comment by daattali** [comment]
This is a less direct method, but until that happens (if it ever happens?), you can add a little uiOutput that simply spits out the R version

```
ui <- fluidPage(
  ...,
  uiOutput("rversion")
)

server <- function(input, output) {
  output$rversion <- renderUI({
    R.version.string
  })
}

shinyApp(ui, server)
```

**Comment by dmpe** [comment]
Great ! thanks. Nonetheless, maybe it should be really automatically in the shiny.  :)

**Comment by wch** [comment]
What environment are you deploying to that you don't know the R version?

**Comment by dmpe** [comment]
I was dealing with shinyapps.io. Maybe it is described somewhere in the docs but i was not able to find it (on which R version it run) and had to find it out similarly to the above snippet.

Considering that we already display such information, it should not be a large challenge 👍
 
```
<script type="application/html-dependencies">json2[2014.02.04];jquery[1.12.4];shiny[1.0.3];jqueryui[1.12.1];showdown[0.3.1];highlight.js[6.2];ionrangeslider[2.1.6];strftime[0.9.2];bootstrap[3.3.7];font-awesome[4.7.0]</script>
```

**Comment by daattali** [comment]
No comment on whether or not it should be included in the header.

But FYI, on shinyappsio if you click on an application and go to the Logs tab, the R version should be in the log

**Comment by wch** [comment]
As @daattali said, the R version (and R package versions) are in the log on shinyapps.io.

The versions you're referring to are for JS libraries, and they aren't there for debugging purposes -- they're necessary for dynamic JS dependency resolution to work correctly.

**Comment by wch** [comment]
Here's a screenshot of the log panel for an app:

![image](https://cloud.githubusercontent.com/assets/86978/25588288/4d6ee19c-2e6d-11e7-811d-d3f6043a1690.png)

**Comment by dmpe** [comment]
okey, thanks
