### ISSUE TITLE
Inquiry:  Is Shiny "Production Ready" for end users?

### ISSUE THREAD

**Issue by billcgold** [rstudio/shiny#1687]
Apologize if this is not the forum for this.  

I'm considering using Shiny to deliver a matching alogithm to a team of 5 users.  The user team would:

- load ~100k rows of data, 3-5 times a week 
- run some R code behind the scene againt the loaded data
- interactively masage the data  (potentially via rhandontable)
- save results to a data.table
- the server to which this would be deployed window / 32 GB RAM and lightly used, if at all

I've search and read the Shiny issue log and observed a) there are not many crash reports and b) crash reports with reproducable code are closed quickly.  Google searches for "Shiny crash" show issues which are 18+ months old. 

**Questions**
1.  Is anyone using Shiny in a "production mode" where users interact and use a Shiny application daily?
2.  If so, is the Shiny application stable?
3.  How much data is being loaded into Shiny?

I'd prefer to not have to re-write my existing R code.

Thank you in advance  and kind regards,
Bill

**Comment by daattali** [comment]
A better platform to ask/discuss this would be [the shiny discuss group](https://groups.google.com/forum/#!forum/shiny-discuss)

To answer your question briefly: yes, shiny is used in production by many companies. It is of course not as widely used or mature as some of the more classic web app frameworks, but if you have developed code in R and want to supply it as a web interface to clients, you will be joining a long list of others who have done so already. If your data is ~100k rows and a few dozens of columns, you should be fine. I know people use larger datasets.

**Comment by billcgold** [comment]
Thanks Dean.  Search the shiny discussion group and post there if needed.
