### ISSUE TITLE
Avoid browser refresh in Shiny triggering observe() restart

### ISSUE THREAD

**Issue by iamraybao** [rstudio/shiny#1690]
Suppose I have the following Shiny app (some parts recycled from a bigger project I'm working on):

**`global.R`**

    # Clear environments
    rm(list=ls())
    rm(.polo)
    rm(.ohlc)
    
    # First, load all your libraries:
    library(shiny)
    library(httr)
    library(plyr)
    library(xts)
    
    # Rebuild empty environments if RStudio's "Clear All" has been used:
    if (!exists('.polo')) .polo <- new.env()
    if (!exists('.ohlc')) .ohlc <- new.env()
    
    # Get OHLCV data; see: https://poloniex.com/support/api/
    refreshPoloniex <- function(.symbol1 = 'BTC', .symbol2 = 'ETH', .period = 7200, .start = 1483228800, .end = 9999999999) {
      .pair <- paste(.symbol2,.symbol1,sep="")
      if (!exists(.pair, envir = .polo)) {
        .url <- paste("https://poloniex.com/public?command=returnChartData&currencyPair=", .symbol1, "_", .symbol2, "&start=", .start,"&end=", .end, "&period=", .period, sep = "")
        .ohlcv <- ldply(content(GET(.url)), data.frame)  # Get OHLCV data via 'returnChartData' API call
        assign(x = .pair, value = .ohlcv, envir = .ohlc)
        .ohlcv$date <- as.POSIXct(.ohlcv$date, origin = "1970-01-01")  # is.OHLCV(.ohlcv)
        .ts <- xts(.ohlcv[, 2:8], order.by = .ohlcv$date)  # Create 'xts' object
        assign(x = .pair, value = .ts[,c("open", "high", "low", "close", "volume")], envir = .polo)  # Assign environment variable
        cat(paste(.symbol2, "/", .symbol1, " Poloniex OHLCV data downloaded at ",Sys.time(),"\n", sep = ""))
      } else {
        .url <- paste("https://poloniex.com/public?command=returnChartData&currencyPair=", .symbol1, "_", .symbol2, "&start=", last(get(.pair, envir = .ohlc)$date), "&end=", .end, "&period=", .period, sep = "")
        .diff <- ldply(content(GET(.url)), data.frame)
        .diff$date <- as.POSIXct(.diff$date, origin = "1970-01-01")
        .ohlcv <- rbind(subset(get(.pair, .ohlc), date < min(.diff$date)), .diff)
        assign(x = paste(.symbol2, .symbol1, sep = ""), value = .ohlcv, envir = .ohlc)
        .ohlcv$date <- as.POSIXct(.ohlcv$date, origin = "1970-01-01")
        .ts <- xts(.ohlcv[, 2:8], order.by = .ohlcv$date)
        assign(x = .pair, value = .ts[,c("open", "high", "low", "close", "volume")], envir = .polo)
        cat(paste(.symbol2, "/", .symbol1, " Poloniex OHLCV data updated at ",Sys.time(),"\n", sep = ""))
      }
    }

**`ui.R`**:

    shinyUI(navbarPage(title = "TestApp",
                       tabPanel("Home",
                                withTags({
                                  div(class="container", checked=NA,
                                      div(class="jumbotron", checked=NA, 
                                          h4("Testing123"),
                                          tableOutput("downloadTable")))
                                }),
                                icon = NULL),
                       footer = NULL
    ))

**`server.R`**:

    shinyServer(function(input, output, session) {
      
      # ## Set up observers
      updatePrices <- observe({
        invalidateLater(15*1000, session = session)  # Update every 15 seconds
        refreshPoloniex()
      }, priority = 1)
      
      ## Reactively get the table data (to pass into the render function) every x seconds
      tableData <-reactivePoll(30*1000, session = session,
                               checkFunc = function() {Sys.time()},
                               valueFunc = function() {
                                 .df <- tail(.ohlc$ETHBTC, 5)[,c('date','high','low','open','close','volume')]
                                 return(.df)
                               })
      
      output$downloadTable <- renderTable({
        tableData()
      }, width = '100%')
      
    })

Here's the problem:

The loads and seems to run. I call my `refreshPoloniex()` function inside the `observe` in my server definition which gets the underlying data on some interval (here, I set it to 15 seconds). Because I added the `cat` output in the definition, I can confirm in the console within RStudio that it is indeed running correctly every 15s.

When I open the app inside my web browser (RStudio > Run App > Open in Browser), I notice that doing so re-runs the `refreshPoloniex()` function within my `observe` as if the app was just launched. **This also happens when I do a page refresh (F5)** -- and is confirmed by the `Sys.time()` in my function's `cat` console output. In other words, every time I hit F5, it executes the function irrespective of the observer.

Obviously this is not desirable for my app (the function should run server-side every 15s regardless of what the user does). How can I fix this?

**Comment by wch** [comment]
When you reload the app, it starts a new session and re-runs the server function. If you want it to persist across sessions, you can create the observer outside of the server function. You could put it in your global.R. Note that if you do that, it will also be shared across sessions, if there are multiple users connected to the same R process.

See the scoping article: http://shiny.rstudio.com/articles/scoping.html

If you have more questions, the shiny-discuss list is the appropriate place for them.
