### ISSUE TITLE
Vague error message on shinyapps.io

### ISSUE THREAD

**Issue by VMJim** [rstudio/shiny#1691]
A Shiny app I'm working on works fine locally, but when deployed to shinyapps.io/myapp it disconnects and on a refresh throws this error:

**An error has occurred**
 
**Worker asked to create wait channel was in stopped state.**

There is no entry in the server log.  

To put this as a question: what does this mean? 
To put it as a request:  can the error message be made a little bit more descriptive and can a few lines be written in the log. 

also see: https://groups.google.com/forum/#!topic/shinyapps-users/AMROjcib8DA

**Comment by wch** [comment]
I know this is very similar to the message you linked to on shiny-discuss, but can you ask your question there? That's where this question belongs, since it's related to shinyapps.io. I've asked our support people to be on the look out for your message.
