### ISSUE TITLE
reactlog remains empty

### ISSUE THREAD

**Issue by mschilli87** [rstudio/shiny#1694]
While troubleshooting #1692, I tried to see the dependency graph (as I suspect a missing link between the `reactive` and the `output` element).

I ran

```R
setwd(appdir)
options(shiny.reactlog=TRUE)
shiny::runApp()
```

in Rstudio.
Then I clicked 'Open in Browser' and pressed Ctrl+F3.

I can see the app in a browser tab and the react log in another.

However, the log only shows a slim gray top bar that increases size two- to three-fold upon mouseover,
a message

> Press right-arrow to advance

in the top-middle, and a small legend

> * Normal
> * Invalidated
> * Running

(white, grey and green squares) in the bottom right.

---

Obviously I tried hitting right, repeatedly and/or holding it without any effect.
I also tried to use the app a bit and refreshing both tabs.
I also tried not clicking 'Open in Browser' having my app running in Rstudio and the reactlog in the  browser.

---

The only remotely related information I could find is http://stackoverflow.com/q/39131833/2451238 which tells me that I am not the first to encounter this issue.

**Comment by fabiangehring** [comment]
+1

**Comment by fabiangehring** [comment]
It seems as if in our case the reason the reactive log does not show up is, that we do not have internet access on our machines. In the header of the reactive log jquery and d3 is loaded from the web.

Isn't it possible to make the needed libraries available offline?
```
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
```

**Comment by jcheng5** [comment]
We have a new reactlog implementation coming that will work offline.

**Comment by nteetor** [comment]
Occasionally the reactlog fails similarly for me, each time I get this message at the browser console,

![image](https://user-images.githubusercontent.com/3228369/46501045-5d87e400-c7f2-11e8-940b-48fe540883ca.png)

**Comment by jcheng5** [comment]
@nteetor If you install from `"rstudio/shiny@v1.2-rc"` does the problem go away?

**Comment by jcheng5** [comment]
Same question for you @mschilli87 ^

cc @schloerke

**Comment by nteetor** [comment]
I don't see the error anymore. Because the problem wasn't consistent, I'll post another update if this does come up again.

**Comment by mschilli87** [comment]
@jcheng5 
> If you install from "rstudio/shiny@v1.2-rc" does the problem go away?

First I followed the steps in my first comment of this issue to ensure I can still reproduce it.
This confirmed I was still affected by this.
Then I installed `v1.2-rc`, restarted Rstudion and repeated the steps.
This time, I got a working reactlog!

So AFAICT this issue seems to be resolved in `v1.2-rc`. :tada:

**Comment by schloerke** [comment]
Closing as everyone appears to be in a good position

**Comment by kambanane** [comment]
I get the same issue in shiny 1.3.2.

**Comment by schloerke** [comment]
@kambanane Please open a new issue as `reactlog` within `shiny` has been overhauled.  If possible, please include a screenshot of the browser webpage and if there are any console errors in the new issue. [Chrome DevTools Console](https://developers.google.com/web/tools/chrome-devtools/) . 

Thank you!
