### ISSUE TITLE
Shiny App - rsession aborted

### ISSUE THREAD

**Issue by nomealeatorio999** [rstudio/shiny#1695]
Hi Guys,

I have an issue with the default shiny app generated by shiny package: R Session Aborted.

Can anyone help me ?

***************
sessioninfo()
***************
>>> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0   

![rsession_abort](https://cloud.githubusercontent.com/assets/23126792/25754996/42549e44-318f-11e7-9c8c-9e76b00f8369.png)
***************
ui.R
***************
library(shiny)

# Define UI for application that draws a histogram
shinyUI(fluidPage(
  
  # Application title
  titlePanel("Old Faithful Geyser Data"),
  
  # Sidebar with a slider input for number of bins 
  sidebarLayout(
    sidebarPanel(
       sliderInput("bins",
                   "Number of bins:",
                   min = 1,
                   max = 50,
                   value = 30)
    ),
    
    # Show a plot of the generated distribution
    mainPanel(
       plotOutput("distPlot")
    )
  )
))

***************
server.R
***************
library(shiny)

# Define server logic required to draw a histogram
shiny::shinyServer(function(input, output, session) {

  output$distPlot <- renderPlot({

     # generate bins based on input$bins from ui.R
     x    <- faithful[, 2]
     bins <- seq(min(x), max(x), length.out = input$bins + 1)
    
     # draw the histogram with the specified number of bins
     hist(x, breaks = bins, col = 'darkgray', border = 'white')

  })
  
})

**Comment by wch** [comment]
Can you install the devtools package, run `devtools::session_info()`, then paste the output here?


```R
# Install devtools if needed
if (system.file(package='devtools') == "")
  install.packages('devtools')

devtools::session_info()
```

**Comment by nomealeatorio999** [comment]
>>> devtools::session_info()
Session info ------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, mingw32             
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2017-05-05                  

Packages ----------------------------------------------------------------------------------
 package  * version date       source        
 devtools   1.12.0  2016-06-24 CRAN (R 3.3.2)
 digest     0.6.12  2017-01-27 CRAN (R 3.3.2)
 memoise    1.1.0   2017-04-21 CRAN (R 3.4.0)
 withr      1.0.2   2016-06-20 CRAN (R 3.3.2)

**Comment by bborgesr** [comment]
You need to do `devtools::session_info()` *AFTER* you run the app, not before.

**Comment by bborgesr** [comment]
One thing that jumps out right away though is that you are using R 3.4.0 but most of your packages were build for R 3.3.2. I bet that re-installing all your old packages (including shiny and Cairo) will solve your problems:

```r
install.packages("devtools")
install.packages("devtools")
```

**Comment by nomealeatorio999** [comment]
Calling devtools::session_info() AFTER is **just what I did**. You have to remember my session is being **aborted**, therefore I end up in the default R session.

**Comment by wch** [comment]
You can get a list of all packages that were installed with an older version of R by running the following:

```R
pkgs <- as.data.frame(installed.packages(), stringsAsFactors = FALSE, row.names = FALSE)
pkgs$Built <- as.package_version(pkgs$Built)

# Drop base and recommended packages from list
pkgs <- pkgs[is.na(pkgs$Priority), ]
pkgs <- pkgs[pkgs$Built < getRversion(), ]
pkgs <- pkgs[, c("Package", "Version", "Built")]
pkgs
```

If you reinstall those packages, there's a good chance it will fix the problem.

**Comment by nomealeatorio999** [comment]
I did the following:
update.packages(ask = FALSE, checkBuilt = TRUE)

The problem is solved.

Thanks

**Comment by nomealeatorio999** [comment]
I am closing this issue.
