### ISSUE TITLE
Shiny document closes itself in approximately a minute

### ISSUE THREAD

**Issue by bryan-kc** [rstudio/shiny#1697]
Hi,

I'm experiencing a bug with our hosted RStudio setup. When following the steps below, the document will open up in the viewer pane (or window) for ~40 seconds and then unexpectedly close. In the case of the viewer pane the panel will turn to a blank page - I believe it to be rendering about:blank. 

Steps to reproduce:
1. Goto RStudio
2. Select File > New File > RMarkdown
3. In the popup window, select Shiny and Shiny Document 
4. Run Document.  _I ran in viewer pane to see network logs but popout window also experiences this bug_

http://imgur.com/a/vmIZh

Here is the full network log. I have noticed that the moment the websocket connection terminates is the exact moment that the panel closes.

**Comment by andrewsali** [comment]
I think we had a similar issue when running Rstudio Server behind a reverse proxy. The proxy had a timeout that disconnected the websocket connection. Not sure if this is causing your problem, but might be worthwhile to check.

**Comment by bryan-kc** [comment]
Thanks Andrew, I will look into it.

I suspected it was nginx causing problems but our reverse proxy config was similar in nature to the recommended config (https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy). Here's our nginx reverse proxy config.

```
events {
  worker_connections 1024;
}

http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
  }

  server {
    listen 8080;

    client_max_body_size 0;

    location / {
      proxy_pass http://rstudio:8787;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_read_timeout 20d;
    }
  }
}
```
