### ISSUE TITLE
reactiveVal in session$userData loses reactive status when passed around

### ISSUE THREAD

**Issue by fabiangehring** [rstudio/shiny#1704]
When setting a reativeVal in sessionUser data (using the parent-workaraound in #1546), the reactive value seems to loose its reactivity when passed around (here: to a module's server function)

**Comment by jcheng5** [comment]
I don't understand--can you provide some example code? (Even if it's not a full reproducible example, I want to see what you mean by "setting")

**Comment by fabiangehring** [comment]
When trying to reproduce everything worked now. Probably I made a silly mistake somewhere in my first attempt. Thanks anyways -> closed
