### ISSUE TITLE
Creat shiny app to get query using api and output json string

### ISSUE THREAD

**Issue by samistat08** [rstudio/shiny#1708]
I need to create a microservice using R shiny which receives query string and reply in json format. This code gives me a page but it has 2 problems which I am trying to solve : 1.I am not able to query from it by URL, need to enter PC values in the ui bar. 2. I need only the json output without any ui output , e.g. when I try to get this json string on postman [https://www.getpostman.com/](url), I get an html string. 

```
>library(jsonlite)
> shinyApp(
> ui = fluidPage(
>   textInput("txt", "Enter PC"),
>    textOutput("query")
> ),
> server = function(input, output, session) {
>   load("14-01-2017.Rdata")
>     observeEvent(input$go, {
>     updateQueryString(url, mode = "push" )
>   })
>   output$query <- renderText({
>     query<-parseQueryString(session$clientData$url_search)
>     subs<-subset(MV,MV$PC==input$txt)
>    query<- average.speed<-mean(subs$SU)
>     })
> }
> )
```

Further info: file that I load include a matrix named MV with variables PC and SU. I want to get mean of SU for the variables when PC= requested in query 

Would be extremely thankful for any help.

**Comment by wch** [comment]
It sounds like one of these might be more appropriate for your use case:
* https://www.opencpu.org/
* https://github.com/trestletech/plumber

**Comment by samistat08** [comment]
I used plumber and it works well. Thanks a lot.
