### ISSUE TITLE
Not able to display all my tables on Shiny server

### ISSUE THREAD

**Issue by NJeanray** [rstudio/shiny#1714]
Hello everyone,

I developped locally an application displaying 2 dataframes and a DT thanks to renderDataTable, renderTable and renderUI. Locally, it works very fine, but it does not work anymore when I deploy my app on Shiny server. 

Weirdly, I am able to display only my DT whereas nothing happends regarding my two other dataframes. I do not receive any error message, and there is no information indicating an issue in the logs.

I tried to track my network, and this is the only difference I can see when it works, and when it doesn't : 

XHR finished loading: POST "http://*****.local:*****/MyApp/session/e4c182410a46f3525393cb7f60998e55/dataobj/out348960e8f6221aa0?w=&nonce=26965598b90216d1". jquery.min.js:4

And otherwise, when I play with my tabs where my tables normally should be displayed  : 

 [DBG]: 3 message(s) discarded from buffer   shiny-server-client.min.js:1

What does this previous message mean ? 

Also, all my tables come from the same data source, retrieved thanks to a SQL request. I guess there is no issue at this level because the only displayed table contains the correct data. So I guess the issue comes from my reactive functions, but as I do not have any error message and since it works locally, I'm a bit confused...

Could someone help me ?

Many thanks in advance,

Best regards,
Nath

ps : other apps are running on the server without any issue and it has been recently restarted.

**Comment by wch** [comment]
Can you provide a minimal reproducible example?
