### ISSUE TITLE
Warning: Error in : XML content does not seem to be XML on Shiny Server

### ISSUE THREAD

**Issue by NJeanray** [rstudio/shiny#1715]
Hello everyone,

I'm using a fileInput to upload some XML files but when I try to parse it/them thanks to XML package (function xmlParse), I get this error : 

Warning: Error in : XML content does not seem to be XML: 'myFile.xml'

When I run my App locally, I do not have any issue (the XML files are in the same directory than my R scripts, does it make a difference ?).

What can cause this problem when I run the same App on Shiny server ?

Many thanks in advance,

Best regards,
Nathalie

**Comment by NJeanray** [comment]
To be more specific, I printed the following in my log : 
File name : myFile.xml
File path : /tmp/Rtmpay3vjG/91ccdb2eff649c7475e35186/0
File type : text/xml
 
So my file is well recognized as an XML. 

Besides, I put my file into my Shiny working directory manually - pointing on the directory where are located server.r and ui.r) and I restarted my App, chosing the SAME file to be uploaded thanks to fileInput. And then, it worked... Is it a normal behaviour ? Do I have to copy and rename all the uploaded file from tempdir() to getwd() ?

**Comment by wch** [comment]
Can you provide a minimal reproducible example?

**Comment by Kbushu** [comment]
You've probably got it sorted by now. But just in case...

fileInput creates a dataframe of your selection of files, the columns of this dataframe contains a column called __datapath__, reference the data in the xml functions using something like this: __yourdataframe$datapath__
