### ISSUE TITLE
renderTable shall split long rows into subrows fitting the page width

### ISSUE THREAD

**Issue by gurol** [rstudio/shiny#1722]
I have a long table to render in shiny application by r`enderTable(xtable(df))`. Is it possible to split the rows into subrows so that the table width do not cross the horizantal page width limit.

Thank you.

**Comment by mine-cetinkaya-rundel** [comment]
One option is to use instead the `DT::renderDataTable` / `DT::dataTableOutput` function pairs, in the `server` and `ui`, respectively. In the `options` argument of the `renderDataTable` function you can set `scrollX = TRUE`. This will make it easier to scroll horizontally in just the table output to view columns to the right.

**Comment by alandipert** [comment]
Since a workaround was provided and this isn't an inherent problem with Shiny, I'm closing. Please don't hesitate to comment further or create a new issue if this remains a problem for you.
