### ISSUE TITLE
running shinyApps synchronously when multiple inline

### ISSUE THREAD

**Issue by timelyportfolio** [rstudio/shiny#1723]
I apologize if this has already been covered, but I exhausted all the search terms I could on Shiny issues and StackOverflow and found nothing.  I am guessing this is something simple, but let's say we have more than one `shinyApp` inline, and we want each to run all with a single `CTRL+Enter`.  **Please note I am not trying to run the two Shiny apps simultaneously.  I would like to run them synchronously.**

```
app <- shinyApp(
    ui = fluidPage(
        numericInput("n", "n", 1),
        plotOutput("plot")
    ),
    server = function(input, output) {
        output$plot <- renderPlot( plot(head(cars, input$n)) )
    }
)

runApp(app)
runApp(app)
```

`runApp` only runs once.  While this may seem dumb, if we think about Shiny gadgets, then we might want the return value from one gadget to then feed a second `gadget1() %>% gadget2()`.  For my specific use case, see https://github.com/r-spatial/mapedit/issues/24.

Is this possible, or is there a workaround?

Thanks so much!

**Comment by wch** [comment]
I believe that if you press the close button on the app window, it essentially interrupts the R process, like pressing Esc in RStudio, and it won't run any code after the first `runApp()`. But if you have a button that causes `stopApp()` to be called, it will keep going. For example:

```R
app <- shinyApp(
    ui = fluidPage(
      actionButton("quit", "Quit")
    ),
    server = function(input, output, session) {
      observeEvent(input$quit, stopApp(100))
    }
)

runApp(app)
runApp(app)
```

**Comment by jcheng5** [comment]
@wch, that sounds right to me, and the correct course anyway if you want to return a value. If you absolutely must catch the close button on the app window you may be able to `tryCatch(runApp(...), interrupt = function(cond) { ... })`.

**Comment by timelyportfolio** [comment]
@wch, @jcheng5 great ideas, and I have done enough gadgets by now that I should have thought of this myself.  This gets me closer to solving the riddle of https://github.com/r-spatial/mapedit/issues/24, but I fear that I have a long way to go to a solution.  Thanks!!

**Comment by timelyportfolio** [comment]
As a status update, my issue seems to be caused by `dialogViewer` in `runGadget`.  If I switch to `paneViewer` I can no longer replicate the problem.   It seems `dialogViewer` kills the current process, while `paneViewer` and `browserViewer` do not.  For anyone that might run into this in the future, here is a very minimal reproducible example of the difference in behavior.

```
library(shiny)
library(miniUI)

testApp <- function(viewer=paneViewer()){
  ui = miniPage(
    gadgetTitleBar(
      "title",
      left = miniTitleBarCancelButton(),
      right = miniTitleBarButton("done", "Done", primary = TRUE)
    )
  )
  server = function(input, output, session) {
    observeEvent(input$done, stopApp(TRUE))
    observeEvent(input$cancel, stopApp(NULL))
  }
  app <- shinyApp(ui, server)
  runGadget(app, viewer=viewer, stopOnCancel=FALSE)
}

lapply(1:3, function(x) testApp(paneViewer()))
lapply(1:3, function(x) testApp(browserViewer()))
lapply(1:3, function(x) testApp(dialogViewer("test")))
```
