### ISSUE TITLE
Failed to load resource: Unable to init SSL Context: in windows OS rstudio internal viewer

### ISSUE THREAD

**Issue by yonicd** [rstudio/shiny#1730]
i am able to GET `XMLHttpRequest()` on mac/unix but not in windows rstudio internal viewer.

i am getting this error back in js console:
`Failed to load resource: Unable to init SSL Context:  https://raw.githubusercontent.com/yonicd/jsTree/master/README.md?raw=true`

similar to older [issue](https://github.com/rstudio/shiny/issues/1148)

```
library(htmltools)
browsable(
  tagList(
    tags$pre(id="myPreview"),
    tags$script(
      '
      
      var uri="https://raw.githubusercontent.com/yonicd/jsTree/master/README.md?raw=true";
      loadXMLDoc(uri);
      
      function loadXMLDoc(uri) {
      var xmlhttp = new XMLHttpRequest();
      xmlhttp.onreadystatechange = function() {
      if (this.readyState == 4) {
if(this.status == 200) document.getElementById("myPreview").innerHTML = 
this.responseText;
      }
      };
      xmlhttp.open("GET", uri, true);
      xmlhttp.send();
      }
      
      '
    ),
    rmarkdown::html_dependency_jquery()
  )
)
```

**Comment by bborgesr** [comment]
This is an IDE issue that is currently being handled by the RStudio support team. I'll close it here, since it is not Shiny-related.
