### ISSUE TITLE
make selectInput's label inline

### ISSUE THREAD

**Issue by feng5** [rstudio/shiny#1737]
please make selectInput's label inline but not separate the label and input element into two rows

**Comment by bborgesr** [comment]
There's ways of doing this with CSS. We're unlikely to change the implementation in Shiny.

For example, here's one way, adapted from [this SO answer](https://stackoverflow.com/a/33960430/6174455):

```r
library(shiny)

ui <- fluidPage(
  tags$head(
    tags$style(type="text/css", 
      "label.control-label, .selectize-control.single { 
         display: table-cell; 
         text-align: center; 
         vertical-align: middle; 
      } 
      label.control-label {
        padding-right: 10px;
      }
      .form-group { 
        display: table-row;
      }
      .selectize-control.single div.item {
        padding-right: 15px;
      }")
  ),
  selectInput("variable", "Variable", c("Cylinders", "Transmission", "Gears"))
)

server <- function(input, output, server) {}
shinyApp(ui, server)
```

You'll probably want to tweak it, depending on you app's particular needs.

**Comment by sanjmeh** [comment]
Doesn't work for numericInput().
Is there an idiot's CSS guide for shiny users where we can go to?

**Comment by GregorDeCillia** [comment]
I just ran into the same issue. The [`shinyWidgets`](https://github.com/dreamRs/shinyWidgets) package provides an input widget `pickerInput()`, which supports inline-labels via the parameter `width = "fit"`.

```r
library(magrittr)
shinyWidgets::pickerInput("id", "label", c("some", "choices), width = "fit") %>%
  shiny::fluidPage() %>% shiny::shinyApp(function(...) {})
```
