### ISSUE TITLE
update placeholder via updateTextInput

### ISSUE THREAD

**Issue by bklingen** [rstudio/shiny#1738]
I think it would be very useful to allow easy updating of the placeholder parameter, too, via ``updateTextInput`` or ``updateTextAreaInput``. Currently, these two update functions only allow updating label and value.

**Comment by carlganz** [comment]
This is easy to implement. Would only require a small amount of code here: https://github.com/rstudio/shiny/blob/master/srcjs/input_binding_text.js#L32

Happy to make pull request if shiny team is interested.

**Comment by wch** [comment]
@carlganz I think it's a good idea - we'd definitely consider it.
