### ISSUE TITLE
Selectize Shiny Server 30000 elements 

### ISSUE THREAD

**Issue by aleferna** [rstudio/shiny#1740]
I have a servers side gene list with 30k elements, it works perfectly except for the fact that when you type the name of a gene too fast it doesn't give time for the server to respond and therefore since it doesn't find the gene then it disapears. How can I make it so that if the selectize doesn't find the gene on the list it keeps the gene name? Also I would like to search for all gene begining with some letters and not whenever the letters are present in the gene ?

**Comment by aleferna** [comment]
Here's the app: 

https://nordicbio.shinyapps.io/BoxPlot/

**Comment by iainmwallace** [comment]
To add novel entries, I believe you can use the create=True option
options = list(create = TRUE)
https://shiny.rstudio.com/articles/selectize.html

In general, it is probably faster to get help by posting on StackOverflow
https://stackoverflow.com/questions/tagged/shiny

**Comment by jcheng5** [comment]
Can you give an example of one where typing too quickly causes it to disappear?

**Comment by alandipert** [comment]
Closing because we requested additional information and didn't receive it, but if this remains a problem for you please don't hesitate to comment further or create a new issue.
