### ISSUE TITLE
Select algorithm from selectinput with shiny

### ISSUE THREAD

**Issue by makis23** [rstudio/shiny#1746]
Hi i need to run an algorithm on the server side based on my selectinput choise on the ui side. i use if. any suugestions?

#ui.R
library(shiny)
library(caret)
library(caTools)
library(klaR)
library(MASS)

navbarPage("Model Developement",
           tabPanel("Data Import",
                    sidebarLayout(sidebarPanel( fileInput("file","Upload your CSV",multiple = FALSE),
                                                tags$hr(),
                                                h5(helpText("Select the read.table parameters below")),
                                                checkboxInput(inputId = 'header', label = 'Header', value = FALSE),
                                                checkboxInput(inputId = "stringAsFactors", "stringAsFactors", FALSE),
                                                radioButtons(inputId = 'sep', label = 'Separator', 
                                                             choices = c(Comma=',',Semicolon=';',Tab='\t', Space=''), selected = ',')
                    ),
                    mainPanel(uiOutput("tb1"))
                    ) ),
           tabPanel("Model_dev",
                    sidebarLayout(sidebarPanel(
                      uiOutput("modelselect")
                    ),
                    mainPanel(
                               verbatimTextOutput("other_val_show")
                               #verbatimTextOutput("other_val_show2"),
                               #verbatimTextOutput("other_val_show3")
                    )))
           )
#Server.r
library(shiny)
library(caret)
library(caTools)
library(klaR)
library(MASS)
library(lattice)
library(rvest)
library(dplyr)
library(e1071)
library(rpart)
library(rpart.plot)
library(rminer)
library(corrplot)
library(DT)
library(tidyr)
library(ggplot2)
library(ggvis)

function(input,output) { data <- reactive({
  file1 <- input$file
  if(is.null(file1)){return()} 
  read.table(file=file1$datapath, sep=input$sep, header = input$header, stringsAsFactors = input$stringAsFactors)
  
})

output$table <- renderTable({
  if(is.null(data())){return ()}
  data()
})
output$tb1 <- renderUI({
  tableOutput("table")
})

output$model_select<-renderUI({
  selectInput("modelselect","Select Algo",choices = c("Logistic_reg"="Log","Naives_Bayes"="n","Decision Tree"= "dec"),selected = "Log")
})

output$other_val_show<-renderPrint({
  f<-data()
  hr_model <- f %>% filter(last_evaluation >= 0.70 | time_spend_company >= 4 | number_project > 5)
  hr_model$left <- as.factor(hr_model$left)
  train_control<- trainControl(method="cv", number=5, repeats=3)
  
  if(input$modelselect== "Log")
  {
  gmlmodel <- train(left~., data=hr_model, trControl=train_control, method="LogitBoost")
  # make predictions
  predictions<- predict(gmlmodel,hr_model)
  gmlmodelbinded <- cbind(hr_model,predictions)
  # summarize results
  confusionMatrix<- confusionMatrix(gmlmodelbinded$predictions,gmlmodelbinded$left)
  confusionMatrix }
  
  else if(input$modelselect== "n"){
  
  e1071model2 <- train(left~., data=hr_model, trControl=train_control, method="nb")
  predictions<- predict(e1071model2,hr_model)
  e1071modelbinded <- cbind(hr_model,predictions)
  # summarize results
  confusionMatrix<- confusionMatrix(e1071modelbinded$predictions,e1071modelbinded$left)
  confusionMatrix }
  
  else{
  
  rpartmodel<- train(left~., data=hr_model, trControl=train_control, method="rpart")
  # make predictions
  predictions<- predict(rpartmodel,hr_model)
  hr_model_tree<- cbind(hr_model,predictions)
  # summarize results
  confusionMatrix<- confusionMatrix(hr_model_tree$predictions,hr_model_tree$left)
  confusionMatrix}
})
  
  #output$other_val_show2<-renderPrint({
   # f<-data()
    #hr_model <- f %>% filter(last_evaluation >= 0.70 | time_spend_company >= 4 | number_project > 5)
    #hr_model$left <- as.factor(hr_model$left)
    #train_control<- trainControl(method="cv", number=5, repeats=3)
    #e1071model2 <- train(left~., data=hr_model, trControl=train_control, method="nb")
    #predictions<- predict(e1071model2,hr_model)
    #e1071modelbinded <- cbind(hr_model,predictions)
    # summarize results
    #confusionMatrix<- confusionMatrix(e1071modelbinded$predictions,e1071modelbinded$left)
    #confusionMatrix
  #})
  
  #output$other_val_show3<-renderPrint({
   # f<-data()
    #hr_model <- f %>% filter(last_evaluation >= 0.70 | time_spend_company >= 4 | number_project > 5)
    #hr_model$left <- as.factor(hr_model$left)
    #train_control<- trainControl(method="cv", number=5, repeats=3)
    # train the model 
    #rpartmodel<- train(left~., data=hr_model, trControl=train_control, method="rpart")
    # make predictions
    #predictions<- predict(rpartmodel,hr_model)
    #hr_model_tree<- cbind(hr_model,predictions)
    # summarize results
    #confusionMatrix<- confusionMatrix(hr_model_tree$predictions,hr_model_tree$left)
    #confusionMatrix
  #})
  
  

}

**Comment by wch** [comment]
Hi, this issue tracker is for bug reports and feature requests for Shiny. For general help questions, it's better to use the shiny-discuss mailing list, or StackOverflow. It's also helpful for people who are trying to answer your question if you have a minimal reproducible example.
