### ISSUE TITLE
Error in Output$ModuleVariance <- renderPlot({ :    object 'Output' not found

### ISSUE THREAD

**Issue by rajdeepn** [rstudio/shiny#1759]
Hi 

So If I use this code I get the  bar chart output 

library(shiny)
library(shinyBS)
library(dplyr)
library(ggplot2)

setwd("folderlink")
getwd()

InputCSV <- read.csv("File.csv", header = TRUE)
ModuleOut <- as.data.frame(InputCSV %>% group_by(PSE_MODULE) %>% summarise(V=var(Act))%>%top_n(30,V)%>%arrange(desc(V)))

# UI for application that draws a histogram
ui <- fluidPage(
   
  titlePanel("FM Variance Analysis"),
      mainPanel(
         plotOutput("distPlot")
      )
   )
# server logic required to draw a histogram
server <- function(input, output) {
   
   output$distPlot <-renderPlot({
     Mod_Top30<-ModuleOut
     getOption("scipen")
     options("scipen" = 20)
     ggplot(Mod_Top30,aes(x= reorder(PSE_MODULE,-V),y = V))+ geom_bar(stat="identity")
   })
}

# Run the application 
shinyApp(ui = ui, server = server)

However, now when I integrate the same with another code mentioned below it gives me the error
Error in Output$ModuleVariance <- renderPlot({ : 
  object 'Output' not found

library(shiny)
library(shinyBS)
library(dplyr)
library(ggplot2)

setwd("Folder")
getwd()

InputCSV <- read.csv("File.csv", header = TRUE)
ModuleOut <- as.data.frame(InputCSV %>% group_by(MODULE) %>% summarise(V=var(Act))%>%top_n(30,V)%>%arrange(desc(V)))

ui <- fluidPage(
  
  titlePanel("FM Variance Analysis"),
  sidebarLayout(
    
    sidebarPanel(
      
      uiOutput("PartKeywordOutput"), 
      actionButton("go", "Get Output")
      
    ), 
    
    mainPanel(
      plotOutput("ModuleVariance"),
      bsModal("ScatterPlot", "PartKeyword Vs. Date", "go", size = "large",plotOutput("contents"),downloadButton('downloadPlot', 'Download'))
    )
    
    
  )
)

server <- function(input, output){
  
  InputCSV <- read.csv("FM_Variance.csv", header = TRUE)
  output$PartKeywordOutput<-renderUI({
    selectInput("PartKeyInput", "Please Select the PartKeyword of your choice",
                choices = sort(unique(InputCSV$PartKeyword)),
                selected = NULL, multiple = FALSE,
                selectize = TRUE, width = NULL, size = NULL) 
  })
  
  Filtered <- reactive({
    if (is.null(input$PartKeyInput)) {
      return(NULL)}
    
    select(filter(InputCSV,PartKeyword == input$PartKeyInput),Shipment.Date,Act)
    
    
  })
  
  
  Output$ModuleVariance <-renderPlot({
    Mod_Top30<-ModuleOut
    getOption("scipen")
    options("scipen" = 20)
    ggplot(Mod_Top30,aes(x= reorder(PSE_MODULE,-V),y = V),environment = environment())+ geom_bar(stat="identity")
  })
  
  output$contents<-renderPlot({
    if (is.null(Filtered())) {
      return()
    }
    ggplot(Filtered(),aes(Shipment.Date,Act),environment = environment())+ geom_point(colour = "darkblue", size = 3)
  })
  
  output$downloadPlot <- downloadHandler(
    filename = "Shinyplot.png",
    content = function(file) {
      png(file)
      plotInput()
      dev.off()
    }) 

}
  
  
  shinyApp(ui = ui, server = server) 

Do you know why is this happeing?

**Comment by wch** [comment]
It looks like you need to use `output` instead of `Output`.

**Comment by rajdeepn** [comment]
feeling so darn silly... Thanks
