### ISSUE TITLE
Provide accessor function for input

### ISSUE THREAD

**Issue by fbreitwieser** [rstudio/shiny#1769]
A common source of unintended behavior in R is that no error is thrown when trying to access a non-existent element in a `list` - just `NULL` is returned. Same with shiny's `input`. When I change the ID of an input in the UI, but forget to reflect it in the server code (or just have a typo), no error is thrown. In a big project it can take a long time to find such typos. 

I wrote the following getter function as workaround:
```{r}
  get_input <- function(x) {
    ni <- isolate(names(input))
    validate(need(x %in% ni, message = sprintf("Error: Expect %s in input! Available: %s", x, paste0(sort(ni), collapse = ", "))))
    input[[x]]
  }
```

Do you think it would be useful to others? Do you see any problems, for example with reactivity, with this function?

**Comment by wch** [comment]
One issue with erroring when dynamic UI contains an input -- initially that input value will not exist and `get_input` will error. So in general, it wouldn't be safe for app authors to use this function.

But it does sound like it's useful for your case. I think it's a good solution for that, but not for general use.
