### ISSUE TITLE
runApp doesn't repect shinyApp(onStart = function()) argument

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#1772]
If you run this from the console, it prints `start!` when the app starts:

```R
shinyApp(
  fluidPage(),
  function(input, output) {},
  onStart = function() cat("start!\n")
)
```

However, if you save it in an `app.R` and then call `runApp()` on it, the `onStart` function doesn't run.

**Comment by warnes** [comment]
Oops, found and error in my code responsible for the problem.
