### ISSUE TITLE
ERROR: there is no package called ‘googlesheets’

### ISSUE THREAD

**Issue by yichunsung** [rstudio/shiny#1774]
Hi, today I create a new application and it run  successfully at localhost, BUT when I push my application to shinyapps website, I saw the ERROR message.

**ERROR: there is no package called ‘googlesheets’**

However, we can use install.packsges() to install this package from CRAN, so I don't know which part I got wrong?

It's my server.R :

`library(shiny)
library(googlesheets)
library(plotly)

GTPurl <- "https://docs.google.com/spreadsheets/d/11VFUdSCfZahqIuaO5eAvtCyyIjpnnYkG4w7KliiY_fc/edit?usp=sharing"
GTPtest <- gs_url(GTPurl)
GTPtestdf <- gs_read(ss=GTPtest, ws = "工作表1", skip=0)
GTPtestdf$date <- as.Date(GTPtestdf$date)

shinyServer(function(input, output) {
  output$the_data <- renderDataTable({
    
    GTPtestdf
  })
  output$plotlyData <- renderPlotly({
    
    GTPdataplotly <- plot_ly(
      data = GTPtestdf, 
      x = GTPtestdf$date, 
      y = GTPtestdf$TA_Day,
      type = "scatter", 
      mode = "liners+markers"
    )
    GTPdataplotly
  })
})

and It's ui.R :

`library(shiny)
library(googlesheets)
library(plotly)

shinyUI(fluidPage(
  titlePanel("Quick demo"),
  
  sidebarLayout(
    sidebarPanel(
      dateRangeInput("dates", label = h3("date"), start = "2017-01-01", end = "2017-01-01", format = "yyyy-mm-dd"),
      selectInput("title", label = h3("station"), 
                  choices = c("title1", "title2", "title3"), selected = "title1"),
      submitButton("Submit"),
      br()
     
    ),
    
    mainPanel(
      tabsetPanel(
        
        tabPanel("result",
                 
                 dataTableOutput("the_data")
                 
        ),
        
          tabPanel("Plot", 
                   
                   plotlyOutput("plotlyData"))
        
      )
    )
  )
  
  
))`

`

**Comment by wch** [comment]
Hi, this seems to be an issue with shinyapps.io. Please post a message to the shinyapps-users mailing list: https://groups.google.com/forum/#!forum/shinyapps-users

If you are a paying customer, you can also open a ticket with RStudio support: https://support.rstudio.com/
