### ISSUE TITLE
Feature request: don't include shared bootstrap.css when navbarPage theme is used

### ISSUE THREAD

**Issue by alexvpickering** [rstudio/shiny#1781]
When an alternative bootstrap theme is used with the `theme` argument of `navbarPage`, 
`<link href="shared/bootstrap/css/bootstrap.min.css" rel="stylesheet">` still shows up in the `<head>` tag.

This causes the default theme to load first and be momentarily visible and then be replaced with the specified theme. It's ugly and also causes unnecessary bloat (loading two separate bootstrap.min.css files).

**Comment by cpsievert** [comment]
I think is the way it has to work for things for `{shinythemes}` to work. That being said, you can now use `{bslib}` to customize the bootstrap css that "we" bundle in the app. There you can customize bootstrap itself and/or tack on more custom rules, like this:

```r
library(bslib)
navbarPage(
  theme = bs_theme(version = 3, bg = "black", fg = "white", primary = "green") %>%
    bs_add_rules(sass::sass_file("custom-rules.scss")),
  ...
)
``` 

https://rstudio.github.io/bslib/
