### ISSUE TITLE
requires httpuv 1.3.5 but that version fails due to missing CXX11

### ISSUE THREAD

**Issue by merl-dev** [rstudio/shiny#1807]
I have been trying to install shiny and come up with the following problem:

1. `install.packages('httpuv')` installs version 1.3.3 without a glitch but cause the shiny install to fail:
```
* installing *source* package 'shiny' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'httpuv' 1.3.3 is being loaded, but >= 1.3.5 is required
ERROR: lazy loading failed for package 'shiny'
* removing '/usr/lib64/microsoft-r/3.4/lib64/R/library/shiny'
Error: Command failed (1)
```

2. `devtools::install_github('rstudio/httpuv')` fails:
```
Downloading GitHub repo rstudio/httpuv@master
from URL https://api.github.com/repos/rstudio/httpuv/zipball/master
Installing httpuv
'/usr/lib64/microsoft-r/3.4/lib64/R/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmp3oeMQV/devtools168fd7c21/rstudio-httpuv-65016f2'  \
  --library='/usr/lib64/microsoft-r/3.4/lib64/R/library' --install-tests 

* installing *source* package 'httpuv' ...
** libs
Error in .shlib_internal(args) : 
  C++11 standard requested but CXX11 is not defined
* removing '/usr/lib64/microsoft-r/3.4/lib64/R/library/httpuv'
Error: Command failed (1)
In addition: Warning message:
GitHub repo contains submodules, may not function as expected! 
Execution halted
```

Is there a way out of this nasty loop?

I also opened this github issue in rstudio/httpuv [C++11 standard requested but CXX11 is not defined](https://github.com/rstudio/httpuv/issues/79)
and this microsoft developer forum thread [install-httpuv-failing](https://social.technet.microsoft.com/Forums/en-US/c4742af5-07af-4202-a801-dc2fb11e4c52/install-httpuv-failing?forum=ropen)

**Comment by kamilien1** [comment]
@merl-dev  I found the best solution for me was to update my R version to 3.4.x

**Comment by wch** [comment]
If you're using an Amazon AMI, this could solve the problem:
  https://github.com/rstudio/httpuv/issues/82#issuecomment-331260778

See the previous message in that thread for a bit more info.

**Comment by HassanAftab** [comment]
did any one found solution to this ?

**Comment by merl-dev** [comment]
It appears that my problem was due to having anaconda in my path during install.  By changing the install sequence the issue disappeared.

**Comment by farman1855** [comment]
@HassanAftab if you found solution for this please let me know?

**Comment by Feruz88** [comment]
try to install  new version of R (not R Studio). it works!!!
