### ISSUE TITLE
plotOutput crash R session

### ISSUE THREAD

**Issue by tempranillo1** [rstudio/shiny#1809]
plotOutput crashes R session (3.4.1). To reproduce, first example from function's help page can be used:

```{r}
shinyApp(
  ui = fluidPage(
    sidebarLayout(
      sidebarPanel(
        actionButton("newplot", "New plot")
      ),
      mainPanel(
        plotOutput("plot")
      )
    )
  )
,
  server = function(input, output) {
    output$plot <- renderPlot({
      input$newplot
      # Add a little noise to the cars data
      cars2 <- cars + rnorm(nrow(cars))
      plot(cars2)
    })
  }
)
```

my session info:

> 
> R version 3.4.1 (2017-06-30)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250 LC_NUMERIC=C                  
> [5] LC_TIME=Polish_Poland.1250    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] shiny_1.0.3
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.4.1  R6_2.2.2        htmltools_0.3.6 tools_3.4.1     Rcpp_0.12.12    digest_0.6.12   xtable_1.8-2    httpuv_1.3.5   
> [9] mime_0.5

**Comment by wch** [comment]
Can you run `devtools::session_info()` and provide the output here? You may need to install the devtools package first.

Also, please read this article: http://shiny.rstudio.com/articles/upgrade-R.html

**Comment by tempranillo1** [comment]
Thanks a lot, `update.packages(ask = FALSE, checkBuilt = TRUE)` solved my problem. Previously I used "update" button from packages tab.
