### ISSUE TITLE
Segmentation fault when using ggplot2 and rJava dependent library

### ISSUE THREAD

**Issue by tencnivel** [rstudio/shiny#1810]
Hello,

I have a very strange problem on CentOS 7.

Loading any library that depends on rJava (eg. XLConnect, mailR) results in a call to ggplot to crash the Shiny app with a segmentation fault. Oddly enough loading rJava itself doesn't cause the same problem.

-bash: line 1: 29854 Segmentation fault      R --no-save --slave -f \/opt\/shiny-server\/R\/SockJSAdapter\.R

Apparently I have exactly the same configuration on the CentOS machine as on my Fedora machine (where everything works fine) : same R version, same library versions, same shiny-server version, same jdk (Sun 1.8.0_141).

Apparently I have no problem of configuration of rJava, XLConnect and mailR work fine in other apps on the same machine.

Here is the a one file app source code to reproduce the problem :

```
# Execute the following two lines to detach previously loaded packages
# library(mise)
# mise(vars = TRUE, figs = TRUE, console = TRUE, pkgs = TRUE)

library(shiny)
library("ggplot2")
library("mailR")

# Define UI for app that draws a histogram ----
ui <- fluidPage(

  # App title ----
  titlePanel("Hello Shiny!"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      
      # Output: Histogram ----
      plotOutput(outputId = "test_ggplot")

    )
  )
)

# Define server logic required to draw a histogram ----
server <- function(input, output) {
  
  
  output$test_ggplot <- renderPlot({
 
    writeLines(capture.output(sessionInfo()), "/tmp/sessionInfo.txt")
 
    ggplot(data = iris,aes(x = Sepal.Length, y = Sepal.Width)) + geom_point() # Crash!
    # plot(c(1,1)) # works!
    
  })

}

# Create Shiny app ----
shinyApp(ui = ui, server = server)

```
The result of sessionInfo is the following :

> R version 3.4.0 (2017-04-21)
> Platform: x86_64-redhat-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                 
>  [3] LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8       
>  [5] LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8      
>  [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8          
>  [9] LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8     
> [11] LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] mailR_0.4.1   ggplot2_2.2.1 shiny_1.0.3  
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.12      magrittr_1.5      munsell_0.4.3     colorspace_1.3-2 
>  [5] xtable_1.8-2      R6_2.2.2          rlang_0.1.1       stringr_1.2.0    
>  [9] plyr_1.8.4        tools_3.4.0       grid_3.4.0        gtable_0.2.0     
> [13] R.oo_1.21.0       htmltools_0.3.6   lazyeval_0.2.0    digest_0.6.12    
> [17] tibble_1.3.3      rJava_0.9-8       R.utils_2.5.0     mime_0.5         
> [21] stringi_1.1.5     compiler_3.4.0    scales_0.4.1      R.methodsS3_1.7.1
> [25] jsonlite_1.5      httpuv_1.3.5     
> 
> 
>

**Comment by tencnivel** [comment]
I have updated what needed to be updated using the following command :
`update.packages(ask = FALSE, checkBuilt = TRUE)`
It doesn't help.

I also reinstalled all libraries but same result

Here is the result of session_info() from the Fedora machine on which ggplot2 and java libraries do work : 

> R version 3.4.0 (2017-04-21)
> Platform: x86_64-redhat-linux-gnu (64-bit)
> Running under: Fedora 25 (Twenty Five)
> 
> Matrix products: default
> BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
> 
> locale:
>  [1] LC_CTYPE=en_SG.UTF-8          LC_NUMERIC=C                  LC_TIME=en_SG.UTF-8          
>  [4] LC_COLLATE=en_SG.UTF-8        LC_MONETARY=en_SG.UTF-8       LC_MESSAGES=en_SG.UTF-8      
>  [7] LC_PAPER=en_SG.UTF-8          LC_NAME=en_SG.UTF-8           LC_ADDRESS=en_SG.UTF-8       
> [10] LC_TELEPHONE=en_SG.UTF-8      LC_MEASUREMENT=en_SG.UTF-8    LC_IDENTIFICATION=en_SG.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] mailR_0.4.1   ggplot2_2.2.1 shiny_1.0.3  
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.12        magrittr_1.5        nnls_1.4            munsell_0.4.3       colorspace_1.3-2   
>  [6] xtable_1.8-2        R6_2.2.2            rlang_0.1.1         stringr_1.2.0       plyr_1.8.4         
> [11] tools_3.4.0         grid_3.4.0          gtable_0.2.0        R.oo_1.21.0         SuperLearner_2.0-22
> [16] htmltools_0.3.6     lazyeval_0.2.0      digest_0.6.12       tibble_1.3.3        rJava_0.9-8        
> [21] R.utils_2.5.0       mime_0.5            labeling_0.3        stringi_1.1.5       compiler_3.4.0     
> [26] scales_0.4.1        R.methodsS3_1.7.1   jsonlite_1.5        httpuv_1.3.5       
>

**Comment by wch** [comment]
Can you provide the output from devtools::session_info() from both of your computers?

**Comment by tencnivel** [comment]
the output of the CENTOS machine is in my first message

**Comment by wch** [comment]
Not `sesssionInfo()`, but `devtools::session_info()`

**Comment by tencnivel** [comment]
ah ok, sorry, here it is

**devtools::session_info() for Fedora (OK) :**

> setting  value                       
>  version  R version 3.4.1 (2017-06-30)
>  system   x86_64, linux-gnu           
>  ui       X11                         
>  language (EN)                        
>  collate  en_US.UTF-8                 
>  tz       Asia/Singapore              
>  date     2017-08-05                  
> 
>  package     * version date       source        
>  base        * 3.4.1   2017-06-30 local         
>  colorspace    1.3-2   2016-12-14 CRAN (R 3.4.0)
>  compiler      3.4.1   2017-06-30 local         
>  datasets    * 3.4.1   2017-06-30 local         
>  devtools    * 1.13.2  2017-06-02 CRAN (R 3.4.0)
>  digest        0.6.12  2017-01-27 CRAN (R 3.4.0)
>  ggplot2     * 2.2.1   2016-12-30 CRAN (R 3.4.0)
>  graphics    * 3.4.1   2017-06-30 local         
>  grDevices   * 3.4.1   2017-06-30 local         
>  grid          3.4.1   2017-06-30 local         
>  gtable        0.2.0   2016-02-26 CRAN (R 3.4.0)
>  htmltools     0.3.6   2017-04-28 CRAN (R 3.4.0)
>  httpuv        1.3.5   2017-07-04 CRAN (R 3.4.0)
>  jsonlite      1.5     2017-06-01 CRAN (R 3.4.0)
>  lazyeval      0.2.0   2016-06-12 CRAN (R 3.4.0)
>  magrittr      1.5     2014-11-22 CRAN (R 3.4.0)
>  mailR       * 0.4.1   2015-01-14 CRAN (R 3.4.0)
>  memoise       1.1.0   2017-04-21 CRAN (R 3.4.0)
>  methods     * 3.4.1   2017-06-30 local         
>  mime          0.5     2016-07-07 CRAN (R 3.4.0)
>  munsell       0.4.3   2016-02-13 CRAN (R 3.4.0)
>  plyr          1.8.4   2016-06-08 CRAN (R 3.4.0)
>  R.methodsS3   1.7.1   2016-02-16 CRAN (R 3.4.0)
>  R.oo          1.21.0  2016-11-01 CRAN (R 3.4.0)
>  R.utils       2.5.0   2016-11-07 CRAN (R 3.4.0)
>  R6            2.2.2   2017-06-17 CRAN (R 3.4.0)
>  Rcpp          0.12.12 2017-07-15 CRAN (R 3.4.0)
>  rJava         0.9-8   2016-01-07 CRAN (R 3.4.0)
>  rlang         0.1.1   2017-05-18 CRAN (R 3.4.0)
>  scales        0.4.1   2016-11-09 CRAN (R 3.4.0)
>  shiny       * 1.0.3   2017-04-26 CRAN (R 3.4.0)
>  stats       * 3.4.1   2017-06-30 local         
>  stringi       1.1.5   2017-04-07 CRAN (R 3.4.0)
>  stringr       1.2.0   2017-02-18 CRAN (R 3.4.0)
>  tibble        1.3.3   2017-05-28 CRAN (R 3.4.0)
>  tools         3.4.1   2017-06-30 local         
>  utils       * 3.4.1   2017-06-30 local         
>  withr         1.0.2   2016-06-20 CRAN (R 3.4.0)
>  xtable        1.8-2   2016-02-05 CRAN (R 3.4.0)
> 

**devtools::session_info() for CentOS (NOK) :**

> 
>  setting  value                       
>  version  R version 3.4.1 (2017-06-30)
>  system   x86_64, linux-gnu           
>  ui       X11                         
>  language (EN)                        
>  collate  en_US.UTF-8                 
>  tz       Asia/Singapore              
>  date     2017-08-04                  
> 
>  package     * version date       source        
>  base        * 3.4.1   2017-06-30 local         
>  colorspace    1.3-2   2016-12-14 CRAN (R 3.4.0)
>  compiler      3.4.1   2017-06-30 local         
>  datasets    * 3.4.1   2017-06-30 local         
>  devtools    * 1.13.3  2017-08-02 CRAN (R 3.4.0)
>  digest        0.6.12  2017-01-27 CRAN (R 3.4.0)
>  ggplot2     * 2.2.1   2016-12-30 CRAN (R 3.4.0)
>  graphics    * 3.4.1   2017-06-30 local         
>  grDevices   * 3.4.1   2017-06-30 local         
>  grid          3.4.1   2017-06-30 local         
>  gtable        0.2.0   2016-02-26 CRAN (R 3.4.0)
>  htmltools     0.3.6   2017-04-28 CRAN (R 3.4.0)
>  httpuv        1.3.5   2017-07-04 CRAN (R 3.4.0)
>  jsonlite      1.5     2017-06-01 CRAN (R 3.4.0)
>  lazyeval      0.2.0   2016-06-12 CRAN (R 3.4.0)
>  magrittr      1.5     2014-11-22 CRAN (R 3.4.0)
>  mailR       * 0.4.1   2015-01-14 CRAN (R 3.4.0)
>  memoise       1.1.0   2017-04-21 CRAN (R 3.4.0)
>  methods     * 3.4.1   2017-06-30 local         
>  mime          0.5     2016-07-07 CRAN (R 3.4.0)
>  munsell       0.4.3   2016-02-13 CRAN (R 3.4.0)
>  plyr          1.8.4   2016-06-08 CRAN (R 3.4.0)
>  R.methodsS3   1.7.1   2016-02-16 CRAN (R 3.4.0)
>  R.oo          1.21.0  2016-11-01 CRAN (R 3.4.0)
>  R.utils       2.5.0   2016-11-07 CRAN (R 3.4.0)
>  R6            2.2.2   2017-06-17 CRAN (R 3.4.0)
>  Rcpp          0.12.12 2017-07-15 CRAN (R 3.4.0)
>  rJava         0.9-8   2016-01-07 CRAN (R 3.4.0)
>  rlang         0.1.1   2017-05-18 CRAN (R 3.4.0)
>  scales        0.4.1   2016-11-09 CRAN (R 3.4.0)
>  shiny       * 1.0.3   2017-04-26 CRAN (R 3.4.0)
>  stats       * 3.4.1   2017-06-30 local         
>  stringi       1.1.5   2017-04-07 CRAN (R 3.4.0)
>  stringr       1.2.0   2017-02-18 CRAN (R 3.4.0)
>  tibble        1.3.3   2017-05-28 CRAN (R 3.4.0)
>  tools         3.4.1   2017-06-30 local         
>  utils       * 3.4.1   2017-06-30 local         
>  withr         2.0.0   2017-07-28 CRAN (R 3.4.0)
>  xtable        1.8-2   2016-02-05 CRAN (R 3.4.0)
>

**Comment by wch** [comment]
We've encountered hard-to-diagnose issues with rJava in the past. Your Centos and Fedora systems are probably similar but not identical.

 It's possible that there's a kernel incompatibility. See these:
https://stackoverflow.com/questions/44682540/rjava-dependent-package-installation-segmentation-fault-core-dumped
https://github.com/s-u/rJava/issues/110

**Comment by veitveit** [comment]
Thanks a lot!

Adding 
_options(java.parameters = "-Xss2560k")_ 
solved this for me on CentOS 7. Could indeed be a kernel issue as my code works without problems on OpenSuSE Tumbleweed and Arch Linux with recent kernels

**Comment by wch** [comment]
Glad it works now!

**Comment by tencnivel** [comment]
Adding `options(java.parameters = "-Xss2560k")` worked for me as well

**Comment by statwonk** [comment]
Same issue on,
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

`options(java.parameters = "-Xss2560k")` fixes.

**Comment by dsaada** [comment]
Hi,

I used mailR package on my shiny app, and i get segmentation fault when i change of tab. I try to use 
`options(java.parameters = "-Xss2560k")` without sucess.

could you help me please?
many thanks
David
