### ISSUE TITLE
Can I get a R console in a shiny app

### ISSUE THREAD

**Issue by statquant** [rstudio/shiny#1811]
Hello, I am looking for a way to get a proper R console into a shiny app.
If it sounds like a reasonable feature to me I have found nothing online probably meaning there is an obvious reason why this is not possible.

My use case would be to build a shiny app (a dashboard of some kind), but still provide the user a way to modify the underlying data. For this I was hoping to use shinyAce for the editor and ... some embeded console.

Does that exists ?
Is this doable ?

**Comment by wch** [comment]
Sorry, there's currently no component that provides an R console in a Shiny app. Such a thing is not impossible, but to do it well would probably be difficult, and it would also be a security risk from allowing others to run arbitrary code on the server.

**Comment by jcheng5** [comment]
A better avenue may be allowing Shiny to run in a nonblocking mode (where Shiny doesn't hold up the console the whole time it's running). Something we've thought about since the beginning but might become more feasible soon.

**Comment by statquant** [comment]
Hi Joe, many thanks for this answer.
I understand that those things are not easy to time but from what I
understand the feature I am looking for won't be available in 2017. Would
you say it is an okish assessment?

Best
