### ISSUE TITLE
conditionalPanel error when there is a newline in expression (was: breaking changes in 1.0.4?)

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#1818]
It seems Shiny 1.0.4 introduces some breaking changes compared to 1.0.3. The issue was first reported to me here: https://github.com/radiant-rstats/radiant/issues/25

The app (link below) works fine with 1.0.3 but the UI is broken by changes in 1.0.4. i.e., it looks like conditional panel just stopped working. I don't see any messages or errors so I'm not even sure where to start looking.

https://github.com/radiant-rstats/radiant.data

In the screen shot below all UI components are shown, including inputs that should only be shown if file-type csv is selected.

Shiny 1.0.4:

![image](https://user-images.githubusercontent.com/2998956/29434785-477dbdd0-8359-11e7-8365-b8bc9d8033d4.png)

Here is what the ui *should* look like if rds is selected. This works as intended in 1.0.3

Shiny 1.0.3:

![image](https://user-images.githubusercontent.com/2998956/29434862-86615944-8359-11e7-83e0-a3a5115e15c4.png)

**Comment by vnijs** [comment]
Just looked in the javascript console and the problem seems to occur when shiny tries to do evaluation for conditional panels

![image](https://user-images.githubusercontent.com/2998956/29435343-8ced1fda-835b-11e7-86c0-9912968a5bd2.png)

**Comment by umms-hackathon** [comment]
Have the same problem. All conditionalPanels in debrowser stopped working.

**Comment by vnijs** [comment]
@umms-hackathon I only have a large app to illustrate the issue at the moment which is not ideal. Do you have a (smaller) reproducible example already perhaps?

**Comment by umms-hackathon** [comment]
Mine is also large bioconductor package "debrowser"

**Comment by jcheng5** [comment]
Dang it. What does the condition string look like?

**Comment by vnijs** [comment]
Looks like this is the line it is stuck on:

https://github.com/radiant-rstats/radiant.data/blob/master/inst/app/tools/data/manage_ui.R#L140-L141

**Comment by vnijs** [comment]
If I put the condition string on one line conditional panel does work!

**Comment by jcheng5** [comment]
@umms-hackathon, does going to one line fix it for you?

Regardless, sorry for the breakage, we didn't think to test for that. @wch @bborgesr @alandipert maybe the meta-lesson is that we should add "Radiant smoke test" to the Shiny release checklist.

**Comment by vnijs** [comment]
@jcheng5 I didn't actually go through all my code to check that condition strings are one liners. I was just hoping to provide some information to help the shiny team track down the issue. Is there a fix (in shiny) in the works?

**Comment by wch** [comment]
I've bisected this to 379d523ac5dcddc93d9b073d1d7ca66b7fe09c82, which was from #1727.

**Comment by wch** [comment]
The problem is that it's essentially trying to run this code:

```
new Function("with (this) {
        try {
          return (input.plotType ==
                     'hist');
        } catch (e) {
          console.error('Error evaluating expression: input.plotType ==
                     \'hist\'');
          throw e;
        }
      }")
```

But the line break here is causing a parse error:

```
          console.error('Error evaluating expression: input.plotType ==
                     \'hist\'');
```

**Comment by wch** [comment]
@vnijs, @umms-hackathon, can you try out the proposed fix, #1820? You can install with:

```R
devtools::install_github("rstudio/shiny@wch-fix-conditionalpanel")
```

**Comment by umms-hackathon** [comment]
That fixed the problem for DEBrowser. However, they still get error, when they install 1.0.4 as a dependancy. Could you send me the timeline to put this change into the next version?

**Comment by vnijs** [comment]
Thanks for the fix!

**Comment by jcheng5** [comment]
@umms-hackathon We understand the urgency--we take all breaking changes seriously. However I think we should wait at least a couple more days to see if other breaking changes are reported.

**Comment by vnijs** [comment]
Thanks the quick release update! Shiny 1.0.5 is already on CRAN.
