### ISSUE TITLE
using NA as an radioButtons option

### ISSUE THREAD

**Issue by tbradley1013** [rstudio/shiny#1819]
I am currently building an app that uses a large number of `radioButtons` for the user to input whether Yes or No was indicated on a form so the information can be added to a SQL database. However, it is not unusual for neither Yes or No to be selected on the form. Because of this, I would like a NA to be selected as a third option for the `radioButtons`. 

Looking at the HTML from a `radioButtons()` input with my desired values, we can see that there is no value associated with the NA option:

        radioButtons(
              inputId = "ex_legal",
              label = "Is over 21?",
              choices = list("Yes" = TRUE, "No" = FALSE, "N/A" = NA),
              selected = NA,
              inline = TRUE
            )

        <div id="ex_legal" class="form-group shiny-input-radiogroup shiny-input-container shiny-input-container-inline">
          <label class="control-label" for="ex_legal">Is over 21?</label>
          <div class="shiny-options-group">
            <label class="radio-inline">
              <input type="radio" name="ex_legal" value="TRUE"/>
              <span>Yes</span>
            </label>
            <label class="radio-inline">
              <input type="radio" name="ex_legal" value="FALSE"/>
              <span>No</span>
            </label>
            <label class="radio-inline">
              <input type="radio" name="ex_legal" value checked="checked"/>
              <span>N/A</span>
           </label>
          </div>
        </div>

Even though there is no value associated with the "N/A" option, setting `selected = NA` still results in the correct "N/A" option being selected on the app loading. However, with no value being associated with the NA input, an empty character string is entered into the SQL database rather than an NA value. Since the columns associated with the `radioButtons` in the SQL database are booleans, the database then converts the empty strings to FALSE, which defeats the purpose of having N/A as an option. I am not sure if this behaviour is intentional or if I stumbled onto a bug. 

In addition to empty strings being entered into the SQL database, this issues causes the `shinyjs::reset()` function to fail when `selected = NA` in the `radioButtons` input. You can see [issue #142](https://github.com/daattali/shinyjs/issues/142) in the shinyjs repo for a complete reproducible example.

Thanks in advance for your help!

**Comment by wch** [comment]
The values of the choices should be strings, as in:

```
radioButtons(
  inputId = "ex_legal",
  label = "Is over 21?",
  choices = list("Yes" = "TRUE", "No" = "FALSE", "N/A" = "NA"),
  selected = "NA",
  inline = TRUE
)
```

If you pass in other values (like numbers or logicals) they get coerced to strings before being rendered in the web page. If you look at the value of `input$ex_legal` in your app, you'll see that it's a string, not a logical.

**Comment by daattali** [comment]
@tbradley1013 is not the first person to report a "bug" in shinyjs because of strange values supplied to radio buttons. Perhaps it's worth adding a few words in the documentation for radio buttons to mention that the values are expected to be strings.

**Comment by wch** [comment]
@daattali Good idea; I've done that in fc32c2c9.
