### ISSUE TITLE
tabSetpanel first argument

### ISSUE THREAD

**Issue by dmuijen** [rstudio/shiny#1823]
Migrating from shiny 1.0.3 to 1.0.4 tabSetpanel changed in a way it took a while to figure out the issue, see example below. Although caused by bad programming on my side by not declaring id specifically, others may experience similar problems.

### Works in 1.0.3 and 1.0.4
```
library(shiny)    
ui <- shinyUI(basicPage( 
  
  textOutput("text"),
  tabsetPanel(id = "tabs",
              tabPanel("Tab 1", value = "1", "Tab 1 content"),
              tabPanel("Tab 2", value = "2", "Tab 2 content")
  )
))

server <- function(input, output) {
  output$text <- renderText({paste0("Viewing tab \"", input$tabs, "\"")})
}

shinyApp(ui = ui, server = server)
```

### Works in 1.0.3 and crashes in 1.0.4 with "Error : $ operator is invalid for atomic vectors" on start
```
library(shiny)    
ui <- shinyUI(basicPage( 
  
  textOutput("text"),
  tabsetPanel("tabs",
              tabPanel("Tab 1", value = "1", "Tab 1 content"),
              tabPanel("Tab 2", value = "2", "Tab 2 content")
  )
))

server <- function(input, output) {
  output$text <- renderText({paste0("Viewing tab \"", input$tabs, "\"")})
}

shinyApp(ui = ui, server = server)
```

**Comment by wch** [comment]
In 1.0.3, the text `"tabs"` essentially got discarded:

```R
tabsetPanel(
  "abcdefg",
  tabPanel("Tab 1", value = "1", "Tab 1 content")
)
# <div class="tabbable">
#   <ul class="nav nav-tabs">
#     <li class="active">
#       <a href="#tab-2220-1" data-toggle="tab" data-value="1">Tab 1</a>
#     </li>
#   </ul>
#   <div class="tab-content">
#     <div class="tab-pane active" data-value="1" id="tab-2220-1">Tab 1 content</div>
#   </div>
# </div>
```

I agree that it would be useful to have a more informative error message when a non-`tabPanel` is passed to a `tabsetPanel`.

**Comment by wch** [comment]
Reopening so that we have a reminder to give a better message.

**Comment by micstr** [comment]
On Shiny 1.0.5, the help file has "old code" which has `tabsetPanel` without an id, which strangely works but it might be helpful to include an id to avoid others falling into this trap. 

Currently `?help(tabsetPanel)` Examples:
```
# Show a tabset that includes a plot, summary, and
# table view of the generated distribution
mainPanel(
  tabsetPanel(
    tabPanel("Plot", plotOutput("plot")),
    tabPanel("Summary", verbatimTextOutput("summary")),
    tabPanel("Table", tableOutput("table"))
  )
)
```

Please consider updating this in next release so it is explicit.
