### ISSUE TITLE
Allow ability to customize url hostname when using bookmarks

### ISSUE THREAD

**Issue by manny-goti** [rstudio/shiny#1834]
I've got a few shiny apps iframed into my own website. I'd like to be able to customize the bookmark links to also have the same hostname as my website. Then from the server side of my website I could take the url path that shiny creates and feed the correct link to the iframe. That way I won't have an ugly shiny server address link.

**Comment by wch** [comment]
Closing because there is a simple solution using `onBookmarked`. See comment in #1838.
