### ISSUE TITLE
Bug: Shiny v1.0.5 overwrites native html file upload behavior

### ISSUE THREAD

**Issue by adilapapaya** [rstudio/shiny#1835]
My app has a `server.R` and a separate `www/index.html` page for the UI. When I run the app with Shiny v1.0.4+ I am unable to upload a file using regular html:
```html
<!-- This will not work!! -->
<form>
      <div class="form-group">
        <label for="fileUpload">File Upload</label>
        <input type="file" id="fileUpload">
      </div>
</form>
```

This is what it looks like after I launch the page and upload a file:

1. `shiny::runApp()`: "no file selected"
<img width="203" alt="indexhtmlviashiny_screenshot" src="https://user-images.githubusercontent.com/4053020/29844804-73e4fe86-8cc5-11e7-9e48-3288797a8716.png">

2. Opening the `index.html` page in the browser: file shows up next to the upload.
<img width="295" alt="indexhtml_screenshot" src="https://user-images.githubusercontent.com/4053020/29844783-616ab20a-8cc5-11e7-872e-b8b3d18d7d91.png">

---

**Minimal reproducible example:**
```r
#server.R
library(shiny)
shinyServer(function(input, output, session) {});
```

```html
<!-- www/index.html -->
<html>
  <head>
    <script src="shared/jquery.js" type="text/javascript"></script>
    <script src="shared/shiny.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="shared/shiny.css"/> 
    <link rel="stylesheet" type="text/css" href="shared/bootstrap/css/bootstrap.css"/> 

    <style>
    body { font-family: Helvetica; }
    </style>
  </head>
   
  <body>
    <div class="container">    
      <form>
        <div class="form-group">
          <label for="fileUpload">File Upload</label>
          <input type="file" id="fileUpload">
        </div>
      </form>
    </div>
  </body>
</html>
```

---

Notes: 

- bug is in v1.0.4+ as v1.0.3 and below doesn't have this issue.
- Seems to be due to an update in the javascript. `shiny::runApp()` without including the `shiny.js` code doesn't have this isssue
```html
<!-- This will work -->
<script src="shared/jquery.js" type="text/javascript"></script>
<!-- <script src="shared/shiny.js" type="text/javascript"></script> -->
<link rel="stylesheet" type="text/css" href="shared/shiny.css"/> 
<link rel="stylesheet" type="text/css" href="shared/bootstrap/css/bootstrap.css"/> 
```

**Comment by wch** [comment]
I believe the HTML structure of file inputs changed somewhere in those versions, and the JS code is expecting the new structure. You might want to try updating your index.html to use the new structure. To get it, you can call `fileInput()` at the R console. For example:

```R
> fileInput("file1", "label")
<div class="form-group shiny-input-container">
  <label>label</label>
  <div class="input-group">
    <label class="input-group-btn">
      <span class="btn btn-default btn-file">
        Browse...
        <input id="file1" name="file1" type="file" style="display: none;"/>
      </span>
    </label>
    <input type="text" class="form-control" placeholder="No file selected" readonly="readonly"/>
  </div>
  <div id="file1_progress" class="progress progress-striped active shiny-file-input-progress">
    <div class="progress-bar"></div>
  </div>
</div>
```

**Comment by alandipert** [comment]
@adilapapaya did using the new HTML structure as per @wch fix this for you?

**Comment by adilapapaya** [comment]
@alandipert somewhat...It seems like I have to wrap things up the way @wch mentioned above (or use something along the same lines) if I want to display the name of the file that was uploaded. 

Is there a reason to overwrite `<input type="file"/>` so that  it doesn't display the name of the file next to the 'choose file' button, _even_ when it's not wrapped up in a `<div class="form-group shiny-input-container"> ... </div>`?

**Comment by wch** [comment]
The file is getting uploaded successfully, but in the browser it gets cleared. It does this so that a user can upload a file with the same file name multiple times. See #1508 and #1719.

Normally the `<input type="file">` tag is hidden and the user sees a text box that continues to display the name of the file. However, in your case, you're displaying the `<input>`, so the user sees that it has been cleared.

Is there a particular reason you want to use a bare input tag instead of the fancier-looking one that's generated by Shiny?

**Comment by adilapapaya** [comment]
> Is there a particular reason you want to use a bare input tag instead of the fancier-looking one that's generated by Shiny?

Main reason is that I usually have a 'submit' button that the user clicks on to submit the files. In the shiny 1.0.4+ implementation, there is no submit: uploading == submitting. (On the backend, both shiny and my custom implementation actually submit the file so the difference is purely what the user experiences)

I can hack around it but would prefer not to if it's also a simple script change on your end. If it's >5 mins work, then I'll figure out something since it also looks like I'm the only one affected by this. :)

Thanks for looking into this!

**Comment by wch** [comment]
It would be a nontrivial change to Shiny to support the behavior that you want -- I think it's best if you work around it.
