### ISSUE TITLE
icon and text alignment in navbarMenu and tabPanel

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#1840]
I just noticed that after the upgrade to 1.0.4 / 1.0.5  the alignment of text, icons, and dropdown triangles has changed. See screenshots below. Was this a deliberate change? Is this customizable?

In 1.0.3 all dropdown-indicators are on the left and all icons in the dropdown menu are on the left. In a dropdown menu the icons were on the left, which I think looks a bit nicer.

![image](https://user-images.githubusercontent.com/2998956/29903119-01906c56-8db7-11e7-9c0e-e6f9de8015a9.png)

In 1.0.5 dropdown-indicators for tab panels with text labels are on the right and for icons they are on the left. In a dropdown menu the icons are now on the right.

![image](https://user-images.githubusercontent.com/2998956/29903101-f51cc38e-8db6-11e7-9a83-6395d966ac79.png)

**Comment by vnijs** [comment]
For `actionLink` and `downloadLink` the icons are still aligned on the left so if you combine them with `tabPanel` icons you get something like this:

![image](https://user-images.githubusercontent.com/2998956/29903578-6b2c1f00-8db9-11e7-8432-83f508b919ad.png)

**Comment by dmpe** [comment]
I also saw this change in my forked repo. 👍 Glad not the only one. :)

**Comment by vnijs** [comment]
Just created a small example (see below). When you use text and an icon with `navbarMenu` in 1.0.5 the dropdown indicator is between the text and the icon. This, I expect, will be confusing for users. See screenshots below. Having all icon on the left, as it was in 1.0.3, seems preferable. 

```r
library(shiny)
shinyApp(
  ui = navbarPage("Navbar test",
    navbarMenu("", icon = icon("question-circle"), tabPanel("Text", icon = icon("power-off"))),
    navbarMenu("Text", icon = icon("edit"), tabPanel("Text", icon = icon("save")))
  ),
  server = function(input, output) {
  }
)
```

Shiny 1.0.3

![image](https://user-images.githubusercontent.com/2998956/30141949-2aaffe86-9333-11e7-9ca8-23c49abb4591.png)



Shiny 1.0.5

![image](https://user-images.githubusercontent.com/2998956/30141891-e3432d52-9332-11e7-86d8-9facf364737a.png)

**Comment by dmpe** [comment]
https://github.com/rstudio/shiny/blob/b4c5debbdf0502928fb69565cbe8656477fcdc72/R/bootstrap.R#L874 
this is where the problem begins. 
bug line: https://github.com/rstudio/shiny/blob/master/R/bootstrap.R#L887, https://github.com/rstudio/shiny/blob/master/R/bootstrap.R#L903

I fixed it in mine like this https://github.com/dmpe/shiny/blob/bootstrap4_changes/R/bootstrap.R#L912
Hope helps

**Comment by jcheng5** [comment]
@bborgesr Please fix
