### ISSUE TITLE
Rmarkdown runtime shiny crashes when rendering a ggplot if a library using rJava is imported

### ISSUE THREAD

**Issue by ashraaghav** [rstudio/shiny#1842]
I am trying to create an interactive markdown file using shiny and I am facing issues with using ggplot with libraries that use rJava. Using rJava does not seem to cause a problem though.

I had to use openNLP for some text mining operations I wanted to do and it caused the document to crash when I was rendering a `ggplot` exactly the **2nd time**. 

I later noticed that this happens when I just import any library that uses `rJava`, and this seems to happen only on R version >= 3.4.0. 

Some libraries I tried and got the same reaction: *openNLP, RWeka, wordnet, Rdrools*

I have added a sample gist below for others to try.

[gist for the sample Rmd](https://gist.github.com/ashraaghav/1d02dd8d1d519f3703d97bf7de57192c)

**Comment by wch** [comment]
This is probably the same issue as #1810, and is related to an issue with the Linux kernel. Try using `options(java.parameters = "-Xss2560k")` and see if that fixes it.

**Comment by ashraaghav** [comment]
Yes adding the parameter fixed it. Thanks!
