### ISSUE TITLE
call modules in parallel

### ISSUE THREAD

**Issue by hschult** [rstudio/shiny#1843]
Hello everyone,
I'm working on an app which is dynamically calling modules based on the given input.
But as each call can take some time I tried a parallelized approach to increase the performance.

So now to my problem the app is starting and everything looks fine but the output won't update itself if there are changes. If I look at the reactlog it shows that the selectInput is receiving the new input but doesn't invalidate the reactive.

```
###module
moduleUI <- function(id, text = "module"){
  ns <- shiny::NS(id)
  
  shiny::tagList(
    shiny::textInput(inputId = ns("text"), label = id, value = text)
  )
}

module <- function(input, output, session){
  
  out <- shiny::reactive({
    paste("Text:", input$text)
  })
  
  return(out)
}

###app
## ui.R
ui <- fluidPage(
  moduleUI("id1", text = "module1"),
  moduleUI("id2", text = "module2"),
  moduleUI("id3", text = "module3")
)

## server.R
server <- function(input, output, session) {
  cl <- parallel::makeCluster(parallel::detectCores()-1, type = "PSOCK")

  parallel::clusterExport(cl, varlist = c("module", "session"), envir = environment())
  
  modules <- parallel::parSapply(cl, paste0("id", 1:3), function(x){
    modcall <- shiny::withReactiveDomain(session, shiny::callModule(module = module, id = x))
  })
  
  parallel::stopCluster(cl)
  
  shiny::observe({
    outlist <- sapply(modules, function(x){
      x()
    })
    print(outlist)
  })
}

shinyApp(ui = ui, server = server)
```
I tried the same with a normal sapply and it worked so I'm relatively sure the problem occurs within the clustered computation.
Also I guess it has something to do with the environment/ session as each thread creates it's one scope so the reactivity is maybe lost on return. But I can't really narrow it down.

I hope my description is understandable and thanks in advance for any help.

**Comment by jcheng5** [comment]
You can't do it this way. Running with parallel does the computation in a different R process, and the reactive framework has no way to track dependencies across multiple processes.

Your best option is to try to reduce the amount of work done by each module (is there work you can precompute and put on disk, or at least extract work that's common between modules and pass the common data into each module?). If that really can't be done, then you might benefit from an upcoming feature that will introduce asynchronous computation into Shiny.

**Comment by hschult** [comment]
Thanks for the answer
I kind of feared that it would be impossible this way. Well, I guess I have to try to precompute it as you said.
Asynchronous computation sounds interesting is there already a release date for it?

Anyway thanks for the great package keep up the good work.
