### ISSUE TITLE
Can't update value server selectize

### ISSUE THREAD

**Issue by carlganz** [rstudio/shiny#1852]
MRE:

```{R}
library(shiny)

ui <- fluidPage(
  selectizeInput("test", "test", "", options = list(
    maxOptions = 5
  )),
  actionButton("update", "Set selectize to 6")
)

server <- function(input, output, session) {
  updateSelectizeInput(session, "test", choices = 1:100, server = TRUE)
  
  observeEvent(input$update, {
    updateSelectizeInput(session, "test", selected = 6)
  })
  
}

shinyApp(ui, server)
```

It works if selected is between 1 and 5. Clearly only the values currently loaded by selectize are available to be selected. When I get a chance I will look at source code and see if there is a fix.

**Comment by DarioS** [comment]
I encountered the same bug today. Another issue with this code is if both `updateSelectizeInput` usages have `server = TRUE`, there is an error. The error message is "Warning: Error in <-: attempt to set an attribute on NULL".

**Comment by carlganz** [comment]
#1861 was the cause of this

**Comment by carlganz** [comment]
The example above works now if I include choices with the second `updateSelectizeInput` so I consider this solved
