### ISSUE TITLE
reactiveValues inside downloadHandler

### ISSUE THREAD

**Issue by KZARCA** [rstudio/shiny#1853]
I need to have a counter for downloads. So I use a reactive value that I want to set inside the 'content' argument of the `downloadHandler` function 

An example:
```r
library(shiny)
ui <- fluidPage(
  downloadButton("downloadData", "Download"),
  actionButton("trig", "get number")
)

server <- function(input, output) {
  data <- mtcars
  rnDownloads <- reactiveValues(n=0)

  observe(print(rnDownloads$n))

  observeEvent(input$trig, {
    print(paste("number of downloads:", rnDownloads$n))
  })
  
  output$downloadData <- downloadHandler(
    filename = function() {
      paste("data-", Sys.Date(), ".csv", sep="")
    },
    content = function(file) {
      rnDownloads$n <- rnDownloads$n + 1
      write.csv(data, file)
    }
  )
}

shinyApp(ui, server)
```
The only way to update the value of the reactiveValue `rnDownloads$n` is to click on the `actionButton`.

I posted [this question](https://community.rstudio.com/t/how-to-count-downloads/897) on community.rstudio.com, and @jcheng5 recommended to post it on this github.

**Comment by jcheng5** [comment]
Internal note: Downloading a file should cause a flush.

**Comment by jcheng5** [comment]
This got fixed somewhere along the way.

**Comment by sollano** [comment]
@jcheng5 , sorry to bother you. But I was trying to do this exact same thing, and it worked for me on my Windows machine. But when I sent my app to my shiny server (on a linux server) I ran into this same problem. I had to manually flush the session by changing tabs for the counter to go up. 
Maybe it's something local for me, but I think this is still an issue on linux. 

Obs: The fix that you suggested on the github question solved it for me, so It's working. But I thought you should know this,
