### ISSUE TITLE
In eventReactive, ignoreNULL=TRUE prevents code from being executed even if other reactive values are being invalidated

### ISSUE THREAD

**Issue by gutweniger** [rstudio/shiny#1854]
It seems to me that there are undesired side effects of setting ignoreNULL=TRUE in eventReactive():

Apparently, code will generally not be executed as long as the event equals NULL - even if other relevant events in that context occur, e.g. the change of a reactive value. As a consequence, inserting an event handler with ignoreNULL=TRUE may prevent code from beeing executed that otherwise would work fine.

Please see my example below:
```
ui <- shinyUI(pageWithSidebar(
  headerPanel("eventReactive and observeEvent"),
  sidebarPanel(
    actionButton("evReactiveButton", "Button"),
    p(),
    radioButtons("radio", "Select a value:", c("One"=1, "Two"=2, "Three"=3), selected=1)
  ),
  mainPanel(
    p("This works right from the beginning:"),
    verbatimTextOutput("myText1"),
    p("This doesn't work until the button is pressed for the first time:"),
    verbatimTextOutput("myText2"),
    p("This works right from the beginning:"),
    verbatimTextOutput("myText3")
  )
))

server <- shinyServer(function(input, output) {

  buttonReaction1 <- eventReactive(input$evReactiveButton, ignoreNULL=FALSE, 42)

  buttonReaction2 <- eventReactive(input$evReactiveButton, ignoreNULL=TRUE, 42)

  output$myText1 <- renderText({
    b <- buttonReaction1()  # eventReactive having ignoreNULL=FALSE
    input$radio
  })

  output$myText2 <- renderText({
    b <- buttonReaction2() # eventReactive having ignoreNULL=TRUE
    input$radio
  })

  output$myText3 <- renderText({
    # No eventReactive 
    input$radio
  })
  
})

shinyApp(ui=ui,server=server) 
```

**Comment by wch** [comment]
I think this is because of how ignoreNULL works with actionButtons. From the eventReactive help page:

> Both observeEvent and eventReactive take an ignoreNULL parameter that affects behavior when the eventExpr evaluates to NULL (or in the special case of an actionButton, 0). In these cases, if ignoreNULL is TRUE, then an observeEvent will not execute and an eventReactive will raise a silent validation error.

Since an actionButton starts out with a value of 0, the eventReactive raises the silent validation error.

**Comment by gutweniger** [comment]
Dear Winston,

thanks for your prompt reply.

Yes, it somehow fits the description of the help page – although I don’t think this part of the documentation is particularly clear (« raise a silent validation error » is a very positive way of saying « nothing will happen without telling you why »).

Anyhow, I find it this behaviour very counter-intuitive:
Usually, if I combine several reactive values (or «events) in one piece of code, the code will be executed, when AT LEAST one of those reactive values changes.
Here, it’s the very opposite : by adding eventReactive to my code, I prevent it from executing in cases where it otherwise would.
And because the validation error is raised «silently », it’s very hard to get aware of this strange behaviour. For me, it really became a trap and I spent several hours in evaluating what’s acutally going on.

Maybe it’s at least possible to extend the documentation on this a little ?

Thanks a lot

Andreas


Von: Winston Chang [mailto:notifications@github.com]
Gesendet: Mittwoch, 20. September 2017 19:26
An: rstudio/shiny <shiny@noreply.github.com>
Cc: gutweniger <andreas.gutweniger@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [rstudio/shiny] In eventReactive, ignoreNULL=TRUE prevents code from being executed even if other reactive values are being invalidated (#1854)


I think this is because of how ignoreNULL works with actionButtons. From the eventReactive help page:

Both observeEvent and eventReactive take an ignoreNULL parameter that affects behavior when the eventExpr evaluates to NULL (or in the special case of an actionButton, 0). In these cases, if ignoreNULL is TRUE, then an observeEvent will not execute and an eventReactive will raise a silent validation error.

Since an actionButton starts out with a value of 0, the eventReactive raises the silent validation error.
