### ISSUE TITLE
Significantly speed-up server-side selectizeInput

### ISSUE THREAD

**Issue by dselivanov** [rstudio/shiny#1859]
[This line of code](https://github.com/rstudio/shiny/blob/e30fac02eddbb7cd510d448e385c559c82009a24/R/update-input.R#L683-L685) slows down **A LOT** on large lists (>10000). The problem in in `apply()` function and thousands of function calls. This could be done much faster with `rowSums()`. Something like:
```r
matches = rowSums(matches)
if(query$conju == 'and')
  idx = idx | (matches == length(key))
else 
  idx = idx | matches
```

**Comment by dselivanov** [comment]
According to benchmark below it is **~50x faster**.  Initial `grepl()` call takes ~ 0.1 sec, so overall improvement will be significant.

```r
N = 1e6
conju = "and"

x1 = matrix(sample(c(T, F), size = N, replace = T, prob = c(0.01, 0.99)), ncol = 1)
x2 = matrix(sample(c(T, F), size = N, replace = T, prob = c(0.01, 0.99)), ncol = 1)
key = c('a', 'b')

m = cbind(x1, x2)
K = ncol(m)

idx1 = logical(N)
system.time({
  matches = rowSums(m)
  if(conju == 'and') {
    idx1 = idx1 | (matches == K)
  } else {
    idx1 = idx1 | matches
  }
})
# user  system elapsed 
# 0.017   0.009   0.026 

idx2 = logical(N)
system.time({
  if(conju == 'and') {
    cjn = all 
  } else {
    cjn = any
  }
  idx2 <- idx2 | apply(m, 1, cjn)
})
# user  system elapsed 
# 1.173   0.165   1.347 

all.equal(idx1, idx2)
# TRUE
```

**Comment by wch** [comment]
@yihui, does this look like a reasonable fix?

**Comment by yihui** [comment]
Yes! Thanks @dselivanov!

**Comment by dselivanov** [comment]
actually I've spent a little bit more time on profiling. It seems that most time spent in `choicesWithNames` [call](https://github.com/rstudio/shiny/blob/e30fac02eddbb7cd510d448e385c559c82009a24/R/update-input.R#L670-L671). Can't it be replaced with just ?

```r
data <- if (is.atomic(data)) {
    lab = if(is.null(names(data))) {
      as.character(data)
    } else {
      names(data)
    }
    data.frame(label = lab, value = data,
               stringsAsFactors = FALSE)
  } else {
    as.data.frame(data, stringsAsFactors = FALSE)
  }
```

**Comment by dselivanov** [comment]
With these 2 fixes server-side `selectizeInput` works very fast on 1M choices.

**Comment by wch** [comment]
@dselivanov `choicesWithNames` is more sophisticated than that, and unfortunately can't be simplified so easily. The unit tests illustrate:
  https://github.com/rstudio/shiny/blob/176fe699/tests/testthat/test-bootstrap.r#L71-L164

**Comment by yihui** [comment]
In this particular case, it probably can be simplified, because there is the `is.atomic()` condition. The code that @dselivanov provided is not completely equivalent to `choicesWithNames()`, but pretty close. There is only one edge case to consider: a vector with elements with empty names, e.g. `c(A = 'a', 'b')`. In this case, `names()` is not NULL.

**Comment by wch** [comment]
Does it not need to support nested lists here?

A few asides:

* The `is.atomic` check means that lists will take the slow path, even if they are flat and therefore could be coerced to a character vector without losing any information.
* Could the `choices` be converted to a data frame before being passed to `session$registerDataObj`?
* `data.frame` and `as.data.frame` can be slow, and using a list of vectors can be significantly faster for some use cases.

**Comment by dselivanov** [comment]
@yihui agree. This edge case could be replaced with
```r
empty_names_mask = names(data) == ""
lab[empty_names_mask] = as.character(data[empty_names_mask])
```
@wch can't comment on these topics, not familiar shiny codebase. But I'm pretty sure these 2 tweaks can be 100% back-compatible with current code and improve a lot "fastpath" (which I believe used in 99% cases).

I can create PR and we can continue discussion there.  Should I do that?

**Comment by daattali** [comment]
On behalf of a lot of shiny users, thank you @dselivanov ! You're not the first to notice large server-side select can be slow, but you're the first to dig into it and improve it :)
