### ISSUE TITLE
Small documentation issue

### ISSUE THREAD

**Issue by GregorDeCillia** [rstudio/shiny#1863]
The usage section of the `shinyApp` documentation mentions a function called `as.tags`. 

    ## S3 method for class 'shiny.appobj'
    as.tags(x, ...)

This function is however from the `htmltools` package and it is not visible after loading shiny.

    # load shiny, but not htmltools
    library(shiny)     

    # apply as.tags to a dummy app
    as.tags(shinyApp(fluidPage(), function(...){}))
> Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
>   object 'as.tags' not found

**Comment by jcheng5** [comment]
Thanks. I think we'll just leave it--it's pretty minor and those are automatically generated by Roxygen (I'd prefer if it didn't show it at all).
