### ISSUE TITLE
Error "Can't call `runApp()` from within `runApp()`" when showing tooltips

### ISSUE THREAD

**Issue by mjpnijmeijer** [rstudio/shiny#1875]
Hi,
First of all my apologies if this issue is my mistake.

Running a Shiny app in RSudio with server logic (in "server.R")
```
library(shiny)
library(ggvis)

shinyServer(function(input, output) {
  
  df = data.frame(x = c(1,0), y = c(0,1))

  all_values <- function(x) {
    if(is.null(x)) return(NULL)
    paste0(names(x), ": ", format(x), collapse = "<br />")
  }
  
  output$my_plot <- renderPlot({
    
    df %>% ggvis( ~ x, ~ y) %>% layer_points() %>%
      bind_shiny( "ggvis_ui", "my_plot") 

  }, width = 500, height = 500)
})
```
and ui logic (in "ui.R")
```
library(shiny)
library(ggvis)

shinyUI(fluidPage(
  
  sidebarLayout(
    sidebarPanel(),
    
    mainPanel(
      uiOutput("ggvis_ui"),
      ggvisOutput("my_plot")
    )
  )
))
```
works fine. However, if I add tooltips to the plot by modifying the ggvis call in the server logic to
```
    df %>% ggvis( ~ x, ~ y) %>% layer_points() %>%
      add_tooltip(all_values, "hover") %>%
      bind_shiny( "ggvis_ui", "my_plot")
```
I obtain the plot with tooltips but also an error message "Warning: Error in <Anonymous>: Can't call \`runApp()\` from within \`runApp()\`". 

I am running the Shiny app by pressing the button "Run App" in RStudio.

**Comment by bborgesr** [comment]
I think your code might be doing something strange, especially with the call to `ggvis` inside the `renderPlot` function, which I think you shouldn't do for _ggvis_ (though I'm really not an authority on that)

I started from a basic app found on the _ggvis_ repo (https://github.com/rstudio/ggvis/tree/master/demo/apps/basic) and didn't have any problems adding the tool tips:

```r
library(shiny)
library(ggvis)

ui <- fluidPage(
  sliderInput("n", "Number of points", min = 1, max = nrow(mtcars),
    value = 10, step = 1),
  ggvisOutput("plot")
)

server <- function(input, output, session) {
  mtc <- reactive({ mtcars[1:input$n, ] })
  
  all_values <- function(x) {
    if(is.null(x)) return(NULL)
    paste0(names(x), ": ", format(x), collapse = "<br />")
  }
  
  mtc %>%
    ggvis(~wt, ~mpg) %>%
    layer_points() %>%
    add_tooltip(all_values, "hover") %>%
    bind_shiny("plot")
}

shinyApp(ui, server)
```

if i misread your problem, let me know and I'll re-open.
