### ISSUE TITLE
request: Installation of R package "RMeCab", MeCab, and its dictionary on ShinyApps.io.

### ISSUE THREAD

**Issue by ms512** [rstudio/shiny#1878]
Hi.
I was advised to post here by the Rstudio support.

I want to use MeCab on ShinyApps.io.
It is a morphological analysis engine for Japanese.
Is there a possibility that ShinyApps.io would make them available on their server?

**Comment by bborgesr** [comment]
cc @jspiewak

**Comment by jspiewak** [comment]
I suspect that support suggested you open a ticket in the [shinyapps-package-dependencies](https://github.com/rstudio/shinyapps-package-dependencies) repository.

Also have a look at http://docs.rstudio.com/shinyapps.io/getting-started.html#using-your-r-packages-in-the-cloud

**Comment by ms512** [comment]
Thank you!
I opened a ticket in the shinyapps-package-dependencies repository as you advised.

**Comment by mschilli87** [comment]
for reference: https://github.com/rstudio/shinyapps-package-dependencies/issues/112
