### ISSUE TITLE
Provide a color option in checkboxGroupInput?

### ISSUE THREAD

**Issue by tianxu03** [rstudio/shiny#1879]
Sometimes for convenience, it would be great to have the options in checkboxGroupInput color-coded. Just wondering if there's a way of providing such an option.

Thanks,
Victor

**Comment by wch** [comment]
You can do it with `choicesNames`, which lets you pass in HTML for a choice.


For example:

```
shinyApp(
  fluidPage(
    checkboxGroupInput("x", "X",
      choiceNames = list(
        span("choice 1", style = "color: green;")
      ),
      choiceValues = list(
        "choice1"
      )
    )
  ),
  function (input, output) {}
)
```

I put the style in line, but you could also do it with CSS and `span("choice 1", class = "myclass")`. That might more efficient if you have a lot of items or custom styling.

**Comment by mareichler-spra** [comment]
Hello!  The code listed above only changes the font color to green.  Is there a way to change the color in the checkbox from the default blue to another color? Thanks!

**Comment by cpsievert** [comment]
@mareichler-spra this is easiest to do with `{bslib}` with it's new Bootstrap 5 support.

```r
shinyApp(
    fluidPage(
        theme = bslib::bs_theme(version = 5, primary = "red"), 
        checkboxGroupInput("x", "X", c("a", "b"))
    ),
    function (input, output) {}
)
```

**Comment by mareichler-spra** [comment]
Thank you! Is it possible to do it outside of the theme argument?  I already have a `theme = "styles.css"` in that argument that is required.

**Comment by jzadra** [comment]
> Thank you! Is it possible to do it outside of the theme argument? I already have a `theme = "styles.css"` in that argument that is required.
> 
> Edit 2021-09-10 at 16:40 PT
> 
> * `bslib::bs_theme(version = v, primary = "red")` does not change the color if v = 3 or 4.  I think version = 3 is the default R shiny theme.
> * `bslib::bs_theme(version = 5, primary = "red")` is not compatible with all widgets; I was unable to get `selectInput()`, `selectizeInput()`, or `shiny::pickerInput()` to work.

I also have the same question.

**Comment by MarEichler** [comment]
I'm not sure if it will work for everyone, but I was change the color of the checked box using the following: 
```
tags$style("input[type=checkbox] { accent-color: red; }")
```

This changed the checked box color for both `checkboxInput()` and `checkboxGroupInput()` while I was testing.
