### ISSUE TITLE
renderUI and uiOutput slower than loading the data directly

### ISSUE THREAD

**Issue by emmanuelaaaaa** [rstudio/shiny#1888]
Hello, 

I have been having issues with using the renderUI/uiOutput in my app. I find that it is considerably slower than loading the data in the ui.R using the uiOutput. In reality, they are both kind of slow because they are creating the ui with a very long vector, but they seem to be different slow. The 1st one is slow to load before the app is rendered properly, while the other it looks ready but without any data in it for a (long) while. I realize that this is a similar scenario to the issue [1175,](https://github.com/rstudio/shiny/issues/1175) but that issue is closed and slightly different in the implementation so I thought I’d start a new one. I'm attaching the folders of both my example apps (I can also attach the code, if it's easier).

[shiny_temp.zip](https://github.com/rstudio/shiny/files/1449858/shiny_temp.zip)
[shiny_temp_renderUI.zip](https://github.com/rstudio/shiny/files/1449859/shiny_temp_renderUI.zip)

I would load the data directly in the ui to save me some time, even though it's not optimal, but I when I tried to publish on the shiny server that option doesn’t seem to work (not sure why that is either). 
A bit off the topic, but I also tried to use the profvis to see if I can get any ideas of why this is happening, but I am getting an error (Error in parse_rprof(prof_output, expr_source) : No parsing data available. Maybe your function was too fast?).

Please keep in mind that the figshare will need to be authenticated to load the data, so you will need an account (even if it’s a dummy one). 

Any recommendations about my code are always welcome :)

Thank you and sorry if I packed it with questions!
Emma

**Comment by emmanuelaaaaa** [comment]
Just a note to say that eventually I found an answer to that, in case someone needs it in the future. 
The selectizeInput with updateSelectizeInput combination seem to be handling very large input selections much better than the renderUI and uiOutput ones. That way I didn't need to load the data in the ui in the end. 
I hope this helps. 
Emma

**Comment by AhmedJOU** [comment]
Works, so many thanks!!! @emmanuelaaaaa
