### ISSUE TITLE
[proposal] change functions name rule.

### ISSUE THREAD

**Issue by mrchypark** [rstudio/shiny#1893]
How do you think to change functions name like sliderInput() to inputSlider() ?

It would be better to use autocomplete with rstudio.

**Comment by wch** [comment]
That would be helpful for function discovery, but at this point it's not feasible to change the function names.

**Comment by vnijs** [comment]
Add aliases?

**Comment by mrchypark** [comment]
@vnijs fork and add aliases is good alternative!
