### ISSUE TITLE
Shiny web server

### ISSUE THREAD

**Issue by wenbostar** [rstudio/shiny#1897]
Hi,

I built a web application based on Shiny in a Linux server. When the application was running with a job A, I tried to access the web application in another computer, I couldn't see the web page until the job A was done. It means in the same time, only one job can be running. Does anyone know how to configure the app to make multiple users be able to submit jobs in the same time?

Bo

**Comment by jcheng5** [comment]
There are a couple of ways to handle this. One is to use Shiny Server Pro, our enterprise solution for hosting Shiny apps, and configure it to use one process per user. The other is an upcoming feature of Shiny called async. For a preview of that functionality you can read this draft documentation: https://medium.com/@joe.cheng/an-informal-intro-to-async-shiny-cbf01c85c4c5

**Comment by wenbostar** [comment]
@jcheng5 , thank you for your answer. You mean if I use Shiny Server Pro I can make multiple users use my app in the same time?

Best regards!
Bo

**Comment by bborgesr** [comment]
Exactly so, it's a feature called "Utilization Scheduler": see details in the Shiny Server admin's Guide: http://docs.rstudio.com/shiny-server/#utilization-scheduler

**Comment by bborgesr** [comment]
And I should clarify: even in the Shiny Server open source version, multiple users _can_ use your app at the same time. They just all share the same R process, so if there is a blocking operation at any time, all connected clients won't be able to communicate with the server (R) side for the duration of that blocking operation.

**Comment by wenbostar** [comment]
@bborgesr , got it. Thanks a lot.
