### ISSUE TITLE
ggsave changed current graphic device and moved all plot in shiny out of shiny

### ISSUE THREAD

**Issue by dracodoc** [rstudio/shiny#1901]
[Stackoverflow discussion](https://stackoverflow.com/questions/47699956/ggplot-in-shiny-app-go-to-rstudio-plot-window/47701308)

This shiny app used `ggsave` to save a ggplot object before rendering it.

```r
library(shiny)
library(ggplot2)
SAVE_PLOT <- TRUE
ui <- fluidPage(fluidRow(column(12, plotOutput("plot"))))
server <- function(input, output){
  output$plot <- renderPlot({
    print(dev.list())
    cat("current device:\n")
    print(dev.cur())
    g <- ggplot(mtcars, aes(wt, mpg)) + geom_point()
    if (SAVE_PLOT) {
      ggsave("plot.png", g)
    }
    print(dev.list())
    cat("current device:\n")
    print(dev.cur())
    g
  })
}
shinyApp(ui = ui, server = server)
```

If user made some plot in R session,

```r
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) + geom_point()
```

then the app will show plot in RStudio plot window instead of Shiny window.

We can see the current open graphic device changed after `ggsave`

```r
Listening on http://127.0.0.1:7766
        RStudioGD quartz_off_screen quartz_off_screen 
                2                 3                 4 
current device:
quartz_off_screen 
                4 
Saving 12.9 x 5.56 in image
        RStudioGD quartz_off_screen quartz_off_screen 
                2                 3                 4 
current device:
RStudioGD 
        2 
```

This is not limited to RStudio. R console have same problem.

Basic plot and `dev.print` don't have this problem.

We can work around the problem by saving and restoring the device before/after `ggsave`, however ideally this should not be needed for user. 

```r
      cur_dev <- dev.cur()
      ggsave("plot.png", g)
      dev.set(cur_dev)
```

I'm not sure if this is a problem in Shiny or `ggsave`, or some interaction between them.

**Comment by dracodoc** [comment]
I think `ggsave` first created a device (like `png` in our case) then turned it off before exit. Somehow it turned off the Shiny device and the RStudio device became current.

**Comment by wch** [comment]
Thanks for the investigation. It looks like this is a bug in `ggsave()` (tidyverse/ggplot2#2363) so I'm closing this issue.
