### ISSUE TITLE
renderPlot lag time

### ISSUE THREAD

**Issue by manalirupji** [rstudio/shiny#1904]
I have developed a shiny with mutliple tabs. The tabs are data dependent and perform analysis like a workflow in different tabs. In the third tab, I am using renderPlot to display images from the ConsensusClusterPlus bioconductor package function after performing clustering analysis on my reactive object (containing my data). I also provide the user, a download button to select the pdf output of the results. 

I notice that the clustering is completed in less an a minute on my virtual instance (based on the log file displaying clustered), but the plot is not rendered for another 12 minutes making it a total of about 14 mins on that particular tab. I also notice that if I were to chose not to display the renderPlot but only provide the users the download option, the clustering is done within a minute and the output pdf is available almost instantly for download after that. 

I am unable to understand why there is a lag when I use renderPlot. 

Regards,
Manali

**Comment by manalirupji** [comment]
I was able to remove the time lag by putting the plotting function inside a reactive function and calling it from the renderPlot. I still don't understand why even when the clustering is finished within a minute the plots are not rendered to ui side (and thus the lag time), when I directly plot using renderPlot.

**Comment by jcheng5** [comment]
That's wild. Can you show us your code?

**Comment by bborgesr** [comment]
Closing unless we hear back from OP and we reopen it
