### ISSUE TITLE
`attach` data.frames in a reactiveValues list? 

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#1905]
I have an app where the user can use the UI to generate code. The generated code can be run inside the app but also as part of an rmarkdown file or r-code file in R(studio). In the app, the user loads data that is stored in a `reactiveValues` list called `r_data`. Suppose the user generated (or typed) code is:

```r
lm(y ~ x1 + x2 + vs, data = r_data[["user_data"]])
``` 

This will work fine inside the app and will also run outside the app *if* the user has a list called `r_data` with `user_data`. What I'd like, however, is to have the code below work *inside the shiny app* so that it can be used more easily both inside and outside the app.

`lm(y ~ x1 + x2, data = user_data)`

`reactiveVal` or `reactive({...})` wouldn't work because you would have to use something like `user_data()`. If `r_data` was a regular list you could do something like:

```r
attach(r_data)
lm(y ~ x1 + x2, data = user_data)
```

but using `attach` on a `reactiveValues` object doesn't seem to have any effect. Any suggestions?

**Comment by vnijs** [comment]
Any ideas if something like this is possible? Is there another way perhaps to put `r_data` on the search path and make `user_data` directly accessible? Thanks

**Comment by wch** [comment]
You could use `reactiveValuesToList()`. Depending on your use case, you may also want to wrap it in `isolate()`.

**Comment by vnijs** [comment]
I do use `reactiveValuesToList()` when saving data and inputs. 

In the shiny app, however, I need data.frames to be reactive. Now, accessing the data requires `user_data$dataset1`. If `reactiveValues` had an `attach` type method you could access the data using `dataset1` which could make a **big** difference for me.

I guess what I'm looking for is more of a `pointer`, however, as you'd also need to be able to change the data using something like:

`dataset1 <- mutate(dataset1, x = y / 2)`

instead of

`user_data$dataset1 <- mutate(user_data$dataset1, x = y / 2)`

An alternative might be to have reactive data.frames that can be created in the main shiny environment. You could call them using `dataset1` rather than `dataset1()` as you would have to do if you used `reactiveVal`

**Comment by vnijs** [comment]
Or perhaps an option to create a `reactiveEnvironment` where you could store objects and that could be added to the search path. All objects created in that environment would automatically be reactive. You could then probably also use something like `eval(my_function(...), env = my_reactiveEnvironment)` inside a shiny app

**Comment by vnijs** [comment]
I'm still very curious if the idea of a reactive data.frame that can be addressed as `my_data` rather than `my_data()` or `my_reactive_values_list$my_data` is feasible. 

I just noticed `shiny::makeReactiveBinding` which seems like it may be what I'm looking for. If you have any better ideas please let me know. Else I'll explore if I can make `makeReactiveBinding` work in my apps.

**Comment by vnijs** [comment]
@jcheng5 Just saw [this post](https://groups.google.com/forum/#!topic/shiny-discuss/3HVsdJvZ8-Q) and want to check with you to make sure the `makeReactiveBinding` feature will to stay in shiny before I put in a good amount of time to convert several apps. If it works as I expect I think this will be *really* helpful and will allow me to remove and/or simplify a large amount of (wrapper) code. It would be nice to know, however, if there is a way to determine that the variable `a` in the example below is indeed reactive or where to look up its reactive status. 

```
library(shiny)
isolate({
  makeReactiveBinding("a")
  b <- reactive(a * -1)
  observe(print(b()))
  a <- 20
  print(is.reactive(b))
  print(is.reactive(a))
})

[1] TRUE
[1] FALSE
```

Joe Cheng quote from google group post mentioned above:

"The other possibility is a new feature introduced in Shiny 0.9 called "makeReactiveBinding"; just leave your code as it is in your email, and add the line "makeReactiveBinding(obj)" right before the declaration of obj. That will let you use obj as if it is a normal variable, but it's actually a reactive variable. I haven't decided if this is actually a good idea or not (as it's not obvious from looking at a read/write of this variable that anything out of the ordinary is going on), if you want you can give it a try and let me know whether it helps or hurts vs. the reactiveValues approach."

**Comment by jcheng5** [comment]
@vnijs The makeReactiveBinding feature should be considered stable. There's not a isReactiveBinding function but isActiveBinding might be close enough for your needs? There could potentially be false positives, I'm not sure what else uses active bindings. 

What cases do you have in mind for this? And have you seen reactiveVal, does that help at all?

**Comment by vnijs** [comment]
Thanks @jcheng5. `isActiveBinding` sounds useful but I can't find a reference to it using `?shiny::isActiveBinding` or even in https://github.com/rstudio/shiny for some reason. 

I have several shiny apps (e.g., radiant.data @ https://github.com/radiant-rstats) where the UI can generate R-code for the user. The code is put into a shinyAce editor (i.e., _Report > Rmd_) and can be (re)run inside the app. However, I also need the code to work as an Rmd in Rstudio after calling `library(radiant.data)`. In the app, data is assigned to `r_data` (a `reactiveValues`). If the generated code refers to `r_data$my_data`, for example, that will work in the app but outside the app it would work only if the user puts data in an `r_data` list as well. For example, 

`lm(y ~ x1 + x2 + vs, data = r_data[["user_data"]])`

will work fine inside the app but not conveniently outside the app. Right now many of my function take a string with the name of the dataset as input and then determine if the data should be accessed from `r_data` or else from another environment (e.g., .GlobalEnv). It works, but requires a good amount of wrapper code on my end. Based on initial testing it looks like `makeReactiveBinding` will be *really* helpful. Thanks!

That said, a `reactiveEnvironment` in `shiny` could also be a nice option. Anything created in or assigned to that environment would automatically become reactive. So very similar for `reactiveValues`. I'm using an environment (with shiny's environment as the parent env) as I'm trying out `makeReactiveBinding` and it seems to be working nicely. I do have some extra bookkeeping to do, however, to make sure new objects are registered as reactive ... which is where `reactiveEnvironment` might come in handy

**Comment by jcheng5** [comment]
I got the function name wrong, it's bindingIsActive and it's in base. Looks like it needs you to give it a symbol and an environment, so you might need to do some searching in environments if you're not sure where exactly the variable is coming from (let me know if you're not clear on what that means and I can try to explain or write a wrapper function).

**Comment by vnijs** [comment]
Got it. Thanks Joe! See code example below. I do have a wrapper function that will "register" a data.frame as reactive and add it to a datasets dropdown. Works well so far.

Question: Could `reactiveEnvironment` become an option in Shiny (i.e., as an alternative for `reactiveValues`) or is that unlikely?

```
load("data/superheroes.rda")
bindingIsActive(as.symbol("superheroes"), env = r_data)
[1] TRUE
makeReactiveBinding("superheroes", env = r_data)
bindingIsActive(as.symbol("superheroes"), env = r_data)
[1] TRUE
```

**Comment by vnijs** [comment]
So far converting my apps to use `makeReactiveBinding` seems to be going well @jcheng5 (see e.g., https://github.com/radiant-rstats/radiant.data/tree/MRB). 

Question: Is there a (simple) way to remove (all) reactive bindings created using `makeReactiveBinding`?  The code below works but it converts the environment I'm using to store all data to a list and then back to an environment which is perhaps a bit inefficient. 

`list2env(mget(ls(r_data), r_data))`

**Comment by vnijs** [comment]
I'll close this as `makeReactiveBinding` does exactly what I was looking for. I will refer to issue #2065. Thanks for your help @jcheng5
