### ISSUE TITLE
shiny app crashes on server pro without stack trace or error message

### ISSUE THREAD

**Issue by jcubic** [rstudio/shiny#1909]
We have medium size app using shiny R framework and we're using shiny server pro, and the app crashed after a while in random places, no info in logs just:

```
Execution halted
```

and some warnings that was always there (before that line), is there some trick to show real reason why we have this error? so we can know what's happening?

We use server pro with shiny for a while and everything was working fine, we have two apps, one for dev and one for test and I think, not sure, that it happen when we today deploy new version of the app on test, we always have latest version on dev that's deployed automatically on each commit (we use PRs so it happen on merge).

**Comment by jcubic** [comment]
It happen in Firefox and Chrome and we couldn't reproduce the issue on a Mac, looking at #155 we don't use proxy and the browser is using websockets for connection. no error in console. (sometimes it show not related error when it try to send message when websocket was destroyed after disconnection).

version:
```
Shiny Server (Commercial) v1.5.4.872
Node.js v6.10.3
```

**Comment by jcubic** [comment]
I've got this from websocket `c[3000, "No response from heartbeat"]`

**Comment by pyltime** [comment]
Hi Jakub, as a Pro customer can you file a support ticket with us at https://support.rstudio.com/hc/en-us/requests/new ?
