### ISSUE TITLE
Question about adjusting the position of two sidebar panels

### ISSUE THREAD

**Issue by HowardPu** [rstudio/shiny#1910]
May I know is there a way to display two sidebar panels vertically instead of horizontally. Specifically, how can I put a sidebar panel under a sidebar panel instead of putting second sidebar panel at the right of the  first sidebar panel?

**Comment by wch** [comment]
You might want to use `wellPanel`s for this.

This issue tracker is for bug reports and feature requests. For general help questions, please use https://community.rstudio.com/ and https://stackoverflow.com/.
