### ISSUE TITLE
eventReactive for group of elements nested in a div

### ISSUE THREAD

**Issue by yonicd** [rstudio/shiny#1912]
I am creating a div (wellPanel) that has objects being dynamically created by the user. then a plot is reacting to setting in that div.

I am trying to have the content that creates the plot be wrapped in a eventReactive conditional on any elements in the div

is it possible to have an eventReactive for all elements wrapped in a div?

any suggestions?

**Comment by bborgesr** [comment]
If you mean "is it possible to have an eventReactive for all elements wrapped in a div _using only one identifier [for the div]_?," then no. Otherwise, yes: see here for a discussion on that subject: https://groups.google.com/forum/#!topic/shiny-discuss/vd_nB-BH8sw

**Comment by bborgesr** [comment]
In your case, you have to keep track of the objects being dynamically created by the user, and refer back to them inside the `reactive`\`eventReactive`. it's not trivial, but possible. Here are two apps that had to overcome that issue for dynamic content:

- for dynamic content with `insertUI`: https://gist.github.com/bborgesr/48c4453bb83137815a53d8639b282fef
- for dynamic content with `appendTab`: https://gist.github.com/edgararuiz/89e771b5d1b82adaa0033c0928d1846d

**Comment by yonicd** [comment]
those are great references. 

My problem is on the hard no side for now, I thought that validations can propagate up through a nested reactive object.

I'll see how I can translate my problem to the not so trivial option.

thank you!

**Comment by yonicd** [comment]
follow up to same idea. if i have an identifier that is associated to all elements in the div is there a way to make reactiveEvent be conditional on a grep of inputs instead of known objects, ie `eventReactive('^(.*?)_AAA',{})`

**Comment by yonicd** [comment]
here something that works. 

```
shiny::eventReactive({
    lapply(grep('_GF$',names(input),value=TRUE),function(x) input[[x]])
    },{})
```

that be generalized to an eventgroupReactive, or allow in addition to inputId and inputGroupId and then people can reference it later in the script.

**Comment by wch** [comment]
I think the `lapply` is a good solution.
