### ISSUE TITLE
Optimize Selectize Performance for Character Vectors

### ISSUE THREAD

**Issue by colearendt** [rstudio/shiny#1918]
In the following `reprex`, server-side selectize is very slow for character vectors due largely to [`choicesWithNames`](https://github.com/rstudio/shiny/blob/e30fac02eddbb7cd510d448e385c559c82009a24/R/update-input.R#L670).  Second-biggest time hitter is the [`apply`](https://github.com/rstudio/shiny/blob/e30fac02eddbb7cd510d448e385c559c82009a24/R/update-input.R#L685) after finding indices.

If there is a way to optimize this performance, that would be great!

profvis:
![image](https://user-images.githubusercontent.com/23075542/34623830-d13ca99c-f220-11e7-98fa-e2c611c2643d.png)

reprex:
```r
library(shiny)

myFun <- function(n) {
  a <- do.call(paste0, replicate(5, sample(LETTERS, n, TRUE), FALSE))
  paste0(a, sprintf("%04d", sample(9999, n, TRUE)), sample(LETTERS, n, TRUE))
}

# generate choices
select_choices <- myFun(n = 2 * 1e+6)

ui <- fluidPage(
  mainPanel(
    selectizeInput('test', 'Input Item', choices = NULL),
    verbatimTextOutput('selector_output')
  )
)

server <- function(input, output, session) {
  updateSelectizeInput(session, 'test'
                       , choices = select_choices
                       , server = TRUE
                       , options = list(
                         maxOptions = 100
                       )
  )
  output$selector_output = renderText({
    paste('selector input:',input$test)
  })
}

profvis::profvis({runApp(shinyApp(ui, server, options = c("display.mode"="normal")))})
```

**Comment by jcheng5** [comment]
My thought was that choicesWithNames could detect the simple cases (vectors) and short-circuit, rather than normalizing everything to a list first.

**Comment by wch** [comment]
I believe this is the same as #1859 and #1861. I think there were just a couple small things that were remaining on the PR.

**Comment by jcheng5** [comment]
Cool, closing as dupe then.
