### ISSUE TITLE
Feature Request: buttonGrid

### ISSUE THREAD

**Issue by charliejhadley** [rstudio/shiny#1919]
A common feature of a Shiny app is to have a set of grouped buttons, for instance the CFL app here: https://daattali.com/shiny/cfl/

- There's a (single) column of buttons
- Clicking on a button changes the state of a variable via `Shiny.onInputChange` in `www/main.js` 

```JS
$( "#welcome_list" ).on( "click", ".welcome_row", function(x){
    Shiny.onInputChange("gamerowclick", $(this).data("gameinfo"));
  });
```
- The selected button from the group modifies the state of the app

A useful feature for `shiny` would be to group buttons together by a master input variable, and for each button in the group to have a unique id, as follows:

- Master id: input$button.master.id
- Unique button id: input$button.master.id_button.id

Please note I initially suggested this as a feature for `shinyjs` https://github.com/daattali/shinyjs/issues/151 but @daattali suggested it didn't fit there but might be a reasonable thing to suggest to add to `shiny` 

# Quasi Example

```r
the_ui <- fluidPage(
  shinyjs::useShinyjs(),
  div(id = "select_game_page",
      buttonGrid(
        button.master.id = "gameid",
        button.contents = list(
          gridButton(
            button.id = "game004",
            button.text = "UK vs US"
          ),
          gridButton(
            button.id = "game006",
            button.text = "DE vs FR"
          )
        ),
        columns = 2
      )),
  
  hidden(div(id = "game_info_page",
             fluidPage(
               datatableOutput("game_info"),
               actionButton("select_another_game",
                            "Select Another Game")
             )))
  
  
)

the_server <- function(input, output){
  
  output$game_info <- renderDataTable({
    
    shinyjs::hide("select_game_page")
    shinyjs::show("game_info_page")
    
    game_data %>%
      filter(game.id == input$gameid) %>%
      datatable()
    
  })
  
  observeEvent(input$select_another_game,
               {
                 shinyjs::hide("game_info_page")
                 shinyjs::show("select_game_page")
               })
  
}

shinyApp(the_ui, the_server)
```

**Comment by nteetor** [comment]
@martinjhnhadley, if you had a moment, I am curious to know if dull's [buttonGroupInput](https://github.com/nteetor/dull/blob/master/R/button.R#L279) is similar to what you have in mind.

**Comment by martinjhnhadley** [comment]
@nteetor that's a really nice feature of dull! That's very much the kind of functionality that I was looking for with this feature request. I think it would make sense to have something like this available directly in Shiny or else extract your `buttonGroupInput` into its own tiny package.

**Comment by nteetor** [comment]
Breaking out pieces of dull into their own small packages is a slippery slope I would like to avoid. However, I can put together a PR adding a `buttonGroup` to Shiny. For a few reasons the PR is not a simple copy and paste.

**Comment by jcheng5** [comment]
@martinjhnhadley Is there a reason you can't just use dull?

**Comment by martinjhnhadley** [comment]
@jcheng5 I could use this functionality from dull directly for my own purposes but I'm currently designing a lot of template shiny apps for folks at University of Oxford and want to reduce the dependency list as much as possible. As dull feels like a re-imagining of shiny I'd prefer not to direct new users towards it.

**Comment by nteetor** [comment]
Unfortunately, using a single function from dull may prove difficult. dull depends on and includes bootstrap 4. Thus, if a bootstrap class changed or was removed between bootstrap 3 and 4 one's UI might not look as expected. Additionally, there are likely breaking javascript changes between versions 3 and 4.

**Comment by charliejhadley** [comment]
I'm closing this issue as I now agree using a single function for this is unwise.
