### ISSUE TITLE
How does shiny render plot?

### ISSUE THREAD

**Issue by Takkoona** [rstudio/shiny#1920]
Hi,

I'm sort of doing a web project using another web framework but it does involve ggplot2 (not exactly, ggtree actually). I once had an experience using shiny and one thing I just found so great and peculiar is that shiny doesn't need to save the plot as file to render (or does it?). The best I can do in my case is save the plot and give it an uuid and then do the rendering. I tried put the final 'p' variable in an html placeholder but all it does is open an R graphic device to show the plot :( 

I really want to know how you guys manage to embed the plot directly in html (too lazy to read through the codes...). Please help.

Thank you in advance.

**Comment by wch** [comment]
The image is base64 encoded on the server and sent to the client, which then puts it in the img tag as a data URI. This page has some information on data URIs:
https://www.abeautifulsite.net/convert-an-image-to-a-data-uri-with-your-browser

**Comment by Takkoona** [comment]
Wow. That is so cool. You are my hero.
