### ISSUE TITLE
Warning: partial match of 'y' to 'yintercept'

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#1922]
This can happen when partial argument match warnings are enabled:

```R
options(
  warnPartialMatchArgs = TRUE,
  warnPartialMatchAttr = TRUE,
  warnPartialMatchDollar = TRUE
)
```

Example app:

```R
shinyApp(
  ui = fluidPage(
    plotOutput("plot")
  ),
  server = function(input, output) {
    output$plot <- renderPlot({
      ggplot(mtcars) + 
        geom_hline(yintercept = 20) +
        geom_point(aes(wt, mpg))
    })
  }
)
```

It prints out this warning:

```R
Warning: partial match of 'y' to 'yintercept'
```

I've also seen the following in another app:

```R
Warning in m$y : partial match of 'y' to 'yintercept'
```

For the latter message, these lines are probably involved:
  https://github.com/rstudio/shiny/blob/cad20a0b/R/render-plot.R#L726-L727

**Comment by jcheng5** [comment]
That seems *really* dangerous! `y` and `yintercept` seem pretty unlikely to mean the same thing, no?
