### ISSUE TITLE
Unable to load shared object. invalid ELF header.

### ISSUE THREAD

**Issue by peleonard** [rstudio/shiny#1924]
I created a simple shinyApp, using a R package written by me.  This packages depends on Rcpp.
Everything works well locally. But when I deploy it, I get this error. 

![image](https://user-images.githubusercontent.com/25212734/35120507-f53a1a86-fc5d-11e7-8994-097efca8469f.png)

**Comment by peleonard** [comment]
Could you give me some pointer to solve this issue

**Comment by shrektan** [comment]
I don’t think it’s related to shiny. I see your github repo and you have pushed the compiled objects to git. You may delete them and try again.

**Comment by shrektan** [comment]
devtools::clean_dll() may help

**Comment by wch** [comment]
I agree, the problem is probably that you committed compiled objects (like the .so files) to your repository.

**Comment by peleonard** [comment]
@wch @shrektan I really appreciate it. I am Cpp fresher. Finally I make it.

**Comment by shrektan** [comment]
@peleonard remember to close the issue if it works... thanks.
