### ISSUE TITLE
temporarily disable focus on modaldialog

### ISSUE THREAD

**Issue by madmark81** [rstudio/shiny#1925]
I have been struggling with an issue concerning the forced focus on modal dialogs,

in my modal dialog i'm trying to call another popup (sweetalert) that has an input field, but the user can't use it as long as the modaldialog claims the focus. The input field in the message is not clickable. 
Would you know a work around to temporarily shift focus to the other popup? 
I have posted a working example here: 

https://stackoverflow.com/questions/48249608/focus-on-text-input-field-in-sweetalert-combined-with-modaldialog-in-r/48321162#48321162

would much appreciate any input from you! 

cheers and thanks for any help, 

Mark

**Comment by jcheng5** [comment]
Sorry for the delay. Seems like you figured it out?

**Comment by madmark81** [comment]
Yes I have. I understand you're a very busy man with the R core and shiny work! thanks
Perhaps if you have the chance, I could use some help on an SO issue concerning observeEvents where ignoreInit = T doesn't seem to work when they are created together with dynamically rendered UI elements. 
https://stackoverflow.com/questions/50135834/observers-fire-on-render-of-dynamic-ui-when-they-should-not
