### ISSUE TITLE
shiny googlecloud "Disconnected from the server. Reload"

### ISSUE THREAD

**Issue by dujm** [rstudio/shiny#1929]
Hello, 
my shiny app is running on the googlecloud. But whenever I want to click a Shiny button, like "Submit", the app is disconnected form the server. What could be the reasons?

a. I tried VM instances with high memory, however, the problem remains. 
b. Some people say it's java issue, but I don't have java code in my app.R file.

<img width="323" alt="screen shot 2018-01-23 at 12 56 37" src="https://user-images.githubusercontent.com/30461000/35275531-6573549e-0040-11e8-9635-64cb64196b28.png">

**Comment by dujm** [comment]
The app runs nicely on my local mac.

**Comment by jcheng5** [comment]
Sorry for the delay. Have you looked at the application log files?
https://support.rstudio.com/hc/en-us/articles/115003717168-Shiny-Server-Error-Logs

**Comment by nathmenini** [comment]
Did you fix it? I'm getting the same error, but in my case, I'm trying to get some infos from Google Earth Engine API. Maybe (for me), it could be a timeout issue..

**Comment by dujm** [comment]
@nathmenini , hi there, yes, I solved it. In my case, it was a problem with a package devtools. So I just reinstalled it. 

If you have a API json key, also check whether it's in your app directory.
