### ISSUE TITLE
DOM not updated with selectInput(selective = FALSE) added with insertUI()

### ISSUE THREAD

**Issue by timothy-thomas** [rstudio/shiny#1931]
I have a large app that implements a dynamic UI. Given the need to update only a single element at a time, I moved away from using `renderUI()` and was able to use the `insertUI()` function to successfully add/remove the UI elements needed for the project.

They work as expected with a small caveat: the DOM is not updated to reflect the selected elements as they are with renderUI(), i.e. the `selected` attribute is never added to the `option` elements. Is this by design or a bug? In short, the elements are always created and operate as expected, but my testing code is no longer able to determine the value of a selection as the DOM is left unchanged.

Please inspect the DOM in the following app after a `selectInput()` and `verbatimTextOutput()` pair has been added and some selections have been made.

```
library(shiny)

# Code license: MIT
# Using selectInput(selectize = FALSE) with insertUI()
# by Tim Thomas
# adapated from work by Bárbara Borges

ui <- fluidPage( 
  actionButton('insertBtn', 'Insert'), 
  actionButton('removeBtn', 'Remove'), 
  tags$div(id = 'placeholder') 
)

server <- function(input, output) {
  
  ids <- c()
  
  observeEvent(input$insertBtn, {
    id <- paste0(input$insertBtn)
    ids <<- c(id, ids)
    div_id <- paste0("div_", id)
    select_id <- paste0("select_", id)
    output_id <- paste0("output_", id)
    choices <- lapply(1:4, function(x) {paste("Choice", x)})
    insertUI(
      selector = '#placeholder',
      ui = tags$div(
        id = div_id,
        selectInput(select_id,
                    select_id,
                    choices,
                    multiple = TRUE,
                    selectize = FALSE),
        verbatimTextOutput(output_id)
      )
    )
    output[[output_id]] <- renderText(input[[select_id]])
  })
  
  observeEvent(input$removeBtn, {
    removeUI(
      selector = paste0('#div_', ids[length(ids)])
    )
    ids <<- ids[-length(ids)]
  })
}

shinyApp(ui, server)
```

I first submitted this as a [topic](https://community.rstudio.com/t/dom-not-updated-with-selectinput-selective-false-added-with-insertui/4469) on community.rstudio.com. Let me know if this needs to be removed in favor of tracking it here.

**Comment by bborgesr** [comment]
We looked into this. Using `selectInput(selectize = FALSE)` _never_ adds the `selected` attribute to the DOM `option` tag when that option is selected. This happens even without using dynamic ui (e.g. `ui <- fluidPage(selectInput("slc", "Select input", choices, selectize = FALSE))`). So the behavior of  `selectInput(selectize = FALSE)` is consistent for static and dynamic ui versions.

If you really want the DOM to change upon a new option selection, you could use  `selectInput(selectize = TRUE)` (the default) since that does update the DOM every time, either in static or dynamic ui.

**Comment by timothy-thomas** [comment]
I thought I had an example where I was using the `selected` attribute of the option tag to drive the UI with Selenium in the past. I will try to dig up that example and post it here if I can track it down. Thank you for the investigation.
