### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 ()

### ISSUE THREAD

**Issue by UOTLeop** [rstudio/shiny#1934]
When I run the application on the local machine, the project works perfectly. However, when I try to deploy it to the shiny app.io. I just get the error message shown in the title without further explanation.
I can make sure that all the packages have been updated and there is no View function in my project. Could you please give me a hint for how to resolve this?

**Comment by cderv** [comment]
just to cross reference issues as this one has been open twice in two different repositories.
So there is a duplicate in rstudio/rsconnect#243

@UOTLeop, just so you know, as you have more a question / issue than a bug to report, https://community.rstudio.com could be a better place to ask and you could get some help quicker.
