### ISSUE TITLE
add md() convenience function to write fragments in markdown

### ISSUE THREAD

**Issue by maxheld83** [rstudio/shiny#1936]
I'm so used to writing in basic markdown (*emph*, **bold**, `pre` etc.), I can't get myself to write, say `shiny::tags$em("foo")`.
Maybe others are feeling the same.

I build myself a simple wrapper to be able to easily write markdown:

```
#' @title Convert markdown to html
#'
#' @param text A character vector to be converted to markdown.
#'
#' @param HTML A logical flag, indicating whether the result should additionally be wrapped in shiny::HTML().
#'
#' @noRd
md <- function(text, HTML = TRUE) {
  res <- markdown::renderMarkdown(
    file = NULL,
    output = NULL,
    text = text
  )
  if (HTML) {
    res <- shiny::HTML(text = res)
  }
  return(res)
}
```

which can be used wherever shiny expects HTML.

Now I can write something like:

```
fileInput(
  inputId = "rdata",
  label = md("Upload a `*.rdata` file created by *pensieve*."),
)
```
which makes life a little easier.

Is there any interest in supporting this directly in shiny? I'm guessing an `md()` function might be an alternative to / modelled on the existing `HTML()`.

If there's interest, I'd be happy to write up a PR.

---

Just to be sure, what this isn't:
- this is not about including external files, `shiny::includeMarkdown()` does that already,
- this is strictly about *Markdown*, **not** RMarkdown.

**Comment by jcheng5** [comment]
Sorry for the delay. I think this belongs in https://github.com/rstudio/htmltools instead--if you submit a PR there, we'd take it.

Thanks!

**Comment by maxheld83** [comment]
migrated to https://github.com/rstudio/htmltools/issues/94
Will do a PR there as suggested.
