### ISSUE TITLE
Performance issue with long selectizeInput choices inside modal

### ISSUE THREAD

**Issue by iutomo** [rstudio/shiny#1937]
I have a large vector (~41000 elements) that I want to use as choices for a selectizeInput inside a modal. It takes ~1 minute for the modal to be generated which at that point, Chrome consider the page to be unresponsive and suggested to kill it. The same vector is used in another selectizeInput inside ui.R and there is no performance hit on that. 

I am running this on R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux stretch/sid
shiny_1.0.5

**Comment by wch** [comment]
Have you tried the development version of shiny? We recently merged a change (#1861) which should dramatically speed up server-side selectizeinput.
