### ISSUE TITLE
Adding 'box-shadow' to plots created in a Shiny app

### ISSUE THREAD

**Issue by lxwrght** [rstudio/shiny#1940]
Has anyone tried to use box-shadow (CSS) to add a shadow around a ggplot created in a Shinyapp?

**I've tried:**

## Outside UI
plotCSS <- "
.box{
box-shadow: 10x 10x grey
}
"

## Inside UI
tags$style(plotCSS),

**Comment by DarioS** [comment]
Your size setting isn't valid CSS syntax. `10x` is not a [possible value](https://www.w3schools.com/CSSref/css_units.asp), but instead you should use `px`. For example, `box-shadow: 10px 10px grey;` Also, you are applying the style to class `box` but shiny plots don't have that class. You should apply it to `shiny-plot-output` instead. Finally, I would not recommend putting CSS into your ui.R. Create an ordinary CSS file and import the style rules into your application by using the `includeCSS` function in `ui.R`.

**Comment by lxwrght** [comment]
Hi @DarioS,

Thanks! Your comments helped me resolve this issue. 

I really do appreciate you taking the time to help me,
Alex
