### ISSUE TITLE
selectInput does not hold in shiny module

### ISSUE THREAD

**Issue by xsswang** [rstudio/shiny#1944]
In modulizing a shiny app, I came across a problem which can be demonstrated by the following code. The app runs OK. The only issue is that, when select a new name under "name to analyze" passing through selectInput, updated result does not hold. The result for the new selected name will flash over and automatically return back to default 'name1' within seconds. Debugging does not show any clue about the reason. Much appreciated if any suggestion.

  subgroupInput <- function(id){
  
    ns <-NS(id)
    tagList(
      selectInput(ns("name"), 
                  label = "name to analyze",
                  choices = NULL,selected=NULL),
      
      radioButtons(ns('radio'), 'cutoffType', choices=c('percentile', 'value'), 
                   selected = NULL, inline = FALSE),
      
      conditionalPanel(
        condition = paste0("input['", ns("radio"), "'] == 'percentile'"), 
        sliderInput(ns("cutoff1"), 
                    label = "Bottom-trim percentile:",
                    min = 0, max = 100, value = 5),
        
        sliderInput(ns("cutoff2"), 
                    label = "Top-trim percentile:",
                    min = 0, max = 100, value = 95)
        
      ),
      conditionalPanel(
        condition = paste0("input['", ns("radio"), "'] == 'value'"), 
        sliderInput(ns("cutoff3"), 
                    label = "Bottom-trim value:",
                    min = 0, max = 100, value = -1),
        sliderInput(ns("cutoff4"), 
                    label = "Top-trim value:",
                    min = 0, max = 100, value = 1)
      )
      )
      }
  
     subgroup <- function(input, output, session,default_selected=NULL){
  
     ns=session$ns
  
     model <- reactive({
    
    data = data.frame(matrix(rep(rnorm(100*100,sd=3)),ncol=100),stringsAsFactors = F)
    colnames(data)=paste0('name',1:100)
    
    namelist = colnames(data)    
    updateSelectInput(session, "name",choices = namelist, selected = default_selected)
    
    validate(
      shiny::need(input$name,"Select name")
    )
    
    x = round(data[,input$name])
    updateSliderInput(session, "cutoff3", label="Cufoff value", min=min(x),max=max(x))
    updateSliderInput(session, "cutoff4", label="Cufoff value", min=min(x),max=max(x))
    
    
    if(input$radio=="percentile") {
        dt = data[,input$name]
        qt = quantile(dt,c(input$cutoff1,input$cutoff2)/100)
        result <- hist(dt[dt>qt[1] & dt<=qt[2]],main=paste0("Histogram of ",input$name))
      } 
    else if(input$radio=="value"){
        dt = data[,input$name]
        result <- hist(dt[dt>input$cutoff3 & dt<=input$cutoff4],main=paste0("Histogram of ",input$name))
      }
    
    return(list(plot = result, data = data, inname=input$name))
    })  
  
    return (model)
    }
  
  
     shinyApp(
       ui = fluidPage(
        subgroupInput("test1"),
        plotOutput("plot")
        ),
       server = function(input, output, session){
    
        test <- shiny::callModule(subgroup,"test1")
  
        output$plot <- renderPlot({
         test()$plot
        })
       }
      )

**Comment by daattali** [comment]
@xsswang it may help anyone else trying to reproduce the problem and debugging it if you could come up with more minimal code that reproduces the problem with as little extra code as possible

**Comment by jcheng5** [comment]
These lines:

```r
    data = data.frame(matrix(rep(rnorm(100*100,sd=3)),ncol=100),stringsAsFactors = F)
    colnames(data)=paste0('name',1:100)
    
    namelist = colnames(data)    
    updateSelectInput(session, "name",choices = namelist, selected = default_selected)
```

don't belong inside the `model` reactive. Move them outside the reactive, but still within the module function, and you should see it working correctly.
