### ISSUE TITLE
Validation errors in futures aren't treated as errors

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#1949]
Shiny raises errors with custom subclasses in order to trigger custom UI behavior. For example, a very common/useful feature of Shiny is the [`req` function](https://shiny.rstudio.com/articles/req.html), which you use to conditionally raise a "silent" error--instead of a red error message in the UI, you get silence, which is often what you want (for example, the user hasn't selected a dataset yet, instead of `Error: No applicable method for `filter_` applied to an object of class "NULL"` you just want nothing.

```r
> library(shiny)
> te <- try(req(FALSE), silent = TRUE)
> class(attr(te, "condition"))
[1] "shiny.silent.error" "validation"         "error"              "condition"         
```

But when used with multicore/multisession futures, error subclasses don't work correctly with `value(..., signal = TRUE)`. These fail in two different ways. With multicore, `value()` returns a try-error instead of signaling:

```r
> library(shiny)
> library(future)
> plan(multicore)

> f1 <- future({ stop("boom") })
> value(f1)  # Throws error (correct)
Error: boom

> f2 <- future({ validate(need(FALSE, "Validation error")) })
> value(f2)  # Returns try-error (incorrect)
[1] "Error : \n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<shiny.silent.error: >
```

And with multisession, it's signaled, but it's become a `simpleError`:

```r
> plan(multisession)
> f3 <- future({ validate(need(FALSE, "Validation error")) })
> value(f3)  # Works...?
Error : Validation error
> cond <- attr(try(value(f3), silent = TRUE), "condition")
> class(cond)  # But actually the classes are gone
[1] "FutureEvaluationError"     "FutureError"               "simpleError"              
[4] "error"                     "FutureEvaluationCondition" "condition" 
```

@HenrikBengtsson At first I thought this was a simple matter of fixing up the corresponding `value` methods for these two future types, but it occurred to me that you might've done this on purpose--like it might not be safe to serialize errors across process boundaries or something? Would love to hear your thoughts. It would be hard to ship the next version of Shiny without having a resolution to this problem.

**Comment by HenrikBengtsson** [comment]
Thanks, it looks like a bug on my end; [`value()` for multicore looks for `simpleError` rather than just `error`](https://github.com/HenrikBengtsson/future/blob/master/R/MulticoreFuture-class.R#L141-L144);
```r
    condition <- attr(res, "condition")
    if (inherits(condition, "simpleError")) {
        future$state <- "failed"
        future$value <- condition
    }
```

Roughly, how soon do you need this fix to be on CRAN?

**Comment by jcheng5** [comment]
Thanks for looking into this. We don't have a date targeted yet, but I imagine it'll be about a month before we want to submit. If you can even get this on future's GitHub master in the next couple of weeks that would be a big help.

**Comment by HenrikBengtsson** [comment]
Ok.  FYI, my `master` branch == CRAN; the fix will go in the `develop` branch.
