### ISSUE TITLE
Using sliderinput output as sliderinput value

### ISSUE THREAD

**Issue by kiavashfayyaz** [rstudio/shiny#1957]
Hi,

I can't figure out how to this in shiny:
I have several variables (a, b, c) that user can select between them (lets say using selectinput). I have one sliderinput that determines the weights of this variables. So, if variable "a" is selected the sliderinput value will be assigned to this variable as weight. No problem so far. The problem rises when I change my selected variable (lets say to variable "b") and I want to update the initial value the sliderinput shows to be the weight of variable "b" (and not the last weight which is variable "a"). I tried many ways couldn't get my head around it. The code in the bottom generate a looping event.

shinyUI(fluidPage(

      selectInput("SelectIndicator", "Select Indicator", choices = c("a", "b", "c"),

      sliderInput('SelectIndicatorWeight', 'Select Indicator Weight',
                  min=1, max=4, value= weight_holder[,1], # initial value
                  step=1, round=0))

shinyServer(function(input, output, session) {
observe({
      indic_selected <- input$SelectIndicator
      x <- which(colnames(weight_holder) == indic_selected)
      updatesliderinput(session, "SelectIndicator", value = weight_holder[,x]
      weight_holder[,x] <- input$SelectIndicatorWeight
})
})

Thanks!

**Comment by wch** [comment]
Hi, this issue tracker is for bug reports and feature requests. For general help, please use https://community.rstudio.com/ or https://stackoverflow.com/ .
