### ISSUE TITLE
SelectInput loading slow 60000 items

### ISSUE THREAD

**Issue by Jemkon** [rstudio/shiny#1963]
Hi,
I am using development version of shiny 1.0.5.9000. I have 60000 items in my selectInput and its extremely slow.

Here is the code:
sever.R
      
        output$choose_Genes <- reactiveUI(function() {
    
        #selectInput(inputId = "Genes", label = "Genes of interest", multiple = TRUE, choices = c("Select Gene", as.list(GeneNames))
        selectizeInput(inputId = "Genes", label = "Genes of interest", multiple = TRUE, choices = c("Select Gene", as.list(GeneNames)),
          options = list(maxOptions = 100))                          
        })

ui.R

        uiOutput("choose_Genes")

The GeneNames is the list of 60000 genes. I have also used selectizeInput but still very slow. 

Any idea How I can improve the loading time.

Many thanks.

**Comment by jcheng5** [comment]
See the section on server-side selectize here: https://shiny.rstudio.com/articles/selectize.html

**Comment by Jemkon** [comment]
Thanks jcheng5. I have changed the code according to the server-side selectize. But i got following error.

Error in .getReactiveEnvironment()$currentContext() : 
  Operation not allowed without an active reactive context. (You tried to do something that can only be done from inside a reactive expression or observer.)

Do I need to put updateSelectizeInput(session, 'Genes', choices = c('Select Gene', as.list(GeneNames)), server=TRUE) into observe function?

I have placed it in server function.

Thanks.

**Comment by wch** [comment]
Yes, you need to put `updateSelectizeInput()` in an `observe()`.

**Comment by Jemkon** [comment]
Hi wch,
Not working. still got the same error. If I put it in observe function then I dont get error but the selectizeInput is empty.

ui.R

        uiOutput("selectGenes")

server.R

        server <- function(input, output, session) {
                updateSelectizeInput(session, 'Genes', choices = c('Select Gene', as.list(GeneNames)), server=TRUE)

               output[["selectGenes"]] <- renderUI({
                         selectizeInput(inputId = "Genes", label = "Genes of interest", choices = NULL)
                   })
            }

Anything wrong with the code?

Many thanks.

**Comment by wch** [comment]
The problem is that the `updateSelectizeInput` runs as soon as the app starts, before the `selectizeInput` is rendered on the page (because it is rendered with `renderUI`). If `selectizeInput` were directly in the UI (that is, not with `renderUI`), then it would work without putting `updateSelectizeInput` in `observe()`
