### ISSUE TITLE
is it practical to use renderplot or renderdatatable with showModal & modalDialog ?

### ISSUE THREAD

**Issue by jz1584** [rstudio/shiny#1970]
I am working on rendering  datatable and plots on modal dialog, and it works so far. I am just wondering if there is any potential limitation on putting datatable or plots on modal dialog. 
Thanks,

**Comment by wch** [comment]
There shouldn't be any problems using those in a modal dialog.

**Comment by jz1584** [comment]
Great, Thanks !
