### ISSUE TITLE
httpuv braks shiny installation

### ISSUE THREAD

**Issue by ivlachos** [rstudio/shiny#1971]
Hi,
I tried many different ways to install shiny or httpuv separately / together.
The system is a Centos 7 with R 3.4.3. It's a development node, with dozens of packages already installed.

The same error is returned regardless of the process used to install httpuv (git, with shiny, solo, etc).

I updated / removed system-wide installation of libuv, in case it intefered with the package but without any luck.

Any ideas?

```
> install.packages("httpuv")
Installing package into ?/home/iv/R/x86_64-redhat-linux-gnu-library/3.4?
(as ?lib? is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/httpuv_1.3.6.2.tar.gz'
Content type 'application/x-gzip' length 427598 bytes (417 KB)
==================================================
downloaded 417 KB

* installing *source* package ?httpuv? ...
** package ?httpuv? successfully unpacked and MD5 sums checked
** libs
g++ -m64 -std=gnu++11 -I/usr/include/R -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/home/iv/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++11 -I/usr/include/R -DNDEBUG -I./libuv/include -I./http-parser -I./sha1 -I./base64 -I"/home/iv/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c filedatasource-unix.cpp -o filedatasource-unix.o
In file included from ./libuv/include/uv.h:67:0,
                 from uvutil.h:6,
                 from filedatasource.h:4,
                 from filedatasource-unix.cpp:3:
./libuv/include/uv-private/uv-unix.h:101:28: error: ?sem_t? does not name a type
 # define UV_PLATFORM_SEM_T sem_t
                            ^
./libuv/include/uv-private/uv-unix.h:132:9: note: in expansion of macro ?UV_PLATFORM_SEM_T?
 typedef UV_PLATFORM_SEM_T uv_sem_t;
         ^
In file included from uvutil.h:6:0,
                 from filedatasource.h:4,
                 from filedatasource-unix.cpp:3:
./libuv/include/uv.h:1893:27: error: ?uv_sem_t? was not declared in this scope
 UV_EXTERN int uv_sem_init(uv_sem_t* sem, unsigned int value);
                           ^
./libuv/include/uv.h:1893:37: error: ?sem? was not declared in this scope
 UV_EXTERN int uv_sem_init(uv_sem_t* sem, unsigned int value);
                                     ^
./libuv/include/uv.h:1893:42: error: expected primary-expression before ?unsigned?
 UV_EXTERN int uv_sem_init(uv_sem_t* sem, unsigned int value);
                                          ^
./libuv/include/uv.h:1893:60: error: expression list treated as compound expression in initializer [-fpermissive]
 UV_EXTERN int uv_sem_init(uv_sem_t* sem, unsigned int value);
                                                            ^
./libuv/include/uv.h:1894:31: error: variable or field ?uv_sem_destroy? declared void
 UV_EXTERN void uv_sem_destroy(uv_sem_t* sem);
                               ^
./libuv/include/uv.h:1894:31: error: ?uv_sem_t? was not declared in this scope
./libuv/include/uv.h:1894:41: error: ?sem? was not declared in this scope
 UV_EXTERN void uv_sem_destroy(uv_sem_t* sem);
                                         ^
./libuv/include/uv.h:1895:28: error: variable or field ?uv_sem_post? declared void
 UV_EXTERN void uv_sem_post(uv_sem_t* sem);
                            ^
./libuv/include/uv.h:1895:28: error: ?uv_sem_t? was not declared in this scope
./libuv/include/uv.h:1895:38: error: ?sem? was not declared in this scope
 UV_EXTERN void uv_sem_post(uv_sem_t* sem);
                                      ^
./libuv/include/uv.h:1896:28: error: variable or field ?uv_sem_wait? declared void
 UV_EXTERN void uv_sem_wait(uv_sem_t* sem);
                            ^
./libuv/include/uv.h:1896:28: error: ?uv_sem_t? was not declared in this scope
./libuv/include/uv.h:1896:38: error: ?sem? was not declared in this scope
 UV_EXTERN void uv_sem_wait(uv_sem_t* sem);
                                      ^
./libuv/include/uv.h:1897:30: error: ?uv_sem_t? was not declared in this scope
 UV_EXTERN int uv_sem_trywait(uv_sem_t* sem);
                              ^
./libuv/include/uv.h:1897:40: error: ?sem? was not declared in this scope
 UV_EXTERN int uv_sem_trywait(uv_sem_t* sem);
                                        ^
make: *** [filedatasource-unix.o] Error 1
ERROR: compilation failed for package ?httpuv?
* removing ?/home/iv/R/x86_64-redhat-linux-gnu-library/3.4/httpuv?
Warning in install.packages :
  installation of package ?httpuv? had non-zero exit status```

**Comment by wch** [comment]
This appears to be the same as rstudio/httpuv#110. Can you try installing some other versions of httpuv and include the full output? You'll need the devtools package installed to do this.

```
# Old version from CRAN
devtools::install_version("httpuv", "1.3.5")
```

```
# Current development version from github
devtools::install_github("rstudio/httpuv")
```

Please post the results in the httpuv issue I linked to above and we can continue the discussion there.

**Comment by YvonneJemutai** [comment]
Hello.am getting this error everytime i install rshiny


install.packages("shiny") Installing package into ‘/home/rstudio2/R/x86_64-pc-linux-gnu-library/3.2’ (as ‘lib’ is unspecified) --2019-05-02 18:00:02--  https://cran.rstudio.com/src/contrib/shiny_1.3.2.tar.gz Resolving cran.rstudio.com (cran.rstudio.com)... 13.249.44.72, 13.249.44.107, 13.249.44.31, ... Connecting to cran.rstudio.com (cran.rstudio.com)\|13.249.44.72\|:443... connected. HTTP request sent, awaiting response... 200 OK Length: 2991469 (2.9M) [application/x-gzip] Saving to: ‘/tmp/RtmpC6UwM9/downloaded_packages/shiny_1.3.2.tar.gz’       0K .......... .......... .......... .......... ..........  1% 18.4M 0s     50K .......... .......... .......... .......... ..........  3%  113M 0s    100K .......... .......... .......... .......... ..........  5% 81.7M 0s    150K .......... .......... .......... .......... ..........  6% 49.1M 0s    200K .......... .......... .......... .......... ..........  8% 31.5M 0s    250K .......... .......... .......... .......... .......... 10%  350M 0s    300K .......... .......... .......... .......... .......... 11%  291M 0s    350K .......... .......... .......... .......... .......... 13% 47.4M 0s    400K .......... .......... .......... .......... .......... 15%  222M 0s    450K .......... .......... .......... .......... .......... 17%  383M 0s    500K .......... .......... .......... .......... .......... 18% 58.0M 0s    550K .......... .......... .......... .......... .......... 20%  197M 0s    600K .......... .......... .......... .......... .......... 22% 17.7M 0s    650K .......... .......... .......... .......... .......... 23%  349M 0s    700K .......... .......... .......... .......... .......... 25%  351M 0s    750K .......... .......... .......... .......... .......... 27%  234M 0s    800K .......... .......... .......... .......... .......... 29%  289M 0s    850K .......... .......... .......... .......... .......... 30% 28.8M 0s    900K .......... .......... .......... .......... .......... 32%  341M 0s    950K .......... .......... .......... .......... .......... 34%  214M 0s   1000K .......... .......... .......... .......... .......... 35%  354M 0s   1050K .......... .......... .......... .......... .......... 37%  261M 0s   1100K .......... .......... .......... .......... .......... 39%  379M 0s   1150K .......... .......... .......... .......... .......... 41%  210M 0s   1200K .......... .......... .......... .......... .......... 42%  296M 0s   1250K .......... .......... .......... .......... .......... 44%  358M 0s   1300K .......... .......... .......... .......... .......... 46%  380M 0s   1350K .......... .......... .......... .......... .......... 47%  231M 0s   1400K .......... .......... .......... .......... .......... 49%  369M 0s   1450K .......... .......... .......... .......... .......... 51% 17.8M 0s   1500K .......... .......... .......... .......... .......... 53% 78.4M 0s   1550K .......... .......... .......... .......... .......... 54%  211M 0s   1600K .......... .......... .......... .......... .......... 56%  256M 0s   1650K .......... .......... .......... .......... .......... 58%  358M 0s   1700K .......... .......... .......... .......... .......... 59%  341M 0s   1750K .......... .......... .......... .......... .......... 61% 12.4M 0s   1800K .......... .......... .......... .......... .......... 63%  325M 0s   1850K .......... .......... .......... .......... .......... 65%  220M 0s   1900K .......... .......... .......... .......... .......... 66% 78.4M 0s   1950K .......... .......... .......... .......... .......... 68%  110M 0s   2000K .......... .......... .......... .......... .......... 70%  363M 0s   2050K .......... .......... .......... .......... .......... 71%  138M 0s   2100K .......... .......... .......... .......... .......... 73%  345M 0s   2150K .......... .......... .......... .......... .......... 75%  330M 0s   2200K .......... .......... .......... .......... .......... 77%  196M 0s   2250K .......... .......... .......... .......... .......... 78%  345M 0s   2300K .......... .......... .......... .......... .......... 80%  249M 0s   2350K .......... .......... .......... .......... .......... 82%  307M 0s   2400K .......... .......... .......... .......... .......... 83%  392M 0s   2450K .......... .......... .......... .......... .......... 85%  227M 0s   2500K .......... .......... .......... .......... .......... 87%  275M 0s   2550K .......... .......... .......... .......... .......... 88%  261M 0s   2600K .......... .......... .......... .......... .......... 90%  298M 0s   2650K .......... .......... .......... .......... .......... 92%  236M 0s   2700K .......... .......... .......... .......... .......... 94%  295M 0s   2750K .......... .......... .......... .......... .......... 95%  303M 0s   2800K .......... .......... .......... .......... .......... 97%  371M 0s   2850K .......... .......... .......... .......... .......... 99% 23.5M 0s   2900K .......... .......... .                               100% 16.5M=0.03s  2019-05-02 18:00:02 (89.8 MB/s) - ‘/tmp/RtmpC6UwM9/downloaded_packages/shiny_1.3.2.tar.gz’ saved [2991469/2991469]  * installing *source* package ‘shiny’ ... ** package ‘shiny’ successfully unpacked and MD5 sums checked ** R ** inst ** preparing package for lazy loading Warning: replacing previous import by ‘Rcpp::evalCpp’ when loading ‘later’ Warning: S3 methods ‘format.staticPath’, ‘format.staticPathOptions’, ‘print.staticPath’, ‘print.staticPathOptions’ were declared in NAMESPACE but not found Error in library.dynam(lib, package, package.lib) :    shared object ‘httpuv.so’ not found ERROR: lazy loading failed for package ‘shiny’ * removing ‘/home/rstudio2/R/x86_64-pc-linux-gnu-library/3.2/shiny’ Warning in install.packages :   installation of package ‘shiny’ had non-zero exit status  The downloaded source packages are in 	‘/tmp/RtmpC6UwM9/downloaded_packages’
--
 
> | >
>
