### ISSUE TITLE
shiny crashes R 3.4.4

### ISSUE THREAD

**Issue by SamoPP** [rstudio/shiny#1977]
This little app crashes R session in RStudio:
`binner<-function(var) {
	library(shiny)
 
	shinyApp(
		ui = fluidPage(
			 sidebarLayout(
				 sidebarPanel(sliderInput("n", "Bins", 5, 100, 20)),
				 mainPanel(plotOutput("hist"))
				 )
			 ), 
		server = function(input, output) {
			output$hist <- renderPlot( 
				hist(var, breaks = input$n,
				col = "skyblue", border = "white") 
				)
		}
	)	 
}
 
binner(faithful$eruptions)`

`R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(shiny)
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.0.5.9000

loaded via a namespace (and not attached):
 [1] compiler_3.4.4  R6_2.2.2        htmltools_0.3.6 tools_3.4.4     yaml_2.1.18     Rcpp_0.12.16    digest_0.6.15   xtable_1.8-2    httpuv_1.3.6.2 
[10] mime_0.5   `

**Comment by wch** [comment]
Can you provide the full output from your session?

Also, please provide the output of `devtools::session_info()` (after doing `library(shiny)`).

**Comment by SamoPP** [comment]
It crashes everywhere: RStudio, StatET and R in terminal. See below.

I believe it has to do something with R base graphics since when I do not use any base graphics/plots Shiny applications do not crash R...

In terminal:
$ R

R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.


Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(shiny)
> devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 os       Ubuntu 16.04.4 LTS          
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_US                       
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-03-20                  

─ Packages ───────────────────────────────────────────────────────────────────
 package     * version     date       source                         
 assertthat    0.2.0.9000  2017-04-29 local                          
 backports     1.1.2       2017-12-13 cran (@1.1.2)                  
 callr         2.0.2       2018-02-11 cran (@2.0.2)                  
 cli           1.0.0       2017-11-05 cran (@1.0.0)                  
 clisymbols    1.2.0       2017-05-21 cran (@1.2.0)                  
 crayon        1.3.4       2017-09-16 cran (@1.3.4)                  
 debugme       1.1.0       2017-10-22 cran (@1.1.0)                  
 desc          1.1.1       2017-08-03 cran (@1.1.1)                  
 devtools      1.13.5.9000 2018-03-17 Github (r-lib/devtools@61c0c41)
 digest        0.6.15      2018-01-28 CRAN (R 3.4.4)                 
 htmltools     0.3.6       2017-04-28 CRAN (R 3.4.4)                 
 httpuv        1.3.6.2     2018-03-02 CRAN (R 3.4.4)                 
 magrittr      1.5.0       2017-11-19 local                          
 memoise       1.1.0       2017-04-21 CRAN (R 3.4.0)                 
 mime          0.5         2016-07-07 CRAN (R 3.4.4)                 
 pkgbuild      0.0.0.9001  2018-03-17 Github (r-lib/pkgbuild@fd48c79)
 pkgload       1.0.0       2018-03-17 Github (r-lib/pkgload@0cd9f8d) 
 R6            2.2.2       2017-06-17 CRAN (R 3.4.4)                 
 Rcpp          0.12.16     2018-03-13 cran (@0.12.16)                
 rlang         0.2.0       2018-02-20 cran (@0.2.0)                  
 rprojroot     1.3-2       2018-01-03 cran (@1.3-2)                  
 sessioninfo   1.0.0       2017-06-21 cran (@1.0.0)                  
 shiny       * 1.0.5.9000  2018-03-17 local                          
 testthat      2.0.0       2017-12-13 cran (@2.0.0)                  
 usethis       1.3.0       2018-02-24 cran (@1.3.0)                  
 withr         2.1.2       2018-03-15 cran (@2.1.2)                  
 xtable        1.8-2       2016-02-05 CRAN (R 3.4.4)                 
> 
> binner<-function(var) {
+ library(shiny)
+ 
+ shinyApp(
+ ui = fluidPage(
+  sidebarLayout(
+  sidebarPanel(sliderInput("n", "Bins", 5, 100, 20)),
+  mainPanel(plotOutput("hist"))
+  )
+  ), 
+ server = function(input, output) {
+ output$hist <- renderPlot( 
+ hist(var, breaks = input$n,
+ col = "skyblue", border = "white") 
+ )
+ }
+ ) 
+ 
+ }
> 
> binner(faithful$eruptions)

Listening on http://127.0.0.1:3751

 *** caught segfault ***
address 0xbd, cause 'memory not mapped'

Traceback:
 1: .External("cairo_create_new_device", as.character(ctype), file,     width, height, pointsize, bg, canvas, umpl, dpi, ..., PACKAGE = "Cairo")
 2: Cairo(width, height, type = "png", file = filename, pointsize = pointsize,     bg = bg, res = res, ...)
 3: pngfun(filename = filename, width = width, height = height, res = res,     ...)
 4: startPNG(outfile, width * pixelratio, height * pixelratio, res = res *     pixelratio, ...)
 5: drawPlot(outputName, session, func, dims$width, dims$height,     pixelratio, res)
 6: force(expr)
 7: withVisible(force(expr))
 8: withCallingHandlers(expr, error = doCaptureStack)
 9: globals$domain$wrapSync(expr)
10: promises::with_promise_domain(createStackTracePromiseDomain(),     expr)
11: captureStackTraces({    result <- withVisible(force(expr))    if (promises::is.promising(result$value)) {        p <- promise_chain(setVisible(result), ..., catch = catch,             finally = finally)        runFinally <- FALSE        p    }    else {        result <- Reduce(function(v, func) {            if (".visible" %in% names(formals(func))) {                withVisible(func(v$value, .visible = v$visible))            }            else {                withVisible(func(v$value))            }        }, list(...), result)        setVisible(result)    }})
12: doTryCatch(return(expr), name, parentenv, handler)
13: tryCatchOne(expr, names, parentenv, handlers[[1L]])
14: tryCatchList(expr, classes, parentenv, handlers)
15: tryCatch({    captureStackTraces({        result <- withVisible(force(expr))        if (promises::is.promising(result$value)) {            p <- promise_chain(setVisible(result), ..., catch = catch,                 finally = finally)            runFinally <- FALSE            p        }        else {            result <- Reduce(function(v, func) {                if (".visible" %in% names(formals(func))) {                  withVisible(func(v$value, .visible = v$visible))                }                else {                  withVisible(func(v$value))                }            }, list(...), result)            setVisible(result)        }    })}, error = function(e) {    if (!is.null(catch))         catch(e)    else stop(e)}, finally = if (runFinally && !is.null(finally)) finally())
16: do()
17: hybrid_chain({    dims <- if (execOnResize)         getDims()    else isolate(getDims())    pixelratio <- session$clientData$pixelratio %OR% 1    drawPlot(outputName, session, func, dims$width, dims$height,         pixelratio, res)}, catch = function(reason) {    getDims()    stop(reason)})
18: `<reactive:plotObj>`(...)
19: ..stacktraceon..(`<reactive:plotObj>`(...))
20: .func()
21: withVisible(.func())
22: withCallingHandlers({    .error <<- FALSE    withVisible(.func())}, error = function(cond) {    .value <<- cond    .error <<- TRUE    .visible <<- FALSE})
23: contextFunc()
24: env$runWith(self, func)
25: withReactiveDomain(.domain, {    env <- .getReactiveEnvironment()    .graphEnterContext(id)    on.exit(.graphExitContext(id), add = TRUE)    env$runWith(self, func)})
26: globals$domain$wrapSync(expr)
27: promises::with_promise_domain(reactivePromiseDomain(), {    withReactiveDomain(.domain, {        env <- .getReactiveEnvironment()        .graphEnterContext(id)        on.exit(.graphExitContext(id), add = TRUE)        env$runWith(self, func)    })})
28: ctx$run(function() {    result <- withCallingHandlers({        .error <<- FALSE        withVisible(.func())    }, error = function(cond) {        .value <<- cond        .error <<- TRUE        .visible <<- FALSE    })    .value <<- result$value    .visible <<- result$visible})
29: self$.updateValue()
30: ..stacktraceoff..(self$.updateValue())
31: drawReactive()
32: force(expr)
33: withVisible(force(expr))
34: withCallingHandlers(expr, error = doCaptureStack)
35: globals$domain$wrapSync(expr)
36: promises::with_promise_domain(createStackTracePromiseDomain(),     expr)
37: captureStackTraces({    result <- withVisible(force(expr))    if (promises::is.promising(result$value)) {        p <- promise_chain(setVisible(result), ..., catch = catch,             finally = finally)        runFinally <- FALSE        p    }    else {        result <- Reduce(function(v, func) {            if (".visible" %in% names(formals(func))) {                withVisible(func(v$value, .visible = v$visible))            }            else {                withVisible(func(v$value))            }        }, list(...), result)        setVisible(result)    }})
38: doTryCatch(return(expr), name, parentenv, handler)
39: tryCatchOne(expr, names, parentenv, handlers[[1L]])
40: tryCatchList(expr, classes, parentenv, handlers)
41: tryCatch({    captureStackTraces({        result <- withVisible(force(expr))        if (promises::is.promising(result$value)) {            p <- promise_chain(setVisible(result), ..., catch = catch,                 finally = finally)            runFinally <- FALSE            p        }        else {            result <- Reduce(function(v, func) {                if (".visible" %in% names(formals(func))) {                  withVisible(func(v$value, .visible = v$visible))                }                else {                  withVisible(func(v$value))                }            }, list(...), result)            setVisible(result)        }    })}, error = function(e) {    if (!is.null(catch))         catch(e)    else stop(e)}, finally = if (runFinally && !is.null(finally)) finally())
42: do()
43: hybrid_chain(drawReactive(), function(result) {    dims <- getDims()    pixelratio <- session$clientData$pixelratio %OR% 1    resizeSavedPlot(name, shinysession, result, dims$width, dims$height,         pixelratio, res)})
44: origRenderFunc(...)
45: `output$hist`(...)
46: ..stacktraceon..(`output$hist`(...))
47: orig(name = name, shinysession = self)
48: func()
49: withCallingHandlers(expr, error = doCaptureStack)
50: globals$domain$wrapSync(expr)
51: promises::with_promise_domain(createStackTracePromiseDomain(),     expr)
52: captureStackTraces(expr)
53: withCallingHandlers(captureStackTraces(expr), error = function(e) {    if (inherits(e, "shiny.silent.error"))         return()    handle <- getOption("shiny.error")    if (is.function(handle))         handle()})
54: shinyCallingHandlers(func())
55: force(expr)
56: withVisible(force(expr))
57: withCallingHandlers(expr, error = doCaptureStack)
58: globals$domain$wrapSync(expr)
59: promises::with_promise_domain(createStackTracePromiseDomain(),     expr)
60: captureStackTraces({    result <- withVisible(force(expr))    if (promises::is.promising(result$value)) {        p <- promise_chain(setVisible(result), ..., catch = catch,             finally = finally)        runFinally <- FALSE        p    }    else {        result <- Reduce(function(v, func) {            if (".visible" %in% names(formals(func))) {                withVisible(func(v$value, .visible = v$visible))            }            else {                withVisible(func(v$value))            }        }, list(...), result)        setVisible(result)    }})
61: doTryCatch(return(expr), name, parentenv, handler)
62: tryCatchOne(expr, names, parentenv, handlers[[1L]])
63: tryCatchList(expr, classes, parentenv, handlers)
64: tryCatch({    captureStackTraces({        result <- withVisible(force(expr))        if (promises::is.promising(result$value)) {            p <- promise_chain(setVisible(result), ..., catch = catch,                 finally = finally)            runFinally <- FALSE            p        }        else {            result <- Reduce(function(v, func) {                if (".visible" %in% names(formals(func))) {                  withVisible(func(v$value, .visible = v$visible))                }                else {                  withVisible(func(v$value))                }            }, list(...), result)            setVisible(result)        }    })}, error = function(e) {    if (!is.null(catch))         catch(e)    else stop(e)}, finally = if (runFinally && !is.null(finally)) finally())
65: do()
66: hybrid_chain(shinyCallingHandlers(func()), catch = function(cond) {    if (inherits(cond, "shiny.custom.error")) {        if (isTRUE(getOption("show.error.messages")))             printError(cond)        structure(list(), class = "try-error", condition = cond)    }    else if (inherits(cond, "shiny.output.cancel")) {        structure(list(), class = "cancel-output")    }    else if (inherits(cond, "shiny.silent.error")) {        structure(list(), class = "try-error", condition = cond)    }    else {        if (isTRUE(getOption("show.error.messages")))             printError(cond)        if (getOption("shiny.sanitize.errors", FALSE)) {            cond <- simpleError(paste("An error has occurred. Check your",                 "logs or contact the app author for", "clarification."))        }        invisible(structure(list(), class = "try-error", condition = cond))    }})
67: force(expr)
68: withVisible(force(expr))
69: withCallingHandlers(expr, error = doCaptureStack)
70: globals$domain$wrapSync(expr)
71: promises::with_promise_domain(createStackTracePromiseDomain(),     expr)
72: captureStackTraces({    result <- withVisible(force(expr))    if (promises::is.promising(result$value)) {        p <- promise_chain(setVisible(result), ..., catch = catch,             finally = finally)        runFinally <- FALSE        p    }    else {        result <- Reduce(function(v, func) {            if (".visible" %in% names(formals(func))) {                withVisible(func(v$value, .visible = v$visible))            }            else {                withVisible(func(v$value))            }        }, list(...), result)        setVisible(result)    }})
73: doTryCatch(return(expr), name, parentenv, handler)
74: tryCatchOne(expr, names, parentenv, handlers[[1L]])
75: tryCatchList(expr, classes, parentenv, handlers)
76: tryCatch({    captureStackTraces({        result <- withVisible(force(expr))        if (promises::is.promising(result$value)) {            p <- promise_chain(setVisible(result), ..., catch = catch,                 finally = finally)            runFinally <- FALSE            p        }        else {            result <- Reduce(function(v, func) {                if (".visible" %in% names(formals(func))) {                  withVisible(func(v$value, .visible = v$visible))                }                else {                  withVisible(func(v$value))                }            }, list(...), result)            setVisible(result)        }    })}, error = function(e) {    if (!is.null(catch))         catch(e)    else stop(e)}, finally = if (runFinally && !is.null(finally)) finally())
77: do()
78: hybrid_chain(hybrid_chain(shinyCallingHandlers(func()), catch = function(cond) {    if (inherits(cond, "shiny.custom.error")) {        if (isTRUE(getOption("show.error.messages")))             printError(cond)        structure(list(), class = "try-error", condition = cond)    }    else if (inherits(cond, "shiny.output.cancel")) {        structure(list(), class = "cancel-output")    }    else if (inherits(cond, "shiny.silent.error")) {        structure(list(), class = "try-error", condition = cond)    }    else {        if (isTRUE(getOption("show.error.messages")))             printError(cond)        if (getOption("shiny.sanitize.errors", FALSE)) {            cond <- simpleError(paste("An error has occurred. Check your",                 "logs or contact the app author for", "clarification."))        }        invisible(structure(list(), class = "try-error", condition = cond))    }}), function(value) {    self$requestFlush()    private$sendMessage(recalculating = list(name = name, status = "recalculated"))    if (inherits(value, "cancel-output")) {        return()    }    private$invalidatedOutputErrors$remove(name)    private$invalidatedOutputValues$remove(name)    if (inherits(value, "try-error")) {        cond <- attr(value, "condition")        type <- setdiff(class(cond), c("simpleError", "error",             "condition"))        private$invalidatedOutputErrors$set(name, list(message = cond$message,             call = utils::capture.output(print(cond$call)), type = if (length(type)) type))    }    else private$invalidatedOutputValues$set(name, value)})
79: observerFunc()
80: doTryCatch(return(expr), name, parentenv, handler)
81: tryCatchOne(expr, names, parentenv, handlers[[1L]])
82: tryCatchList(expr, classes, parentenv, handlers)
83: tryCatch(if (..stacktraceon) ..stacktraceon..(observerFunc()) else observerFunc(),     shiny.silent.error = function(e) NULL)
84: contextFunc()
85: env$runWith(self, func)
86: withReactiveDomain(.domain, {    env <- .getReactiveEnvironment()    .graphEnterContext(id)    on.exit(.graphExitContext(id), add = TRUE)    env$runWith(self, func)})
87: globals$domain$wrapSync(expr)
88: promises::with_promise_domain(reactivePromiseDomain(), {    withReactiveDomain(.domain, {        env <- .getReactiveEnvironment()        .graphEnterContext(id)        on.exit(.graphExitContext(id), add = TRUE)        env$runWith(self, func)    })})
89: ctx$run(.func)
90: run()
91: withCallingHandlers(expr, error = doCaptureStack)
92: globals$domain$wrapSync(expr)
93: promises::with_promise_domain(createStackTracePromiseDomain(),     expr)
94: captureStackTraces(expr)
95: withCallingHandlers(captureStackTraces(expr), error = function(e) {    if (inherits(e, "shiny.silent.error"))         return()    handle <- getOption("shiny.error")    if (is.function(handle))         handle()})
96: shinyCallingHandlers(run())
97: force(expr)
98: withVisible(force(expr))
99: withCallingHandlers(expr, error = doCaptureStack)
100: globals$domain$wrapSync(expr)
101: promises::with_promise_domain(createStackTracePromiseDomain(),     expr)
102: captureStackTraces({    result <- withVisible(force(expr))    if (promises::is.promising(result$value)) {        p <- promise_chain(setVisible(result), ..., catch = catch,             finally = finally)        runFinally <- FALSE        p    }    else {        result <- Reduce(function(v, func) {            if (".visible" %in% names(formals(func))) {                withVisible(func(v$value, .visible = v$visible))            }            else {                withVisible(func(v$value))            }        }, list(...), result)        setVisible(result)    }})
103: doTryCatch(return(expr), name, parentenv, handler)
104: tryCatchOne(expr, names, parentenv, handlers[[1L]])
105: tryCatchList(expr, classes, parentenv, handlers)
106: tryCatch({    captureStackTraces({        result <- withVisible(force(expr))        if (promises::is.promising(result$value)) {            p <- promise_chain(setVisible(result), ..., catch = catch,                 finally = finally)            runFinally <- FALSE            p        }        else {            result <- Reduce(function(v, func) {                if (".visible" %in% names(formals(func))) {                  withVisible(func(v$value, .visible = v$visible))                }                else {                  withVisible(func(v$value))                }            }, list(...), result)            setVisible(result)        }    })}, error = function(e) {    if (!is.null(catch))         catch(e)    else stop(e)}, finally = if (runFinally && !is.null(finally)) finally())
107: do()
108: hybrid_chain({    if (!.destroyed) {        shinyCallingHandlers(run())    }}, catch = function(e) {    printError(e)    if (!is.null(.domain)) {        .domain$unhandledError(e)    }}, finally = .domain$decrementBusyCount)
109: flushCallback()
110: FUN(X[[i]], ...)
111: lapply(.flushCallbacks, function(flushCallback) {    flushCallback()})
112: ctx$executeFlushCallbacks()
113: .getReactiveEnvironment()$flush()
114: flushReact()
115: serviceApp()
116: withCallingHandlers(expr, error = doCaptureStack)
117: globals$domain$wrapSync(expr)
118: promises::with_promise_domain(createStackTracePromiseDomain(),     expr)
119: captureStackTraces({    while (!.globals$stopped) {        serviceApp()        Sys.sleep(0.001)    }})
120: ..stacktraceoff..(captureStackTraces({    while (!.globals$stopped) {        serviceApp()        Sys.sleep(0.001)    }}))
121: runApp(x)
122: do.call("runApp", args)
123: print.shiny.appobj(x)
124: function (x, ...) UseMethod("print")(x)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:

**Comment by SamoPP** [comment]
I have reinstalled Cairo using install.packages("Cairo") and now it works. No R crash anymore...

**Comment by shrektan** [comment]
@SamoPP Thanks for your comment! `install.packages("Cairo")` works! :heart:

**Comment by wch** [comment]
This sounds like the same issue as #1726. There's more information about it in this article:
  http://shiny.rstudio.com/articles/upgrade-R.html
