### ISSUE TITLE
Regression bug: from 1.0.3 to 1.0.4, tabsetPanel() can no longer take an id as unnamed first parameter 

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1988]
The following code worked up until and including shiny 1.0.3

```
tabsetPanel("id", tabPanel("tab", "content"))
```

Since then, the following error is produced:

```
Error in divTag$attribs : $ operator is invalid for atomic vectors
```

(A better error would be much appreciated for people with old code, it took me a long time to pinpoint this was the issue in a huge UI file that hasn't been touched in a year)

Two observations:

1. It's possible that current behaviour is correct in being broken, because the function signature is `(..., id)` so the first argument really should be either named or a tabPanel.
2. The `tabsetPanel` code has not changed, so the error must be propagating from elsewhere

**Comment by wch** [comment]
This is a duplicate of #1823. In the past, it never took the first argument as the ID -- it essentially just discarded it. Now it throws an error, but, as mentioned in the linked issue, the error message isn't very informative and should be improved.

See the function signature from 1.0.3 here:
https://github.com/rstudio/shiny/blob/v1.0.3/R/bootstrap.R#L625-L629

**Comment by daattali** [comment]
Ah yes that's what it is. I didn't realize the "id" was discarded. Thanks!
