### ISSUE TITLE
Can shinyoutput entries be removed?

### ISSUE THREAD

**Issue by mmuurr** [rstudio/shiny#1989]
Can we _remove_ elements from a shinyoutput object?
Some simple testing suggests no (at least not with the first few obvious guesses):
```R
## in shinyServer(function(input, output, session)):

output$foo <- renderText("foo")

## rm(output[["foo"]]) ## doesn't work
## output[["foo"]] <- NULL ## also doesn't work
```
The reason for wanting such a function is to prevent server-side memory accumulation in long-running applications that frequently call `insertUI()` & `removeUI()`.

For example, `insertUI()` might insert a dynamically-generated `textOutput("foo", ...)` element coupled to a corresponding `output[["foo"]] <- renderText(...)` assignment to the session's `output` object. Later, when `removeUI()` removes the `textOutput("foo", ...)` element, I'd like to 'clean-up' the session's `output` object by removing the `output[["foo"]]` entry. (In this example, "foo" is a randomly-generated unique ID.)

For applications where this is a frequent procedure the UI-side of the application can be kept tidy, but I suspect the server-side `output` object simply continues to accumulate these entries.

Is there any way to _remove_ a specific entry in the `output` object by that entry's ID?
(I can't find any such function/procedure in the docs.)

**Comment by jcheng5** [comment]
Note: "doesn't work" means

```
Error in .subset2(x, "impl")$defineOutput(name, value, label) : 
  Unexpected NULL output for plot
```
