### ISSUE TITLE
Triggering "shown" javascript event causes the element to be selected

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1991]
(originally posted on https://github.com/daattali/shinyjs/issues/148 and now suspected to be a shiny issue)

The following code creates a shinydashboard with two menu items. Triggering the "shown" event on a menu item in javascript causes that tab to become selected. The reason this is problematic is because if the menu is hidden and then shown, it would be auto selected instead of keeping the current selection.

```
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(
    sidebarMenu(
      id = "tabs",
      menuItem("Item 1", tabName = "item1"),
      menuItem("Item 2", tabName = "item2"),
      actionButton("go", "Trigger 'shown'")
    )
  ),
  dashboardBody(
    tags$script(
      "Shiny.addCustomMessageHandler('triggerShown', function(message) {
        $(message).trigger('shown');
      })"
    ),
    tabItems(
      tabItem("item1", h1("Item 1")),
      tabItem("item2", h1("Item 2"))
    )
  )
)

server <- function(input, output, session) {
  observeEvent(input$go, {
    session$sendCustomMessage('triggerShown', 'a[data-value=item2]')
  })
}

shinyApp(ui = ui, server = server)
```

Apologies for not having debugged this down to the absolute minimal reproducible example or even as far as seeing if this is only in shinydashboard or only on menu items. But it's definitely the call to `.trigger('shown')` that's causing the behaviour, and it's isolated to shiny+shinydashboard packages.

Windows 7 using both RStudio and Chrome are causing this for me. Reports on the initial github issue also show that safari and linux are seeing this problem.

**Comment by jcheng5** [comment]
This appears to be a shinydashboard specific issue. I don't know the code well but it appears we use the `shown.bs.tab` event: https://github.com/rstudio/shinydashboard/blob/1c5a3129a1b892b049520d5eb70d16461447541a/srcjs/tabs.js#L26

I don't know what a good fix for this would be--perhaps @wch and @bborgesr can weigh in. But in the meantime, you could work around this by providing an option to `toggle()` about whether to raise the `shown` event--it's not needed in this case.

**Comment by daattali** [comment]
Thanks Joe, I'll report an issue with shinydashboard (with the understanding that this may not get fixed)
