### ISSUE TITLE
selectizeJSON should be coercing values to lowercase

### ISSUE THREAD

**Issue by carlganz** [rstudio/shiny#1992]
According to note [here](https://github.com/rstudio/shiny/blob/master/R/update-input.R#L700) data that is searched by server selectize is already in lower case, but some simple testing shows this is not the case.

MRE taken from this example: https://shiny.rstudio.com/gallery/option-groups-for-server-side-selectize.html

```{R}
library(shiny)

ui <- fluidPage(
  selectizeInput('group', NULL, NULL, multiple = TRUE, options = list(
    #### ADDED THIS ONE LINE####
    maxOptions = 5,
    placeholder = 'Select a category',
    
    # predefine all option groups
    optgroups = list(
      list(value = '1st', label = 'First Class'),
      list(value = '2nd', label = 'Second Class'),
      list(value = '3rd', label = 'Third Class'),
      list(value = 'Crew', label = 'Crew')
    ),
    
    # 'Class' is a field in Titanic2 created in server.R
    optgroupField = 'Class',
    
    optgroupOrder = c('1st', '2nd', '3rd', 'Crew'),
    
    # you can type and search in these fields in Titanic2
    searchField = c('Sex', 'Age', 'Survived'),
    
    # how to render the options (each item is a row in Titanic2)
    render = I("{
      option: function(item, escape) {
        return '<div>' + escape(item.Age) + ' (' +
                (item.Sex == 'Male' ? '&male;' : '&female;') + ', ' +
                (item.Survived == 'Yes' ? '&hearts;' : '&odash;') + ')' +
               '</div>';
      }
    }")
  )),
  
  verbatimTextOutput('row'),
  title = 'Using options groups for server-side selectize input'
)

server <- function(input, output, session) {
  
  Titanic2 <- as.data.frame(Titanic, stringsAsFactors = FALSE)
  Titanic2 <- cbind(Titanic2, value = seq_len(nrow(Titanic2)))
  Titanic2$label <- apply(Titanic2[, 2:4], 1, paste, collapse = ', ')
  updateSelectizeInput(session, 'group', choices = Titanic2, server = TRUE)
  
  output$row <- renderPrint({
    validate(need(
      input$group, 'Please type and search (e.g. Female)'
    ))
    Titanic2[as.integer(input$group), -(6:7)]
  })
}

shinyApp(ui, server)
```
When I search "Adult" nothing appears because search term is coerced to lowercase "adult", but values in data.frame that are searched retain capital letters. I find that if I change code [here](https://github.com/rstudio/shiny/blob/master/R/update-input.R#L701) to `tolower(data[[v]])` everything works in this example. 

This issue doesn't appear when maxOptions is larger than the number of options in selectize, because I believe the server filter was simply sending all values to client and client sorting code was effectively performing filtering.

**Comment by bborgesr** [comment]
The server-side capitalization loss was actually a regression that was fixed in https://github.com/rstudio/shiny/pull/1996. The choices should retain capitalization, but the searching is case-insensitive, so you should be able to search in all lowercase or all caps and get the same results back. Your app should now work as expected; if not, let us know.
