### ISSUE TITLE
Server-side selectize loses capitalization

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#1995]
For example, this app doesn't have capitalized options. But if `server = TRUE` is commented out, it works.

```R
ui <- fluidPage(
  selectizeInput("inSelect", "Select input", NULL)
)
server <- function(input, output, session) {
  observe({
    updateSelectizeInput(session, "inSelect",
      choices = paste(c("Male", "male", "Female", "female")),
      server = TRUE
    )
  })
}
shinyApp(ui, server)
```

I think this was probably introduced by #1861. It might be the root cause of #1992 and #1993.

**Comment by bborgesr** [comment]
This was definitely caused by #1861: the bad commit is https://github.com/rstudio/shiny/commit/7b722092779138813361b80cd7d116f84e98ec81 (you can see the capitalization working fine in its parent: cad20a0bfea9d02dc9f163f028a0c498462fdd90).
