### ISSUE TITLE
Consider upgrading jQuery to 3.x

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#2006]

**Comment by thomasneu** [comment]
jQuery 1.12.4 have some known CVE's, so i'm looking forward for a new version with upgraded dependencies

**Comment by daattali** [comment]
Is the full version or the slim version of jquery going to be used?

**Comment by wch** [comment]
Closing because we've already switched to 3.x.

@daattali We've always used the full version.

**Comment by daattali** [comment]
Glad I helped clear the issues backlog a little bit :)
