### ISSUE TITLE
Development version of ggplot2 causes test failure

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#2016]
This line and others like it fail:
https://github.com/rstudio/shiny/blob/6948e90c/tests/testthat/test-plot-coordmap.R#L28

The problem is that the names have changed from `xvar` and `yvar` to `~xvar` and `~yvar`:

```
> m[[1]]$mapping
$x
[1] "~xvar"

$y
[1] "~yvar"
```

**Comment by jcheng5** [comment]
I guess these changes in ggplot2 were intentional? (cc @lionel-)

**Comment by lionel-** [comment]
There's probably a faulty `as.character()` somewhere. Mappings are now stored as quosures. I should probably add `as.character.quosure` method to throw an error.

**Comment by lionel-** [comment]
This might be relevant: https://github.com/cran/shiny/blob/3ed20b9bdbafb4f07d8f77395abef4b413a616d8/R/render-plot.R#L479

**Comment by wch** [comment]
@lionel When `x` is a language or symbol object, does `quo_squash(x)` always return it unchanged? If so then `lapply(mapping, deparse)` could become:

```R
lapply(mapping, function(x) deparse(quo_squash(x)))
```

And this would support both old and devel versions of ggplot2.

**Comment by lionel-** [comment]
Yes it only affects quosures.
