### ISSUE TITLE
updateSliderInput with different argument data type

### ISSUE THREAD

**Issue by helgasoft** [rstudio/shiny#2019]
_updateSliderInput_ does not acknowledge change of data type of arguments (min, max, value).
To run the [demo](https://gist.github.com/helgasoft/0353c54a3b50deceeb18afc1b0a7f460):
`runGist('https://gist.github.com/helgasoft/0353c54a3b50deceeb18afc1b0a7f460')`
 
Also an **enhancement** request - to allow **styling** of sliders generated from code, 
like `renderUI({ sliderInput(...`
Currently styling with themes, skins or custom CSS does not work with those on-the-fly generated sliders.

**Comment by tmastny** [comment]
## Time zone

Shiny uses `as.POSIXt` to convert strings to date-time. Note that `as.POSIXt` does not recognize your timezone:

``` r
as.POSIXlt('2018-05-30 12:00:00', tz = 'Europe/Stockholm')
#> Warning in strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz): unknown
#> timezone 'default/America/Chicago'
#> Warning in as.POSIXct.POSIXlt(x): unknown timezone 'default/America/
#> Chicago'
#> Warning in strptime(x, f, tz = tz): unknown timezone 'default/America/
#> Chicago'
#> [1] "2018-05-30 12:00:00 CEST"
```
I believe this is the reason for the timezone change when you use `renderUI`. 

## updateSliderInput

`updateSliderInput` is behaving as expected. When `sliderInput` is created, the data type is set as a [date, date-time, or number](https://github.com/rstudio/shiny/blob/6df3509869e05bcfa278e9cb51ddc2b03cdd7ce7/R/input-slider.R#L175).

Then `updateSliderInput` only changes the value of the `sliderInput`, which includes `min`, `max`, and the starting `value`. `updateSliderInput` does not change the data type that was set during the creation of `sliderInput`.

**Comment by helgasoft** [comment]
## Time zone
@tmastny , looks like the Timezone warnings come from your environment.  Here is a replication:
```
# ---------- when timezone is set with an incorrect string, warning msgs show up:
Sys.setenv(TZ="default/America/Chicago")
Sys.getenv("TZ")
as.POSIXlt('2018-05-30 12:00:00', tz = 'Europe/Stockholm')
```
 > Sys.setenv(TZ="default/America/Chicago")
 > Sys.getenv("TZ")
 [1] "default/America/Chicago"
 > as.POSIXlt('2018-05-30 12:00:00', tz = 'Europe/Stockholm')
 [1] "2018-05-30 12:00:00 CEST"
 Warning messages:
   1: In strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) :
   unknown timezone 'default/America/Chicago'
 2: In as.POSIXct.POSIXlt(x) : unknown timezone 'default/America/Chicago'
 3: In strptime(x, f, tz = tz) : unknown timezone 'default/America/Chicago'

```
# --------- now if set up correctly, there are no warnings:
Sys.setenv(TZ="America/Chicago")
Sys.getenv("TZ")
as.POSIXlt('2018-05-30 12:00:00', tz = 'Europe/Stockholm')
```
 > Sys.setenv(TZ="America/Chicago")
 > Sys.getenv("TZ")
 [1] "America/Chicago"
 > as.POSIXlt('2018-05-30 12:00:00', tz = 'Europe/Stockholm')
 [1] "2018-05-30 12:00:00 CEST"

My original question about the confusion of 3 timezones (given,shown,returned) still stands.

## updateSliderInput
I understand the current logic.  Maybe an enhancement down the road ? Switching from date to number doesn't make sense, but from date to date-time does.  For instance in a financial app when the user wants to toggle between daily and intraday timeseries of stock data.
