### ISSUE TITLE
The application failed to start (exited with code 1)

### ISSUE THREAD

**Issue by Hamed51** [rstudio/shiny#2025]
@jcheng5 @wch 
Hello, 
I try publish my Shiny app but i got this error: 
Error in value[[3L]](cond) : object 'gapminder' not found
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

I would appreciate to advise me.

**Comment by wch** [comment]
Can you provide a reproducible example?

**Comment by alexvlima** [comment]
I have the same problem. I also use a free shinyapps.io account

**Comment by alexvlima** [comment]
I solve the problem. I had a line with setwd(directory/in/my/computer). So, I commit this line and replublished the app.

**Comment by monipip3** [comment]
I also have this issue 

![shiny_code_error](https://user-images.githubusercontent.com/16262065/73690489-79c5ba80-469e-11ea-8f25-5744af970a00.PNG)


I scoured the internet and this person also has a similar error associated to exited with code 1 but no anaswer :( 
https://stackoverflow.com/questions/48568067/error-in-value3lcond-trying-to-get-slot-data-from-an-object-class-da

**Comment by jcheng5** [comment]
@monipip3 The "exited with code 1" is just a generic message that there was an error. In your case, there's some kind of error in your logic; specifically, a data frame is being treated like an S4 object (in that `@data` is being called on it), so you probably have the wrong kind of object. Ideally, try to reproduce this problem on your desktop, and use standard R debugging techniques to narrow down to the line that's causing the problem.

**Comment by jcheng5** [comment]
Failing that, please create a minimal reproducible example that we can try.

**Comment by monipip3** [comment]
@jcheng5 I figured it out. 
When I did a merge I had to use sp::merge instead of base R merge to retain the S4 object properties. When I merge a spatial object with dataframe the product output was a dataframe but using sp::merge retains the S4 properties.
