### ISSUE TITLE
conditionalPanels on second tab, not playing nice

### ISSUE THREAD

**Issue by elmsoftware** [rstudio/shiny#203]
Basic example of a sidebarPanel with two tabs. On the second tab, there is a selectInput with two values. There are two conditionalPanels that apply to each entry in the selectInput. On my MacBook Pro using Chrome and Safari, when visiting the second tab, the contents of both conditionalPanels is visible. Only after making a choice, do they play as expected. Seems to work fine on my Windows and on iPhones.

Please see the following gist.
https://gist.github.com/elmsoftware/6005332

The gist is just the sidebarPanel.

Below is the visual sequence.
First is Tab 1.
Then Tab 2 with both conditionalPanels' contents visible.
Then a selection is made and it is good.
Then the other/original selection is made and all is well.
Note: This behavior is experienced on my nice MacBook Pro Retina (purchased last November) with the latest browsers (Chrome and Safari).

![screen shot 2013-07-15 at 10 40 20 pm](https://f.cloud.github.com/assets/2679066/802345/e131b8b8-edc2-11e2-9cc0-eabfa90c0fa7.png)

![screen shot 2013-07-15 at 10 40 27 pm](https://f.cloud.github.com/assets/2679066/802346/e978afe0-edc2-11e2-8adb-03684ac6299f.png)

![screen shot 2013-07-15 at 10 40 51 pm](https://f.cloud.github.com/assets/2679066/802347/ee10fad0-edc2-11e2-8775-905927fe9a50.png)

![screen shot 2013-07-15 at 10 41 00 pm](https://f.cloud.github.com/assets/2679066/802348/f3470dfa-edc2-11e2-8557-50e6f07d0c2f.png)

All the best,

John Lueders

**Comment by alandipert** [comment]
Sorry to take so long to look at this! You'll be happy to know that at some point between now and 2013, this was fixed. I was able to run your gist with Shiny 1.3.2 and the problem did not manifest.
