### ISSUE TITLE
Error when trying to install shiny 

### ISSUE THREAD

**Issue by U201412486** [rstudio/shiny#2039]
Hi,
I'm facing an unusual error when installing shiny.I have istalled  httpuv (version1.4.1) before.When I excute "R CMD INSTALL shiny_1.0.5.tar.gz" on the linux platform,It still report it:
>>
 Error : .onLoad failed in loadNamespace() for 'shiny', details:
  call: .Call("_httpuv_getRNGState", PACKAGE = "httpuv")
  error: "_httpuv_getRNGState" not available for .Call() for package "httpuv"
 Error: loading failed
 Execution halted
 ERROR: loading failed
>>
Any advice to solve my question? looking forward to your reply.

**Comment by wch** [comment]
Can you try starting a new R session, then reinstall httpuv, and then reinstall shiny? If that doesn't work, can you run the following, and provide the output:

```
install.packages("sessioninfo")
library(httpuv)
library(shiny)
sessioninfo::session_info()
```

**Comment by wch** [comment]
Note: this is the same as #2054.
