### ISSUE TITLE
unable to deploy to shinyapps.io

### ISSUE THREAD

**Issue by pastrami0** [rstudio/shiny#2044]
I get this error whenever I try to deploy to shinyapps.io, even when I'm using the default simple Shiny web app ("Old Faithful Geyser Data") that opens when you create a new Shiny app in RStudio:

```
Preparing to deploy application...DONE
Uploading bundle for application: 333624...DONE
Deploying bundle: 1346036 for application: 333624 ...
Waiting for task: 522982840
  building: Building package: rlang
################################ Begin Task Log ################################ 
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 522982321 failed: Error building image: Error building rlang (0.2.0). R version 3.5.0 currently unavailable
In addition: Warning messages:
1: invalid uid value replaced by that for user 'nobody' 
2: invalid gid value replaced by that for user 'nobody' 
Execution halted
```

The `rlang` package looks like it's installed fine on my system:

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rlang_0.2.0      intervals_0.15.1 lubridate_1.7.4 

loaded via a namespace (and not attached):
 [1] compiler_3.5.0  magrittr_1.5    rsconnect_0.8.8 tools_3.5.0     RCurl_1.95-4.10
 [6] yaml_2.1.18     Rcpp_0.12.16    RJSONIO_1.3-0   stringi_1.1.7   digest_0.6.15  
[11] stringr_1.3.0   bitops_1.0-6   
```

**Comment by wch** [comment]
Since this is an issue with shinyapps.io, could you post this questionto https://community.rstudio.com/ ? If you're a paid customer, you can also open a ticket at https://support.rstudio.com/hc/en-us .

**Comment by bborgesr** [comment]
fwiw, @pastrami0, R 3.5.0 as a stable release is only 1 week old. If you can switch the the previous one (R 3.4.4), there's a chance that issue won't be a problem anymore, since your error message states:

> Error: Unhandled Exception: Child Task 522982321 failed: Error building image: Error building rlang (0.2.0). R version 3.5.0 currently unavailable

if that doesn't do it, please start a post at https://community.rstudio.com/c/shiny, as Winston suggested. good luck!
