### ISSUE TITLE
R Studio: list() variable initializing to past version

### ISSUE THREAD

**Issue by LoganMallory** [rstudio/shiny#2045]
When I initialize a list, it seems to be accessing files that used to be in my workspace, or accessing previous versions of that list. If I am working and fill a list with data frames, when I delete that list later on during my work and then try to initialize it as a blank list, it is filled with the same data frames as before. This occurs even when the data frames are not in my workspace, and after restarting R Studio. I have attached a gif showing the bug.
![rstudiolistbug_gif](https://user-images.githubusercontent.com/38388056/39437980-8ba66396-4c70-11e8-9e6e-0a354ba31e13.gif)

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests for Shiny. For questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
