### ISSUE TITLE
Navigation bar in a “Home > Users > User X > …” text form for R Shiny application

### ISSUE THREAD

**Issue by andirey** [rstudio/shiny#2050]
Is it possible to design navigation bar in a simple text form like "Home > Users > User X > ..." with selection appropriated tabsetPanel/tabPanel in R Shiny application?

Using tabsetPanel/tabPanel is cool but for many levels of navigations (3+) takes a lot of screen space.

**Comment by wch** [comment]
Hi, I think what you're describing is breadcrumb navigation. Shiny currently doesn't have built-in support for this, but we hope to add something like this in the future.
