### ISSUE TITLE
uiOutput problem 

### ISSUE THREAD

**Issue by LuisCanoA** [rstudio/shiny#2051]
Hi , i have a problem with shiny ... I used this command for create a widget for select the uploaded files 

server

`server <- function(input, output) {
  
  output$selecc <- renderUI({
    if (is.null(input$file)) {return()}
    list(hr(),
         helpText("selecciona los sets a usar"),
         selectInput("selecciona", "selecciona", choices = input$file$name))
  })
}`

but I receive the following error: 
Error in validateCssUnit(width) : 
  CSS units must be a single-element numeric or character vector

How I can fix it? 
thank you very much!

**Comment by shrektan** [comment]
The functions `req()` and `tagList()` can help you.

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
