### ISSUE TITLE
nearPoints and brushData do not work with dataframe created by splitting data frame

### ISSUE THREAD

**Issue by AliciaSchep** [rstudio/shiny#2052]
This is an issue that arose with a shiny gadget for selecting points to label: https://github.com/AliciaSchep/gglabeller/issues/6

The goal was to be able to split a dataframe, create plots from each split, and then run the shiny app on each split.  However, this leads to an issue because when `nearPoints` (or `brushData`) is called for a ggplot made from any but the first dataframe created, it seemingly fails to recognize the points.  Below is an example adapted from the basic selection demo in the shiny documentation:

```r
library(tidyverse)
library(shiny)

#Create some data
testdata <- tibble(sample = rep(LETTERS[1:6], each = 15),
                   catvar = rep(paste0("var_",letters[1:15]), times = 6),
                   contvar = abs(rnorm(90)))

#Split data into manageable chunks for plotting by categorical variables
testlist <- testdata %>%
  mutate(catvar = as.factor(catvar),
         group = as.numeric(catvar) %>%
           cut(3) %>% #cut into how many pieces?
           as.integer()) %>% 
  split(.$group) #returns a list of dataframes

ui <- basicPage(
  plotOutput("plot1", click = "plot_click"),
  verbatimTextOutput("info")
)

server <- function(input, output) {
  output$plot1 <- renderPlot({
    ggplot(testlist[[2]], aes(x = catvar, y = contvar, label = sample)) +
      geom_point()
  })
  
  output$info <- renderPrint({
    nearPoints(testlist[[2]], input$plot_click, threshold = 10, maxpoints = 1,
               addDist = TRUE)
  })
}

shinyApp(ui, server)
```

With testlist[[2]] as the input data, nothing happens on clicking on the points.  However, with testlist[[1]] the app behaves as expected.  Similarly, if the code is adapted for brushPoints instead of nearPoints, it works okay for testlist[[1]] as a data source for the plot but not testlist[[2]].

**Comment by wch** [comment]
The root cause is that ggplot drops unused factor levels by default, and shiny currently doesn't recognize this case. For example, this app will have the x values shifted by one when you click. If you uncomment the `scale_x_discrete(drop=FALSE)`, it will show all the factor levels, and x positions won't be shifted relative to the click:

```R
testdata <- data.frame(
  catvar = factor(letters[2:7], levels = letters[1:10]),
  contvar = 1:6
)

ui <- basicPage(
  plotOutput("plot1", click = "plot_click"),
  verbatimTextOutput("info")
)

server <- function(input, output) {
  output$plot1 <- renderPlot({
    ggplot(testdata, aes(x = catvar, y = contvar)) +
      geom_point() # +
      # scale_x_discrete(drop = FALSE)
  })
  
  output$info <- renderPrint({
    str(input$plot_click)
    nearPoints(testdata, input$plot_click, threshold = 10, maxpoints = 1,
               addDist = TRUE)
  })
}

shinyApp(ui, server)
```


As a workaround for now, you could re-factor your x column in the `renderPlot`. You might need to do it before the call to `nearPoints` as well.

**Comment by AliciaSchep** [comment]
Thanks for the explanation & workaround suggestion!  `scale_x_discrete(drop = FALSE)` resolves the issue, as does dropping the factors with `forcats::fct_drop` before passing the data to `ggplot` and `nearPoints`.
