### ISSUE TITLE
Shiny won't load / install after httpuv install (tried solution in #2030 but did not work)

### ISSUE THREAD

**Issue by DrSylWil** [rstudio/shiny#2054]
Hello

After an httpuv update, Shiny apps don't run because shiny library fails to load.
A rapid googling led me here : 
https://github.com/rstudio/shiny/issues/2030

So I : 
 - restarted R, went fine
 - reinstalled httpuv, went fine (after quite a long compilation and some warning messages about deprecating issues)
 - reinstalled shiny, crashed
 - run a sessioninfo::session_info()
- copy paste the entire console (all above steps) in this message

Plz, help... that shiny app is supposed to be a demo to show how great it is :-(
Also, sorry, but my R install is in French, although I hope most messages remain quite understandable do not hesitate to ask me for a translation if needed

Sylvain

Restarting R session...

R> install.packages("httpuv")
Installing package into ‘/home/alfred/R_libs’
(as ‘lib’ is unspecified)
essai de l'URL 'https://cran.rstudio.com/src/contrib/httpuv_1.4.3.tar.gz'
Content type 'application/x-gzip' length 1673359 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

* installing *source* package ‘httpuv’ ...
** package ‘httpuv’ correctement décompressé et sommes MD5 vérifiées
** libs
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports-legacy.cpp -o RcppExports-legacy.o
In file included from /home/alfred/R_libs/Rcpp/include/Rcpp/Module.h:338:0,
                 from /home/alfred/R_libs/Rcpp/include/Rcpp.h:64,
                 from RcppExports-legacy.cpp:23:
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:103:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:161:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
In file included from /home/alfred/R_libs/Rcpp/include/Rcpp/Module.h:338:0,
                 from /home/alfred/R_libs/Rcpp/include/Rcpp.h:64,
                 from RcppExports.cpp:4:
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:103:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:161:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c callback.cpp -o callback.o
In file included from /home/alfred/R_libs/Rcpp/include/Rcpp/Module.h:338:0,
                 from /home/alfred/R_libs/Rcpp/include/Rcpp.h:64,
                 from /home/alfred/R_libs/later/include/later.h:6,
                 from /home/alfred/R_libs/later/include/later_api.h:4,
                 from callback.h:5,
                 from callback.cpp:1:
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:103:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:161:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c callbackqueue.cpp -o callbackqueue.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c filedatasource-unix.cpp -o filedatasource-unix.o
In file included from /home/alfred/R_libs/Rcpp/include/Rcpp/Module.h:338:0,
                 from /home/alfred/R_libs/Rcpp/include/Rcpp.h:64,
                 from uvutil.h:15,
                 from filedatasource.h:4,
                 from filedatasource-unix.cpp:3:
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:103:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:161:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c filedatasource-win.cpp -o filedatasource-win.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c http.cpp -o http.o
In file included from /home/alfred/R_libs/Rcpp/include/Rcpp/Module.h:338:0,
                 from /home/alfred/R_libs/Rcpp/include/Rcpp.h:64,
                 from webapplication.h:6,
                 from http.h:7,
                 from http.cpp:1:
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:103:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:161:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c httprequest.cpp -o httprequest.o
In file included from /home/alfred/R_libs/Rcpp/include/Rcpp/Module.h:338:0,
                 from /home/alfred/R_libs/Rcpp/include/Rcpp.h:64,
                 from /home/alfred/R_libs/later/include/later.h:6,
                 from /home/alfred/R_libs/later/include/later_api.h:4,
                 from httprequest.cpp:4:
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:103:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:161:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c httpresponse.cpp -o httpresponse.o
In file included from /home/alfred/R_libs/Rcpp/include/Rcpp/Module.h:338:0,
                 from /home/alfred/R_libs/Rcpp/include/Rcpp.h:64,
                 from uvutil.h:15,
                 from httpresponse.h:4,
                 from httpresponse.cpp:1:
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:103:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:161:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c httpuv.cpp -o httpuv.o
In file included from /home/alfred/R_libs/Rcpp/include/Rcpp/Module.h:338:0,
                 from /home/alfred/R_libs/Rcpp/include/Rcpp.h:64,
                 from uvutil.h:15,
                 from httpuv.cpp:12:
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:103:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:161:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c md5.c -o md5.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c set_invalid_parameter.c -o set_invalid_parameter.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c socket.cpp -o socket.o
In file included from /home/alfred/R_libs/Rcpp/include/Rcpp/Module.h:338:0,
                 from /home/alfred/R_libs/Rcpp/include/Rcpp.h:64,
                 from webapplication.h:6,
                 from http.h:7,
                 from socket.h:4,
                 from socket.cpp:1:
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:103:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:161:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c thread.cpp -o thread.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c utils.cpp -o utils.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c uvutil.cpp -o uvutil.o
In file included from /home/alfred/R_libs/Rcpp/include/Rcpp/Module.h:338:0,
                 from /home/alfred/R_libs/Rcpp/include/Rcpp.h:64,
                 from uvutil.h:15,
                 from uvutil.cpp:1:
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:103:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:161:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c webapplication.cpp -o webapplication.o
In file included from /home/alfred/R_libs/Rcpp/include/Rcpp/Module.h:338:0,
                 from /home/alfred/R_libs/Rcpp/include/Rcpp.h:64,
                 from httpuv.h:4,
                 from webapplication.cpp:2:
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:103:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
/home/alfred/R_libs/Rcpp/include/Rcpp/module/Module_Property.h:161:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     void set(Class* object, SEXP value) throw(std::range_error,Rcpp::not_compatible){
                                         ^~~~~
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c websockets-base.cpp -o websockets-base.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c websockets-hixie76.cpp -o websockets-hixie76.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c websockets-hybi03.cpp -o websockets-hybi03.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c websockets-ietf.cpp -o websockets-ietf.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c websockets.cpp -o websockets.o
cp -p -f libuv/m4/lt_obsolete.m4 libuv/m4/lt~obsolete.m4
(cd libuv \
	&& touch aclocal.m4 \
	&& touch -r aclocal.m4 configure Makefile.in \
	&& CC="gcc -std=gnu99" CFLAGS="-g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -fvisibility=hidden" AR="ar" RANLIB="ranlib" LDFLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro" ./configure "--quiet")
make --directory=libuv \
	HAVE_DTRACE=0
make[1] : on entre dans le répertoire « /tmp/Rtmpx70QHv/R.INSTALL5c0a2609960f/httpuv/src/libuv »
  CC       src/libuv_la-fs-poll.lo
  CC       src/libuv_la-inet.lo
  CC       src/libuv_la-threadpool.lo
  CC       src/libuv_la-uv-common.lo
  CC       src/libuv_la-version.lo
  CC       src/unix/libuv_la-async.lo
  CC       src/unix/libuv_la-core.lo
  CC       src/unix/libuv_la-dl.lo
  CC       src/unix/libuv_la-fs.lo
  CC       src/unix/libuv_la-getaddrinfo.lo
  CC       src/unix/libuv_la-getnameinfo.lo
  CC       src/unix/libuv_la-loop-watcher.lo
  CC       src/unix/libuv_la-loop.lo
  CC       src/unix/libuv_la-pipe.lo
  CC       src/unix/libuv_la-poll.lo
  CC       src/unix/libuv_la-process.lo
  CC       src/unix/libuv_la-signal.lo
  CC       src/unix/libuv_la-stream.lo
  CC       src/unix/libuv_la-tcp.lo
  CC       src/unix/libuv_la-thread.lo
  CC       src/unix/libuv_la-timer.lo
  CC       src/unix/libuv_la-tty.lo
  CC       src/unix/libuv_la-udp.lo
  CC       src/unix/libuv_la-linux-core.lo
  CC       src/unix/libuv_la-linux-inotify.lo
  CC       src/unix/libuv_la-linux-syscalls.lo
  CC       src/unix/libuv_la-procfs-exepath.lo
  CC       src/unix/libuv_la-proctitle.lo
  CC       src/unix/libuv_la-sysinfo-loadavg.lo
  CC       src/unix/libuv_la-sysinfo-memory.lo
  CCLD     libuv.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[1] : on quitte le répertoire « /tmp/Rtmpx70QHv/R.INSTALL5c0a2609960f/httpuv/src/libuv »
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c http-parser/http_parser.c -o http-parser/http_parser.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sha1/sha1.c -o sha1/sha1.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -fvisibility=hidden -I"/home/alfred/R_libs/Rcpp/include" -I"/home/alfred/R_libs/BH/include" -I"/home/alfred/R_libs/later/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c base64/base64.cpp -o base64/base64.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o httpuv.so RcppExports-legacy.o RcppExports.o callback.o callbackqueue.o filedatasource-unix.o filedatasource-win.o http.o httprequest.o httpresponse.o httpuv.o md5.o set_invalid_parameter.o socket.o thread.o utils.o uvutil.o webapplication.o websockets-base.o websockets-hixie76.o websockets-hybi03.o websockets-ietf.o websockets.o ./libuv/.libs/libuv.a ./http-parser/http_parser.o ./sha1/sha1.o ./base64/base64.o -L/usr/lib/R/lib -lR
installing to /home/alfred/R_libs/httpuv/libs
** R
** demo
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (httpuv)

The downloaded source packages are in
	‘/tmp/Rtmp5BAP1W/downloaded_packages’
R> install.packages("shiny")
Installing package into ‘/home/alfred/R_libs’
(as ‘lib’ is unspecified)
essai de l'URL 'https://cran.rstudio.com/src/contrib/shiny_1.0.5.tar.gz'
Content type 'application/x-gzip' length 2330710 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

* installing *source* package ‘shiny’ ...
** package ‘shiny’ correctement décompressé et sommes MD5 vérifiées
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘shiny’:
 .onLoad failed in loadNamespace() for 'shiny', details:
  call: .Call("_httpuv_getRNGState", PACKAGE = "httpuv")
  error: "_httpuv_getRNGState" non disponible pour .Call() pour le package"httpuv"
Erreur : le chargement a échoué
Exécution arrêtée
ERROR: loading failed
* removing ‘/home/alfred/R_libs/shiny’
* restoring previous ‘/home/alfred/R_libs/shiny’
Warning in install.packages :
  installation of package ‘shiny’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp5BAP1W/downloaded_packages’
R> sessioninfo::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 os       Ubuntu 18.04 LTS            
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  fr_LU.UTF-8                 
 tz       Europe/Luxembourg           
 date     2018-05-10                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       source        
 clisymbols    1.2.0   2017-05-21 CRAN (R 3.4.4)
 sessioninfo   1.0.0   2017-06-21 CRAN (R 3.4.4)
 withr         1.0.2   2016-06-20 CRAN (R 3.4.0)
 yaml          2.1.14  2016-11-12 CRAN (R 3.4.0)

**Comment by wch** [comment]
Another thought: It's possible there's another, older version of httpuv also installed on your system, but in a different directory. Can you run `.libPaths()` and the look in each of the listed directories for httpuv?

For example:

```
> .libPaths()
[1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"      
[3] "/usr/lib/R/library"           
```

In this case, you would check each of those directories for a subdirectory named httpuv. If you find them, can you provide the contents of the DESCRIPTION file in that directory? In the case above, there might be one at `/usr/local/lib/R/site-library/httpuv/DESCRIPTION` and `/usr/local/R/library/httpuv/DESCRIPTION`.

**Comment by wch** [comment]
In my opinion, it's best to install packages at the user level, unless you have a specific reason to install them as root. When you have the same package installed in multiple levels of your libpath, things should generally work, but when they don't, it can make things harder to diagnose.

**Comment by sjackman** [comment]
Reinstalling `Rcpp` and then `httpuv` worked for me. Reinstall `httpuv` alone was not sufficient.

**Comment by binarin** [comment]
I was doing a bit of RPM packaging, and got the same `_httpuv_getRNGState` problem. It turned out that `httpuv` was build with `-fvisibility=hidden`, but `R_init_httpuv` wasn't explicitly exported. I've solved this by patching in some visibility into `src/RcppExports.cpp` like this:
    RcppExport void R_init_httpuv(DllInfo *dll) __attribute__((visibility("default")));

In a newer versions of {{Rcpp}} this is already done automatically by {{RcppExport}} macro above. Probably `httpuv` should put a stricter lower bound on {{Rcpp}} version.

**Comment by HashRocketSyntax** [comment]
When I published my first Shiny App to a remote R Server:
```
2019/04/23 14:42:54.687002238 Installing httpuv (1.5.1) ... 
# errored out with the following message:
<p id="message">database is locked</p>
```

I rebooted my R Connect Server (EC2 machine) and retried the publishing. This time it passed.

**Comment by jonykoren** [comment]
try to update the package:
"htmltools" 
this is how i fixed the issue
