### ISSUE TITLE
Error when deploying shiny app: Cannot uninstall "six"

### ISSUE THREAD

**Issue by neurospine** [rstudio/shiny#2058]
Hi 

I created a shiny applet which works without problems locally. I have a Windows 10 machine.
However, when I use deploy, I get the following error:

`Installing collected packages: six, funcsigs, pbr, mock, html5lib, bleach, numpy, futures, protobuf, markdown, werkzeug, tensorflow-tensorboard, backports.weakref, enum34, tensorflow
 Found existing installation: six 1.5.2
Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 525783247 failed: Error building image: Build exited with non-zero status: 1
Execution halted`

Has anyone had this issue and does anyone know how I can resolve it? Thank you!

**Comment by wch** [comment]
@neurospine is this still an issue when you try to deploy? Also, if you can provide information on how and where you're deploying to, that would help.

**Comment by jcheng5** [comment]
@javierluraschi Does this look familiar to you? I'm guessing @neurospine is deploying a tensorflow project to shinyapps.io?

**Comment by neurospine** [comment]
@jcheng5 @wch Thanks for your feedback - The error was indeed due to my using TensorFlow and has been resolved with the update last week.
