### ISSUE TITLE
checkboxes reactive after Shiny.unbindAll()

### ISSUE THREAD

**Issue by szymonwartak** [rstudio/shiny#206]
checkboxes don't automatically get assigned shiny-bound-input class and don't seem to have a binding: .data('shiny-input-binding')

I haven't looked deeper into the code, but the result is that calling Shiny.unbindAll() still reacts to changes for checkboxes

**Comment by wch** [comment]
This problem appears to be gone. If you call `Shiny.unbindAll()`, checkboxes are not reactive. For example, if you go to https://gallery.shinyapps.io/004-mpg and run `Shiny.unbindAll()`, the checkbox doesn't do anything, as expected.

There is some old code related to this in shiny.js that can be removed; it's only for compatibility with Shiny <= 0.5.0, and should be safe to remove now. For example:
https://github.com/rstudio/shiny/blob/a0c6feb386ad0279420ec1dfabb15edcb75f9dda/inst/www/shared/shiny.js#L3085-L3126

**Comment by yihui** [comment]
@wch Sorry, but it does not seem to be safe to remove the code there. At least the checkbox input is no longer reactive. A minimal repro example:

```r
library(shiny)
shinyApp(
  ui = fluidPage(checkboxInput('foo', 'Option')),
  server = function(input, output) {
    observe({
      print(input$foo)
    })
  })
)
```

**Comment by wch** [comment]
Oh weird, I thought that was working for me but I guess not. I'll look into a fix.

**Comment by wch** [comment]
I just realized why I didn't see it break: I forgot to re-minify the JS file before testing.
