### ISSUE TITLE
Paging in Rhandsontable.

### ISSUE THREAD

**Issue by AshutoshAgrahari** [rstudio/shiny#2066]
I just want to know how to use paging in Rhandsontable. Currently, I have to display more than 100 rows with 20 columns for editing.
It is now very difficult to view in shinydashboard. Please let me if any solution available.

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests for Shiny itself. This question seems more appropriate for https://github.com/jrowen/rhandsontable/issues.
