### ISSUE TITLE
Shiny won't install after httpuv install (tried solutions in #2030 and #2054)

### ISSUE THREAD

**Issue by lzbb** [rstudio/shiny#2068]
Hello

After an httpuv update, my Shiny app won't run because shiny library fails to load. I have tried to re-install shiny but it is failing due to the version of httpuv installed (see below). I have tried the solutions given in #2030 and #2054 but this is still not working for me. Any help would be much appreciated!

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'httpuv' 1.4.1 is being loaded, but >= 1.4.3 is required
ERROR: lazy loading failed for package 'shiny'

**Comment by mschilli87** [comment]
@lzbb: How did you solve the issue in the end?

**Comment by MRuzzante** [comment]
I encountered the same issue and solved it by updating the R version to x64 3.5.1 and RStudio to 1.1.456. After this, the `httpuv` package update ran properly and, therefore, `shiny` could be updated to the 1.1 version too.
