### ISSUE TITLE
shiny 1.1 on macOS R 3.4.4 not available because "later" 0.7.2 is not available

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#2069]
FYI Although shiny 1.1 is available for (almost) all versions now (!) for some reason `later` 0.7.2 hasn't been built for macOS old-release (3.4.4) 20 days after it was submitted. So shiny 1.1 is not available for macOS old-release either and won't be until `later` is built. I'm not sure what is going on with CRAN and macOS as they already dropped support for R 3.3.

![image](https://user-images.githubusercontent.com/2998956/40324065-31b91cca-5cec-11e8-88eb-5d4e789aeaaa.png)

https://cran.r-project.org/web/checks/check_results_later.html

**Comment by vnijs** [comment]
Wow. CRAN already dropped support for R 3.3 and now R 3.4 as well it seems. Any idea if this is something `rhub` could support somehow? (cc @gaborcsardi)

**Comment by vnijs** [comment]
Looks like packages have seen updated now. Hopefully support for oldrel on mac will continue!

**Comment by wch** [comment]
That's good to hear!
