### ISSUE TITLE
IPv6 address should be bracketed within HTTP URLs

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/shiny#2074]
When Shiny creates the HTTP URL from a running server indicating the address it is reachable on, it should bracket any IPv6 address within the URL.

For example, if binding on `::1` port `5873` (IPv6 loopback), the resulting http URL should be: `http://[::1]:5873`. Currently, Shiny will generate the URL without brackets, like `http://::1:5873` which is an invalid URL.

**Comment by wch** [comment]
Testing notes:

This will run an application on an IPv6 loopback address:

```R
shiny::runExample('01_hello', host = "::1")
```

If you run this with Shiny 1.1.0, it says:

```
Listening on http://::1:7405
```

(with a randomly chosen port). Also, that same address that appears in the viewer window. Clicking on the "Open in Browser" button doesn't do anything (RStudio 1.2.752, Mac).

If you run this with the dev version of Shiny, it shows the correct address, `http://[::1]:7405`. As of RStudio 1.2.752, the viewer window goes to that address but doesn't actually load the app. However, clicking on "Open in Browser" causes a new web browser to open up at that address. 

@shalutiwari I believe that's the correct behavior, and in some future version of RStudio, the viewer window will load the app. @kfeinauer, is that correct?

**Comment by kfeinauer** [comment]
This seems to be working fine on RSP. I will have to try reproducing tomorrow with other platforms.

**Comment by kfeinauer** [comment]
There was indeed an issue on the desktop platforms. Fixed this in https://github.com/rstudio/rstudio/commit/acd36b29866a6f4b7ccb955f20bd5bdb5bd5e3a0

**Comment by wch** [comment]
Great, I'm glad to hear it's fixed!

**Comment by shalutiwari** [comment]
I installed the latest daily build 1.2.755 and ran the test  but I still cannot the app in the viewer

**Comment by kfeinauer** [comment]
@shalutiwari Are you sure you are using the dev version of shiny? 

`devtools::install_github("rstudio/shiny")`

When running the command @wch noted above, it should pop up a separate viewer window and display there. The actual `Viewer` pane will just show a blank white screen (this particular behavior is not related to ipv6 in any way).

**Comment by shalutiwari** [comment]
@kfeinauer  Let me check that and try again.

**Comment by shalutiwari** [comment]
@kfeinauer Still not working for me. The shiny version that I have is 
shiny                * 1.1.0.9000 2018-06-20 Github (rstudio/shiny@026b727)

**Comment by shalutiwari** [comment]
Verified.

**Comment by kfeinauer** [comment]
@wch we hashed this out offline - the confusion was that the app was running in an external window due to IDE settings. Once we changed the settings to use the Viewer pane, everything worked as expected.

**Comment by wch** [comment]
Excellent!
