### ISSUE TITLE
modal issue with leaflet 2.0

### ISSUE THREAD

**Issue by wilcar** [rstudio/shiny#2086]
I am using leaflet 2.0 in Shiny. The Z-index of my overlaying legend is 400 (absolute panels ).
Clicking on bs_button : display of modal  dialogs  is grey and I can't use the close button.  

When I am not displaying  leafletOutput, modal dialog works well.

**Comment by jcheng5** [comment]
Leaflet 2.0.1 was just released to CRAN yesterday and includes a fix for a z-index issue--can you try that first? Thanks!

**Comment by wilcar** [comment]
The Leaflet 2.0.1 release  fix the issue. Thanks for your help !
