### ISSUE TITLE
issue with shiny modal

### ISSUE THREAD

**Issue by jacob7182** [rstudio/shiny#2089]
Hi,

I have a button "launch" clicking on which opens a modal popup. In this popup I have a datatable populated, allowing users to filter records and there is a submit button.  on clicking the submit button,observeEvent(input$submit) it takes the records and populates the parent page of the modal.  I close the modal by calling removeModal().
This works fine the first time.
However if I click the "launch" button second time, it automatically calls the observeEvent of the submit button observeEvent(input$submit)  and takes the records and populates the parent page.
Is there a way to prevent this from happening.  I just want the modal to show up again for user to filter the records.

I tried putting the logic inside submit button in isolate() , but it did not resolve.

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.

**Comment by jacob7182** [comment]
Thanks, I have put this in r studio community as well.  However this issue seems to be a bug in shiny modal, not a usage issue.   On closing of modal dialog, it is not resetting the button click value inside the modal dialog and on opening the dialog again, it behaves as if the button inside is already clicked.
