### ISSUE TITLE
Shiny apps calling each other stopped working in 1.1.0

### ISSUE THREAD

**Issue by andreashandel** [rstudio/shiny#2095]
I have an R package where a main function calls different shiny apps. 
The main function is inside an R script and looks like this:

mainmenu <- function() {
  cond <- 1
    while (cond == 1)
    {
      appname <- NULL
      appDir <- system.file("shinyapps", "MainMenu", package = "DSAIRM")
      appname = shiny::runApp(appDir = appDir)
      if (!is.null(appname) & appname != "Exit")     #run the shiny app chosen
      {
          appDir <- system.file("shinyapps", appname, package = "DSAIRM")
          shiny::runApp(appDir = appDir)
      }
      if (appname == "Exit") {cond = 0} #leave while loop/menu
  }
}

On startup, the script above calls the "MainMenu" shiny app. In that one, users click buttons to choose specific apps. That's implemented in the server as follows:

server <- function(input, output, session) {
  observeEvent(input$BasicBacteria,  {
    stopApp(returnValue = 'BasicBacteria')
  })

observeEvent(input$Exit, {
    stopApp(returnValue = 'Exit')
  })

... And a bunch more choices here...

 })

This will lead the mainmenu shiny app to close, return the name of the app to be started, which then is started by the main script/function above.

It all worked fine with 1.0.5, now under 1.1.0 when a button in the main menu is clicked, the underlying app isn't started, instead the main menu returns right away. I checked to make sure the only thing changing is going from 1.0.5 to 1.1.0. Unfortunately I don't know what's going on, had no luck trying to debug this. Any suggestions on what changed and how I need to update my code?

**Comment by andreashandel** [comment]
For what it's worth: I just tried to see if it might work with the latest shiny version by installing from github, and when I try to start my main R function (shown above) it doesn't start and instead I get:

 Error in .Call("_httpuv_ipFamily", PACKAGE = "httpuv", ip) : 
  "_httpuv_ipFamily" not available for .Call() for package "httpuv"

Not sure if that's useful additional information, but I figured i provide it.

**Comment by jcheng5** [comment]
Can you go back to the latest shiny from CRAN, and see if this code loops for you endlessly, or stops right away:

```r
library(shiny)

while (TRUE) {
  shiny::runApp(shinyApp(
    ui = "Hello",
    server = function(input, output, session) {
      stopApp()
    }
  ))
  message("Got here")
  Sys.sleep(1)
}
```

**Comment by andreashandel** [comment]
It's an endless loop of opening a window, closing it back down, reopening it, etc.

**Comment by andreashandel** [comment]
Also, if this helps: My problem should be fully reproducible by installing my package from
https://github.com/ahgroup/DSAIRM
Start the main menu and click on one of the apps (some of the 'model fitting' apps don't exist yet, rest do). What should (and used to) happen is that the main menu shuts down and the selected app comes up. Now it's just the main menu quickly disappearing and reappearing. 
Thanks!

**Comment by jcheng5** [comment]
@andreashandel I see the problem--the main menu app is calling `stopApp` twice: once for whatever button was clicked, and again in the `onSessionEnded`. Previously, it looks like the second was ignored; now, the second is essentially queued up, and the next app that runs is stopped. I'm not sure what the correct behavior should be, but it'd be for the best if you tried to avoid calling `onSessionEnded` twice. I'd do it like this in your main menu app.R:

```r
server <- function(input, output, session) {

  appNames <- c(
    'BasicBacteria',
    'BasicVirus',
    'VirusandIR',
    'ModelExploration',
    'VirusandTx',
    'DrugResistance',
    'ModelVariants',
    'BasicVirusStochastic',
    'USAnalysis',
    'PkPdModel',
    'BasicModelFit',
    'ConfIntFit',
    'ModelComparison',
    'MultiDataFit',
    'Exit')

  stopping <- FALSE

  lapply(appNames, function(appName) {
    observeEvent(input[[appName]], {
      stopping <<- TRUE
      stopApp(appName)
    })
  })

  session$onSessionEnded(function(){
    if (!stopping) {
      stopApp('Exit')
    }
  })

}
```

Your individual apps call `stopApp` twice as well; I'm less certain of your intentions there, but one approach that worked for me was to keep the `onSessionEnded` the same, but change the `observeEvent(input$exitBtn, ...)` to call `session$close()` instead.
