### ISSUE TITLE
Shiny server falls

### ISSUE THREAD

**Issue by nadrieci** [rstudio/shiny#2104]
Hello, 

I have a shiny server and actually I have been able to upload and use "online" some simple apps, and also the shiny and rmardown test works properly. 
But then, when I try to use my own application (which works locally, on my computer), I get the following error message (I looked in log  -> var/log/shiny-server):

```
 su: ignore --preserve-environment, it's mutually exclusive to --login.
Loading required package: viridisLite
Loading required package: heatmaply

======================
Welcome to heatmaply version 0.14.1

Type citation('heatmaply') for how to cite the package.
Type ?heatmaply for the main documentation.

The github page is: https://github.com/talgalili/heatmaply/
Please submit your suggestions and bug-reports at: https://github.com/talgalili/heatmaply/issues
Or contact: <tal.galili@gmail.com>
======================


Listening on http://127.0.0.1:43894

Execution halted

```

The session info:

```
R version 3.5.0 (2018-04-23)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=es_ES.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=es_ES.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.0
```

I reinstaled both packages, and I also try to call them in R (sudo -i R to use R in console and then library(viridisLite) and library(heatmaply)) and they both works without problem.

When I try to use my App, server gets disconected and I have to restart it (My app starts to charge but when I reach to log issue, stops working)

Maybe the R version has to do with my issue, but I tried to change it unsuccesfully.

Best rewards,

Daniel.

**Comment by alandipert** [comment]
This looks to me like your R code is exiting for some reason, but the reason why is missing from the global error log.

One thing you can do is look at your application error logs. In particular, you should add `preserve_logs true;` to your Shiny Server configuration. Then:

1. restart Shiny Server
1. Visit the application in your browser
1. Inspect the application's error log

In most cases, in my own experience, this problem usually happens when my R code has a bug, or a package I have on my machine isn't installed on the server. Looking at the application error log will shed some light.

**Comment by nadrieci** [comment]
Thank you very much Alandipert, 
I have finally been able to solve the problem. It has to do with the shiny-server version (I have uploaded to the latest one) and also I have deleted the additional DNS server. 

Good bye, Daniel!
