### ISSUE TITLE
Shiny package disappeared from Rstudio and does not install

### ISSUE THREAD

**Issue by ravikafle** [rstudio/shiny#2109]
Hi,
I've come through a strange situation where the shiny package has disappeared from RStudio and does not download when i try install.packages("shiny"). Although I have been using R since some time now, I know nothing about Java, HTML etc. programming. 
I'd be grateful to have a solution to this issue.

**Comment by jcheng5** [comment]
Can you paste the console output you see when you try to install?

**Comment by ravikafle** [comment]
Restarting R session...

> install.packages(c("bit", "callr", "data.table", "digest", "dplyr", "httpuv", "later", "mapview", "processx", "purrr", "purrrlyr", "Rcpp", "rgdal", "rgeos", "rJava", "rjson", "rlang", "RMySQL", "RSQLite", "sf", "sourcetools", "sp", "spam", "statnet.common", "stringi", "tidyr", "tm", "units", "utf8", "yaml", "zoo"))
Installing packages into ‘C:/Users/Daniel Brian/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  dependency ‘slam’ is not available

  There are binary versions available but the source versions are later:
                 binary  source needs_compilation
bit              1.1-12  1.1-14              TRUE
callr             2.0.3   2.0.4              TRUE
data.table     1.10.4-3  1.11.4              TRUE
digest           0.6.14  0.6.15              TRUE
dplyr             0.7.4   0.7.5              TRUE
httpuv            1.4.1 1.4.4.1              TRUE
later             0.7.1   0.7.3              TRUE
mapview           2.3.0   2.4.0              TRUE
processx        2.0.0.1   3.1.0              TRUE
purrr             0.2.4   0.2.5              TRUE
purrrlyr          0.0.2   0.0.3              TRUE
Rcpp            0.12.16 0.12.17              TRUE
rgdal            1.2-18   1.3-2              TRUE
rgeos            0.3-26  0.3-28              TRUE
rJava             0.9-9  0.9-10              TRUE
rjson            0.2.15  0.2.20              TRUE
rlang             0.2.0   0.2.1              TRUE
RMySQL          0.10.14 0.10.15              TRUE
RSQLite           2.1.0   2.1.1              TRUE
sf                0.6-1   0.6-3              TRUE
sourcetools       0.1.6   0.1.7              TRUE
sp                1.2-7   1.3-1              TRUE
spam              2.1-4   2.2-0              TRUE
statnet.common    4.0.0   4.1.2              TRUE
stringi           1.1.7   1.2.3              TRUE
tidyr             0.8.0   0.8.1              TRUE
tm                0.7-3   0.7-4              TRUE
units             0.5-1   0.6-0             FALSE
utf8              1.1.3   1.1.4              TRUE
yaml             2.1.18  2.1.19              TRUE
zoo               1.8-1   1.8-2              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/bit_1.1-12.zip'
Content type 'application/zip' length 217979 bytes (212 KB)
downloaded 212 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/callr_2.0.3.zip'
Content type 'application/zip' length 1028797 bytes (1004 KB)
downloaded 1004 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/data.table_1.10.4-3.zip'
Content type 'application/zip' length 1506783 bytes (1.4 MB)
downloaded 1.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/digest_0.6.14.zip'
Content type 'application/zip' length 173830 bytes (169 KB)
downloaded 169 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/dplyr_0.7.4.zip'
Content type 'application/zip' length 2897358 bytes (2.8 MB)
downloaded 2.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/httpuv_1.4.1.zip'
Content type 'application/zip' length 1118480 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/later_0.7.1.zip'
Content type 'application/zip' length 605749 bytes (591 KB)
downloaded 591 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/mapview_2.3.0.zip'
Content type 'application/zip' length 3053587 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/processx_2.0.0.1.zip'
Content type 'application/zip' length 91282 bytes (89 KB)
downloaded 89 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/purrr_0.2.4.zip'
Content type 'application/zip' length 244026 bytes (238 KB)
downloaded 238 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/purrrlyr_0.0.2.zip'
Content type 'application/zip' length 671671 bytes (655 KB)
downloaded 655 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/Rcpp_0.12.16.zip'
Content type 'application/zip' length 4358189 bytes (4.2 MB)
downloaded 4.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rgdal_1.2-18.zip'
Content type 'application/zip' length 32719835 bytes (31.2 MB)
downloaded 31.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rgeos_0.3-26.zip'
Content type 'application/zip' length 1727163 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rJava_0.9-9.zip'
Content type 'application/zip' length 716027 bytes (699 KB)
downloaded 699 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rjson_0.2.15.zip'
Content type 'application/zip' length 561644 bytes (548 KB)
downloaded 548 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/rlang_0.2.0.zip'
Content type 'application/zip' length 754726 bytes (737 KB)
downloaded 737 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/RMySQL_0.10.14.zip'
Content type 'application/zip' length 2433185 bytes (2.3 MB)
downloaded 2.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/RSQLite_2.1.0.zip'
Content type 'application/zip' length 2084378 bytes (2.0 MB)
downloaded 2.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/sf_0.6-1.zip'
Content type 'application/zip' length 39296219 bytes (37.5 MB)
downloaded 37.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/sourcetools_0.1.6.zip'
Content type 'application/zip' length 527805 bytes (515 KB)
downloaded 515 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/sp_1.2-7.zip'
Content type 'application/zip' length 1530644 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/spam_2.1-4.zip'
Content type 'application/zip' length 1887953 bytes (1.8 MB)
downloaded 1.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/statnet.common_4.0.0.zip'
Content type 'application/zip' length 114076 bytes (111 KB)
downloaded 111 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/stringi_1.1.7.zip'
Content type 'application/zip' length 14289043 bytes (13.6 MB)
downloaded 13.6 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/tidyr_0.8.0.zip'
Content type 'application/zip' length 899429 bytes (878 KB)
downloaded 878 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/tm_0.7-3.zip'
Content type 'application/zip' length 1266496 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/utf8_1.1.3.zip'
Content type 'application/zip' length 193991 bytes (189 KB)
downloaded 189 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/yaml_2.1.18.zip'
Content type 'application/zip' length 185468 bytes (181 KB)
downloaded 181 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/zoo_1.8-1.zip'
Content type 'application/zip' length 915465 bytes (894 KB)
downloaded 894 KB

package ‘bit’ successfully unpacked and MD5 sums checked
package ‘callr’ successfully unpacked and MD5 sums checked
package ‘data.table’ successfully unpacked and MD5 sums checked
package ‘digest’ successfully unpacked and MD5 sums checked
package ‘dplyr’ successfully unpacked and MD5 sums checked
package ‘httpuv’ successfully unpacked and MD5 sums checked
package ‘later’ successfully unpacked and MD5 sums checked
package ‘mapview’ successfully unpacked and MD5 sums checked
package ‘processx’ successfully unpacked and MD5 sums checked
package ‘purrr’ successfully unpacked and MD5 sums checked
package ‘purrrlyr’ successfully unpacked and MD5 sums checked
package ‘Rcpp’ successfully unpacked and MD5 sums checked
package ‘rgdal’ successfully unpacked and MD5 sums checked
package ‘rgeos’ successfully unpacked and MD5 sums checked
package ‘rJava’ successfully unpacked and MD5 sums checked
package ‘rjson’ successfully unpacked and MD5 sums checked
package ‘rlang’ successfully unpacked and MD5 sums checked
package ‘RMySQL’ successfully unpacked and MD5 sums checked
package ‘RSQLite’ successfully unpacked and MD5 sums checked
package ‘sf’ successfully unpacked and MD5 sums checked
package ‘sourcetools’ successfully unpacked and MD5 sums checked
package ‘sp’ successfully unpacked and MD5 sums checked
package ‘spam’ successfully unpacked and MD5 sums checked
package ‘statnet.common’ successfully unpacked and MD5 sums checked
package ‘stringi’ successfully unpacked and MD5 sums checked
package ‘tidyr’ successfully unpacked and MD5 sums checked
package ‘tm’ successfully unpacked and MD5 sums checked
package ‘utf8’ successfully unpacked and MD5 sums checked
package ‘yaml’ successfully unpacked and MD5 sums checked
package ‘zoo’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\AppData\Local\Temp\RtmpKGpKap\downloaded_packages
installing the source package ‘units’

trying URL 'https://cran.rstudio.com/src/contrib/units_0.6-0.tar.gz'
Content type 'application/x-gzip' length 912393 bytes (891 KB)
downloaded 891 KB

* installing *source* package 'units' ...
** package 'units' successfully unpacked and MD5 sums checked

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.0/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.0/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="units.dll" OBJECTS="RcppExports.o io.o udunits.o"' had status 127
ERROR: compilation failed for package 'units'
* removing 'C:/Users/Documents/R/win-library/3.3/units'
* restoring previous 'C:/Users/Documents/R/win-library/3.3/units'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.0/bin/x64/R" CMD INSTALL -l "C:\Users\Daniel Brian\Documents\R\win-library\3.3" C:\Users\AppData\Local\Temp\RtmpKGpKap/downloaded_packages/units_0.6-0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘units’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\AppData\Local\Temp\RtmpKGpKap\downloaded_packages’
>

**Comment by ravikafle** [comment]
This is what come up when i do:    install.packages("shiny")

**Comment by wch** [comment]
It looks like the problem is happening when you try to install the dependency package `units`. It is trying to compile the packages from source because you have a somewhat old version of R for which binary packages are not available.

The easiest solution would be to upgrade your version of R to the latest, 3.5.0. Otherwise, you need to install [Rtools](https://cran.r-project.org/bin/windows/Rtools/) in order to compile the packages from source.

**Comment by ravikafle** [comment]
I upgraded R version and it worked!
Thank you so much, Joe!!
