### ISSUE TITLE
StockVis example broken

### ISSUE THREAD

**Issue by GISKid** [rstudio/shiny#2112]
The stockvis shiny example here: [https://shiny.rstudio.com/tutorial/written-tutorial/lesson6/](https://shiny.rstudio.com/tutorial/written-tutorial/lesson6/) is broken. 

Downloading the data from that website and running the app gives this error:

> ‘getSymbols.google’ is defunct. Google Finance stopped providing data in March, 2018. You could try setting src = "yahoo" instead. See help("Defunct") and help("quantmod-defunct")

Replacing the src to yahoo seems to resolve the issue.

`dataInput <- reactive({
    getSymbols(input$symb, src = "yahoo", 
               from = input$dates[1],
               to = input$dates[2],
               auto.assign = FALSE)
`

**Comment by jcheng5** [comment]
Thanks @GISKid!
