### ISSUE TITLE
get original path, file input

### ISSUE THREAD

**Issue by aguerodev** [rstudio/shiny#2113]
How can I access the original path using file input?

**Comment by mschilli87** [comment]
What is the 'original path'?

**Comment by wch** [comment]
If you mean that you want to get the path of the file on the client, that is not possible due to web browser security restrictions.

**Comment by daattali** [comment]
@aguerodev if you try to Google for "javascript file input original path" you'll be pointed to many threads where people have asked this question and the answer is always that it's not possible by design. So it's not a shiny thing, it's a web thing.
