### ISSUE TITLE
UI Grey (Crashes): Connecting to Remote Computer through IP:PORT

### ISSUE THREAD

**Issue by jtelleria** [rstudio/shiny#2114]
If I use the following approach to connect to a remote server application for development purposes:

```r
require(shiny)
folder_address = 'H:/path to app'

x <- system("ipconfig", intern=TRUE)
z <- x[grep("IPv4", x)]
ip <- gsub(".*? ([[:digit:]])", "\\1", z)
print(paste0("the Shiny Web application runs on: http://", ip, ":1234/"))

runApp(folder_address, launch.browser=FALSE, port = 1234, host = ip)
```
When I connect from the Client Computer (To a Remote Server IP) the UI gets Grey, and the app does not work. If I run the same app from the Local Computer, it works.

Is this intended?
Juan

**Comment by jtelleriar** [comment]
It was an issue with corporate proxy.
