### ISSUE TITLE
appendTab and insertTab do not work correctly on Connect

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#2116]
To see the problem:

* Visit https://beta.rstudioconnect.com/content/3819/
* Click the "Add 'Dynamic' Tab" button
* Click on the newly-created tab
* Click the button two more times

Clicking on the second and third new tabs will have the same content. The problem is that the tab IDs have `NaN`. 

![image](https://user-images.githubusercontent.com/86978/42187941-855c83f2-7e17-11e8-8573-931cca99243a.png)

They get `NaN` because the pattern that Shiny is looking for is a relative URL like `href="#tab-1093-1"`, not an absolute one like `href="https://beta.rstudioconnect.com/content/3819/_w_9c84ffcd/#tab-1093-1"`.

This problem does not happen when running locally. The problem likely has to do with a `<base>` tag in the HTML of a deployed app, added by shiny-server-client.

This is the code for the app:

```R
options(shiny.minified = FALSE)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      actionButton("add", "Add 'Dynamic' tab")
    ),
    mainPanel(
      tabsetPanel(id = "tabs",
        tabPanel("Hello", "This is the hello tab")
      )
    )
  )
)
server <- function(input, output, session) {
  n <- 0
  observeEvent(input$add, {
    appendTab(inputId = "tabs",
      {
        n <<- n + 1
        tabPanel(
          "Dynamic",
          paste("Content for dynamic tab", n)
        )
      }
    )
  })
}

shinyApp(ui, server)
```

**Comment by paddybeefcakes** [comment]
@wch I'm also having this same issue on Shiny Server. We recently got the server version of Shiny and can confirm that this bug never appeared when running the apps locally. The odd thing is that the application correctly appends about two tabs before I start seeing the NaN issue.

**Comment by kapsner** [comment]
I can confirm this issue. I am experiencing as described above. Appending tabs works locally but deploying the app on "shinyapps.io" leads to the abovementioned issue.

Does there already exist any solution?

**Comment by PaulC91** [comment]
+1 also having this issue on shinyapps.io 
Is there a deployment options that doesn't currently have this issue?

**Comment by rmccombie** [comment]
Issue reported in `#37188`.

**Comment by marrojwala** [comment]
Has anyone found a workaround for this?

**Comment by kapsner** [comment]
I have changed all apps to use the shinydashboard package (https://rstudio.github.io/shinydashboard/) where this issue does not occur.

**Comment by marrojwala** [comment]
@kapsner Are you using tabItems and tabItem instead of tabsetPanel and tabPanel? If yes, please let me know how.

**Comment by kapsner** [comment]
@marrojwala Yes, I am using tabItems/tabItem instead. You can have a look at my code to see how I am doing this: https://github.com/kapsner/BiasCorrector/blob/master/BiasCorrector/app/ui.R

It was a bit tricky to figure out how to handle the namespace stuff when moving the ui-code to external files, however it now works perfectly. To keep it easy, you can define all ui-code in the ui.R file in the same manner as you would do with tabPanel.

**Comment by wch** [comment]
Investigating with @schloerke, it looks like the change is coming from here:
 https://github.com/rstudio/shiny-server-client/blob/eba5e90/dist/shiny-server-client.js#L1352-L1376
