### ISSUE TITLE
Is it possible to disable close [x] mark on the dialogViewer()

### ISSUE THREAD

**Issue by rudreshahk** [rstudio/shiny#2119]
Is it possible to disable the close [x] mark on the top right corner of the dialogViewer()? I wanted to provide my own Cancel Button. 

The background is that, when i invoke some other window from Shiny dialogViewer, i want to block the user from closing the dialogViewer unless the other window is closed. With the custom Cancel button, i can disable custom "Cancel" button when the child window is active. But still user can close the dialogViewer using the close [x] mark on top right corner.

See the image below:

![image](https://user-images.githubusercontent.com/14134586/42342552-0c5d3268-80b4-11e8-8634-b94ad8f8bd8a.png)

**Comment by jcheng5** [comment]
This would be a question for https://github.com/rstudio/rstudio. Thanks.
