### ISSUE TITLE
1 non-functioning conditionalPanel in app causes all conditionalPanels to break

### ISSUE THREAD

**Issue by OscarChangCC** [rstudio/shiny#2121]
Hi,

I am not sure if this is a known issue but there has not been any thread on a similar issue I could find.
In short, if there is a conditionalPanel in a shinyApp that is not working, all other conditionalPanels will not work (permanently shown). 

Code for reproducible example:
## Working app (this works as intended)
library(shiny)
list_choice <- list("option1" = "option1",
                    "option2" = "option2",
                    "option3" = "option3")

ui <- shinyUI(
  fluidPage(
  selectInput("choice",label = "Reproducible Example",choices = c(list_choice),selectize = TRUE),
  conditionalPanel(condition = "input.choice == 'option1'",
                   h4("Option1 chosen")),
  conditionalPanel(condition = "input.choice != 'option1' ",
                   h4("Option1 not chosen"))))

server <- shinyServer(function(input,output)
  return(NULL)
)
shinyApp(ui,server)

#### but the result is both panels not working
library(shiny)
list_choice <- list("option1" = "option1",
                    "option2" = "option2",
                    "option3" = "option3")

ui <- shinyUI(
  fluidPage(
  selectInput("choice",label = "Reproducible Example",choices = c(list_choice),selectize = TRUE),
#### The below line is coded to break the panel  
 conditionalPanel(condition = "input.choice == option1",
                   h4("Option1 chosen")),
  conditionalPanel(condition = "input.choice != 'option1' ",
                   h4("Option1 not chosen")),
  selectInput("choice",label = "Reproducible Example",choices = c(list_choice),selectize = TRUE),
  conditionalPanel(condition = "input.choice == 'option1'",
                   h4("Option1 chosen")),
  conditionalPanel(condition = "input.choice != 'option1' ",
                   h4("Option1 not chosen"))))

server <- shinyServer(function(input,output)
  return(NULL)
)
shinyApp(ui,server)

**Comment by gexijin** [comment]
I was able to reproduce this issue.

**Comment by cpsievert** [comment]
I think the problem here is there are two input ids with the same value (`"choice"`).
