### ISSUE TITLE
Slow load times on shinyapps.io posted on Community

### ISSUE THREAD

**Issue by schloerke** [rstudio/shiny#2131]
From Curtis:
> Hi Barret - If a community+shiny user asks about why a shinyapps.io apps loads at different rates on Edge/IE11 vs. chrome, do you know who I might ask about that?
Should I perhaps suggest they post to the github issues?
> 
> There are actually four different threads on this topic that haven't really been answered very well (mostly pushed by one Medical research user, KB246).
> 
> Just for reference (I don't think it would be a good use of your time to read all these!)
> 1. https://community.rstudio.com/t/unacceptable-load-time-in-shinyapps-io/11167/1
> 2. https://community.rstudio.com/t/bootstrap-min-css-map-showing-in-networking-tab-i-need-to-know-if-this-affect-the-latency-of-my-app-when-i-deploy-it-to-the-shinuapps-io-in-edge/11021 and Joe helped here. 
> 3. https://community.rstudio.com/t/i-have-a-big-shiny-app-runs-very-weill-locally-in-all-browsers-but-when-i-deploy-it-to-the-shinyapps-io-it-runs-very-slow-in-ie11/10812
> 4. Here's another thread related https://community.rstudio.com/t/big-apps-run-slow-in-ie-edge-firefox-but-not-chrome/2989/6 (edited)
> I was also going to suggest, after answering the specific question about IE11 Edge vs chrome, that it would also be a good chance to refer to the resources y'all put out. 
> https://shiny.rstudio.com/articles/scaling-and-tuning.html
> https://www.rstudio.com/resources/videos/make-shiny-fast-by-doing-as-little-work-as-possible/ (edited)

**Comment by schloerke** [comment]
tagging @EconomiCurtis

**Comment by jcheng5** [comment]
I think this is just JavaScript slowness? And using server-side selectize (if he's not) and DT should help a whole lot.

That said, on April 25 in the Shiny team slack channel we had a conversation about slowness on shinyapps.io with Edge that I think only I could reproduce. I was supposed to follow up with the shinyapps.io team but didn't 😞

**Comment by KHBHH** [comment]
:(

**Comment by KHBHH** [comment]
:(

**Comment by jcheng5** [comment]
@KHBHH Would it be possible for you let us access your app on ShinyApps.io? You can email joe@rstudio.com and josh@rstudio.com if you'd rather discuss privately.

**Comment by jcheng5** [comment]
This should be fixed on ShinyApps.io soon if it hasn't been already. It turned out to be a problem with Edge and SockJS's xhr-streaming protocol, which we have (or will) disabled.

**Comment by shreya2105** [comment]
@jcheng5 https://howindialives.shinyapps.io/Mintdashboard/
My Shinyapp has become super slow after deploying. It ran much faster in R studio. What would you suggest I do?

**Comment by jcheng5** [comment]
@shreya2105 It's not related to this issue, but I'd start with simplifying your polygons probably? https://rstudio.github.io/leaflet/shapes.html#simplifying-complex-polygonspolylines
