### ISSUE TITLE
Stopwatch in shiny

### ISSUE THREAD

**Issue by neurospine** [rstudio/shiny#2133]
Hi

Is there a possibility of providing a start- and stoppable stopwatch in shiny? Would it be possible to use it's value in seconds as an input then?

I think an inut function like that could be useful to many users.

Does anyone know about a possibility?
Thank you

**Comment by jcheng5** [comment]
This could be implemented in JavaScript, as a [custom input](https://shiny.rstudio.com/articles/building-inputs.html). (In theory it could be implemented in R, but I'd advise against it as you'd lose time if the R process is being used by multiple sessions simultaneously.) However, this is probably too niche for the Shiny team to implement. We'd be happy to answer questions to anyone trying to implement this though.

Thanks for the suggestion.
