### ISSUE TITLE
Plot interaction - exclude

### ISSUE THREAD

**Issue by fmmattioni** [rstudio/shiny#2140]
I am developing a new app based on this great example:

https://shiny.rstudio.com/gallery/plot-interaction-exclude.html 

However, I would like to know how I could exclude a data point permanently? The way it works now is that whenever I brush over a previously excluded data point, it comes back in.

Any thoughts?

**Comment by tmastny** [comment]
Hi, thanks for the question. This issue tracker is meant for bug reports and feature requests. For general help questions, check out https://community.rstudio.com/c/shiny or https://stackoverflow.com/.
