### ISSUE TITLE
Drag/drop fileInput gives NULL as filename under Ubuntu (ok on Win)

### ISSUE THREAD

**Issue by dmenne** [rstudio/shiny#2142]
Latest Shiny from CRAN, same result from github as of today.

Ok on Edge Browser, Chrome. The following is for Firefox 61.0.1, also tested  with alle Extensions off.

- Use example from fileInput to test
- Using "Browse" button always works
- Drag/drop Works Ok under Windows
- Drag/drop gives NULL filename under Ubuntu/Shiny server 

Worked in previous versions (don't know exactly in which version it started to fail)

**Comment by tmastny** [comment]
Could you include a minimal Shiny app that demonstrates these problems so we can try to replicate it on Firefox?

**Comment by dmenne** [comment]
As mentioned, I used the example from the `fileInput` documentation

**Comment by dmenne** [comment]
And for a real-life application, try `https://apps.menne-biomed.de/breathtestshiny/`.

**Comment by alandipert** [comment]
Thanks for the report @dmenne. I can confirm a problem on Firefox 61.0.1 on Mac, where dropping the file on the `fileInput` has no effect:

![anim](https://user-images.githubusercontent.com/26024/46230146-7ee15f80-c31c-11e8-8814-e97e52d6e676.gif)

It's closer to working on Firefox 55 on Mac, which was one of the last releases before [Quantum](https://en.wikipedia.org/wiki/Quantum_(Mozilla)), where dropping the file works but the input remains green:

![output](https://user-images.githubusercontent.com/26024/46230690-35920f80-c31e-11e8-8382-f10b6c710289.gif)

## Other browsers

Just to make sure this wasn't a larger regression, I tested a few more browsers. Latest Chrome and Safari on Mac work fine. So do Chrome and Edge on Windows 10. IE11 on Windows works with a slight quirk (fileInput remains highlighted after dropping)

**Comment by alandipert** [comment]
This should be fixed in 1.2 via #2203. @dmenne if you have a spare moment, could you please install the v1.2-rc branch from github (`devtools::install_github("rstudio/shiny@v1.2-rc")`) and confirm it's fixed for you?

Thanks again for the report. Feel free to close this issue if you find the problem resolved.

**Comment by dmenne** [comment]
- Reproduced error with Firefox 62 (it was 61  before)
- Everything works fin with 1.2-rc

Thanks
