### ISSUE TITLE
Cannot install Shiny

### ISSUE THREAD

**Issue by pbalegro** [rstudio/shiny#2148]
I have been encountering a problem in installing Shiny in R. Whenever I attempt installing Shiny using the built-in Install Package feature in RStudio or run

`install.package("shiny")`

I encounter the following message:

![image](https://user-images.githubusercontent.com/26851384/43707752-594bc1e8-999b-11e8-99e1-c76e51d287d5.png)

I have tried suggested solutions like (1) installing the latest version of httpuv and (2) reinstalling Rcpp and httpuv packages, then restarting R. I also tried finding all httpuv packages using

`.libPaths()`

 and deleting the httpuv folder. In any case, I still can't get to install the Shiny app.

Are there any other solutions that I can try? Thanks.

**Comment by wch** [comment]
You're using R 3.3, and CRAN no longer updates binary packages for that version of R. If you want to upgrade httpuv to the latest version, you would need to compile it from source, which requires Rtools. The easiest solution is simply to upgrade your version of R, then install shiny. That way you'll get pre-built binary packages from CRAN.

**Comment by pbalegro** [comment]
Thank you! That solved the problem.
