### ISSUE TITLE
cannot install due to issues with httpuv

### ISSUE THREAD

**Issue by snowman55** [rstudio/shiny#215]
I'm trying to install as non-root (OK for other packages like rCharts) but having problems with the httpuv dependency:

Installating from cran 
and github produces the same error:

```
<snip>
mylocalpath/Rpacks/Rcpp/include"   -fpic  -g -O2  -c websockets.cpp -o websockets.o
In file included from websockets.cpp:9:
./base64/base64.hpp:6:7: warning: no newline at end of file
make --directory=libuv \
CC="gcc -std=gnu99" CFLAGS="-g -O2  -fpic" AR="ar" RANLIB="ranlib" \
 libuv.a
make[1]: Entering directory `/tmp/RtmpiYlmb7/R.INSTALL773c2d7993a1/httpuv/src/libuv'
Makefile:26: SRCDIR/event/linux/build.mk: No such file or directory
make[1]: *** No rule to make target `SRCDIR/event/linux/build.mk'.  Stop.
make[1]: Leaving directory `/tmp/RtmpiYlmb7/R.INSTALL773c2d7993a1/httpuv/src/libuv'
make: *** [libuv.a] Error 2
ERROR: compilation failed for package 'httpuv'
* removing '/web/ci/htdocs/vendor/Rpacks/httpuv'
* restoring previous '/web/ci/htdocs/vendor/Rpacks/httpuv'
* installing *source* package 'shiny' ...
** package 'shiny' successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in library.dynam(lib, package, package.lib) :
 shared object 'httpuv.so' not found
ERROR: lazy loading failed for package 'shiny'
* removing 'mylocalpath/Rpacks/shiny'
```

**Comment by mant121** [comment]
Package LibPath Version Priority Depends Imports LinkingTo Suggests Enhances
     License License_is_FOSS License_restricts_use OS_type Archs MD5sum
     NeedsCompilation Built 
I am still getting the above error

**Comment by scottyraymond** [comment]
After globally updating packages in R Studio (via the "Update" button on the Packages tab) I received the error below when attempting to load the shiny library. The updated shiny version is 1.0.5, and httpuv is 1.4.1.

`library(shiny)`

> Error: package or namespace load failed for ‘shiny’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): there is no package called ‘httpuv’

This was solved with:

`install.packages("httpuv")`

However, this error did not occur previously, i.e. before I globally updated the packages.

**Comment by featherduino** [comment]
https://cran.r-project.org/web/packages/BH/index.html

Try Unzipping this package on local then install. 
I felt this overrides the existing cpp header file
