### ISSUE TITLE
Copy reactive function data into a static data frame

### ISSUE THREAD

**Issue by dipsen21** [rstudio/shiny#2151]
I am able to plot the table using the reactive function with DT package as shown below  using Shiny

DT::renderDataTable(DT::datatable(as.matrix(dataset())))

Is it possible to store the above table data in a static data frame that I can use for other purpose ?

for eg. xyz <- dataset()

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
