### ISSUE TITLE
Dynamic variable select issue :: MaxDiff analysis - Shiny reactive error

### ISSUE THREAD

**Issue by Venkatraman92** [rstudio/shiny#2161]
pacman::p_load(devtools)
pacman::p_load(flipMaxDiff)
pacman::p_load(flipStandardCharts)
pacman::p_load(AlgDesign)
pacman::p_load(flipData)
pacman::p_load(Rcpp)
pacman::p_load(foreign)
pacman::p_load(shiny)
pacman::p_load(data.table)

tech.data = foreign::read.spss("http://wiki.q-researchsoftware.com/images/f/f1/Technology_2017.sav", to.data.frame = TRUE)
tech.design = read.csv("http://wiki.q-researchsoftware.com/images/7/78/Technology_MaxDiff_Design.csv")
Model_data  <- tech.data
Design_data <- tech.design

best = Model_data[, c("Q5a_left", "Q5b_left", "Q5c_left",  "Q5d_left", "Q5e_left", "Q5f_left")]
worst = Model_data[, c("Q5a_right", "Q5b_right", "Q5c_right", "Q5d_right", "Q5e_right", "Q5f_right")] 
names <- c("Apple", "Microsoft", "IBM", "Google", "Intel", "Samsung","Sony", "Dell", "Yahoo", "Nokia")

ui <- fluidPage(
  headerPanel("MaxDiff Analysis"), 
  sidebarPanel(
    checkboxGroupInput('BstVar','Best',
                       c("Q5a_left" = "Q5a_left",
                         "Q5b_left" = "Q5b_left",
                         "Q5c_left" = "Q5c_left",
                         "Q5d_left" = "Q5d_left",
                         "Q5e_left" = "Q5e_left",
                         "Q5f_left" = "Q5f_left")),
    checkboxGroupInput('WrstVar','Worst',
                       c("Q5a_right" = "Q5a_right",
                         "Q5b_right" = "Q5b_right",
                         "Q5c_right" = "Q5c_right",
                         "Q5d_right" = "Q5d_right",
                         "Q5e_right" = "Q5e_right",
                         "Q5f_right" = "Q5f_right")),
    submitButton("Submit")
  ),
  # Main panel for displaying outputs ----
  mainPanel(
    
    # Output: Tabset w/ plot, summary, and table ----
    tabsetPanel(type = "tabs",
                #mainPanel(
                
                tabPanel("Analytics Output",tableOutput("pref.shares"),tabPanel("Pie_Chart", plotOutput("PlotMD"))),
                # ),
                tabPanel("Statistics Table By Brand", tableOutput("Mean_SD"),tabPanel("linechart",plotOutput("LineChart"))),
                tabPanel("By Customer preference and Score", verbatimTextOutput("Prob_table"))
                
                
    )
    
  )
)

## Hierarchical Bayes
server <- function(input, output, session) {
  
  best <- renderDataTable({Model_data[,c("BstVar",input$BstVar),drop=FALSE]})
  worst <- renderDataTable({Model_data[,c("WrstVar",input$WrstVar),drop=FALSE]})
  
  fit <- reactive({
  
  fit <- FitMaxDiff(design = tech.design, version = rep(1, nrow(Model_data)),best = best, worst = worst,
                    alternative.names = names, algorithm = "HB",hb.iterations = 100, hb.chains = 1)
  })
  
  Mean_SD <- reactive({
  Mean_SD <- data.frame(fit$parameter.statistics)
  Mean_SD$Brand <- row.names(Mean_SD)
  row.names(Mean_SD)<- NULL
  Mean_SD<- Mean_SD[, c(6,3,1)]
  
  Mean_SD <- Mean_SD[,c("mean","sd")]
  #linechart <- matplot(dat, type = c("b"),pch=1,col = 1:2) #plot
  
  })
 
  ################
  result<- reactive({
  
  result <- FitMaxDiff(design = Design_data,version = rep(1, nrow(Model_data)),
                       best = best,worst = worst,alternative.names = names,n.classes = 5,output = "Classes")
  # respondent.shares = prop.table(exp(as.matrix( (flipMaxDiff::RespondentParameters(result) ) ) ), 1)
  
  })
  
  pref.shares <- reactive({
  
  pref.shares = result$class.preference.shares[, 6]
  pref.shares = data.frame(sort(pref.shares, decreasing = TRUE) * 100)
  pref.shares$Brand <- row.names(pref.shares)
  row.names(pref.shares)<- NULL
  pref.shares<- pref.shares[, c(2,1)]
  data.table::setnames(pref.shares,"sort.pref.shares..decreasing...TRUE....100","Values")
  
  })
  ##################
  ## Probility score
  Prob_Score <- reactive({
    
  Prob_Score <- data.frame(fit$respondent.probabilities)
  
 
   })
  
  output$pref.shares <- renderTable({data.frame(pref.shares)})
  output$PlotMD <- renderPlot({ pie(pref.shares$Values,labels = pref.shares$Brand, col=rainbow(length(pref.shares$Brand)),main="Pie Chart of Brands")})
  output$Mean_SD <- renderTable({Mean_SD})
  output$Prob_table <- renderPrint({Prob_Score})
  output$LineChart <- renderPlot({matplot(Mean_SD, type = c("b"),pch=1,col = 1:2)})
  
}

shinyApp(ui = ui, server = server)

My error is ::

Listening on http://127.0.0.1:6422
Warning: Error in as.data.frame.default: cannot coerce class ‘c("reactiveExpr", "reactive")’ to a data.frame
  [No stack trace available]
Warning: Error in $: object of type 'closure' is not subsettable
  [No stack trace available]

**Comment by wch** [comment]
There is a place where you are calling `data.frame(pref.shares)`, but you should be doing `data.frame(pref.shares())`.

Also: this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
