### ISSUE TITLE
Error - Reactive context was created in one process and accessed from another

### ISSUE THREAD

**Issue by pfgherardini** [rstudio/shiny#2163]
Hi,

I am having an issure with Shiny (I am on version 1.1.0). 

I wrote a Shiny app that, upon pressing an actionButton, calls a function that uses parallel::mclapply internally. On MacOS (haven't been able to reproduce this on Windows), I get an error message complaining that

`Reactive context was created in one process and accessed from another`

I think the code was introduced in commit https://github.com/rstudio/shiny/commit/35d1747bc35a08cf54e1a5b289cad082ccdc701a

I have definitely traced this down to the use of parallel::mclapply, as everything works fine with regular lapply.

Any suggestions?

Thanks

**Comment by wch** [comment]
Can you provide a minimal reproducible example?

**Comment by jjlynch2** [comment]
I'm also having this issue after passing a reactive value to a function that calls mclapply using that argument. However, calling the argument variable name within the function prior to calling mclapply allows it to run without issues. My code has worked for the last year without issues until a recent update caused this problem. I'll try to add a reproducible example when I can.

**Comment by wch** [comment]
@jjlynch2 In your case, the error is being thrown correctly -- it's there to save you from having problems. `mclapply` uses forked processes to run the function, so any side effects that occur in the function will not affect the main process.

For example, if you try to modify an environment from within a `mclapply`, it doesn't work:

```R
e <- new.env()
parallel::mclapply(c("a", "b", "c"), function(x) {
  e[[x]] <- x
  123
})
# [[1]]
# [1] 123
# 
# [[2]]
# [1] 123
# 
# [[3]]
# [1] 123


e$a
# NULL
e$b
# NULL
e$c
# NULL
```

In the case of reactivity, when you access a reactive value or invoke a reactive expression, there is a side effect: Shiny tracks the reactive dependency so that it knows when it needs to re-execute the code in the future.

The best course of action is to execute the reactive expression outside of the `mclapply` and store the value in a variable (or in the case of a reactive value, just store it in a regular variable), then pass that to `mclapply`.

**Comment by jjlynch2** [comment]
@wch After passing a reactive value through a function, shouldn't it be stored as a new variable within the function anyway due to scoping rules?

**Comment by wch** [comment]
@jjlynch2 Can you provide an example of what exactly you mean? I can think of a couple different ways to interpret what you wrote.

**Comment by jjlynch2** [comment]
@wch My Shiny app is calling a function in another package that uses mclapply. The reactive value being passed from the Shiny app to that function call, which then passes it to mclapply, is just a single numerical value that never changes. Previously this never caused any issues as the function in the other package has its own scoping rule.

**Comment by wch** [comment]
@jjlynch2 A reproducible example would help.

**Comment by jcheng5** [comment]
@jjlynch2 Does the error go away if you call `force()` on the value inside the function call (but before the call to mclapply)?

You never would've seen this error in previous versions of Shiny as the check is new, but the scoping rules are unchanged.

**Comment by pfgherardini** [comment]
@jcheng5  let me try that.

Unfortunately setting up a reproducible example is not easy for me, as it seems to be Mac (and maybe Linux?) specific. I am on windows, and I know that mclapply works differently on windows (this came in as a bug report on a package I wrote, and was quite hard to track down).

What I can tell you is that this line in the shiny server

https://github.com/ParkerICI/grappolo/blob/90d6f013a98b97b31c47cadd16da02bd8ca654c8/inst/shinyGUI/server.R#L112

calls this function that uses `mclapply`

https://github.com/ParkerICI/grappolo/blob/90d6f013a98b97b31c47cadd16da02bd8ca654c8/R/cluster.R#L207

I know that this is the source of the problem because:

1) It doesn't happen with shiny 1.0.5 (which is the release before that commit I referenced above)
2) The error does not happen with regular lapply (as opposed to mclapply)

I guess I am not understanding what would trigger the invalidation of the reactive context. I may be assigning (using `<-`) to some of those variables in the functions that get called from mclapply, but in a call-by-value fashion (i.e. I am not trying to assign to the original variable, just to the local copy). Is that what causes the problem?

**Comment by jcheng5** [comment]
As for why this doesn't happen on Windows, Windows doesn't use forking at all, so it's not possible for delayed evaluation to "leak" across from the parent to child process like this. Instead, the arguments are all resolved in the parent. (I'm assuming, I haven't tried it. But I bet that `what_pids` would return the same results as calling `Sys.getpid()` in the parent process, which would confirm it.)

**Comment by jjlynch2** [comment]
@jcheng5 Thanks for the explanation, that makes a lot more sense regarding the lazy evaluation. Force() allows it to run.

**Comment by pfgherardini** [comment]
thanks @jcheng5 for the incredibly detailed explanation. I'll try the force solution tomorrow. Just as a suggestion, maybe it's worth adding to the docs in some fashion?

**Comment by pfgherardini** [comment]
Ok using `force` solved the problem. Thanks again

**Comment by earnaud** [comment]
Hi,
I am experiencing a similar issue (here: https://github.com/earnaud/MetaShARK/issues/29) with the error message "Reactive context was created in one process and invalidated from another." 
The `force()` trick does not make it. But if I take a `browser()` breakpoint the line before the issue, I can execute the bugging line. By this method, resuming script execution lets the app work normally. But - obviously - I would like to avoid such trick as executing two times the same line of code, the first one triggering the bug without stopping, the second one allowing to pass over the bug.

If this question shall open a new issue, please tell me, I will do accordingly.

**Comment by laresbernardo** [comment]
After lots of hours debugging a similar issue but using `foreach` within a function that was being called in shiny, all parameters must be wrapped with `isolate()`. Wasn't obvious to me but this fixed the issue. Inspired by [this reply from SO](https://stackoverflow.com/a/46186148).
