### ISSUE TITLE
subscript out of bounds

### ISSUE THREAD

**Issue by germanlopezvalenzuela** [rstudio/shiny#2181]
Dear all, I am new to R and I am trying to create an app for analysing a water quality plot, but I get this error message:

Listening on http://127.0.0.1:4254
Warning: Error in [: subscript out of bounds
  [No stack trace available]

This is whatI typed. I would really appreaciate any guidance on this topic. Thanks.

```r
ui <-fluidPage(
  titlePanel("Water Quality"),
  sidebarLayout(
    sidebarPanel(
      selectInput("Con", "Concentration:",
                  choices = colnames(water_quality)),
      hr(),
      helpText("Data from ANA 2014")
    ),
    mainPanel(
      plotOutput("plot1")
    )
  )
)


server<-function(input, output) {
  output$plot1 <- renderPlot({
    barplot(water_quality[,input$Con],
            main = input$Con,
            ylab="Concentration",
            xlab="Stations")
  })
}


shinyApp(ui, server)
```

**Comment by schloerke** [comment]
@germanlopezvalenzuela 

We are still missing your `water_quality` variable.  You can capture the content of it by using `dput(water_quality)`.

If I set `water_quality <- iris[1:4]` and I copy and paste your app in my R session and it works.

```r
library(shiny)
water_quality <- iris

ui <-fluidPage(
  titlePanel("Water Quality"),
  sidebarLayout(
    sidebarPanel(
      selectInput("Con", "Concentration:",
                  choices = colnames(water_quality)),
      hr(),
      helpText("Data from ANA 2014")
    ),
    mainPanel(
      plotOutput("plot1")
    )
  )
)


server<-function(input, output) {
  output$plot1 <- renderPlot({
    barplot(water_quality[,input$Con],
            main = input$Con,
            ylab="Concentration",
            xlab="Stations")
  })
}

shinyApp(ui, server)
```

Can you please include the output of `dput(water_quality)`?

**Comment by germanlopezvalenzuela** [comment]
Dear @schloerke Thanks a lot! I tried your code with iris and it worked. Then I tried it again with my data which is an excel spreadsheet with the same distribution of iris data and it also worked.

Thanks!
