### ISSUE TITLE
shiny displays a "div row div row..."string when the fluidRow is set into a variable

### ISSUE THREAD

**Issue by porfila** [rstudio/shiny#2185]
tabPanelRows<-c(fluidRow(column(10,DT::dataTableOutput("x"))),
                fluidRow(column(10,downloadButton("dx","Download"))))

ui<-fluidPage(
  titlePanel(PPtitle),
   tabsetPanel(tabPanel("Panel Title",tabPanelRows)
  )

This will show "div row div row ..." line on the top of the screen.

**Comment by nteetor** [comment]
When creating a list of tag elements use `list()` or `tagList()` instead of `c()`. 

```R
library(shiny)

tabPanelRows <- list(
  fluidRow(
    column(
      width = 10, 
      DT::dataTableOutput("x")
    )
  ),
  fluidRow(
    column(
      width = 10, 
      downloadButton("dx", "Download")
    )
  )
)

PPtitle <- "Max PP"

ui <- fluidPage(
  titlePanel(PPtitle),
  tabsetPanel(
    tabPanel(
      "Panel Title",
      tabPanelRows
    )
  )
)
```
