### ISSUE TITLE
Selectize optgroup bug in shiny-examples 023-optgroup-server

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shiny#2192]
https://github.com/rstudio/shiny-examples/tree/master/023-optgroup-server

![023](https://user-images.githubusercontent.com/1365941/46028192-89e68680-c0b5-11e8-967f-8969b6920d8a.gif)

**Comment by jcheng5** [comment]
Here's the commit: https://github.com/rstudio/shiny/commit/165ce26b2f9e3b6e5b9dcad869d0282db7805d06

I'm still investigating, but here's what I've noticed so far.

Here's what the data returned from the server looks like before this commit:
```
// Good
[
  {
    "Class": "1st",
    "Sex": "Male",
    "Age": "Child",
    "Survived": "No",
    "Freq": 0,
    "value": 1,
    "label": "Male, Child, No"
  },
  {
    "Class": "2nd",
    "Sex": "Male",
    "Age": "Child",
    "Survived": "No",
    "Freq": 0,
    "value": 2,
    "label": "Male, Child, No"
  },
...
```

and here's after:

```
// Bad
[
  {
    "label": "1st",
    "value": "1st",
    "group": "Class"
  },
  {
    "label": "2nd",
    "value": "2nd",
    "group": "Class"
  },
...
```

**Comment by jcheng5** [comment]
Also, this app sets optgroups in the client side, and apparently expects them to stick around as the server results are updated; but this commit added a call to `clearOptionGroups()` during initialization when it notices it's a URL-based control.

**Comment by jcheng5** [comment]
Also reported by a user: https://github.com/rstudio/shiny/issues/2172
