### ISSUE TITLE
updateDateInput changes the initial date

### ISSUE THREAD

**Issue by GaGaMan1101** [rstudio/shiny#2204]
Within R shiny, `dateInput("date", "date:", value = "2018-10-07"))` will always dispaly `2018-10-06` in the UI all the time.

**Below is my actual case:**
I set the server time zone to Sys.setenv(TZ=" Australia/Melbourne") in my R code.
2018-10-07 is the DayLight saving transition date in Australia.

I run the local test of my Shiny APP. However, when the client side updateDateinput with a value of 2018-10-07 from my DataBase, it immediately changed to 2018-10-06.

This has caused so much trouble for me. Not sure where this issue comes from, browser, Shiny Package?

I think the date component calculation from Shiny might have some problems.

**Comment by GaGaMan1101** [comment]
@tsmuse

**Comment by jcheng5** [comment]
Hmmm, I'm not able to reproduce this. Can you try this again, and tell me what your system date/time is when you repro it?

**Comment by jcheng5** [comment]
Here's the code I'm using:

```r
library(shiny)

ui <- fluidPage(
  dateInput("date", "date:", value = "2018-10-01")
)

server <- function(input, output, session) {
  updateDateInput(session, "date", value = "2018-10-07")
}

shinyApp(ui, server)
```

**Comment by jcheng5** [comment]
Never mind, I got it to repro after I also changed my system time zone to Melbourne.

**Comment by jcheng5** [comment]
This jsfiddle is a minimal repro of the problem (you must set your system timezone to Melbourne):
http://jsfiddle.net/5tuneg7s/1/

Changing `setUTCDate` to `setDate` fixes it, but I'm worried about what other cases will break. Here's the commit where we moved to UTC (@wch).
https://github.com/rstudio/shiny/commit/37b6a668abe28c0305c0268a9327e949d246e20d
Here's the full PR.
https://github.com/rstudio/shiny/pull/1374

**Comment by jcheng5** [comment]
bootstrap-datepicker docs: https://bootstrap-datepicker.readthedocs.io/en/stable/index.html

**Comment by jcheng5** [comment]
This might be an old bug in bootstrap-datepicker. https://github.com/uxsolutions/bootstrap-datepicker/commit/13885397deb748bfc02efe9752f16d06b682ffc7#diff-dd513a8bab7ad1033c8784c4a1b9ce15

The jsfiddle was a red herring; I used `/` as separators instead of `-`, which gives different behavior. In Shiny, we're using `-`, and if you make that change the fiddle doesn't repro the problem anymore:
http://jsfiddle.net/jcheng/5tuneg7s/3/
