### ISSUE TITLE
Add queryString argument to runApp and friends

### ISSUE THREAD

**Issue by hafen** [rstudio/shiny#221]
It would be nice to be able to specify a query string directly to runApp so that apps that use the query string can be launched in different states from the console.  This argument could be simply the query string or maybe a named list from which the string is constructed.

This is a quick thing - maybe there is a reason it hasn't been done.  I'd do a pull request but you probably would want to do it in a particular way.

**Comment by jcheng5** [comment]
Sorry. It's possible to do this manually by providing a function as the launch.browser argument; you can modify the URL value then call browseURL.
