### ISSUE TITLE
rcbc package

### ISSUE THREAD

**Issue by cmber** [rstudio/shiny#2213]
I've been working with rcbc in RStudio/Windows 10 for some time now and it works perfectly (devtools::install_github("dirkschumacher/rcbc"). Now, I would like to test a shiny app I developed that makes use of rcbc. When I try to deploy the app I got the following error:

------------------------- ANTICONF ERROR ---------------------------
Configuration failed because cbc was not found. Try installing:

    deb: coinor-libcbc-dev, coinor-libclp-dev (Debian, Ubuntu, etc)
    rpm: coin-or-Cbc-devel, coin-or-Clp-devel (Fedora, CentOS, RHEL)
    brew: coin-or-tools/coinor/cbc (Mac OSX)
    If cbc is already installed, check that 'pkg-config' is in your
    PATH and PKG_CONFIG_PATH contains a cbc.pc file. If pkg-config
    is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
    R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
---------------------------------------------------------------------------
I contacted the the package maintainer/author and he suggested: "Those libraries might not be available on your shiny server. If you host it on shinyapps.io, you need to make sure shinyapps has the ubuntu dependencies listed above installed. I think you can request that in an rstudio github repository".

Any help will be appreciated.

Christian

**Comment by jcheng5** [comment]
This is the repo in question, a PR would be appreciated! https://github.com/rstudio/shinyapps-package-dependencies
