### ISSUE TITLE
Open modal on top of another modal

### ISSUE THREAD

**Issue by samssann** [rstudio/shiny#2220]
It would be a useful feature if one could open another modal on top of existing modal, without replacing it. The desired behaviour would be that after dismissing the second modal, the first would still be visible. Here is a short example demonstrating the missing feature:

```library(shiny)
shinyApp(
  basicPage(
    actionButton("showModal1","Show Modal 1")
  ),
  function(input, output, session) {
    observeEvent(input$showModal1, {
      showModal(modalDialog(basicPage(actionButton("showModal2","Show Modal 2"))))
    })
    
    observeEvent(input$showModal2, {
      showModal(modalDialog(basicPage(p("After dismissing me, this should return to the first modal"))))
    })
  }
)
```

And an example of the wished behaviour (all inputs in the modal would have to set or updated again):
```
library(shiny)
shinyApp(
  basicPage(
    actionButton("showModal1","Show Modal 1")
  ),
  function(input, output, session) {
    observeEvent(input$showModal1, {
      showModal(modalDialog(basicPage(p("this is modal 1"), actionButton("showModal2","Show Modal 2"))))
    })
    
    observeEvent(input$showModal2, {
      showModal(modalDialog(
        basicPage(p("After dismissing me, this should return to the first modal")),
        footer = actionButton("exit","Exit to back to Modal 1")
        ))
    })
    
    observeEvent(input$exit, {
      removeModal()
      showModal(modalDialog(basicPage(p("this is modal 1"), actionButton("showModal2","Show Modal 2"))))
    })
  }
)
```

`bsModal` from the package `shinyBS` can accomplish this, but I think this should be native shiny feature:

```
library(shiny)
library(shinyBS)
shinyApp(
  basicPage(
    actionButton("showModal1","Show Modal 1"),
    bsModal("modal1", "this is modal 1", "showModal1", actionButton("showModal2", "Show Modal 2")),
    bsModal("modal2", "this is modal 2", "showModal2", p("After dismissing me, this should return to the first modal"))
  ),
  function(input, output, session) {
  }
)
```

**Comment by nteetor** [comment]
Unfortunately, the Bootstrap library used to handle modals does not support multiple modals, see https://getbootstrap.com/docs/3.3/javascript/#modals. 

![image](https://user-images.githubusercontent.com/3228369/47932560-5e22a180-dea8-11e8-9bff-728083c3d7e4.png)

I am not sure how shinyBS handled multiple modals. I believe multiple modals with Bootstrap are "possible", however there are unanticipated consequences to do with scrolling or responsiveness.

**Comment by davidfgeorge** [comment]
Did anything ever happen with this? I want to do something similar - stack modals dynamically depending on runtime circumstances.

**Comment by skad00sh** [comment]
Even I want a similar thing. Could not find it anywhere.

**Comment by graemediack** [comment]
In case anyone wants a workaround, I've done this kind of thing. I like bsModal but I found it doesn't work well in all situations, like if I call my modal from a link in a sidebar or header it seems to fail (maybe I'm not using it right!)

        library(shiny)

        ui <- basicPage(
            actionButton("showModal1","Show Modal 1")
        )
        
        server <- function(input, output, session) {
            # pass modal 1 contents into a function for easy call back
            modal1 <- function(){
              modalDialog(title = "this is modal 1",actionButton('showModal2',"Modal 2"))
            }
            # observe button click for modal 1
            observeEvent(input$showModal1, {
              showModal(
                modal1()
              )
            })
            # observe button click for modal 2
            observeEvent(input$showModal2,{
              # tidy up modal 1
              removeModal()
              showModal(modalDialog(
                title = "this is modal 1",
                footer = tagList(
                  # user can decide to fully dismiss or return to modal 1
                  modalButton("Dismiss"),
                  actionButton('returnToModal1', "Return to Modal 1")
                )
              ))
            })
            # observe button click from modal 2
            observeEvent(input$returnToModal1, {
              # tidy up modal 2 and show modal 1
              removeModal()
              showModal(
                modal1()
              )
            })
          }
        
        shinyApp(ui, server)

**Comment by samssann** [comment]
This is a bootstrap issue https://github.com/twbs/bootstrap/issues/3233.
To get around this you can use the `shinyBS` package or a hack solution similar to this
```
library(shiny)
library(htmltools)
library(rlang)

modal_dialog_button <- function(..., button_id, modal_id, button_args = list(label = "Button"), modal_args = list()) {
  stopifnot(
    is_scalar_character(button_id),
    is_scalar_character(modal_id),
    modal_id != button_id,
    is.list(button_args),
    is.list(modal_args)
  )
  button_args$inputId <- button_id
  modal_args <- append(dots_list(...), modal_args)
  tagList(
    tagQuery(exec(actionButton, !!!button_args))$
      addAttrs(
        `data-toggle` = "modal",
        `data-target` = paste0("#", modal_id)
      )$allTags(),
    tagQuery(exec(modalDialog, !!!modal_args))$
      removeAttrs("id")$
      addAttrs(id = modal_id, `aria-hidden` = "true", style = "overflow-x: visible; overflow-y: visible;")$
      children("div")$
      children("div")$
      children("div")$
      sibling(".modal-footer")$
      find("button")$
      removeAttrs(c("data-dismiss", "data-bs-dismiss"))$
      addAttrs(onclick = glue("$('#{modal_id}').modal('hide');"))$
      allTags()
  )
}

shinyApp(
  ui = fluidPage(
    br(),
    modal_dialog_button(
      p("test"),
      br(),
      modal_dialog_button(
        p("test2"),
        br(),
        modal_dialog_button(
          p("test3"), 
          button_id = "button3", 
          modal_id = "modal3",
          modal_args = list(size = "m", title = "modal 3")
        ), 
        button_id = "button2", 
        modal_id = "modal2",
        modal_args = list(size = "l", title = "modal 2")
      ), 
      button_id = "button1", 
      modal_id = "modal1",
      modal_args = list(size = "xl", title = "modal 1")
    )
  ), 
  server = function(input, output, session) {}
)
```
![image](https://user-images.githubusercontent.com/19807339/137489989-f772e5f0-8f78-40e0-8b0d-b716d43f189c.png)
