### ISSUE TITLE
Segmentation fault when using mailR package on shiny app

### ISSUE THREAD

**Issue by dsaada** [rstudio/shiny#2231]
Hi all,

when i use my app with the package `mailR` I get segmentation fault. I use lot of package:

```
library(ggplot2)
library(dplyr)
library(lubridate)
library(xts)
library(stringr)
library(data.table)
library(xgboost)

library(dummies)
library(DT)
library(dygraphs)

library(shinyWidgets)
library(shiny)
library(shinydashboard)
```

i saw on other post it's a conflict between rjava and other package.
Any one can help me please?
thx
David

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
