### ISSUE TITLE
Can't install httpuv

### ISSUE THREAD

**Issue by cstangor** [rstudio/shiny#2232]
I've downloaded the tar.gz but can't read it properly

install.packages("c:/.../httpuv_1.4.5.tar.gz", repos = NULL)

produces

Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="httpuv.dll" OBJECTS="RcppExports-legacy.o RcppExports.o callback.o callbackqueue.o filedatasource-unix.o filedatasource-win.o http.o httprequest.o httpresponse.o httpuv.o md5.o set_invalid_parameter.o socket.o thread.o utils.o uvutil.o webapplication.o websockets-base.o websockets-hixie76.o websockets-hybi03.o websockets-ietf.o websockets.o"' had status 127

**Comment by wch** [comment]
Do you have Rtools installed?

If you do and it's still not working, please provide more information -- more of the output, and more information about your system.

**Comment by wch** [comment]
Oh, also, please file this in the httpuv repo: https://github.com/rstudio/httpuv/issues
