### ISSUE TITLE
Different text wrapping behavior for code (pre) output in Safari

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/shiny#2233]
The text wrapping behavior for code output is different in Safari compared to Firefox and Chrome (all tested with latest releases). A horizontal scrollbar won't appear in Safari, instead the lines of text are wrapped.

<img width="1654" alt="text_wrapping_browser_comparison" src="https://user-images.githubusercontent.com/5612024/47678321-b98a2200-db7e-11e8-81d2-7068819d1eb5.png">
 
In the above screenshot (from the `shiny-examples` app: `017-select-vs-selectize`), Firefox is **LEFT**, Safari is **CENTER**, and Chrome is **RIGHT**).

From a little investigation between me and @wch yielded some findings (from Trello card notes):

> It turns out that Safari displays text with the CSS properties white-space: pre; overflow-wrap: break-word differently from other browsers. ...  JSFiddle: https://jsfiddle.net/fba61pct/2/
> 
> With those CSS properties, Safari wraps text but the other browsers do not.
> 
> It seems that setting overflow-wrap: normal fixes it in Safari. However, Bootstrap specifically sets overflow-wrap: break-word for pre tags, and we would be overriding it. I'm not sure why they made that choice -- it seems to have no effect in other browsers.

**Comment by wch** [comment]
IE11 and Edge also wrap the text, like Safari.

**Comment by wch** [comment]
Update:

Bootstrap has `word-wrap: break-word` for `pre` tags. It turns out that setting it to `word-wrap: normal` fixes the issue in Safari.

(The previous comment, which said that `overflow-wrap: normal` fixes it, works for the jsfiddle, but doesn't work when Bootstrap is involve, because Bootstrap also sets `word-wrap: break-word`.)
