### ISSUE TITLE
Is it possible to **Repeat all item labels** in RpivotTable output?

### ISSUE THREAD

**Issue by Saad55555** [rstudio/shiny#2242]
Hi guys, I'm getting pivot table output without repetition of column and rows labels using *RpivotTable* package in R (kindly run the codes to see the result). I need the output layout in *Tablular form* with **repetition of labels** . I have tried a lot but couldn't get the desired results. Can someone please help me out?
Regards

`
    library(rpivotTable) 
    
    library(dplyr)
    
    library(readr)
    
    library(shiny)
    
    library(openxlsx)

#ui

    ui = fluidPage(
      
      
      fluidRow( rpivotTableOutput("pivot")))

#server

    server = function(input, output) { 
      
      output$pivot <- renderRpivotTable(rpivotTable::rpivotTable(mtcars, rows = c( 
        "vs","gear" ),cols=c("am","cyl"),vals =  "mpg", aggregatorName = "Sum",rendererName =  
          "Table",width="50%", height="550px"))}
    
    shinyApp(ui = ui, server = server)

`

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests for Shiny itself. I suggest asking at one of the following:

* https://github.com/smartinsightsfromdata/rpivotTable
* https://community.rstudio.com/
* https://stackoverflow.com/

**Comment by wch** [comment]
As stated earlier, this issue tracker is meant for bug reports and feature requests for Shiny. It is not for general help questions like yours. I suggest asking in one the places that I linked to.
