### ISSUE TITLE
class = "fa fa-download" doesn't added download icon in 1.2

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#2244]
In 1.1:

![image](https://user-images.githubusercontent.com/2998956/47947394-ede04400-ded8-11e8-97ec-cfe8e41f5b60.png)

In 1.2:

![image](https://user-images.githubusercontent.com/2998956/47947400-ffc1e700-ded8-11e8-9643-d49d8b2b81e0.png)

Reproducible example that works in 1.1 but not in 1.2
```
 library(shiny)

# Define UI for application that draws a histogram
ui <- navbarPage("App Title",
  navbarMenu("",
    icon = icon("save"),
    "Server",
    tabPanel(actionLink("state_save_link", "Save radiant state file", icon = icon("download"))),
    tabPanel(downloadLink("state_download", "    Download radiant state file", class = "fa fa-download"))
  )
)

server <- function(input, output) { 
}

shinyApp(ui = ui, server = server)
```

BTW It would be great to have an `icon` argument for `downloadLink` :)

**Comment by jcheng5** [comment]
Does this work?

```r
downloadLink("state_download", tagList(icon("download"), "Download radiant state file"))
```

**Comment by vnijs** [comment]
Yes! Thanks Joe. Would be great to have an icon argument for `downloadLink` at some point :)

![image](https://user-images.githubusercontent.com/2998956/48283200-aa259700-e410-11e8-838c-3bfdae67e08f.png)

**Comment by alandipert** [comment]
@vnijs It looks like Joe's suggestion worked for you. If you also feel like this issue was resolved, please feel free to close it. Thanks!
