### ISSUE TITLE
Error in passing NULL via updateSliderInput

### ISSUE THREAD

**Issue by jon11w** [rstudio/shiny#2250]
The following in the documentation for updateSliderInput seems to no longer be true in the current version of Shiny:

> Any arguments with NULL values will be ignored; they will not result in any changes to the input object on the client.

For instance trying to update only the label of a slider previously worked with the following example, and should work according to the documentation:

```
## Only run this example in interactive R sessions
if (interactive()) {
  shinyApp(
    ui = fluidPage(
      sidebarLayout(
        sidebarPanel(
          p("The first slider controls the second"),
          sliderInput("control", "Controller:", min=0, max=20, value=10,
                      step=1),
          sliderInput("receive", "Receiver:", min=0, max=20, value=10,
                      step=1)
        ),
        mainPanel()
      )
    ),
    server = function(input, output, session) {
      observe({
        val <- input$control
        # Update label
        updateSliderInput(session, "receive", label = "Updated")
      })
    }
  )
}
```

But now requires the following code, even though min and max default to NULL:

```
## Only run this example in interactive R sessions
if (interactive()) {
  shinyApp(
    ui = fluidPage(
      sidebarLayout(
        sidebarPanel(
          p("The first slider controls the second"),
          sliderInput("control", "Controller:", min=0, max=20, value=10,
                      step=1),
          sliderInput("receive", "Receiver:", min=0, max=20, value=10,
                      step=1)
        ),
        mainPanel()
      )
    ),
    server = function(input, output, session) {
      observe({
        val <- input$control
        # Update label
        updateSliderInput(session, "receive", label = "Updated", min=0, max=20)
      })
    }
  )
}
```

The old version is preferable, and logical in my opinion, but if this is no longer possible an update to the documentation would be useful.

Cheers, Jon

**Comment by pfgherardini** [comment]
+1 I encountered the same problem

**Comment by JulianBo** [comment]
+1 

The changes introduced with the latest version of shiny also do break my code. 
I think the following should work, as it used to do: 
`updateSliderInput(session,"id",value=NULL)`

It now throws an error "Error in [[: subscript out of bounds"

**Comment by cpsievert** [comment]
This issue was introduced by https://github.com/rstudio/shiny/commit/639b520d397d0695d767e12bcc0934f01e7a771c
