### ISSUE TITLE
selectInput - inputId issue

### ISSUE THREAD

**Issue by eniso-partners** [rstudio/shiny#2251]
When using selectInput with default selectize=TRUE, when selectInput value is empty a "-selectized" character is amended to the user's defined inputId. Is this change in the new version of shiny on purpose ?
This cause troubles when one tries to use generic functions to deal with the defined inputIds

**Comment by wch** [comment]
We updated the version of Selectize.js that came with Shiny, and there was a change in the behavior of Selectize. It adds a second input with the id "xxx-selectized". For reference, here are some screenshots of a test application with Shiny 1.1.0 and 1.20.


```R
shinyApp(
  ui = fluidPage(
    selectizeInput("s", "Label", choices=c("A", "B", "C"), multiple=TRUE)
  ), 
  server = function(input, output,session) {}
)
```

Shiny 1.1.0:

![image](https://user-images.githubusercontent.com/86978/48147340-b24ccd80-e27c-11e8-89f6-a8c1ead4717e.png)

Shiny 1.2.0:

![image](https://user-images.githubusercontent.com/86978/48147347-b7118180-e27c-11e8-8a67-0439ca330f3a.png)


The user-defined input ID is still there. In the screenshots, it's the `<select id="s" ...>`. There's also another input which, in 1.1.0, does not have an ID; in 1.2.0, it has the id `s-selectized`.

I don't think this new ID should cause any problems with typical usage. What are you doing that it causes problems?

**Comment by eniso-partners** [comment]
I used some inputs within a plot function as arguments and retrieve the inputs by the name. Some selectInput do have the extension -selectized and some not, which cause an issue in my plot function. But I now understand the reason, thank you for the explanation and the screenshots

**Comment by adambondarzewski** [comment]
shiny::selectizeInput does not wrap whole html (in particular crucial part selectize-control) in div with shiny id (which becomes html id) can indeed cause some problems while doing frontend/E2E testing.

For example:

```
<div>
    <select id="facile_filter-url_filter_1-Value_Filter_1"
        class="form-control shiny-bound-input shinyjs-resettable selectized" multiple="multiple"
        ...
        ></select>
    <div class="selectize-control form-control shiny-bound-input shinyjs-resettable multi">
        <div class="selectize-input items not-full has-options"><input type="text" autocomplete="off" tabindex=""
                id="facile_filter-url_filter_1-Value_Filter_1-selectized"></div>
        <div class="selectize-dropdown multi form-control shiny-bound-input shinyjs-resettable"></div>
            <div class="selectize-dropdown-content">
                <div class="option" data-selectable="" data-value="IC0">IC0</div>
            </div>
        </div>
    </div>
    <script type="application/json" data-for="facile_filter-url_filter_1-Value_Filter_1">{}</script>
</div>
```

Here I need sibling of element with id facile_filter-url_filter_1-Value_Filter_1. That causes some issues while testing frontend (e.g. there are some issues with Cypress validation, details :https://docs.cypress.io/guides/core-concepts/retry-ability.html#Commands-vs-assertions)
