### ISSUE TITLE
Selection between master and children lost (non reproducible error, datas are from database)

### ISSUE THREAD

**Issue by philibe** [rstudio/shiny#2262]
I've created DT tables with links between master table, and child tables, which has child table etc...

I click on table master and I go from table to tables. And sometimes the initial selection is lost.

The initial goal was to have 2 database, archive and present time. I have a radio button to switch between the 2 database. So I have to put in all reactive function a function to reconnect or not to the correct chosen database.

__It seems to that it's a bug, but it's could be an error in my code__

This is for a big application.

But I have the same issue for a simple (old) application without DT and without reconnection between database.

The simple and the big Shiny applications are multi-user and each user could use multi-tab on their browser.

Thanks in advance :)

__My structure of the big application:__

__server.R__

    database_name_decale<-"blabla_decale"
    database_name_archive<-"blabla_archive"

    connexion_bdd_odbc_decale_txt <- paste0('driver={ODBC Driver 17 for SQL Server};server=blabla;database=',database_name_decale,';uid=xxx;pwd=xxx;')
    connexion_bdd_odbc_archive_txt <- paste0('driver={ODBC Driver 17 for SQL Server};server=blabla;database=',database_name_archive,';uid=xx;pwd=xx;')
    ...
    shinyServer(function(input, output, session) {
      react <- reactiveValues( connexion_bdd = 0) 
      observeEvent(
      c(
        input$radiob.ChoixBase
      ),
      {
       Init_cnx_bdd.fct_react (input,output,session, change_base= TRUE)

     })
    ...
      observeEvent(input$NavTabPanels, {
        Init_cnx_bdd.fct_react (input,output,session, change_base= FALSE)
        if (input$NavTabPanels=="My_Menu") {
    ...
          My_Menu_maitre.tab.fct_react (input,output,session)  
        }
      })  
    ...
      My_Menu_maitre.tab.fct_react <- function (input,output,session) {
    ...
        detail.table <-  reactive({
          Init_cnx_bdd.fct_react (input,output,session, change_base = FALSE)
          input_appelant=  input$My_Menu_maitre_rows_selected
          validate(
            need(!is.null(input_appelant) , "Select a line from master")
          )                 
          res<-  data.frame() 
          table_details <-subset( My_Menu_maitre.table()[as.integer(input_appelant), ],
                                  select=c("id_num"))
          res<- detail.reqSQL.fct (react$connexion_bdd,as.data.frame(table_details))            
          return(res)
        })  
    ...
        sub_detail.table <-  reactive({...})
    ...
        sub_sub_detail.table <-  reactive({...})
    ...
        sub_sub_sub_detail.table <-  reactive({...})

With this function

    Init_cnx_bdd.fct_react <- function (input,output,session,   change_base) {
        req(react$connexion_bdd)
        if(input$radiob.ChoixBase == "BaseActuelle")   {
          output$BaseCouranteTxt <-renderText({"Actuelle"})
          if (change_base==TRUE) {
              tryCatch(
                {
                  odbcClose(react$connexion_bdd)
                },
                error=function(e) { # print("e")
                  },
                warning=function(w) { # print("w")  
                  }
              )
              react$connexion_bdd<-odbcDriverConnect(connexion_bdd_odbc_decale_txt)
          } else {
              tryCatch(
                {
                  odbcGetInfo(react$connexion_bdd)
                },
                error=function(e) {   print("e")
                  react$connexion_bdd<-odbcDriverConnect(connexion_bdd_odbc_decale_txt)
                },
                warning=function(w) {  print("w")
                }
              )
          }

    }
    
        if(input$Technique.Connexions.radiob.ChoixBase == "BaseArchive")   {
          output$Home.Technique.BaseCouranteTxt <-renderText({"Archive"})
          if (change_base==TRUE) {
              tryCatch(
                {
                  odbcClose(react$connexion_bdd)
                },
                error=function(e) {  #print("e")
                },
                warning=function(w) { # print("w")   
                }
              )
              react$connexion_bdd<-odbcDriverConnect(connexion_bdd_odbc_archive_txt)
          } else {
            tryCatch(
              {
                odbcGetInfo(react$connexion_bdd)
              },
              error=function(e) { #  print("e")
                react$connexion_bdd<-odbcDriverConnect(connexion_bdd_odbc_archive_txt)
              },
              warning=function(w) { # print("w")
              }
            )
          }
          
        }
    }

__My structure of the little application__:

__server.R__

    connexion_bdd_odbc_txt='driver={ODBC Driver 11 for SQL Server};server=xxx;database=blabla_decale;uid=xx;pwd=xxx;'
    ...
    shinyServer(function(input, output,session) {
    ...
    table.brut<-reactive({
      connexion_bdd <- odbcDriverConnect(connexion_bdd_odbc_txt, readOnly = TRUE)  
      table<-sqlQuery(connexion_bdd, "SELECT * FROM blabla")
      odbcClose(connexion_bdd)
      table<-as.data.frame(table)
    
      return(table)
    })
    ...
    and other tables and reactive function, not of the DT package, and a few linked between them.

**Comment by jcheng5** [comment]
This is definitely not right. Outputs and reactives don't work the way you think they do; you shouldn't be creating the reactives and defining the outputs from inside calls to `observeEvent` or `observe` (whether wrapped in a function like `Init_cnx_bdd.fct_react` or not).

I highly recommend you watch this entire tutorial, although it is a couple of hours long. But the part where I talk about this class of error is at about the 16:00 mark of the first video. https://www.rstudio.com/resources/videos/effective-reactive-programming/

**Comment by jcheng5** [comment]
Also, if you get past that part and still have questions, please ask at https://community.rstudio.com/c/shiny instead, unless you have a specific Shiny issue to report.

**Comment by philibe** [comment]
For information: the cause of lost selections was not only the use of "anti-solution". After the correction the issue was going on again a little.

I have replaced RODBC by DBI and RStudio/odbc, and the  issue doesn't occur anymore.
