### ISSUE TITLE
Radio buttons does not set answer to `NULL` if selected is `FALSE`

### ISSUE THREAD

**Issue by schloerke** [rstudio/shiny#2266]
When a radio button is initialized, the radio button input value is not reset on display.  This should be set to `NULL` if selected is FALSE.

Steps to reproduce:
1. select a button and checkbox
2. click reset button
3. observe checkbox reset the value and the radiobutton value is not reset

Reprex:

```r
library(shiny)

shiny::shinyApp(
  fluidPage(
    actionButton("reset", "Reset Input"),
    uiOutput("radio_buttons"),
    verbatimTextOutput("radio_txt"),
    uiOutput("checkbox"),
    verbatimTextOutput("check_txt")
  ),
  function(input, output) {
    output$radio_txt <- renderPrint(input$radio_buttons)
    output$radio_buttons <- renderUI({
      input$reset
      radioButtons(
        "radio_buttons",
        "Input:",
        choices = c("Choice A", "Choice B"),
        selected = FALSE
      )
    })
    output$check_txt <- renderPrint(input$checkbox)
    output$checkbox <- renderUI({
      input$reset
      checkboxGroupInput(
        "checkbox",
        "Input:",
        choices = c("Choice C", "Choice D"),
        selected = FALSE
      )
    })
  }
)
```

**Comment by jcheng5** [comment]
Hmmm, good one.

**Comment by wch** [comment]
FWIW, I think the way to go is to use `character(0)` to select none. That's how it works for the update functions `updateCheckboxInput` and `updateSelectInput` (and the docs say that's how it works for `updateRadioButtons`, although #2688 says that's currently not true).
