### ISSUE TITLE
Is there a way to update a graph without recreating it.

### ISSUE THREAD

**Issue by vikram-rawat** [rstudio/shiny#2269]
What I actually mean is that if I want to append some constant data in a plot like some time series. It should not update and recreate the entire plot from scratch. I should be just able to append new data into it.

Or in value box. It should not create it self afresh butt just change the value.

I thought this is something I could already do. So I opened an issue on Rstudio.

https://community.rstudio.com/t/is-there-any-equivalent-of-web-sockets-in-shiny-world/17908/12

But seems like there is no direct alternative of doing so.

Could you please help me out. Kindly tell me how should I achieve this desired result.

If it's confusing please go through the community link you might understand the issue Better.

**Comment by alandipert** [comment]
@vikram-rawat I'm closing this because it looks like your questions were answered on Community.
