### ISSUE TITLE
2d slider/xy controller UI input

### ISSUE THREAD

**Issue by ericricky** [rstudio/shiny#2270]
I'd like a UI input that allows the user to drag a point within a 2d box where each dimension represents a numeric input. These are common in audio processing, eg FL studio calls them [XY controllers](http://www.image-line.com/support/flstudio_online_manual/html/plugins/Fruity%20X-Y%20Controller.htm). Does anyone know of any implementation of this? If not, would maintainers entertain a pull request?

**Comment by stla** [comment]
There is jQuery Kontrol: http://anthonyterrien.com/demo/kontrol/

**Comment by ericricky** [comment]
@stla Thanks that's good enough

**Comment by stla** [comment]
@ericricky I have done a Shiny implementation; if you're interested: https://gist.github.com/stla/89d65f0d293212f70a246231619ccb03
I will do a package soon.

**Comment by stla** [comment]
@ericricky I've done the package: https://github.com/stla/shinyXYpad
Your feedback is welcome. Do you have a use case ?

**Comment by ericricky** [comment]
@stla I'm actually don't need it for any project currently, but if I do in the future I will definitely get back to you.

**Comment by ejharrit** [comment]
Hello, I could use this for a current project and I'm trying to install shinyXYpad, but I seem to be having some issues, it looks like it needs and earlier version of rlang?  Any help in getting this package installed would be greatly appreciated, or alternatives.  Thanks!

**Comment by stla** [comment]
@ejharrit Hello. I don't see what you mean. Is there a problem with the installation or with the usage?

**Comment by stla** [comment]
FYI, **shinyXYpad** will soon be on CRAN.

**Comment by stla** [comment]
And I'm still looking for a use case :-)
