### ISSUE TITLE
Error in match.arg(kernel) : 'arg' must be of length 1 while implementing density function

### ISSUE THREAD

**Issue by ShuaibAslam** [rstudio/shiny#2274]
![image](https://user-images.githubusercontent.com/12622827/49116656-99916f80-f29e-11e8-91be-8d853dea78c1.png)

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests for Shiny. Your question appears to be a help question about R in general. For questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
