### ISSUE TITLE
renderTable `align` parameter check fails although input is valid

### ISSUE THREAD

**Issue by dirkschumacher** [rstudio/shiny#2276]
It seems the length check of the `align` parameter in `renderTable` always if `length(align) > 1`, although the input is valid. 

The docs say:

> A string that specifies the column alignment. If equal to 'l', 'c' or 'r', then all columns will be, respectively, left-, center- or right-aligned. Otherwise, align must have the same number of characters as the resulting table (if rownames = TRUE, this will be equal to ncol()+1),

Some failing examples:
``` r
shiny::renderTable(mtcars[, 1:2], align = c("l", "l"), rownames = FALSE)()
#> Error in `align<-.xtable`(`*tmp*`, value = switch(1 + is.null(align), : "align" must have length equal to 3 ( ncol(x) + 1 )
shiny::renderTable(mtcars[, 1:2], align = c("l", "l", "l"), rownames = TRUE)()
#> Error in `align<-.xtable`(`*tmp*`, value = switch(1 + is.null(align), : "align" must have length equal to 3 ( ncol(x) + 1 )
```

<sup>Created on 2018-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by alandipert** [comment]
@dirkschumacher Thank you for the report, however I think that `align` is intended to be a single-element character vector and used like this:

```R
shiny::renderTable(mtcars[, 1:2], align = c("lll"), rownames = TRUE)()
```
I'm closing because I don't think this is a bug, but if you have a suggestion for how to improve the docs feel free to re-open or to send a PR.
