### ISSUE TITLE
selectInput with choices as a dictionary

### ISSUE THREAD

**Issue by lmeninato** [rstudio/shiny#2278]
Just an idea that would be useful to me (and hopefully others as well). Would it be possible to have a version of selectInput where you can set the parameter choices equal to a named vector. So for instance, if I have the vector:

```r
time_series_ids <- c(1,2,3,4,5)
names(time_series_ids) <- c('a','b','c','d','e')
```
It would be great if the user could search either the numeric id of the time_series_ids vector _or_ their associated names. Any thoughts?

**Comment by nteetor** [comment]
As luck would have it, selectize.js supports this out of the box. In this case you need to use the `selectizeInput()` `options` argument (see also the [complete list of options](https://github.com/selectize/selectize.js/blob/master/docs/usage.md#data_searching)).

```R
shinyApp(
  ui = fluidPage(
    selectizeInput(
      inputId = "test1",
      label = NULL,
      choices = c(
        A = 1,
        B = 2,
        C = 3
      ),
      multiple = TRUE,
      options = list(                      # <-
        searchField = c("label", "value")  # <- 
      )
    )
  ),
  server = function(input, output) {

  }
)
```

Here is what I saw when I interacted with the selectize input,

![image](https://user-images.githubusercontent.com/3228369/49314995-2c5a2600-f4ba-11e8-98c3-9e20fa8ad4d4.png)

![image](https://user-images.githubusercontent.com/3228369/49315463-c5d60780-f4bb-11e8-9f2c-417ce99e8ff3.png)

I hope this helps.

**Comment by lmeninato** [comment]
Wow that is awesome! What a great feature.
