### ISSUE TITLE
remove zip uploaded files from shiny

### ISSUE THREAD

**Issue by LuisCanoA** [rstudio/shiny#2290]
Hi 

I'am working with Shiny in Rstudio, i created an app for input data in .zip format.
But my problem start when i try to upload a new zip file, because shiny don't delete previous files 
i would like to know how i can delete all those files with code or maybe with action button. someone knows how i can do automatically ?

**Comment by alandipert** [comment]
@LuisCanoA I'm closing this because the question appears to have been answered on Community. Feel free to re-open if you have additional questions.
