### ISSUE TITLE
hover with multi-panel plots

### ISSUE THREAD

**Issue by stranda** [rstudio/shiny#2299]
I have a shiny app that helps a user visualize electropherograms (essentially spectra) that come from automated DNA sequencers. I would like the user to be able to hover over a peak and find out the time the peak came off the instrument. I also would like to be able to compare multiple electropherograms by plotting the spectra one above the other.

If I plot a single spectrum, I can recover the mouse x-position with the 'hover' option provided to plotOutput() in the ui. If I stack plots using base graphics and the par(mfrow=c(n,1)) where n is the number of spectra, the results are unpredictable. Basically the x-position is recoverable in part of the plot region but not throughout.

As a final piece of information, I wrote this app several years ago and it's been working as expected until I updated R and the shiny package to fairly recent versions: (R 3.4.4; shiny 1.2.0).

I've included an app.R file that reproduces this issue on a simple case using histograms and the old-faithful data and shows the approach I have been taking. I get the same behavior whether I set 'clip' in hoverOpts to TRUE or FALSE.

I asked about this on stackoverflow as well [https://stackoverflow.com/questions/54099480/r-shiny-hover-with-multi-panel-plots](url), and have not received any feedback as of yet. 

Thanks for any insight in advance here.

Here is a self-contained example, though it uses histograms rather than spectra plotted with plot()

```
library(shiny)

ui = fluidPage(

titlePanel("Mulitpanel hover: Old Faithful Geyser Data"),

sidebarLayout(
  sidebarPanel(
     sliderInput("bins","Number of bins:",min = 1,max = 50,value = 30)
  ),

  mainPanel(
     textOutput("xpos"),
     plotOutput("distPlot",hover=hoverOpts(id="plot_hover",clip=TRUE))
      )
   )
 )

 server = function(input, output) {
   output$xpos = renderText({paste("x coord:",input$plot_hover$x)})
   output$distPlot = renderPlot({
   x    = faithful[, 2] 
   bins = seq(min(x), max(x), length.out = input$bins + 1)

   par(mfrow=c(2,1))
   hist(x, breaks = bins, col = 'darkgray', border = 'white')
   hist(x, breaks = bins, col = 'orange', border = 'white')
  })
 }
 shinyApp(ui = ui, server = server)
```

**Comment by wch** [comment]
For base graphics, the plot interaction stuff in Shiny was never designed to work with multiple plots using `par(mfrow = ....)`.

There is a bug where `clip=FALSE` doesn't work: #1982, and it may have been introduced after you wrote your existing code. In that, were you using `clip=FALSE`?

**Comment by wch** [comment]
It should just work with facets in ggplot2, but it won't work for lattice.

**Comment by stranda** [comment]
Sounds good to me.  Thanks for the time
