### ISSUE TITLE
[Feature request] bookmarking and automatic URL update

### ISSUE THREAD

**Issue by pachamaltese** [rstudio/shiny#2302]
Hi

Would it be possible to implement this
https://stackoverflow.com/a/25385474/3720258
as default in Shiny?

The idea is simple:
1. Take user input from dropdowns and sliders
2. Put that input in the URL
3. Move the dropdowns and sliders if the user edits the URL

**Comment by jcheng5** [comment]
It's already supported, please see this article including the last section on automatic URL updating. If this isn't working for you, please include a code sample that demonstrates the issue. Thanks. http://shiny.rstudio.com/articles/bookmarking-state.html

**Comment by pachamaltese** [comment]
Hi @jcheng5.
I was trying to propose something much simpler. As an example, if I have three dropdowns (let's say year1, year2 and year3) I was trying to generate the URL with just year1 and year2 like `myapp.com/?y1=2000&y2=2001`.
Any chance to use what you suggest with something like ` session$doBookmark(year1, year2)` in a future version?
