### ISSUE TITLE
Nested conditional panels with reactive values do not work properly

### ISSUE THREAD

**Issue by strboul** [rstudio/shiny#2304]
I have created a nested conditional panel structure to display a "loading text" appearing while some actual stuff is being calculated. I have a problem with the behavior of this text. Here is the example code:

```
library(shiny)

ui <- fluidPage(
  actionButton("btn", "Click"),
  conditionalPanel(condition = "output.btnClicked", {
    tagList(
      conditionalPanel(condition = "!output.loadingCompleted", {
        p("Loading...")
      }),
      conditionalPanel(condition = "output.loadingCompleted", {
        tableOutput("table")
      })
    )
  })
)

server <- function(input, output, session) {

  loading <- reactiveValues(data = NULL, completed = FALSE)

  btn.value <- eventReactive(input$btn,{
    if (input$btn == 0) {
      FALSE
    } else {
      TRUE
    }
  }, ignoreNULL = FALSE)

  observe({
    req(btn.value())
    Sys.sleep(2)
    loading$data <- head(mtcars)
    loading$completed <- TRUE
  })

  output$table <- renderTable({
    loading$data
  })

  output$btnClicked <- reactive({
    btn.value()
  })
  outputOptions(output, "btnClicked", suspendWhenHidden = FALSE)

  output$loadingCompleted <- reactive({
    loading$completed
  })
  outputOptions(output, "loadingCompleted", suspendWhenHidden = FALSE)

}

shinyApp(ui, server)
```

Speaking of the example above, if the first condition is replaced with `input.btn`, the loading text is mannerly displayed before the table. On the other hand, the loading text is not shown at all if a reactive value is passed to the first condition, e.g. `output.btnClicked` in this example. 

This is the simplified version of my problem. I often work with reactive values so replacing panel conditions with input values aren't my (desired) option, but looking forward to hearing your thoughts.

**Comment by cpsievert** [comment]
I'm not sure I fully understand, but I think a dynamic UI (i.e., `uiOutput()`+`renderUI()`) pattern (instead of `conditionalPanel()` pattern) works better here. Also note that there are packages like shinycssloaders that give a fancier loading animation:

```r
library(shiny)

ui <- fluidPage(
  actionButton("btn", "Click"),
  uiOutput("ui")
)

server <- function(input, output, session) {
  
  output$ui <- renderUI({
    if (input$btn == 0) return(div())
    shinycssloaders::withSpinner(tableOutput("table"))
  })
  
  output$table <- renderTable({
    req(input$btn)
    Sys.sleep(2)
    head(mtcars)
  })
}

shinyApp(ui, server)
```

For future reference, questions like this would be a better fit for https://community.rstudio.com/
