### ISSUE TITLE
observe updateSelectInput selected not working in for loop

### ISSUE THREAD

**Issue by rvernica** [rstudio/shiny#2312]
I have an app with two tabs (`A` and `B`). When I change the selected value of a `selectInput` in tab `A`, I want the value of a `selectInput` in tab `B` to update as well. I use something like this:
```R
function(input, output, session) {
  observe({updateSelectInput(session, "B1", selected = input$A1)})
  ...
```
This works fine, but I have ~10 such cases, so I made a `for` loop like so:
```R
function(input, output, session) {
  for (i in 1:10)
    observe({updateSelectInput(session, paste0("B", i), selected = input[[paste0("A", i)]])})
  ...
```
For some dubious reason the `for` loop implementation does not work.

A possibly interesting observation is that this `selectInput` objects are not static and not in `ui.R`, but are created dynamically by a function in `server.R`.

* R version `3.5.1` (2018-07-02)
* Platform: `x86_64-redhat-linux-gnu` (64-bit)
* Running under: Fedora `28` (Workstation Edition)
* `shiny_1.2.0`

**Comment by stla** [comment]
Have you tried to use a `lapply` instead of a for loop ?

**Comment by nteetor** [comment]
@rvernica, if you are dealing with a smallish, static number of inputs I would highly encourage you to simplify your application's server logic by avoiding dynamically generating observers. 

If you cannot and need the approach you describe above below is a small working example. 

```R
library(shiny)

ui <- fluidPage(
  fluidRow(
    column(
      width = 6,
      lapply(1:5, function(i) {
        selectInput(
          inputId = paste0("a_", i),
          label = paste0("Select A", i),
          choices = paste("Choice", 1:3)
        )
      })
    ),
    column(
      width = 6,
      lapply(1:5, function(i) {
        selectInput(
          inputId = paste0("b_", i),
          label = paste0("Select B", i),
          choices = paste("Choice", 1:3)
        )
      })
    )
  )
)

server <- function(input, output, session) {
  lapply(1:5, function(i) {
    observe({
      updateSelectInput(
        session, 
        inputId = paste0("b_", i), 
        selected = input[[paste0("a_", i)]]
      )
    }) 
  })
}

shinyApp(ui, server)
```

I hope this helps.

**Comment by rvernica** [comment]
Thanks! I'll probably get rid of these observers.

Still, is the execution different if I use `lapply` vs. `for` loop?

**Comment by stla** [comment]
> Still, is the execution different if I use lapply vs. for loop?

Not sure for observers, but I know some things work with `lapply` and not with `for` (such as `insertUI`).

**Comment by alandipert** [comment]
@rvernica I'm going to close this because your question appears to have been resolved, but if that's incorrect, please don't hesitate to re-open it or ask on [Community](http://community.rstudio.com).
