### ISSUE TITLE
Please upgrade the 'shiny' package to (at least) version 1.1

### ISSUE THREAD

**Issue by hafizan** [rstudio/shiny#2313]
Im not sure what the problem is since when i deploy my app on RStudio it working fine but when i deploy on shiny server, the problem below would occurs.

`Warning: Error in checkShinyVersion: Please upgrade the 'shiny' package to (at least) version 1.1
Stack trace (innermost first):
    77: f
    76: checkShinyVersion
    75: htmlwidgets::shinyWidgetOutput
    74: leafletOutput
    73: tag
    72: tags$div
    71: div
    70: tag
    69: tags$div
    68: div
    67: tag
    66: tags$div
    65: div
    64: box
    63: tag
    62: tags$div
    61: div
    60: fluidRow
    59: tag
    58: tags$div
    57: div
    56: tabItem
    55: eval
    54: eval
    53: withVisible
    52: source
    51: lapply
    50: tabItems
    49: tag
    48: tags$section
    47: tag
    46: tags$div
    45: div
    44: dashboardBody
    43: inherits
    42: tagAssert
    41: dashboardPage
     1: runApp
Error : Please upgrade the 'shiny' package to (at least) version 1.1

`

below are my sessionInfo()

![1](https://user-images.githubusercontent.com/8509184/51896950-860e9c00-23e8-11e9-9764-c4aee76652a1.png)

**Comment by shrektan** [comment]
> but when i deploy on shiny server

Your shiny server may use a different shiny version from your local computer.

**Comment by alandipert** [comment]
@hafizan did you install `shiny` as root?

If you only installed shiny as whatever user you logged in as, then the `shiny` user that Shiny Server uses won't be able to see it.

The fix could be to run `sudo R` and then `install.packages("shiny")`.

If this is helpful, feel free to close this issue.

Also, in the future, please note that [Community](http://community.rstudio.com) is a better forum for this type of question.
