### ISSUE TITLE
https://www.shinyapps.io does not work

### ISSUE THREAD

**Issue by henry090** [rstudio/shiny#2326]
Hi @jjallaire ,
cannot log in to my account on ```https://www.shinyapps.io```
Even cannot register a new account
Moreover, links of apps do not work, either

```
Login Failed
```

**Comment by mschilli87** [comment]
@henry090:
On the bottom of https://www.shinyapps.io it says

> # Community Support
> The best place to get help with shinyapps.io is the [shinyapps.io Users mailing list](https://groups.google.com/forum/#!forum/shinyapps-users). If you're having difficulties with shinyapps.io, feel free to ask questions there.

Also, the README of this repository says

> If you have general questions about using Shiny, please use the [RStudio Community website](https://community.rstudio.com/).

Probably you'll have a much better chance of getting help when trying these places.

**Comment by henry090** [comment]
It works, now
