### ISSUE TITLE
Deploying shiny app using leaflet - only working locally

### ISSUE THREAD

**Issue by jstandifer** [rstudio/shiny#2328]
Hey,

This code only works locally (first time deploying a shiny app) - any suggestions? I am trying to post to my website, but having issues. 

`#Title:2018 Midterm Election Voter Participation

library(tigris)
library(RColorBrewer)
library(leaflet)
library(leaflet.extras)
library(sp)
library(albersusa)

#Import U.S. states shapefile from the tigris package
options(tigris_use_cache = TRUE)
states <- states(cb=T)

#Import data
turnout_test<-read.csv("Turnout.csv")

#Join state shapefile and desired data
states_test <- geo_join(states, turnout_test, "NAME", "State")

#Create projection for U.S.
ee<-
  leafletCRS(
  crsClass = "L.Proj.CRS",
  code = "EPSG:2163",
  proj4def = "+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs",
  resolutions = 2^(16:7))

#Create color palette
library(RColorBrewer)
pal <- colorFactor("YlOrRd", states_test$Ballots, n=9)

#Make Shiny app

library(shiny)

ui <- fluidPage(
  leafletOutput("mymap"),
  p()
)

server <- function(input, output, session) {

  output$mymap <- renderLeaflet({
    leaflet(usa_sf, options=leafletOptions(crs=ee))%>%
      setView(-98.483330, 38.712046, zoom = 3) %>%
      setMapWidgetStyle(list(background="white"))%>%
      addResetMapButton()%>%
      addPolygons(data = states_test,stroke = TRUE,
              fillOpacity = 0.7, 
              color = 'gray',
              fillColor = ~pal(Ballots),
              weight = 0.2, 
              smoothFactor = 0.2,
              highlight = highlightOptions(
                  weight = 3,
                  color = "#666",
                  fillOpacity = 0.7,
                   bringToFront = TRUE),
              label=popup_turn,
              labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto"))
  })
}

shinyApp(ui, server)
`
``

**Comment by alandipert** [comment]
@jstandifer Hi, how are you posting to your website?

Usually problems like this are caused by missing packages on the server hosting your website. If you're using Shiny Server, the answer is likely to run `sudo R` on that server and then `install.packages` all of the packages your app uses.

**Comment by Daseandre** [comment]
A boy is sitting the mountain sight, the name "Amit written on his saffron tshirt, And next to him Hanuman ji is also sitting on sight.
