### ISSUE TITLE
Different url header's content between shiny local and server mode

### ISSUE THREAD

**Issue by tdecers** [rstudio/shiny#2333]
Hi,
A web app rerouts towards a shiny app, with a variable in the header.
I can't get header variable when the shiny app is deployed on shiny-server (Ubuntu 16.04 LTS), while I got it locally in my laptop "HTTP_myvariable" (via session$request). Is there a difference between the functionalities of shiny in server, and locally?

Moreover, I need techno clarifications about shiny opening session. When I sollicite "mydomaine.com/myapp/" I have juste "myapp/" in Network>Name browser (F12) with 200 status. But, when I sollicite "mydomaine.com/myapp", I have "myapp" (with 301 status) and "myapp/" (with 200 status).
Which intern redirection runs when shiny is excited to open a session?

Thanks for all details.

**Comment by wch** [comment]
Regarding headers: https://docs.rstudio.com/shiny-server/#proxied-headers

Shiny Server does the redirection here: https://github.com/rstudio/shiny-server/blob/0227ff5e5ce0182921446e45295873932507b36f/lib/router/directory-router.js#L88-L91

**Comment by tdecers** [comment]
Thank you so much @wch !
No possibility to imitate shiny server pro fonctionnement?
