### ISSUE TITLE
Bookmark a shiny app whose UI is made up of individual files.

### ISSUE THREAD

**Issue by abhispatel42** [rstudio/shiny#2336]
The UI of my shiny app is not in the fluid-page, but rather made up of functions that are defined in other R files. I am unaware as where to define the bookmarkButton() - in the main R file or individual R files.

`header <- shinydashboard::dashboardHeader(
  tags$li(
    class = "dropdown",
    tags$style(".main-header {max-height: 100px;}"),
    tags$style(".main-header .logo {min-height: 60px;}"),
    tags$style(".sidebar-toggle {height: 20px; padding-top: 1px;}"),
    tags$style(".navbar {min-height: 50px;}")
  ),

  title = tags$img(src = "test_logo.PNG", height = "auto",
                   width = 150, aling = "left")
)

sidebar <- shinydashboard::dashboardSidebar(
  tags$style(".left-side, .main-sidebar {padding-top: 50px}"),

  menu_choices("about", "load_dat", "net_vis", "trans", "pub_bias",
               "run_nma", "incon", "results")
)

body <- shinydashboard::dashboardBody(
  format_edits(),

  tabItems(
    # First tab content
    about_content(),

   data_content(),

   net_vis_content(),  

   trans_content() 
  )
 )

ui <- shinydashboard::dashboardPage(header, sidebar, body, skin = "black")

server <- function(input, output,session) {

  output$winbugs <- data_server(input,"data_path")
  output$trts <- data_server(input, "treatment_path")
  output$covar <- data_server(input, "cov_path")

}

shiny::shinyApp(ui, server, enableBookmarking = "url")
`

**Comment by abhispatel42** [comment]
@bborgesr It would be great if you could help me with the matter.

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
