### ISSUE TITLE
Difficulties with insertUI and setting state

### ISSUE THREAD

**Issue by ifellows** [rstudio/shiny#2340]
I have some fairly complex states that need to be set after an `insertUI` call is made. I'm having trouble getting operations to run in the order that I want them to. Here is a small example:

```


library(shiny)

ui <- basicPage(
    h2('Insert'),
    actionButton("loadui","loadui")
)

server <- function(input, output, session) {
    i <- 1
    observeEvent(input$loadui,{
        j <- i
        print(j)
        insertUI(
            "h2",
            "afterEnd",
            tags$div(
                textInput(paste0("txt",j), paste0("txt",j), value=j),
                textInput(paste0("txtn",j), paste0("txtn",j))
            ),
            immediate =TRUE
        )
        
        observeEvent(input[[paste0("txt",j)]],{
            updateTextInput(session, paste0("txtn",j), value= input[[paste0("txt",j)]])
        })
        
        #updateTextInput(session, paste0("txt",j), value= paste("+", input[[paste0("txt",j)]]))
        #updateTextInput(session, paste0("txtn",j), value= "initial")
        onFlushed(function(){
            updateTextInput(session, paste0("txt",j), value= paste("+", isolate(input[[paste0("txt",j)]])))
            updateTextInput(session, paste0("txtn",j), value= "initial")
        })
        i <<- i + 1
    })
    
}

# Run the application 
shinyApp(ui = ui, server = server)

```

When they are inserted, I'd like the first text input to be "+1" and the second one to be "initial". I tried updating within onFlushed or just in the server, but not much helped. Is there a way to trigger an event after all of the input/outputs have been resolved? Or maybe a way to pause reactivity while the inputs are getting updated?

**Comment by jcheng5** [comment]
You want `txt1` to initially be `1`, then for additional logic to immediately make it `+1`, and for `txtn1` to be `initial`, but after the user changes `txt1`, then `txtn1` should adopt that value instead? Does that sum it up?

**Comment by ifellows** [comment]
Yes, that is correct. My use case is much more general than this, but I've tried to abstract out some of the problems that I'm having into a minimal example. The actual use case is to load and save arbitrary shiny modules on the fly. I looked into the bookmarking capabilities, but they don't seem to be applicable.

See:
https://github.com/fellstat/vivid/blob/master/R/server-documents.R#L74
https://github.com/fellstat/vivid/blob/master/R/gizmo.R#L1

**Comment by jcheng5** [comment]
As you've probably figured out, the main thing that makes this tricky is that the single source of truth for inputs is in the client, and your server code can only update those values asynchronously. The `freezeReactiveValue` function is designed to help with this, as it puts specific input values into an unreadable state until the flush cycle ends; any observers/reactives that attempt to read a frozen value will encounter a `req(FALSE)` instead. So it's helpful to call `freezeReactiveValue` both when new UI is inserted, and when calling `updateXXXInput(value=...)`. If I could go back in time, I'd have Shiny invoke `freezeReactiveValue` automatically in the latter case, but it seems too late to do that without potentially breaking backwards compatibility.

The other thing that makes your task tricky is that some of these actions/relations have very specific start and end times. You want `txtn1` to stay in sync with `txt1`, but only after the first user-provided edit to `txt1`. The way you would achieve this in event-driven code is to attach event handlers from within other event handlers, and the same is true for `observeEvent`. There are two `observeEvent` arguments that help with this: `once = TRUE` means that once the observer executes its body, it should destroy itself (regardless of whether the body execution succeeds or errors). And `ignoreInit = TRUE` instructs the observer not to execute until the `eventExpr` invalidates, even if its initial value is non-falsy.

I think this accomplishes what you described:

```r
library(shiny)

ui <- basicPage(
  h2('Insert'),
  actionButton("loadui","loadui")
)

server <- function(input, output, session) {
  i <- 1
  observeEvent(input$loadui,{
    j <- i
    txt_id <- paste0("txt", j)
    txtn_id <- paste0("txtn", j)
    
    print(j)
    insertUI(
      "h2",
      "afterEnd",
      tags$div(
        textInput(txt_id, txt_id, value=j),
        textInput(txtn_id, txtn_id)
      ),
      immediate =TRUE
    )
    freezeReactiveValue(input, txt_id)
    freezeReactiveValue(input, txtn_id)
    
    # When txt finishes initializing, do this once:
    observeEvent(once=TRUE, input[[txt_id]], {
      # Add a `+` to txt
      updateTextInput(session, txt_id, value = paste("+", input[[txt_id]]))
      freezeReactiveValue(input, txt_id)

      # When txt finishes updating, do this once:
      observeEvent(once=TRUE, input[[txt_id]],{
        # Set txtn to "initial
        updateTextInput(session, txtn_id, value = "initial")
        freezeReactiveValue(input, txtn_id)
        
        # The next time txt changes, and every time after that, sync txtn
        observeEvent(ignoreInit=TRUE, ignoreNULL=FALSE, input[[txt_id]],{
          updateTextInput(session, txtn_id, value = input[[txt_id]])
          freezeReactiveValue(input, txtn_id)
        })
      })
    })
    
    i <<- i + 1
  })
  
}

# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by jcheng5** [comment]
BTW, it might be helpful to look at a demo I wrote for R/Pharma last year:
https://github.com/jcheng5/rpharma-demo

The "Add Filter" feature seems like it might be along the lines of what you're doing, and includes edge cases like restoring the dynamically loaded UI from a bookmark.

**Comment by ifellows** [comment]
Thanks. That works, but is a bit of a beast to require my users to write. They have to figure out what to freeze and when, along with having nested observers and additional parameters (`ignoreInit=TRUE`).

Okay, let's see about abstracting out a general solution. How about something like the `update_ui` function below. The function of this would be to execute ui changes after all observers of dependent values have been executed. The operation can be chained together so that some updates can be executed after all observers of previous operations have executed.

Does this look like an approach that would work in general, or are there contingencies that I am not accounting for?




```r
library(shiny)
library(magrittr)

update_ui <- function(update_chain, expr, depends=c(),
                      substitute_update_chain=TRUE, substitute_expr=TRUE,
                      session = shiny::getDefaultReactiveDomain()){
  if(substitute_update_chain)
    update_chain <- substitute(update_chain)
  envir <- parent.frame()
  no_expr <- missing(expr)
  if(substitute_expr && !no_expr)
    expr <- substitute(expr)
  input <- session$input
  for(dep in depends)
    freezeReactiveValue(input, dep)
  n <- length(depends)
  recur <- function(i){
    if(i > n){
      if(!no_expr){
        eval(expr, envir=envir)
        for(dep in depends)
          freezeReactiveValue(input, dep)
      }
      eval(update_chain, envir=envir)
      if(no_expr){
        for(dep in depends)
          freezeReactiveValue(input, dep)
      }
      return()
    }
    observeEvent(
      once=TRUE, 
      input[[depends[i]]],
      recur(i + 1)
    )
  }
  recur(1)
}


ui <- basicPage(
  h2('Insert'),
  actionButton("loadui","loadui")
)

server <- function(input, output, session) {
  i <- 1
  observeEvent(input$loadui,{
    j <- i
    txt_id <- paste0("txt", j)
    txtn_id <- paste0("txtn", j)
    print(j)
    insertUI(
      "h2",
      "afterEnd",
      tags$div(
        textInput(txt_id, txt_id, value=j),
        textInput(txtn_id, txtn_id)
      ),
      immediate =TRUE
    )
    
    observeEvent(input[[paste0("txt",j)]],{
      print("keeping txtn in synch")
      updateTextInput(session, paste0("txtn",j), value= input[[paste0("txt",j)]])
    })
    
    update_ui(
      {
        print("updating txt")
        updateTextInput(session, txt_id, value = paste("+", input[[txt_id]]))
      },
      depends = txt_id
    ) %>% update_ui(
      {
        print("updating txtn")
        updateTextInput(session, txtn_id, value = "initial")
      },
      depends = c(txt_id, txtn_id)
    )
    
    i <<- i + 1
  })
  
}

# Run the application 
shinyApp(ui = ui, server = server)
```

This results in:
```
[1] 1
[1] "keeping txtn in synch"
[1] "updating txt"
[1] "keeping txtn in synch"
[1] "updating txtn"
```

**Comment by jcheng5** [comment]
I'm really losing the plot here... what's an example of a module you'd write in this style? What would be a specific example of txt/txtn?

**Comment by ifellows** [comment]
Sorry, so here is a toy example of a module:

https://github.com/fellstat/vivid/blob/master/R/gizmo-package-data.R

It is not yet written in a correct style. 

Essentially I'm suggesting replacing the block on line 74 with:

```r
update_ui({
        updateSelectInput(session, "selectpkg", selected = state$selectpkg)
        updateSelectInput(
          session,
          "selectdat",
          choices = as.vector(data(package = state$selectpkg)$results[, "Item"]),
          selected = state$selectdat
        )
        updateTextInput(session, "renameas", state$renameas)
        },
        depends= c("selectpkg","selectdat","renameas")
)
```

The current pattern is to have developers create modules that take `state` as a parameter, and apply that initial state to a `ui` that has just been inserted.

**Comment by ifellows** [comment]
Actually, because `renameas` reacts to changes in `selectdat` and `selectdat` reacts to changes in `selectpkg` it would be:

```r
update_ui({
        updateSelectInput(session, "selectpkg", selected = state$selectpkg)
        },
        depends= c("selectpkg")
) %>%
update_ui({
        updateSelectInput(
          session,
          "selectdat",
          choices = as.vector(data(package = state$selectpkg)$results[, "Item"]),
          selected = state$selectdat
        )
        },
        depends= c("selectpkg","selectdat")
) %>%
update_ui({
        updateTextInput(session, "renameas", state$renameas)
        },
        depends= c("selectpkg","selectdat","renameas")
)
```

**Comment by jcheng5** [comment]
OK, I think I understand now.

Two things seem a little strange to me about `update_ui`:

1. Both the input you're waiting on, and the input you're updating, are listed in `depends`. Shouldn't those be separate? e.g. does it make sense for step 2 to be freezing `selectpkg`--shouldn't it just ensure that `selectpkg` is not frozen, before updating and freezing `selectdat`? How about `target = "selectdat", depends = "selectpkg"`? (Or better yet, inferring the `depends` based on the previous pipeline stage? Your description seemed to indicate that was the intent?)
2. I don't really understand the need for `recur`. I would've expected a single `observeEvent` that listens for all of the `depends` at once?
3. Your most recent example shows how to restore the `state`. It doesn't show how to establish the ongoing relationship between `input$selectdat` and `input$renameas`, did you have an idea about how/where to express that?

The idea of the pipeline of serial steps is extremely interesting to me. It looks almost like promises.

**Comment by ifellows** [comment]
To be upfront, I have very little idea how this all works. the internals of how freezing works and exactly when things become unfrozen is unclear to me at present.

1.  So, values are frozen before and after evaluation. If I'm understanding correctly, all values (including target values) should be frozen before, and only target values should be frozen after. It seems that the entire dependency chain has to be specified. For example `txt_id` must be included as a depends in the second call to `update_ui` even though it is not present in the execution expression. The following seems to work for my toy example:
```
update_ui <- function(update_chain, expr, depends=c(), target=c(),
                      substitute_update_chain=TRUE, substitute_expr=TRUE,
                      session = shiny::getDefaultReactiveDomain()){
  if(substitute_update_chain)
    update_chain <- substitute(update_chain)
  envir <- parent.frame()
  no_expr <- missing(expr)
  if(substitute_expr && !no_expr)
    expr <- substitute(expr)
  input <- session$input
  for(dep in c(depends, target))
    freezeReactiveValue(input, dep)
  full <- c(depends, target)
  n <- length(full)
  recur <- function(i){
    if(i > n){
      if(!no_expr){
        eval(expr, envir=envir)
        for(dep in target)
          freezeReactiveValue(input, dep)
      }
      eval(update_chain, envir=envir)
      if(no_expr){
        for(dep in target)
          freezeReactiveValue(input, dep)
      }
      return()
    }
    observeEvent(
      once=TRUE, 
      input[[full[i]]],
      recur(i + 1)
    )
  }
  recur(1)
}
```

2. I don't understand it either. However, getting rid of it doesn't work in the toy example. Using
```r
update_ui <- function(update_chain, expr, depends=c(),
                      substitute_update_chain=TRUE, substitute_expr=TRUE,
                      session = shiny::getDefaultReactiveDomain()){
  if(substitute_update_chain)
    update_chain <- substitute(update_chain)
  envir <- parent.frame()
  no_expr <- missing(expr)
  if(substitute_expr && !no_expr)
    expr <- substitute(expr)
  input <- session$input
  for(dep in depends)
    freezeReactiveValue(input, dep)
  vals <- reactive({
    l <- list()
    for(dep in depends)
      l[[dep]] <- req(input[[dep]])
    l
  })
  n <- length(depends)
  observeEvent(
    once=TRUE,
    vals,
    {
      if(!no_expr){
        eval(expr, envir=envir)
        for(dep in depends)
          freezeReactiveValue(input, dep)
      }
      eval(update_chain, envir=envir)
      if(no_expr){
        for(dep in depends)
          freezeReactiveValue(input, dep)
      }
    }
  )
}
```
results in 
```
Listening on http://127.0.0.1:7510
[1] 1
[1] "updating txt"
[1] "updating txtn"
[1] "keeping txtn in synch"
```
Any idea as to why this is?

3. The ongoing relationship is that whenever `selectdat` is changed `renameas` is updated via an `observeEvent`. Am I missing the point?

I'm glad you find it interesting. Figuring this out is pretty critical for me as whatever pattern I decide on is going to be embedded in a way that will be difficult to change later, so I want to get it right.

**Comment by jcheng5** [comment]
Let's take a step back. My understanding of what `update_ui` is supposed to mean is:

1. Automatically wait until the inputs in `depends` become available (i.e. are not frozen)
2. Then execute this code I'm giving you (`updateXXXInput`, etc.)
3. Then automatically freeze the input I just told you to
4. _Then and only then_, execute the next `update_ui` in the chain

Am I wrong?

**Comment by ifellows** [comment]
I guess it depends on what you mean by "becomes available." I'd like initialization to happen after all observers in the dependency chain have executed. For example if `c` observes input `b` and `b` observes input `a`, then a dependency chain `c("a","b","c")` should only execute step 2 after both observers have completed.

Taking a further step back, I don't want to shove a square peg into a round hole. My goal is to have a pattern that is easy to use and that can restore a module to the state it was in when it was saved. It seems like the existing infrastructure around bookmarking should be relevant, but I don't see how to use those facilities in this more dynamic case.

Another option might be to work with the pattern that initialization should happen prior to server code execution, so something like
```r
update_ui({
    updateXXX()
    ...
  },
  depends=c(txt_id, txtn_id)
) %>% {
   ...  all the server code ...
}
```

Of course the module writer would have to be careful to use `ignoreInit` in the server code so as to not overwrite the initialization. I wonder if this might be simpler as there shouldn't be multiple asychronous dependencies within the initialization code (just a bunch of `updateXXXInput` calls).

**Comment by jcheng5** [comment]
Wait, wait. Now that I look at the selectpkg/selectdat/renameas example again, I now realize there's no relationship between these inputs _during restore time_; they all read the `state` object, not each other. I think I understand what you're saying now. I was thinking the restore had to be done as a step-by-step process (the restore of each input fully taking effect before proceeding to the next one) but that's not the case, is it? You just want to make sure the observers don't fire until the user actually types in a new value.

If that's correct, then I believe your existing gizmo-package-data.R is very close to correct; your two `observeEvent`s just need `ignoreInit = TRUE`, and the calls to `updateXXXInput` using `state` need to be followed or preceded (doesn't matter which) with `freezeReactiveValue` calls. If you want to make a more elegant wrapper, it would just be syntactic sugar over that, I think.

By the way, I do think the bookmark restoring machinery is extremely relevant, but I don't think we currently have the necessary functions exported that would let you create and install a restore context. @wch would need to weigh in on whether exposing those would be a good idea and what it would look like.

I presume you already attempted to "just" let the built-in bookmarking feature automatically restore without you doing anything, and it didn't work?

**Comment by ifellows** [comment]
Okay, I think I have a plan of action. Bookmarking as it stands wont work because I'm saving/restoring only part of the app. Each "document" in the app is dynamic and has a bunch of "gizmos" (shiny modules) in it. The user goes through a dialog to save this document or load one from file (see https://youtu.be/fJMhS2BUf_c?t=428).

Ideally, I'd REALLY like to have the default save/load behavior that bookmarking does, so the module writer wouldn't have to do anything, provided their ui was sufficiently simple.

**Comment by alandipert** [comment]
@ifellows Closing because your question appears to have been resolved, but feel free to open a thread on [Community](http://community.rstudio.com) if you have additional questions.
