### ISSUE TITLE
[Feature Request] Eager versions of pollReactive and reactiveFileReader

### ISSUE THREAD

**Issue by jeffkeller87** [rstudio/shiny#2348]
The `pollReactive` and `reactiveFileReader` functions are, well, reactive, which means the `valueFunc` and `readFunc` functions are not run unless the reactive is needed by another observer or reactive.

I have a use-case where `valueFunc`/`readFunc` are relatively expensive, but observers that are dependent on these reactives need to be relatively fast.

In this case, it would be better to have an eager, observant version of `pollReactive` and `reactiveFileReader`, so that the idle time between `input$button` clicks can be used to run `valueFunc`/`readFunc`.

```
data <- reactiveFileReader(2000, session, filePath = "data.csv", readFunc = function(filePath) {
    ...
    # Takes ~1000ms to run
})

observe({
    # This block should only be triggered by input$button
    input$button
    use_data_somehow <- isolate(data())
    # user expectation is that this block runs effectively instantaneously (i.e. <100ms)

    # as it stands now, the first time input$button is clicked after a file
    # modification is detected, this block will take >1000ms to run
    # subsequent button clicks will be very fast (as desired), until a file change is detected again
})
```

**Comment by shrektan** [comment]
A workaround I can think of is to create an invisible element on the page which uses `data()`...

**Comment by jcheng5** [comment]
You can actually just do this:

```r
observe({ data() })
```

Same goes for any other lazy reactive you want to turn eager.
