### ISSUE TITLE
How to embed a .swf to Rshiny?

### ISSUE THREAD

**Issue by Qtttttt** [rstudio/shiny#2352]
Hi,I used the function tags$embed("animation.swf"), and I also put the animation.swf in the www folder of the server and ui folder. The page is still blank for this function, could you tell me how to solve it? Thank you.

**Comment by jcheng5** [comment]
Probably need to do tags$embed(src="animation.swf"). You might need to add width and height to the embed as well.

**Comment by Qtttttt** [comment]
> Probably need to do tags$embed(src="animation.swf"). You might need to add width and height to the embed as well.

tags$embed(src = "CI.swf", width="1000",height="1000")

I change to it but it still doesn't work

**Comment by alandipert** [comment]
Hi @Qtttttt, I put together a working example of doing this and deployed it here: https://alandipert.shinyapps.io/swf-embed/

One additional thing to note is that your browser may be configured to block Flash content. Flash content is also not supported in the RStudio viewer.

If you have any additional questions, please post them in the [Shiny category Community](https://community.rstudio.com/c/shiny) &mdash; that's the best place to get answers to your questions and help others.
