### ISSUE TITLE
The "filename" argument of "downloadHandler" has no effect in rstudio's integrated browser

### ISSUE THREAD

**Issue by MarcSousbie** [rstudio/shiny#2357]
Hi,

This is shiny's documentation example for downloadHandler:
```
ui <- fluidPage(
    downloadLink("downloadData", "Download")
)

server <- function(input, output) {
## Our datasetdata <- mtcars
    output$downloadData <- downloadHandler(
        filename = function() {
            paste("data-", Sys.Date(), ".csv", sep="")
},
        content = function(file) {
            write.csv(data, file)
        }
    )
}
shinyApp(ui, server)
```

When executing this in Rstudio (in the integrated browser), the download does not work as expected. When I click on the link, the default file name is "downloadData" (the name of the output), regardless of the value of the "filename" argument.

In firefox or chrome, however, it works as expected.

**Comment by alandipert** [comment]
@MarcSousbie Thank you for the report; however, this is actually a [bug in RStudio](https://github.com/rstudio/rstudio/issues/3483) that will likely be fixed when 1.2 is released.

In the meantime, if you'd like, you can try using one of the RStudio IDE nightly releases. It might be fixed.

**Comment by MarcSousbie** [comment]
@alandipert Thank you for your reply. I should have checked if this came from Rstudio.

**Comment by csmatyi** [comment]
why not try this?


    filename <- function() { paste('mutation_','plot','.png',sep='') },
    content <- function(file) { 
      png(file)
      mutation_plotter()
      dev.off()
    },
    contentType <- 'image/png'
