### ISSUE TITLE
A very annoying bug: can't upload multiple files in shiny if I use rstudio browser

### ISSUE THREAD

**Issue by jasonzhao0307** [rstudio/shiny#2362]
Hi there,

I've been using Rstudio and Rshiny for a long time, and there is a bug that never fixed: if we open a shiny app in rstudio brower, it won't allow multiple file upload, I have to click the button "open in browser" to do that. Could you help me with this? Thanks a lot!!

**Comment by wch** [comment]
Closing because this is an issue with the RStudio IDE, not Shiny. https://github.com/rstudio/rstudio/issues/4531
