### ISSUE TITLE
When sourcing ui.R and server.R, use runApp caller's environment instead of .GlobalEnv as parent

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#237]

**Comment by wch** [comment]
Do we still want to do this? It shouldn't be a difficult change to implement.

**Comment by jcheng5** [comment]
I'm having trouble imagining now why this matters, can you?

**Comment by wch** [comment]
The only thing that I can think of is if you have a function that calls `runApp()`, and you want to set some variables that get inherited by the app, without affecting the global state.

**Comment by jcheng5** [comment]
That must be it. It made more sense before runApp could take objects
instead of directory names, I'd say we can close this.

**Comment by meowcat** [comment]
Hm. I basically still want this. Typical application (in a package)
```
runViewer <- function(database)
{
 runApp(shinyApp(ui = myUI, server = myServer))
}
```

where myServer refers to "database".  I could, of course, make server a *function* dependent on database that builds the server function on the fly, but really?

**Comment by sylvainschmitt** [comment]
Hello,

I'm having the exact same issue than @meowcat : I'm running a shinyApp with runApp function inside my own package function. And I want the shinyApp to get one of the function argument (a directory path to be used in the app). If I understood well currently launching shinyApp use globalenv and not parent env. One solution I found was to assign the function argument to the globalenv, and then I could get it inside the shinyApp. But logically CRAN policy refuse this assignment to globalenv. So is there another way to do it or is it a dead end in the current version of shiny ?

Thank you by advance for your answers

**Comment by jcheng5** [comment]
It's not a dead end at all. There are multiple ways of doing this that don't involve environment inheritance, which would be a pretty bad way to do this anyway IMHO.

Here's a simple way to do what @meowcat suggested and rejected:

```r
serverFactory <- function(database) {
  function(input, output, session) {
    # Just a normal server function in here, except you can use `database` too
  }
}

runViewer <- function(database) {
  runApp(shinyApp(ui = myUI, server = serverFactory(database))
}
```

If having a nested function like that offends your sensibilities, you can do partial application instead:

```r
server <- function(input, output, session, database) {
  # Just a normal server function, but you can use database
}

runViewer <- function(database) {
  runApp(shinyApp(ui = myUI, server = pryr::partial(server, database=database)))
}
```

**Comment by sylvainschmitt** [comment]
It's working thank you.

And I'm always happy to learn more on the use of shiny which is by the way a great package.

Have a nice day,

Sylvain
