### ISSUE TITLE
Shiny 1.3.x behind nginx load balancer

### ISSUE THREAD

**Issue by jekriske-lilly** [rstudio/shiny#2390]
Affects 1.3.0, 1.3.1, and 1.3.1-patch.

When behind a simple nginx load balancer, Shiny 1.3.x with any Shiny app returns a 404 for resources, user defined or otherwise, but works fine if bypassing the proxy.

![image](https://user-images.githubusercontent.com/16085156/56252083-399c3980-6084-11e9-8bd5-c4cebc52b6af.png)

This behavior does not occur with <= 1.2.0
This is 100% reproducible for us and started with 1.3.0. Does this have to do with the Shiny-Shared-Secret header? Is there any documentation around this? @jcheng5 

Thanks

**Comment by jcheng5** [comment]
See the post here: https://community.rstudio.com/t/shiny-v1-3-known-regressions-and-serious-issues/28180/2

Sorry about this!

**Comment by jekriske-lilly** [comment]
This works great. Thanks Joe!
