### ISSUE TITLE
Problem with R 3.6 new set.seed function

### ISSUE THREAD

**Issue by fbertran** [rstudio/shiny#2397]
I tried to install shiny on the latest R level version.

R Under development (unstable) (2019-04-19 r76406) -- "Unsuffered Consequences"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

but it fails.

> devtools::install_github("rstudio/shiny")
Downloading GitHub repo rstudio/shiny@master
   checking for file ‘/tmp/RtmpHtIuKv/remotes4e57695dc26e/rstudio-shiny-bc8fbd6/✔  checking for file ‘/tmp/RtmpHtIuKv/remotes4e57695dc26e/rstudio-shiny-bc8fbd6/DESCRIPTION’
─  preparing ‘shiny’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘shiny_1.3.1.9000.tar.gz’
   
Installing package into ‘/usr/local/lib/R-devel/lib/R/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘shiny’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘shiny’:
 .onLoad failed in loadNamespace() for 'shiny', details:
  call: set.seed(NULL)
  error: 3 arguments passed to .Internal(set.seed) which requires 4
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R-devel/lib/R/library/shiny’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/RtmpHtIuKv/file4e573f11e515/shiny_1.3.1.9000.tar.gz’ had non-zero exit status

Issue should be due to this change

[Package base version 3.5.3 Index]
set.seed(seed, kind = NULL, normal.kind = NULL)

[Package base version 3.6.0 Index]
https://stat.ethz.ch/R-manual/R-devel/library/base/html/Random.html
set.seed(seed, kind = NULL, normal.kind = NULL, sample.kind = NULL)

**Comment by wch** [comment]
We're calling `set.seed(NULL)` here: https://github.com/rstudio/shiny/blob/bc8fbd6/R/globals.R#L8

According to the documentation for `set.seed`, that should be OK: 
https://github.com/wch/r-source/blob/8c1c78a/src/library/base/man/Random.Rd#L46-L47
https://github.com/wch/r-source/blob/8c1c78a/src/library/base/man/Random.Rd#L173-L175

I suspect that the error is a bug in the development version of R, though I'm not 100% sure at the moment.

**Comment by wch** [comment]
FWIW, I'm unable to reproduce this problem with r74605.

```
R Under development (unstable) (2019-04-19 r76405) -- "Unsuffered Consequences"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(shiny)
> 
```

**Comment by fbertran** [comment]
Thanks, I will wipe out my r-devel svn install and try it from scratch. Something wrong may have happened in the update process.
Best.

Envoyé de mon iPhone

**Comment by kanchanpathak06** [comment]
I reinstalled R-devel but I am still getting the above error
