### ISSUE TITLE
Shiny Stateless Sessions Question

### ISSUE THREAD

**Issue by jdonnell01** [rstudio/shiny#2405]
I understand that Shiny sessions are stateful, however I am attempting to implement a stateless load balancer (does not enforce sticky sessions across app instances) across (2) Shiny application instances. When I implemented a load balancer I noticed that I would get intermittent Ajax errors (404 errors) on Chrome due to the Datatables package. This occurs when the request goes to another server than the one the session was initialized with resulting in the 404 error as the session does not exist on that server. I tried updating my app to handle the data on the client-side however performance was severely degraded. Is it possible to re-configure Shiny to be stateless? Mindful that I am not using Shiny Server or Shiny Server PRO, only RStudio with R and IP/port (shiny::runApp) method of hosting the application. Thank you

**Comment by alandipert** [comment]
Hi, thank you for the report, but unfortunately the answer is no: Shiny is not stateless. When operating behind a load balancer, stickiness is required for correct functioning.

**Comment by alandipert** [comment]
Oh, and if you are satisfied with my answer, please close this issue. Otherwise, I'm happy to discuss further 👍
