### ISSUE TITLE
Overlapping two plots

### ISSUE THREAD

**Issue by GhostValk** [rstudio/shiny#2412]
I need to know if it's possible to have two renderPlot outputs exactly in the same position in Shiny, in the same div. One overlapping another, not side by side, just in the same position and of the same size.

I obviously already tried something as simple as:

    output$a <- renderPlot({
        plot(anything)
    })

    output$a <- renderPlot({
        plot(another_thing)
    })
But as expected, the second output block overrides the first one.

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
