### ISSUE TITLE
Problems in accessing Shiny page remotely:

### ISSUE THREAD

**Issue by gladex** [rstudio/shiny#2414]
Hi all,

I deployed Shiny apps on a local server and test the example apps successfully. And I also opened port 3838. But I can not open the app remotely, the page only shows document style. See the attached snapshot.
![Capture](https://user-images.githubusercontent.com/7739145/57027691-aeb86300-6c6f-11e9-94dc-e607ca38241c.JPG)

**Comment by alandipert** [comment]
Hi, thank you for the report. This looks like a problem with your Shiny Server configuration file. Have you consulted the ["Host a Single Application"](https://docs.rstudio.com/shiny-server/#host-a-single-application) section of the admin guide? It could shed some light.

If it doesn't, please provide your `/etc/shiny-server/shiny-server.conf` and we're happy to take a look.

**Comment by alandipert** [comment]
Oh, also, if you're an RStudio customer running Shiny Server Pro, you might consider e-mailing support@rstudio.com with this question. Our support team is fantastic 😃

**Comment by gladex** [comment]
# more /etc/shiny-server/shiny-server.conf
# Instruct Shiny Server to run applications as the user "shiny"
preserve_logs true;
run_as shiny;
# Define a server that listens on port 3838
server {
  listen 3838;

  # Define a location at the base URL
  location / {

    # Host the directory of Shiny Apps stored in this directory
    site_dir /srv/shiny-server;

    # Log all Shiny output to files in this directory
    log_dir /var/log/shiny-server;

    # When a user visits the base URL rather than a particular application,
    # an index of the applications available in this directory will be shown.
    directory_index on;
  }
}

**Comment by alandipert** [comment]
Cool, thanks for sharing that.

It looks to me like the example apps are located in `/srv/shiny-server`, which is the location that appears to be mapped from `/` via `location / { ... }` in your config file. `directory_index on;` is causing a directory index for `/srv/shiny-server` to be generated when you access `/` from your browser. That directory index is what it looks like you shared a screenshot of.

Based on what you've shared so far, I'd suggest moving or removing the example apps from `/srv/shiny-server` and instead placing the apps you wish to deploy there.

**Comment by gladex** [comment]
> Cool, thanks for sharing that.
> 
> It looks to me like the example apps are located in `/srv/shiny-server`, which is the location that appears to be mapped from `/` via `location / { ... }` in your config file. `directory_index on;` is causing a directory index for `/srv/shiny-server` to be generated when you access `/` from your browser. That directory index is what it looks like you shared a screenshot of.
> 
> Based on what you've shared so far, I'd suggest moving or removing the example apps from `/srv/shiny-server` and instead placing the apps you wish to deploy there.

Hi Alan,

The problem is the example apps at "/srv/shiny-server" can not open at all. It only displays directory index. I tried uploading different apps into "/srv/shiny-server". It did not display either. See attached snapshots.

After upgrading this new version of Shiny-Server, the problem occurs. Previously we did not met such errors. 

![Capture1](https://user-images.githubusercontent.com/7739145/57118971-51b8cc00-6d99-11e9-8bca-611cdc7bb842.JPG)
![Capture2](https://user-images.githubusercontent.com/7739145/57118976-58dfda00-6d99-11e9-98ef-077e9c396a21.JPG)

**Comment by alandipert** [comment]
Thanks for the update. I think the next step is to figure out why those applications are not starting.

The best way to diagnose a problem with an application is to inspect its error logs. Based on your configuration, error logs are stored in `/var/log/shiny-server`.

Do you see any files in there, and do they contain anything interesting?

In my experience, the examples not working is an indication that either R is not installed or not working properly or that the `shiny` package is not installed. So, you should confirm that you can run `R` in a terminal and enter R successfully.

If that worked, you should ensure the `shiny` and `rmarkdown` packages are installed globally on your server with `sudo R -e 'install.packages(c("shiny", "rmarkdown"))'`

**Comment by gladex** [comment]
Hi Alan,

Below is the error logs (also the snapshot),
===
# more 01_hello-shiny-20190503-114629-36087.log
su: ignore --preserve-environment, it's mutually exclusive to --login.
bash: R: command not found
===

I install R with root role (CentOS 7), Shiny and rmarkdown can run successfully under root account, but they can not run under other user account in this sever.

Is the error due to such environment? Any suggestion? Thanks a lot for your help.

![Capture](https://user-images.githubusercontent.com/7739145/57173970-96ac3380-6e69-11e9-9f29-9c7fbeef5d5b.JPG)

**Comment by alandipert** [comment]
It sounds like `R` is not in the `PATH` shell variable for the `shiny` user, which is the user running your apps by default.

This command as root will show you where `R` is: `which R`

Then, you should make sure the directory in which `R` resides is on the system `PATH`. I believe that on CentOS you can do this by editing `/etc/profile` as root, but I might be wrong.

Anyway, I hope that helps.

**Comment by gladex** [comment]
> It sounds like `R` is not in the `PATH` shell variable for the `shiny` user, which is the user running your apps by default.
> 
> This command as root will show you where `R` is: `which R`
> 
> Then, you should make sure the directory in which `R` resides is on the system `PATH`. I believe that on CentOS you can do this by editing `/etc/profile` as root, but I might be wrong.
> 
> Anyway, I hope that helps.
Hi Alan,

R is installed as below (under root account),
`(base) [root@efg-cos ~]# which R
/root/miniconda3/bin/R`

To make other accounts use it, I chmod 777 for this installation directory, so other accounts can run R without any problem. But it still can not visit Shiny page remotely, see below snapshot.
![Capture](https://user-images.githubusercontent.com/7739145/57363131-f7fa3c80-71b2-11e9-9a22-a5d1041d85d2.JPG)

BTW, previously installed and successfully tested Shiny apps on other CentOS servers, have the same problems after upgrading shiny-server to the newer version. I do not know whether other users met. 

Thanks a lot for your help.

**Comment by jcheng5** [comment]
If you change user to shiny using `sudo su - shiny` (exactly like that) then `which R`, what is the result?

**Comment by gladex** [comment]
Hi Joe,

It gives, 
`-sh-4.2$ which R`
`/usr/bin/which: no R in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
`
I export the R path in .bashrc file and it works.
`export PATH="/root/miniconda3/lib/R/bin:$PATH"`

**Comment by alandipert** [comment]
I don't think anything related to this has changed in Shiny Server, so I'd guess it's something in CentOS.

I'll close this since it sounds like the issue has been resolved, but please don't hesitate to comment further or create a new issue if you are still experiencing problems.

**Comment by gladex** [comment]
> I don't think anything related to this has changed in Shiny Server, so I'd guess it's something in CentOS.
> 
> I'll close this since it sounds like the issue has been resolved, but please don't hesitate to comment further or create a new issue if you are still experiencing problems.

Hi, Joe,

I use "chmod" the installation folder and modifying .bashrc for shiny account, so it works. Is there any suggestion to modify configuration for CentOS?

**Comment by poorvam** [comment]
HI All,

Your post is very helpful but I am not able to solve my problem following what is recommended above.

I get the same message when i open my shiny app, i cannot open R using "sudo su shiny". 
which: no R in (/sbin:/bin:/usr/sbin:/usr/bin)

i tried export $PATH variable to .bashrc under /root directory but nothing positive.

Can you please help?

Thank you,
Poorva
