### ISSUE TITLE
Can't run shiny app after deleting the R session's tempdir

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#2421]
I noticed that if I delete the folder given by `tempdir()`, I can't run any more shiny apps until I restart my R session.

```
> runApp()
Warning in file(con, "w") :
  cannot open file 'C:\Users\Dean\AppData\Local\Temp\Rtmp4CsZx5\file12f00718d3933': No such file or directory
Error in file(con, "w") : cannot open the connection
```

I doubt this will ever actually be an issue for anyone, it's just something I noticed while experimenting. Perhaps using `tempdir(check = TRUE)` in shiny's source code may be slightly safer than `tempdir()`, but again, this is very unlikely to affect anyone :)

**Comment by daattali** [comment]
Another issue that I decide to close immediately after opening - there is absolutely no practical reason for this to happen, it seems silly. No need to worry about this.

**Comment by ismirsehregal** [comment]
Actually this happens to me on Windows occasionally. The `tempdir()` folder is deleted after the app is ideling for a few days. 

I think using `tempdir(check = TRUE)` would be a very useful thing to do. Do you know about any workaround?

Cheers
