### ISSUE TITLE
Input changed event fired on document

### ISSUE THREAD

**Issue by nteetor** [rstudio/shiny#2442]
This pertains to the javascript side of shiny. I had forgotten and was surprised all over again to see the `shiny:inputchanged` event is not fired on a changing input element and instead is fired on `document`. 

https://github.com/rstudio/shiny/blob/a4a49a354e1b411dbb57bd3e5a0acd5666c62655/srcjs/input_rate.js#L270-L281

So, if one wanted to handle a selection of `shiny:inputchanged` events one must listen for all `shiny:inputchanged` events. The listener must then check each event for a relevant property or properties. This came up as I was imagining a new input, which suppresses the values of its child inputs until a condition is met (think a selection of inputs inside a form updated only when the related submit button is clicked). Unfortunately, implementing such an input while all input changed events are fired on the document seems highly inefficient. 

Is there any possibility of triggering the event on the input element instead of document? If I understand correctly, the event would still bubble up, so existing listeners could still catch the event.

**Comment by alandipert** [comment]
Thank you, that's an interesting insight. I consulted with @jcheng5 and @schloerke and we couldn't think of a reason not to trigger the event on the source input's element instead of on `document`. We also agree it seems like it would be totally backward compatible because of bubbling.

So, a PR would be welcome 👍

**Comment by nteetor** [comment]
Awesome! I'll put together a PR.

**Comment by nteetor** [comment]
The article here, https://shiny.rstudio.com/articles/js-events.html, will be incorrect if this issue is resolved, is a change to the article something I can make or should I file an issue elsewhere?

**Comment by alandipert** [comment]
Ah, thanks for pointing that out. It's in a private repo so it's not something you can file an issue with, but if you would please note it on your PR we can be sure to update it after merging.

**Comment by wch** [comment]
Closed by #2446.
