### ISSUE TITLE
cols doesn't change width of textAreaInput?

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#2465]
```
ui <- fluidPage(
  textAreaInput("a", "Label", rows = 3, cols = 40),
  textAreaInput("b", "Label", rows = 3, cols = 80),
  textAreaInput("c", "Label", rows = 3, cols = 120)
)

shinyApp(ui, function(...) {})
```

<img width="727" alt="image" src="https://user-images.githubusercontent.com/4196/58706349-6a57da00-8377-11e9-9939-5ec090722e77.png">

**Comment by trestletech** [comment]
<img width="605" alt="Screen Shot 2019-06-17 at 1 57 24 PM" src="https://user-images.githubusercontent.com/1593639/59629169-c4a3b980-9131-11e9-836c-88f29bee16a8.png">


Bootstrap is clobbering something. Without it, things work.

Looks like the `.form-control` class is the culprit. It sets width to 100%. This is sort of referred to in the existing docs. 

> Value of the visible character columns of the input, e.g.80. If used with width, width will take precedence in the browser's rendering.

We should just call out that the default Bootstrap styling will provide its own width which also overrides col.

**Comment by hadley** [comment]
I'm not sure the distinction of being inside/outside of bootstrap will mean much to most users.

**Comment by trestletech** [comment]
Agreed. It doesn't feel like deprecating is the right call, IMHO. So my point is just that we should at least set the expectation that this is probably not going to work. Without using too many technical words.
