### ISSUE TITLE
Getting print.key_missing fastmap when trying to run shiny app on R3.6

### ISSUE THREAD

**Issue by shalutiwari** [rstudio/shiny#2483]
Seeing this while running shiny app on R3.6:

> shiny::runApp('051-movie-explorer')
Registered S3 method overwritten by 'shiny':
  method            from   
  print.key_missing fastmap
Loading required package: shiny

**Comment by cpsievert** [comment]
This is now fixed, right @wch?

**Comment by wch** [comment]
Yes, it was fixed by #2517.
