### ISSUE TITLE
Create multiple tabs within one shiny module

### ISSUE THREAD

**Issue by gordocabron** [rstudio/shiny#2486]
Hi,

I recently ran into a problem when I tried to create a module which adds two tabs to a tabset panel. I posted it [here](https://stackoverflow.com/questions/56490966/create-multiple-tabs-within-one-shiny-module). The suggested solution provides a work-around but in the end led to other issues. I suspect that this is not working as intended and therefore file it as bug report. Here is the self-contained code example:

```R
library(shiny)
library(tidyverse)

resultlistUI <- function(id) {
  ns <- NS(id)
  tabPanel(
    title = "Result1",
    "Some text here 2"
  )
  tabPanel(
    title = "Result2",
    "Some text here 3"
  )
}

resultlist <- function(input, output, session) {
}

ui <- fluidPage(
  tabsetPanel(
    id = "tabs",
    tabPanel(
      title = "Tab 1",
      "Some text here"
    ),
    resultlistUI(id = "resultlist1")
  )
)

server <- function(input, output, session) {
}


shinyApp(ui = ui, server = server)
```

I was first wondering why I could not simply separate the two tabs with a comma. When I execute the code only my second tab "Result2" is added to the tabsetPanel. I also tried to use tagList but then none of the tabs was shown.

**Comment by alandipert** [comment]
Hi, thanks for the report.

I'm not sure this is strictly a bug, since the documentation for `tabsetPanel()` states that arguments must be `tabPanel()`s, although like you I thought a `tagList()` might work.

I'm not sure what your larger goal is, I `do.call()` + `tabsetPanel()` seems to address your immediate problem:

```R
library(shiny)
library(tidyverse)

resultlistUI <- function(id) {
  ns <- NS(id)
  list(
    tabPanel(
      title = "Result1",
      "Some text here 2"
    ),
    tabPanel(
      title = "Result2",
      "Some text here 3"
    )
  )
}

resultlist <- function(input, output, session) {
}

ui <- fluidPage(
  do.call(
    tabsetPanel,
    append(
      list(
        id = "tabs",
        tabPanel(
          title = "Tab 1",
          "Some text here"
        )
      ),
      resultlistUI(id = "resultlist1")
    )
  )
)

server <- function(input, output, session) {
}

shinyApp(ui = ui, server = server)
```

`do.call()` is a way to dynamically construct the argument list for a function, which I think is what you need here to pass in `tabPanel()`s from `resultlistUI()` to `tabsetPanel()`.

Is that helpful?

**Comment by gordocabron** [comment]
Hi,
Thanks for the answer. The code works fine for the example. In my current app I used another approach because using the `do.call` variant led to partial execution of server logic of the module on startup. My solution looked like this:

```R
library(shiny)
library(tidyverse)

## module start
results_1_UI <- function(id) {
  ns <- NS(id)
  tabPanel(
    title = "Plot",
    plotOutput(ns("testplot"))
  )
}
results_2_UI <- function(id) {
  ns <- NS(id)
  tabPanel(
    title = "Export",
    downloadButton(ns("download_data"), "Download")
  )
}

results <- function(input, output, session, data) {
  ## do some complicated data transformations
  data_transformed <- data

  output$testplot <- renderPlot(
    {
      data_transformed %>%
        ggplot(aes(x = Sepal.Length, y = Sepal.Width)) +
        geom_point()
    })
  output$download_data <- downloadHandler(
    filename = function() {
      paste("data_", Sys.time(), ".csv", sep = "")
    },
    content = function(file) {
      write.csv(data_transformed, file, row.names = FALSE, quote = FALSE, na = "", fileEncoding = "latin1")
    },
    contentType = "text/csv"
  )
}
### module end

ui <- fluidPage(
  tabsetPanel(
    id = "tabs",
    tabPanel(
      title = "Tab 1",
      "Some text here"
    ),
    results_1_UI(id = "test1"),
    results_2_UI(id = "test1")
  )
)

server <- function(input, output, session) {
  callModule(
    module = results,
    id = "test1",
    data = iris
  )
}

shinyApp(ui = ui, server = server)
```
I used two UI functions - one for each tab - and calling both with the same ID which in my case was no problem as both tabs were not sharing any inputs/outputs. I will close this issue as I recognize that its probably not a bug.
