### ISSUE TITLE
Merging of dataframe using the real time data

### ISSUE THREAD

**Issue by sdiwash** [rstudio/shiny#2503]
Hello,
I am trying to make a near realtime  application. I am using sparklyr to simulate the data as in realtime . Shiny server will read the .csv files created by the sparklyr . I want to merge these dataframes in shiny and use for further analysis or visualizations.I used codes from other  issues in github and stackoverflow but they dont my problem.
my code:

## Server will work on the data reading,data passing to model and passing data to ui section for visualization
data <- read_csv("/home/diwash/projeckt/credit_card_feaud/credit-card-fraud-detector/data/data.csv")

IsThereNewFile <- function() { #  cheap function whose values over time will be tested for equality;
  #  inequality indicates that the underlying value has changed and needs to be
  #  invalidated and re-read using valueFunc
  filenames <- list.files(pattern = "*.csv", full.names = TRUE)
  length(filenames)
}

ReadAllData <- function() { # A function that calculates the underlying value
  filenames <- list.files(pattern = "*.csv", full.names = TRUE)
  read_csv(filenames[length(filenames)])
}

shinyServer(server <- function(input, output, session) {

  ## read the files in 3 second difference
  sampled_data <- reactivePoll(3000, session, IsThereNewFile, ReadAllData)
  real_data <- reactive({ rbind(data, sampled_data())
  })
data <- real_data
  observe({
    
    print(values$data)
  }) 
  source("server/01-dashboard-srv.R", local = TRUE)
  source("server/02-alert-srv.R", local = TRUE)
})

Here i am taking input from reactivepoll which will take input in 3 seconds. I merged the "data" dataframe with sample_data with real_data reactive expression. I want to save upcoming data in the previous data .

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/. It would also help if you include a reproducible example.
