### ISSUE TITLE
Generate docs and JS in CI

### ISSUE THREAD

**Issue by trestletech** [rstudio/shiny#2505]
We should generate Roxygen docs and JS docs in CI. We can then compare the committed code against the generated versions to see if there are differences. That will allow us to automatically fail our CI pipeline if a proposed PR forgot to update some generated asset.

**Comment by hadley** [comment]
I think you should hold of on doing anything for roxygen2, since we're working on a general approach.

**Comment by trestletech** [comment]
Ah, good to know. I think I've got a solution in https://github.com/rstudio/shiny/pull/2507 but we'll gladly roll over to the official one when it's available.
