### ISSUE TITLE
RStudio should have ui and server snippets

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#2512]
So that you can type `ui` <shift+tab> to get:

```R
ui <- fluidPage(
  ...
)
```

Or `server` <shift+tab>:

```R
server <- function(input, output, session) {
  ...
}
```

**Comment by SaurabhWhadgar** [comment]
Just type shinyapp and hit the tab button(or enter ).
![shinyapp_snip](https://user-images.githubusercontent.com/50226745/60357648-d9196900-99f1-11e9-9798-ef115be177da.png)

**Comment by hadley** [comment]
This doesn't work for me. Are you sure it's not a snippet you've added yourself?

**Comment by cderv** [comment]
Thoses snippets on shiny are also present in rstudio.cloud by default. 

![96BBE27E-F4E6-46EC-8761-246DEE0DFC8D](https://user-images.githubusercontent.com/6791940/60389423-08e37200-9ac1-11e9-9b2f-43b6eff1718c.jpeg)

**Comment by SaurabhWhadgar** [comment]
@hadley .. Ya I'm sure. I haven't added on myself. By default, it is there.

**Comment by daattali** [comment]
`shinyapp` has been a snippet in rstudio open source since Sept 2017 https://github.com/rstudio/rstudio/commit/193acea9951fcbb55f4eabd91a1650d6e93a5c97

**Comment by hadley** [comment]
Not sure why it fails for me; I guess I must have accidentally deleted it.

**Comment by earnaud** [comment]
I don't know if it is only for me, but `shinymod` snippet was not updated upon 1.5. 

Here is the way I corrected this:
```
snippet shinymod
	${1:name}_UI <- function(id) {
	  ns <- NS(id)
	  tagList(
		${0}
	  )
	}
	
	${1:name} <- function(id, ${2:additional_arguments}, {
		moduleServer(id, function(input, output, session) {
	  
	  })
	}
```
