### ISSUE TITLE
Shiny gives error if named selectInput choices are a factor

### ISSUE THREAD

**Issue by jnolis** [rstudio/shiny#2515]
Selection inputs in Shiny allow you to provide a named vector of choices so that the names are shown to the user but the values are what are passed to input. It was designed for the choices to be a character vector, but it's easy to accidentally pass it a named factor vector. If you do you get an extremely confusing error.

It seems like selectInput should either:
* convert the vector from factor to character with as.character, or
* provide a more clear error.

Here is an example showing the issue.

Thanks!

```r

library(shiny)

choices <- letters

choices <- factor(choices) # comment this line out and the app works
# if the choices are a factor instead of character, shiny gives the error:
# Error in (function (choice, name)  : 
#   All sub-lists in "choices" must be named.

names(choices) <- LETTERS

ui <- fluidPage(selectInput("example", "Choose", choices))
server <- function(input, output) {}

shinyApp(ui = ui, server = server)
```

**Comment by alandipert** [comment]
Thank you for the report. I experimented with this and it appears to me that the most specific problem is related to *named* factor vectors. This, for example, works:

```R
library(shiny)
choices <- factor(letters)
#names(choices) <- LETTERS
ui <- fluidPage(selectInput("example", "Choose", choices))
server <- function(input, output) {}
shinyApp(ui = ui, server = server)
```

Based on this, I have arrived at the following understanding of the current treatment of factors by `selectInput()`:

1. When `choices` is a factor based on an unnamed vector, it works. The factor levels are the choices that are made available in the select input.
2. When `choices` is a factor based on a named vector, it explodes with the weird/bad error.

I haven't worked enough with factors myself to say confidently whether or not a factor based on a named vector should be handled differently, but my intuition is that it should not. In other words, regardless of whether or not the vector associated with them is named, factor choices are levels (not names, not values).

Does that seem right to you too?

**Comment by schloerke** [comment]
I think `listify` inside `choicesWithNames` should be upgraded to 


```r
listify <- function(obj) {
        makeNamed <- function(x) {
            if (is.null(names(x))) 
                names(x) <- character(length(x))
            x
        }
### start of new code
        if (is.factor(obj) && !is.null(names(obj)) {
          obj <- setNames(as.list(unname(obj)), names(obj))
        }
### end of new code
        res <- lapply(obj, function(val) {
            if (is.list(val)) 
                listify(val)
            else if (length(val) == 1 && is.null(names(val))) 
                as.character(val)
            else makeNamed(as.list(val))
        })
        makeNamed(res)
    }
```

Example:

```
# factor of LETTERS with letters as names
❯❯ a
a b c d e f g h i j 
B A C A A D B B D A 
Levels: A B C D


# current behavior
❯❯ listify(a)
[[1]]
[[1]][[1]]
a 
B 
Levels: A B C D


[[2]]
[[2]][[1]]
b 
A 
Levels: A B C D


[[3]]
[[3]][[1]]
c 
C 
Levels: A B C D


[[4]]
[[4]][[1]]
d 
A 
Levels: A B C D


[[5]]
[[5]][[1]]
e 
A 
Levels: A B C D


[[6]]
[[6]][[1]]
f 
D 
Levels: A B C D


[[7]]
[[7]][[1]]
g 
B 
Levels: A B C D


[[8]]
[[8]][[1]]
h 
B 
Levels: A B C D


[[9]]
[[9]][[1]]
i 
D 
Levels: A B C D


[[10]]
[[10]][[1]]
j 
A 
Levels: A B C D




# expected behavior
❯❯ setNames(as.list(unname(a)), names(a)) %>% listify()
$a
[1] "B"

$b
[1] "A"

$c
[1] "C"

$d
[1] "A"

$e
[1] "A"

$f
[1] "D"

$g
[1] "B"

$h
[1] "B"

$i
[1] "D"

$j
[1] "A"
```
