### ISSUE TITLE
Dynamic includeHTML() with htmlwidgets

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shiny#2535]
There seems to be a problem with using `includeHTML()` dynamically with htmlwidgets. Note that this non-dynamic approach works:

```r
# also works with plotly::plot_ly()
htmlwidgets::saveWidget(leaflet::leaflet(), "foo.html")
ui <- fluidPage(includeHTML("foo.html"))
srv <- function(input, output) {}
shinyApp(ui, srv)
```

But the dynamic approach throws an error. I also tried this with plotly and DT and it throws the same error

```r
ui <- fluidPage(htmlOutput("inc"))
srv <- function(input, output) {
  output$inc <- renderUI(includeHTML("foo.html"))
}
shinyApp(ui, srv)
```

<img width="907" alt="Screen Shot 2019-07-24 at 12 36 37 PM" src="https://user-images.githubusercontent.com/1365941/61815985-0bf82680-ae11-11e9-90ae-1eecbfd20b11.png">

**Comment by tdeenes** [comment]
See also [here](https://stackoverflow.com/questions/40185986/using-includehtml-in-an-r-shiny-app-along-with-dtdatatableoutput-causes-javasc)

**Comment by jcheng5** [comment]
This can't work; even the non-dynamic version shouldn't be used, even though it happens to work right now. `foo.html` is a standalone HTML document, with dependencies fully rendered into the document. There isn't a way for Shiny to referee between the dependencies in `foo.html` and the dependencies that it wants to load for the app, so both copies get loaded.

In this case, both foo.html and the Shiny app include copies of jquery, so it gets loaded twice. Once that happens, jquery starts behaving erratically; in this repro, an object that's definitely a jquery object fails the `obj instanceof jQuery` condition.

**Comment by jcheng5** [comment]
More broadly, `includeHTML` is really primitive, in that it simply inlines whatever HTML you give it. It should only really be used for pretty simple cases. If we really wanted to serve these kinds of use cases (saving rendered HTML on disk that can be persisted between R processes) we'd need an intermediate form of rendered HTML, where the HTML dependencies are not baked into the HTML yet but are serialized to disk in a way that they can be recovered as `htmlDependency` objects.

**Comment by john-harrold** [comment]
Is there a better way to include RMarkdown in shiny Apps? For example, I have an RMD report that I dynamically render and place in a tab. This way the user can see the final report, make changes in the interface and then save it. 

Is there a better way to do this?

**Comment by jcheng5** [comment]
I would definitely do that in an iframe. Otherwise, you're not seeing a true preview of the report, since the report will be subject to the CSS and JS environment of the Shiny app.

**Comment by john-harrold** [comment]
I think this will explain some other strange things I've seen. I'll look into it and bug folks on the RStudio Community if I run into any problems.

Thanks a lot.

**Comment by john-harrold** [comment]
In case someone stumbles on this, I found a good example of the iframe option here:
https://stackoverflow.com/questions/22177974/r-shiny-using-iframe-for-local-files

This seems to solve the problem:
` 
ui <- fluidPage(
   htmlOutput("map")
 )
 
 addResourcePath("tmpuser", getwd())
 server <- function(input,output){
     output$map <- renderUI({
       tags$iframe(seamless="seamless", src= "tmpuser/foo.html", width=800, height=800)
     })
 }

shinyApp(ui, server)
`

**Comment by jcheng5** [comment]
@john-harrold That works! Just a few tips:

* If multiple users might access your app at the same time, it's a good idea to use a distinct (sub)folder or filename for each, so you don't get accidental collisions. The `session$token` object contains a long alphanumeric string that is unique per session.
* Don't forget to delete the file(s) when you're done--though it's hard to know exactly when "done" is in this case. One possibility is `onSessionEnded()`, which might be best if your R process might last a long time. If you're only expecting light traffic, then use a subdirectory of `tempdir()`, which should get cleaned out whenever the R process exits cleanly.

**Comment by tdeenes** [comment]
> Is there a better way to include RMarkdown in shiny Apps? For example, I have an RMD report that I dynamically render and place in a tab. This way the user can see the final report, make changes in the interface and then save it.
> 
> Is there a better way to do this?

@john-harrold  If the RMD doc is simple (no JS is needed), IMO the best option is to do use includeHTML, but put this in the header of your Rmd file:
```yaml
----
output:
  html_document:
    toc: true
    theme: null
    mathjax: null
    css: some_custom.css
----
```

In the custom css file, use a special class (e.g. "rmd-class") which does not collide with any other class in your app. Then, put the rendered HTML in a container with that class, e.g.:

```r
tags$div(
  class = "rmd_class",
  includeHTML("the_rendered_rmd.html")
)
```

Compared to the iframe-solution, this gives you a fully responsive layout.

**Comment by cafernandezlo** [comment]
@tdeenes do you mean a blank css file with a rmd-class specific for the RMD generation? or on the contrary, to include a rmd-class in the web.css and use with both file generation and web?
