### ISSUE TITLE
shiny installation problem (compilation failed for package 'httpuv')

### ISSUE THREAD

**Issue by Saospark** [rstudio/shiny#2536]
Hi, I am trying to install Shiny as a dependency for Seurat. However, when installing the dependency httpuv, I got the following error. Any idea what might caused it? Thanks!

trying URL 'https://cran.revolutionanalytics.com/src/contrib/httpuv_1.5.1.tar.gz'
Content type 'application/octet-stream' length 1758514 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
* installing *source* package 'httpuv' ...
** package 'httpuv' successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++   -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fPIC   -c RcppExports-legacy.cpp -o RcppExports-legacy.o
g++   -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fPIC   -c RcppExports.cpp -o RcppExports.o
g++   -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fPIC   -c callback.cpp -o callback.o
g++   -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fPIC   -c callbackqueue.cpp -o callbackqueue.o
g++   -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fPIC   -c filedatasource-unix.cpp -o filedatasource-unix.o
g++   -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fPIC   -c filedatasource-win.cpp -o filedatasource-win.o
g++   -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fPIC   -c http.cpp -o http.o
g++   -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fPIC   -c httprequest.cpp -o httprequest.o
g++   -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fPIC   -c httpresponse.cpp -o httpresponse.o
g++   -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fPIC   -c httpuv.cpp -o httpuv.o
gcc -std=gnu99 -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fpic  -g -O2  -c md5.c -o md5.o
g++   -I"/home/haonansu/R-3.6.1/include" -DNDEBUG -Ilibuv/include -pthread -I"/home/haonansu/R-3.6.1/library/Rcpp/include" -I"/home/haonansu/R-3.6.1/library/BH/include" -I"/home/haonansu/R-3.6.1/library/later/include" -I/home/haonansu/bzip2-1.0.6/include/ -I /home/haonansu/xz-5.2.4/include/ -I/home/haonansu/pcre-8.40/include/ -I/home/haonansu/curl-7.47.1/include/ -I/home/haonansu/bzip2-1.0.6/include/ -fvisibility=hidden -DSTRICT_R_HEADERS -fPIC   -c mime.cpp -o mime.o
mime.cpp:553: error: in C++98 'mime_map' must be initialized by constructor, not by '{...}'
mime.cpp:553: warning: extended initializer lists only available with -std=c++0x or -std=gnu++0x
mime.cpp:553: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
mime.cpp:553: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
mime.cpp:553: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
mime.cpp:553: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
mime.cpp:553: warning: extended initializer lists only available with -std=c++0x or -std=gnu++0x
mime.cpp:553: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
mime.cpp:553: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
mime.cpp:553: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
mime.cpp:553: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
mime.cpp:553: warning: extended initializer lists only available with -std=c++0x or -std=gnu++0x
mime.cpp:553: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
mime.cpp:553: error: deducing from brace-enclosed initializer list requires #include <initializer_list>
mime.cpp:553: error: no matching function for call to 'std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::map(<brace-enclosed initializer list>)'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_map.h:170: note: candidates are: std::map<_Key, _Tp, _Compare, _Alloc>::map(const std::map<_Key, _Tp, _Compare, _Alloc>&) [with _Key = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _Tp = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _Compare = std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _Alloc = std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >]
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_map.h:150: note:                 std::map<_Key, _Tp, _Compare, _Alloc>::map() [with _Key = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _Tp = std::basic_string<char, std::char_traits<char>, std::allocator<char> >, _Compare = std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, _Alloc = std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >]
make: *** [mime.o] Error 1
ERROR: compilation failed for package 'httpuv'
* removing '/home/haonansu/R-3.6.1/library/httpuv'

The downloaded source packages are in
	'/tmp/Rtmp61gZo0/downloaded_packages'
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("httpuv") :
  installation of package 'httpuv' had non-zero exit status

**Comment by wch** [comment]
What platform are you on, and what compiler (and compiler version) are you using?

**Comment by Saospark** [comment]
I changed some config and it worked now. Thanks
