### ISSUE TITLE
?shinyOptions should link to ?`shiny-options`

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shiny#2544]
Although these pages aren't really documenting the same thing, I think it's easy to land on `?shinyOptions` expecting to find documentation for shiny's various options, when what you really want is ?`shiny-options`.

Also, maybe it's worth considering merging these two into the same page

**Comment by wch** [comment]
I agree that they should be connected somehow. Whichever way we go (link vs one help page), we should make it very clear how they're different.

**Comment by hadley** [comment]
I think they should be a single page
