### ISSUE TITLE
SelectInput crashes with unnamed one-dimensional chracter

### ISSUE THREAD

**Issue by fproske** [rstudio/shiny#2549]
Commit 1a8b36f introduced a crash of `selectInput` when choices is a one-dimensional unnamed character vector. The `choicesWithNames` function in `R/input-utils.R` does not cover this case. 
`listify` recurses into lists so the check for length-1-unnamed-characters makes sense, but it does not cover the case where the original choices vector is a 1-dimensional-character.

**Comment by wch** [comment]
Note: PR #2540 already addresses this.
