### ISSUE TITLE
Add option to ignore incomplete datapoints to brushedPoints

### ISSUE THREAD

**Issue by sempeelman** [rstudio/shiny#2553]
Minimal example:

```
library(shiny)
library(ggplot2)

ui <- basicPage(
  plotOutput("plot1", brush = "plot_brush"),
  dataTableOutput("info")
)

server <- function(input, output) {
  output$plot1 <- renderPlot({
    ggplot(airquality, aes(Ozone, Solar.R)) +
      geom_point()
  })
  
  output$info <- renderDataTable({
    brushedPoints(airquality, input$plot_brush)
  })
}

shinyApp(ui, server)
```

The variables in the original dataframe contain missing values. This causes the dataframe returned by brushedPoints to contain rows consisting only of NA values, when brushing particular regions from the plot (e.g. the region where variable Ozone lies between 150 and 175 and the variable Solar.R lies between 300 and 350).

Can we add an optional argument to brushedPoints() to ignore observations with NA values in the concerned variables?

**Comment by cpsievert** [comment]
I'm pretty sure that, with the changes that came as part of #2410, we now ignore NAs (which I agree is the correct behavior), so try again after installing:

```r
devtools::install_github("rstudio/shiny")
```

(Closing since this seems to be fixed now, but feel free to reopen if I'm missing something)

**Comment by sempeelman** [comment]
Thank you for your reply, I confirm it has already been solved. (I was running the latest available version on CRAN of the package, thereby missing out on all the goodies.)
