### ISSUE TITLE
Consider upgrading  bootrsrap ( 3.3.7 -> 4.X) and jQuery (1.12.4.-> 3.4.X )

### ISSUE THREAD

**Issue by thomasneu** [rstudio/shiny#2554]
Consider upgrading bootrsrap ( 3.3.7 -> 4.X) and jQuery (1.12.4.-> 3.4.X).
Bootstrap 3.3.7 and jQuery 1.12.4 have some known CVE's!

**Comment by jcheng5** [comment]
Thanks for the report!

Note to team: This keeps coming up in Pro support tickets--historically we've explained why these CVEs don't affect Shiny apps but it'd be better to just upgrade. Bootstrap will have to go to 3.4.1 as 4.x is not backward compatible, but jQuery can probably go to the latest (in theory also not backward compatible but from what I've seen the differences are minuscule).
