### ISSUE TITLE
custom css causes navbar page causes undesired outputs

### ISSUE THREAD

**Issue by uttam-1996** [rstudio/shiny#2564]
### System details

Browser Version: 

Output of `sessionInfo()`:

```
# sessionInfo() output goes here
```

### Example application *or* steps to reproduce the problem

 

```R
# Minimal, self-contained example app code goes here
```

### Describe the problem in detail

when using the navbar page with custom css from "https://bootswatch.com/" causes an undesired interaction with the ui elements 

########################################UI CODE###########################

shinyUI(

navbarPage(
           position ="fixed-bottom",
           collapsible = TRUE,
           theme = "bootstrap.css",title = "poultrynxt",
           
           
           tabPanel(title = "Production",
                    
                  fluidRow( style = "margin-top:2%" ,
                  
                    column(4,
                      div(class="card",
                      div(class="card-header","Header",tags$span(style = "float: right",  dropdownButton(circle = F,
                                                                                                         status = "success",icon = icon("cog"),actionBttn("b1",label = "Download Image",block = TRUE,no_outline = TRUE))
)),
                      div(class="card-body","Content")
                      )
                    )
                    
                    
                    )
            )

)
  
)  
  

#########################################
![Screenshot from 2019-08-28 17-43-57](https://user-images.githubusercontent.com/33053682/63854734-732e6b00-c9bb-11e9-97db-0236ea062926.png)

**Comment by shrektan** [comment]
I guess you are using the theme of bootstrap version 4 but shiny only support version 3. Download theme from https://bootswatch.com/3/ will be fine.

**Comment by uttam-1996** [comment]
Yes i noticed it now, is there any possibility in near future  of navbar page to support bootstrap 4 ?
