### ISSUE TITLE
Edge receives 500 errors for run-time html dependencies

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shiny#2571]
Discovered in https://github.com/ropensci/plotly/issues/1605. See there for a minimal example using plotly (but the same issue surfaces anytime you have a runtime html dependency in shiny).

#2280 seems to have introduced a problem with serving run-time html dependencies to an Edge browser. Here's a minimal example that generates 500 error codes for me on Edge 44.18362.267.0. It's worth noting that I don't get the same errors in the same environment with Chrome or Firefox

```r
library(shiny)

ui <- fluidPage(
  uiOutput("x")
)

server <- function(input, output, session) {
  output$x <- renderUI({
    htmltools::attachDependencies(
      tags$p("Hello, check your console for errors!"),
      crosstalk::crosstalkLibs()
    )
  })
}

shinyApp(ui, server)
```

**Comment by jcheng5** [comment]
Will be fixed in https://github.com/rstudio/httpuv/pull/239
