### ISSUE TITLE
Can't see any output from server.R

### ISSUE THREAD

**Issue by pathumphre** [rstudio/shiny#260]
I've tried modifying a shiny app from the demo, and also copied directly the Hello Shiny app into two files. I can get the UI from Hello, but no graph.

From my modification of another CLT app (tgouhier/climit  from gIthub), where I deleted some of the parent populations, I don't even get the UI.

The files were created using Notepad, and my computer recognizes them as R files.

Any suggestions?

**Comment by mmulchandani** [comment]
I recently noticed this problem too and the problem crops up even with Chrome. I posted about it here(https://community.rstudio.com/t/output-served-by-shiny-server-does-not-display-on-laptop/23530), but haven't got any response.

In case a solution was found for this, please do post. Thanks.
