### ISSUE TITLE
Error in output$spatialplot <- renderPlot({ : object 'output' not found

### ISSUE THREAD

**Issue by avijit09** [rstudio/shiny#2644]
Hi Experts,

I am trying to build an app where I can show map for my spatial analysis. Here is the snipet of my code.

```
library(shiny)
library(ggplot2)
library(dplyr)
library(ggmap)
library(plotly)


crime <- read.csv("crimedata.csv", stringsAsFactors = FALSE)
crime$date <- as.Date(crime$date, format = "%m/%d/%Y")

exclude_theft_crime <- subset(crime, offense %in% c('aggravated assault', 'burglary', 'murder','rape', 'robbery'))

ui <- fluidPage(
  titlePanel("Houston Crime Spatial Analysis"),
  sidebarLayout(
    sidebarPanel(
      uiOutput("offenseOutput"),
      uiOutput("datesOutput")
    ),
    mainPanel(
      plotOutput("spatialplot")
      
    )
  )
)
##UI for rendering offence input and and burglary is autoselected at the start

server <- function(input, output, session) {
  output$offenseOutput <- renderUI({
    checkboxGroupInput("offenseInput", "Choose from below",
                       sort(unique(exclude_theft_crime$offense)),
                       selected = "robbery")   
  })
  
  #Date range
  
  output$datesOutput <- renderUI({
    dateRangeInput("dates", label = "Select Date range", start = "2010-03-01", 
                   end = "2010-04-30")
  })
  
  
  exclude_theft_crime %>%
    filter( offense == input$offenseInput,
            date >=input$dates[1] & date <=input$dates[2])
  
}

##rendering map and plotting points

output$spatialplot <- renderPlot({
  if (is.null(Filtered())) {
    return()
  }
  
  ggmap(get_stamenmap()) + geom_point(data =Filtered(), aes(lon, lat,color=offense))
  
})

##display offence in MAP

output$results <- renderTable({
  filtered()
})

##merging UI and server for APP run

shinyApp(ui = ui, server = server)
```

When I run my app, I always get the below error,
the error;
Can anyone help me with this problem. I tried all possible ways to fix it. But couldnt able to solve it.

Thanks in advance.

Error in output$spatialplot <- renderPlot({ : object 'output' not found

**Comment by cpsievert** [comment]
Looks like you need to move the `}` that appears just before `output$spatialplot` to be just before `shinyApp(ui = ui, server = server)`

**Comment by avijit09** [comment]
Hello,

Thank you for your reply. But i am getting this following error


Warning: Error in .getReactiveEnvironment()$currentContext: Operation not allowed without an active reactive context

**Comment by cpsievert** [comment]
This new error is because your attempting to read reactive variables outside of a reactive context:

```r
exclude_theft_crime %>%
    filter( offense == input$offenseInput,
            date >=input$dates[1] & date <=input$dates[2])
```

This is more of a question of how to use Shiny then a bug report or feature. Please post questions on https://community.rstudio.com/ and read more about Shiny at https://shiny.rstudio.com/ and https://mastering-shiny.org

**Comment by avijit09** [comment]
Hi,

Thanks.. could you pls help me to resolve this issue. I am a newbie to this. would appreciate your help.

**Comment by avijit09** [comment]
> This new error is because your attempting to read reactive variables outside of a reactive context:
> 
> ```r
> exclude_theft_crime %>%
>     filter( offense == input$offenseInput,
>             date >=input$dates[1] & date <=input$dates[2])
> ```
> 
> We reserve Github issues bug reports or feature requests only, it seems you have more of a question on how Shiny works. Please post questions on https://community.rstudio.com/ and read more about Shiny at https://shiny.rstudio.com/ and https://mastering-shiny.org before posting Github issues.

do you mind help me with resolving this issue?. how should i resolve this?
