### ISSUE TITLE
Operation not allowed without an active reactive context.

### ISSUE THREAD

**Issue by avijit09** [rstudio/shiny#2646]
This new error is because your attempting to read reactive variables outside of a reactive context:exclude_theft_crime %>%     filter( offense == input$offenseInput,             date >=input$dates[1] & date <=input$dates[2])We reserve Github issues bug reports or feature requests only, it seems you have more of a question on how Shiny works. Please post questions on https://community.rstudio.com/ and read more about Shiny at https://shiny.rstudio.com/ and https://mastering-shiny.org before posting Github issues.do you mind help me with resolving this issue?. how should i resolve this?
--
dfsd

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
