### ISSUE TITLE
Possible Memory Leak?

### ISSUE THREAD

**Issue by loicpalma** [rstudio/shiny#2648]
Hello,

I am trying to make a R Dashboard that I host through Travis. 

The repo containing all the code is here: https://github.com/loicpalma/Shiny_App

Locally the app works perfectly well, but on shinyapps.io, when I try to get some confusion matrix, ROCS, etc... I get disconnected and get an "Out of memory!" error in the logs.

I have heard that there are several memory leaks with `reactiveEvents()` ...

**How do I fix that ?**

For information, you can connect to my App through here: https://loicpalma.shinyapps.io/Test_Shiny/

**Comment by loicpalma** [comment]
Here are my session_info():

`
> devtools::session_info()
- Session info -------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  French_France.1252          
 ctype    French_France.1252          
 tz       Europe/Paris                
 date     2019-09-30                  

- Packages -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package         * version    date       lib source        
 assertthat        0.2.1      2019-03-21 [1] CRAN (R 3.6.1)
 backports         1.1.4      2019-04-10 [1] CRAN (R 3.6.0)
 callr             3.3.1      2019-07-18 [1] CRAN (R 3.6.1)
 caret           * 6.0-84     2019-04-27 [1] CRAN (R 3.6.1)
 class           * 7.3-15     2019-01-01 [1] CRAN (R 3.6.1)
 cli               1.1.0      2019-03-19 [1] CRAN (R 3.6.1)
 codetools         0.2-16     2018-12-24 [2] CRAN (R 3.6.1)
 colorspace        1.4-1      2019-03-18 [1] CRAN (R 3.6.1)
 corrplot        * 0.84       2017-10-16 [1] CRAN (R 3.6.1)
 crayon            1.3.4      2017-09-16 [1] CRAN (R 3.6.1)
 crosstalk         1.0.0      2016-12-21 [1] CRAN (R 3.6.1)
 data.table        1.12.2     2019-04-07 [1] CRAN (R 3.6.1)
 desc              1.2.0      2018-05-01 [1] CRAN (R 3.6.1)
 devtools          2.2.1      2019-09-24 [1] CRAN (R 3.6.1)
 digest            0.6.20     2019-07-04 [1] CRAN (R 3.6.1)
 dplyr           * 0.8.3      2019-07-04 [1] CRAN (R 3.6.1)
 DT              * 0.8        2019-08-07 [1] CRAN (R 3.6.1)
 e1071           * 1.7-2      2019-06-05 [1] CRAN (R 3.6.1)
 ellipsis          0.3.0      2019-09-20 [1] CRAN (R 3.6.1)
 foreach           1.4.7      2019-07-27 [1] CRAN (R 3.6.1)
 fs                1.3.1      2019-05-06 [1] CRAN (R 3.6.1)
 generics          0.0.2      2018-11-29 [1] CRAN (R 3.6.1)
 ggplot2         * 3.2.1      2019-08-10 [1] CRAN (R 3.6.1)
 glue              1.3.1      2019-03-12 [1] CRAN (R 3.6.1)
 gower             0.2.1      2019-05-14 [1] CRAN (R 3.6.1)
 gtable            0.3.0      2019-03-25 [1] CRAN (R 3.6.1)
 htmltools         0.3.6      2017-04-28 [1] CRAN (R 3.6.1)
 htmlwidgets       1.3        2018-09-30 [1] CRAN (R 3.6.1)
 httpuv            1.5.1      2019-04-05 [1] CRAN (R 3.6.1)
 ipred             0.9-9      2019-04-28 [1] CRAN (R 3.6.1)
 iterators         1.0.12     2019-07-26 [1] CRAN (R 3.6.1)
 jsonlite          1.6        2018-12-07 [1] CRAN (R 3.6.1)
 labeling          0.3        2014-08-23 [1] CRAN (R 3.6.0)
 later             0.8.0      2019-02-11 [1] CRAN (R 3.6.1)
 lattice         * 0.20-38    2018-11-04 [2] CRAN (R 3.6.1)
 lava              1.6.6      2019-08-01 [1] CRAN (R 3.6.1)
 lazyeval          0.2.2      2019-03-15 [1] CRAN (R 3.6.1)
 lubridate         1.7.4      2018-04-11 [1] CRAN (R 3.6.1)
 magrittr          1.5        2014-11-22 [1] CRAN (R 3.6.1)
 MASS              7.3-51.4   2019-03-31 [2] CRAN (R 3.6.1)
 Matrix            1.2-17     2019-03-22 [2] CRAN (R 3.6.1)
 memoise           1.1.0      2017-04-21 [1] CRAN (R 3.6.1)
 mime              0.7        2019-06-11 [1] CRAN (R 3.6.0)
 ModelMetrics      1.2.2      2018-11-03 [1] CRAN (R 3.6.1)
 munsell           0.5.0      2018-06-12 [1] CRAN (R 3.6.1)
 nlme              3.1-140    2019-05-12 [2] CRAN (R 3.6.1)
 nnet              7.3-12     2016-02-02 [2] CRAN (R 3.6.1)
 pillar            1.4.2      2019-06-29 [1] CRAN (R 3.6.1)
 pkgbuild          1.0.5      2019-08-26 [1] CRAN (R 3.6.1)
 pkgconfig         2.0.2      2018-08-16 [1] CRAN (R 3.6.1)
 pkgload           1.0.2      2018-10-29 [1] CRAN (R 3.6.1)
 plyr              1.8.4      2016-06-08 [1] CRAN (R 3.6.1)
 precrec         * 0.10.1     2019-04-12 [1] CRAN (R 3.6.1)
 prettyunits       1.0.2      2015-07-13 [1] CRAN (R 3.6.1)
 processx          3.4.1      2019-07-18 [1] CRAN (R 3.6.1)
 prodlim           2018.04.18 2018-04-18 [1] CRAN (R 3.6.1)
 promises          1.0.1      2018-04-13 [1] CRAN (R 3.6.1)
 ps                1.3.0      2018-12-21 [1] CRAN (R 3.6.1)
 purrr             0.3.2      2019-03-15 [1] CRAN (R 3.6.1)
 R6                2.4.0      2019-02-14 [1] CRAN (R 3.6.1)
 Rcpp              1.0.2      2019-07-25 [1] CRAN (R 3.6.1)
 recipes           0.1.6      2019-07-02 [1] CRAN (R 3.6.1)
 remotes           2.1.0      2019-06-24 [1] CRAN (R 3.6.1)
 reshape2          1.4.3      2017-12-11 [1] CRAN (R 3.6.1)
 rlang             0.4.0      2019-06-25 [1] CRAN (R 3.6.1)
 rpart             4.1-15     2019-04-12 [1] CRAN (R 3.6.1)
 rprojroot         1.3-2      2018-01-03 [1] CRAN (R 3.6.1)
 rsconnect         0.8.15     2019-07-22 [1] CRAN (R 3.6.1)
 rstudioapi        0.10       2019-03-19 [1] CRAN (R 3.6.1)
 scales            1.0.0      2018-08-09 [1] CRAN (R 3.6.1)
 sessioninfo       1.1.1      2018-11-05 [1] CRAN (R 3.6.1)
 shiny           * 1.3.2      2019-04-22 [1] CRAN (R 3.6.1)
 shinycssloaders * 0.2.0      2017-05-12 [1] CRAN (R 3.6.1)
 shinydashboard  * 0.7.1      2018-10-17 [1] CRAN (R 3.6.1)
 shinyWidgets    * 0.4.9      2019-09-10 [1] CRAN (R 3.6.1)
 stringi           1.4.3      2019-03-12 [1] CRAN (R 3.6.0)
 stringr           1.4.0      2019-02-10 [1] CRAN (R 3.6.1)
 survival          2.44-1.1   2019-04-01 [2] CRAN (R 3.6.1)
 testthat          2.2.1      2019-07-25 [1] CRAN (R 3.6.1)
 tibble          * 2.1.3      2019-06-06 [1] CRAN (R 3.6.1)
 tidyselect        0.2.5      2018-10-11 [1] CRAN (R 3.6.1)
 timeDate          3043.102   2018-02-21 [1] CRAN (R 3.6.0)
 usethis           1.5.1      2019-07-04 [1] CRAN (R 3.6.1)
 withr             2.1.2      2018-03-15 [1] CRAN (R 3.6.1)
 xgboost         * 0.90.0.2   2019-08-01 [1] CRAN (R 3.6.1)
 xtable            1.8-4      2019-04-21 [1] CRAN (R 3.6.1)
 yaml              2.2.0      2018-07-25 [1] CRAN (R 3.6.0)
`

**Comment by jcheng5** [comment]
It sounds from your description like there's not enough memory to do certain operations at all. The first thing to try is to increase the instance size of your shinyapps.io app, the default gives you a relatively small amount of RAM.

**Comment by loicpalma** [comment]
Could you please tell me how to do so? I don't see any of this options even in the advanced settings tab of Shinyapps.io

**Comment by jcheng5** [comment]
Hmmm, try the instructions here: https://docs.rstudio.com/shinyapps.io/applications.html

**Comment by loicpalma** [comment]
![image](https://user-images.githubusercontent.com/43248962/65905575-17dc0800-e3c1-11e9-93cc-14374ed50af0.png)

Well I already have it set to large (1GB)

**Comment by jcheng5** [comment]
Try 2GB

**Comment by loicpalma** [comment]
I only have the basic (free) version of Shinyapps. 

Don't you think the application should be okay with only 1GB? I mean my datasets only is 50Mb

**Comment by jcheng5** [comment]
It's impossible for me to say--it's your code. Certainly, lots and lots of Shiny apps work just fine in 1GB.

**Comment by loicpalma** [comment]
Well, is there a way to find out in my code what is taking so much memory ?

**Comment by jcheng5** [comment]
I'd start by running the app (locally) under profvis:
https://rstudio.github.io/profvis/

**Comment by loicpalma** [comment]
Thanks.

Found out a trick to make sure Shiny doesn't have to make such big executions.

**Comment by jcheng5** [comment]
Glad you were able to figure it out!
