### ISSUE TITLE
Option to start the shiny app in a separate R session with RStudio runApp, just like Knitting Rmd

### ISSUE THREAD

**Issue by dracodoc** [rstudio/shiny#2661]
This is related to #2034 (which want to start shiny app in local env and don't pollute global env), but considering shiny app itself need to have its own global environment, I think the better approach is to start the shiny in a separate R session.

I often need to prepare some data for shiny app use, and it happened more than once that the app used some variable in global env thus worked normal, but failed in deployed mode because the data was not imported in the app itself yet. This kind of problem can be revealed immediately and fixed easier if the app start in a clean environment. It's simply impractical to clean up session in every test run of shiny app, because I need to continue to work with the data in global env.

I think in general a shiny app is intended to be deployed and using some independent environment, just like knitr by default knit the RMD in a clean session. Thus it make senses use similar strategy with starting shiny app in RStudio.

**Comment by wch** [comment]
Hi, I suggest you file this at https://github.com/rstudio/rstudio/issues.

Currently, you can use the [callr package](https://github.com/r-lib/callr#readme) to launch shiny apps in a separate process.

**Comment by dracodoc** [comment]
Thanks for pointing to callr, which seemed to be a solution to my problem. I was thinking this is related to `runApp` so filed issue here.
