### ISSUE TITLE
nearPoints with a discrete x-axis does not find points with a NA x-value

### ISSUE THREAD

**Issue by stla** [rstudio/shiny#2666]
Hello,

 Please give a try to the app below. The point with a `NA` value on the x-axis is not found by `nearPoints`. 

 With `shiny < 1.4.0` I added the variable `as.integer(dat$fact)` to the dataframe `dat` and I used this variable for `xvar` in `nearPoints`. This worked with `NA` values (if I correctly remember). 

```
library(shiny)
library(ggplot2)

ui <- basicPage(
  plotOutput("plot", hover = hoverOpts("hover")),
  verbatimTextOutput("nearPoint")
)

server <- function(input,output){
  
  dat <- data.frame(
    x = 1:3,
    fact = c("a","b",NA)
  )
  # dat$fact <- addNA(dat$fact) useless!
  
  output$plot <- renderPlot({
    ggplot(dat, aes(fact, x)) + geom_point()  
  })
  
  output$nearPoint <- renderPrint({
    if(!is.null(coordinfo <- input$hover)){
      nearPoints(dat, coordinfo, threshold = 15, maxpoints = 1)
    }
  })
}

shinyApp(ui, server)
```

**Comment by cpsievert** [comment]
Thanks for the report. I do see a difference between shiny 1.4 and 1.3 when `addNA()` is used.

**Comment by cpsievert** [comment]
Until a proper fix is done, note that you can work around this specific problem by coercing the NA values to a string

```r
dat$fact <- ifelse(is.na(dat$fact), "NA", dat$fact)
```
