### ISSUE TITLE
error in istalling httpuv

### ISSUE THREAD

**Issue by rezamds** [rstudio/shiny#2667]
Hi
I use centos7 and R 3.6
when I try to install httpuv package this error appears:

                 from /usr/lib64/R/library/BH/include/boost/algorithm/string/ite                                                                                                              r_find.hpp:27,
                 from /usr/lib64/R/library/BH/include/boost/algorithm/string/spl                                                                                                              it.hpp:16,
                 from /usr/lib64/R/library/BH/include/boost/algorithm/string.hpp                                                                                                              :23,
                 from /usr/lib64/R/library/BH/include/boost/date_time/tz_db_base                                                                                                              .hpp:24,
                 from /usr/lib64/R/library/BH/include/boost/date_time/local_time                                                                                                              /tz_database.hpp:14,
                 from /usr/lib64/R/library/BH/include/boost/date_time/local_time                                                                                                              /local_time.hpp:19,
                 from /usr/lib64/R/library/BH/include/boost/date_time.hpp:15,
                 from utils.h:13,
                 from websockets.h:12,
                 from websockets.cpp:1:
/usr/lib64/R/library/BH/include/boost/get_pointer.hpp: At global scope:
/usr/lib64/R/library/BH/include/boost/get_pointer.hpp:48:40: warning: ‘template<                                                                                                              class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
 template<class T> T * get_pointer(std::auto_ptr<T> const& p)
                                        ^~~~~~~~
In file included from /usr/local/include/c++/7.4.0/memory:80:0,
                 from /usr/lib64/R/library/BH/include/boost/config/no_tr1/memory                                                                                                              .hpp:21,
                 from /usr/lib64/R/library/BH/include/boost/smart_ptr/shared_ptr                                                                                                              .hpp:23,
                 from /usr/lib64/R/library/BH/include/boost/shared_ptr.hpp:17,
                 from websockets.h:9,
                 from websockets.cpp:1:
/usr/local/include/c++/7.4.0/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG -Ilibuv/include -pthread -I"/u                                                                                                              sr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/usr/lib                                                                                                              64/R/library/later/include" -I/usr/local/include -fvisibility=hidden -DSTRICT_R_                                                                                                              HEADERS -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-p                                                                                                              rotector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=ge                                                                                                              neric  -c winutils.cpp -o winutils.o
cp -p -f libuv/m4/lt_obsolete.m4 libuv/m4/lt~obsolete.m4
(cd libuv \
        && touch aclocal.m4 \
        && touch -r aclocal.m4 configure Makefile.in \
        && chmod +x configure \
        && CC="gcc -m64 -std=gnu99" CFLAGS="-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SO                                                                                                              URCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-                                                                                                              gcc-switches   -m64 -mtune=generic  -fpic -fvisibility=hidden" AR="ar" RANLIB="r                                                                                                              anlib" LDFLAGS="-Wl,-z,relro " ./configure "--quiet")
configure: error: unsafe absolute working directory name
make: *** [libuv/Makefile] Error 1
ERROR: compilation failed for package ‘httpuv’
* removing ‘/usr/lib64/R/library/httpuv’
Warning message:
In install.packages("https://cran.r-project.org/src/contrib/httpuv_1.5.2.tar.gz"                                                                                                              ,  :
  installation of package ‘/users/$USER/tmp/RtmpcTiCwG/downloaded_packages/httpu                                                                                                              v_1.5.2.tar.gz’ had non-zero exit status

**Comment by wch** [comment]
It looks like the problem is that your temp directory is in `/users/$USER/tmp`, which the configure script doesn't like. If your home directory is `/users/$USER`, that will probably cause problems with a lot of other software. If it isn't `/users/$USER`, but your system is using that for the temp directory for some reason, then your system is probably misconfigured somehow.

**Comment by rezamds** [comment]
please help me
indeed  I have problem in installing package in R
I only can install packages one by one from its url
If I use "install.package("anypkg")" it downloads all dependencies but shows this error

trying URL 'https://ftp.fau.de/cran/src/contrib/httpuv_1.5.2.tar.gz'
Content type 'application/x-gzip' length 1763900 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

Warning: invalid package ‘/users/root/tmp/RtmpSv4OZ0/downloaded_packages/httpuv_1.5.2.tar.gz’
Error: ERROR: no packages specified

The downloaded source packages are in
        ‘/users/$USER/tmp/RtmpSv4OZ0/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("httpuv") :
  installation of package ‘httpuv’ had non-zero exit status

**Comment by wch** [comment]
This issue tracker is for reporting bugs in httpuv. It sounds like your system is misconfigured somehow, but I don't know how exactly. You may be able to find someone who can help if you ask on stackoverflow.com.
