### ISSUE TITLE
tabsetPanel(type = "hidden")

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#2680]
It would be useful to have a tabset variant where the user level controls for switching between tabs are hidden, and they can only be changed via `updateTabsetPanel()`. I think that this would facilitate a useful pattern for dynamic UI, where instead of having to use `renderUI()` or `insertUI()`/`removeUI()` you'd instead reveal different UI by changing the active tab.

For example, you could imagine implementing a wizard by having next and previous action buttons that adjusted the active tab.

**Comment by cpsievert** [comment]
FWIW, this is already possible with a bit of css:

```css
#inputId { display: none; }
```

For example,

```r
ui <- fluidPage(
  tags$style("#inTabset { display:none; }"), 
  sidebarLayout(
    sidebarPanel(
      sliderInput("controller", "Controller", 1, 3, 1)
    ),
    mainPanel(
      tabsetPanel(id = "inTabset",
                  tabPanel(title = "Panel 1", value = "panel1", "Panel 1 content"),
                  tabPanel(title = "Panel 2", value = "panel2", "Panel 2 content"),
                  tabPanel(title = "Panel 3", value = "panel3", "Panel 3 content")
      )
    )
  )
)

server <- function(input, output, session) {
  observeEvent(input$controller, {
     updateTabsetPanel(session, "inTabset", selected = paste0("panel", input$controller))
  })
}

shinyApp(ui, server)
```

**Comment by hadley** [comment]
Yeah, I think it's worth baking in though.

**Comment by hadley** [comment]
Thanks all!
