### ISSUE TITLE
when i use grid.arrange,i got this error no applicable method for 'plotly_build' applied to an object of class "c('gtable', 'gTree', 'grob', 'gDesc')"

### ISSUE THREAD

**Issue by cl886699** [rstudio/shiny#2681]
if i use subplot(p1,p2) replace grid.arrange(p1,p2), i will get the correct plot
library(ggplot2)
library(plotly)

ui <- fluidPage(
  column(width = 12,
         plotlyOutput("plot1", height = 350)
  )
)
server <- function(input, output) {
  output$plot1 <- renderPlotly({
    p1<-ggplot(data=data0plot,aes(x=x,y=value,colour=variable))+geom_line()
    p2<-ggplot(data=data1plot,aes(x=x,y=value,colour=variable))+geom_line()
    grid.arrange(p1,p2)
  })
}
shinyApp(ui, server)

**Comment by cpsievert** [comment]
Unfortunately plotly doesn't know how to convert the result of `grid.arrange()`, but `subplot()` provides essentially the same functionality https://plotly-r.com/arranging-views.html

**Comment by cl886699** [comment]
> Unfortunately plotly doesn't know how to convert the result of `grid.arrange()`, but `subplot()` provides essentially the same functionality https://plotly-r.com/arranging-views.html

thank you ,i used subplot,but it cant dell well with the legend .p is a list of ggplot,each of them has a legend ,when subplot(p),the legends may be overlapped
