### ISSUE TITLE
Broken web link for accessing the slides in the tutorial 

### ISSUE THREAD

**Issue by yuyu-aung** [rstudio/shiny#2684]
Link is broken here. 

https://shiny.rstudio.com/tutorial/

"The How to Start Shiny video series will take you from R programmer to Shiny developer. Watch the complete tutorial, or jump to a specific chapter by clicking a link below. The entire tutorial is two hours and 25 minutes long. Download the slides and exercises here: Part 1, Part 2, and Part 3.2

**Comment by mine-cetinkaya-rundel** [comment]
This is now fixed, thanks for reporting!

**Comment by max111** [comment]
Thanks! Appreciate quick response!
