### ISSUE TITLE
radioButtons cannot be reset

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#2688]
This seems like it should work--hitting the Reset button should clear the radios. But it doesn't work, there's a JS error.

```
library(shiny)

ui <- fluidPage(
  radioButtons("radio", "Radios", letters[1:5]),
  actionButton("reset", "Reset")
)

server <- function(input, output, session) {
  observeEvent(input$reset, {
    updateRadioButtons(session, "radio", selected = character(0))
  })
  observe({
    print(input$radio)
  })
}

shinyApp(ui, server)
```

**Comment by jcheng5** [comment]
This seems related too https://github.com/rstudio/shiny/issues/2266

**Comment by armenic** [comment]
Interestingly, if I keep changing the `inputID` of `radioButtons()` within `renderUI` then the returned value in `input` gets reset, but the issue comes back again after changing `inputID` 9 times. Then it consistently returns NULL, no issues. Not sure where this 9 number comes from.

**Comment by ColinFay** [comment]
Related: 

When updateSliderInput receives a `numeric(0)`, it sets the value of the slider to the `min` of the slider. I'm not sure if that's a desired behavior, and if not what would be the expected one 🤔

```r
ui <- fluidPage(
  sliderInput("slider", "slider", 1, 10, 4),
  actionButton("change", "Change")
)

server <- function(input, output, session) {
  
  
  observeEvent(input$change, {
    # This will make slider be equal to `min`
    updateSliderInput(session, "slider", value = numeric(0))
  })
  
  observeEvent( input$slider , {
    print(input$slider)
  })
  
  
}

shinyApp(ui, server)
```
