### ISSUE TITLE
my application run fine with native encoding but connot start when changing the encoding to UTF-8 

### ISSUE THREAD

**Issue by ahmedshingaly** [rstudio/shiny#2697]
I am using korean alphabets in ui.R and server.R both reopened with UTF-8. the application run fine one my local pc. 
```
> getOption("encoding")
[1] "native.enc"
```
but I cannot deploy because it shows errors so when I try to change the option encoding to UTF-8 using this command: 
`options(encoding = "UTF-8")`
I no more can run application on local pc: it shows this error message 
```
Warning in writeLines(text, ..., useBytes = TRUE) :
  invalid char string in output conversion
Warning in readLines(textConn, encoding = "UTF-8") :
  incomplete final line found on ''
```
any suggestions will be appreciated 

sincerely 
Ahmed

**Comment by cderv** [comment]
Hi, 

did you follow those recommandations already ? 
https://shiny.rstudio.com/articles/unicode.html
There is a strong advice against using the glocal option
> When dealing with encoding problems, you are not recommended to set the encoding option to a specific encoding name, e.g. options(encoding = 'UTF-8'). This may have very bad consequences, since it makes a strong assumption that all file connections and character manipulations should use this encoding by default.

Hope it helps

**Comment by ahmedshingaly** [comment]
Dear Christophe, 
I did follow the unicode article and your comments regarding the french parsing techniques however I am facing the same errors. 
I managed to deploy the app with korean alphabets last week 
 https://ahmedshingaly.shinyapps.io/AppKo/ 
but after adding some more lines, I no more can deploy, I dont know why its throwing the error that korean alphabets cannot be encoded with UTF-8 

thanks in advance
