### ISSUE TITLE
how to use Sys.time() condition in conditionalPanel?

### ISSUE THREAD

**Issue by jinholeetopology** [rstudio/shiny#2698]
I'm looking for a simple solution to the following problem (I don't think it's supposed to be very hard..)

I want to use time condition using Sys.time() to conditionalPanel.

For example:

```{r}
conditionalPanel(
  condition = "format(Sys.time(),'%H:%M') >= '18:30'",
  numericInput("num","Number", value = 1, step=1)
)
```
But, it's not working.

Is there any solution?

Thanks.
Lee

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
