### ISSUE TITLE
Shiny Image rendering image with messy text

### ISSUE THREAD

**Issue by RobertWan91** [rstudio/shiny#2699]
I have created a shiny dashboard. Basically it loads some cached images from CloudFront where the images were generated.

However, when the shiny dashboard is launched, I found that the image loaded sometimes turn into messy code. If I refresh the page, it can turn back to normal but it could turn the messy code again after a few click. 

<img width="973" alt="Screen Shot 2019-11-08 at 2 24 14 pm" src="https://user-images.githubusercontent.com/31884593/68447384-dd715080-0233-11ea-8e6f-99e1c3978630.png">
<img width="509" alt="Screen Shot 2019-11-08 at 2 25 33 pm" src="https://user-images.githubusercontent.com/31884593/68447391-e4985e80-0233-11ea-927a-2d42db234bad.png">

**Comment by wch** [comment]
Can you please provide a reproducible example?

**Comment by cpsievert** [comment]
Closing since no reproducible example was provided
