### ISSUE TITLE
icon() docs are confusing

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#2731]
> Icons are drawn from the Font Awesome Free (currently icons from the v5.3.1 set are supported with the v4 naming convention) and Glyphicons libraries. Note that the "fa-" and "glyphicon-" prefixes should not be used in icon names (i.e. the "fa-calendar" icon should be referred to as "calendar")

What does using v5.3.1 with the v4 naming convention mean?

**Comment by cpsievert** [comment]
Fixed via #3302
