### ISSUE TITLE
brushedPoints includes points not shown on plot

### ISSUE THREAD

**Issue by swebs** [rstudio/shiny#2735]
Points returned by `brushedPoints` can include some that are not shown on the plot, e.g., if they are excluded by `xlim` (which leaves some blank space at the edges of the plot where there could be "invisible points"). This could be counterintuitive, and might mean that the `clip` option in `brushOpts` is not working.

[Brief discussion on RStudio Community](https://community.rstudio.com/t/brushedpoints-includes-points-not-shown-in-plot/47985)

R 3.6.1
Shiny 1.4.0
RStudio 1.2.5019
Windows

Example code. To reproduce the problem, use the slider to change the `xlim` such that a point is just excluded, then brush displayed points and note the average. Finally, extend the brushed range outside the `xlim` range such that it covers one of the excluded points and note that the average value changes.

```
library(shiny)
library(tidyverse)

df <- mtcars

ui <- fluidPage(
  plotOutput('plot',brush=brushOpts(id="plot_brush",direction="x")),
  fluidRow(
    column(6,
           sliderInput("range", label="Range", min = 0, 
                       max = max(df$wt), value = c(0, max(df$wt)))
    ),
    column(6,
           tableOutput("brush_info")
    )  
  )
)

server <- function(input, output) {
  output$plot <- renderPlot({
    ggplot(df,aes(x=wt,y=mpg)) +
      geom_point() +
      xlim(input$range)
  })
  output$brush_info <- renderTable({
    brushedPoints(df,input$plot_brush) %>% summarize_at(vars(mpg),mean)
  })
}

shinyApp(ui = ui, server = server)

**Comment by cpsievert** [comment]
Is this still an issue? If it is would you mind including a screen recording the wrong behavior?

**Comment by swebs** [comment]
I just tested this again and it seems like it is fixed now!

My current versions:
R 4.0.2
Shiny 1.5.0
RStudio 1.3.1056
