### ISSUE TITLE
Unable to install Shiny package and CrossTalk through plotly?

### ISSUE THREAD

**Issue by mmdoka** [rstudio/shiny#2742]
* installing *source* package ‘shiny’ ...
** package ‘shiny’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Warning: replacing previous import by ‘Rcpp::evalCpp’ when loading ‘later’
Warning: S3 methods ‘format.staticPath’, ‘format.staticPathOptions’, ‘print.staticPath’, ‘print.staticPathOptions’ were declared in NAMESPACE but not found
Error in library.dynam(lib, package, package.lib) : 
  shared object ‘httpuv.so’ not found
ERROR: lazy loading failed for package ‘shiny’
* removing ‘/home/mmdoka/R/i686-pc-linux-gnu-library/3.2/shiny’
Warning in install.packages :
  installation of package ‘shiny’ had non-zero exit status
ERROR: dependency ‘shiny’ is not available for package ‘crosstalk’
* removing ‘/home/mmdoka/R/i686-pc-linux-gnu-library/3.2/crosstalk’
Warning in install.packages :
  installation of package ‘crosstalk’ had non-zero exit status
ERROR: dependency ‘crosstalk’ is not available for package ‘plotly’
* removing ‘/home/mmdoka/R/i686-pc-linux-gnu-library/3.2/plotly’
Warning in install.packages :
  installation of package ‘plotly’ had non-zero exit status

**Comment by wch** [comment]
It looks like you're using R 3.2. You may need to upgrade to a newer version for some of the dependencies to install correctly.
