### ISSUE TITLE
ActionButton/ActionLink

### ISSUE THREAD

**Issue by DJSUBHAOO7** [rstudio/shiny#2762]
Can anyone please tell me how to put a url into actionButton/Link, where the link will be collected from a table column. The link will be change by different other actions, with this the Link will bw open into a new tab of browser.
Please help me to do this

**Comment by schloerke** [comment]
The issue tracker is not for general questions. 

If you have a question, please feel free to ask it on our community site, at [https://community.rstudio.com/c/shiny](https://community.rstudio.com/c/shiny).

-------------------------

(untested)

```r
# in ui
uiOutput("link_ui")

# in server
link <- reactiveVal("http://google.com")
output$link_ui <- shiny::renderUI({
  shiny::tags$a(href=link(), target="_blank", "link title") 
})
```
