### ISSUE TITLE
remember state option for inputs

### ISSUE THREAD

**Issue by josephstatwick** [rstudio/shiny#2768]
When I create shiny apps, I frequently have inputs that show up in modals or conditional panels. They work just fine, except that if the user reopens the modal multiple times, the inputs "forget" the value that was chosen for them the previous time. Sometimes this is advantageous, but other times it's annoying. Can someone add an argument for the various input types that would allow them to "remember" the value of the previous time they were selected? Take this example where the user presses a button to select a species by which to filter the `iris` dataset. 

```
# server code
# deploy modal after UI input "selectspeciesbutton" is pushed
observeEvent(input$selectspeciesbutton, {
    showModal(
      modalDialog(
        title = "Pick a species",
        selectInput("species", 
                           "Select a species", 
                           c("Pick one..." = "", unique(iris$Species)),
        footer = tagList(
          modalButton("Cancel"),
          actionButton("speciesok","Ok")
        )
      )
    )
  })

  #Check data after ok button is pushed.
  observeEvent(input$speciesok, {
    if (isTruthy(input$species) {
        showNotification(type = "message", HTML("Species chosen correctly"))
        removeModal()
    } else {
        showNotification(type = "warning", HTML("No species chosen, try again"))
    }
  })

  irisfiltered <- reactive({
      filter(iris, Species == input$species)
  })
```
This is problematic because if the user presses the button a second time, the `selectInput` overwrites the user's previous choice, and forces a warning if the user just hits "Ok" a second time.

This could be fixed by adding the following argument to `selectInput`.
```
selected = if (isTruthy(input$species)) input$species else NULL
```
However, this gets pretty tedious when you have a lot of inputs. 

Ideally, there would be an argument called "remember" or "save.state" or whatever, that would look something like this
```
selectInput("species", 
                   "Select a species", 
                   c("Pick one..." = "", unique(iris$Species),
                   remember = TRUE)
```
This would pre-select the server-stored value for this input, if there is one. In the case where `remember = TRUE` and `selected` is not `NULL`, `selected` would be used if there is not a value for the input, but otherwise, the previously-chosen value would override the value of `selected`. In other words, something like:
```
if (remember) {
    selected <- if (isTruthy(input[[inputId]])) input[[inputId]] else selected
}
```

For backwards compatibility, `remember` should default to `FALSE`.

**Comment by cpsievert** [comment]
Closing as it doesn't seem that the cost of implementing and maintaining this feature is worth the benefit. Also, FWIW, it seems `reactiveVal()` could be useful here to remember truthy values:

```r
species <- reactiveVal()
observe({
  if (isTruthy(input$species)) species(input$species)
})

# Now use species() instead of input$species in your other reactive expressions
```

**Comment by jcheng5** [comment]
There are also shinyBS modals, which are created once and then shown/hidden multiple times, so they inherently retain their state. (I don't think I've used them personally, just read the docs)
