### ISSUE TITLE
class of reactive should include function

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#2787]
Because a reactive **is a** function 

``` r
library(shiny)
class(reactive(1))
#> [1] "reactiveExpr" "reactive"
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wch** [comment]
Just curious -- have you run into any problems in practice because of this?

**Comment by hadley** [comment]
No, this is just motivated by our current best understanding of S3 theory.

**Comment by daattali** [comment]
It's useful for teaching as well, I sometimes tell people that reactives really are functions under the hood, and this will reinforce that concept 👍
