### ISSUE TITLE
Conditional panels does not recognize my inputs: error: object "input" not found

### ISSUE THREAD

**Issue by KinSimon96** [rstudio/shiny#2801]
Hello,

I am implementing a web application for my lab, which consists of analysing genomic datasets. Using conditionalPanel is very helpful but i'm dealing with lot of issues with my inputs.
Here is a part of my ui.R code:

![ui](https://user-images.githubusercontent.com/57133275/77235813-6ec8da00-6bb9-11ea-9615-ab4ab07b4095.png)

and my server.R:

![R](https://user-images.githubusercontent.com/57133275/77235829-87d18b00-6bb9-11ea-92b0-ac25df34b6fa.png)

I always get the error:  object "input" not found, which refers to my input$count. When i use selectInput with many values and with multiple "if" in my renderPlot, it works, because i thus specify a real number in 
`subset(pbmc2, subset = nCount_RNA > 500 & nCount_RNA < REAL NUMBER)`
instead of input$count. But panel with 15 values is way less friendly than with a slider, that's why i am asking for your help!

Thanks.

**Comment by wch** [comment]
Can you provide a reproducible example as text? We can't copy and paste the code from these screenshots.

See this for more info about creating reproducible examples: https://community.rstudio.com/t/shiny-debugging-and-reprex-guide/10001

**Comment by KinSimon96** [comment]
Hello, 
thanks for replying.
Here is it, but with basic plot, it's working.... The reason why i made screens instead of text is because the "insert code" function is always a mess with me.

`  ui1 <- navbarPage(title ="xxxxxxx", theme = shinytheme("united"),
                 
                 
                 div(style="text-align:center"), 
                 
                 tabPanel("issue conditional panels",
                          
                          sidebarPanel(
                            
                            wellPanel(
                              radioButtons("MainMenu","Main Menu",
                                           list("Uploading dataset(s)"="Input",
                                                "Preprocessing"="Preprocess",
                                                "Clustering"="Cluster",
                                                "About"="About"))
                              
                            ),
                            conditionalPanel(condition="input.MainMenu=='Preprocess'",
                                             wellPanel(
                                               h5("Example"),
                                               selectInput("number","Choose a number",choices = c("1","2","3"))))
                          ),
                          
                          mainPanel(
                            
                            conditionalPanel(condition="input.MainMenu=='Preprocess'",
                                             tabsetPanel(
                                               tabPanel("plot",
                                                        plotOutput("try", height = 550))))
                          )
                          
                          
                 ))`

`server =  function(input, output, session){
  
 
  
  output$try <- renderPlot({
    plot(x = input$number, y = 2)
  })   
  }

shinyApp(ui=ui1, server = server)`


Can't do better to display it.... but at least this is a text.  Here I'm just not working with specific file from users, but the phylosophy is the same. The input$xxx in my conditional panel is not recognized when i am working with real datasets and specific genomic packages, and i can't understand why it's working with this reproductive example.

Best,
Simon

**Comment by stla** [comment]
I believe the problem is in the `subset` function. Try to replace with
`pbmc2 <- pbmc2[pbmc2$nCountRNA> 500 & pbmc2$nCountRNA < input$count, ]`

**Comment by KinSimon96** [comment]
This subset function is an official one from Seurat package, so i do not think the problem comes from it. I've tried your solution but it still didn't work. 

Do you think it's a reactive intput problem encountered when working with specific R packages? 
This is not the first time i'm making an app for a lab, and the only solution i had found was to work with If / Else if conditions, but here the optimisation thus becomes chaotic: for every input included in the code, i need to add dozens of identations, rerun all previous functions, and with genomic data, the laptop can fastly "burn" !

I've tried to put these inputs into a reactive function but the problem remains the same.

One delicious cookie pack for the one who will fix this ahah!

**Comment by wch** [comment]
From the debugging guide: either (A) remove bits of code from your app until the problem goes away, or (B) modify the basic app until it exhibits the same problem.

Note that the `subset` function is in the base package, and because it uses non-standard evaluation, it often causes problems in Shiny apps, especially if you're accessing things like `input$x`. The Seurat package has S3 methods defined for `subset`, but that doesn't change the issue of non-standard evaluation. You may need replace this line:

```R
pbmc2 <- subset(pbmc2, subset = nCountRNA> 500 & nCountRNA < input$count)
```

with something like

```R
count <- input$count
pbmc2 <- subset(pbmc2, subset = nCountRNA> 500 & nCountRNA < count)
```

**Comment by jcheng5** [comment]
There appears to be a bug in the seurat package that's causing this. I'll file an issue on their repo, but in the meantime this may work for you:

```r
pbmc2 <- eval(rlang::expr(subset(pbmc2, subset = nCountRNA> 500 & nCountRNA < !!input$count)))
```

**Comment by KinSimon96** [comment]
@wch , @jcheng5, for both of your solutions ,

I got this as error:
Warning: Error in FetchData: None of the requested variables were found: 
  [No stack trace available]

As you mentionned it, that's more of a Seurat package's bug. I guess I will have to work with If/else if as long as they don't fix this problem. 

Thank you really much for your help!

**Comment by mojaveazure** [comment]
Hi Simon,

This should be fixed in the latest development version of Seurat. We are working on prepping a release to CRAN with this fix so you can use it in your Shiny app

**Comment by KinSimon96** [comment]
Glad to hear it! Thank you for your hard work!
