### ISSUE TITLE
"Run App" button should honour the port specified in in `shinyApp()`

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#2803]
It's very handy to specify a port when developing and restarting your R session frequently for testing. The following code will always run the app on the given port if the code is run explicitly:

```
library(shiny)
ui <- fluidPage()
server <- function(input, output, session) {}
shinyApp(ui, server, options = list(port=5555))
```

But if I click on the "Run App" button (and by extension, the `runApp()` function) then the port is ignored and it will randomize a port every session. This makes testing less streamlined.

It looks like `runApp()` does know how to honour some other parameters of `shinyApp`, for example the `enableBookmarking` parameter.

**Comment by schloerke** [comment]
Confirmed.

RStudio calls run app on the file and the port is not set to `5555`.

```r
runApp('~/tmp/dean_runApp.R')
#> 
#> Listening on http://127.0.0.1:4789
```


Sourcing the file and printing it works as expected.
```r
print(
  source('~/tmp/dean_runApp.R')$value
)
#> 
#> Listening on http://127.0.0.1:5555
```

**Comment by cpsievert** [comment]
I think https://github.com/rstudio/shiny/pull/2969 closes (please re-open if not)
