### ISSUE TITLE
Many static resources 404 behind DigitalOcean's Load Balancer

### ISSUE THREAD

**Issue by prologic** [rstudio/shiny#2841]
The problem I'm having is actually related to probably some weird configuration or missing configuration, I'm not sure. I couldn't find anything int he docs.

I'm seeing a bunch of 404's on static resources for things like

This seems similar somewhat to this [StackOverflow thread](https://stackoverflow.com/questions/55582092/how-to-fix-404-not-found-errors-when-sourcing-css-and-javascript-files-in-sh) but the problem still persists.

The problem I'm seeing is that many of the static resources such as all of the font-awesome resources are 404'ing. These appear to use a different set of URL paths than the ones that start with `shared/...`. I don't understand where Shiny is expected to pick these up from?

See attached screenshots.

For reference this is the `Dockerfile` I use to build the image:

```
FROM r-base:3.5.0

# Install Ubuntu packages
RUN apt-get update && apt-get install -y \
    sudo \
    gdebi-core \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev/unstable \
    libxt-dev \
    libssl-dev

# Download and install ShinyServer (latest version)
RUN wget --no-verbose https://s3.amazonaws.com/rstudio-shiny-server-os-build/ubuntu-12.04/x86_64/VERSION -O "version.txt" && \
    VERSION=$(cat version.txt)  && \
    wget --no-verbose "https://s3.amazonaws.com/rstudio-shiny-server-os-build/ubuntu-12.04/x86_64/shiny-server-$VERSION-amd64.deb" -O ss-latest.deb && \
    gdebi -n ss-latest.deb && \
    rm -f version.txt ss-latest.deb

# Create shiny user
RUN adduser --system --disabled-password  --group --home /srv/shiny-server --shell /bin/sh shiny && \
    passwd --delete shiny

# Create shiny library directory
RUN mkdir -p /usr/local/lib/R && \
    chown -R shiny:shiny /usr/local/lib/R && \
    chmod 1755 /usr/local/lib/R

# Install R packages that are required
# TODO: add further package if you need!
RUN su - shiny /bin/sh -c 'R -e "install.packages(c('"'"'shiny'"'"', '"'"'shinydashboard'"'"'), repos='"'"'http://cran.rstudio.com/'"'"')"'
RUN su - shiny /bin/sh -c 'R -e "install.packages(c('"'"'shinyWidgets'"'"'), repos='"'"'http://cran.rstudio.com/'"'"')"'
RUN su - shiny /bin/sh -c 'R -e "install.packages(c('"'"'plotly'"'"'), repos='"'"'http://cran.rstudio.com/'"'"')"'
RUN su - shiny /bin/sh -c 'R -e "install.packages(c('"'"'lubridate'"'"'), repos='"'"'http://cran.rstudio.com/'"'"')"'
RUN su - shiny /bin/sh -c 'R -e "install.packages(c('"'"'DT'"'"'), repos='"'"'http://cran.rstudio.com/'"'"')"'
RUN su - shiny /bin/sh -c 'R -e "install.packages(c('"'"'shinyjs'"'"'), repos='"'"'http://cran.rstudio.com/'"'"')"'

RUN apt-get update && apt-get install -y \
    fonts-font-awesome

# Copy configuration files into the Docker image
COPY shiny-server.conf /etc/shiny-server/shiny-server.conf
COPY app /srv/shiny-server/app

# Copy startup script
COPY start.sh /start.sh

# Fix ownerships/permissions
RUN chown -R shiny:shiny /etc/shiny-server /srv/shiny-server /var/lib/shiny-server /var/log/shiny-server/ && \
    chmod 1777 /etc/shiny-server /srv/shiny-server /var/lib/shiny-server /var/log/shiny-server/ && \
    chown shiny:shiny /start.sh && \
    chmod 755 /start.sh

# Expose ShinyApp on TCP port 8000
EXPOSE 8000/tcp

# Change working directory and user
WORKDIR /srv/shiny-server
USER shiny

CMD ["/start.sh"]
```
<img width="752" alt="Screen Shot 2020-04-25 at 01 23 23" src="https://user-images.githubusercontent.com/1290234/80229310-96690180-8693-11ea-98ec-7599430bfbf1.png">
<img width="752" alt="Screen Shot 2020-04-25 at 01 23 29" src="https://user-images.githubusercontent.com/1290234/80229324-9b2db580-8693-11ea-97fe-e93a0593517e.png">

**Comment by wch** [comment]
It looks like you need to install the relevant R packages, like htmlwidgets, plotly, crosstalk, and so on.

Please note that this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.

**Comment by prologic** [comment]
> It looks like you need to install the relevant R packages, like htmlwidgets, plotly, crosstalk, and so on.
> 
> Please note that this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.

I guess you didn't notice:

```
RUN su - shiny /bin/sh -c 'R -e "install.packages(c('"'"'shinyWidgets'"'"'), repos='"'"'http://cran.rstudio.com/'"'"')"'
RUN su - shiny /bin/sh -c 'R -e "install.packages(c('"'"'plotly'"'"'), repos='"'"'http://cran.rstudio.com/'"'"')"'
```
?

**Comment by prologic** [comment]
Turns out trying to load balance across identical instances is what was causing the problem. I'm not sure why though :/

**Comment by jcheng5** [comment]
You’ll definitely need to enable sticky sessions in your load balancer. If not this problem, you’ll run into other problems with websocket emulation and selectize/DT calling back to the server for data.

**Comment by prologic** [comment]
You are right; _probably_ but enabling Sticky sessions seems too hard right now. So I'm just running a single instnace.

**Comment by mpereira-dev** [comment]
For me the 404s were a combination of the load balancer (AWS ALB) sticky session cookie and the content delivery network (AWS CloudFront CDN).

The load balancer adds a "set-cookie" header to the response so that the browser can send it in subsequent requests. However, the CDN caches that value and it can eventually become stale (or in conflict with another user's).

Also I discovered that Shiny can't serve up individual resources. ex: /myapp/shared/jquery.min.js until after the app is visited for the first time at the root context. ex: /myapp.

This is a problem because when the objects cached in the CDN expire it will request them again from the Shiny app. But if your Shiny R process has been cleaned up (ex 1: Shiny Server app_idle_timeout, ex2: a different instance of the app that hasn't been visited) then Shiny just returns an 404 for each of those assets.

I ended up storing all static assets in S3 and updating the routing in CloudFront for those assets to avoid the ALB. And disabled caching on all other requests. ex /myapp, /myapp/* /myapp/session* (even tho this is a POST request).

And that cleared up the issue.
