### ISSUE TITLE
Suggestion: Auto-loading R files in R/ subdirectory should be recursive

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#2850]
The new shiny feature of auto-loading R files in an `R/` subdir is great. 

Often in complex apps, placing all the R files in one directory is too messy and results in too many files, and a further division into subfolders is required. It's not at all uncommon to have over 50 R files, responsible for different modules, different components, different helpers, etc. I see it a lot. I would not advise anyone with over 10 files to use shiny's new auto loading feature because it only loads the top-level. I see a lot of added benefit if it were to support loading all R files under `R/` or its subdirs.

**Comment by daattali** [comment]
Actually, I don't even know if subdirectories are allowed in the R/ folder of a package on CRAN. If CRAN doesn't allow it, then that weakens my request.

**Comment by cpsievert** [comment]
I'm pretty sure we intentionally decided not to do recursive search for consistency with how R packages work
