### ISSUE TITLE
uiOutput does not work in nested shiny modules

### ISSUE THREAD

**Issue by colearendt** [rstudio/shiny#2862]
### System details

Browser Version: Chrome / Brave

Output of `sessionInfo()`:

```
devtools::session_info()
Failed to create bus connection: No such file or directory
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       Ubuntu 18.04.4 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language en_US:en                    
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Etc/UTC                     
 date     2020-05-03                  

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date       lib source                           
 assertthat    0.2.1      2019-03-21 [2] RSPM (R 3.6.3)                   
 backports     1.1.5      2019-10-02 [2] RSPM (R 3.6.1)                   
 callr         3.4.1.9000 2020-02-10 [1] Github (r-lib/callr@fe18b1b)     
 cli           2.0.1      2020-01-08 [2] RSPM (R 3.6.2)                   
 crayon        1.3.4      2017-09-16 [2] RSPM (R 3.6.2)                   
 desc          1.2.0      2018-05-01 [2] RSPM (R 3.6.1)                   
 devtools      2.2.1      2019-09-24 [2] RSPM (R 3.6.1)                   
 digest        0.6.23     2019-11-23 [2] RSPM (R 3.6.1)                   
 ellipsis      0.3.0      2019-09-20 [2] RSPM (R 3.6.3)                   
 evaluate      0.14       2019-05-28 [2] RSPM (R 3.6.1)                   
 fansi         0.4.1      2020-01-08 [2] RSPM (R 3.6.2)                   
 fastmap       1.0.1      2019-12-12 [1] Github (r-lib/fastmap@6d0fafb)   
 fs            1.4.1      2020-04-04 [1] RSPM (R 3.6.3)                   
 glue          1.4.0      2020-04-03 [1] RSPM (R 3.6.3)                   
 htmltools   * 0.4.0      2019-10-04 [2] RSPM (R 3.6.1)                   
 httpuv        1.5.2      2019-09-11 [2] RSPM (R 3.6.2)                   
 jsonlite      1.6.1      2020-02-02 [2] RSPM (R 3.6.2)                   
 knitr         1.27       2020-01-16 [2] RSPM (R 3.6.2)                   
 later         1.0.0.9002 2020-02-11 [1] Github (r-lib/later@077245d)     
 magrittr      1.5        2014-11-22 [2] RSPM (R 3.6.3)                   
 memoise       1.1.0      2017-04-21 [2] RSPM (R 3.6.1)                   
 mime          0.9        2020-02-04 [2] RSPM (R 3.6.2)                   
 packrat       0.5.0-25   2020-01-28 [1] Github (rstudio/packrat@448aafd) 
 pkgbuild      1.0.6      2019-10-09 [2] RSPM (R 3.6.1)                   
 pkgload       1.0.2      2018-10-29 [2] RSPM (R 3.6.1)                   
 prettyunits   1.1.1      2020-01-24 [2] RSPM (R 3.6.2)                   
 processx      3.4.1      2019-07-18 [2] RSPM (R 3.6.1)                   
 promises      1.1.0.9000 2020-02-11 [1] Github (rstudio/promises@627dfc6)
 ps            1.3.0      2018-12-21 [2] RSPM (R 3.6.1)                   
 R6            2.4.1      2019-11-12 [2] RSPM (R 3.6.3)                   
 Rcpp          1.0.3      2019-11-08 [2] RSPM (R 3.6.3)                   
 remotes       2.1.0.9000 2019-08-12 [1] Github (r-lib/remotes@a9bf4a2)   
 rlang         0.4.5      2020-03-09 [1] Github (r-lib/rlang@6592336)     
 rmarkdown     1.14       2019-07-12 [1] RSPM (R 3.6.1)                   
 rprojroot     1.3-2      2018-01-03 [2] RSPM (R 3.6.1)                   
 rsconnect     0.8.16     2019-12-13 [1] RSPM (R 3.6.2)                   
 rstudioapi    0.11       2020-02-07 [2] RSPM (R 3.6.2)                   
 sessioninfo   1.1.1      2018-11-05 [2] RSPM (R 3.6.1)                   
 shiny       * 1.4.0.2    2020-03-13 [1] RSPM (R 3.6.3)                   
 testthat      2.3.1      2019-12-01 [2] RSPM (R 3.6.1)                   
 usethis       1.5.1      2019-07-04 [2] RSPM (R 3.6.1)                   
 withr         2.1.2      2018-03-15 [2] RSPM (R 3.6.1)                   
 xfun          0.12       2020-01-13 [2] RSPM (R 3.6.2)                   
 xtable        1.8-4      2019-04-21 [2] RSPM (R 3.6.2)                   
 yaml          2.2.1      2020-02-01 [2] RSPM (R 3.6.2)                   

[1] /usr/home/cole/R/x86_64-pc-linux-gnu-library/3.6
[2] /opt/R/3.6.2/lib/R/library
```

### Example application *or* steps to reproduce the problem

```R

library(shiny)
library(htmltools)

mod3ui <- function(id) {
    ns <- NS(id)

    tagList(
        # should work?
        uiOutput(ns("hm")),
        htmltools::tags$b(ns("hm")),

        # actually works
        uiOutput("1-1-2-1-1-2-3-hm")
    )
}

mod3 <- function(input,output,session) {
    ns <- session$ns
    #browser()

    output$hm <- renderUI({
        #browser()
        tagList(
            tags$b("Three"),
            tags$br()
        )
    }
    )
}
mod2ui <- function(id) {
    ns <- NS(id)

    tagList(
        tags$b("Two"),
        tags$br(),
        mod3ui(ns("3"))
    )
}

mod2 <- function(input,output,session) {
    ns <- session$ns
    callModule(mod3, ns("3"))
}

mod1ui <- function(id) {
    ns <- NS(id)

    tagList(
        tags$b("One"),
        tags$br(),
        mod2ui(ns("2"))
    )
}

mod1 <- function(input,output,session) {
    ns <- session$ns
    callModule(mod2, ns("2"))
}

ui <- fluidPage(

    titlePanel("Old Faithful Geyser Data"),

    sidebarLayout(
        sidebarPanel(
        ),

        mainPanel(
            mod1ui("1")
        )
    )
)

server <- function(input, output) {
    callModule(mod1, "1")
}

shinyApp(ui = ui, server = server)
```

### Describe the problem in detail

Multiple levels of nested Shiny modules do not work with `uiOutput` and `renderUI`. Namespacing is treated differently on the UI and server side of the house. One repeating parent namespacing (`1-1-2-1-1-2-3` = `1` + `1-2` + `1-1-2-3`) the other only repeating the parents ids (`1-2-3`)

At the surface, this seems to require the child environment coding to the parent. Or perhaps I am missing a different type of namespacing function 😄

**Comment by daattali** [comment]
You shouldn't use `ns()` inside the server, when calling the callModule functions. For example, change `callModule(mod2, ns("2"))` to `callModule(mod2, "2")`

The title of this issue really freaked me out so I had to try to figure out how I never ran into such a terrible bug :)

**Comment by colearendt** [comment]
🙈 Wowzers. Good to know! That makes a lot of sense. Sorry about that!! 

That definitely solves it!! That was an interesting path for me to find myself in!

**Comment by earnaud** [comment]
Coming back on this point instead of opening a new issue:

In the case of multiple nested modules, it becomes uneasy to manage NS-ed ids for `render*()` function since they need to be NS-ed as UI parts. I fix this by sending a 'full.id' variable across my modules server which is basically the NS-ed version of the server id, see illustration below:

```
# Server definition
module <- function(id, full.id) {
    moduleServer(id, function(input, output, session) {
        output$text1 <- renderUI(
            textInput( NS(id, "server_text"), "Label") # doesn't work
        )

        output$text2 <- renderUI(
            textInput( NS(full.id, "server_text"), "Label") # works
        )
    })
}

# Other module server
otherModule <- function(id) {
    moduleServer(id, function(input, output, session){
        # Call to module
        module("myID", NS(id, "myID"))
    })
}
```

**Comment by daattali** [comment]
@earnaud perhaps if I saw a full example I would see why I'm wrong, but couldn't you use `module(NS(id, "myID"))` instead of `module("myID", NS(id, "myID"))` and that would make everything else work without having to jump through these hoops?

**Comment by earnaud** [comment]
My comment did not aim to point out why you would be wrong: I just wanted to talk about the way namespaces are managed in shiny servers (but I do not really know about any other places than this github page's issues).

The thing could be illustrated with successive levels of module servers called. I will detail namespace (interpreted by shiny while building the app) and provided id (accessible through arguments to the developper) for each level.

- On level 0 of my server, I call the module servers for each feature (assuming this is the only role of my app server, so no `observe*` nor `reactive*` at this level).

- On level 1 (= first modules to be called), I write observers for main features. In my case, I use a wizard which uses a different module on each one of its pages. So I call a module for each page. 
**Namespace:** "level1"
**Provided module id:** "level1"

- On level 2 (= module for each page of the wizard), I `renderUI` a form depending on any variable (e.g. columns of a table).
**Namespace:** "level1-pageX"
**Provided module id:** "pageX"

Here is what I wanted to point out: it would be simpler if providing an id to a module would be done the same way it is in UI. For "small apps" (with at most 2 levels of nested modules) this is not so important but for heavier apps, this would be useful. Something like the "asis" option would be really great in my opinion.

I will also work on a reprex but this might be quite specific need.

**Comment by earnaud** [comment]
Well, here is a reprex to test each cases possible: modules at level 2 with provided id "flat" (single character) or "NS-ed" (embedded in `NS`) and three `renderUI` tested with various ids.

```
library(shiny)

lower_UI <- function(id) {
  tagList(
    uiOutput(NS(id, "text1")),
    uiOutput(NS(id, "text2")),
    uiOutput(NS(id, "text3")),
    tags$hr(),
    tags$b("1: control"),
    textOutput(NS(id,"verbose1")),
    tags$b("2: with module id"),
    textOutput(NS(id,"verbose2")),
    tags$b("3: with module full namespace"),
    textOutput(NS(id,"verbose3"))
  )
}

lower <- function(id, full.id) {
  moduleServer(id, function(input, output, session) {
    output$text1 <- renderUI(textInput("text1", "Without NS"))
    output$text2 <- renderUI(textInput(NS(id,"text2"), "With local NS"))
    output$text3 <- renderUI(textInput(NS(full.id,"text3"), "With full NS"))
    
    output$verbose1 <- renderText(input$text1)
    output$verbose2 <- renderText(input$text2)
    output$verbose3 <- renderText(input$text3)
  })
}

upper_UI <- function(id) {
  tagList(
    actionButton(NS(id, "click"), "click"),
    tags$h3("1st module"),
    lower_UI(NS(id, "lower1")),
    tags$h3("2nd module -- with NS-ed id"),
    lower_UI(NS(id, "lower2"))
  )
}

upper <- function(id, full.id) {
  moduleServer(id, function(input, output, session) {
    observeEvent(input$click, message(input$click))
    lower("lower1", NS(id, "lower1"))
    lower(NS(id, "lower2"), NS(id, "lower2"))
  })
}

ui <- fluidPage(
  upper_UI("upper")
)

server <- function(input, output, session) {
  upper("upper", "upper") # NS(id, ...) can't be applied at top level
}

shinyApp(ui, server)
```

**Comment by earnaud** [comment]
What I wanted to underline was the need to use the `full.id` argument to use `renderUI` (no other case allows it). Maybe this is my way to use Shiny that is incorrect, also I would be really glad to let me know about this :)

**Comment by daattali** [comment]
RStudio Community is probably a good place for discussions rather than issues (I'll look at and respond to your comments if I find some time soon)

**Comment by daattali** [comment]
@earnaud Your example has a lot of code so it's hard for me to understand which part exactly is the one you think isn't working but should. Maybe the problem stems from the fact you're using `NS(id)` in the server. In the server you don't need to do that, you should use `session$ns()` (the server portion already knows its own id.

For example, here's a somewhat simplified version of one part of your app, this is how I would code it:

```
library(shiny)

lower_UI <- function(id) {
  tagList(
    uiOutput(NS(id, "text3")),
    textOutput(NS(id,"verbose3"))
  )
}

lower <- function(id) {
  moduleServer(id, function(input, output, session) {
    output$text3 <- renderUI(textInput(session$ns("text3"), "test", "test"))
    output$verbose3 <- renderText(input$text3)
  })
}

upper_UI <- function(id) {
  lower_UI(NS(id, "test"))
}

upper <- function(id) {
  moduleServer(id, function(input, output, session) {
    lower("test")
  })
}

ui <- fluidPage(
  upper_UI("upper")
)

server <- function(input, output, session) {
  upper("upper")
}

shinyApp(ui, server)
```

**Comment by earnaud** [comment]
Wow ! Thanks for this reminder @daattali ! I completely forgot about the role of `session` . Sorry for these dense useless comments :/ 
And many thanks again !

**Comment by inizi** [comment]
Greetings to all.

I am quite new to Shiny and in going through the basics examples at https://mastering-shiny.org/basic-ui.html I can't seem to get renderText() and renderPrint() to work.

The example in question is:

ui <- fluidPage(
  textOutput("text"),
  verbatimTextOutput("code")
)
server <- function(input, output, session) {
  output$text <- renderText({ 
    "Hello friend!"  
  })
  output$code <- renderPrint({ 
    summary(1:10) 
  })
}

Any suggestion of what I might not be doing?

Thank you.

zii
