### ISSUE TITLE
renderImage() should not defaulting deleting files

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#2869]
This is a dangerous operation so it should be deliberately opt-in.  

I just lost 15 minutes of work because of this 😬

**Comment by wch** [comment]
Maybe one way we can change the default for `renderImage` is to get people to explicitly set `deleteFile=TRUE` or `FALSE`. We could do this by printing a message if the user doesn't explicitly pass in a value. Then in a future version, we'll change the default.

**Comment by hadley** [comment]
I think the current behaviour is sufficiently dangerous that you'd need to make it an error (i.e. remove the default).

**Comment by stla** [comment]
Agreed. I helped several guys on Stackoverflow who were wondering why their image files were deleted.

**Comment by jcheng5** [comment]
So sorry about this. Fixed in https://github.com/rstudio/shiny/pull/2881
