### ISSUE TITLE
Update FontAwesome

### ISSUE THREAD

**Issue by bhogan-mitre** [rstudio/shiny#2890]
I recently tried to add an icon to my app and discovered that it was not in the built-in set from FontAwesome.  There are actually 500+ new free icons since the last version that is included here (5.3.1): https://fontawesome.com/icons?d=gallery&v=5.13.0,5.12.1,5.12.0,5.11.0,5.10.0,5.9.0,5.8.0,5.7.0,5.6.0,5.5.0,5.4.0&m=free

Could this get bumped to catch up with the latest (5.13.0)?  Among other things, this would include all the timely [new virus and hand-washing icons](https://blog.fontawesome.com/covid-19-awareness-icons/).

**Comment by wch** [comment]
Thanks for the idea!
