### ISSUE TITLE
Problem getting volumes() of users when deploying shiny App online (but works locally)

### ISSUE THREAD

**Issue by KinSimon96** [rstudio/shiny#2895]
Hello shiny team,

I've just deployed a shiny app online (https://data-exploration.shinyapps.io/scRNA-seq/) but I encounter problem to upload a folder when it is not in local. 

Here is the problem with screenshots.
![Annotation 2020-05-14 161549](https://user-images.githubusercontent.com/57133275/81945379-5516a280-95fe-11ea-821a-0f50121dca10.png)

The first screen is when it is running locally. All common folders are present and we just have to select the correct one for further analysis. 

![Annotation 2020-05-14 161614](https://user-images.githubusercontent.com/57133275/81945491-77a8bb80-95fe-11ea-8cbd-32e13940df35.png)

The second screen is when it is deployed online. Folders are unknown and I can not go through my C: to select a correct one. 

Do you know how to fix it ? Here is a part of server.R:

```
server2 =  function(input, output, session){

    volumes <- getVolumes()
    shinyDirChoose(input, 'dir11', roots = volumes, session = session)

    folderInput11 <- reactive({
        return(parseDirPath(volumes, input$dir11))
    })

        output$directory11 = renderPrint({  folderInput11()  })
} 
```

Thank you in advance!
Simon

**Comment by wch** [comment]
It is showing the files on the server. For security reasons, there's no way for Javascript in a web browser to read the contents of the user's hard drive. The reason you can get it to work when you run the app locally is because the client (web browser) and server are the same computer.

I think to do what you want, you'll have to use a regular `fileInput` with `multiple=TRUE`

**Comment by KinSimon96** [comment]
Thanks for the type! 
The problem is that the intern function of the package uses directly a folder containing 3 specific files, in order to load them for downstream analysis. Moreover, fileInput, even with multiple = TRUE, has a limit size for files to upload. In my case, genomic files can be up to 800 mb, I have then as error: 
`"Maximum upload size exceeded"`
What would you suggest then ? Giving the shiny code for every lab user, so that they can run the app locally and avoïd security/size problems, or another solution exists ?

Thank you!
Simon
