### ISSUE TITLE
testServer() and testModule() are missing

### ISSUE THREAD

**Issue by aftoncoombs** [rstudio/shiny#2901]
NEWS.md lists new features:

_testServer() and testModule() are two new functions for testing reactive behavior inside server functions and modules, respectively. (#2682, #2764)_

But, they are missing from the package. I installed the development version (remotes::install_github) but the functions are missing, and are not in the NAMESPACE file. I can only find the code for these functions in the specific pull requests #2682, #2764.

**Comment by pajupilli** [comment]
Thanks for the report. `testServer()` is in, and in the NAMESPACE file, but `testModule()` is gone and we should update the NEWS.md. Its functionality was subsumed by that of `testServer()`.

**Comment by alandipert** [comment]
Hi, thanks for the report. `testServer()` is in, and in `NAMESPACE`, but `testModule()` didn't ultimately make the cut. We should definitely update the NEWS.md.

**Comment by aftoncoombs** [comment]
Whoops -- you're right about testServer(). Thanks for the info!

**Comment by julianstanley** [comment]
Similarly, [this doc page](https://shiny.rstudio.com/articles/integration-testing.html) references testModule
