### ISSUE TITLE
Resizing Problem - Bug?

### ISSUE THREAD

**Issue by caiolif** [rstudio/shiny#2912]
Hi everyone!

I'm trying to develop an dashboard using the packages `shinydashboardPlus` but sometimes when I run or develop the app, I get problem with resizing plots, something like on the print below. 

The problem is solved when I unmaximized and soon after maximized the window browser, but this will be uncomfortable to the user. Another option is fix a width, but will be not flexible to other devices.

Somebody already has an problem like that? Looks like a bug.

![image](https://user-images.githubusercontent.com/31769064/83431789-e4e18c80-a405-11ea-94ed-efa2d7e0a015.png)

**Comment by wch** [comment]
Hi, I think this is probably an issue with the shinydashboardPlus package, so I suggest filing an issue there.
