### ISSUE TITLE
tabsetPanel() doesn't work with list of panels

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#2927]
It would be nice if `tabsetPanel()` could work more easily with a list of panels, so you can program with it without needing to know `do.call()`:

```R
panels <- list(
  tabPanel("Plot", "plot"),
  tabPanel("Summary", "summary"),
  tabPanel("Table", "table")
)

ui <- fluidPage(
  tabsetPanel(panels)
)
shinyApp(ui, function(...) {})

ui <- fluidPage(
  do.call(tabsetPanel, panels)
)
shinyApp(ui, function(...) {})
```

This is somewhat related to #1928 (in the sense that if you fix issue you should also fix this one)

I think you have two main options to fix:

* Automatically splice list inputs (like htmltools)
* Use `list2()` instead of list to get explicit `!!!` splicing

**Comment by cpsievert** [comment]
Seems like the first option would be tricky to get right, especially for nested list situations, so I'd be in favor of option 2 (especially given that `tabsetPanel()` might be superseded within the next year or so)
