### ISSUE TITLE
Inconsistency between RenderUI lapply and observe functions

### ISSUE THREAD

**Issue by u9090** [rstudio/shiny#2930]
Not sure if it's a bug, but just in case I post my request here (if it is my code that is not written properly, please close this issue).
 
In the example app below, I try to add a `actionButton` that resets a `checkboxGroupInput` across several tabs that have been generated dynamically. But the button does have any effect.

It seems that the `updateCheckboxGroupInput` does not function when inside `lapply`.
I also tried to create reactive values, dynamic observers (like [here](https://gist.github.com/mine-cetinkaya-rundel/0fe2a9830f7151e72053239e73350592)), etc, but still no effects.

```
library(shiny)

df <- data.frame(
  "Group" = c("Group A", "Group B", "Group A", "Group A", "Group B"),
  "Name" = c("Bob", "Paul", "Peter", "Emma", "John"),
  "Value" = seq(1,10, length.out=5),
  stringsAsFactors = F
)

# UI
ui <- fluidPage(
  mainPanel(
    uiOutput('mytabs')
  )
)

# SERVER
server <- function(input, output, session) {
  
  Tabs_titles = unique(df$Group)
  
  # Dynamic UI
  output$mytabs <- renderUI({
    myTabs <- lapply(Tabs_titles,
                     function(x){
                       tabPanel(title = x,
                                checkboxGroupInput(inputId = paste0("checkboxID_", x),
                                                   label = "My Checkbox",
                                                   choices = df %>% subset(Group == x) %>% pull(Name),
                                                   selected = df %>% subset(Group == x) %>% pull(Name)
                                ),
                                checkboxInput(paste0("clear_", x), "Clear"),
                                tableOutput(paste0("my_Table_", x))
                       )
                     }
    )
    
    do.call(tabsetPanel, myTabs)
    
  })
  
  
  observe(
    lapply(Tabs_titles,
           function(x){
             checked_names <- reactive({input[[paste0("checkboxID_", x)]]})
             
             # Table
             output[[paste0("my_Table_", x)]] <-renderTable({
               df %>%
               subset(Group == x & Name %in% checked_names())
             })
             
             # Clear button here
             req(input[[paste0("clear_", x)]])
             observeEvent(
               input[[paste0("clear_", x)]],
               {updateCheckboxGroupInput(
                  session = session,
                  inputId = paste0("checkboxID_", x),
                  choices = df %>% subset(Group == x) %>% pull(Name),
                  selected = if(input[[paste0("clear_", x)]] == TRUE) NULL
               )
               }
             )
           }
    )
  )
}


shinyApp(ui, server)
```

**Comment by cpsievert** [comment]
Are you trying to use `actionButton()` (as your comment suggests) or `checkboxInput()` (as your code suggests) to do the clearing? Closing since this doesn't appear to be a shiny issue, but if you haven't already, you might be able to get more immediate help with your code on https://community.rstudio.com/

**Comment by wch** [comment]
It's generally a bad idea to put an observer in an observer -- usually that means that there's something wrong with the design. If the outer `observe()` is calling `observeEvent()` and it re-executes, there will be multiple `observeEvent`s calling `updateCheckboxGroupInput()`.

**Comment by earnaud** [comment]
@wch What would be recommended to replace the nested `observe*` structures? I would need to generate observers according to a use of `renderUI()` and I also came up with this solution. I know this multiplies - widely ! - the number of observers but I couldn't figure out a better way.
