### ISSUE TITLE
img cann't show  picture

### ISSUE THREAD

**Issue by fjptwenger** [rstudio/shiny#2932]
my code:
```
library(shiny)
ui <- fluidPage(
    titlePanel("Hello Shiny!"),
    sidebarLayout( 
        sidebarPanel(),
        mainPanel(
            img(src = "shiny.png",height = '72px', width = '100px') 
        ) 
    )
)
server <- function(input, output){ 
}
shinyApp(ui = ui, server = server) 
```
my directory structure：
```
---shiny  #directory
    ---shiny.R  #code file
    ---www #directory
         ---shiny.png #picture
```
but why the picture cann't show：
![image](https://user-images.githubusercontent.com/25705121/85202058-61e19100-b336-11ea-8cd9-49263b355361.png)

and the body code of html is below，I am not sure what the correct **src img** format，so why can't display the picture ：
```

<body>
--
<div class="container-fluid">
 <h2>Hello Shiny!</h2>
<div class="row">
<div class="col-sm-4">
<form class="well"></form>
</div>
<div class="col-sm-8">
<img src="shiny.png" height="72" width="100"/>
 </div>
</div>
</div>
 </body>
```

**Comment by cpsievert** [comment]
Hmm, that should be working as long as the app is run with the right working directory. That is, did you run the app via `shiny::runApp("shiny")`? If you just evaluate that code with a different working directory than shiny won't know about that `www` dir.

**Comment by wch** [comment]
If your file is named shiny.R, the app shouldn't work at all if you do `runApp("shiny")`. How are you running your app? If you are simply calling `source()` on the file, then it won't be aware of the `www` directory.

**Comment by fjptwenger** [comment]
Sorry for replying so late，I  run shiny app from jupyter notebook，copy the code in cell and run，The code is shown above。so what is the right way to run？

**Comment by fjptwenger** [comment]
the code currently  run in jupyter can‘t show picture, but now I am running in jupyter
```
library(shiny)
runApp("shiny")
```
And modify shiny.R to app.R, the picture can be displayed.
