### ISSUE TITLE
Shiny's JS files causing encoding warnings on RStudio Server

### ISSUE THREAD

**Issue by drzamich** [rstudio/shiny#2933]
### System details
* SLES 15.1 / CentOS 8 (1911) / openSUSE 15.1 Leap (error occuring on all of those)
* RStudio Server 1.3.959
* Shiny 1.4.0.2
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 8 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] shiny_1.4.0.2

loaded via a namespace (and not attached):
 [1] compiler_3.6.3  fastmap_1.0.1   magrittr_1.5    R6_2.4.1       
 [5] promises_1.1.0  later_1.0.0     htmltools_0.4.0 tools_3.6.3    
 [9] Rcpp_1.0.4.6    jsonlite_1.6.1  digest_0.6.25   xtable_1.8-4   
[13] httpuv_1.5.2    mime_0.9        rlang_0.4.6 
```

### How to reproduce
1. Restart RStudio Server: 
```
sudo rstudio-server restart
```
2. Run the 8th shiny example
```
shiny::runExample("08_html")
```

### Describe the problem in detail

In my app I have [UI built with HTML](https://shiny.rstudio.com/articles/html-ui.html). When running the app for the **first time** after restarting RStudio Server I am getting encoding warnings in the console. 
```
Warning in force(expr) : input string '�' cannot be translated to UTF-8, is it valid in 'ANSI_X3.4-1968'?
Warning in force(expr) : input string '�' cannot be translated to UTF-8, is it valid in 'ANSI_X3.4-1968'?
```
While debugging the issue I noticed that warnings are not there when I comment out those two lines in the `index.html` file:
```html
  <script src="shared/jquery.js" type="text/javascript"></script>
  <script src="shared/shiny.js" type="text/javascript"></script>
```
this of course cannot be done because the app will not work properly but shows that the encoding issue is within those two files.

At the same time, the issue is not present on RStudio Desktop.

**Comment by drzamich** [comment]
While trying to fix the issue on my side I installed the experimental version of Shiny by running
```
remotes::install_github("rstudio/shiny")
```
and it fixed the issue. Apparently new version contains `.js` files without _weird_ characters.

Do we have an estimation when the new Shiny version will be released to CRAN so that the fix is official?

**Comment by wch** [comment]
I think the problem is not with the JS files themselves. It's that, when you comment out those lines, the Shiny code isn't loaded, and so much of the R code on the server side does not run.

I have seen this problem elsewhere: in that case the problem was that the package was built where `LANG=C` or `LANG=C.UTF-8`, but then the package was used in `en_US.UTF-8`. This is probably the cause of your problem. How are you installing your packages from CRAN?

At any rate, if you re-install 1.4.0.2 from CRAN, but with `install.packages("shiny", type="source")`, that would probably fix your problem.

**Comment by drzamich** [comment]
@wch you're right - I had problems in the R locales which I had to fix before installing Shiny's experimental version (otherwise installation wouldn't proceed) by creating `.Renviron` file in `/home/admin`:
```
LC_COLLATE  = "en_US.UTF-8"
LC_CTYPE    = "en_US.UTF-8"
LC_MONETARY = "en_US.UTF-8"
LC_NUMERIC  = "en_US.UTF-8"
LC_TIME     = "en_US.UTF-8"
```
Another mistake of me was the fact that I wasn't specifying the `type` parameter when installing packages. I would simply run `install.packages("shiny")` in the R console.
All in all it was - just as you said - an issue with locales on my side rather than a problem in package's code.
