### ISSUE TITLE
shiny won't install after R 4.0.0

### ISSUE THREAD

**Issue by Spudtopia** [rstudio/shiny#2942]
I just upgraded to R 4.0.2, and I can no longer install 'shiny'. I went back and tested previous versions, and everything after R 4.0.0 throws an error when installing shiny. When I try to install I get the following in the terminal...

```
'\\ad.network_location.ca\Empl\Home2\active\b\USER_NAME\My Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'shiny' ...
** package 'shiny' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices

...[All the html indices]....

*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
Error in as.list.environment(base::getNamespace("shiny"), all.names = TRUE) : 
  lazy-load database 'H:/My Documents/R/win-library/4.0/shiny/R/shiny.rdb' is corrupt
Calls: <Anonymous> ... withCallingHandlers -> <Anonymous> -> <Anonymous> -> as.list.environment
Execution halted
*** arch - x64
Error in as.list.environment(base::getNamespace("shiny"), all.names = TRUE) : 
  lazy-load database 'H:/My Documents/R/win-library/4.0/shiny/R/shiny.rdb' is corrupt
Calls: <Anonymous> ... withCallingHandlers -> <Anonymous> -> <Anonymous> -> as.list.environment
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'H:/My Documents/R/win-library/4.0/shiny'
Warning in install.packages :
  installation of package ‘shiny’ had non-zero exit status

```
I tried installing with R 3.6.3 and it ran fine, but I got a similar error when I tried to install in 4.0.0. No other packages have had any installation problems.

**Comment by jooyoungseo** [comment]
Hello,

Could you please double-check whether you have [Rtools40](https://cran.r-project.org/bin/windows/Rtools/) installed on your system?

**Comment by Spudtopia** [comment]
I do not. When I try to install it I get...
```
Warning in install.packages :
  package ‘Rtools40’ is not available (for R version 4.0.2)
```

**Comment by Spudtopia** [comment]
I do now.
However now when I start up I get the error message...
```
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
path[1]="//NETWORK_LOCATION/My Documents/R/win-library/4.0": Access is denied
```

**Comment by jooyoungseo** [comment]
Great! Do you have any other issues with `shiny` installation?

**Comment by Spudtopia** [comment]
I posted the same question on StackOverflow and got a workaround. This isn't a shiny issue, it's an R issue. Installing onto network drives with spaces in the file path sometimes throws errors depending on the package.

In case anyone has similar issues, copy the method here: [https://stackoverflow.com/a/59814948/3358272](url) Essentially you need to install to a temporary local folder with an acceptable file path, then relocate everything to the network drive. It's clunky but works.
