### ISSUE TITLE
Documentation for observers methods & best practices for performance

### ISSUE THREAD

**Issue by earnaud** [rstudio/shiny#2952]
Hello Shiny team,

I am experimenting some advanced Shiny features as I am building a "large app". At a moment, I am asking the user to pass from form to form on ~10 pages. To avoid generating too many observers, I would like to create observers into a list-like objects (list, reactiveValues, environment, ...). Upon arriving on a page already visited (= observers already created), I would look for reactivating the observers and on leaving a page, I would like to make them not react.

By looking into `observeEvent()` methods, I saw this class has many methods, but I can't find any documentation to use them efficiently (for example, what are the differences between `run()` and `resume()` ?). In cases like mine, it could be really helpful to have help for the main function of the observers.

Another question concerning high numbers of observers would be: what are the recommendations and best practices for application with such a number of observers simultaneously activated/existing (say ~200 observers as I saw on reactlog)? Is this number even high? 

I hope my english syntax is at least a little comprehensible. Please do not hesitate to tell me if I was unclear.

**Comment by hadley** [comment]
I don't think you should worry about this, unless you have specifically found a performance issue in your app — Shiny already takes take of only firing the observers when needed. For a multi-"page" app, you might also consider the approach in https://mastering-shiny.org/action-dynamic.html#dynamic-wizard

**Comment by earnaud** [comment]
Well, I made my app more dynamic than that with a side module for navigation changing the value of a "currrent.page" reactiveValues. Pages are rendered with a renderUI each time page change, but rendering it causes observers to be generated again each time. 

I will try to make it easier ;)
