### ISSUE TITLE
InputBinding.getId tries to read element's property 'data-input-id', instead of attribute

### ISSUE THREAD

**Issue by sigmapi** [rstudio/shiny#2955]
Currently Javascript `Shiny.InputBinding` class in order to resolve an element's input id, tries first to read the property `data-input-id` and then falls back to element's id.
```
this.getId = function(el) {
  return el['data-input-id'] || el.id;
};
```

However this is incorrect, this property will never exist (unless you define it manually from within Javascript).
It should instead read an attribute with same name:
```
this.getId = function(el) {
  return el.getAttribute('data-input-id') || el.id;
};
```

And this is what the docs really say under `getId`: 
https://shiny.rstudio.com/articles/building-inputs.html

If we define an input element and define an attribute `data-input-id`, that will be totally ignored, with the current implementation.

**Comment by jcheng5** [comment]
🤦‍♂️  Thank you!
