### ISSUE TITLE
missing testModule() in shiny that is used in docs

### ISSUE THREAD

**Issue by nbbn** [rstudio/shiny#2960]
Hi,
My problem is more about documentation, because when you will install shiny from GitHub according to [article](https://shiny.rstudio.com/articles/integration-testing.html), you will not have `testModule()` that is mentioned in this article. Are there any plans to implement/include it into shiny?

My suggestion is to update the article or add this function to shiny :)
Best,
Jakub

**Comment by hadley** [comment]
That article is out of date; you can now just use `testServer()`. There's an example and some very rough notes at https://mastering-shiny.org/scaling-testing.html#modules
