### ISSUE TITLE
sliderInput can not be achieved if both fluidPage and fluidRaw both exist.

### ISSUE THREAD

**Issue by LuffyLuffy** [rstudio/shiny#2963]
![image](https://user-images.githubusercontent.com/15357865/86682544-444d4080-c033-11ea-9c16-665d04fc5c40.png)

ui <- fluidPage(
  titlePanel("censusVis"),
  
  sidebarLayout(
    sidebarPanel(
      helpText("Create demographic maps with 
               information from the 2010 US Census."),
      
      selectInput("var", 
                  label = "Choose a variable to display",
                  choices = c("Percent White", 
                              "Percent Black",
                              "Percent Hispanic", 
                              "Percent Asian"),
                  selected = "Percent White"),
      
      sliderInput("range", 
                  label = "Range of interest:",
                  min = 0, max = 100, value =100)
    ),
    
    mainPanel(
      textOutput("selected_var"),
      textOutput("range_var")
    )
  ),
  fluidRow(
    column(3,
           br(),
           submitButton("Submit"))
  )
  
)

server <- function(input, output) {
  
  output$selected_var <- renderText({ 
    paste("You have selected", input$var)
   
  })
  output$range_var<-renderText({
    paste("You have chosen a range that goes from",input$range[1]," to ",input$range[2])
  })
  
}

# Run the app ----
shinyApp(ui = ui, server = server)

**Comment by LuffyLuffy** [comment]
It seems the problem of submit. If I click submit, then the value will update as the scroll value.

**Comment by wch** [comment]
Yes, the `submitButton` will prevent any input values from being sent to the server until the button is clicked. In general, you should use `actionButton` instead. Please see this article:
https://shiny.rstudio.com/articles/action-buttons.html#how-are-submit-buttons-and-action-buttons-different

**Comment by LuffyLuffy** [comment]
> Yes, the `submitButton` will prevent any input values from being sent to the server until the button is clicked. In general, you should use `actionButton` instead. Please see this article:
> https://shiny.rstudio.com/articles/action-buttons.html#how-are-submit-buttons-and-action-buttons-different

Thanks! It is interesting to use Shiny to create app!
