### ISSUE TITLE
shiny server library load error

### ISSUE THREAD

**Issue by lakeparkXPA** [rstudio/shiny#2976]
Hi, I was trying to deploy an application in my server using shiny server open source.

But, if I try to use it error pops up in the log and doesn't work. 

processing file: index.Rmd
Quitting from lines 8-1102 (index.Rmd)
Warning: Error in library: there is no package called 'shinydashboardPlus'
  140: <Anonymous>

I can't show all of the code but show you the fragment of it is down below.

`---
title: "Untitled"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}

#### Library ####
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
...
ui <- dashboardPagePlus(
  skin = 'black',
  header,
  sidebar,
  body
)
server <- function(input, output, session){...}
`

`
```{r eruptions, echo=FALSE}
shinyApp(ui = ui, server = server)
```
`

All of the package is installed in the server.

Thank you.

**Comment by wch** [comment]
You need to make sure that the shinydashboardPlus package is installed on your server, and can be loaded by the shiny user.

Please note that this issue tracker is meant for bug reports and feature requests for the Shiny package. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
