### ISSUE TITLE
addResourcePath should allow resources that starts with a dot

### ISSUE THREAD

**Issue by ColinFay** [rstudio/shiny#2980]
It's pretty common to have on a website a folder called `/.well-known`, notably for adding a `security.txt`: https://securitytxt.org/

It would be doable by doing `addResourcePath(".well-known", "inst/.well-known")`, but `addResourcePath()` regex for prefix name excludes prefixes that starts with dot. 

https://github.com/rstudio/shiny/blob/6ad2125ee74a0a6cab723fefc25449c50a4568fa/R/server.R#L74

Could this regex be turned to `"^[a-z0-9\\-_\\.][a-z0-9\\-_\\.]*$"` instead?

Happy to make a PR in that sense. 

Cheers

**Comment by ColinFay** [comment]
Ah, I hadn't think about the use of dot only. 

I've pushed a new test to check if the prefix is made only of dots (that would also cacth `".."`).

``` r
fn <- function(prefix) {
  if (grepl("^\\.+$", prefix)) stop("prefix can't be composed of dots only") else "ok"
}

fn(".")
#> Error in fn("."): prefix can't be composed of dots only
fn("..")
#> Error in fn(".."): prefix can't be composed of dots only
fn(".well-known")
#> [1] "ok"
```

<sup>Created on 2020-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wch** [comment]
Thanks!
