### ISSUE TITLE
Suggestion: Super tiny icons

### ISSUE THREAD

**Issue by stla** [rstudio/shiny#2997]
Hello,

 The [super tiny icons](https://github.com/edent/SuperTinyIcons) are really cool. I just wanted to suggest to incorporate them in Shiny.

**Comment by cpsievert** [comment]
Thanks for the suggestion, although, I don't think it makes sense for shiny itself to ship with numerous sets of icons. This would be a great contribution to a package like https://github.com/ropenscilabs/icon though
