### ISSUE TITLE
Add html support to input controllers (selectInput, checkboxInput) etc

### ISSUE THREAD

**Issue by johnpauls** [rstudio/shiny#300]
I would like to request the ability to add HTML code to customize all of the input controllers. For example,  I have a selectInput() control that lets the user pick the color of the points to be displayed on a plot in the main window. Each selection is a color name. It would be nice to be able to add code to make the name appear in the color it represents(i.e. "blue" would be blue and "red" would be red).  Similarly it would be great if you could add html to change the appearance of each individual controller on the ui. 

Thanks

**Comment by alandipert** [comment]
`HTML()` [can now be used](https://stackoverflow.com/a/22033435) with `selectInput`. I just checked, and I was also able to use `HTML()` together with `checkboxInput()`:

```R
checkboxInput("crazy", HTML("Are you <strong>crazy</strong>?"))
```

I'm don't know which inputs don't yet cooperate with `HTML()` (if any), but I think it makes sense to close this and then anyone who runs across a misbehaved input can open a new, more specific issue.
