### ISSUE TITLE
Source does not work anymore in server.R since shiny 1.5

### ISSUE THREAD

**Issue by PhilippPro** [rstudio/shiny#3029]
Thanks for creating shiny. You do a great job guys. 

Since updating to plotly 1.5 sourcing of external code via source does not work anymore. 
Minimal Example:

ui.R:
```R
library(shiny)
ui <- pageWithSidebar(
  headerPanel("Example"),
  sidebarPanel(),
  mainPanel(selectInput("abc", "Dum", c("A", "B")),
            uiOutput("test_me"),
            uiOutput("test_me_too"))
)
```

server.R:
```R
server <- function(input, output) {
  output$test_me <- renderUI({selectInput("BeispielUI", "Dum", c("2", "3"))})
  source("./R/helper.R", local = TRUE)
}
```
In the folder R in the file helper.R:
```R
output$test_me_too <- renderUI({selectInput("sourceBeispielUI", "Dum", c("Ich", "Du"))})
```

Error:
```R
Error in output$test_me_too <- renderUI({ : 
  object 'output' not found
```
Seems like "output" (and "input") cannot be found in the file.

In shiny 1.4 this works, in shiny 1.5 it doesn't. I could also write it in modules, but this would make things more complicated and more code would be necessary? Is there another solution?

**Comment by ColinFay** [comment]
Hey, 

Using `{shiny}` version 1.5.0 here, I tried to reproduce your issue but your example works. 

Can you share your `sessionInfo()` please?

**Comment by PhilippPro** [comment]
```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.5.0

loaded via a namespace (and not attached):
 [1] compiler_4.0.2  fastmap_1.0.1   magrittr_1.5    R6_2.4.1        promises_1.1.1 
 [6] later_1.1.0.1   htmltools_0.5.0 tools_4.0.2     withr_2.2.0     Rcpp_1.0.5     
[11] jsonlite_1.7.0  digest_0.6.25   xtable_1.8-4    httpuv_1.5.4    mime_0.9       
[16] rlang_0.4.7  
```

**Comment by PhilippPro** [comment]
This also happened on a shiny server.

**Comment by wch** [comment]
I think the problem is probably due to a change in Shiny 1.5.0, where the R/ directory is sourced automatically when the application starts. This means that the assignment to `output$test_me_too` is happening outside of the server function.

There is an option to disable this behavior, but the best long-term solution is to just rename the R/ directory to something else.

**Comment by PhilippPro** [comment]
Thanks a lot, this solved my problem.

**Comment by philibe** [comment]
>I think the problem is probably due to a change in Shiny 1.5.0, where the R/ directory is sourced automatically when the application starts. 

>but the best long-term solution is to just rename the R/ directory to something else.

Thanks  :) (work with shiny 1.5 and 1.6)
