### ISSUE TITLE
eventReactive ignoreInit clarification in docs and/or possible ignoreInit bug

### ISSUE THREAD

**Issue by mmuurr** [rstudio/shiny#3031]
The documentation for `ignoreNULL` and `ignoreInit` within `observeEvent()` is quite clear. Likewise, the docs for `ignoreNULL` within `eventReactive()` is also clear. But, I believe the description of `ignoreInit` within `eventReactive()` is either misleading **or** the current behavior of `ignoreInit` is off somehow. Here's a simple Shiny app demonstrating my confusion or a possible bug (take note of the `ignoreInit` values for `re1` and `re2`):
```R
library(tidyverse)
library(shiny)

rv <- reactiveVal(lubridate::origin)

f1 <- function() {
  print("in f1")
  print(sprintf("current rv() = %s", isolate(rv())))
  rv(lubridate::now())
  print(sprintf("new rv() = %s", isolate(rv())))
  re1()
  re2()
}

re1 <- eventReactive(rv(), {
  print("in re1")
}, ignoreNULL = TRUE, ignoreInit = TRUE)

re2 <- eventReactive(rv(), {
  print("in re2")
}, ignoreNULL = TRUE, ignoreInit = FALSE)

ui <- fluidPage(actionButton("action_button_1", label = "click me"))

server <- function(input, output, session) {
  observeEvent(input[["action_button_1"]], {
    f1()
  })
}

shinyApp(ui, server)
```
When the app starts, `rv` is created (and is set immediately to a non-`NULL` value), as are two `eventReactive()`s, `re1` and `re2`, both of which take in their `eventExpr` a reactive dependency on `rv`. Both are also set to `ignoreNULL`, but this should not come into play here since `rv` will never be set to `NULL`.

In my interpretation of the documentation, `re1` and `re2` are both now "created", and my (apparently) naïve assumption is that they've both been "initialized", too. The documentation line for `observeEvent/eventReactive` is:

> By default, both of these will run right when they are created (except if, at that moment, eventExpr evaluates to NULL and ignoreNULL is TRUE).

"both of these", according to the docs, implies `observeEvent()` and `eventReactive()`.

When clicking the app's action button the first time, here's the (console) output:
```
 [1] "in f1"
 [1] "current rv() = 1970-01-01"
 [1] "new rv() = 2020-08-31 19:31:54"
```
 `f1()` runs, which sets `rv` and should thus invalidate both `re1` and `re2`. `f1()` then explicitly calls both `re1()` and `re2()`, however neither run. The `eventExpr` evaluates to non-`NULL` (since it's just been set to the current time), and so my only guess is that the `ignoreInit` argument is blocking both from running.

When clicking the app's action button the second time, we finally get some `re1` and `re2` action:
```
 [1] "in f1"
 [1] "current rv() = 2020-08-31 19:31:54"
 [1] "new rv() = 2020-08-31 19:31:57"
 [1] "in re1"
 [1] "in re2"
```

This confuses me, for two reasons.

The first reason is that the documentation isn't very clear about what "initialized" means in the context of a `eventReactive()`. Does `ignoreInit = TRUE` really just block the first _execution_ attempt of the reactive function? Is that first attempted execution count as the "initialization"? That feels different than `observeEvent()`, which, being a reactive _endpoint_, can logically be blocked on the app initialization procedure (i.e. the documentation and behavior make perfect sense for `observeEvent()`).

The second reason I'm confused is when `ignoreInit = FALSE`, `re2()` _still_ doesn't run on the first button-click, despite being created with `ignoreInit = FALSE`. So even if the first attempted execution of an `eventReactive()` counts as the "initialization", then `re2()` should run on that first button-click, since the `eventExpr` evaluates to non-`NULL` both during app startup (where `rv` is initialized to `lubridate::origin`) and after the button-click.

The behavior I first expected was that _both_ `rv1()` and `rv2()` would run on the first button-click. Then, after updating by beliefs and guessing a bit at what "initialization" means for an `eventReactive()`, I expected that `rv2()` would run on the first button-click. But neither reactive functions run, and that is surprising behavior to me (and perhaps some other Shiny users out there?).

BTW, this is using Shiny v1.5.0.

**Comment by ismirsehregal** [comment]
If you switch the order of `re1()` and `re2()` in `f1()` you will see `re2` beeing executed after the first button click. `re1()` gives a silent error on it's first execution - which I guess indicates, that `eventReactives` are initialized when they are first triggered.

**Comment by mmuurr** [comment]
@ismirsehregal yup, that makes sense now, I was just failing to catch that silent error condition. (I kind of dislike those silent errors and wish that minimally they're log to the console.) Nevertheless, perhaps this issue should then simply be to add the clarification in the docs that:
* `observeEvent` "initialization" is when the observer is _created_, while
* `eventReactive` "initialization" is the first attempted _execution_ of the reactive function.

Those are sufficiently different that I think making that explicit in the docs would be helpful.
