### ISSUE TITLE
Shiny apps not rendering with Nginx after update to Ubuntu 20.04.1 LTS (on Azure VM)

### ISSUE THREAD

**Issue by onemoregile** [rstudio/shiny#3041]
### System details

Browser Version:

Microsoft Edge Version 81.0.416.64 (Official build) (64-bit)

Output of `sessionInfo()`:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.2
```

### Example application *or* steps to reproduce the problem

 

```R
shiny::runExample("01_hello", host = '0.0.0.0', port = 3800)
```

### Describe the problem in detail

I am running a Shiny (version ‘1.5.0’) app via the following command in R:

```R
shiny::runExample("01_hello", host = '0.0.0.0', port = 3800)
```

If I navigate to localhost:3800 everything works fine.

If I use a proxy (nginx version: 1.19.2), the Shiny app is not rendered properly.

I have followed the instructions on how to configure Nginx from #2372 

This is the error from the browser:

GET http://[DNS-NAME-DELETED]/shared/json2-min.js net::ERR_ABORTED 404 (Not Found) hello:8
GET http://[DNS-NAME-DELETED]/shared/jquery.min.js net::ERR_ABORTED 404 (Not Found) hello:9
GET http://[DNS-NAME-DELETED]/shared/shiny.css net::ERR_ABORTED 404 (Not Found) hello:10
Etc...

These are the relevant blocks in the Nginx config files that I have used:

```
http {
[...]
    map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
    }
[...]
}

server {
[...]
        location /hello {
             proxy_pass http://localhost:3800/;
             proxy_read_timeout 200s;
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection $connection_upgrade;
             proxy_buffering off;
        }

[...]
}
```

**Comment by jcheng5** [comment]
Try adding a slash to the end of `/hello`?

**Comment by onemoregile** [comment]
It worked! May I ask why this works? =)

Curiously enough, the no slash at the end of /hello setting worked before the upgrade to Ubuntu 20.04.1 LTS.
