### ISSUE TITLE
`Uncaught TypeError: e.replace is not a function` in `updateRadioButtons(session, "radio", selected = letters[1:5])`

### ISSUE THREAD

**Issue by ColinFay** [rstudio/shiny#3065]
When running `updateRadioButtons(session, "radio", selected = letters[1:5])`, the browser fails with the following error: 

```r
shiny.min.js:3 Uncaught TypeError: e.replace is not a function
    at exports.$escape (shiny.min.js:3)
    at exports.InputBinding.setValue (shiny.min.js:3)
    at exports.InputBinding.receiveMessage (shiny.min.js:3)
    at ShinyApp.<anonymous> (shiny.min.js:3)
    at ShinyApp._sendMessagesToHandlers (shiny.min.js:3)
    at ShinyApp.dispatchMessage (shiny.min.js:3)
    at WebSocket.n.onmessage (shiny.min.js:3)
```

Reprex: 

```r
library(shiny)
ui <- fluidPage(
  radioButtons("radio", "Radios", letters, selected = letters[10]),
  actionButton("changes", "Changes")
)

server <- function(
  input, 
  output, 
  session
){
  observeEvent(input$changes, {
    updateRadioButtons(session, "radio", selected = letters[2:3])
  })
}

shinyApp(ui, server)
```

Related: 

- discussion here : https://github.com/rstudio/shiny/pull/3043#discussion_r486628704
- issue #2688 

This should be solved when #3064 is fixed, but I think there might be some other corner cases where this happens ?

**Comment by ColinFay** [comment]
As far as I can tell, the issue originates in 

```javascript
var $escape = exports.$escape = function(val) {
  return val.replace(/([!"#$%&'()*+,.\/:;<=>?@\[\\\]^`{|}~])/g, '\\$1');
};
```

receiving an array, and `[].replace` doesn't exist.

I think it could be solved via: 

```javascript
var $escape = exports.$escape = function(val) {
  if ($.isArray(val)){
    return val.map(e => e.replace(/([!"#$%&'()*+,.\/:;<=>?@\[\\\]^`{|}~])/g, '\\$1'));
  } 
  return val.replace(/([!"#$%&'()*+,.\/:;<=>?@\[\\\]^`{|}~])/g, '\\$1');
};
```

But then it needs to be handled in the `setValue` method of radiobutton.

**Comment by wch** [comment]
I'm not sure I understand why this is a problem. If the app author writes code where the server sends bad data to the client, the client throws an error. That seems like correct behavior to me.

**Comment by ColinFay** [comment]
Ok then :) 

That felt weird as from the user point of view, the app doesn't change even if the button is clicked. 
But that might be an issue to solve only from the server side indeed.
