### ISSUE TITLE
fileInput() doesn't upload a file when the UI contains multiple tabPanel() in navbarMenu()

### ISSUE THREAD

**Issue by latlio** [rstudio/shiny#3071]
When I run the shinyApp, the fileInput UI is still functional, as in clicking the "Browse" button still opens up my directory. However, when I select a file, the file then fails to upload. This issue is resolved by removing a tabPanel such that there is only one within navbarMenu(). However, I would like to know how to resolve this issue without having to remove any tabPanels.

### System details
Output of `sessionInfo()`:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6
```

### Reprex
```R
library(shiny)

ui <- fluidPage(
  shinyUI(
    navbarPage("reprex",
               tabPanel("upload file",
                        fluidRow(
                                 fileInput("file", "Choose a CSV file",
                                           multiple = FALSE,
                                           accept = c('text/csv',
                                                      'text/comma-separated-values,text/plain',
                                                      '.csv'))
                        ) #close fluidrow
                        ), #close tab panel
               navbarMenu("additional",
                          tabPanel("tab1"),
                          tabPanel("tab2")
    ) #close navbarpage
  ) #close shinyUI
) #close fluidpage

server <- function(input, output) {}

shinyApp(ui, server)
```

**Comment by ColinFay** [comment]
Hey @latlio, 

I don't have any issue uploading a file using the code you've provided. 

Does the following code prints elements to your console when uploading a csv? 

```r
library(shiny)

ui <- fluidPage(
  shinyUI(
    navbarPage(
      "reprex",
      tabPanel(
        "upload file",
        fluidRow(
          fileInput(
            "file", 
            "Choose a CSV file",
            multiple = FALSE,
            accept = c(
              'text/csv',
              'text/comma-separated-values,text/plain',
              '.csv'
            )
          )
        ) 
      ),
      navbarMenu(
        "additional",
        tabPanel("tab1"),
        tabPanel("tab2")
      ) 
    ) 
  ) 
)
server <- function(input, output) {
  observe({
    print(input$file)
  })
}

shinyApp(ui, server)
```

**Comment by latlio** [comment]
It does print elements! So your code works; however I may have to think a little bit more on creating another reprex that better represents the larger code I have because for some reason fileInput still doesn't work in my original code.

**Comment by ColinFay** [comment]
Any chance you have a duplicated id in your code?

**Comment by latlio** [comment]
I suspected that, but I don't think I have a duplicated id to the best of my knowledge

**Comment by latlio** [comment]
This is not necessarily a reprex, but I noticed that in my navbarMenu, if I do the following:

```R
navbarMenu(
        "additional",
        tabPanel("tab1",
source("file1")$value),
        tabPanel("tab2",
source("file2")$value))
```

then fileInput doesn't work. However, when I remove one of the sources, it works again. Does that suggest to you that there's a duplicate ID issue?

**Comment by latlio** [comment]
I found the issue, it was a typo, so it did end up being a duplicated ID!
