### ISSUE TITLE
Remove the support for IE8/9 in fileInput()?

### ISSUE THREAD

**Issue by yihui** [rstudio/shiny#3074]
The support for IE8/9 in `fileInput()` was added in **shiny** 0.10.2 (PR #598). I wonder if it could be removed now since we no longer support IE8/9. I'm asking because I added a rather complex function `parse_multipart` to the **mime** package at that time to support this feature, and I'm thinking of removing it now. I guess **shiny** is the only package that actually uses this function. Thanks!

**Comment by wch** [comment]
I'm fine with that. Is there any pressing reason to remove `parse_multipart` from mime?

**Comment by yihui** [comment]
No pressing reason. I just want to keep the **mime** package lightweight and easy to maintain. Please take your time. No hurry at all. Getting rid of the special IE8 file uploader in the JS code in **shiny** may also make **shiny** slightly easier to maintain, too :)

**Comment by wch** [comment]
I think we'd have to remove support in Shiny first, and then after it's released, you'd be able to remove `parse_multipart` from mime.

**Comment by jcheng5** [comment]
I think we can also get rid of "allowDataUriScheme" too (the .js side doesn't come up unless you search for ".clientdata_allowDataUriScheme").
