### ISSUE TITLE
dateRangeInput returns NA

### ISSUE THREAD

**Issue by jlesuffleur** [rstudio/shiny#3099]
With shiny 1.5.0, I have trouble using dateRangeInput.

When parameters end and max are equal, the end date returns NA. And if I set start to min, the textOutput does not even appear!

Note: I get the correct value if I don't set the format, or if I use an older version of shiny

### Example application

```R
shinyApp(
  ui = fluidPage(
    textOutput("dateprint"),
    dateRangeInput("daterange",
                   label = "Dates:",
                   start = Sys.Date() - 6, end = Sys.Date(),
                   min = Sys.Date() - 7, max = Sys.Date(),
                   format = "dd/mm/yy"
                   )),
  server = function(input, output) {
    output$dateprint <- renderText({
      c(as.character(input$daterange[1]), as.character(input$daterange[2]))
    })
  }          
)
```

**Comment by cpsievert** [comment]
I'm pretty sure this is fixed in the development version, please re-open if it isn't! `remotes::install_github("rstudio/shiny")`
