### ISSUE TITLE
formatting for numericInput

### ISSUE THREAD

**Issue by HarlanH** [rstudio/shiny#31]
I'm playing with a little app design that has something like this:

```
numericInput("id", "ID:", 10000000000),
```

Unfortunately, that default displays as `1e+10`. The function should probably have some sort of formatting or number-type argument that disables scientific notation, potentially disables the decimal point for integers, etc.

Related, it'd be useful to be able to disable the stepping part of that widget, in cases where it's not relevant (ID numbers, phone numbers, etc.)

An alternative to this would be a filter to `textInput` that could be used to restrict input to a certain regular expression or similar.

**Comment by spgarbet** [comment]
But what if I want scientific notation? The patch b2d004c disabled it, but left no means to reenable.

**Comment by bborgesr** [comment]
You could check out the [work-around I created for a very similar issue](https://groups.google.com/forum/#!searchin/shiny-discuss/comma/shiny-discuss/Wb9XemTFM0w/pkhMZYWvO0gJ). The post includes links to a demo app, as well as the source code in github. In this case, the user wanted the number to be comma-separated; scientific notation is just another format -- so, you could adapt that Javascript code to do that. Note that this is more of a hack than a real solution. Hopefully, we will address this (number formatting in general) sometime in the near future.

**Comment by alandipert** [comment]
I'm closing this because the original issue was resolved via b2d004c back in 2014, and because the input validation feature request is represented by at least #1656 and #33.

@spgarbet if you still feel scientific notation in inputs would be desirable, please don't hesitate to open a new issue.
