### ISSUE TITLE
textAreaInput: `width` parameter does not work, possibly because the attribute is applied to the inner instead of outer div

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#3107]
When supplying a `width` to most inputs, the input actually takes on the specified width. Here is the output from 3 different inputs using widths:

```
> textInput("test", "test", "test", width = "500px")
<div class="form-group shiny-input-container" style="width: 500px;">
  <label class="control-label" for="test">test</label>
  <input id="test" type="text" class="form-control" value="test"/>
</div>

> selectInput("test", "test", "test", width = "500px")
<div class="form-group shiny-input-container" style="width: 500px;">
  <label class="control-label" for="test">test</label>
  <div>
    <select id="test"><option value="test" selected>test</option></select>
    <script type="application/json" data-for="test" data-nonempty="">{}</script>
  </div>
</div>

> checkboxInput("test", "test", TRUE, width = "500px")
<div class="form-group shiny-input-container" style="width: 500px;">
  <div class="checkbox">
    <label>
      <input id="test" type="checkbox" checked="checked"/>
      <span>test</span>
    </label>
  </div>
</div>
```

Note that the width is being applied to the top level element in all cases.

The issue is that with `textAreaInput()`, the width is applied to the input tag itself instead of the top level element. This results in the input not actually taking the proper width, unless you add a custom CSS rule or modify the parent element:

```
> textAreaInput("test", "test", TRUE, width = "500px")
<div class="form-group shiny-input-container">
  <label class="control-label" for="test">test</label>
  <textarea id="test" class="form-control" style="width: 500px;  ">TRUE</textarea>
</div>
```

Is this done on purpose for any reason? Will moving the width to the outer div cause other issues, or is it simply a bug?

**Comment by cpsievert** [comment]
I think this was recently fixed by https://github.com/rstudio/shiny/commit/c498b02289c39a2bd53ddc3c98dcca87ac06b8ea?

**Comment by daattali** [comment]
Yes you're right, it was fixed just last week! Thanks Carson
