### ISSUE TITLE
Reactive functions should accept quosures and deprecate `env` and `quoted`

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#3108]
Reactive functions like `reactive`, `observe`, `renderText`, and so on, accept an `env` and `quoted` argument, but those are no longer necessary if these functions accept quosures.

There aren't many real use cases for `env` and `quoted`, but here's a contrived example. This app will display `100`, instead of `0`.

```R
x <- 100
e <- environment()

shinyApp(
  ui = fluidPage(verbatimTextOutput("text")),
  server = function(input, output) {
    x <- 0
    output$text <- renderText(quote({ x }), env = e, quoted = TRUE)
  }
)
```

This can done with quosures instead.

```R
x <- 100
# This is a quosure: it captures the expression and the environment.
q <- quo({ x })
q
#> <quosure>
#> expr: ^{
#>           x
#>         }
#> env:  global


shinyApp(
  ui = fluidPage(verbatimTextOutput("text")),
  server = function(input, output) {
    x <- 0
    # The !! operator (from rlang) tells it to unquote `q`, and the reactive
    # will use the expression and environment from `q`.
    r <- reactive(!!q)
    output$text <- renderText(r())
  }
)
```

The `env` and `quoted` parameters will be deprecated; if you think there's a reason you need them, or if you need assistance converting code to quosures, please comment on this issue.

**Comment by cpsievert** [comment]
This can be closed, right?
