### ISSUE TITLE
DataTables with form elements

### ISSUE THREAD

**Issue by SamoPP** [rstudio/shiny#312]
Hi,

Would it be possible to support DataTables with form elements as shown in this example: http://datatables.net/release-datatables/examples/api/form.html . So that we could know which rows were selected in a DataTable. 

An example would be nice when we would have a table displayed with a histogram of a column below/above table where in histogram only selected rows are included (or two histograms overlayed one with all rows and one with selected rows). For example...

Best regards,
Samo

https://groups.google.com/d/msg/shiny-discuss/dU-kUdCGOoU/LhbpfZVk2cAJ

**Comment by yihui** [comment]
It is possible with the new **DT** package now. Please see https://github.com/rstudio/DT/issues/20#issuecomment-77943180
