### ISSUE TITLE
mysteriously coupled objects in r shiny

### ISSUE THREAD

**Issue by lijian007** [rstudio/shiny#3121]
In certain situations shiny does not correctly fill the values of the variables and it picks up the last available value in the whole body of the code. See example below. This bug has been around at least for 3 years.

### System details

Browser Version: 

Output of `sessionInfo()`:
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.5.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5          withr_2.3.0         digest_0.6.25      
 [4] later_1.1.0.1       mime_0.9            R6_2.4.1           
 [7] xtable_1.8-4        jsonlite_1.7.1      magrittr_1.5       
[10] rlang_0.4.7         promises_1.1.1      tools_4.0.2        
[13] tinytex_0.26        fastmap_1.0.1       httpuv_1.5.4       
[16] xfun_0.18           compiler_4.0.2      htmltools_0.5.0    
[19] shinyFeedback_0.3.0
```
# sessionInfo() output goes here
```

### Example application *or* steps to reproduce the problem

```R
#mimimal code for bug report, see comments in the code

library(shiny)

A=list(title='plotA',x=1:100)
B=list(title='plotB',x=100:1)

ui <- fluidPage(
  h1("shiny bug report"),
  h2("dynamic ui"),
  
  uiOutput("dynamicUI")
)
server <- function(input, output, session) {
  output$dynamicUI <- renderUI({
    uilist=shiny::tagList()
    v=A
    uilist[[1]]=div(h3(v$title), renderPlot(plot(v$x)))
    
    
    v=B
    uilist[[2]]=div(h3(v$title), renderPlot(plot(v$x)))
    
    #please note the plots of line 16 and 20 should be different, however, we got the same plot 
    # if we change line 19 and 20 to the following, we will get different plots
    #vx=B
    #uilist[[2]]=div(h3(vx$title), renderPlot(plot(vx$x)))
    
    uilist
  })
}
shinyApp(ui, server)
```

### Describe the problem in detail
If you run the example code you will see the problem. the two plots that are added to uilist should be different as A and B are different, but they ended up the same the only plot for data B is plotted.

**Comment by cpsievert** [comment]
In general, it's an anti-pattern to use `render*()` functions inside of other `render*()` functions. It seems what you want here is `htmltools::capturePlot()` instead of `renderPlot()`

**Comment by lijian007** [comment]
Not sure how to use capturePlot here for dynamic UI. and isn't the two plots ended up the same unexpected?

**Comment by wch** [comment]
I agree with @cpsievert's point -- it's generally not good to use a `render` function inside of another `render` function.

Now, as for why you're seeing the same plot twice, it has to do with _when_ the expression inside of the `renderPlot()` calls are evaluated.

When the `renderUI()` executes, it calls `renderPlot()` twice, and each of those capture the unevaluated expression `plot(v$x)`, but they do not evaluate that expression right away. It's not until the browser requests the plot that it evaluates `plot(v$x)`. But by the time that happens, you've assigned `v=B`, so it renders the plot for `B$x` for both of them.

Your code is also relying on a feature of `renderPlot` that is really designed for R Markdown documents. Namely, the `render*` functions can automatically make calls to the corresponding `output` functions and insert them into the page. But that's generally not good practice for normal Shiny apps.


I suggest separating the UI generation from the calls to `renderPlot`. See https://gist.github.com/wch/5436415 for an example.

**Comment by hadley** [comment]
There's a brief explanation of this issue in Mastering Shiny: https://mastering-shiny.org/reactivity-objects.html#nesting-observers

**Comment by lijian007** [comment]
hadley, wch, cpsievert, thanks for your answers, they are  really helpful.

**Comment by lijian007** [comment]
this is not a bug. thanks everyone
