### ISSUE TITLE
Shinyapps.ios - Error without an explanation

### ISSUE THREAD

**Issue by luis-zapata-b** [rstudio/shiny#3123]
![image](https://user-images.githubusercontent.com/59374884/97772327-f2fe1b00-1b13-11eb-96b6-572073080dbd.png)

The application failed to start (exited with code 1).. I got an Error in value Error, but it doenst tell me what is wrong.  please help?

**Comment by cpsievert** [comment]
The warning message is providing you a hint as to what is wrong with your application code. It's saying that the length of the result of the `na.omit()` call is not a multiple of the `names()` assignment.

If you need help debugging the application code, I recommend making a [reproducible example](https://github.com/rstudio/shiny/wiki/Creating-a-Reproducible-Example) and posting it on https://community.rstudio.com/

**Comment by luis-zapata-b** [comment]
Thanks. But i had to debug step by step. Yes, te problem was with the length of the vector, but in principle, it was a UTF-8 problem, because my data base had an "ñ". Thanks anyway.
