### ISSUE TITLE
Is there an official list of browsers+versions that are supported by shiny?

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#3124]
I see in #3075 that file uploads are no longer supported in IE8/9. Does this mean that shiny is generally supposed to be supported in IE 10+? And more generally, is there a whitelist of explicitly supported/tested browsers?

**Comment by daattali** [comment]
Part of my reason for asking is because I noticed selectInputs no longer work in IE10 (don't ask me why I know that...) because of the new `selectize-plugin-a11y.min.js` that causes an error. I don't care about that much, but it did make me think that I don't actually know what browsers are supported.

**Comment by wch** [comment]
We don't have an official list, but we are no longer supporting IE 10 and below.
