### ISSUE TITLE
Un-suspend elements in hidden part in Shiny

### ISSUE THREAD

**Issue by thothal** [rstudio/shiny#3136]
### Disclaimer

I posted this issue already on [SO](https://stackoverflow.com/questions/64682245/un-suspend-elements-in-hidden-part-in-shiny) but I guess you need to know more about the internals of Shiny to be able to answer this question, hence a re-post here.

### Problem

When I use standard Shiny, a change in the `tabPanel` somehow tells the output elements to un-suspend and show their value:
```R
library(shiny)

ui1 <- fluidPage(
   tabsetPanel(
      tabPanel("Start", p("Nothing to see here, really")),
      tabPanel("Calc", actionButton("do", "Calc"), verbatimTextOutput("out"))
   )
)

server1 <- function(input, output, session) {
   output$out <- renderPrint({
      input$do
   })
}
shinyApp(ui1, server1)
```

However, when using another framework (`bulma` in this case), the elements stay suspended. In order to make them work I have to explicitly switch off the suspendWhenHidden flag.
```R
library(shiny)
library(shinybulma)

ui2 <- bulmaPage(
   bulmaTabs(
      c("Start", "Calc"),
      center = FALSE,
      bulmaTab("Start", p("Nothing to see here, really")),
      bulmaTab("Calc", bulmaActionButton("do", "Calc"), verbatimTextOutput("out"))
   )
)

server2 <- function(input, output, session) {
   ## Need to comment out to make it run
   # session$onFlushed(function() {
   #    outputOptions(output, 
   #                  "out",
   #                  suspendWhenHidden = FALSE)
   # })
   output$out <- renderPrint({
      input$do
   })
}

shinyApp(ui2, server2)
```

Setting the `suspendWhenHiddenFlag` seems to me like a dirty workaround. Ideally, `shiny` would realize that these controls are now shown.

Granted, `shiny` cannot take care of all frameworks and there are a myriad of ways to hide an element. `shiny` simply cannot foresee all of these. However, there should be somewhere some documentation of how to un-suspend these elements *by hand*, such that package authors can take care about that.

### Question

Is there a `JavaScript` event or an `R` command through which I can explicitly un-suspend the elements in the hidden part? In this way I could submit a `PR` to `shinybulma` such that the proper code is fired upon tab changes.

### System details
```R
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinybulma_0.0.2.9000 shiny_1.5.0          

loaded via a namespace (and not attached):
 [1] compiler_3.6.3  fastmap_1.0.1   magrittr_1.5    R6_2.4.1       
 [5] promises_1.1.1  later_1.1.0.1   htmltools_0.5.0 Rcpp_1.0.5     
 [9] jsonlite_1.7.1  digest_0.6.26   xtable_1.8-4    httpuv_1.5.4   
[13] mime_0.9        rlang_0.4.8   
```

**Comment by daattali** [comment]
This sounds like a bug you should report to the bulma package. In {shinyjs}, I need to explicitly call `$(el).trigger("shown");` on elements that shiny needs to know about, I suspect something similar needs to be done when you switch to a new tab using bulma.

**Comment by thothal** [comment]
Thanks for the pointer. This was exactly what I was looking for. My assumption was that a certain event has to be triggered (`shown` in this case) to make it work. Looking into `shinybulma` I see that they rely on `jqueryui` for the tab functionality. I will commit a bugfix for that there to trigegr `shown` on click of the header.
