### ISSUE TITLE
rlang's quasi-quotation is evaluated too early in reactive expressions

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shiny#3139]
Minimal example:

```r
library(shiny)

ui <- fluidPage(actionButton("x", "Press me"))

server <- function(input, output, session) {
  
  observeEvent(input$x, {
    foo <- list(input$x)
    code <- rlang::expr(print(!!!foo))
    rlang::eval_tidy(code)
  })
  
}

shinyApp(ui, server)
```

On startup, the app crashes with

```r
Listening on http://127.0.0.1:3445
Warning: Error in enquo: object 'foo' not found
  51: enquo
  50: observeEvent [/Users/cpsievert/github/shiny/R/reactives.R#2281]
  49: server [#3]
Error in enquo(handlerExpr) : object 'foo' not found
```

Suggesting that the `rlang::expr(print(!!!foo))` is being evaluated at the wrong time with the wrong environment. I've confirmed that this was introduced by #3127

**Comment by wch** [comment]
I think this is a feature, not a bug. The `!!` or `!!!` will be resolved when the observer is created. For example:

```R
x <- 1
observe({
  print(!!x)
})
rm(x)
shiny:::flushReact()
#> [1] 1
```

So the question is how to _prevent_ that from happening. There's probably a way with rlang. I don't know how off the top of my head, but I'll look into it.

**Comment by jcheng5** [comment]
What would this do?

```r
r <- reactive({
  data %>% select(!!!input$vars)
})
```

**Comment by wch** [comment]
Hm, that would be problematic since it would try to substitute at creation time. I wonder if we'll have to back out the the quosure stuff. :(

**Comment by wch** [comment]
After talking with @lionel-, I think we have a way out of this. Basically, `reactive()` will not call `enquo()` to unwrap quosures, but users will be able to do that by using the `blast()` function from the upcoming release of rlang.


```R
blast <- function(expr, env = caller_env()) {
  eval_bare(enexpr(expr), env)
}
```

So code like this will work as the user expects:

```R
r <- reactive({
  data %>% select(!!!input$vars)
})
```

And if an advanced user wants to have `reactive()` unwrap a quosure, they can use `blast()`:

```R
q <- quo(a + 1)
r <- blast(reactive(!!q))
```
