### ISSUE TITLE
Upgrade to Bootstrap 4.5?

### ISSUE THREAD

**Issue by AshesITR** [rstudio/shiny#3169]
Are there any plans to upgrade from Bootstrap 3 to Bootstrap 4?

If no, are there canonical alternative packages to be used?
So far I've seen `bs4Dash` as a replacement for `shinydashboard`, currently under development.

**Comment by cpsievert** [comment]
You can do this via the new `{bslib}` package. https://rstudio.github.io/bslib/

We'll be submitting it to CRAN around the end of the year
