### ISSUE TITLE
issue running random forest in R Shiny 

### ISSUE THREAD

**Issue by innanenk** [rstudio/shiny#3171]
Hi! I'm trying to make a shiny app that includes a random forest already created and allows the user to input patient data that will lead to a prediction. However i keep getting the following error:
_Warning: Error in predict.randomForest: Type of predictors in new data do not match that of the training data._
Attached is my code in my app.r Shiny web app: dia.rf is the random forrest model that i've creates, I will attach it and Good.test as well.. 

![image](https://user-images.githubusercontent.com/75083565/100635950-27294f00-32ff-11eb-8472-b1780fcc276f.png)

`
set.seed(682)

dia.rf <- randomForest(as.factor(readmitted) ~., data=Good.train, mtry=1, importance=T, 
  proximity=T, na.action=na.omit)`

`library(shiny)
library(randomForest)

#inport thr model 
dia.rf <- readRDS(file = './rf.rda')
Good.test<- read.csv("Good.test.csv")

# Define UI for application that makes a prediction
ui <- fluidPage(

    # Application title
    titlePanel("Diabetes Hospital Readmission Prediction"),
    
    #1. Set up a fluid row with a description fo the model
    fluidRow( #describe the model
        column(12, 
               h3("Model Description:"), 
               verbatimTextOutput("Model_Description")
               )
        
    ),
    
    fluidRow( #description
        column(12, 
               h3("Please Answer the Following Questions as they Pertain to your Client:"))
        
    ),
    
    #3. Set up a fluidRow with 6 columns of equal widths
    fluidRow( #input for time_in_hospital, num_lab_procedures, num_procedures, num_medications, number_outpatient, & number_emergency
        column(2, #time_in_hospital
               selectInput(
                   inputId = "h_time",  #the input will be stored in input variable 
                   label= "Please select the number of days spent in the hospital between admission and discharge:", 
                   choice = 1:14, 
                   selected = 2, #defult vaue selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
               ),
        column(2, #num_lab_procedures
               selectInput(
                   inputId = "n_labp",  #the input will be stored in input variable 
                   label= "Please select the number of lab procedures completed:", 
                   choice = 1:130, 
                   selected = 57, #defult vaue selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
               ),
        column(2, #num_procedures
               selectInput(
                   inputId = "n_proc",  #the input will be stored in input variable 
                   label= "Please select the number of medical procedures completed:", 
                   choice = 0:6, 
                   selected = 3, #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
               ),
        column(2, #num_medications
               selectInput(
                   inputId = "n_meds",  #the input will be stored in input variable 
                   label= "Please select the number of medications administered:", 
                   choice = 0:70, 
                   selected = 19, #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
               ),
        column(2, #number_outpatient
               selectInput(
                   inputId = "n_outpatient",  #the input will be stored in input variable 
                   label= "Please select the number of outpatient visists in the year preceeding the Hospital visit:", 
                   choice = 0:21, 
                   selected = 0, #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
               ),
        column(2, #number_emergency
               selectInput(
                   inputId = "n_emerg",  #the input will be stored in input variable 
                   label= "Please select the number of emergancy room visists in the year preceeding the Hospital visit:", 
                   choice = 0:16, 
                   selected = 0, #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
               )
    ),
    
    #4. set up another fluid row  with 4 eqal things
    fluidRow(  #input for number_inpatient, diag_3, number_diagnoses,  &A1Cresult
        column(3, #number_inpatient
               selectInput(
                   inputId = "n_inpatient",  #the input will be stored in input variable 
                   label= "Please select the number of inpatient visists in the year preceeding the Hospital visit:", 
                   choice = 0:13, 
                   selected = 0, #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
               ), 
        column(3, #diag_3
               selectInput(
                   inputId = "diagnosis",  #the input will be stored in input variable 
                   label= "Please select the patients diagnosis(coded as the first 3 digists of ICD9):", 
                   choice = c(250, 427, 414, 428, 276, 401), 
                   selected = 250, #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
        ),
        column(3, #number_diagnoses
               selectInput(
                   inputId = "n_diag",  #the input will be stored in input variable 
                   label= "Please select the patients number of diagnoses given:", 
                   choice = 0:10, 
                   selected = 7, #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
        ),
        column(3, #A1Cresult
               selectInput(
                   inputId = "A1C",  #the input will be stored in input variable 
                   label= "Please select the patients A1C test result:", 
                   choice = c(">7", ">8",  "None",  "Norm"), 
                   selected = "Norm", #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
        )
    
        
    ),
    
    #5. Set up a new header
    fluidRow( #medication info
        column(12, 
               h3("Please Indiate Whether the Following Medications were Perscribed, and if There was a Change in Dosage:"))
        
    ), 
    
    #6. Another fluid row with 6 even rows
    fluidRow( #meds 
        column(2, #metformin
               selectInput(
                   inputId = "metformin",  #the input will be stored in input variable 
                   label= "Please Select the Metformin Medication Status:", 
                   choice = c("Down", "No", "Steady", "Up"), 
                   selected = "No", #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
               ),
        column(2, #glipizide
               selectInput(
                   inputId = "glipizide",  #the input will be stored in input variable 
                   label= "Please Select the glipizide Medication Status:", 
                   choice = c("Down", "No", "Steady", "Up"), 
                   selected = "No", #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
        ),
        column(2, #glyburide
               selectInput(
                   inputId = "glyburide",  #the input will be stored in input variable 
                   label= "Please Select the glyburide Medication Status:", 
                   choice = c("Down", "No", "Steady", "Up"), 
                   selected = "Steady", #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
        ),
        column(2, #pioglitazone
               selectInput(
                   inputId = "pioglitazone",  #the input will be stored in input variable 
                   label= "Please Select the pioglitazone Medication Status:", 
                   choice = c("Down", "No", "Steady", "Up"), 
                   selected = "Steady", #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
        ),
        column(2, #rosiglitazone
               selectInput(
                   inputId = "rosiglitazone",  #the input will be stored in input variable 
                   label= "Please Select the rosiglitazone Medication Status:", 
                   choice = c("Down", "No", "Steady", "Up"), 
                   selected = "No", #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
        ),
        column(2, #insulin
               selectInput(
                   inputId = "insulin",  #the input will be stored in input variable 
                   label= "Please Select the insulin Medication Status:", 
                   choice = c("Down", "No", "Steady", "Up"), 
                   selected = "No", #defult value selected when app is open
                   multiple = F # do not colour on mutple variables 
               )
        )
    ),
    
    #8. Calculate button 
    fluidRow(
             actionButton('cal', "Calculate!", icon = icon('calculator'))
    ),
    
# 7. the output for the prediction
    fluidRow( #prediction output
        column(12, 
               h4("Hospital Readmission Prediction"),
               verbatimTextOutput("value")  # stored in output$value
               
               )
        
    ) 

    
) #the final bracket for the entire UI

# Define server logic required 
server <- function(input, output) {
    
    #2. set up output for the model description 
    output$Model_Description <-  renderText({
        "A Machine Learning Model for Predicting Hospital Readmission in Individuals of Caucasian or African American background 
        Aged 40-90 Yrs with Pre-existing Diabetes and who Have Already Been in the Hospital."
    })
    
    
    #8. make all the inputs into a dataframe
    a <- reactiveValues(result = NULL)

    observeEvent(input$cal, {
        #Copy of the test data without the dependent variable
        test_pred <- Good.test[- c(17,18)]

        #Dataframe for the single prediction
        values =     data.frame(time_in_hospital = as.integer(input$h_time),
                            num_lab_procedures = as.integer(input$n_labp),
                            num_procedures = as.integer(input$n_proc),
                            num_medications = as.integer(input$n_meds),
                            number_outpatient = as.integer(input$n_outpatient),
                            number_emergency = as.integer(input$n_emerg),
                            number_inpatient = as.integer(input$n_inpatient),
                            diag_3 = as.factor(input$diagnosis),
                            number_diagnoses = as.integer(input$n_diag),
                            A1Cresult = as.factor(input$A1C),
                            metformin = as.factor(input$metformin),
                            glipizide = as.factor(input$glipizide),
                            glyburide = as.factor(input$glyburide),
                            pioglitazone = as.factor(input$pioglitazone),
                            rosiglitazone = as.factor(input$rosiglitazone),
                            insulin = as.factor(input$insulin))
           
      #Include the values into the new data
      test_pred <- rbind(test_pred,values)
      
      #Single preiction using the randomforest model
      a$result <-  predict(dia.rf, newdata=test_pred[nrow(test_pred),], type="response",  aggregation="average")
    })

    output$value <- renderText({
        #Display the prediction value
        paste(a$result)
    })
    
    
}

# Run the application 
shinyApp(ui = ui, server = server)
   
Warning: Error in predict.randomForest: Type of predictors in new data do not match that of the training data.
  75: stop
  74: predict.randomForest
`

**Comment by cpsievert** [comment]
Seems as though the data types of `dia.rf` don't match up `test_pred`. Closing since this isn't a shiny issue
