### ISSUE TITLE
Thematic styling can inherit error colors

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#3196]
Test app:

```R
library(thematic)
library(shiny)
library(ggplot2)

ui <- fluidPage(
  plotOutput("ggplot"),
  checkboxInput("err", "Throw an error", value = TRUE)
)
server <- function(input, output) {
  output$ggplot <- renderPlot({
    if (input$err) stop("Error here")

    dat <- data.frame(x = rnorm(50), y = rnorm(50))
    ggplot(dat, aes(x, y)) +
      geom_point()
  })
}

thematic_shiny()
shinyApp(ui, server)
```

If you uncheck "Throw an error", the plot will appear normally. However, if you re-check it, resize the window, then uncheck it, then the plot will be red.

![image](https://user-images.githubusercontent.com/86978/101683607-c6022980-3a2a-11eb-9437-f7a070c61863.png)

Possible solutions

* If there's an error class on the div, don't recompute the style and send to the server.
* Put error messages in a child div, and put the error class on that child div.

**Comment by cpsievert** [comment]
This is an unfortunate consequence of the client-side logic behind `getCurrentOutputInfo()` generally not knowing when to resend CSS styles. Currently, we (re)send CSS info when these events occur:

1. On initial load.
2. When the browser resizes.
3. When `session$setCurrentTheme()` is called.

Ideally, we'd also resend CSS when the output container itself changes, which would fix the example above (where we mutate the container, adding/remove a special class to show/hide error messages), as well as an example like this (where someone else is doing the mutation):

```r
library(shiny)
ui <- fluidPage(
    h3("After 1 second, the points should change from red to blue"),
    tags$head(
        tags$style(HTML("#p {color: red}")),
        tags$script(HTML(
            "setTimeout(function() { document.getElementById('p').style.setProperty('color', 'blue'); }, 1000);"
        ))
    ),
    plotOutput("p")
)
server <- function(input, output) {
    output$p <- renderPlot({
        plot(1:10, pch = 19, col = getCurrentOutputInfo()$fg())
    })
}
shinyApp(ui, server)
```


Unfortunately, this wouldn't fix the problem for _inherited_ styles. That is, I'm not sure of a decent way we can make something like this work (other than encouraging folks to use `session$setCurrentTheme()` as much as possible).

```r
library(shiny)
ui <- fluidPage(
    h3("After 1 second, the points should change from red to blue"),
    tags$head(
        tags$style(HTML("body {color: red}")),
        tags$script(HTML(
            "setTimeout(function() { document.body.style.setProperty('color', 'blue'); }, 1000);"
        ))
    ),
    plotOutput("p")
)
server <- function(input, output) {
    output$p <- renderPlot({
        plot(1:10, pch = 19, col = getCurrentOutputInfo()$fg())
    })
}
shinyApp(ui, server)
```


Now that I'm thinking about this last problem though, maybe we could provide a `session` method to resend the CSS styles on-demand (as a last resort to work around it)
