### ISSUE TITLE
Feature request: `reactive()` capable of "ignoring" its queue of states

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#3213]
### The problem:

When a reactive takes a long time to calculate and its value changes too often, the UI needs to "catch up" with the reactive values one-by-one. Here is an example code:

```
library(shiny)
ui <- fluidPage(
  numericInput("num", "num", 5),
  textOutput("square")
)
server <- function(input, output, session) {
  square <- reactive({
    Sys.sleep(1)
    input$num ^ 2
  })
  output$square <- renderText({ square() })
}
shinyApp(ui, server)
```

If you change the input too fast but not fast enough, you end up with this issue:

![shiny](https://user-images.githubusercontent.com/952340/102427463-68984a80-3fdf-11eb-98ad-1d6f049a2661.gif)

### Existing solutions

The `debounce()` and `throttle()` functions were added as a way to combat this problem. In many cases they do work, but I've often felt it's not always an ideal solution. With debounce, it can cause the user to have to wait too long to see a change, and with throttle the problem is just reduced to happen less frequently.

### Proposal

The root of the issue is that there is a queue of values that get accessed one by one. If could be useful to have something such as `reactive(.., cancelPrevious = TRUE)` which would cause any values in the invalidation loop that haven't yet been looked at to be removed. I only thought about it in a very narrow simple context and my naive thinking is that because reactive values do not require to keep their history (which makes them so well suited for bookmarking) maybe this would be possible. It's also entirely possible that this is not achievable and would break a lot of things that I haven't considered.

**Comment by jcheng5** [comment]
I’ve looked at this in the past. It *might* be possible to do this, but not, I believe, at the level of a reactive object. Instead, shiny would need to look at the queue of built up websocket update messages and decide which messages are safe to coalesce. However, that decision isn’t an easy one and today I don’t think we have quite enough information to do that. Imagine a form with a bunch of text fields and a Save actionButton that persists the values to a db, what would happen if you collapse a sequence of messages that include multiple button presses?

You’d basically need to know precisely what inputs are being used only for their values (and thus safe to coalesce) versus being used to trigger side effects (forms a barrier). Action buttons definitely fall into the latter category, what about clicking on a ggplot or leaflet map? I think only the app author can answer that for sure.

**Comment by daattali** [comment]
Thanks for the explanation. This feature would indeed only be useful if it can be controlled at a per-reactive level. Since you say it's only possible at the app level,  it's probably best to not do it.
