### ISSUE TITLE
selectizeInput(multiple=T) fg color doesn't properly contrast selected bg color

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shiny#3215]
It looks like for certain "Primary" Accent colors and a contrast text color shown with that primary color, the pills in the selectizeInput(Multiple) box does not display the same text color.

1. Navigate to https://testing-apps.shinyapps.io/shinyapps-themer-demo-Dec-16/
2. Go to Accent colors in the themer window
3. Select a primary color for ex: #2754AE (dark blue). Notice that the text color within that box is adjusted to white for a better contrast.
4. In the InputPanel's selectizeInput (Multiple) box, add some states. 
5. Highlight or select the pills within the box. Notice the text color when the pill is selected

Expected: This is supposed to be the white text color as mentioned in step 3 above
Actual: shows text color in black.

Few snapshots and example for other primary color selections are below.

<img width="1679" alt="selectInput_pills_text_color_does_not_match_primary_color_text" src="https://user-images.githubusercontent.com/5369655/102423688-725d8600-3fbe-11eb-82f5-0a1851ede8af.png">

<img width="1678" alt="selectizeInput_text_color_vs_primary_color_1" src="https://user-images.githubusercontent.com/5369655/102423652-5eb21f80-3fbe-11eb-8bd5-fb7ef76734e1.png">

<img width="1676" alt="selectizeInput_vs_primary_color_text_color_2" src="https://user-images.githubusercontent.com/5369655/102423751-8d2ffa80-3fbe-11eb-8a9d-a2a9e54817e0.png">

Note: I could not find or understand a specific pattern for these cases. Also, this happens on all platforms (locally and hosted)

**Comment by cpsievert** [comment]
@MadhulikaTanuboddi the table color contrasting is a separate issue that would have to be addressed in the DT package. I've filed a separate issue so we don't forget about it (https://github.com/rstudio/bslib/issues/198), but I see that as a "v2" issue that we'll address after an initial `{bslib}`/`{shiny}` release

**Comment by MadhulikaTanuboddi** [comment]
selectizeInput verified
