### ISSUE TITLE
Move label text inside of selectInput box

### ISSUE THREAD

**Issue by johnpauls** [rstudio/shiny#322]
It would be nice if you could put the label text for the selectInput control in the select box area. For example if you have a control where you select a city name, there would be the option to have "Chose a city" as the default selection, and this selection could pass a NULL value to server.R. Then you would not have to put this text above the controller, which would save some space, if needed.

**Comment by tarunparmar** [comment]
@yihui is it possible to break the text inside placeholder to display on next line ?
I have tried with `HTML()` but did not work. 
e.g. 
`placeholder = HTML("Please input paste comma separated string <br/> OR <br/> upload CSV file")`

**Comment by yihui** [comment]
@tarunparmar I don't think the placeholder supports HTML: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefplaceholder
