### ISSUE TITLE
unexpected behaviour when clicking on a scaled image

### ISSUE THREAD

**Issue by pieterprovoost** [rstudio/shiny#3234]
### System details

Browser Version: Google Chrome Version 87.0.4280.88 (Official Build) (x86_64), high DPI screen

Output of `sessionInfo()`:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS  10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.5.0.9006

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5           digest_0.6.27        later_1.1.0.1        mime_0.9            
 [5] R6_2.5.0             jsonlite_1.7.2       lifecycle_0.2.0      xtable_1.8-4        
 [9] magrittr_2.0.1       cachem_0.0.0.9000    rlang_0.4.10         promises_1.1.1.9001 
[13] jquerylib_0.1.3      bslib_0.2.3.9000     ellipsis_0.3.1       tools_4.0.2         
[17] tinytex_0.24         httpuv_1.5.4         xfun_0.15            fastmap_1.0.1       
[21] compiler_4.0.2       htmltools_0.5.0.9003 sass_0.2.0.9005  
```

### Example application

```R
library(shiny)

shinyApp(
  ui = basicPage(
    fluidRow(
      column(width = 6, imageOutput("image", click = "image_click")),
      column(width = 6, verbatimTextOutput("image_clickinfo"))
    )
  ),
  server = function(input, output, session) {
    output$image <- renderImage({
      list(
        src = "test_1000.png",
        contentType = "image/png",
        width = "100%"
      )
    })
    output$image_clickinfo <- renderPrint({
      str(input$image_click)
    })
  }
)
```

Test image: [test_1000.png](https://user-images.githubusercontent.com/490041/103578997-d2698d00-4ed7-11eb-8b72-6a584f452289.png)

### Describe the problem in detail

The example application loads an existing image into an imageOutput and adds a click handler. This works fine for smaller images, but when the image is larger than the DOM element, clicks are only registering in the top left part of the image. In the example below, a 1000 by 1000 pixel image is loaded into a 610 CSS pixels wide element. Clicking on the top left crosshairs will correctly return (200, 200) in image coordinates, so the fact that the image is scaled is taken into account. However, clicking on the bottom right crosshairs does not work as its location in image coordinates (800, 800) exceeds the size of the DOM element (610).

I fiddled around with the code a bit and managed to fix my problem by using `img.naturalWidth` and `img.naturalHeight` [here](https://github.com/rstudio/shiny/blob/master/srcjs/output_binding_image.js#L388), but that breaks the [official example](https://shiny.rstudio.com/reference/shiny/0.12.1/imageOutput.html).

<img width="1280" alt="screenshot" src="https://user-images.githubusercontent.com/490041/103579892-7acc2100-4ed9-11eb-96dc-394ab01cf992.png">

**Comment by dcaud** [comment]
Does using something like `image_click$coords_img$x` and `image_click$coords_img$y` fix this?

**Comment by lachlansimpson** [comment]
This was mentioned in internal support ticket 107146.
