### ISSUE TITLE
Extract the id location of Shiny input functions (like dateInput()) in a consistent manner

### ISSUE THREAD

**Issue by MarkEdmondson1234** [rstudio/shiny#3248]
Perhaps this exists internally in the package, but I couldn't find it.

I'm templating some Shiny modules that lets users pass in input Shiny functions like `dateInput()` or `selectInput()` to create a Shiny module on the fly.

Its all working but at the moment only for `dateInput()` as I can add the module namespace via `NS::` to the known id attibute:

```r
library(shiny)
library(assertthat)

inputShiny <- dateInput("my_id","Input Date")

# this only works with dateInput()
input_id <- inputShiny$attribs$id
  
ui <- function(id, ...){
    ns <- shiny::NS(id)
    if(!is.null(input_id)){
      inputShiny$attribs$id <- ns(input_id)
    } 
    shiny::tagList(
      inputShiny,
      outputShiny(outputId = ns("ui_out"), ...)
    )
  }

#...server code makes reactive inputs via input[[input_id]]
```

This works as I can find the `id` attribute in the object via `inputShiny$attribs$id`:

```r
str(shiny::dateInput("my_id","date"))
#List of 3
# $ name    : chr "div"
# $ attribs :List of 2
 # ..$ id   : chr "my_id"
#  ..$ class: chr "shiny-date-input form-group shiny-input-container"
 #$ children:List of 3
#...etc...
```

But the same code doesn't work with say `selectInput()` or `checkboxInput()` as its `id` is in a different location:

```r
str(shiny::checkboxInput("my_id","label"))
#List of 3
# $ name    : chr "div"
# $ attribs :List of 1
#  ..$ class: chr "form-group shiny-input-container"
# $ children:List of 1
 # ..$ :List of 3
#  .. ..$ name    : chr "div"
#  .. ..$ attribs :List of 1
#  .. .. ..$ class: chr "checkbox"
#  .. ..$ children:List of 1
#  .. .. ..$ :List of 3
#  .. .. .. ..$ name    : chr "label"
#  .. .. .. ..$ attribs : Named list()
#  .. .. .. ..$ children:List of 2
#  .. .. .. .. ..$ :List of 3
#  .. .. .. .. .. ..$ name    : chr "input"
#  .. .. .. .. .. ..$ attribs :List of 2
 # .. .. .. .. .. .. ..$ id  : chr "my_id"
 ...etc..
```
e.g. the id to change is now at `x$children[[1]]$children[[1]]$children[[1]]$attribs$id` 

I could make some kind of recursive search tool but I thought it likely or would be nice to have a function in `shiny` that would do it.  

It could be something like `extract_id(checkboxInput("my_id","my_label")` which would extract `"my_id"`. 

Or perhaps there is another way to do it?

**Comment by MarkEdmondson1234** [comment]
Some potential candidates here:

```r
replace_in_list <- function(a_list, id = "my_id", change_id = "my_id2"){
  rapply(a_list, function(x){
    if(x == id){
      change_id
    } else {x}}, how = "replace", classes = "character")
}

extract_from_list <- function(a_list, id = "id"){
  chrs <- rapply(a_list, function(x) if(is.character(x)){x})
  unique(unname(chrs[grepl("id$",chrs)]))
}

replace_in_list(dateInput("my_id","Date"))
<div id="my_id2" class="shiny-date-input form-group shiny-input-container">
  <label class="control-label" for="my_id2">Date</label>
  <input type="text" class="form-control" data-date-language="en" data-date-week-start="0" data-date-format="yyyy-mm-dd" data-date-start-view="month" data-date-autoclose="true" data-date-dates-disabled="null" data-date-days-of-week-disabled="null"/>
</div>

extract_from_list(dateInput("my_id","Date"))
[1] "my_id"

replace_in_list(checkboxInput("my_id","Date"))
<div class="form-group shiny-input-container">
  <div class="checkbox">
    <label>
      <input id="my_id2" type="checkbox"/>
      <span>Date</span>
    </label>
  </div>
</div>

extract_from_list(checkboxInput("my_id","Date"))
[1] "my_id"
```

**Comment by cpsievert** [comment]
Thanks for the ideas @MarkEdmondson1234, we're aware this is a sore point, and we're hoping to dedicate some to it in a future release (this would probably end up living in `{htmltools}` though)

**Comment by cpsievert** [comment]
The dev version of htmltools now has `tagQuery()` designed to solve this class of problem https://rstudio.github.io/htmltools/articles/tagQuery.html

**Comment by nuno-agostinho** [comment]
Hey @cpsievert, `tagQuery()` is currently not a solution, as the results from that function may modify the original Shiny object just from passing a Shiny object as argument.

For instance, in this case I simply convert a `navbarPage` to `tagQuery(...)$allTags()` and the resulting Shiny app has a weird UI:

```R
ui <- navbarPage("App Title",
           tabPanel("Plot"),
           navbarMenu("More", tabPanel("Table")))
mod <- tagQuery(ui)$allTags()
shinyApp(mod, server=function(...) {} )
```

Is there a way to use `tagQuery()` properly with Shiny? If you prefer, I can open a new issue regarding this.

**Comment by ismirsehregal** [comment]
I just left a related answer [here](https://stackoverflow.com/a/70898415/9841389), wondering whether there is a better way to get those id's via `tagQuery`?

**Comment by cpsievert** [comment]
@nuno-agostinho your example is actually a bug that I believe was recently fixed in htmltools: `remotes::install_github("rstudio/htmltools")`
