### ISSUE TITLE
Feature Request: option to disable accessibility js and css

### ISSUE THREAD

**Issue by lz100** [rstudio/shiny#3258]
In the pre 1.6 release, the accessibility plugin is added. This plugin adds undesired border, background etc. to my existing UI. 

Can we have an argument on shiny start to choose / not choose to add this plugin?

![image](https://user-images.githubusercontent.com/35240440/104777133-2cc0e400-5749-11eb-999d-5e11661b0afd.png)

**Comment by cpsievert** [comment]
Currently there is no easy way to op-out of the plugin, but we've removed mouse-based outline focus by default in the release. Please let us know if you encounter any other issues with the accessibility plugin

https://blog.rstudio.com/2021/02/01/shiny-1-6-0/#accessibility
