### ISSUE TITLE
List Objects in Reactive Values

### ISSUE THREAD

**Issue by iqis** [rstudio/shiny#3265]
When working with reactive values, it is sometimes necessary to see what bindings are available within.  Adding a `reactivevalues` method to `ls()` doesn't work because it's not a generic function.

I have been using the following as a workaround: 
```
ls_rv <- function(x, ...){
  base::ls(unclass(x)$impl$.values$private$map$as_list(), 
           ...)
}
```

Is there a canonical/idiomatic way to do this? If not, can we have something like this built into Shiny?

**Comment by wch** [comment]
The `names()` function will work on reactiveValues objects.
