### ISSUE TITLE
Bug with InputPicker among others from ShinyWidgets

### ISSUE THREAD

**Issue by quantsulting** [rstudio/shiny#3266]
With shiny 1.6.0 there is now an issue for the different select pickers from the package ShinyWidgets. The option menu has to be manually closed with "escape" after having picked one element (or several if multiple=TRUE)

**Comment by wch** [comment]
Can you provide a minimal reproducible example?

**Comment by yandiru** [comment]
I think it's the same here https://github.com/dreamRs/shinyWidgets/issues/346

**Comment by wch** [comment]
Great. I'll close here but if it requires modifications to Shiny, this can be reopened, or a new issue can be filed.
