### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#33]
Need to give developers a way to specify what values are valid, at least for text boxes.

**Comment by maxheld83** [comment]
not sure about the bigger scheme of things, but I was hoping some feature like this would exist.

My use case is where I might want to run some simple validation tests, such as:

- provided string as a valid R object name
- arbitrary regex


I'm aware of the [`validate(need())`](https://shiny.rstudio.com/articles/validation.html) way of doing things, but this perhaps has some shortcomings:

1. it may sometimes be more intuitive to place some of these input validations right *inside* the `textInput()` call, especially when it's something simple such as *accept only letters, no numbers*.
2. a similar problem arises for the UI/UX: input validation via `validate()` is customarily displayed in whatever *output* object is affected by some unacceptable input. This is a bit weird/distracting for users, who may expect such a message *at the place where they need to make changes*, say, by highlighting the `textInput()` entry field in red or whatever.

I know that I could (probably) build this by hand, using additional `render*()` output calls right next to the `textInput()` calls, but this would seem to add a lot of cruft to my code, and perhaps muddy intent. (I'm not really `render*()`ing any output, I'm just complaining about an input).

Anyway, I was hoping this would be possible outside the box, but I'm too naive a user to know how/if/where this should be done.

Am I making sense?

Other thoughts / caveats:

- I like @rpruim's syntax, but I wonder whether integrating with some *existing* syntax/package for input validation (such as @mllg's [checkmate](https://github.com/mllg/checkmate)) wouldn't be more elegant. (will open separate issue for that).
- Accepting more complicated validation tests *inside* `inputText()` may run the risk of duplicating `validate()` functionality, and might just confuse everyone more. Would it be possible to use render the `validate()` output to whichever `inputx()` created the offending ID. (will open separate issue)

This may also be interesting to @bborgesr and/or revelant to #1656.

**Comment by mkaranja** [comment]
Hi all,
So I need to validate email address textInput() and immediately tell the user to proceed by use of a check icon or show a warning to supply the right email address if not valid. I know how validate(need()) works but it's not suitable here.
Supporting  @maxheld83 question, has anyone found a way to do this?
Thank you.

**Comment by mvarewyck** [comment]
@mkaranja I did something similar with the R package [shinyFeedback](https://cran.r-project.org/web/packages/shinyFeedback/vignettes/shinyFeedback-intro.html)

**Comment by cpsievert** [comment]
Closing since we now have https://github.com/rstudio/shinyvalidate
