### ISSUE TITLE
runGist in a function

### ISSUE THREAD

**Issue by helgasoft** [rstudio/shiny#3309]
### System details

Browser Version: Chrome Version 88.0.4324.190 (Official Build) (64-bit)
Working in RStudio Version 1.4.1103.

Output of `sessionInfo()`:

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3   assertthat_0.2.1 cli_2.3.0        tools_4.0.3     
[5] glue_1.4.2       yaml_2.2.1       rlang_0.4.10 
```

### Example application *or* steps to reproduce the problem

 

```R
fun <- function() {
  if (interactive())
    shiny::runGist('6c33ee09a16d55569c562f7aa3951088')
}
fun()
```

### Describe the problem in detail
When running **any** gist from a function,  exiting/closing the Shiny window pops a breakpoint in the Console:
   **Called from: top level**
then after clicking Stop, comes another one
   **Called from: execCallbacks(timeoutSecs, all, loop$id)**
and after stopping again everything is back to normal.
This is confusing to all users.  
Any solution to make those breakpoints disappear?

**Comment by wch** [comment]
I'm not able to reproduce this problem.

The behavior you're describing sounds exactly like what happens if `options(error=browser)` has been set before running the Shiny app.

**Comment by helgasoft** [comment]
Thank you, Winston!  Indeed this is the cause. We set this option thru RStudio.
RStudio > Debug > On Error has 3 options: "Message only", "Error Inspector"  and "Break in Code".
The first two do not interrupt the exit, but "Break in Code" does.
