### ISSUE TITLE
Allow option for nested directories in R/ folder to be sourced automatically with runApp()

### ISSUE THREAD

**Issue by heds1** [rstudio/shiny#3342]
As described in the documentation [here](https://shiny.rstudio.com/articles/app-formats.html):

> As of Shiny version 1.3.2.9001, any .R files found in an R/ directory adjacent to your app will be automatically loaded when your app starts. Just like R packages, only the files at the top level of R/ are considered; nested directories are ignored. Files in this directory are sourced in alphabetical order and any variables, functions, or modules they create are available to be used in your app.R, ui.R, or server.R files.

It would be useful to have an option to allow nested directories to be sourced, rather than ignored. I often have a layout like this in my app's R/ directory:

```
R/
|---- global.R
|---- modules
        |---- module1.R
        |---- module2.R
        |---- module3.R
        |---- particularlyLargeTopic/
                |---- module4.R
                |---- module5.R
```

Currently, calling `runApp` (or clicking Run App in RStudio) will only source `global.R`, ignoring all the nested files.

(Note that the documentation linked above has a warning that this automatic sourcing of scripts in R/ is only available in the development version of Shiny, which is outdated advice now.)

My current workaround is just to read in all data, which isn't too annoying but would be nice to avoid:

```
invisible(sapply(list.files('./R', full.names = TRUE, recursive = TRUE), function(i) {
    source(paste0(i))
}))
```

Perhaps adding the following option that defaults to FALSE but can be set TRUE, in the style of `shiny.autoload.r`:

`options(shiny.autoload.r.nested = FALSE)`

**Comment by daattali** [comment]
This was suggested (and rejected) in https://github.com/rstudio/shiny/issues/2850

**Comment by heds1** [comment]
Thanks Dean, I missed that. 

I don't fully understand the reasoning behind this. A shiny app isn't an R package; why does the behaviour have to be consistent? Or more to the point, why can't the user set different behaviour?

Would it be worth submitting a pull request that modifies `loadSupport`? E.g.,

```
helpers <- list.files(helpersDir, pattern = "\\.[rR]$", 
    recursive = getOption("shiny.autoload.r.nested", FALSE),
    full.names = TRUE)
```

Source [here](https://github.com/rstudio/shiny/blob/1f9e4929a6d46ca4b1337faed8273b4d0b21b75c/R/shinyapp.R).

**Comment by wch** [comment]
The decision was made for consistency and simplicity. Adding features and options is always a tradeoff -- there is a cost in terms of complexity and maintenance burden. For example, with the proposed implementation, setting the option to `TRUE` could cause a different Shiny app that is run in the same session to break, in a way that is hard to diagnose. (We are trying to reduce the amount of global settings and global state in Shiny for similar reasons, and doing so is nontrivial.)
