### ISSUE TITLE
There is a blank line when the URL is added to the TabPanel.

### ISSUE THREAD

**Issue by li153348734** [rstudio/shiny#3359]
As per the following thread: https://stackoverflow.com/questions/66705252/open-url-in-shiny-with-html, when I add the URL to the title of the TabPanel, it will show a blank row, How can I remove it ?

**Comment by cpsievert** [comment]
In that example, you have a `tabPanel()` within a `tabPanel()` (which isn't allowed, unless you put the inner `tabPanel()` within a `tabsetPanel()`)
