### ISSUE TITLE
No line numbers for R errors

### ISSUE THREAD

**Issue by leedrake5** [rstudio/shiny#3369]
I can't provide reproducible code precisely because of the nature of the error. For the past 6 months, shiny isn't providing helpful traceback when an error is reached. The full error I just received is: 

```
Warning: Error in if: argument is of length zero
  1: shiny::runApp
```

This is extremely common - obviously some if() statement is causing problems in the server code, but I have to guess randomly to find it. This is probably the hundredth time I've run into inadequate traceback. Is this just me or are other people facing this problem with recent shiny updates?

**Comment by cpsievert** [comment]
Try calling `shiny::devmode()` before running the app -- that should give you a better stack trace

**Comment by leedrake5** [comment]
That fixed it! For others with this problem, first run

`shiny::devmode(TRUE)
`
Then your app.

**Comment by IanWorthington** [comment]
> Try calling `shiny::devmode()` before running the app -- that should give you a better stack trace

This gives a full stack trace indeed, but still no line numbers or the specifics of the failing instruction:

`
Warning: Error in $: object of type 'closure' is not subsettable
shiny devmode - Turning on full stack trace. To disable, call `options(shiny.fullstacktrace = FALSE)`
This message is displayed once every 8 hours.
  103: h
  102: .handleSimpleError
  101: validate_slider_value
  100: `sliderInput`
`
