### ISSUE TITLE
DataTableOutput truncates dotted strings

### ISSUE THREAD

**Issue by sriumcp** [rstudio/shiny#337]
Strings -- both column names as well as character values in R data.frames with a dot ('.') in them does not displayed correctly in the dataTableOutput:  for e.g., Z.Y.X.22 ends up getting displayed as Z (with the rest of the string after the first half getting truncated).

I believe the issue is with the datatable javascript implementation. I found a suggested remedy here: http://datatables.net/forums/discussion/comment/51007 ; this states that using version 1.10 of the datatable implementation provides a work around (e.g., dots can be escaped in this new version of the javascript for correct rendering).

How can I integrate this new dataTable javascript with my existing shiny download? Or are there simple settings in existing R Shiny that can make dataTableOutput work for me?

**Comment by yihui** [comment]
DataTables 1.10.x has been integrated into shiny. You may also be interested in the DT package: https://github.com/rstudio/DT
