### ISSUE TITLE
fileinput doesn't return multiple line in shiny

### ISSUE THREAD

**Issue by namrouche993** [rstudio/shiny#3380]
when i tried to do the simple example of fileInput maybe something is not happening :

    library(shiny)

     ui <- fluidPage(
        fileInput("upload", NULL, buttonLabel = "Upload...", multiple = TRUE),
        tableOutput("files")
                       )
     
     server <- function(input, output, session) {
       output$files <- renderTable(input$upload)
          }
 
     shinyApp(ui, server)

I only get the recurrent file (single file), and not like this :

![upload](https://user-images.githubusercontent.com/42832704/117127985-4a8e7500-ad49-11eb-9e7c-7676ba8f3de9.png)

I tried to change a browser but the same problem, or is there any way to upload multiple files ? maybe using append and reactive

**Comment by vipultagai** [comment]
Could you share the output you are getting?

**Comment by cpsievert** [comment]
>  is there any way to upload multiple files ?

Yes, when you clicked "Upload..." did you select multiple files before clicking "Open" (like this)?

<img width="579" alt="Screen Shot 2021-06-28 at 3 40 54 PM" src="https://user-images.githubusercontent.com/1365941/123701298-45b8df80-d827-11eb-9544-13765d9b2ee6.png">


If you want to keep the _history_ of uploaded files, you'll want to store that info in a `reactiveVal()`, like this:

```r
uploads <- reactiveVal()
observeEvent(input$upload, {
  x <- rbind(uploads(), input$upload)
  uploads(x)
})
```
