### ISSUE TITLE
Implement Flaticon 'uicons' alongside fontawesome and glyphicon

### ISSUE THREAD

**Issue by joannawolthuis** [rstudio/shiny#3405]
Hi Shiny crew, thanks for your hard work on this wonderful package!
I am an avid user of icons, and also a great fan of [Flaticon](https://www.flaticon.com/). 
Recently I noticed that they have added a new feature, namely icons that seem to function similarly to fontawesome icons in terms of syntax, called '[uicons](https://www.flaticon.com/uicons/)' and was wondering if it is possible to implement these icons as an additional icon source alongside fontawesome and glyphicon.

Kind regards and thank you for your time,
Joanna

**Comment by cpsievert** [comment]
Thanks, we've decided that Shiny won't be bundling anymore icon libraries, but that doesn't mean you can't use them via another package, or your own `htmlDependency()`s. See, for example, https://github.com/mitchelloharawild/icons
