### ISSUE TITLE
Should all TypeScript config files be moved from `./srcts` to `./`

### ISSUE THREAD

**Issue by schloerke** [rstudio/shiny#3415]
Pros for keeping all configs at `./srcts`
* Does not clutter the top level repo. The configs only pertain to `./srcts`

Pros for moving all configs to `./`
* When working on TypeScript code, no need to open the `./srcts` subfolder as a new VS Code project
* Able to install Shiny package from GitHub.
	* Not able to install a NodeJS package from a GitHub subdirectory: (Denied) https://github.com/npm/npm/issues/2974
* husky (pre-commit) hooks work out of the box
	* (Can work in a custom directory like `./srcts` - https://typicode.github.io/husky/#/?id=custom-directory)

---------------

Other approach:

Keep all TS files in `./srcts`, but add an _additional_ `package.json` in the root folder that contains husky (pre-commit) hooks and points to type declarations within `./srcts`.  
* Pro: 
	* This may not be a bad approach as developer usage and Shiny application execution are different goals.
	* Top level folder only gains `package.json` 
		* Allows external developers to install the Shiny type definitions
* Con: 
	* It will lead to confusion as to why there are two package.json files.
	* Still requires internal developers to open the project on the `./srcts` folder to have the VS Code IDE work as expected.

---------------

Not having a `package.json` in the top level is a deal breaker. This prevents developers from being able to install nodejs packages from a subdirectory.  Once type definitions are exported, having the `package.json` in a subdirectory prevents users from being able to import the Shiny TypeScript type definitions.

**Comment by cpsievert** [comment]
Moving to `./` seems like a good idea (will be nice to open VS Code from root and have things "just work"TM)

**Comment by cpsievert** [comment]
Let's make sure we have a section on the README explaining the setup:

- [ ] Update README
- [ ] Update `srcts/README.md`
- [ ] Update https://github.com/rstudio/shiny/blob/master/.github/CONTRIBUTING.md
