### ISSUE TITLE
Font awesome content not working properly

### ISSUE THREAD

**Issue by avinash-1997** [rstudio/shiny#3438]
I am trying to add font awesome content throgh css but it's not working properly.
Here the code "content: "\f095";"
Kindly help mi with out

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.

I suggest taking a look at the help page for the `icon()` function in Shiny, and at the fontawesome package. https://github.com/rstudio/fontawesome
