### ISSUE TITLE
Faild to load resource: the server responded with a status of 404

### ISSUE THREAD

**Issue by apalacio10** [rstudio/shiny#3454]
Hello,

In the developer version when a selectizeInput is added the following error appears in the js console. 

![imagen](https://user-images.githubusercontent.com/40868159/124047077-f5817f00-d9d8-11eb-9c2f-0ae5b2cd39f0.png)

**Comment by apalacio10** [comment]
Using the safari browser, the screen freezes. I think this is related to the error.

**Comment by wch** [comment]
Can you provide a reproducible example? Otherwise we don't have a way of debugging the problem. Please see: https://community.rstudio.com/t/shiny-debugging-and-reprex-guide/10001

**Comment by apalacio10** [comment]
Hello,

I was building a reproducible error, the error is given by the combination of a selectInput and a renderPlotly. This is the code I built.

`library(shiny)

shinyApp(
  ui = fluidPage(
    selectInput("n", "N", 1:10),
    plotlyOutput("plot")
  ),
  server = function(input, output, session) {
    output$plot <- renderPlotly({
      n <- as.numeric(input$n) * 2
      plot_ly(head(cars, n)) %>% add_markers(x=~speed,y=~dist)
    })
  }
)
`

This is the error that appears in the java console 

![imagen](https://user-images.githubusercontent.com/40868159/124781095-c0a98680-df08-11eb-80f3-1ca7b596bf03.png)

Plotly version is latest from developer

**Comment by cpsievert** [comment]
I don't think this code example reproduces the 404 that you're seeing. Also, I'd be surprised if this error is actually causing the safari issue you mentioned (a missing `.map` file is only relevant for the developer tools).

**Comment by wch** [comment]
Just to add a bit more detail: the crosstalk.min.js.map file would only be loaded _after_ you open the JavaScript console -- it's used only when debugging the application, but not when the application is loaded normally.
