### ISSUE TITLE
Problem installing httpuv while installing shiny package

### ISSUE THREAD

**Issue by bishnu-dumbledore** [rstudio/shiny#3491]
While installing 'httpuv' I encountered this....

install.packages("httpuv")`
Installing package into ‘/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/httpuv_1.6.2.tar.gz'
Content type 'application/x-gzip' length 1815049 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

* installing *source* package ‘httpuv’ ...
** package ‘httpuv’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Ilibuv/include -pthread -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/later/include'   -fvisibility=hidden -DSTRICT_R_HEADERS -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports-legacy.cpp -o RcppExports-legacy.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Ilibuv/include -pthread -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/later/include'   -fvisibility=hidden -DSTRICT_R_HEADERS -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Ilibuv/include -pthread -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/later/include'   -fvisibility=hidden -DSTRICT_R_HEADERS -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c callback.cpp -o callback.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Ilibuv/include -pthread -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/later/include'   -fvisibility=hidden -DSTRICT_R_HEADERS -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c callbackqueue.cpp -o callbackqueue.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Ilibuv/include -pthread -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/later/include'   -fvisibility=hidden -DSTRICT_R_HEADERS -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c filedatasource-unix.cpp -o filedatasource-unix.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Ilibuv/include -pthread -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/later/include'   -fvisibility=hidden -DSTRICT_R_HEADERS -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c filedatasource-win.cpp -o filedatasource-win.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Ilibuv/include -pthread -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/later/include'   -fvisibility=hidden -DSTRICT_R_HEADERS -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fs.cpp -o fs.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Ilibuv/include -pthread -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/Rcpp/include' -I'/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/later/include'   -fvisibility=hidden -DSTRICT_R_HEADERS -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-QwogzP/r-base-4.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c gzipdatasource.cpp -o gzipdatasource.o
In file included from gzipdatasource.cpp:1:
gzipdatasource.h:4:10: fatal error: zlib.h: No such file or directory
    4 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:177: gzipdatasource.o] Error 1
ERROR: compilation failed for package ‘httpuv’
* removing ‘/home/bishnu_dumbledore/R/x86_64-pc-linux-gnu-library/4.1/httpuv’
Warning in install.packages :
  installation of package ‘httpuv’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpoispJ5/downloaded_packages’

......

Any solutions I can apply ?
Thank you in advance!

**Comment by bishnu-dumbledore** [comment]
I solved this problem by updating `zlib` in terminal

**Comment by toxintoxin** [comment]
I'm still experiencing the glance problem in December 2023 on ubuntu 20.04, which I solved via `sudo apt install libz-dev`
