### ISSUE TITLE
Error could not find function "get_quosure"

### ISSUE THREAD

**Issue by arunkodati77** [rstudio/shiny#3506]
After installing the latest version of shiny I am getting the following error
could not find function "get_quosure"

**Comment by nagiosleaner** [comment]
Yes， I alse get this error when I run my shiny app after re-install the latest version of shiny:
![image](https://user-images.githubusercontent.com/9432108/134461003-b6631a33-dd8e-4416-af5d-a613d7f87c0a.png)

and my server.R line 570 is:
![image](https://user-images.githubusercontent.com/9432108/134461094-2831d561-0388-412c-8c95-87866287a412.png)

**Comment by cpsievert** [comment]
I'm pretty sure doing `install.packages("bs4Dash")` will fix this issue (please reopen if not)

**Comment by ferroao** [comment]
workaround:
```
package = "https://cran.r-project.org/src/contrib/Archive/shiny/shiny_1.6.0.tar.gz"
utils::install.packages(pkgs = package, repos = NULL)
```

**Comment by wch** [comment]
If your package uses bs4Dash, reinstalling it should fix it. shinydashboardPlus also had the same issue, and reinstalling them from CRAN should also fix it. For reference:

* https://github.com/RinteRface/shinydashboardPlus/pull/151
