### ISSUE TITLE
Support client side rendering for real time analytics

### ISSUE THREAD

**Issue by travis-leith** [rstudio/shiny#3507]
I was recently demoed a commercial solution for real time streaming analytics visualization.
I was impressed by how smoothly the dashboard handled very many updates per second (financial market data).
I remarked that this would take 20 seconds between each update if I tried to do this in R Shiny.
The presenter responded with something along the lines "yes, especially because shiny uses server side rendering".

Unfortunately, as a data scientist, I have very limited knowledge of this aspect of the technology so I don't know how reasonable a feature request this is.

But it would be nice if I could get this kind of performance out of R Shiny, presumably using client side rendering.

**Comment by cpsievert** [comment]
Some `{htmlwidgets}` packages have support for client-side updating (via "proxy" object), notably `{DT}`, `{leaflet}`, and `{plotly}`. Here are a few links:

https://plotly-r.com/linking-views-with-shiny.html#shiny-performance
https://plotly-r.com/linking-views-with-shiny.html#fig:shiny-stream
https://rstudio.github.io/leaflet/shiny.html#modifying-existing-maps-with-leafletproxy 

By the way, https://community.rstudio.com is a better place to be asking these sorts of questions
