### ISSUE TITLE
Error in value[[3L]]

### ISSUE THREAD

**Issue by Tkthon** [rstudio/shiny#3510]
I tried to visualize some graph as described below page. https://jokergoo.github.io/InteractiveComplexHeatmap/articles/deseq2_app.html

When I run "shinyApp", the error was occured. 
How can I resolve this?

Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'fontawesome-5.13.0'; `directoryPath` = ''
[No stack trace available]

**Comment by cpsievert** [comment]
Thanks for the reprex.

I believe the development version of https://github.com/jokergoo/InteractiveComplexHeatmap has a fix (https://github.com/jokergoo/InteractiveComplexHeatmap/commit/677d2b345849ebcd3078d879dbb202546848e6f9) for the underlying issue (this package was assuming that fontawesome's CSS files are bundled with the `{shiny}` package which is no longer true -- now they're bundled with `{fontawesome}`)
