### ISSUE TITLE
"get_quosure" error with  renderMenu shinydashboard example

### ISSUE THREAD

**Issue by WayneGitShell** [rstudio/shiny#3514]
### System details

Browser Version: Chrome

Output of `sessionInfo()`:

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.7.0          shinydashboard_0.7.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7        crayon_1.4.1      digest_0.6.28     later_1.3.0       mime_0.11        
 [6] R6_2.5.1          jsonlite_1.7.2    lifecycle_1.0.0   xtable_1.8-4      magrittr_2.0.1   
[11] cachem_1.0.6      rlang_0.4.11      fontawesome_0.2.2 promises_1.2.0.1  jquerylib_0.1.4  
[16] bslib_0.3.0       ellipsis_0.3.2    tools_4.1.1       httpuv_1.6.3      fastmap_1.1.0    
[21] compiler_4.1.1    htmltools_0.5.2   sass_0.4.0       

```

```R
library(shinydashboard)
library(shiny)
# ========== Dynamic sidebarMenu ==========
ui <- dashboardPage(
   dashboardHeader(title = "Dynamic sidebar"),
   dashboardSidebar(
     sidebarMenuOutput("menu")
   ),
   dashboardBody()
)
server <- function(input, output) {
   output$menu <- renderMenu({
     sidebarMenu(
       menuItem("Menu item", icon = icon("calendar"))
     )
   })
 }
shinyApp(ui, server)



```

Using R version 4.1.1 on windows with Shiny Version 1.7.0 and Shinydashboard version 0.7.1 I get the following error message: 

The browser greys out and the console shows the following error message: 

Warning: Error in get_quosure: could not find function "get_quosure"
  50: renderMenu
  49: server [#2]
Error in get_quosure(expr, env, quoted) : 
  could not find function "get_quosure"

**Comment by wch** [comment]
Can you try reinstalling shinydashboard with:

```R
install.packages("shinydashboard", type="source")
```

**Comment by WayneGitShell** [comment]
Bug Already reported here: https://github.com/rstudio/shinydashboard/issues/369

**Comment by WayneGitShell** [comment]
> Can you try reinstalling shinydashboard with:
> 
> ```r
> install.packages("shinydashboard", type="source")
> ```

Tried it but doesn't solve issue....

**Comment by cpsievert** [comment]
`remotes::install_github("rstudio/shinydashboard")` should do it now (we'll be submitting to CRAN shortly)

**Comment by WayneGitShell** [comment]
Thanks Carson - do you have an ETA for upload to CRAN? Users of my package don't have the capability to install from GitHub- see for example: https://www.claire.co.uk/projects-and-initiatives/gwsdat

**Comment by wch** [comment]
The new version of shinydashboard (0.7.2) is on CRAN, although at the moment only the source package is available; it will take some time for them to build the binary packages for various platforms. https://cran.r-project.org/web/packages/shinydashboard/

For now, you can install the source package with:

```R
install.packages('shinydashboard', type='source')
```

**Comment by WayneGitShell** [comment]
Thanks Winston.

Wayne
