### ISSUE TITLE
Does `observeEvent` priority value also has an influence on `eventReactive`?

### ISSUE THREAD

**Issue by stla** [rstudio/shiny#3523]
Hello,

  I observed a behavior which is not documented. Consider this app:

```r
library(shiny)

ui <- fluidPage(
  selectInput("slct", NULL, letters[1:3]),
  radioButtons("rad", NULL, c("X", "Y")),
  radioButtons("rad2", NULL, c("K", "L"))
)

server <- function(input, output, session){
  
  observeEvent(input[["slct"]], {
    freezeReactiveValue(input, "rad")
    updateRadioButtons(session, "rad", choices = sample(LETTERS,2L))
  }, priority = 1)

  observeEvent(input[["rad"]], {
    freezeReactiveValue(input, "rad2")
    updateRadioButtons(session, "rad2", choices = sample(LETTERS,2L))
  }, priority = 1)
  
  R <- eventReactive(list(input[["slct"]], input[["rad"]], input[["rad2"]]), {
    print("rrrrrrrrrr")
    print(input[["rad"]])
    print(input[["rad2"]])
    "XXXX"
  })
  
  observe({
    print(R())
    cat("-----------------\n")
  })
  
}
```

Then, when one changes the value of the select input, the reactive conductor reacts only one time.

Now, remove `priority = 1` (or set `priority = 0`). Then, when one changes the value of the select input, the reactive conductor reacts two times.

Does that mean that a priority value >0 of an `observeEvent` imply that this `observeEvent` is executed before any reactive conductor? Have I the good understanding?

**Comment by jcheng5** [comment]
I'm going to go ahead and close this issue as there's no bug or feature request here, I don't think. But feel free to continue the discussion, and reopen if you disagree.

**Comment by stla** [comment]
Thanks Joe for the explanations. Yes this is a good thing. I used this technique to solve a double reactivity issue in my app.
