### ISSUE TITLE
Fire js event when bind/unbind inputs

### ISSUE THREAD

**Issue by dipterix** [rstudio/shiny#3545]
I'm thinking about applying js globally to the shiny elements. One thing I notice is that some elements from `shiny` are added on demand. If the js script is initialized before these elements, then the modification cannot be fulfilled. 

Right now I wrote a loop to actively monitor the DOM changes. However, this approach is quite heavy. It would be great if shiny can fire events when bind/unbind actions occur. This will allow us to passively listen to the changes.

Thanks : )

**Comment by ismirsehregal** [comment]
The JS events you ask for are already available: shiny:bound & shiny:unbound

https://shiny.rstudio.com/articles/js-events.html

> When an input or output is bound to Shiny, the event shiny:bound is triggered. Similarly, there is a shiny:unbound event after an input/output is unbound. In these events, the event object has properties binding (the input/output binding object) and bindingType (may be 'input' or 'output' depending on whether the binding is for an input or an output).

**Comment by dipterix** [comment]
@ismirsehregal Thank you, this is exactly what I was looking for!
