### ISSUE TITLE
renderPlot blinking with TreeMap 

### ISSUE THREAD

**Issue by xingxin** [rstudio/shiny#357]
hi guys,

Really need some advise here. So I've created an app that displays some data in the form of a treemap (used the treemap package in R). The input data changes every 1 sec through the invalidaeLater method. It works fine when I create just 1 layer of parent, as the heatmap changes smoothly each second. However, once I add another layer of parent  node, the plot starts blinking. My guess is more drawings slow the renderPlot function down, but not sure. Have you guys encountered similar problems before or have any ideas why this is happening? Thanks in advance!

**Comment by ttzzhh** [comment]
Hi, I think you can use the print() function and set the newpage argument to F so that shiny displays the old plot while rendering the new one and you won't see it blink.

For example, if you have a ggplot called g, instead of returning g to renderplot you can do print(g,newpage=F)
