### ISSUE TITLE
Dynamic tabPanel title prevents tabPanel bookmarking

### ISSUE THREAD

**Issue by pasipasi123** [rstudio/shiny#3577]
Restoring a bookmarked `tabsetPanel()` Shiny app state works by looking up the `tabsetPanel` `id` and titles of the `tabPanel()`s. This causes problems when there's anything else than plain text in the `tabPanel()` title, eg. a dynamic title text with `textOutput()`, because then the saved value will have a div in it, thus the opened tab can't be restored and in fact no tab will be opened on restore.

I think the fix would be to instead use a `tabPanel()` id. It seems an automatically generated `id` value exists but instead `data-value` is used.

### System details

Output of `sessionInfo()`:

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=Finnish_Finland.1252  LC_CTYPE=Finnish_Finland.1252    LC_MONETARY=Finnish_Finland.1252 LC_NUMERIC=C                    
[5] LC_TIME=Finnish_Finland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.7.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8       digest_0.6.29    withr_2.4.3      later_1.3.0      mime_0.12        R6_2.5.1         jsonlite_1.7.3   lifecycle_1.0.1  xtable_1.8-4    
[10] magrittr_2.0.1   cachem_1.0.6     rlang_0.4.12     promises_1.2.0.1 jquerylib_0.1.4  bslib_0.3.1      ellipsis_0.3.2   tools_4.1.0      httpuv_1.6.5    
[19] fastmap_1.1.0    compiler_4.1.0   htmltools_0.5.2  sass_0.4.0      
```

### Example application 

This is a slightly modified script from the [multiple bookmark buttons example](https://shiny.rstudio.com/articles/bookmarking-state.html).

```R
library(shiny)

ui <- function(request) {
  fluidPage(
    tabsetPanel(id = "tabs",
                tabPanel(title = textOutput("title1"),
                         textInput("change1", "Change title", "Title 1"),
                         checkboxInput("chk1", "Checkbox 1"),
                         bookmarkButton(id = "bookmark1")
                ),
                tabPanel("Two",
                         checkboxInput("chk2", "Checkbox 2"),
                         bookmarkButton(id = "bookmark2")
                )
    )
  )
}

server <- function(input, output, session) {

  output$title1 <- renderText(input$change1)

  # Need to exclude the buttons from themselves being bookmarked
  setBookmarkExclude(c("bookmark1", "bookmark2"))

  # Trigger bookmarking with either button
  observeEvent(input$bookmark1, {
    session$doBookmark()
  })
  observeEvent(input$bookmark2, {
    session$doBookmark()
  })
}

shinyApp(ui, server, enableBookmarking = "url")

```

The bookmark url will look like this: `http://127.0.0.1:7188/?_inputs_&change1=%22Title%201%22&tabs=%22%3Cdiv%20id%3D%5C%22title1%5C%22%20class%3D%5C%22shiny-text-output%5C%22%3E%3C%5C%2Fdiv%3E%22&chk1=false&chk2=false`

**Comment by cpsievert** [comment]
IIUC providing a character string to `tabPanel()`'s `value` argument should fix the issue?

**Comment by pasipasi123** [comment]
> IIUC providing a character string to tabPanel()'s value argument should fix the issue?

Thanks for your comment. Yes. D'oh! I'll close this issue.
