### ISSUE TITLE
missing bacckground color for checkboxGroupButtons for reactive input choices

### ISSUE THREAD

**Issue by meharjiarumilli** [rstudio/shiny#3587]
Hi,

```
> packageVersion("shiny")
[1] ‘1.6.0’

```

The input choices for `checkboxGroupButtons` are to be read from reaciveFileReader object:

`view_data <<- reactiveFileReader(intervalMillis=10000, NULL, "viewdata.rds", readFunc = readRDS)
`

And the UI code for checkboxGroupButtons:

```
checkboxGroupButtons(
              inputId = "select_system",
              label = h4("Select system"),
              choices = character(0),
              selected = "quota",
              status = "success",
              individual = TRUE,
              checkIcon = list(
                yes = icon("ok",
                         lib = "glyphicon")
              )
            )
```

Server side code for reactive input choices to checkboxGroupButtons. 

```
choices_select_system <- reactive({
  select_systems <- unique(view_data()$name)
  select_systems
})

observe({
  updateCheckboxGroupButtons(session = session,
                    inputId = "select_system",
                    choices = choices_select_system(), selected = "quota")
})
```

The above code snippets do work as expected in updating the CheckboxGroupButtons from the reactive object `view_data()`.  However in the UI, the background color (green) for checkboxGroup buttons has disappeared and also the checkIcons are missing.

The background color and the checkIcons appeared when static `choices` for `checkboxGroupButtons` were used but not when reactive/dynamic choices as shown in the above code snippet were used.

Could someone help if im missing any argument or so in case of reactive input choices?

**Comment by jcheng5** [comment]
Oh, looking at this closer, it's using `checkboxGroupButtons`; I think you need to file this on https://github.com/dreamRs/shinyWidgets, as that functions belongs to that package.
