### ISSUE TITLE
reactiveUI does not always correctly render sliders

### ISSUE THREAD

**Issue by nicolaromano** [rstudio/shiny#36]
When creating a `sliderInput` through `reactiveUI` the slider is not rendered properly unless another slider has already been created in ui.R.

(This was seen under Fedora Core 16 with both Firefox 16.0.2 and Google Chrome  23.0.1271.64)

How to reproduce:

**ui.R**

``` R
library(shiny)

shinyUI(pageWithSidebar(
  headerPanel("Reactive UI test"),
  sidebarPanel(
              uiOutput("reactiveSlider")
              ),
  mainPanel ()
  ))
```

**server.R**

``` R
library(shiny)

shinyServer( function(input, output)
  {
  output$reactiveSlider <- reactiveUI(function()
    {
    sliderInput("reactiveSlider", "Choose a value:", 
                 min=1, max=10, step=0.5, value=2, ticks=T)   
    })
  })
```

This results in `reactiveSlider` being rendered as a text input rather than a slider.
Simply adding a slider to ui.R, e.g.

``` R
sliderInput("dummySlider", "some value", min=0, max=100, value=10) 
```

is sufficient to solve the issue.
A temporary workaround is then to add an invisible slider to ui.R

``` R
conditionalPanel
   (
   condition = '0==1',
   sliderInput("dummyslider", "", min=0, max=1, value=0)
   )
```

---

It seems this somehow derives from missing CSS instances, but I can't really understand why.
Even in the first case FireBug reports `http://localhost:8100/shared/slider/css/jquery.slider.min.css` as being loaded.
When a second slider is added in ui.R a second instance of the CSS appears (same file, just a second instance).
A third instance is not added if adding other sliders in ui.R but a new instance of the CSS is loaded for every `reactiveUI` slider component. If you add a few `reactiveUI` sliders you can see them rendered as text inputs and then change into sliders one by one as the CSS files get loaded. 

So I guess what happens is that if a slider is present in ui.R the slider CSS is loaded.
Reactive UI components then load the CSS if needed.

Note that if you just add two `reactiveUI` sliders and no slider in ui.R the problem reappears, but two instances of the CSS are loaded anyway.

**Comment by kkmann** [comment]
still an issue for me - really weird!
