### ISSUE TITLE
R 4.2.0: Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by dmenne** [rstudio/shiny#3626]
After installing R 4.2.0 on Windows, I get 

`Fontconfig error: Cannot load default config file`

on every Shiny program creating a plot. Some old-style default font is used for plotting (Chrome Browser).  No warning when ggplot or default plots are created/printed without shiny.

![2022-04-29 09_21_31-127 0 0 1_6828](https://user-images.githubusercontent.com/506275/165900936-3bb874c7-690c-4740-823f-b45991368fa4.png)

I am aware that this message is not coming from Shiny, but rather from the operating system, and it has to do with some path settings (https://askubuntu.com/questions/492033/fontconfig-error-cannot-load-default-config-file). The reported cases were old and all referred to Linuxes.

I also tested with an Ubuntu installation, where the warning does not come up.

**Comment by WouterDH-UZL** [comment]
I'm having the same issue with R 4.2.0. Seems to be related to Cairo specifically, as the app no longer triggers the warning message when using `options(shiny.usecairo = FALSE)`. Plots look worse when disabling it though.

**Comment by dmenne** [comment]
ragg example added. Looks ok, but I would feel more future-proof with a standard package.

**Comment by jessekps** [comment]
It also happens in rmarkdown documents on a windows computer. A workaround for me was running:
`showtext::showtext_auto()` before making any plots.

Which is fine for reports and stuff but I rather not add an extra dependency in my packages.
