### ISSUE TITLE
Error in ..stacktraceon..({ : object 'supermarket_sales' not found

### ISSUE THREAD

**Issue by chantalvdaker** [rstudio/shiny#3642]
Hello, i'm working on a groupproject for school and we're starting to learn the language R. I cannot figure out why i can't run the app. the app and the data are in the same map and there is no error in the way i wrote the name of the data. 

library(tidyverse)
library(shiny)
library(plotly)
library(dplyr)
library(lubridate)

supermarket_sales
view(supermarket_sales)

supermarket_data <-supermarket_sales
supermarket_data <- read.csv("supermarket_sales.csv") 

class(supermarket_data$Date)

supermarket_data$Date <- mdy(supermarket_data$Date) 
class(supermarket_data$Date) 

supermarket_data$week_day <- wday(supermarket_data$Date, label = TRUE)

levels(supermarket_data$week_day)

#grafiek 1
supermarket_data %>%
  group_by(Branch, week_day) %>%
  summarize(total_sales = n())

supermarket_sales_per_branch_weekday <- supermarket_data %>%
  group_by(Branch, week_day) %>%
  summarize(avg_Total = mean(Total,
                             qty = n))

supermarket_sales_per_branch_weekday %>%
  ggplot(mapping = aes(x = week_day,
                       y = avg_Total,
                       fill = Branch)) +
  geom_col(position = 'dodge') +
  scale_x_discrete(name = 'Week_day') + 
  scale_y_continuous(name = 'Count') +
  ggtitle(label = 'number of sales per week day')

#grafiek 2
supermarket_data %>%
  group_by(Gender) %>%
  summarize(total_sales = n())

supermarket_sales_by_gender_weekday <- supermarket_data %>%
  group_by(Gender, week_day) %>%
  summarize(avg_Total = mean(Total,
                             qty = n))

supermarket_sales_by_gender_weekday %>%
  ggplot(mapping = aes(x = week_day,
                       y = avg_Total,
                       fill = Gender)) +
  geom_col(position = 'dodge') +
  scale_x_discrete(name = 'Total') + 
  scale_y_continuous(name = 'Count') + 
  ggtitle(label = 'Histogram of total sales amount')

#in shiny zetten

# Define UI for application that draws a histogram
ui <- fluidPage(

    titlePanel("Number of sales per weekday for each brand"),
        sidebarLayout(
        sidebarPanel(
           selectInput("select_branch", label = "which brand?", choices = c('A', "B", "C"))
        ),

        mainPanel(
           plotOutput("distPlot")
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {

    output$distPlot <- renderPlot({
       supermarket_sales_per_branch_weekday %>%
        filter(Branch %in% input$select_branch) %>%
        supermarket_data %>%
        ggplot(mapping = aes(x = week_day,
                             y = avg_Total,
                             fill = Branch)) +
        geom_col(position = 'dodge') +
        scale_x_discrete(name = 'Week_day') + 
        scale_y_continuous(name = 'Count') +
        ggtitle(label = 'number of sales per week day')

        # draw the histogram with the specified number of bins
        hist(x, breaks = bins, col = 'darkgray', border = 'white')
    })
}

# Run the application 
shinyApp(ui = ui, server = server)

**Comment by jcheng5** [comment]
This isn't really an appropriate forum for homework questions, it's more to report issues with the framework itself, so I'm going to close this.

You can probably fix your problem by removing these lines from the top:

```
supermarket_sales
view(supermarket_sales)

supermarket_data <-supermarket_sales
```

If they ever worked, I'm sure they were left over from some other session where you actually defined supermarket_sales; because there's nothing in this script that does.
