### ISSUE TITLE
bslib messes up with the pagination in renderDataTable() 

### ISSUE THREAD

**Issue by acastroaraujo** [rstudio/shiny#3643]
The pagination option used with `dataTableOutput()` and `renderDataTable()` gets messed up when I use `bs_theme()`.

For example:

```R
library(shiny)
library(bslib)

ui <- fluidPage(
  theme = bslib::bs_theme(),
  dataTableOutput("table")
)

server <- function(input, output, session) {
  output$table <- renderDataTable(
    expr = mtcars, options = list(pageLength = 10)
  )
}

shinyApp(ui, server)
```
<img width="403" alt="Screen Shot 2022-05-23 at 2 33 20 PM" src="https://user-images.githubusercontent.com/7806658/169884592-2c3bd1e6-7b40-4acb-832b-d8f2a996bd3c.png">

This gets fixed when I use the DT package explicitly.

For example:

```R
library(shiny)
library(DT)
library(bslib)

ui <- fluidPage(
  theme = bslib::bs_theme(),
  DT::dataTableOutput("table")
)

server <- function(input, output, session) {
  output$table <- DT::renderDataTable(
    expr = mtcars, options = list(pageLength = 10)
  )
}

shinyApp(ui, server)
```

<img width="329" alt="Screen Shot 2022-05-23 at 2 34 39 PM" src="https://user-images.githubusercontent.com/7806658/169884560-c3bbf0ea-1afc-4c4d-bcb8-bd4aa651b32a.png">

I assume this is a bug.

**System details:**

R version 4.1.3 (2022-03-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.6.2

**Comment by jcheng5** [comment]
Please use DT and not shiny::renderDataTable, the latter has been superseded for years. @cpsievert maybe this is a reason for us to deprecate it much more strongly?

**Comment by jcheng5** [comment]
Oh, right, we already print a deprecation message. I'll close this then.
