### ISSUE TITLE
Repeating download same plot as pdf file error

### ISSUE THREAD

**Issue by bioinformatics-takara** [rstudio/shiny#3646]
I got an error when I repeatedly download a plot as pdf file from same tabPanel by clicking downloadButton.
The downloaded pdf file is correct by first time. However, by repeating the operation, the second time downloaded file has less size and can not be opened by pdf reader.

**Comment by wch** [comment]
Can you provide a reproducible example?

**Comment by bioinformatics-takara** [comment]
The issue has been fixed. Thanks
