### ISSUE TITLE
The link to the contibutor guidelines on the main shiny website is dead

### ISSUE THREAD

**Issue by dvg-p4** [rstudio/shiny#3658]
The last link on the page https://shiny.rstudio.com/contribute/ , marked "contributing guidelines", points to https://github.com/rstudio/shiny/blob/main/CONTRIBUTING.md , which is a dead link. The contributing guidelines now appear to be at https://github.com/rstudio/shiny/blob/main/.github/CONTRIBUTING.md -- whoever the webmaster is for shiny.rstudio.com should probably update that.

**Comment by wch** [comment]
Thanks for the report! I've fixed the link and it will be deployed soon.
