### ISSUE TITLE
isTruthy could handle missing function arguments

### ISSUE THREAD

**Issue by SigurdJanson** [rstudio/shiny#3681]
Is there a reasony why `isTruthy` does not handle missing function arguments? I searched for an issue but I did not find anything.

Example:
```r
 x <- function(y) {
  if (missing(y)) print ("Missing")
  if (!shiny::isTruthy(y)) print("Falsy")
}

x()
#>"Missing"
#> Error in shiny::isTruthy(y) : argument "y" is missing, with no default

x(NA)
#> [1] "Falsy"
```

The error is what I don't want and don't expect. Maybe I did not pay attention. In this case please point me to a source that explains it.  Or maybe it cannot be done riliably? Anyway, from a very subjective point of view "missing" does not seem "truthy" to me.

The reason why I request it? I try to put every little piece of logic into a function so that I have the chance to write unit tests. Reactive expressions are a lot more difficult to test. For higher robustness I let the functions test all it's arguments. And it would be much easier (for me) if `isTruthy` would just identify missing arguments.

If my needs are isolated needs, feel free to close the issue.

The solution would be kinda simple. I was sceptical if that even works but a first test confirmed that I can pass a missing argument on to `isTruthy` where it is identified as missing.

```r
myTruthy <- function (x) 
{
  if (missing(x)) #probably has to be the first or we might get an exception below
    return(FALSE)
  if (inherits(x, "try-error")) 
    return(FALSE)
  if (!is.atomic(x)) 
    return(TRUE)
  if (is.null(x)) 
    return(FALSE)
  if (length(x) == 0) 
    return(FALSE)
  if (all(is.na(x))) 
    return(FALSE)
  if (is.character(x) && !any(nzchar(stats::na.omit(x)))) 
    return(FALSE)
  if (inherits(x, "shinyActionButtonValue") && x == 0) 
    return(FALSE)
  if (is.logical(x) && !any(stats::na.omit(x))) 
    return(FALSE)
  return(TRUE)
}

x <- function(y) {
  if (missing(y)) print ("Missing")
  if (!myTruthy(y)) 
    print("Falsy")
  else
    print("indubitably")
}

x()
#> [1] "Missing"
#> [1] "Falsy"
x(NA)
#> [1] "Falsy"
x(1)
#> [1] "indubitably"
```

<sup>Created on 2022-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by cpsievert** [comment]
The main intention of `isTruthy()` is to check truthiness of `input` values, which should never be missing in the same way function arguments are missing, so it's not 100% clear what the right behavior should be in this case. Also, FWIW, this problem isn't exclusive to `isTruthy()`...if you evaluate a missing argument you're always going to get error. It seems the best solution for use case is to use a simple wrapper like this?

```r
is_truthy <- function(y) {
  !missing(y) && shiny::isTruthy(y)
}
```

**Comment by wch** [comment]
To add on to @cpsievert's comment:
I don't mean to be flippant, but the reason `isTruthy()` doesn't check for missingness is because `isTruthy()` is meant to check for truthy _values_, not whether a value is missing. Missingness is distinct concept from truthiness, and the purpose of the function is to check for truthiness.

I would also argue that one should avoid using `missing()` checks whenever possible in code, because missingness can be difficult to use programmatically. Instead, it's best to use some default value like `NULL` to indicate that a value is missing in the function call.
