### ISSUE TITLE
Feature Request: renderTable digits argument to accept reactive value without recalculating table

### ISSUE THREAD

**Issue by GuestJim** [rstudio/shiny#3696]
A feature I like to have is the ability to change the rounding for a table within the applet itself. While this is possible currently, it is a bit cumbersome because **renderTable** does not natively accept reactive values for the **digits** argument, and because it will recalculate the table when changing it as well.
Here's an example with both my solution of calculating the table outside of an observeEvent, and what happens if you do not do that:
```
shinyApp(
	ui	=	fluidPage(
		numericInput('roundTerm',	label = "Rounding term",	value = 2,	step = 1),
		fluidRow(
			column(3, tableOutput('stable')),
			column(3, tableOutput('calc'))
		)
	),
	server	=	function(input, output)	{
		STABLE	=	runif(4)
		observeEvent(input$roundTerm,	{
		output$stable	<-	renderTable(data.frame("Stable" = STABLE),	digits = input$roundTerm)
		
		output$calc	<-	renderTable(data.frame("Recalculated" = runif(4)),	digits = input$roundTerm)
		})
	}
)
```
The observeEvent can be dropped by using `digits = reactive(input$roundTerm)` but I personally prefer the method in my example. Regardless, my request is to allow **digits** to accept a reactive natively (so neither **reactive** nor **observeEvent** are needed) and that when this reactive value changes, it does not recalculate the table. (Sometimes the tables I am working with take a moment to calculate, which is why I wish to specifically avoid recalculating them for what is only a visual change.) In other words, I would want both the **stable** and **calc** tables in this example to show identical behaviors and without needing to explicitly identify input$roundTerm as a reactive.

**Comment by jcheng5** [comment]
Hi @GuestJim, I highly recommend you not use `observeEvent` to make `digits` dynamic. Please see [this video](https://www.rstudio.com/resources/shiny-dev-con/reactivity-pt-1-joe-cheng/) starting at 17:20. If you have a specific objection to using `digits = reactive(input$roundTerm)` I'd be interested to hear it.

You can "stabilize" your table by extracting the code in the `renderTable` that actually generates the data frame, and make that a separate reactive expression.

```r
shinyApp(
  ui = fluidPage(
    numericInput('roundTerm', label = "Rounding term", value = 2, step = 1),
    fluidRow(
      column(3, tableOutput('stable')),
      column(3, tableOutput('calc'))
    )
  ),
  server = function(input, output) {
    STABLE <- runif(4)
    output$stable <- renderTable(data.frame("Stable" = STABLE), digits = reactive(input$roundTerm))
    
    df <- reactive({
      data.frame("Recalculated" = runif(4))
    })
    output$calc <- renderTable(df(), digits = reactive(input$roundTerm))
  }
)
```

I can totally see a case for `renderTable` separating your data-frame-generating expression into a reactive expression on your behalf, but I don't think it's worth making that change at this point, sorry. The workaround is quite idiomatic Shiny (the use of reactive expressions to indicate the granularity of caching).

**Comment by GuestJim** [comment]
Hello @jcheng5,

I don't have any functional objection to using `digits = reactive(input$roundTerm)` as usually it is just a personal preference to have shorter lines. (So completely idiosyncratic.) Also I didn't realize that worked until I tried it recently because observeEvent seemed a more natural solution, at least based on the name. A consequence of being self-taught at this is some quirks are not immediately obvious. (Forgive me but to my perspective having an argument, `digits`, that does not accept a reactive value, such as `input$roundTerm`, suddenly working by explicitly stating it is a reactive is not an obvious solution, hence why I call it a quirk.)

As to the second point, I can completely understand my use cases are not common enough to warrant an immediate change, but I do think it is a reasonable enough situation for future consideration. At least I found this ability to live adjust the rounding without recalculating the table useful. Some of my tables are large enough to take a while to recalculate, or can be dependent on enough inputs that constantly recalculating while tweaking the inputs is undesirable.

**Comment by jcheng5** [comment]
I totally understand why it's unintuitive that `digits = input$roundTerm` doesn't react but `digits = reactive(input$roundTerm)` does. The difference is, the first form provides _a value_ to `digits`, while the second provides _a way to access_ `digits`. It's like the difference between `a` and `b` in this snippet:

```r
> a <- Sys.time()

> b <- function() { Sys.time() }

> a
[1] "2022-09-09 12:44:35 PDT"

> b()
[1] "2022-09-09 12:44:35 PDT"

> Sys.sleep(5)

> a
[1] "2022-09-09 12:44:35 PDT"

> b()
[1] "2022-09-09 12:44:40 PDT"
```

As a matter of fact, `digits = function() {input$roundTerm}` would also work just the same as `digits = reactive(input$roundTerm)`. What's important is providing something more function-like than value-like, and `reactive()` happens to be a convenient way to create a function out of an expression.

I'm just realizing that the docs for `renderTable` don't even hint that you can do this (provide a function instead of a value). I'll file a separate issue for that.

**Comment by jcheng5** [comment]
For the second point, I just want to make sure we're crystal clear that you _can_ tweak the inputs without recalculating the table--you just need to put the logic for the table in a separate reactive expression.

**Comment by GuestJim** [comment]
Updating the documentation sounds good to me.

As to clarity on the second point, what you describe I believe is what I'm already doing. I just wish it could be more native to`renderTable` but I completely recognize that would be a significant change to it, and potentially not worth it if too few people would take advantage of it.

I do have one (hopefully) quick question though, concerning what you said earlier about recommending `reactive(input$roundTerm)` over `observeEvent`. If the situation involves multiple tables that are to follow `input$roundTerm` would that be a time to using `observeEvent` would be better? My thinking would be that involves one reaction triggering multiple events, which would be more efficient than a reaction for each table, but I am not certain on some of the inner workings and if each use of `reactive(input$roundTerm)` would be a separate check.

**Comment by GuestJim** [comment]
I just had a random idea to try something, and I'm rather surprised it worked, but might be worth documenting as well. I found a way to pass the `input$roundTerm` into a server module, preserving reactivity, but without needing to make it an argument, and it works for other objects too.
```
testServer	<-	function(name)	{
	roundTerm	<-	reactive(input$roundTerm)
	moduleServer(name, function(input, output, session)	{
		output$TABLE	<-	renderTable(TABLE,	digits = reactive(roundTerm))
	})}
```
You can assign the external object, such as `input$roundTerm`, in the function but outside of moduleServer and the module will have access to whatever you assign it to. Little annoying having to use `reactive` twice like this, but still, this ability to pass in objects other than arguments could be very useful for me.

Only though to try this because of the "Inside of the module function, it can use parameters from the outside function" statement from the article on [Modularizing Shiny app code](https://shiny.rstudio.com/articles/modules.html) but I think that was meant more to refer to the outer functions arguments, rather than whatever you put into that function.

Regardless, I wanted to share this because this bridging of `input$roundTerm` into the module without needing to constantly make it an argument is something that should help my situation significantly. I've already confirmed reactivity can be passed into the module precisely as I desire. Also I have situations where I want normal data objects to be given to the module, and this is cleaner than making them an argument.
