### ISSUE TITLE
removing the priority of the `ragg` package in the `shiny:::startPNG` - crashing the R session

### ISSUE THREAD

**Issue by Polkas** [rstudio/shiny#3704]
linked to https://github.com/r-lib/ragg/issues/116
very important it seems to not be a problem of arm64 only.

Please consider removal of the priority of the `ragg` package in the `shiny::startPNG`.
The `ragg` package is causing a hard crash of the R session and unfortunately maintainer seems to NOT have time for fixes.

In my opinion the  core R  grDevices seems to be a much better choice, at least regarding stability.

**Comment by cpsievert** [comment]
You can set `options(shiny.useragg = FALSE)` to revert to the old behavior

**Comment by Polkas** [comment]
Yes, I know. Still it is not obvious to do so each time or putting it to .Rprofile.
I feel the default shiny should be as stable as possible.
It is only my feeling, feel free to close the issue.

**Comment by jcheng5** [comment]
@Polkas Are you saying this is causing a crash with valid inputs? Or only when you somehow end up with a plot whose width or height is `NULL`?

**Comment by jcheng5** [comment]
I can reproduce the crash when using a NULL value for height or width. For sure we should validate these arguments in our function (and of course it would be great if ragg would check them too instead of segfaulting).
