### ISSUE TITLE
unused argument (lib = "font-awesome")

### ISSUE THREAD

**Issue by BirongZhang** [rstudio/shiny#3711]
Dear all,

Thanks for developing such a useful tool!

I found an icon here: https://fontawesome.com/search?q=covid&o=r, and I wanted to use it like this: infoBox(title = " ", width = 4, icon = icon("viruses"), lib="font-awesome"). But I got this error: unused argument (lib = "font-awesome"). What should I do? 

Any advices would be highly appreciated! Many thanks!

Best regards,
Birong

**Comment by wch** [comment]
It should probably be:

```R
infoBox(title = " ", width = 4, icon = icon("viruses", lib="font-awesome"))
```

**Comment by BirongZhang** [comment]
> It should probably be:
> 
> ```r
> infoBox(title = " ", width = 4, icon = icon("viruses", lib="font-awesome"))
> ```

What did I do???😖
Thanks for your efficient reply! It works well now.
