### ISSUE TITLE
dialogViewer: allow dimensions to go right up until the perimeter of the IDE instead of forcing ~150px margin

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#3722]
When building shiny gadgets, it's common to use `dialogViewer()` to run them inside the IDE. However, one frustrating feature of `dialogViewer()` is that it seems to not allow the viewer to come within ~70-80 pixels of the IDE (from my own testing).

For example, the following code

```r
shiny::runGadget(shiny::shinyApp("test", function(input, output) {}), viewer = shiny::dialogViewer("test", 3000, 3000))
```

Results in this:

![image](https://user-images.githubusercontent.com/952340/199340875-9d00d8d6-c616-4733-b91d-af6ed7ae5c61.png)

In a desktop IDE it's not too bad, but often when running a gadget inside an RStudio Server (inside a browser), those extra pixels make a difference. I often end up making a gadget run in a separate browser window instead of in the IDE just because of this. If `dialogViewer()` allowed me to get right up until the edges of the IDE, it would be much more useable.

**Comment by wch** [comment]
I think this is an issue for the IDE (https://github.com/rstudio/rstudio/issues).

**Comment by daattali** [comment]
Will move.
This reminds me, I think you guys need to buy out this user https://github.com/posit :)
