### ISSUE TITLE
NULL width/height causing "segfault" R exit in renderPlot

### ISSUE THREAD

**Issue by slodge** [rstudio/shiny#3735]
### System details

Browser Version: Not applicable

Output of `sessionInfo()`:

```
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8    LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9           pillar_1.8.1         compiler_4.2.0       later_1.3.0          urlchecker_1.0.1     prettyunits_1.1.1    profvis_0.3.7       
 [8] remotes_2.4.2        tools_4.2.0          testthat_3.1.5       digest_0.6.30        pkgbuild_1.3.1       pkgload_1.3.2        memoise_2.0.1       
[15] lifecycle_1.0.3      tibble_3.1.8         pkgconfig_2.0.3      rlang_1.0.6          shiny_1.7.3.9001     cli_3.4.1            rstudioapi_0.14     
[22] yaml_2.3.6           curl_4.3.3           fastmap_1.1.0        withr_2.5.0          stringr_1.4.1        desc_1.4.2           vctrs_0.5.1         
[29] fs_1.5.2             htmlwidgets_1.5.4    devtools_2.4.5       rprojroot_2.0.3      glue_1.6.2           R6_2.5.1             processx_3.8.0      
[36] fansi_1.0.3          sessioninfo_1.2.2    callr_3.7.3          purrr_0.3.5          magrittr_2.0.3       ps_1.7.2             promises_1.2.0.1    
[43] ellipsis_0.3.2       htmltools_0.5.3.9002 usethis_2.1.6        mime_0.12            xtable_1.8-4         renv_0.16.0          httpuv_1.6.6        
[50] utf8_1.2.2           stringi_1.7.8        miniUI_0.1.1.1       cachem_1.0.6         crayon_1.5.2         brio_1.1.3    
```

### Example application *or* steps to reproduce the problem

Sorry - **not** got an easily reproducible sample right now.

The steps we have depend on internal code that I can't share - and I'm still debugging that HTML/javascript

### Describe the problem in detail

Basically what I believe is happening is that

- my plot area has **zero** `getBoundingClientRect().height` - so is not sending height and width from:

```
  function doSendImageSize() {
    $(".shiny-image-output, .shiny-plot-output, .shiny-report-size").each(
      function () {
        const id = getIdFromEl(this),
          rect = this.getBoundingClientRect();

        if (rect.width !== 0 || rect.height !== 0) {
          inputs.setInput(".clientdata_output_" + id + "_width", rect.width);
          inputs.setInput(".clientdata_output_" + id + "_height", rect.height);
        }
      }
    );
```
https://github.com/rstudio/shiny/blob/20cc8e26b5e366286caf47f65d9670fbe45412dd/srcts/src/shiny/init.ts#L281

- but has **non-zero** `offsetHeight`, so is sending `hidden: false` from:

```
  $(".shiny-bound-output").each(function () {
    const id = getIdFromEl(this);

    if (isHidden(this)) {
      initialValues[".clientdata_output_" + id + "_hidden"] = true;
    } else {
      lastKnownVisibleOutputs[id] = true;
      initialValues[".clientdata_output_" + id + "_hidden"] = false;
    }
  });
 ```
https://github.com/rstudio/shiny/blob/20cc8e26b5e366286caf47f65d9670fbe45412dd/srcts/src/shiny/init.ts#L326

This is causing NULL to be returned in 

```
  getDimsDefault <- function() {
    width <- widthWrapper()
    height <- heightWrapper()

    # Note that these are reactive calls. A change to the width and height
    # will inherently cause a reactive plot to redraw (unless width and
    # height were explicitly specified).
    if (width == 'auto')
      width <- session$clientData[[paste0('output_', outputName, '_width')]]
    if (height == 'auto')
      height <- session$clientData[[paste0('output_', outputName, '_height')]]

    list(width = width, height = height)
  }
```
https://github.com/rstudio/shiny/blob/20cc8e26b5e366286caf47f65d9670fbe45412dd/R/render-plot.R#L109

When these null get passed into C++ code inside [drawPlot](https://github.com/rstudio/shiny/blob/20cc8e26b5e366286caf47f65d9670fbe45412dd/R/render-plot.R#L226) then the R.exe process crash follows - giving me very little detail about what happened.

I'd like to propose this as two separate issues:

1 I'd love for the code should protect against these NULLs - as tracking down R crashes in Shiny is time consuming unpleasant
2 I'm not entirely about this - but it might be nice to see if the shiny javascript should be consistent in its use of `offsetHeight` and `getBoundingClientRect().height` - I guess there is a reason to use one over the other in each case... and I'm not entirely sure about this... I suspect some investigation and/or expert input might be needed!

**Comment by cpsievert** [comment]
Just curious, can you replicate the issue with the current CRAN version of Shiny? And can you share with us the error that gets generated (of course, a reproducible example, even if sent through email would be _very_ helpful)?

> my plot area has zero `getBoundingClientRect().height` and non-zero offsetHeight

Interesting, if that is the case, could it be that a CSS transform could explain the difference ([as suggested in this article](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements))?

Either way, I like the idea of consistently using `getBoundingClientRect()` over `offsetHeight`, but I'm not sure that will solve the `NULL` sizing issues

**Comment by slodge** [comment]
Yes - this was found in the cran version originally.

There is no error message - just a very abrupt R exit.

With shiny.trace enabled I can see the client data arriving with the plot
output showing the output is not hidden - but with no width or height sent.

**Comment by slodge** [comment]
The more I debug into this... the more confused I get :)

The more I look, the less I think this has to do with https://github.com/rstudio/shiny/commit/20cc8e26b5e366286caf47f65d9670fbe45412dd 

I think this is more generally down to our custom elements and custom markdown template (built off flexdashboard with no bootstrap off it) somehow interacting weirdly with the `hidden` and `sendImageSizeFns` functionality in shiny.

Regardless of this, I think the `null` protection around the image plotting are very much worthwhile (those crashes were unpleasant to locate)... but I'll hold off any suggestions around the `getBoundingClientRect` changes - apologies if I led anyone down the wrong rabbit hole there!
