### ISSUE TITLE
Allow users to send custom messages within JavaScript

### ISSUE THREAD

**Issue by dipterix** [rstudio/shiny#3760]
Currently the message handlers registered via `Shiny.addCustomMessageHandler` can be called via `session$sendCustomMessage()` in R. Is it possible to send custom messages in JavaScript directly?

Something like `Shiny.sendCustomMessage(type, json/object)` ? I found `Shiny.shinyapp.dispatchMessage` very close to what I just asked for, but not sure how to use it.

Best.

**Comment by cpsievert** [comment]
Yea, you're probably looking for [`Shiny.setInputValue("foo", "bar", {priority: "event"})`](https://shiny.rstudio.com/articles/communicating-with-js.html)
