### ISSUE TITLE
Chaining gadgets breaks RStudio and shiny behaviour

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#3784]
Usecase: after a gadget completes and returns its value, I want to launch another gadget.  Here's basic example code (taken from [SO](https://stackoverflow.com/questions/64242967/how-to-run-a-shiny-app-on-ending-a-shiny-app)):

```r
library(shiny)

myGadget <- function() {
  
  ui <- fluidPage(
    actionButton("done", "done"),
    actionButton("cancel", "cancel")
  )
  
  server <- function(input, output, session) {
    observeEvent(input$done, {
      session$onSessionEnded(function() {
        myGadget()
      })
      stopApp()
    })
    observeEvent(input$cancel, {
      stopApp()
    })
  }
  
  runGadget(ui, server)
}
```

Run `myGadget()` in the console. If you click the "cancel" button the the gadget exits normally, but "done" will kill the gadget and re-launch it.

However, when it's relaunched, there is no red stop button in RStudio to stop the app, and the console shows `>` as if the process isn't busy. 

If you use a dialogViewer, then the problem is worse (add `viewer = dialogViewer("test")` argument to the `runGadget()` line). Now when the gadget is re-launched, the same issues happen, but also if you click on the "x" at the top right of the dialog viewer, the app will close but the console will be frozen. You need to terminate RStudio to be able to get back to work.

**Comment by jcheng5** [comment]
I would try it the way you wrote it up here: https://stackoverflow.com/questions/75567757/chaining-shiny-gadgets-how-to-run-a-shiny-gadget-based-on-return-value-of-anoth (basically, not trying to launch the next app until the current app is no longer on the stack, i.e. not nesting `runGadget` calls).

That version works fine for me unless you use `dialogViewer`, that seems like an issue with RStudio IDE--do you mind filing an issue there?
