### ISSUE TITLE
All PR workflows are failing the R3.5.3 test due to a new R version requirement in xts (a second-order dependency)

### ISSUE THREAD

**Issue by dvg-p4** [rstudio/shiny#3802]
### System details

NA

### Example application *or* steps to reproduce the problem

Submit a pull request to Shiny, or add a commit to an existing PR

### Describe the problem in detail

The [R-CMD-check / ubuntu-20.04 (3.5.3)](https://github.com/rstudio/shiny/actions/runs/4609814118/jobs/8147483680?pr=3683#logs) test will fail "Dependency resolution" with error:
```
  Error: 
  ! error in pak subprocess
  Caused by error: 
  ! Could not solve package dependencies:
  * deps::.: Can't install dependency dygraphs
  * dygraphs: Can't install dependency xts (>= 0.9-7)
  * xts: Needs R >= 3.6.0
```
This seems to be caused by this recent update to `xts`: https://github.com/joshuaulrich/xts/commit/1ea13d4b787abb97a03e6741d6ea9c02e483706f
which pins a version of R (>= 3.6.0) for the first time. CRAN does not seem to realize that previous versions of the package were compatible with older versions of R, and thus it is impossible to install xts, or anything that depends on it, with R < 3.6.0 
Therefore, any workflow runs (including the current master) fail.

**Comment by dvg-p4** [comment]
Since dygraphs is in "suggested" rather than "imports", it's actually still possible to install shiny in R 3.5, but the test workflow looks like it tries to install all suggested packages as well.

**Comment by dvg-p4** [comment]
Ah, it seems the issue with CRAN is more fundamental--`install.packages` and CRAN simply don't have any concept of "installing an older version of a package"--the latest version is the only one that's even listed in the manifest.

**Comment by philibe** [comment]
And this sort of thing :

```R
wget https://cran.r-project.org/src/contrib/Archive/xts/xts_0.9-5.tar.gz
install.packages('xts_0.9-5.tar.gz',lib='/usr/local/lib/R/site-library/',repos=NULL,type='source')
```

or 
```R
devtools::install_github("joshuaulrich/xts@v0.9-5")  # tag
# or
  devtools::install_github("joshuaulrich/xt@5b7a23f") # commit
# or
devtools::install_github("joshuaulrich/xt#123") # pull request

```
(0.9-5 is an example, I didn't verify the dependency of `R >=`)

**Comment by dvg-p4** [comment]
Yeah that'd work, ditto `remotes::install_version()` or whatever the newfangled `pak` command is. Closed this ticket since enough new versions of R have come out that shiny no longer tests on 3.5.3 and the point is moot.
