### ISSUE TITLE
tags$head() doesn't work in Rmarkdown

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#3809]
In regular shiny apps, using `tags$head()` will result in the contents going into the `<head>` tag. For example:

```r
library(shiny)

ui <- fluidPage(
  tags$head(tags$style("body { background: red; }"))
)

server <- function(input, output, session) {}

shinyApp(ui, server)
```

The resulting page has the style tag in the head.  But in Rmd documents, `tags$head()` seems to not do anything, and the contents get treated as text. Example:

````r
---
runtime: shiny
---

```{r}
tags$head(tags$style("body { background: red; }"))
```
````

That does not result in anything useful.

If instead of `tags$head()` I use any shiny tag such as `tagList()` or `div()`, then the contents do get inserted into the document, but at that spot instead of the `<head>` tag.

Is there a technical reason why `tags$head()` can't work in Rmd, or is this simply a bug?

**Comment by gadenbuie** [comment]
This looks like it's a bug and is being tracked in https://github.com/rstudio/rmarkdown/issues/1842.

As an alternative, you can use the `head` argument of `htmlDependency()` to do something like this:

```r
taglist(
  htmlDependency(
    name = "my-custom-style",
    version = "1.2.3",
    src = c(href = "/"),
    all_files = FALSE,
    head = "<style>background: red</style>"
  )
)
```

That's a bit unwieldy for the example in your issue, but it's a useful approach if you have CSS or JS to include in the header that come from static or packaged files.

**Comment by daattali** [comment]
Thanks, will close this in favour of having it under {rmarkdown}
