### ISSUE TITLE
unused argument problem

### ISSUE THREAD

**Issue by jzen188** [rstudio/shiny#382]
Hi, shiny team
Here is my problem....

http://spark.rstudio.com/inzight/iNZightShiny/

I built a web app by shiny server....
In the final module 'iNZightBasic', I predefine iris dataset. 
However, it shows unused argument error...

But I can run no problem by using runGist locally.

 https://gist.github.com/jzen188/8722480

Besides, I use shiny v0.8.0.99....

@yihui  
Hi, yihui, I saw some of your discussion about NULL problem in shiny so far...Is it the reason that the app not working on server?? 
It is so weired.
Please help..

**Comment by brucegai** [comment]
被中文占领了..哈哈哈
