### ISSUE TITLE
Consider clarifying description of ignoreNULL in observeEvent help file

### ISSUE THREAD

**Issue by brooksambrose** [rstudio/shiny#3826]
The app below does not run the observer because `eventExpr` returns NULL and `ignoreNULL = T`, even though `input$button` is not NULL. Because the help file refers to triggering "when the input is `NULL`" I suggest rewriting the help file to describe it as "when `eventExpr` is `NULL`" to avoid confusion.

> `ignoreNULL` Whether the action should be triggered (or value calculated, in the case of `eventReactive`) when the input is `NULL`. See Details. 

```r
library(shiny)
ui <-
  fluidPage(shiny::actionButton(inputId = 'button', label = 'go'))
server <- function(input, output, session) {
  observeEvent(eventExpr = {
    input$button
    NULL
  },
  handlerExpr = {
    warning('️!')
  },
  ignoreNULL = T)
}
shinyApp(ui, server)
```

**Comment by gadenbuie** [comment]
Thanks @brooksambrose! I can see how that snippet could cause confusion. In #3827 I've updated those docs to read _when the input event expression is `NULL`_, which hopefully is a little bit more clear. Or at the very least, differentiates between `input` (the server `input` object) and input (a function input).

We can't fully commit to `eventExpr` in the docs; the current wording is the result of re-using documentation for `ignoreNULL` in other places, e.g. in `bindEvent()` where the input event expressions are passed into the `...`.

Also, in case you missed it, there's a much longer section in `?observeEvent` that goes into considerable detail about the purpose and use of `ignoreNULL`: https://shiny.posit.co/r/reference/shiny/1.7.4/observeevent

**Comment by brooksambrose** [comment]
Cheers, that explains it. My tl;dr-dar is apparently stronger than my file-a-frivolous-issue-dar.
