### ISSUE TITLE
Update selectize input document

### ISSUE THREAD

**Issue by vivigirardin** [rstudio/shiny#3834]
The [selectize documentation](https://shiny.posit.co/r/articles/build/selectize/) needs to be updated. The link to usage documentation of selectize.js is now https://github.com/selectize/selectize.js/blob/master/docs/docs/usage.mdx. Here is the quote (with correct link).

>A major difference between the usage of selectizeInput() and selectInput() is the options argument, which is a list of parameters to initialize the selectize input. Please check out the [usage documentation](https://github.com/selectize/selectize.js/blob/master/docs/docs/usage.mdx) of selectize.js for all the possible parameters.

**Comment by vivigirardin** [comment]
>Would you be interested in making a PR to update the URLs?

Sure :). Could you please send me name of the file that contains the link?

**Comment by nealrichardson** [comment]
Ah, sorry, looks like that's in a private website repository. I've made a PR to fix it there.

I was thinking of https://github.com/rstudio/shiny/blob/main/R/input-select.R#L175 and https://github.com/rstudio/shiny/blob/main/R/input-select.R#L386, which turn out not to have links, but maybe they should. Would you like to add them there?
