### ISSUE TITLE
updateSliderInput with an empty vector as value can block all other update*Input calls

### ISSUE THREAD

**Issue by SarenT** [rstudio/shiny#3840]
### System details

Browser Version: Firefox 113.0.2

Output of `sessionInfo()`:

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
Matrix products: default

locale:

[1] LC_COLLATE=English_Germany.1252  LC_CTYPE=English_Germany.1252    LC_MONETARY=English_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Germany.1252   

attached base packages:

[1] stats     graphics  grDevices utils     datasets  methods   base    

other attached packages:

[1] sortable_0.5.0     RPostgres_1.4.5    pool_1.0.1         uuid_1.1-0         dplyr_1.1.2        tidyr_1.3.0        colourpicker_1.2.0
[8] ggplot2_3.4.2      shinyBS_0.61.1     shiny_1.7.4      

loaded via a namespace (and not attached):

[1] xfun_0.39         learnr_0.11.4     tidyselect_1.2.0  bslib_0.4.2       shinyjs_2.1.0     purrr_1.0.1       colorspace_2.1-0
[8] vctrs_0.6.1       generics_0.1.3    miniUI_0.1.1.1    htmltools_0.5.5   yaml_2.3.7        utf8_1.2.3        blob_1.2.4      
[15] rlang_1.1.0       later_1.3.0       pillar_1.9.0      jquerylib_0.1.4   glue_1.6.2        withr_2.5.0       DBI_1.1.3       
[22] bit64_4.0.5       lifecycle_1.0.3   munsell_0.5.0     gtable_0.3.3      fontawesome_0.5.1 htmlwidgets_1.6.2 evaluate_0.21   
[29] memoise_2.0.1     knitr_1.43        fastmap_1.1.1     httpuv_1.6.9      crosstalk_1.2.0   fansi_1.0.4       Rcpp_1.0.10     
[36] xtable_1.8-4      promises_1.2.0.1  scales_1.2.1      DT_0.28           cachem_1.0.7      jsonlite_1.8.4    mime_0.12       
[43] bit_4.0.5         hms_1.1.3         digest_0.6.31     rprojroot_2.0.3   grid_4.1.1        cli_3.6.1         tools_4.1.1     
[50] magrittr_2.0.3    sass_0.4.5        tibble_3.2.1      crayon_1.5.2      pkgconfig_2.0.3   ellipsis_0.3.2    data.table_1.14.8
[57] timechange_0.2.0  lubridate_1.9.2   assertthat_0.2.1  R6_2.5.1          compiler_4.1.1   
```

### Example application *or* steps to reproduce the problem

 

```R
updateSliderInput(session, "inputid", value = numeric(0)) # in a subsub module
```

### Describe the problem in detail
updating slider input with an empty vector value, results in an error in the browser. This can quietly interfere with other update*Input calls. In my case, the updateSliderInput() call was in a sub-submodule. And it quietly blocked all update*Input calls from parent modules. I don't think this is an expected behavior. Solution was to manually check if the value length is 0 and replace it with a default value. This probably needs to be done inside updateSliderInput or an error/warning should be thrown.

**Comment by gadenbuie** [comment]
Hi @SarenT, thanks for the report! I've tried to reproduce the error with a small, isolated app, but I haven't been able to reproduce the behavior you've seen. (See my app at the end.)

It's possible that the structure of your modules has something to do with the issue you saw, but unfortunately I don't have enough information to recreate the error. If you're able to create a smaller, isolated example, I'd be happy to take a look.

Here's the app I used to attempt to recreate the issue. You're welcome to use this as a starting point to try to recreate the issue you saw.

```r
library(shiny)

ui <- fluidPage(
  sliderInput("number1", "Number 1", min = 0, max = 100, value = 50),
  sliderInput("number2", "Number 2", min = 0, max = 100, value = 50),
  p(
    actionButton("reset", "Reset"),
    actionButton("randomize", "Randomize"),
  ),
  markdown(c(
    "As reported in [#3840](https://github.com/rstudio/shiny/issues/3840), ",
    "attempting to update a slider input with `numeric(0)`",
    "causes other `update*Input` calls to fail.",
    "Clicking on the **Reset** button should trigger the error",
    "and break the **Randomize** button."
  )),
  verbatimTextOutput("debug")
)

server <- function(input, output, session) {
  observeEvent(input$reset, {
    updateSliderInput(session, "number1", value = numeric(0))
    updateSliderInput(session, "number2", value = numeric(0))
  })

  observeEvent(input$randomize, {
    updateSliderInput(session, "number1", value = sample(0:100, 1))
    updateSliderInput(session, "number2", value = sample(0:100, 1))
  })

  output$debug <- renderPrint({
    list(
      number1 = input$number1,
      number2 = input$number2
    )
  })
}

shinyApp(ui, server)
```


https://github.com/rstudio/shiny/assets/5420529/fa94b990-ccfa-4829-b8e3-43110eacf7a5

**Comment by gadenbuie** [comment]
@wch @jcheng5 I can reproduce the above issue and have a good understanding of how we could prevent it. But my question is: what should `updateSliderInput()` do in the case of a zero-length `value`?

**Comment by wch** [comment]
My guess is that when the client gets the empty value and tries to set the value on the slider, it's causing an exception to be thrown, and that prevents the rest of the message from the server from being processed.

In general, for errors that might be commonly made, it would be good to catch them early, in R, and throw an error or warning. However, because of the nature of R, it's not practical in general to validate all possible inputs this way.

I think that for this case, it makes sense to do the updates in the client in a try-catch, and if any errors occur, catch them and print them as warnings in the console.

**Comment by gadenbuie** [comment]
@wch thanks that's helpful! Your guess is right, I can see in the websocket traffic that the update input messages are sent for both inputs and an error is logged in the console, from these lines

https://github.com/rstudio/shiny/blob/2b48aa0d9149e91cd9079ee705a5c98d5c258c68/srcts/src/shiny/shinyapp.ts#L266-L277

Are input messages sent in the same reactive flush handled as a block in the taskQueue?

The error itself is thrown by the `recieveMessage()` method of the slider input

https://github.com/rstudio/shiny/blob/2b48aa0d9149e91cd9079ee705a5c98d5c258c68/srcts/src/bindings/input/slider.ts#L200

Rather than finding the right place higher in the call stack to try-catch, would it make sense for the slider input to no-op with a logged error rather than to throw?

**Comment by wch** [comment]
Each item in the `taskQueue` is a call to `this.dispatchMessage()` -- the try-catch surrounds that entire function, so if an exception is thrown while handling an part of the message, the rest of the message won't be processed. I think that's what's happening here.

https://github.com/rstudio/shiny/blob/1b7709411beeb345af54d159c0af6528fd542525/srcts/src/shiny/shinyapp.ts#L242-L244

I think it still makes sense for the slider to have the `throw` where you pointed out. This is just one of many, many kinds of invalid values that could be sent to an input binding, and trying to smoothly handle every kind of bad value in all the types of inputs would be impractical. Instead, we could put a try-catch block around the code that actually dispatches each part of the message.

That would be inside of the loop in this function:
https://github.com/rstudio/shiny/blob/1b7709411beeb345af54d159c0af6528fd542525/srcts/src/shiny/shinyapp.ts#L666-L681

**Comment by SarenT** [comment]
@gadenbuie Sorry for not coming back earlier. Indeed, in my case there were 3 modules inside each other. e.g.
Module A was called from server.R
Module B was called from Module A
Module C was called from Module B.

All 3 modules have data tables, where I was listening (`observeEvent`) for a row selection to populate inputs with the selected values.

The silent error occurred in `updateSliderInput` in Module C/`observeEvent`, upon which none of the modules were able to update the inputs (all A, B and C).
Funnily, I had another set of modules called from server.R
Module D was called from server.R
Module E was called from Module D
Module F was called from Module E.

These were working file, because the inputs were all `textInput`s. That was how I was able to find out.

Regarding the solution, wouldn't it be easy to check for length 2 or 1 of the value parameter?

`valid_classes = c("numeric", "Date", "POSIXt")

numeric_values = c(5, 6)
date_values = c(as.Date("18.06.2023", format = "%d.%m.%Y"), as.Date("19.06.2023", format = "%d.%m.%Y"))
datetime_values = c(as.POSIXlt(Sys.time()), as.POSIXlt(Sys.time() + 3600))
invalid_values = list("character", numeric(0), data.frame())

test_values = list(numeric_values, date_values, datetime_values)

tests = c(lapply(test_values, function(values){return(values[[1]])}), test_values, invalid_values)

results = lapply(tests, function(values){
	if(any(valid_classes %in% class(values)) && length(values) %in% c(1, 2)){
		# send messages to the client
		print(values)
		cat("OK! \n")
	}else{
		print(values)
		cat("Error! \n")
		# stop("Please provide a valid value class and a valid vector length.")
	}
})
`

**Comment by gadenbuie** [comment]
> In general, for errors that might be commonly made, it would be good to catch them early, in R, and throw an error or warning. However, because of the nature of R, it's not practical in general to validate all possible inputs this way.


> This is just one of many, many kinds of invalid values that could be sent to an input binding, and trying to smoothly handle every kind of bad value in all the types of inputs would be impractical.

@wch Are you in favor of checking that `value` is length 1 or two and not `NA` in `updateSliderInput()`? i.e. replicating the checks that are performed on `value` in `sliderInput()`? If you are, would you rather error or warn and no-op?

**Comment by gadenbuie** [comment]
@SarenT Thanks for writing back! The good news is that I don't think your module structure is related to the error. I have a WIP fix that you can try by installing from the PR branch. If you do test it, please let me know how it goes!

```r
devtools::install_github("rstudio/shiny#3843")
```

**Comment by wch** [comment]
Regarding validating the values in `updateSliderInput()`, I'm fine with it either way.

It should definitely just warn and not throw an error, though. This is because, if an uncaught error occurs in an observer, it will cause the app to exit.
