### ISSUE TITLE
URL update in package description

### ISSUE THREAD

**Issue by MalteSteinCytel** [rstudio/shiny#3863]
Can you please add the source URL (https://github.com/rstudio/shiny) in the DESCRIPTION file of the package (https://github.com/rstudio/renv/blob/main/DESCRIPTION):

Proposed URL statement:
URL: https://shiny.posit.co/, https://github.com/rstudio/shiny

The URLs is stored within the package repository database (e.g. http://cloud.r-project.org/web/packages/packages.rds).
The source URL will help to access the package source for automatic validation and analyses of packages.

**Comment by gadenbuie** [comment]
Thanks for the report @MalteSteinCytel! I've added the URL to DESCRIPTION and it'll be in the next CRAN release.
