### ISSUE TITLE
Minor typo in documentation

### ISSUE THREAD

**Issue by CRau080** [rstudio/shiny#3895]
Hello Shiny team,

the documentation for "bindEvent" under the URL

https://shiny.posit.co/r/reference/shiny/1.7.4/bindevent

has the following explanation below the first argument (x):
"An object to wrap so that is triggered only when a the specified event occurs."

I believe that "...when the specified event occurs." is what was meant.

Thank you.

**Comment by cpsievert** [comment]
Thanks for noticing @CRau080, a pull request to fix the typo would be most welcome!
