### ISSUE TITLE
can't re-use output items on different tabs

### ISSUE THREAD

**Issue by HarlanH** [rstudio/shiny#39]
I've got an app where I'm displaying the same data different ways on different tags. Below the output graphs, I've got this trivial item:

```r
h3(textOutput("n"))
```

defined by:

```r
  output$n <- reactiveText(function() {
    paste("n =", nrow(this_dat()))
  })
```

Works great if I have a single tab. If I have two tabs, each of which have the above (but with different `plotOutput` objects), then the Javascript crashes because of the duplicate object names.

The workaround is to duplicate the above with `n2`. Not a big deal, once I figured out the problem, but it'd be great if there were some way to have the same output objects on multiple tabs without error. At a minimum, a better error message would be very helpful.

Thanks!

**Comment by wch** [comment]
Sorry for the very slow reply. Sorry, it's not possible to have two outputs with the same ID, because this generates invalid HTML (this would result in multiple DOM elements with the same ID). It would be good to have better error message though. We'll keep track this of issue via #743.
