### ISSUE TITLE
updateselectinput docs on UI input variables with special characters

### ISSUE THREAD

**Issue by nick-youngblut** [rstudio/shiny#3900]
For a number of reasons, I want to use UI input variables that include special characters (e.g., `Project ID` instead of `Project_ID`). However, it appears that `updateselectinput` does not work in such cases (e.g., `updateSelectInput(session, "plot type", choices = new_choices)`). It would be helpful to include such a warning in the [updateselectinput docs](https://shiny.posit.co/r/reference/shiny/0.11/updateselectinput).

**Comment by cpsievert** [comment]
Interesting, thanks! This behavior seems to be specific to Chrome (I'm on 16.0.5845.187), and applies to both `selectInput(selectize = T/F)` Here's a minimal reprex. Notice how `Project ID` becomes `ProjectID` and `Other Choice` becomes `Other choice`

```r
library(shiny)

ui <- fluidPage(
  selectInput("x", NULL, choices = c("Foo", "Bar"), selectize = FALSE),
  verbatimTextOutput("out")
)

server <- function(input, output, session) {  
  updateSelectInput(inputId = "x", choices = c("Project ID", "Other Choice"))
  output$out <- renderPrint(input$x)
}

shinyApp(ui, server)
```

**Comment by gadenbuie** [comment]
If this issue is about the select `inputId` being `"plot type"`, then #3852 will probably fix the original issue.

But it sounds like there's a separate issue with the handling of `choices`.

**Comment by cpsievert** [comment]
Oh interesting, the problem I mentioned in https://github.com/rstudio/shiny/issues/3900#issuecomment-1736402738 goes away if I select "Never translate this page" (it's trying to translate to Arabic?!?)

Anyway, it's not clear what Shiny can do to help the situation without any more details, so I'll be closing the issue
