### ISSUE TITLE
`fileInput`: validate file extensions if specified in `accept`

### ISSUE THREAD

**Issue by chlebowa** [rstudio/shiny#3916]
The `accept` argument can be used to specify valid file extensions it does not actually prevent the user from selecting an invalid file.

In the example below, the input was created with  `fileInput(accept = ".json")`. 
The browser window opens with only `json` files displayed but the user can change that `All Files` and any select file.

![file_choices_json](https://github.com/rstudio/shiny/assets/114988527/ff681ae0-502a-45e7-b1b2-53c4e5d13e98)

![file_choices_all](https://github.com/rstudio/shiny/assets/114988527/66c36992-e7b9-4b87-9bcf-571d5452850e)

Could a validation step be added?

**Comment by gadenbuie** [comment]
Hi @chlebowa and thanks for the feature request. I also looked a bit a the backstory in the linked pull request in teal, which was helpful.

A little context: the `accept` parameter of `fileInput()` determines the `accept` attribute that's added to the file `<input>` tag:

```r
fileInput("json_file", "Pick a .json file", accept = "json")
#> ...
#> <input id="json_file" ...snip... accept=".json"/>
#> ...
```

At this point, which file the user is allowed to upload is up to the browser. As you noticed, browsers can be somewhat lenient, here allowing someone to go around the initial `*.json` filter to upload a file that _isn't_ JSON. That said, a user might also go around the checks to upload a file with an unusual name that _is_ a JSON file but isn't appropriately named. The browser's approach guides the user but also does not stand in the way if the user is certain about what they're doing.

I think Shiny in general would prefer a similar approach here. We can't possible know the full set of file types that app authors would like to support or how to correctly validate them all. If Shiny implemented file checks, in cases were we aren't certain how to handle the file validation, we risk throwing errors when users upload valid files or failing to throw an error when users upload invalid files. Even in very clear cases, like `.json` files, there is a lot of room for how file validation could be handled, ranging from "is it named properly" to "is it valid JSON". If we implement file checks at the wrong level, they would be useful to some app authors and a hindrance to others.

All of this to say: I think you're very right to validate the uploaded file and to handle parsing errors directly in your server logic. I'm confident that you, as the app author, will be able to construct a much better experience for your app users than Shiny ever could if we were to implement a generic file type check.

**Comment by chlebowa** [comment]
Hi @gadenbuie, thanks for the prompt answer.

I agree that a robust file validation is well beyond the purview of `shiny`. However, since file extensions are suggested as an acceptance criterion in the help files, I would expect them to be enforced. Admittedly, juggling strict criteria like file extensions and vague ones such as "valid JSON file", is no easy task.

Very well, we will handle validation on our end.

**Comment by chlebowa** [comment]
I would say a file extension is a strictly defined criterion, even if it is not strictly enforced. But that's just semantics. I understand that `accept` is only used as a hint.
