### ISSUE TITLE
`inputSelectize()` should set option `selectOnTab = FALSE` by default

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/shiny#3934]
The latest version of selectize (in the current release candidate), changes the <kbd>Tab</kbd> behavior so that <kbd>Tab</kbd> or <kbd>Shift</kbd> + <kbd>Tab</kbd> add the selected item rather than move between inputs. We prefer the behavior seen in current Shiny apps where the user can move between inputs with <kbd>Tab</kbd> and <kbd>Shift</kbd> + <kbd>Tab</kbd> and options are added with <kbd>Enter</kbd>.

### Prior behavior (shiny 1.7.4.1)

https://github.com/rstudio/shiny/assets/5420529/8f0cf031-f1c3-46eb-9186-434a0bcc57fa

### Current behavior (shiny rc-1.8.0)

https://github.com/rstudio/shiny/assets/5420529/2b61d1a6-afda-41fe-9c4c-7b21e8c89ceb

### Testing

The [shinycoreci](https://github.com/rstudio/shinycoreci/tree/main/inst/apps) `024-optgroup-selectize` app is a good testing example, also the select inputs in the data tab of `063-superzip-example`.

**Comment by cpsievert** [comment]
Here's the issue that lead to a decision to change `selectOnTab`'s default to `true` https://github.com/selectize/selectize.js/issues/945
