### ISSUE TITLE
Issue with fixedPanel responsive = FALSE argument

### ISSUE THREAD

**Issue by wbakerrobinson** [rstudio/shiny#3941]
### System details

Output of `sessionInfo()`:

```
R version 4.3.1 (2023-06-16)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.7.5.1

loaded via a namespace (and not attached):
 [1] jsonlite_1.8.7    gtable_0.3.4      dplyr_1.1.3       compiler_4.3.1    promises_1.2.1   
 [6] tidyselect_1.2.0  Rcpp_1.0.11       gridExtra_2.3     jquerylib_0.1.4   later_1.3.1      
[11] scales_1.2.1      yaml_2.3.7        fastmap_1.1.1     mime_0.12         ggplot2_3.4.4    
[16] R6_2.5.1          generics_0.1.3    knitr_1.45        viridis_0.6.4     tibble_3.2.1     
[21] munsell_0.5.0     bslib_0.5.1       pillar_1.9.0      rlang_1.1.2       utf8_1.2.4       
[26] cachem_1.0.8      httpuv_1.6.12     xfun_0.41         sass_0.4.7        memoise_2.0.1    
[31] viridisLite_0.4.2 cli_3.6.1         withr_2.5.2       magrittr_2.0.3    digest_0.6.33    
[36] grid_4.3.1        rstudioapi_0.15.0 xtable_1.8-4      lifecycle_1.0.4   vctrs_0.6.4      
[41] evaluate_0.23     glue_1.6.2        rsconnect_1.1.1   fansi_1.0.5       colorspace_2.1-0 
[46] rmarkdown_2.25    tools_4.3.1       pkgconfig_2.0.3   ellipsis_0.3.2    htmltools_0.5.7  
```

### Example application *or* steps to reproduce the problem
```R
library(shiny)

ui <- fixedPage(
  responsive = FALSE,
  titlePanel("Old Faithful Geyser Data"),
  fixedRow(
    column(12,
           wellPanel(
             fixedRow(
             column(4,
                    sliderInput(inputId = "a",
                                label = "slider 1",
                                min = 1,
                                max = 10,
                                value = 3)),
             column(4,
                    sliderInput(inputId = "b",
                                label = "slider 2",
                                min = 1,
                                max = 10,
                                value = 5)),
             column(4,
                    checkboxGroupInput(inputId = "c",
                                       label = "checkbox 1",
                                       choices = c("a", "b", "c", "d"),
                                       selected = "a"))
           ))
           )
  )

)

server <- function(input, output) {
}

shinyApp(ui = ui, server = server)
```

### Describe the problem in detail
The shiny application layout guide (https://shiny.posit.co/r/articles/build/layout-guide/) describes the argument responsive = FALSE passed to fixedPage() as a way to turn off responsive boostrap features. This argument however doesn't work to turn off responsive bootstrap features. When the window in the example shiny app code above becomes smaller than 768px the wellPanel() is resized stacking the widgets. I didn't see anything about the responsive argument in the docs. Is this an issue with the function or does it need to be updated another way?

**Comment by gadenbuie** [comment]
Unfortunately those docs are just very outdated. The `responsive` argument was marked as deprecated in 2014 (when shiny upgraded from Bootstrap 2 to Bootstrap 3) and then fully removed from `fluidPage()` and `fixedPage()` in shiny 1.7.0 (released 3 years ago).

I think the article date on that page isn't quite telling the truth, which leads to additional confusion. I'll make sure we have an internal ticket to update that article.

**Comment by wbakerrobinson** [comment]
Given that this isn't an option anymore. Do you have any suggestions on another way to turn off the responsive bootstrap features for a shiny app?

**Comment by cpsievert** [comment]
> This argument however doesn't work to turn off responsive bootstrap features. When the window in the example shiny app code above becomes smaller than 768px the wellPanel() is resized stacking the widgets. 

FWIW, `responsive = FALSE` was about turning off the responsive page width (i.e., the container that adds margins to the page), not about preventing collapsing of grid layout on small devices (I don't think we've ever supported that).

Thankfully, it seems like a new [Bootstrap stacking](https://getbootstrap.com/docs/5.3/helpers/stacks/) feature might be exactly what you're looking for. We don't have an official wrapper for it, but you could write the HTML:

```r
library(shiny)
library(bslib)

ui <- page_fixed(
  titlePanel("Old Faithful Geyser Data"),
  div(
    class = "hstack p-3 gap-3 justify-content-center bg-light border rounded",
    sliderInput(
      "a", "slider 1",
      min = 1,
      max = 10,
      value = 3
    ),
    sliderInput(
      "b", "slider 2",
      min = 1,
      max = 10,
      value = 5
    ),
    checkboxGroupInput(
      "c", "checkbox 1",
      choices = c("a", "b", "c", "d"),
      selected = "a"
    ) 
  )
)

shinyApp(ui, function(input, output) {})
```
