### ISSUE TITLE
Shiny server not supporting http range requests. This disables seekbars for locally (www folder) hosted media files.

### ISSUE THREAD

**Issue by RSchwinn** [rstudio/shiny#3982]
Shiny does not return HTTP range requests for files hosted in the "www" folder.  The MWE below demonstrates the issue. In setting up this example, save the "sample-mp4-file.mp4" file [(download here](https://jsoncompare.org/LearningContainer/SampleFiles/Video/MP4/sample-mp4-file.mp4)) into the "www" subdirectory of the folder hosting the app.R file. You'll notice the seeker is disabled for the locally hosted mp4 file. This issue doesn't apply to files < 1MB, which might explain why others have not provided compelling examples. This file is 10MB, so Chrome will require a response of 206 from the allow HTTP range inquiry.

```
library(shiny)

# Define UI for application that draws a histogram
ui <- fluidPage(

    # Application title
    titlePanel("Streaming Video Issue"),
    
    h1("Externally Hosted File"),
    tags$iframe(src = "https://jsoncompare.org/LearningContainer/SampleFiles/Video/MP4/sample-mp4-file.mp4", 
                type = "video/mp4",
                width = "600px",
                height = "333px"),
    
    h1("Locally Hosted File"),    
    tags$iframe(src = "sample-mp4-file.mp4", 
                type = "video/mp4",
                width = "600px",
                height = "333px")
)

# Define server logic required to draw a histogram
server <- function(input, output) {

}

# Run the application 
shinyApp(ui = ui, server = server)
```

Others have posted about this issue without resolution. See [https://stackoverflow.com/questions/71958281/r-shiny-embedded-video-works-but-wont-fast-forward-skip-time](https://stackoverflow.com/questions/71958281/r-shiny-embedded-video-works-but-wont-fast-forward-skip-time). It may be helpful to read this article on HTTP range requests: [https://www.zeng.dev/post/2023-http-range-and-play-mp4-in-browser/](https://www.zeng.dev/post/2023-http-range-and-play-mp4-in-browser/l)

**Comment by philibe** [comment]
(Your 2nd link is broken when we click : it seems to be [https://www.zeng.dev/post/2023-http-range-and-play-mp4-in-browser/](https://www.zeng.dev/post/2023-http-range-and-play-mp4-in-browser/)  )
