### ISSUE TITLE
Some known issues of renderDataTable()

### ISSUE THREAD

**Issue by yihui** [rstudio/shiny#400]
- [x] should respect `bCaseInsensitive = TRUE` (#579 <del>need DT support: https://datatables.net/forums/discussion/comment/65260</del>)
- [x] perhaps `iDisplayLength = -1` should mean "display all records"
- [x] `bPaginate = FALSE`
- [x] selectable rows
  - https://groups.google.com/forum/#!topic/shiny-discuss/_zNZMR2gHn0
  - http://demo.shinyapps.io/029-row-selection/
- [x] respect `bFilter` and `bSearchable`
- [ ] obtain the indices of the current rows displayed https://groups.google.com/forum/#!topic/shiny-discuss/r-4stY3xTy0
- [x] display rownames
- [x] a new sorting problem in 1.10.2: DataTables/DataTables#391 (need to upgrade to DT 1.10.3)
- [x] tabletools

**Comment by yihui** [comment]
For those looking for row selection, please see http://rstudio.github.io/DT/shiny.html and test the DT package. Thanks!

**Comment by YungDeiza** [comment]
This is probably not the correct place to write this but I keep getting this error when using renderdatatable "Error in if (is.null(data) || ncol(data) == 0) { : missing value where TRUE/FALSE needed"
