### ISSUE TITLE
After upgrading to Shiny 1.8.1 from 1.8.0, no data is visible on my shiny APP

### ISSUE THREAD

**Issue by gunawebs** [rstudio/shiny#4016]
After upgrading to Shiny 1.8.1 from 1.8.0, no data is visible on my shiny APP

runApp() does not throw any error, but NO data is shown on the screen

Was some backward compatibility broken in this release?

**Comment by gunawebs** [comment]
Note: As soon as I uninstalled 1.8.1 and installed 1.8.0 from : https://cran.r-project.org/src/contrib/Archive/shiny/shiny_1.8.0.tar.gz

Things worked JUST FINE

**Comment by jcheng5** [comment]
Yikes! Certainly not intentionally!

When the problem occurs, is there any error in your browser’s JavaScript console?

**Comment by gunawebs** [comment]
Absolutely nothing. 
Few possible points that may help you debug:
1) Mine is a huge shiny app
2) id= maybe missing for some elements
3) many navbarPages may have the same value for id (shiny did not mind this till now)

**Comment by gunawebs** [comment]
Similarly a few tabsetpanels also may have the same id. 

I cannot think of anything else that could have broken this so badly. 

Note: Earlier same behaviour was observed if there were multiple datatables or UI elements with same id. Is it possible that same strictness is now being enforced on tabsetpanels and navbarpages?

Just trying to think what could have happened :-)

**Comment by gunawebs** [comment]
@jcheng5 please see if above comments help you debug

**Comment by jcheng5** [comment]
Yes we’ve gotten stricter with duplicate IDs, but I would’ve expected messages in the browser’s JavaScript console in that case.

@gadenbuie @cpsievert any ideas?

**Comment by gunawebs** [comment]
As of now I have reverted to 1.8.0, So wont be able to replicate. Since things work perfectly fine on 1.8.0
Will try on my QA box next week. with 1.8.1

But any easy way for me to spot the root cause and fix? I can then try those on QA box. 

Thanks!

**Comment by gunawebs** [comment]
OK, one thing is: I might have closed browser’s JavaScript console too soon. And was using large extension monitors. So there is a non zero chance that I might have missed this. Having said that, this may be breaking stuff for many shiny users. Since many would've copied code for tabsetpanels like me. But I guess there is nothing much you can do? (or is there a global flag to switch off duplicate checks added in 1.8.1? Just for testing?)

**Comment by gadenbuie** [comment]
@gunawebs Could you show us a small snippet of code to give us a sense of how you're using `navbarPage()` and `tabsetPanel()`? In particular, the parts that you suspect might be related?

**Comment by cpsievert** [comment]
Another thing that'll be helpful for debugging: call `shiny::devmode()` before launching the app. If duplicate IDs is the issue, you should see a popup appear in the app with the relevant IDs. Something like this:

<img width="533" alt="error-dialog" src="https://github.com/rstudio/shiny/assets/1365941/3be621d7-d163-4598-87c0-c0f0142cb709">

**Comment by wyu** [comment]
I had the same problem on my modulized app. It turns the "sidebar" in two of my modules had the same id. Wrapping them with ns(), as I should have done, fixed the problem. Thanks to the comment from Joe!

Wen

**Comment by gunawebs** [comment]
hello @cpsievert @jcheng5 @gadenbuie 

 I repeated the test on my QA box:

Here is my error on the screen, when in dev mode
<img width="460" alt="image" src="https://github.com/rstudio/shiny/assets/4875731/53a28f22-51f6-4202-b0a2-7bf6c31e96dd">

Here is my error on javascript console
<img width="557" alt="image" src="https://github.com/rstudio/shiny/assets/4875731/36513c3c-c4ba-4e29-9794-37d3858a3295">


BUT There is no ID called: sidebarItemExpanded anywhere in my code
I searched all over.

So I am badly stuck

Also attached a sippet of code. this may or may not be the error.

<img width="613" alt="image" src="https://github.com/rstudio/shiny/assets/4875731/ee8ce4ef-1255-4d7d-a1b8-feab686c2296">

**Comment by gunawebs** [comment]
OK, I may have zero'ed in on the error:

Commenting the code as below, fixed the error
<img width="697" alt="image" src="https://github.com/rstudio/shiny/assets/4875731/4a2e8fc6-fd87-4f36-8931-41779ba9a5bf">

Basically it did NOT like the dashboardPage(under tabPanel) within navbarPage

**Comment by jcheng5** [comment]
If you have two `dashboardPage` calls, then yes, this problem will occur. `dashboardPage`, `navbarPage`, and really any function from our team that is either `xxxPage` or `page_xxx` is designed to be the outermost function call for your UI.

(Team, seems like this is a scenario we hadn't thought of--apps that are working "correctly" in Shiny <=1.8.0 despite having duplicate IDs, because the app doesn't actually use them.)

**Comment by gunawebs** [comment]
Thanks @jcheng5 

So looks like 2 gotchas:

1) dashboardPage(under tabPanel) within navbarPage works fine in 1.8.0
So presume it got stricter in 1.8.1, and will just break everything now.

2) Duplicate, but unused, ids weren't a problem till 1.8.0, But 1.8.1 will break it.

Correct?

Thanks!

**Comment by jcheng5** [comment]
@gunawebs, what other page functions are you using in your UI, and how many times each? Here we can see navbarPage x 1 and dashboardPage x 1, but are there others?

**Comment by gunawebs** [comment]
Great question @jcheng5 

This was the error:
![image](https://github.com/rstudio/shiny/assets/4875731/955d956a-e2ff-4993-9ecd-c853a2a7cac1)

As you can see it said: 3 errors.

And there were exactly 3 combination of:

navbarPage x dashboardPage in my code.

I commented all three of them. And things worked fine after that.

**Comment by cpsievert** [comment]
Thanks for the reports everyone. We're going to do a patch release early next week so that the error only gets thrown when opt-ing into `shiny::devmode(TRUE)`. Otherwise, you'll just get a warning in the browser's JS console.

**Comment by gunawebs** [comment]
@cpsievert thanks a ton.

quick question, by any chance would this take care of the dashboard issue too?
In other words can we now have dashboardPage within navbarPage?

**Comment by gunawebs** [comment]
Thanks @cpsievert will try right away

**Comment by gunawebs** [comment]
@cpsievert Thanks so so much. I have tested with the pre release version. And things work fine. 

a. Could you please let me know the expected date of the patch to be released on CRAN
b. Regarding your question: "Are you needing that usage because {shinydashboard} doesn't allow for navigation in the header (just the sidebar)". Absolutely correct. Mine is a multi layered app, with deep hierarchy of tabs and dashboards.
c. Will surely check bslib out.

Thanks!

**Comment by cpsievert** [comment]
New release is now up on CRAN
