### ISSUE TITLE
Plot overlaps onto tab panel. 

### ISSUE THREAD

**Issue by joe-jhou2** [rstudio/shiny#4029]
![Screenshot 2024-04-11 at 2 19 25 PM](https://github.com/rstudio/shiny/assets/4881411/b0d55a35-c813-42fd-bdcf-e434131f9426)

Seeing the screenshot, the plot, edge part overlaps onto the tab panel, you see the white bg cover on the gray bg of tab panel. Anyone can share advice how to adjust that? Thanks.

**Comment by gadenbuie** [comment]
Thanks for the report @joe-jhou2 but it's very difficult to understand what's happening in your app from the screenshot. In general, it's very difficult to diagnose an issue from a screenshot alone. If you could please post [a reproducible example with code](https://community.rstudio.com/t/shiny-debugging-and-reprex-guide/10001), there's a much better chance that we or others in the community will be able to help you.

**Comment by joe-jhou2** [comment]
thanks, use css fix it.
