### ISSUE TITLE
shiny > 1.8.0 breaks tags$button reactivity

### ISSUE THREAD

**Issue by trafficonese** [rstudio/shiny#4030]
I am using plenty of functions to create my UI and this used to work until v1.8.0.
But now, a button click is ignored.

```
library(shiny)

make_calc_button <- function() {
  div(class = "myactbtn",
      div(class = "acgrouprun",
          tags$button(id = "konfig_save_modal",
                      class = "btn btn-default action-button shiny-bound-input",
                      type = "button",
                      label = NULL, title = "Save to DB",
                      tags$img(src = "./dist/icons/btn_save.svg", width="16px",height="16px", class = "dbbutns run",
                               alt="Save to DB")),
          tags$button(id = "konfig_del_modal",
                      class = "btn btn-default action-button shiny-bound-input",
                      type = "button",
                      label = NULL, title = "Delete from DB",
                      tags$img(src = "./dist/icons/btn_delete.svg", width="16px",height="16px", class = "dbbutns run",
                               alt="Delete from DB"))
      )
  )
}

ui <- fluidPage(make_calc_button())

server <- function(input, output, session) {
  observeEvent(input$konfig_save_modal, { print("konfig_save_modal") })
  observeEvent(input$konfig_del_modal, { print("konfig_del_modal") })
}

shinyApp(ui, server)
```

**Comment by wch** [comment]
I think the problem is that you're adding the `shiny-bound-input` class to the buttons. That is something that Shiny does dynamically.

**Comment by trafficonese** [comment]
That solves the problem..

**Comment by vnijs** [comment]
Ran into the same issue with 1.8.0 and 1.8.1.1. Just curious ... why would adding `shiny-bound-input` dynamically break the code that already included `shiny-bound-input`?

**Comment by gadenbuie** [comment]
> why would adding `shiny-bound-input` dynamically break the code that already included `shiny-bound-input`?

Shiny adds the class as a signal that the element is bound to an input. If an element already has the class, Shiny will assume that the input-element binding has already happened and will skip the element.

In the example above, the author was creating a button with

```r
tags$button(id = "ID", class = "btn btn-default action-button shiny-bound-input", ...)
```

which will seem like a reasonable thing to do if you copy the HTML from the browser in a running Shiny app. But if you look at the markup created on the R side, we don't include `shiny-bound-input`.

```r
shiny::actionButton("ID", NULL)
#> <button id="ID" type="button" class="btn btn-default action-button"></button>
```

**Comment by gadenbuie** [comment]
It's hard to say whether it was a breaking change or a bug fix. It's certainly empirically clear that the behavior changed. It's possible that we previously bound elements that had the `shiny-bound-input` class. But the intent of the class was always to signal that the input _was bound_ and for the class to be added as part of the input binding process.
