### ISSUE TITLE
New selectInput allows user to clear text

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#404]
The new selectize selectInput allows clear the selection box if you press Backspace, and it automatically sends the value to the server. This can cause problems.

To reproduce, run `runExample('04_mpg')`, then click on the selection box and press Backspace.

**Comment by muranyia** [comment]
BTW
```R
selectInput('foo1', 'No deletion, no searching', choices = state.name,
                options = list(onDelete = I('function(value) {return false;}')))
```
doesn't work,
```R
selectInput('foo1', 'No deletion, no searching', choices = state.name,
                list(onDelete = I('function(value) {return false;}')))
```
does.

**Comment by sada1993** [comment]
Has this issue come back into the latest version of shiny? Everything was working fine till I updated to the latest CRAN version. My question on:

https://stackoverflow.com/questions/51898693/shiny-selectinput-and-selectizeinput

another Reproducible example

`
shinyApp(
  ui = fluidPage(
    selectInput("state", "Choose a state:",
                list(`East Coast` = c("NY", "NJ", "CT"),
                     `West Coast` = c("WA", "OR", "CA"),
                     `Midwest` = c("MN", "WI", "IA"))
    ),
    textOutput("result")
  ),
  server = function(input, output) {
    output$result <- renderText({
      cat("Running...")
      paste("You chose", input$state)
    })
  }
)
`

@jjallaire both 1) and 2) are being violated.

**Comment by sada1993** [comment]
@yihui Just checked with the archived shiny version 1.0.5 and the behavior is as expected. Both the CRAN 1.1.0 and the GitHub master branch have this unexpected behavior when the backspace is pressed. Was this an intentional change on 1.1.0?

**Comment by yihui** [comment]
@sada1993 Sorry, but I don't know. I haven't worked on shiny since 2015...

**Comment by wch** [comment]
@sada1993 can you file a new issue:?
