### ISSUE TITLE
Shiny Getting Started Tutorial missing `textOutput('selectedVar')` from example

### ISSUE THREAD

**Issue by TheNudibranch** [rstudio/shiny#4051]
In the first code block for [lesson 4](https://shiny.posit.co/r/getstarted/shiny-basics/lesson4/), there should be a `textOutput('selectedVar)` statement at the bottom. 

![image](https://github.com/rstudio/shiny/assets/30155695/a691175a-c1aa-42fa-bad0-a691087febff)

**Comment by cpsievert** [comment]
Seems this is related to recent changes @skaltman made in https://github.com/rstudio/shiny-dev-center

**Comment by skaltman** [comment]
Sure, I can fix this!
