### ISSUE TITLE
observeEvent does not trigger to changes in reactiveValues

### ISSUE THREAD

**Issue by shahronak47** [rstudio/shiny#4064]
Taking an example from this post https://stackoverflow.com/questions/68707709/observeevent-not-reacting-to-changes-in-reactivevalues 

```
library(shiny)

ui <- fluidPage(
  numericInput("x", "x", 5),
  numericInput("y", "y", 10)
)

server <- function(input, output, session) {
  test_vals <- reactiveValues(
    x = reactive(input$x),
    y = reactive(input$y)
  )
 
  observeEvent(test_vals, {
    print("test_vals changed")
  })
}

shinyApp(ui, server)
```

The message is printed in the console only once when the app is launched but nothing happens when the value changes. 

In this case I know the issue will be fixed if I use `observeEvent(c(input$x, input$y), {...})` but this is very simplistic example and my actualy example is much more complicated. My goal is to make `observeEvent` (or `observe`) trigger based on the changes in `reactiveValues`. 

I have searched the internet quite extensively along with Github issue but could not find this topic being discussed.

**Comment by MohoWu** [comment]
Instead of the `observeEvent` can you do this?

```
lapply(isolate(names(test_vals)), function(x) {
      observeEvent(input[[x]], {
        print("test_vals changed")
      })
    })
```

**Comment by wch** [comment]
I believe you should be able to do:

```R
observeEvent(reactiveValuesToList(test_vals), {
})
```

**Comment by shahronak47** [comment]
> I believe you should be able to do:
> 
> ```r
> observeEvent(reactiveValuesToList(test_vals), {
> })
> ```

Sorry @wch , but that doesn't seem to work for me. It still behaves the same the message is printed only once upon launch.

**Comment by scal-o** [comment]
You can do this: 

```
  observeEvent(
    lapply(names(test_vals), function(name) test_vals[[name]]()), {
    print("test_vals changed")
  })
```

There were two problems with your code. First of all, the reactiveValues object is not reactive itself, which means that it is not invalidated when one of its elements changes. From `?reactiveValues`: 

> Note that values taken from the reactiveValues object are reactive, but the reactiveValues object itself is not.

The second problem is that the elements inside your reactiveValues are themselves reactive. In order to take an "invalidation dependency" on them, you have to call them to retrieve their value. 

Hope this helps :)
