### ISSUE TITLE
runExample: new version that uses {bslib} no longer uses showcase mode by default, despite docs saying otherwise 

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#4077]
The `runExample()` function documentation claims that it uses `showcase` display mode by default. That used to be true, and is still true if you set `options(shiny.legacy.examples=TRUE)`. However, starting v1.8.1 when using the new default `runExample()` that uses {bslib}, the default mode seems to be `normal`.

Either the docs need to update, or the function needs to update.

**Comment by remonds** [comment]
I confirm daattali's problem description.
Function update is preferred.

**Comment by gadenbuie** [comment]
Thanks for the report @daattali and for bumping this issue @remonds. The documentation hadn't been updated to reflect that `runExample()` can now be used to run examples from other packages as well. The default is `"auto"`, which means that the example's `DESCRIPTION` file is consulted for the value of `DisplayMode`. The new examples that use bslib also use the normal display mode by default, but the function documentation after #4152 will explain how to opt into `"showcase"` mode by setting `display.mode = "showcase"` if you prefer that experience.
