### ISSUE TITLE
Duplicate observer triggers for actionLinks in a renderUI

### ISSUE THREAD

**Issue by rundel** [rstudio/shiny#4160]
### System details

Browser Version: N/A

Output of `sessionInfo()`:

```
R version 4.4.2 (2024-10-31)
Platform: aarch64-apple-darwin20
Running under: macOS Sequoia 15.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.9.3  forcats_1.0.0    stringr_1.5.1    dplyr_1.1.4      purrr_1.0.2     
 [6] readr_2.1.5      tidyr_1.3.1      tibble_3.2.1     ggplot2_3.5.1    tidyverse_2.0.0 
[11] bslib_0.8.0.9000 shiny_1.9.1     

loaded via a namespace (and not attached):
 [1] gtable_0.3.6      jsonlite_1.8.9    compiler_4.4.2    bsicons_0.1.2     promises_1.3.2   
 [6] tidyselect_1.2.1  Rcpp_1.0.13-1     later_1.4.1       jquerylib_0.1.4   scales_1.3.0     
[11] fastmap_1.2.0     mime_0.12         R6_2.5.1          generics_0.1.3    munsell_0.5.1    
[16] tzdb_0.4.0        pillar_1.9.0      rlang_1.1.4       utf8_1.2.4        stringi_1.8.4    
[21] cachem_1.1.0      httpuv_1.6.15     fs_1.6.5          sass_0.4.9        memoise_2.0.1    
[26] timechange_0.3.0  cli_3.6.3         withr_3.0.2       magrittr_2.0.3    digest_0.6.37    
[31] grid_4.4.2        rstudioapi_0.17.1 xtable_1.8-4      hms_1.1.3         lifecycle_1.0.4  
[36] vctrs_0.6.5       glue_1.8.0        rsconnect_1.3.3   fansi_1.0.6       colorspace_2.1-1 
[41] tools_4.4.2       pkgconfig_2.0.3   htmltools_0.5.8.1
```

### Example application *or* steps to reproduce the problem

 

While slightly convoluted the code below demonstrates the issue - to specifically recreate the behavior:

* Run the app

* Click either or both of the action links

* Adjust the slider to n = 3 or greater

The observed behavior is that on the initial click events on either action button the observer(s) are triggered and the `cat()` message(s) show in the console. The unexpected behavior is that when the slider is adjusted the observer(s) for the clicked links are triggered a second time resulting in duplicated `cat()` messages.

The expected behavior is that the observers should only be triggered when the links are clicked and should not be triggered when the `actionLinks()` are recreated by the `renderUI()`.

```R
library(shiny)
library(bslib)
library(tidyverse)

ui = page_sidebar(
  sidebar = sidebar(
    sliderInput("n","Number of links", min = 0, max = 10, value = 2)
  ),
  uiOutput("links")
)

server = function(input, output, session) {
  state = reactiveValues(
    # List used to keep track of our current observers
    observers = list()
  )
  
  observe({
    # Destroy existing observers
    purrr::walk(
      state$observers,
      ~ .x$destroy()
    )
    
    # Reset and create new observers for each of our links
    state$observers = purrr::map(
      seq_len(input$n), 
      function(i) {
        id = paste0("link",i)
        
        observe({
          cat("You clicked link ", i,"!\n",sep="")
        }) |>
          bindEvent(input[[id]])
      }
    )
  }) |>
    bindEvent(input$n)
  
  output$links = renderUI({
    purrr::map(
      seq_len(input$n), 
      function(i) {
        layout_columns(
          actionLink(inputId = paste0("link",i), label = paste0("This is link ",i,"."))
        )
      }
    )
  })
}

shinyApp(ui = ui, server = server)
```

### Describe the problem in detail

In watching the reactlog for this app it seems like the 2nd triggering of the actionLinks comes from the input values being reset to 0 after the new observers are being created which then triggers those observers as the value(s) change from 1 back to 0.

I've been using variations of this code in a couple assignments for a while now and this is the first time I've noticed this particular behavior. I feel like if this had been happening previously I would have noticed, but when I checked this app vs older versions of Shiny (back to 1.7.0) the behavior was consistent.

**Comment by gadenbuie** [comment]
I haven't looked into this too deeply, but you're right, creating a new `actionLink()` involves setting the click counter of the input to 0 – actually a special sentinel value. You might not have run into this with other inputs because typically you'd keep the current input value by setting `value = input[[id]]` in the `renderUI()` when you create the new input.

The easiest way out of this situation is to set `ignoreInit = TRUE` when you `bindEvent(input[[id]])` to ignore the initial reset value.

**Comment by rundel** [comment]
`ignoreInit = TRUE` definitely works - I had used that back in the days of `observeEvent()` but didn't realize that it is available as part of `bindEvent()`.
