### ISSUE TITLE
all-or-nothing selector for checkbox groups

### ISSUE THREAD

**Issue by HarlanH** [rstudio/shiny#42]
Would love the `checkboxGroupInput` to (optionally) have a select all/select none box associated with the group.

**Comment by cc886** [comment]
I love this! An elegant solution!

**Comment by larmarange** [comment]
Could it be relevant to reopen that suggestion?

When using `shiny` with `flexdashboard`, it would be easier for basic users to have a simple option directly within `checkboxGroupInput ()`.

Best regards
