### ISSUE TITLE
Arguments to runApp and friends

### ISSUE THREAD

**Issue by aecay** [rstudio/shiny#440]
I've built a Shiny app which takes a data frame of measurement sites (map coordinates and features measured there) and allows the user to draw various kinds of maps.  The usecase for this app is not a large-scale server deployment, but rather as a tool for individual researchers to download and use to explore various combinations of settings for a (fairly complex) data simplification and plotting procedure.

Currently, the app reads `.GlobalEnv` to offer the user a dropdown list to select the data frame of interest from all the data frames in his/her R session.  However, the case of a user switching between datasets is rare.  What I'd most like is to allow the user to specify their dataset as an argument to the `runApp` function (or `runGitHub`, `runGist`, ...):

```
runApp("explore-maps", dataset = my.data)
```

Then any extra args passed to `runApp` would be accessible as a list in the server function:

```
shinyServer(function (input, output, session, args) {
    dataset <- args[["dataset"]]
    ...
})
```

Is this a possible feature addition?  (Or is there some obvious way to do this using existing features that I've missed?)

**Comment by daattali** [comment]
@jcheng5 I was just experimenting out of curiousity and found this thread. This issue was created long before gadgets existed, which would be another option but involve some refactoring. Just wondering - is your second solution (using an app object) possible to do when there is also a global.R file, without having to manually source the global.R file?

**Comment by oganm** [comment]
It seems like the only "good" solution is using an app object, however that is problematic in terms of organisation if the app is large.

Something like the `.GlobalEnv$.aecay.dataset` solution works fine but I am scared that it might overwrite a user variable. Maybe something like

```r

globalObjects = ls(.GlobalEnv)
if(".aecay.dataset" %in%  globalObjects){
    oldDataset = .GlobalEnv$.aecay.dataset
}
 .GlobalEnv$.aecay.dataset = dataset

on.exit({
    if(exists(oldDataset){
          .GlobalEnv$.aecay.dataset = oldDataset
    } else{
        rm(.aecay.dataset, envir=.GlobalEnv)
    }
})

```

would work reliably but it seems to wordy for something like this.

**Comment by asardaes** [comment]
FYI, I have used a different approach, as mentioned in [this stackoverflow answer](https://stackoverflow.com/a/48831832/5793905). As mentioned there, the key is passing `local=TRUE` to `source`. You can then modularize your app if desired, [here's an example of how I do it in my package](https://github.com/asardaes/dtwclust/tree/master/inst/ssdtwclust), with the launching function defined [here](https://github.com/asardaes/dtwclust/blob/master/R/SHINY-ssdtwclust.R).
