### ISSUE TITLE
fileInput bypass submitButton behavior

### ISSUE THREAD

**Issue by yannrichet** [rstudio/shiny#45]
Trying to use in the same ui a submitButton and a fileInput, it seems that when a file selection is done, the submitButton is not taken into account, that is to say, the output are processed immediatly.

Even if it could be taken as a bug, I think it should be more convenient to have an explicit event handling method for the submitButtton.
Something like a boolean which says if the last event was the press on this button (false if it was any other widget which was updated) ... But I don't know if it is possible with the shiny events policy...
It should also allow to use several buttons on the same ui.

Best regards,
Yann

**Comment by coatless** [comment]
Any eta on this functionality being addressed?

**Comment by jcheng5** [comment]
submitButton edge case bugs are generally unlikely to be fixed; we'd deprecate that feature if we thought we could get away with it, as its overall design is flawed, making it susceptible to lots of bad edge cases.

The actionButton/eventReactive/observeEvent family of functions are far superior, though there is a bit more up-front learning to do.
http://shiny.rstudio.com/articles/action-buttons.html
