### ISSUE TITLE
Operate sliderInput from keyboard

### ISSUE THREAD

**Issue by johnpauls** [rstudio/shiny#511]
For most of the control widgets you can interact with a shiny application by using Tab to select a widget and then arrow keys and enter to pick what you want. However, using Tab will not select a `sliderInput`. Could this be added for `sliderInput` and any other control that does not support this?

**Comment by yihui** [comment]
This is possible now with the new Ion.RangeSlider introduced in the development version of shiny:

```r
devtools::install_github('rstudio/shiny')
library(shiny)
shinyApp(
  ui = fluidPage(sliderInput('foo', 'Press Left or Right', 0, 10, value = 5)),
  server = function(input, output) {}
)
```

Note, however, it seems Tab cannot select the slider, and you have to use click the slider to move the focus on it, then use your arrow keys to change its value.
