### ISSUE TITLE
htmlOutput failing to display html page correctly (only a corner is displayed)

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shiny#519]
I have a problem displaying a HTML page that contains a leaflet map.  It is all well and working if I need to display just that, but my application is multi-tab with various levels of tabsetpanels.

Basically only the upper left corner of the map is displayed, till one resize the browser window.

I create some code that reproduce the problem here:
https://gist.github.com/smartinsightsfromdata/53029bce950049b8beab

Cheers  Enzo

**Comment by wch** [comment]
I think the problem is that you're trying to include a complete HTML file, which has its own head and body sections. This results in malformed HTML, which you can see in a browser by viewing the HTML source. The `includeHTML` function is really meant to include HTML fragments, not entire documents.
