### ISSUE TITLE
unable to load tcltk on installation

### ISSUE THREAD

**Issue by hudon** [rstudio/shiny#52]
When I run `install.packages("shiny")`, I get this error:

```
Loading Tcl/Tk interface ... Error: .onLoad failed in loadNamespace() for 'tcltk', details:
    call: dyn.load(file, DLLpath = DLLpath, ...)
    error: unable to load shared object '/usr/lib/R/library/tcltk/libs/tcltk.so':
    libtk8.5.so: cannot open shared object file: No such file or directory
```

So I tried `install.packages("tcltk2")`, which gives me the same error. Is there a requirement for this package I am missing?

Arch Linux x86_64
R 2.15.2

**Comment by erstern** [comment]
I encountered the same problem, have you already solved? Thx!

**Comment by benjaminengel** [comment]
On archlinux you just have to install the `tk` package with `sudo pacman -S tk`.

**Comment by erstern** [comment]
@benjaminengel Thanks for your reply.

I have found the solution via the internet and solved it last weekend. I use another distro Manjaro based on Arch.

At the beginning, the reason that the package tcltk, pbatR needed, can't run on R is I have not install gcc-fortran on the system.
