### ISSUE TITLE
browser elements vanish from screen under shiny 0.10.0

### ISSUE THREAD

**Issue by leonawicz** [rstudio/shiny#530]
In this example, the "Generate plot" button does not remain display on the screen once it appears. It shows briefly and then vanishes. This does not happen with previous shiny versions. Just FYI, the plot button should not do anything when clicked (say, in shiny 0.9.1) because I've stripped the code down to the simplest app that will reveal the buggy behavior. This means I removed all the plotting code, etc. All I am trying to do here is get the "Generate plot" button to remain in the browser once it appears.

ui.R

shinyUI(fluidPage(
	uiOutput("GoButton"),
	selectInput("datachoices","Choose dataset:",choices=c("", c("a","b","c")),selected="",multiple=T, width="100%"),
	checkboxInput("adjustdata","Adjust data", FALSE),
	uiOutput("PlotButton")
))

server.R

library(shiny)
shinyServer(function(input, output, session){

	# Get the name(s) of the dataset(s)
	dataSelections <- reactive({
		x <- c()
		if(!is.null(input$datachoices)) x <- input$datachoices
		ind <- which(x=="")
		if(length(ind)) x <- x[-ind]
		if(!length(x)) x <- NULL
		x
	})
	
	# Possibly alter the name(s) of the dataset(s)
	datasetName <- reactive({
		x <- dataSelections()
		if(!is.null(input$adjustdata)){
			if(input$adjustdata & !is.null(theDataFrame())) x <- dataSelections() # could do something different here
		}
		x
	})
	
	# If there are names, show the button for subsetting the data
	output$GoButton <- renderUI({
		if(!is.null(datasetName())) actionButton("goButton", "Subset Data")
	})

	# Only react to input$goButton. NUll if no button, button never pressed at least once, or dataSelections() still NULL
	theDataFrame <- reactive({
		if(is.null(input$goButton) || input$goButton==0) return()
		isolate(
			if(is.null(dataSelections())){
				x <- NULL
			} else {
				x <- "I am not NULL"
			}
		)
		#browser()
		x
	})
	
	# If theDataFrame is not NULL, then it is okay to show the plotButton
	output$PlotButton <- renderUI({
		if(!is.null(theDataFrame())) actionButton("plotButton", "Generate Plot")
	})

})

**Comment by yihui** [comment]
Closing the issue since it seems the original problem has been solved (please feel free to re-open if not).
