### ISSUE TITLE
Translation of UI text/messages

### ISSUE THREAD

**Issue by yihui** [rstudio/shiny#547]
Not sure if it is possible, but it has been asked a few times in shiny-discuss.

**Comment by wch** [comment]
Could you give an example of what you mean here?

**Comment by yihui** [comment]
This is actually a general R issue, so we can close it. Basically I meant something like `textInput(id, gettext('A label that may be translated'))`. I was hoping to provide an example, but i18n does not seem to be straightforward unless it is an R package (cf http://stackoverflow.com/q/10765057/559676).

**Comment by motin** [comment]
The projects I have found around solving this issue:
 * https://github.com/Appsilon/shiny.i18n (28 stars, last activity 1 month ago)
 * https://github.com/chrislad/multilingualShinyApp (8 stars, last activity 4 years ago)

It seems shiny.i18n is the best bet at the moment. I added an issue requesting support for gettext https://github.com/Appsilon/shiny.i18n/issues/15 as per the link in @yihui's comment.
