### ISSUE TITLE
Why should not create the ui Just Like html js css files?

### ISSUE THREAD

**Issue by joostshao** [rstudio/shiny#556]
Why should not create the ui Just Like html js css files?
I am a web developer, i think the style of creating ui in Shiny is diffcult.
just like MFC or Qt.
it will be great if create ui with css,html,js.

**Comment by NadeemIqbalSaif** [comment]
Hi jcheng5,
my app works well on LAN but while hosting on internet despite running the server behind Apache in a reverse proxy mode the app does not do what its meant to do. I think its unable to find some CSS and JS files/libraries.

Any help will be much appreciated!
