### ISSUE TITLE
Use of row selection in datatables for drill-down

### ISSUE THREAD

**Issue by pssguy** [rstudio/shiny#613]
It seems that row selection as in /https://demo.shinyapps.io/029-row-selection/ is now implemented. I would like to have the row selected be used as a drill down leading to another table and/or charts

I have a couple of queries.

 a) Given the acquisition of the row-index( as per the above example input$rows) , is it possible to reference values in specific columns of that row.  Use of input$rows alone
   is incorrect if the table has been sorted

b) The default seems to be that after clicking on one row, the next row clicked is additive rather a replacement. If I only want only the new row selected (which would be normal practice) then I have to click the first row again  This is counter-intuitive. On windows I would expect to use control or shift keys to select more than one row

**Comment by jerrymcummings** [comment]
I am curious about row selection (described by edmundex) when changing pages too. I see the same behavior in the sample and my tests. I was *so* hopeful that this would be the solution.

**Comment by yihui** [comment]
@jerrymcummings This issue is a little challenging, but I think it is solvable.

**Comment by yihui** [comment]
@jerrymcummings Yeah, it is a shame that the selections will be lost if you navigate to other pages. I have been working on this problem again recently, and I have got a working example, but I will have to discuss with other people in the team before I can show you the final solution. Sorry for the long delay.

**Comment by jerrymcummings** [comment]
I appreciate the consideration that the issue is being given. Thank you.

**Comment by smartinsightsfromdata** [comment]
@yihui I'm really keen to have a look when you think it is right.  Thanks!

**Comment by yihui** [comment]
I think the row selection in the DT package should be usable now. Please see https://github.com/rstudio/DT/issues/20#issuecomment-77943180 @jerrymcummings @edmundex @pssguy @robAndrewCarter
