### ISSUE TITLE
validate inside downloadHandler filename is strange

### ISSUE THREAD

**Issue by jpritikin** [rstudio/shiny#622]
If I call validate inside of downloadHandler's filename function then the error appears in a separate window. It's strange. Is this a bug? Is there a better way to do it?

**Comment by wch** [comment]
I believe the root cause is the same as #669, which is fixed. Could you try again with the latest development version?

**Comment by jpritikin** [comment]
I changed the way I handle loading data to avoid this problem. I think my new solution is altogether better so I don't need this to work anymore. Thanks for fixing it though.
