### ISSUE TITLE
better sanity checking of update*Input

### ISSUE THREAD

**Issue by jpritikin** [rstudio/shiny#629]
If I write something like updateNumericInput("focusedRecodeRule", ...) then I get an error like "$ operator is invalid for atomic vectors". It would be nice if shiny said, "You idiot. You must pass session as the first argument to update*Input on line XXX."

**Comment by wch** [comment]
`session` should also default to `getDefaultReactiveDomain()`. It's too bad reactive domains didn't exist when we added these functions; if they did, we could move the `session` argument to be the last argument, so that users would never have to pass it explicitly.

**Comment by jpritikin** [comment]
Sounds like a good API change to make when you start working on shiny2.
