### ISSUE TITLE
plotOutput height scalling issue

### ISSUE THREAD

**Issue by jangorecki** [rstudio/shiny#650]
I'm currently not able to scale well my plot.
Default `height` in `plotOutput` is fixed to `400px` while I would expect to have `100%` there to keep the aspect ratio of my plot.
Yet I'm not able to provide `height="100%"`, see below:

``` r
runApp(list(
  ui =   fluidPage(
    h1("plotOutput - WORKS"),
    plotOutput("Oplot_myplot"),
    h1("plotOutput height=600px - WORKS"),
    plotOutput("Oplot_myplot2", height="600px"),
    h1("plotOutput height=100% - DOESN'T WORK"),
    plotOutput("Oplot_myplot3", height="100%")
  ),
  server = function(input, output, session) {
    output$Oplot_myplot <- renderPlot(plot(1:100))
    output$Oplot_myplot2 <- renderPlot(plot(1:100))
    output$Oplot_myplot3 <- renderPlot(plot(1:100))
  }
))
```

The `plotOutput("x", height="100%")` simply doesn't work.

The question is: how can I keep correct aspect ratio in my plot in shiny?

``` r
packageVersion("shiny")
[1] ‘0.10.2.1’
```

**Comment by skparkes** [comment]
This is not well documented anywhere else that I have found.  Please consider putting this either in the tutorial, or as an example in `plotOutput()` and/or `renderPlot()`.

**Comment by ThoDuyNguyen** [comment]
Is there anything new about this?

**Comment by PoLabs** [comment]
Could you please explain that function a bit more? Simply trying to fit a wordcloud to a fluidRow box has been a nightmare. 

session$clientData$output_plot1_width

what is session? What is clientData? What is output_plot1_width? I am confused as none of those are in your ui or server code.

**Comment by jcheng5** [comment]
session is one of the arguments to the server function, you can see it in my code snippet. That code should work if you just replace the "plot1" in output_plot1_width with your plotOutput's actual id.

**Comment by sreifenb** [comment]
This already helped a lot, even after more than four years - thank you!

If I get it right, it's only possible to access width and height of outputs, but not UI elements in general, e.g. the height of a wellPanel?

**Comment by jcheng5** [comment]
@sreifenb That's correct, only outputs have this built-in support for sending their height/width/visibility.

**Comment by Rhydderch** [comment]
Hi @hadley, your solution works (server side defined height), thank you for that.
However, the tabbox I'm using doesn't scale in height and the plot overflows.
![image](https://user-images.githubusercontent.com/3197629/86137606-c3032480-baed-11ea-9f2d-ef0f5301c281.png)

How can I fix this?

**Comment by mf-rug** [comment]
It's a neat solution, but for some reason it makes loading the plot considerably slower; got a lag of an extra 3 seconds or so. Is that to be expected? Would be great if [#2470](https://github.com/rstudio/shiny/issues/2470) would come..

**Comment by cpsievert** [comment]
@mf-rug that's surprising. I don't think #2470 will necessary solve the "fill page" issue, but note there is now a `fillPage()` that offers a much better solution to https://github.com/rstudio/shiny/issues/650#issuecomment-62443654 (with this approach the height will adjust to resizing of the browser correctly)

```r
library(shiny)
runApp(list(
    ui = fillPage(
        plotOutput("plot1", height="100%")
    ),
    server = function(input, output, session) {
        output$plot1 <- renderPlot({
            plot(cars)
        })
    }
))
```
