### ISSUE TITLE
Add a function that returns valid names / completions on session object

### ISSUE THREAD

**Issue by kevinushey** [rstudio/shiny#657]
E.g., for:

``` R
shinyServer(function(input, output, session) {
    session$
})
```

it would be useful for the RStudio IDE (and potentially other editors) to be able to get a set of valid completions from Shiny for `session`.

Would it be feasible to add a function, `shiny:::session_completions()`, that returns the completions for these in some format?

It would be useful if this were returned as a named list, where names were the valid completions, and the entries had metadata for the completion 'type', e.g.

``` R
list(
    someVariable = list(type = "variable"),
    someFunction = list(type = "function", arguments = list(a = , b = ,), returns = list())
)
```

I can implement this myself and submit a PR if the valid objects defined for `$` on session are enumerated somewhere.

**Comment by wch** [comment]
@kevinushey As of 4dde16d8365e99aa347c353aa4d34f8f5d6c25e7, the `ShinySession` object (which is passed to the function as `session`) is simply an R6 object with some public and private members. Is that sufficient for autocompletion?

**Comment by kevinushey** [comment]
RStudio's autocompletion should understand how to produce completions from R6 objects, so that should work fine.

However, we're still attempting to get these completions in the context of e.g.

    shinyServer(function(input, output, session) { ... })

and so when editing the document, that `session` object doesn't exist in the R workspace yet, right? So in the end, we do need to say, "is this the `session` object associated with a `shinyServer` call?", to produce correct completions. Does that sound correct?

**Comment by wch** [comment]
Oh, that's correct - the `session` object isn't created until the app is started.

Would it be generally useful if an R6 generator object (`ShinySession` in this case) could give you the completions for instances of the class, (`session`)? I think implementing that in R6 should be pretty straightforward. For this case, you'd still need to give RStudio special knowledge that `session` will be a `ShinySession` object.

**Comment by kevinushey** [comment]
Yes, that would be very helpful! (and we can definitely verify that within RStudio)

**Comment by alandipert** [comment]
It seems this thread ultimately morphed into an R6 enhancement - @wch feel free to close this one, or otherwise keep it open if it's still helpful to you.

**Comment by alandipert** [comment]
I'm closing this because r-lib/R6#47 carries the torch, but please don't hesitate to re-open or create a new issue if I misunderstand.
