### ISSUE TITLE
updateSliderInput in shiny html_document

### ISSUE THREAD

**Issue by n-dim** [rstudio/shiny#659]
I try to pack this into an shiny html_document:
ui.R:
```R
fluidPage(
  sliderInput("controller", label = "Controller:", min = 1, max = 10, value = 1),
  sliderInput("reactiveSlider", label = "reactive slider:", min = 1, max = 100, value = 1)
)
```

server.R:
```R
shinyServer(function(input, output, session) {
  observe({
    updateSliderInput(session, "reactiveSlider", value = input$controller * input$controller)
  })
})
```
like this: 
test.Rmd

    ---
    runtime: shiny
    output: html_document
    ---
    ```{r, echo=FALSE}
    inputPanel(
      sliderInput("controller", label = "Controller:", min = 1, max = 10, value = 1),
      sliderInput("reactiveSlider", label = "reactive slider:", min = 1, max = 100, value = 1)
    )    
    
    observe({
      updateSliderInput(session, "reactiveSlider", value = input$controller * input$controller)
    })
    ``` 
When I use the ui.R and server.R variant it works. But if I pack both into a markdown document (test.Rmd) after I press "Run document" it opens a new window and tries to load the document, but never finishes loading. The console states "Output created" and gives no error, but the page doesn't load.

If I change `input$controller * input$controller` to simply `input$controller` it works, but as soon as I use two times `input$anything` the page doesn't load. Even if I use for example `input$controller * input$controller2` and define another sliderInput "controller2" in the inputPanel.

I am working with shiny 0.10.1 in RStudio 0.98.1091 and R version 3.0.1 on a Mac. The same happens on shiny 0.10.2.1, RStudio 0.98.945, R version 3.1.2 on Ubuntu.

**Comment by wch** [comment]
Fixed by #606.
