### ISSUE TITLE
argument 'step' is not working as documented in sliderInput()

### ISSUE THREAD

**Issue by pbiecek** [rstudio/shiny#667]
In the documentation for sliderInput() the ‘step’ parameter has comment ‘(NULL means no restriction)‘

However, in the function sliderInput() there is 
```
   if (is.null(step)) {
        if (range < 2 || hasDecimals(min) || hasDecimals(max)) {
            step <- pretty(c(min, max), n = 100)
            step <- step[2] - step[1]
        }
        else {
            step <- 1
        }
    }
```

So, for step=NULL and min = 0, max = 3 the step is set to 1 (while doc promises 0.03).
The change in documentation would fix that, but actually it might be better to fix the code by removing ‘if (range < 2 || hasDecimals(min) || hasDecimals(max))’

**Comment by wch** [comment]
Fixed in 2655c25.
