### ISSUE TITLE
Responsiveness/scaling of pictures has changed

### ISSUE THREAD

**Issue by rappster** [rstudio/shiny#671]
Just tested with `0.10.2.9006`. Seems like the automatic scaling of pictures or the way responsiveness is implemented has changed as things look pretty messy now compared to when running it with `0.10.2.2`. 

This is what things used to look like:
![pic_2](https://cloud.githubusercontent.com/assets/1205659/5395049/12c41206-8145-11e4-9dd0-a2976426c55e.png)

This is what it looks like now:
![pic_1](https://cloud.githubusercontent.com/assets/1205659/5395052/19e9a406-8145-11e4-9137-7fb8a02f0913.png)

**Comment by wch** [comment]
We've settled on the second option -- you'll have to add the `img-responsive` class to your images.
