### ISSUE TITLE
Reactive Slider not working when rendering a html file

### ISSUE THREAD

**Issue by MarBlo** [rstudio/shiny#679]
I am a new to github and try my first steps in shiny. I have encountered a problem and posted a question concerning this problem at [stackoverflow] (http://stackoverflow.com/questions/27580760/reactive-slider-in-shiny-and-rendering-a-html-file-does-not-work-together?noredirect=1#comment43600832_27580760).
There was one answer or comment to my question stating that this is possibly due to a bug and suggesting to post it here. I hope this is the right way to go.

**Comment by wch** [comment]
Can you supply a reproducible example? We'd need not just the server.R and ui.R files, but also the file you're trying to include.

**Comment by MarBlo** [comment]
Hi Winston,

here is a simple html. and rmd.file I tried out.

BR, MB



Am 05.01.2015 um 18:04 schrieb Winston Chang <notifications@github.com>:

**Comment by wch** [comment]
Can you post it in the github issue? If you sent it as an attachment, it was stripped out so I didn't receive it.

**Comment by MarBlo** [comment]
Sure, here is the html.file I wanted to include.

```html
Untitled
Garrett
July 10, 2014
Some inline R code, 4.
This is a text test.
Equations
Equations are included by using LaTeX notation and including them either between single dollar signs (inline equations) or double dollar signs (displayed equations). If you hang around the Q&A site CrossValidated you’ll be familiar with this idea.
There are inline equations such as \(y_i = \alpha + \beta x_i + e_i\).
And displayed formulas:
\[\frac{1}{1+\exp(-x)}\]
new
\(\sqrt[3]{x}\)
\(FG = \sqrt[3]\frac{D}{V}\)

```
