### ISSUE TITLE
downloadHandler() not working with raster::writeRaster()

### ISSUE THREAD

**Issue by mbacou** [rstudio/shiny#680]
I'm trying to write and download multiband rasters through the downloadHandler, no problem in the console, but the same code fails in shiny.

```{r}
  output$saveData <- downloadHandler("test.tif", function(file) {
writeRaster(r, file, format="GTiff", bylayer=F, options="INTERLEAVE=BAND", overwrite=T)  })
```

**Comment by mbacou** [comment]
For others, here is a workaround when multiple files have to be zipped.
```
# in server.ui
writeZip <- function(x, file, filename, format, ...) {
  if (format=="ESRI Shapefile") {
    writeOGR(x, "./", filename, format, overwrite_layer=T, check_exists=T)
  } else {
    writeRaster(x, filename, format, bylayer=F, overwrite=T, ...)
  }
  f <- list.files(pattern=paste0(strsplit(filename, ".", fixed=T)[[1]][1], ".*"))
  zip(paste0(filename, ".zip"), f, flags="-9Xjm", zip="zip")
  file.copy(paste0(filename, ".zip"), file)
  file.remove(paste0(filename, ".zip"))
}

output$saveData <- downloadHandler(filename,
  function(file) {
    x <- "some data to write"
    path <- "path to write files to"
    format <- "argument passed to writeRaster or writeOGR (needed in my case)"
    writeZip(x, file, path, format)
})
```

**Comment by SantoshJadhav** [comment]
Hi, I am facing similar problem while using the writeDoc function of reporters package. I wanted to provide user a option to download a pptx file created using reporters package. I am receiving an error as invalid file. I tried to mention the content type required for pptx file extension but nothing is working out. Can anybody help me on the same, My downlad handler is as below:

 output$downloadData <- downloadHandler(
    filename = function() { 
      paste('Sample', '.pptx', sep='') 
    },
    content = function(file) {
      myppt = pptx(title = 'Sample PPT')
      myppt = addSlide( myppt, "Title Slide" )
      res <- writeDoc(myppt, file)
    },
    contentType = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
  )

**Comment by FrankSauvage** [comment]
Hi, I got the same, end up here and see you got no answer yet Santosh... 
After more hours of trials and fails, I finally came up with a solution!

The trick here is that the document is first written in a temporary file (that I called "tempfile.pptx" below). With a better understanding of the steps thanks to these trials, it appeared the difficulty was making this temporary file to be copied in the chosen "file" from the filename function.
I got the main successful inspiration from here 
http://shiny.rstudio.com/gallery/download-knitr-reports.html
but it was not straightforward for our specific case. Here the modifications that should make things work according to my own  downloadHandler()

output$downloadData <- downloadHandler(
filename = function() {
paste('Sample', '.pptx', sep='')
},
content = function(file) {
myppt = pptx(title = 'Sample PPT')
myppt = addSlide( myppt, "Title Slide" )

#res <- writeDoc(myppt, file)      #assigning writeDoc() return NULL, so it isn't relevant. And "file" is #an arbitrary & not meaningful name at this stage, not the result from filename yet. Rather do:

writeDoc(myppt, "./tempfile.pptx")  # "./" make the temporary file to be in your app's directory,
# easy to retrieve

flist <- list.files("./","^tempfile.pptx$", full.names = TRUE) #flist will get the path to the temporary PPT #file as an accurate "from" argument for file.copy()

file.copy(flist, file) #do the copy in the chosen local "file"
}
#the following is not necessary from my experience
#,
#contentType = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
)

I hope this will help people to avoid having a hard time to make the amazing Shiny and ReporteRs tools to communicate. Do not forget also that downloadHandler() does not really work from the RStudio App Viewer. Do the trials from the browser to monitor its behaviour then.

This is my first post here and it is late, so I apologize for the very poor form of my comment.
