### ISSUE TITLE
Chrome browser does not display page unless already open in Shiny

### ISSUE THREAD

**Issue by jmrichardson** [rstudio/shiny#681]
Edit:  I can get my code to post correctly.  Here is a link to the same question on stackoverflow:
http://stackoverflow.com/questions/27609651/chrome-browser-does-not-display-page-unless-already-open-in-shiny?noredirect=1#comment43641763_27609651

I am able to launch the shiny app when chrome browser is already open in my desktop (linux). However, with my browser closed, and I launch the shiny app, it just shows a blank page and "waiting 127.0.0.1 ..." in lower status bar. In other words, it launches chrome but does not show the shiny app content. Here is my code:

library(shiny)

launch.browser = function(appUrl, browser.path='/usr/bin/chromium-browser') {
  system(sprintf('"%s" --disable-gpu --app="data:text/html,<html>
<head>
<title>Configuration</title>
</head>
<body>

<script>window.resizeTo(800,500);window.location=\'%s\';</script>

</body></html>"', browser.path, appUrl))
}

shinyApp(

  ui = fluidPage(
    fluidRow(
      br(),
      wellPanel(
        fluidRow(
          h4('User Information')
        ),
        fluidRow(
          column(4,
            textInput('Name', 'Full Name', value = "")
          ),
          column(4,
            numericInput('accNum', 'Account Number', value = "")
          ),
          column(4,
            textInput('token', 'Account Token', value = "")
          )
        )
      )
    ),

```
fluidRow(
  column(12,
     actionButton('save', 'Save')
  )
)
# tags$head(tags$style(type="text/css", "#accNum {width: 100px}"))
```

  ), 

  server = function(input, output, session) {
    session$onSessionEnded(function() {
      stopApp()
    })
    observe({
      if (input$save == 0)
        return()
      isolate({
        j<<-input$accNum
      })
    })

  },
  options = list(launch.browser=launch.browser)
)
Thanks for any help

**Comment by Dripdrop12** [comment]
Where should we put the `&` @wch?
