### ISSUE TITLE
radioButtons(inline=TRUE) not showing horizontal radio boxes

### ISSUE THREAD

**Issue by mbacou** [rstudio/shiny#683]
The generated class reads `<label class="radio inline">`, should be `<label class="radio-inline">` instead.

**Comment by wch** [comment]
What version of Shiny are you using? The latest dev version should produce `radio-inline`.

**Comment by mbacou** [comment]
Hi,
I'm on version 0.10.2.2. http://hcapi.harvestchoice.org/ocpu/library/shiny/info

**Comment by wch** [comment]
You're right that with 0.10.2.2, it has `class="radio inline"`, but that's the correct class for Bootstrap 2, which is used in that version of Shiny. See the "Inline checkboxes" section here: http://getbootstrap.com/2.3.2/base-css.html

This test app should show checkboxes and radio buttons inline:

```R
  shinyApp(
    ui = fluidPage(
      checkboxGroupInput("variable", "Variable:", inline = TRUE,
                         c("Cylinders" = "cyl",
                           "Transmission" = "am",
                           "Gears" = "gear",
                           "Horsepower" = "hp",
                           "Weight" = "wt")),
      radioButtons("radio", "Variable:", inline = TRUE,
                         c("Cylinders" = "cyl",
                           "Transmission" = "am",
                           "Gears" = "gear",
                           "Horsepower" = "hp",
                           "Weight" = "wt"))
    ),
    server = function(input, output) {}
  )
```

**Comment by mbacou** [comment]
OK that clarifies. Shall I downgrade to Bootstrap 2 or is this updated in a newer release of Shiny?

**Comment by OleksiyAnokhin** [comment]
Sorry for disturbing, trying to add inline = TRUE, does not work. Any ideas for the code below? 

    div(id='typeInput', 
                                   class="form-group shiny-input-checkboxgroup shiny-input-container shiny-
    bound-input",
                                   
                                   # this was written in order to "separate" checkboxes accross page upon Soren's request for customization 
                                   tags$br(),
                                   tags$br(),
                                   column(width = 7, 
                                          tags$img(src = "Bank.png", height = 50, width = 50), h4(tags$b("BANKS")),
                                          HTML("<input type=checkbox name=typeInput value=Bank>"),
                                          h4(tags$em("1. Bank")),
                                          h4(tags$em("2. Bank")),
                                          h4(tags$em("3. Bank")),
                                          h4(tags$em("4. Bank")),
                                          h4(tags$em("5. Bank")),
