### ISSUE TITLE
shine() generic method

### ISSUE THREAD

**Issue by Mullefa** [rstudio/shiny#686]
@hadley uses the function `shine()` in his package [lineprof](https://github.com/hadley/lineprof). I would like to use it in some of my packages too. 

Would it make sense to add it as a generic in the shiny package? It might act as incentive for people to develop further `shine()` methods too. If not, what would you recommend? 

Cheers.

**Comment by alandipert** [comment]
A belated thank-you for the suggestion.

Shiny and RStudio IDE now have [comprehensive support for visualizing profile data](https://blog.rstudio.com/2016/05/23/profiling-with-rstudio-and-profvis/).
