### ISSUE TITLE
sliderInput with date format

### ISSUE THREAD

**Issue by kismsu** [rstudio/shiny#689]
Hi, based on http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html new sliderInput should work with date format, however I don't think it is working at moment.

```r
runApp(list(
    ui = basicPage(
        sliderInput('foo1', 'How many days after today?', min = Sys.Date() -10, 
                           max = Sys.Date(), value = Sys.Date() - 1)
    ),
    server = function(input, output, session) {
    }
))
```

Returned an error 
```
Error in `/.difftime`(n_steps, scale_factor) : 
  second argument of / cannot be a "difftime" object
```
Do have in mind to implement it?

**Comment by wch** [comment]
Right, it's not implemented in Shiny yet. But we hope to do that in a future version of Shiny.

**Comment by edbarbaro** [comment]
It would be useful to have that functionality! Looking forward to it
