### ISSUE TITLE
Embedding tracking script in Navbar Page results in bug

### ISSUE THREAD

**Issue by mhnierhoff** [rstudio/shiny#690]
When I add a tracking script as described in the guide (http://shiny.rstudio.com/articles/google-analytics.html), the first tab isn't selected anymore. Instead a box empty box next to the title and the first tab is selected. The window under the navbar remains empty. Without tracking script everything works as it should.

![navbarpage_bug](https://cloud.githubusercontent.com/assets/2846718/5786776/0650c646-9deb-11e4-819e-fa3606449d48.jpg)

**Comment by zero323** [comment]
I don't it is a bug. `shiny::navbarPage` expects `...` to be a `tabPanel` elements and for each of these creates anchor. This is the box you see. If you want to add other element you can use `header` or `footer` arguments:

```
shinyUI(navbarPage(
    title='Some title',
    header=singleton(tags$head(includeScript('some_path')),
     ...
))
```

**Comment by yihui** [comment]
Thanks @zero323. I believe you are correct.
