### ISSUE TITLE
dateRangeInput not working on Safari

### ISSUE THREAD

**Issue by josep2** [rstudio/shiny#691]
See the following gist:

run this gist: runGist("https://gist.github.com/withr/9506930")

Works with all other browsers.

**Comment by wch** [comment]
I'm not able to replicate this on my computer, which is running OS X 10.10.2, and Safari 8.0.3 (10600.3.18). What versions are you using?

**Comment by wch** [comment]
Closing for now. If you're still experiencing this and have information about the browser version, you can re-open.
