### ISSUE TITLE
withMathJax breaks conditionalPanel in renderUI

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#692]
When using renderUI, conditionPanel stops working when withMathJax is used. Reproducible example linked below. This happens for both shiny 0.10.2.2 and 0.11. The conditionalPanels work as intended when the withMathJax line in server.R is commented out.

https://github.com/mostly-harmless/withMathJax

> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.10.2.9006

loaded via a namespace (and not attached):
[1] digest_0.6.8    htmltools_0.2.6 httpuv_1.3.2    mime_0.2        R6_2.0.1        Rcpp_0.11.3     RJSONIO_1.3-0  
[8] tools_3.1.2     xtable_1.7-4

**Comment by yihui** [comment]
Thanks for the report. This is really weird, and I was unable to figure out the reason. I rewrote your example without using `conditionalPanel()`, though:

```r
library(shiny)

shinyApp(
  
  ui = fluidPage(
    radioButtons(inputId = "dataType", label = "Load data:",
                 c("rda" = "rda", "csv" = "csv",  "clipboard" = "clipboard"),
                 selected = "rda"),
    uiOutput("x1"),
    uiOutput("x2"),
    withMathJax("$$\\sqrt{2}$$")
  ),
  
  server = function(input, output, session) {
    
    output$x1 <- renderUI({
      if (input$dataType == 'csv')
        checkboxInput('header', 'Header', TRUE)
    })
    output$x2 <- renderUI({
      if (input$dataType == 'clipboard')
        actionButton('loadClipData', 'Paste data')
    })
    
  }
)
```

**Comment by mostly-harmless** [comment]
Thanks @yihui. I tried to provide an example that was simple and demonstrated the issue. Unfortunately I have the same issue in a much larger app where I (most likely) cannot avoid using conditional panel.

**Comment by wch** [comment]
@yihui When I run the example, I get this in the JS console:

```
 Uncaught ReferenceError: MathJax is not defined VM870:1 (anonymous function)
```

The Javascript code that causes the error is part of the HTML that's injected into the web page:

```html
  <script>MathJax.Hub.Queue(["Typeset", MathJax.Hub]);</script>
```

I suspect the error has something to do with that code being run before the MathJax resource is actually loaded.

The `singletons.renderHtml` function does insert this into the head before inserting the previous script into the body, but I think the body script still ends up trying to run first.

```html
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>
```

**Comment by wch** [comment]
I'm using a simplified test app:

```R
library(shiny)
server <- function(input, output, session) {
  output$ui <- renderUI({
    fluidPage(
        radioButtons(inputId = "radio", label = "Select:", c("first", "second")),
        conditionalPanel(condition = "input.radio == 'first'",
          "First selected"
        ),
        conditionalPanel(condition = "input.radio == 'second'",
          "Second selected"
        )
        , withMathJax("$$\\sqrt{2}$$")
        # , sliderInput("slider", "Slider", 1, 10, 5)
     )
  })
}

ui <- bootstrapPage(uiOutput("ui"))

shinyApp(ui, server)
```

Stepping through the shiny.js code, I see that MathJax.js doesn't load immediately. It stays in the pending state as I step through the code:

![image](https://cloud.githubusercontent.com/assets/86978/6151680/0dd4dbb8-b1dd-11e4-8e7c-81757df0ed1e.png)


 When compared to `sliderInput`, I found that the `sliderInput` Javascript resources do load immediately (and in so doing, trigger this warning: `Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience`).


One difference between `sliderInput` and `withMathJax` is that the former uses `htmlDependency`, while the latter uses `singleton`.

I tried modifying `withMathJax` so that it uses `htmlDependency`:

```R
withMathJax <- function(...) {
  dep <- htmlDependency("MathJax", "99.9",
    src = c(href = "https://cdn.mathjax.org/mathjax/latest"),
    script = "MathJax.js?config=TeX-AMS-MML_HTMLorMML"
  )

  attachDependencies(
    tagList(
      ...,
      tags$script(HTML('MathJax.Hub.Queue(["Typeset", MathJax.Hub]);'))
    ),
    dep
  )
}
```

The problem still remains, however: the browser doesn't load MathJax immediately. I suspect the reason is that the browser doesn't want to load the remotely-hosted resource immediately. (In contrast, the `sliderInput`'s resources are local.) 

So here are some possible solutions:

1. Force the script to load synchronously. ([SO discussion](http://stackoverflow.com/questions/10506857/script-not-executing-with-a-dynamically-generated-jquery-script-tag))
2. Add MathJax's resources to Shiny. (Not tested yet, and behavior may be browser-dependent)
3. Make the snippet of JS code run only after the MathJax library is loaded. ([SO discussion](http://stackoverflow.com/questions/3248384/document-createelementscript-synchronously)) I think this is a bit dangerous as a general solution for Shiny, because in some cases, a script must be loaded before an input can return values.


@yihui, @jcheng5 A couple questions:

* Why does the [`withMathJax`](https://github.com/rstudio/shiny/blob/61b83c3e34d8f2f5551817d0a408320a24c2cbcc/R/shinyui.R#L16-L25) function uses `singleton` instead of `htmlDependency`?
* Why does Shiny get MathJax from a CDN?

**Comment by mostly-harmless** [comment]
When I tried to use Mathjax locally it was HUGE. In case it is useful in this discussion, @timelyportfolio just posted a binding to Katex (math renderer used/developed) by Kahn Academy that is faster and  lightweight (in comparison).

https://github.com/timelyportfolio/katexR

**Comment by wch** [comment]
@mostly-harmless If need MathJax working now, you can simply include `withMathJax()` statically in a page.

**Comment by mostly-harmless** [comment]
I use mathjax in modals and Rmd files rendered in my Shiny app to provide user help files / documentation. For the modal I use the code snippet below where I just stick the call to mathjax in the last line. It works ... most of the time .. so I am ok-ish for now. I tried using withMathJax for this but it messes up the conditional panels which led to the issue report. If you have a better work-around that is a bit more reliable please do let me know. I'm not sure exactly what you mean by 'statically in a page'. Thanks for looking into this!

`help_and_report <- function(modal_title, fun_name, help_file) {
  sprintf("<div class='modal fade' id='%s_help' tabindex='-1' role='dialog' aria-labelledby='%s_help_label' aria-hidden='true'>
            <div class='modal-dialog'>
              <div class='modal-content'>
                <div class='modal-header'>
                  <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
                  <h4 class='modal-title' id='%s_help_label'>%s</h4>
                  </div>
                <div class='modal-body'>%s</div>
              </div>
            </div>
           </div>
           <i title='Help' class='glyphicon glyphicon-question-sign alignleft' data-toggle='modal' data-target='#%s_help'></i>
           <i title='Report results' class='glyphicon glyphicon-book action-button shiny-bound-input alignright' href='#%s_report' id='%s_report'></i>
           <div style='clear: both;'></div>
           <script type='text/javascript' src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>",
          fun_name, fun_name, fun_name, modal_title, help_file, fun_name, fun_name, fun_name) %>%
  enc2utf8 %>% HTML`

**Comment by wch** [comment]
@mostly-harmless, I mean that you can put `withMathJax()` somewhere in the (non-dynamic) UI, and this will cause MathJax to load when the page loads. It's the dynamic loading of MathJax that causes the problem - what happens is that the Javascript snippet tries to access the `MathJax` object before the MathJax resources are loaded, and that throws an error that interrupts the execution of other Shiny code, including the `conditionalPanel` parts.

Here's the example from above modified to have `withMathJax()` in the UI:

```R
library(shiny)
server <- function(input, output, session) {
  output$ui <- renderUI({
    fluidPage(
        radioButtons(inputId = "radio", label = "Select:", c("first", "second")),
        conditionalPanel(condition = "input.radio == 'first'",
          "First selected"
        ),
        conditionalPanel(condition = "input.radio == 'second'",
          "Second selected"
        )
        , withMathJax("$$\\sqrt{2}$$")
     )
  })
}

ui <- bootstrapPage(uiOutput("ui"), withMathJax())

shinyApp(ui, server)
```

**Comment by mostly-harmless** [comment]
Thanks Winston. I did notice this at some point when I made a change to some code that removed withMathJax from the ui. Buttons started (dis)appearing when they shouldn't. I will try this approach again.

**Comment by yihui** [comment]
@wch `withMathJax()` was written before **htmltools** was born, which explains why it did not use `htmlDependency()`...

I think including `withMathJax()` in the static UI should fix the error of `"MathJax not defined"`.

**Comment by mostly-harmless** [comment]
FYI Including withMathJax() in the static UI seems to work fine. Thanks

**Comment by yihui** [comment]
@mostly-harmless So I guess we can close this issue now? I tend not to include a local copy of MathJax in shiny.

**Comment by wch** [comment]
@yihui I think there's a deeper issue that we should figure out: in general, when JS libs are loaded dynamically in a htmlDependency, there's no guarantee that they'll load before any inlined Javascript code is executed.

**Comment by yihui** [comment]
@wch I agree. I don't know how to solve this issue, though. A silly workaround for this particular MathJax issue that I can think of at the moment is 

```js
setInterval(function() {
  if (window.MathJax) MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
}, 1000);
```

**Comment by vnijs** [comment]
FYI When offline the work-around of including withMathJax() in the static UI stops working. See, for example, the ui for Regression > OLS in https://github.com/vnijs/radiant. I'm using the latest github version of shiny and DT.

If there a way for withMathJax to detect if a user is online and only wrap inputs if TRUE?

**Comment by yihui** [comment]
@vnijs If you really want MathJax to work offline, I'm afraid you will have to bundle a copy of the MathJax library into your app.

**Comment by vnijs** [comment]
@yihui I understand that would be needed. Hoever, given the size of MathJax that doesn't seem like a practical option. I would be ok with math not being rendered if offline. However, withMathJax messes up the ui in that case.

**Comment by jcheng5** [comment]
I was going to say this is impossible, but hmmm, looks like it's at least possible:
https://developer.mozilla.org/en-US/docs/Online_and_offline_events

**Comment by yihui** [comment]
@vnijs Can you provide a screenshot of how `withMathJax()` messes up the UI? Thanks!

**Comment by vnijs** [comment]
@yihui Attached two screen shots for Base > Single mean using inst/quant (https://github.com/vnijs/radiant). In the first screen shot I am online. In the second I'm offline. Partially this seems to be a problem with conditional panel as 'Select plots:' should only be shown if the user is on the Plot tab (see also earlier comments on the use of renderUI and withMathJax). There is more going on however. 'Select plots:' should be a (multiple) selectize input, the formatting for the 'Alternative hypothesis:' dropdown if different, and the slider for 'Significance level:' is not show at all. The Variable selection dropdown is not shown either.

Other menu items are affected also. Let me know if you need more examples. To install radiant dependencies you can use:

install.packages("radiant", repos = "http://vnijs.github.io/radiant_miniCRAN/")

Online:
![screen shot 2015-04-28 at 10 04 46 pm](https://cloud.githubusercontent.com/assets/2998956/7380416/9cd1c680-edf3-11e4-8773-032920cbc8d4.png)

Offline:
![screen shot 2015-04-28 at 10 09 15 pm](https://cloud.githubusercontent.com/assets/2998956/7380440/c98208c0-edf3-11e4-8e0c-2a4c78ac362f.png)

**Comment by vnijs** [comment]
I took another look at adding MathJax locally. Even after using the mathjax_prune script in the Rstudio repos it is 32MB. Is there a way to link to mathjax bundled with Rstudio from a shiny app perhaps?

**Comment by vnijs** [comment]
FYI 

Surprisingly, to me at least, keeping only the MathJax.js file is sufficient to render the math I have in Rmd files. A more comprehensive workaround might be to put Mathjax in an R-package that users can install.

**Comment by vnijs** [comment]
Using `if (window.MathJax)`, as @yihui suggested, actually works fine for me. I don't mind if math is not rendered when the user is offline. However, `withMathJax` doesn't check if MathJax is, or is not, available and so breaks conditional panels when offline because MathJax is undefined. Would it be useful to tweak `withMathJax` in Shiny as below?

```r
withMathJax <- function (...)
{
  path <- "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
  tagList(tags$head(singleton(tags$script(src = path, type = "text/javascript"))),
      ..., tags$script(HTML("if (window.MathJax) MathJax.Hub.Queue([\"Typeset\", MathJax.Hub]);")))
}
```

**Comment by yihui** [comment]
That makes sense to me.
