### ISSUE TITLE
sliderInput unresponsive in browser for latest Shiny version 0.11

### ISSUE THREAD

**Issue by markriseley** [rstudio/shiny#700]
I'm unable to drag the slider points in a browser view of a shiny app. It works fine in R Studio preview pane. This was fine before I updated to latest shiny.

I'm Win 8.1, tested in browser on Chrome and Opera, same issue.

Reproducible example:

    # code mainly from this post:http://stackoverflow.com/questions/17703711/shiny-reactivity
    # server.R
    
    library("shiny")
    shinyServer(
        function(input, output) { 
            Data <- reactive({
                input$action
            isolate({ 
                return(rnorm(input$N))
            })
        })
        output$plotSample <-renderPlot({
            plot(Data())
        } , height = 400, width = 400
        )
    })
    
    # ui.R

    library("shiny")
    shinyUI(
     pageWithSidebar(
        headerPanel("Example")
        ,
        sidebarPanel(
            sliderInput("N", "Number of Samples", min = 2, max = 1000, value = 100)
            ,
            actionButton("action", "Resample")
        )
        ,  
        mainPanel(
            tabsetPanel(      
                tabPanel("Plot", plotOutput("plotSample"))
                ,
                id = "tabs1"
            )
        )
      )
    )

**Comment by wch** [comment]
It works for me in Chrome and in the viewer pane... Have you restarted R and run this in a clean session? Also, it would help if you could post the output of `devtools::session_info()` (after restarting R and running the app).

Single-file version below:

```R
library(shiny)
server <-
    function(input, output) { 
        Data <- reactive({
            input$action
        isolate({ 
            return(rnorm(input$N))
        })
    })
    output$plotSample <-renderPlot({
        plot(Data())
    } , height = 400, width = 400
    )
}

ui <- pageWithSidebar(
    headerPanel("Example")
    ,
    sidebarPanel(
        sliderInput("N", "Number of Samples", min = 2, max = 1000, value = 100)
        ,
        actionButton("action", "Resample")
    )
    ,  
    mainPanel(
        tabsetPanel(      
            tabPanel("Plot", plotOutput("plotSample"))
            ,
            id = "tabs1"
        )
    )
  )
)

shinyApp(ui, server)
```

**Comment by markriseley** [comment]
I tried a fresh R session, same issue. It's fine in the preview pane but
not in chrome (and I also checked same issue in IE and Opera).

FYI I'm on Windows 8.1 / chrome Version 40.0.2214.93 m.

Here's the output of devtools::session_info()

Session info
-----------------------------------------------------------------------------
 setting  value
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, mingw32
 ui       RStudio (0.98.1091)
 language (EN)
 collate  English_United Kingdom.1252
 tz       Europe/London

Packages
---------------------------------------------------------------------------------
 package    * version   date       source
 devtools   * 1.7.0     2015-01-17 CRAN (R 3.1.2)
 digest     * 0.6.8     2014-12-31 CRAN (R 3.1.2)
 htmltools  * 0.2.6     2014-09-08 CRAN (R 3.1.2)
 httpuv     * 1.3.2     2014-10-23 CRAN (R 3.1.2)
 mime       * 0.2       2014-09-26 CRAN (R 3.1.2)
 R6         * 2.0.1     2014-10-29 CRAN (R 3.1.2)
 Rcpp       * 0.11.3    2014-09-29 CRAN (R 3.1.2)
 RJSONIO    * 1.3-0     2014-07-28 CRAN (R 3.1.2)
 rstudio    * 0.98.1091 2014-11-07 local
 rstudioapi * 0.2       2014-12-31 CRAN (R 3.1.2)
 shiny        0.11      2015-01-17 CRAN (R 3.1.2)
 xtable     * 1.7-4     2014-09-12 CRAN (R 3.1.2)

**Comment by markriseley** [comment]
FYI I can manipulate the demo slider here:
http://ionden.com/a/plugins/ion.rangeSlider/en.html

**Comment by markriseley** [comment]
Oddly in Firefox 35.0.1 and 33.1 the slider is working as intended.

**Comment by markriseley** [comment]
I have the same frozen slider issue with the cran dash demo, so I don't
think it can be to do with my R environment, more of a browser-related
issue.

https://jcheng.shinyapps.io/crandash/

**Comment by wch** [comment]
Does it say anything when you open up the Javascript console on your browser? In Chrome, it's under More Tools -> Javascript console.

**Comment by markriseley** [comment]
No error messages or warnings in the console, all the .js and .css files
look similar between firefox and chrome as far as I can see.

**Comment by ncarchedi** [comment]
Same issue here. `sliderInput()` does not work for me in Chrome 40.0.2214.93 m (latest) or IE 11, but it does work fine in Firefox 35.0.1 (latest). This is true both for my own app and the crandash app that @markriseley linked to above.

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinyBS_0.25         shinydashboard_0.2.1 shiny_0.11          

loaded via a namespace (and not attached):
 [1] digest_0.6.8    htmltools_0.2.6 httpuv_1.3.2    mime_0.2        packrat_0.4.1.8 R6_2.0.1        Rcpp_0.11.4     RJSONIO_1.3-0  
 [9] tools_3.1.2     xtable_1.7-4  
```

**Comment by wch** [comment]
I just pushed some updates to the sliders in Shiny - do you guys mind installing the latest with `devtools::install_github('rstudio/shiny')`, restarting R, and running the app again?

**Comment by ncarchedi** [comment]
@wch The fix works like a charm in Chrome, IE, and Firefox. Thanks!

**Comment by markriseley** [comment]
Sorted for me too, many thanks! You might want to update the crandash
<https://jcheng.shinyapps.io/crandash/>example so the bug is fixed there
too.

**Comment by wch** [comment]
Great, glad it works!

**Comment by wch** [comment]
Quick question - do you both have touchscreen computers? I think this was the cause of the problem:
  https://github.com/IonDen/ion.rangeSlider/issues/166

**Comment by ncarchedi** [comment]
@wch Interesting. I was doing this from my work PC, a Lenovo ThinkPad w/ Windows 8. I believe it has touchscreen capabilities, although I've never used them.

**Comment by markriseley** [comment]
Yup I was using a win 8.1 laptop with touchscreen and mouse.

**Comment by wch** [comment]
Great, thanks for the feedback. I believe that the slider would have worked with touchscreen input, but not the mouse.
