### ISSUE TITLE
absolutePanel not showing in v.0.11

### ISSUE THREAD

**Issue by xinye1** [rstudio/shiny#701]
I'm using R version 3.1.2 on Ubuntu 14.04 LTS

My app is similar to the Superzip example in the Shiny Gallery (http://shiny.rstudio.com/gallery/superzip-example.html) in using absolutePanel.

Are there any known issues with absolutePanel?

Thanks

**Comment by wch** [comment]
Because of the change to Bootstrap 3, the class that should be used has changed to `"panel panel-default"`. More info here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/shiny-discuss/sX2n5-nVkXg/SoMus4_A3WYJ

We'll update the documentation to reflect this.

**Comment by xinye1** [comment]
Excellent
You guys are great!
