### ISSUE TITLE
sliderinput does not work in chrome but in firefox

### ISSUE THREAD

**Issue by MengyingLi** [rstudio/shiny#713]
My issue is my `sliderinput` only works in firefox. The `sliderinput` is withins a `fluidPage` function. 
`sliderInput("Time",
                label = "I have been there at least _ times",
                min = 1, max = 9, value = 1, step = 1),`
The actual visualization could be accessed from https://mengyingli.shinyapps.io/MY_Foursquare/

**Comment by wch** [comment]
This has been fixed in the development version (see #700).  The problem was that on Windows computers with touch screens, the slider doesn't recognize mouse events.
