### ISSUE TITLE
Shiny Version:	0.11: The plot sizing is completely gone bad

### ISSUE THREAD

**Issue by gunapemmaraju** [rstudio/shiny#716]
Till version 0.11 of the shiny release, I could resize my charts using the options like:

server.R 
 output$abcPlot <- renderPlot(width = 1300, height=900, units="px",{
    plot(...Code for PLot..)
  })

ui.R
plotOutput('abcPlot', height="auto")

But now this is not working ok. The resolutions are all gone wrong.

**Comment by wch** [comment]
Can you please describe the issue in more detail and/or include a screenshot? A full reproducible example like the one below would also be useful.

On my system this produces a plot that is 1300x900 pixels:

```R
shinyApp(
  ui = bootstrapPage(
    plotOutput('abcPlot', height="auto")
  ),
  server = function(input, output) {
    output$abcPlot <- renderPlot(width = 1300, height=900, units="px",{
      plot(1:10, 1:10)
    })
  }
)
```
