### ISSUE TITLE
feature request - color picker

### ISSUE THREAD

**Issue by Kushdesh** [rstudio/shiny#718]
Thanks for wonderful shiny which makes it easy to make Customized tools based on R much user friendly. Request you to add color picker widget which can benefit the end user by making easy to select colors.

**Comment by daattali** [comment]
Until shiny gets a builtin colourpicker, you can use the `colourInput` from [shinyjs](https://github.com/daattali/shinyjs). 

```
library(shiny)
library(shinyjs)
runApp(shinyApp(
  ui = fluidPage(
    colourInput("col1", "Select colour:"),
    colourInput("col2", "Select colour:", "#abc123", allowTransparent = TRUE),
    colourInput("col3", "Select colour:", "lightgreen", showColour = "background")
  ),
  server = function(input, output, session) {}
))
```

![colourinput](https://cloud.githubusercontent.com/assets/952340/8296235/1fbbb4fe-1903-11e5-9163-6319ad36f84b.png)

**Comment by daattali** [comment]
Update 2018: if you want to use a colour picker, it now lives in its own package: [`colourpicker`](https://github.com/daattali/colourpicker).

**Comment by alandipert** [comment]
Thank you for the suggestion, but we don't have plans to add a color picker input. I recommend instead using @daattali's `colourpicker` package.
