### ISSUE TITLE
Request: Add a class or some other defining feature to "session" objects

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#720]
Right now, a session is simply an environment and there isn't a proper way to test if is indeed a session of or.  
Winston mentioned [this](https://github.com/rstudio/shiny/blob/master/R/progress.R#L255-L256) is how shiny currently does it in a hacky way

Original discussion: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/shiny-discuss/sFHHBG9SOeg/XmTxjzJCMqAJ

**Comment by wch** [comment]
We've fixed this. You can now test the class like [this](https://github.com/rstudio/shiny/blob/4dde16d8365e99aa347c353aa4d34f8f5d6c25e7/R/progress.R#L255-L256):

```R
  if (!inherits(session, "ShinySession"))
    stop("'session' is not a ShinySession object.")
```

**Comment by daattali** [comment]
Perfect, this is exactly what I wanted, thanks
