### ISSUE TITLE
Request: Remove blank row that is added by default when using the navbar Layout

### ISSUE THREAD

**Issue by anfibil** [rstudio/shiny#722]
As per the following thread: http://goo.gl/QN0cug, I was wondering if there is a particular reason why an extra blank row is appended in the HTML code when using the navbar Layout immediately below the navigation bar and if there is a way to suppress that behavior. Thanks and congratulations on such an amazingly helpful tool!

**Comment by wch** [comment]
@jjallaire Do you recall what the rationale was for adding the blank `&nbsp;` header by default? Unless there's a good reason to keep it, I think we can take that out.

I'm looking at:
  https://github.com/rstudio/shiny/blob/b9c6b84ff5f120311466aec93540221b88ba3f91/R/bootstrap.R#L253-L255

A few lines later there's a `(!is.null(header))` check which can never actually evaluates to TRUE, but that looks like it was added in a different commit.

**Comment by wch** [comment]
@anfibil As a workaround, you can use `navbarPage(header = "")`. Also, there's no need to wrap the `navbarPage` in `fluidPage()`.

For example:

```R
ui <- navbarPage('Minimum Example',
  header = "",
  tabPanel('Tab1',
    sidebarLayout(
      sidebarPanel(br()),
      mainPanel(br())
    )
  )
)

server <- function(input, output, session) {}

shinyApp(ui = ui, server = server)
```

**Comment by anfibil** [comment]
@wch Ha! That took care of it. Thanks a lot for suggesting the workaround and for the note on the unnecessary wrap.

**Comment by jjallaire** [comment]
I don't recall why. My guess is to ensure some level of vertical spacing?
If things look visually OK to you without it then I'd say getting rid of it
is fine.

**Comment by wch** [comment]
I think it looks better without it, so I've removed it.
