### ISSUE TITLE
add class="form-control" to selectInput with multiple=TRUE and selectize=FALSE

### ISSUE THREAD

**Issue by mostly-harmless** [rstudio/shiny#724]
A selectInput with the features in the title does not have the same styling as other elements in Shiny .11. Adding the class "form-control" should fix that. This also applies to textarea etc. but these are easier to fix manually. 

Thanks

**Comment by mostly-harmless** [comment]
I have tried the work-arounds below put into a .js file. The 2nd and 3rd option work from the js console but not when sourced using includeScript. Any suggestions for a work around?

document.getElementsByTagName("select[multiple]").className += " form-control";
document.getElementById("vizvars1").className += " form-control";
$('#vizvars1').addClass('form-control');

**Comment by wch** [comment]
Can you explain what you mean by "features in the title"? A small reproducible example would be really helpful.

**Comment by mostly-harmless** [comment]
Sure. See code below. The 2nd selectInput has different styling than the 1st. If you put the following in the js console you will see that the styling gets updated to bootstrap 3. The same applies to the textarea input also in the code below. Unfortunately, I don’t have a solution that actually works *in* the app code. Any work-around would be great. Thanks Winston!!!




$('#data2').addClass('form-control');






ui <- bootstrapPage(




  selectInput(inputId = "data1", label = "",

              choices = LETTERS[1:5],

    					selected = "A",

    					multiple = TRUE),




  selectInput(inputId = "data2", label = "",

              choices = LETTERS[1:5],

              selected = "A",

              multiple = TRUE, selectize = FALSE),




  tags$textarea(id="old_look",

                rows="3"),




  tags$textarea(class="form-control",

                id="new_look",

                rows="3")

)




server <- function(input, output, session) {




}




shinyApp(ui = ui, server = server)




—

**Comment by wch** [comment]
Great, thanks for the example. It does make sense to add the `form-control` class to the select input. The `textarea` generates a raw HTML tag, so in that case users should add the class themselves. It would be nice if it were somehow more obvious to users that `class="form-control"` would make the styling consistent, though.

**Comment by wch** [comment]
Cleaned up code for example:

```R

ui <- bootstrapPage(
  selectInput(inputId = "data1", label = "",
              choices = LETTERS[1:5],
                        selected = "A",
                        multiple = TRUE),
  selectInput(inputId = "data2", label = "",
              choices = LETTERS[1:5],
              selected = "A",
              multiple = TRUE, selectize = F),
  tags$textarea(id="old_look",
                rows="3"),
  tags$textarea(class="form-control",
                id="new_look",
                rows="3")
)

server <- function(input, output, session) {}

shinyApp(ui = ui, server = server)
```

**Comment by mostly-harmless** [comment]
Thanks @wch !

My guess is there are going to be a lot of questions on the shiny google group in the near future about formatting and CSS. Stuff like radio buttons inline, numeric inputs next to each other (example below). Spacing of various elements etc. Maybe a page with some specific information on things that can be changed in css (such as form-control for a text input).

div(class="row",
	div(class="col-xs-6", numericInput("fac1",
    label = "Factor 1:", value = 1),
	div(class="col-xs-6", numericInput("fac2",
    label = "Factor 2:", value = 1),
)

**Comment by mostly-harmless** [comment]
@wch  I just started a thread on the shiny google group about styling, CSS etc. Please add your CSS tips!

**Comment by wch** [comment]
I actually just realized that it should have `class="control-label"` even when `multiple=FALSE`, so I made that change in 9f8f04caec16fbefc036c177aba9b5bb5f0f09e2. Now single selects actually look pretty nice! So much that the selectize doesn't really improve on appearance.

Below are some screenshots of the updated appearance.

Chrome:

![image](https://cloud.githubusercontent.com/assets/86978/6069187/06c6e634-ad48-11e4-858a-7294a07f9291.png)

Firefox:

![image](https://cloud.githubusercontent.com/assets/86978/6069175/e332dff2-ad47-11e4-840e-ea5687f45704.png)

Safari:

![image](https://cloud.githubusercontent.com/assets/86978/6069289/c0cbed40-ad48-11e4-8bc0-47cb62d65cca.png)

**Comment by mostly-harmless** [comment]
Nice. Thanks!


—

**Comment by nicholaelaw** [comment]
Sorry to dig up an old issue, but if you are using shinythemes, then `selectInput` has different appearance depending on whether `selectize = TRUE` or not.

Using shinytheme 'readable':

![image](https://user-images.githubusercontent.com/10719482/29857238-48975dee-8d8a-11e7-8915-253d98f2246c.png)

Left is `selectize = FALSE` and right is `TRUE`. I can fix this by adding `form-control` class to `selectize-input` element. But it's not very straight forward (couln't find it in the source), and doing it by js also fails because the widget is constantly updated and reverted. 

So, may I ask the good devs to also add `form-control` to every `.selectize-input` element? I mean this one:

![image](https://user-images.githubusercontent.com/10719482/29857504-904d7d52-8d8b-11e7-842a-61c9df0c2a69.png)
