### ISSUE TITLE
Conditional panels and tabs with icons

### ISSUE THREAD

**Issue by incivile** [rstudio/shiny#725]
Hello,
when I am using names of tabs in conditions of conditional panels and the tabs have icons, condition is never solved as true. Is there any way how to solve this problem?
I'm using Shiny 0.10.2.2 and fontawsome icons.

Thank you in advance!

**Comment by wch** [comment]
Can you provide a small reproducible example? Something like [this](https://github.com/rstudio/shiny/issues/724#issuecomment-72979591).

**Comment by incivile** [comment]
This is example ui.R:

library(shiny)
library(datasets)

shinyUI(
  fluidPage(
    conditionalPanel(
      condition = " input.tabs ==  'region' ",
      selectInput("region", "Region:", choices=colnames(WorldPhones))
    ),
    conditionalPanel(
      condition = " input.tabs ==  'iris_params' ",
      selectInput("iris_params", "iris_params:", choices=colnames(iris))
    ),
    tabsetPanel(
      id = 'tabs',
      tabPanel('iris_params', #icon = icon("table"),
               helpText("iris_params")
      ),
      tabPanel('region', icon = icon("phone"),
              helpText("region")
      ),
      selected = "iris_params"
    )
  )
)

**Comment by wch** [comment]
The root of the problem is that the HTML generated has spaces around `region` because of the additional tags. This is how htmltools renders the HTML, and when rstudio/htmltools#19 fixed, I think your existing code should just work.

```HTML
        <li class="active">
          <a href="#tab-1620-1" data-toggle="tab">iris_params</a>
        </li>
        <li>
          <a href="#tab-1620-2" data-toggle="tab">
            <i class=" fa fa-phone fa-fw"></i>
            region
          </a>
        </li>
```

So for the condition, shiny is comparing `"region"` to a string that's something like `"\n    \n    region\n"`, which is false. 

You can make your code work by doing a substring match, or a regex test. Here's a version of your code with the substring match:

```R
library(shiny)
library(datasets)

ui <- fluidPage(
  conditionalPanel(
    condition = " input.tabs.indexOf('region') !== -1 ",
    selectInput("region", "Region:", choices=colnames(WorldPhones))
  ),
  conditionalPanel(
    condition = " input.tabs == 'iris_params' ",
    selectInput("iris_params", "iris_params:", choices=colnames(iris))
  ),
  tabsetPanel(
    id = 'tabs',
    tabPanel('iris_params', #icon = icon("table"),
             helpText("iris_params")
    ),
    tabPanel('region', icon = icon("phone"),
            helpText("region")
    ),
    selected = "iris_params"
  )
)


server <- function(input, output) { }

shinyApp(ui = ui, server = server)
```

**Comment by jcheng5** [comment]
That's really awful. We should put a more canonical version of the ID on the li or something, maybe in a `data-tab-id` attribute.

**Comment by jcheng5** [comment]
Actually--you can work around this already by giving your tabPanel a `value` argument, e.g. `tabPanel('region', value = 'region', icon = ...)`.
