### ISSUE TITLE
range sliderInput with extended width - above ticks bug (Shiny 0.10.2.2)

### ISSUE THREAD

**Issue by incivile** [rstudio/shiny#731]
Dear Shiny masters,
when I'm using range-type (= two values) sliderInput and the right sliding selector gets close enough to the left one, their above ticks change into one in-between "range tick". In this position when you move the left selector, "range tick" jumps above right selector and doesn't change its value. Everything gets ok after moving right selector. Is there any trick to avoid this bug? Everything works ok with smaller sliders, but I would like to use the big one across the screen.
I know that Shiny 0.11 is using the new type of sliders, but right now, I'm not able to upgrade Shiny version.
Thank you in advance.

ui.R:
library(shiny)

shinyUI(fluidPage(
  sliderInput("range", "Range:",
            min = 1, max = 1000, value = c(200,500), width = "100%")
))

**Comment by wch** [comment]
The old sliders did have some rendering issues, and that's one reason that we replaced them; unfortunately we don't have the resources to go and fix the old versions.
