### ISSUE TITLE
Proposal: switch tag format from v/0/11 to v0.11

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#732]
With the current tag format, the tag `v/0/11` is a file with the path `.git/refs/tags/v/0/11`. This means that you can't create a tag like `v/0/11/1`, because that would require `.git/refs/tags/v/0/11` to be a directory -- but instead it's a file.

This is a problem for the `v/0/11/1` tag. It also was a problem for other releases, and so we used `v/0/10/2.1` and `v/0/10/2.2`. I propose that we switch to a format like `v0.11`, which would eliminate this problem and be more standard. Thoughts?

**Comment by yihui** [comment]
I strongly agree.

**Comment by jcheng5** [comment]
Sure. Will the legacy tags remain in place or will you delete them?

**Comment by wch** [comment]
Good question. Unless anyone is using the old tags for something, I think we should migrate them.

**Comment by wch** [comment]
OK, I ended up renaming all the tags. For better or worse, this is outside of what's considered good practice for git. :/ If I had realized this going in, I might have decided against renaming the old tags... but what's done is done.

You'll want to get your local and personal remote repo (like jcheng5/shiny) in sync with the rstudio/shiny repo.

I'll assume that your personal remote is called `origin` and the rstudio remote is called `rstudio`. First delete all local and personal-remote tags .

```sh
## NOTE: If your personal remote isn't named origin, use that name instead below ##
for t in `git tag`
do
    git push origin :$t
    git tag -d $t
done
```

Then fetch the tags from the rstudio repo:

```sh
## NOTE: If your rstudio/shiny remote isn't named rstudio, use that name instead below ##
git fetch rstudio --tags
```

Finally, push your new local tags to your personal remote:

```sh
## NOTE: If your personal remote isn't named origin, use that name instead below ##
git push origin --tags
```

(I've tested these exact steps on my machine.)

**Comment by yihui** [comment]
@wch Thanks. Worked beautifully for me.
