### ISSUE TITLE
SVG rendering bug for boxplots

### ISSUE THREAD

**Issue by MSUPokerGod** [rstudio/shiny#734]
I have a boxplot I'm trying to display and there is buggy behavior when rendering with the default method. I'm now rendering with "canvas", but I figured I'd report this bug .
There might be a clue as to whats happening with the behavior that occurs when I resize.
Here's what I know:
Sometimes the boxplot renders without a problem, depending on the data subset I'm using
When it doesn't render, and I resize it by one pixel, the boxplot appears, but with about 10% of the rightmost side of the image cut off.
when I resize it by one pixel again, the boxplot resizes again, to become smaller and fit in its own container, so it is all visible.
Sorry for the lack of a reproducible example but I'm at work and can't spend that much time to try to make one happen. I'm just using ggvis() %>% layer_boxplots(). I've tried a bunch of combinations of set_options(), none seem to help except changing renderer = "canvas"

**Comment by wch** [comment]
Hi can you file this as a [ggvis issue](https://github.com/rstudio/ggvis/issues)? Also, a reproducible example would be helpful; if we can't see the problem, we probably can't fix it.
