### ISSUE TITLE
js errors in console for conditional panel with checkboxgroup

### ISSUE THREAD

**Issue by mostly-harmless** [rstudio/shiny#735]
I'm using conditionalpanel with a checkboxgroup to show a slider when a box is checked. Both the conditions below work but both throw a js error in the console. Not a big deal but perhaps this error message can be 'caught' ... or is there a better way to write the condition?

 conditionalPanel(condition = "input.reg_check.contains('confint')",   ==>
 Uncaught TypeError: Cannot read property 'contains' of undefined

 conditionalPanel(condition = "input.reg_check.indexOf('confint') >= 0", ==>
 Uncaught TypeError: Cannot read property 'indexOf' of undefined

**Comment by yihui** [comment]
I believe you can use try/catch: http://stackoverflow.com/questions/14782232/how-to-avoid-cannot-read-property-of-undefined-errors

**Comment by mostly-harmless** [comment]
I don't think you can put a try/catch inside a condition for a conditionalPanel. I assume this is something that should be 'caught' in shiny.js unless there is another way to write the condition.

"try{input.reg_sum_check.indexOf('confint') >= 0}catch(e){false}"

Uncaught SyntaxError: Unexpected token try

**Comment by yihui** [comment]
Sorry about that. Wow, the scope is so strict: https://github.com/rstudio/shiny/blob/8b3ca126580/inst/www/shared/shiny.js#L163-L173 I think you can use the "ugly" check like `input.reg_sum_check && input.reg_sum_check.indexOf('confint') >= 0`. In the mean time, let me see if there is a way to make `try` work...

**Comment by mostly-harmless** [comment]
Ah. That works. Thanks Yihui! I tried using _undefined_ but didn't realize && is needed rather than &. The below works, as does your suggestion.

input.reg_sum_check !== undefined && input.reg_sum_check.indexOf('confint') >=
