### ISSUE TITLE
problem with updateSliderInput() with shiny 0.11

### ISSUE THREAD

**Issue by lucasayat** [rstudio/shiny#739]
I just updated shiny with the 0.11 version embedding boostrap3 and every slider working well with he former version  failed. They don't send the new value to the session when a data is sent from an initial file... they work only when they are moved. I changed every sliderInput with numericInput and now it works fine. I find  these new sliders  nicer than the former ones but I can't use them.
Best regards. Lucasayat.

**Comment by wch** [comment]
Can you provide a reproducible example for this? `updateSliderInput` works in my test examples.

**Comment by wch** [comment]
Closing for now. If you have an example, you can re-open the issue.
