### ISSUE TITLE
Deprecated arguments to sliderInput in example "05_sliders"

### ISSUE THREAD

**Issue by cubranic** [rstudio/shiny#748]
Console output:
```
> runExample("05_sliders")

Listening on http://127.0.0.1:6659
The `format` argument to sliderInput is deprecated. Use `sep`, `pre`, and `post` instead. (Last used in version 0.10.2.2)
The `locale` argument to sliderInput is deprecated. Use `sep`, `pre`, and `post` instead. (Last used in version 0.10.2.2)
```

**Comment by wch** [comment]
Thanks, fixed!

**Comment by TanveerHAhmad** [comment]
I am getting this message:
The `format` argument to sliderInput is deprecated. Use `sep`, `pre`, and `post` instead. (Last used in version 0.10.2.2)
I do not know - what it means - is it an Error or just a warning ?
Here is my Code:
sliderInput("age.now", "Current Age:", min = 55, max = 110, value = 59),
How do I fix it ?
