### ISSUE TITLE
What's the language convention?

### ISSUE THREAD

**Issue by Ironholds** [rstudio/shiny#751]
I'm looking at the codebase (I had to dig into a lot of it in the process of writing an app - long story involving retrieving session information to set image height) - and I'm not seeing a consistent language convention. Compare, for example, [this one-line if flow](https://github.com/rstudio/shiny/blob/master/R/bootstrap.R#L32-L34) with [this one-line if flow](https://github.com/rstudio/shiny/blob/master/R/cache.R#L35-L37) or [this one](https://github.com/rstudio/shiny/blob/b7acaf951970e3c96dfe57f808a6830160e9e903/R/shinywrappers.R#L97)

Is there a consistent style guide? If so, I'll happily go through standardising things to make the code more consistent.

**Comment by jcheng5** [comment]
Nope--we're intentionally non-prescriptive about cosmetic differences (other than indentation). Thanks for the offer, though!
