### ISSUE TITLE
Table sizing

### ISSUE THREAD

**Issue by Ironholds** [rstudio/shiny#757]
Take [this](http://datavis.wmflabs.org/agents/) as an example; if your screen is 1920x1200, it works fine...but the moment you resize your browser window, suddenly things get cut off. It'd be good if as well as dynamically refreshing on user input, Shiny was also responsive to changes in browser window size.

**Comment by wch** [comment]
Hm, it looks like DataTables is adding in an explicit pixel width. Inspecting the DOM yields this:

```html
<table class="table table-striped table-hover dataTable no-footer"
id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info"
style="width: 726px;">
```

**Comment by wch** [comment]
Relevant: https://datatables.net/examples/basic_init/flexible_width.html

**Comment by Ironholds** [comment]
Interesting. Presumably we should be inserting the width/height parameters from the user's session data? Or some mod of that.

**Comment by yihui** [comment]
DataTables calculates the widths of the table and its columns automatically by default, and use hard-coded pixel values, which does not make much sense in your case. You can disable this feature by `autoWidth = FALSE`, e.g.

```r
library(shiny)
shinyApp(
  ui = fluidPage(fluidRow(dataTableOutput('foo'))),
  server = function(input, output) {
    output$foo = renderDataTable(iris, options = list(autoWidth = FALSE))
  }
)
```

See http://datatables.net/reference/option/autoWidth

**Comment by Ironholds** [comment]
Got it; thanks! Would it be valuable to have this as the default behaviour? Or, to invert it; can people come up with common use cases for a fixed-width data table? Generally-speaking I'd avoid fixed-width /anything/.

**Comment by yihui** [comment]
@Ironholds I tend to agree with you. I do not see the point of using fixed width for the table, either. Perhaps you can ask the DataTables author about the rationale behind `autoWidth: true` as the default?

**Comment by Ironholds** [comment]
@yihui totally - I was more driving at, would you have any objection for me throwing a PR in that creates an explicit width field to be passed through to the config, and sets a (percentage-based) default value? It seems like the sort of user control that would be really powerful, particularly given datatable's default behaviour - it would also make renderDataTable match, for example, renderPlot, which does have control over sizing.

**Comment by yihui** [comment]
@Ironholds It is trivial to make that change in shiny, so I can do it by myself, but I still want to know the reason why `autoWidth: true` is the default. There might be things that we failed to see. Thanks!
