### ISSUE TITLE
renderTable() additional arguments bug

### ISSUE THREAD

**Issue by cmishra** [rstudio/shiny#761]
renderTable() takes additional arguments to be passed to both the xtable and print.xtable functions. 

The bug arises when one attempts to pass an argument to one function that can be partially matched as the argument of another. One either receives an "argument matches multiple arguments" error or unintentionally passes an argument to one function or the other without meaning to. The temporary workaround I used was to specify all the other arguments that could be partially matched to the argument of interest. 

A specific example (with the argument matches multiple arguments error) can be found here: https://gist.github.com/cmishra/87bad81d4eed495272ae.

**Comment by wch** [comment]
According to `?xtable`, the function takes several named args, as well as `...`, but the `...` is ignored. So I think we can give those specific named args to `xtable()`, and give the rest of them to `print()`.
