### ISSUE TITLE
Problem with numericInput

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shiny#764]
I'm using ```numericInput``` to display values and giving my users the opportunity to change them.
I have two columns of 8 ```numericInput``` each. When a value is updated I check that it is valid (i.e. no characters etc.) then it gets re-rendered back to the user.
In Safari, FireFox and Chrome I see on the right end side of the box an up-and-down arrow.
If I click rapidly 2 or 3 times on the arrow the app goes on a loop because of the different states between client and servers do not get resolved.  The loop is not resolved: I typically need to kill the app.

In IE there is no arrow and I do not see any problem. I think that eliminating the arrow (as a data-entry mode) would resolve the problem.

Is there a way to remove the arrow? I tried ```step=NULL``` but it gives error.

**Comment by wch** [comment]
Could you provide a reproducible example?

**Comment by smartinsightsfromdata** [comment]
@wch The problem seems to disappear with 1.11.1.9003.  Close it for now.  Thanks!

**Comment by wch** [comment]
Hm, I'm not sure what changes there were between 0.11.1 and 0.11.1.9003 that would make a problem like this go away... but if so, that's great to hear.
