### ISSUE TITLE
Shiny app doesnt work after upgrading a shiny r package. 

### ISSUE THREAD

**Issue by vigneshprajapati** [rstudio/shiny#766]
My Shiny app doesnt work after upgrading a shiny r package. Current version is - 0.11.1

library('shiny')
runApp('my_report',host="127.0.0.3",port = 1012)

![image](https://cloud.githubusercontent.com/assets/1836310/6621336/0736b5d4-c8fc-11e4-9a40-9551c538c589.png)

Any suggestions or solution ?

**Comment by wch** [comment]
Have you restarted a clean R session after upgrading? If you could include the output of `sessionInfo()`, that would be helpful.

**Comment by vigneshprajapati** [comment]
Hi wch,

here is sessionInfo() output,

> sessionInfo()
R version 3.0.2 (2013-09-25)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252
[4] LC_NUMERIC=C                   LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.0.2

**Comment by wch** [comment]
Can you run your app and then run `sessionInfo()` again? That will print out the information on packages loaded when you run your app.

I suspect that you need to reinstall Rcpp, but I'm not yet sure.

**Comment by vigneshprajapati** [comment]
I cant do it because my R session aborted at the same time it gives an error. So I cant able to run this sessionInfo() command after that. If I want to do it then I need to restart clean R session.

let me try with re-installing Rcpp package. Hope it might help.

**Comment by wch** [comment]
You may also need to reinstall httpuv.

**Comment by vigneshprajapati** [comment]
Yes, Winston. You are right. I tried with re-installing Rcpp but it didnt work. But also re-installing httpuv is worked. Big Thanks.

**Comment by wch** [comment]
Great!
