### ISSUE TITLE
Slider with discreet values

### ISSUE THREAD

**Issue by FB54321** [rstudio/shiny#771]
Hi,

The interactivity has gotten me to move my scripts over to shiny.

However, for slider, I'd need a fixed limit of values.

For example, I might have 20 graphs for 20 different points in time, and would like to select one.

Or I display a value for all times at once, and would like to select start and end time.

In both cases I only have discreet times available - a slider makes a lot of sense to use, fixed intervals don't.

Either I numerically convert the timestamps to numbers from 1 to n, but then I would need to be able to format the label shown (the user doesn't want to see 1 to n, but rather the different timestamps).

Or the slider should allow custom steps (similar to at for axis).

Great work btw!

**Comment by VermillionAzure** [comment]
You can instead alias factors as numbers with an associative array and use a fixed step. I wonder how hard this might be...

**Comment by alandipert** [comment]
Hello, thank you for the suggestion. I'm closing this because I think we're already tracking this  enhancement idea with #707.
