### ISSUE TITLE
Problems with sliderInput in R Shiny - Getting NaNs

### ISSUE THREAD

**Issue by sigven** [rstudio/shiny#777]
I' am making e a slider input that has years between 25 and 70. Normally it works fine, but if I pull the slider too far to the left and it gives me 'NaN'. It has been discussed previously (http://stackoverflow.com/questions/28866836/having-problems-with-sliderinput-in-r-shiny-getting-nans), but I could not find it as a reported issue.

**Comment by wch** [comment]
Thanks for the report. It's fixed in the dev version.
