### ISSUE TITLE
renderDataTable dosen't look like Boostrap 3

### ISSUE THREAD

**Issue by Free-rider** [rstudio/shiny#779]
When I do renderDataTable the table doesn't looks like examples or Bootstrap. I think that the css is not applied properly. For example:

![shiny datatable](https://cloud.githubusercontent.com/assets/10771197/6831055/40895b44-d31e-11e4-84c4-4e46922a734b.png)

 search input has a different design.

 Thanks!

**Comment by yihui** [comment]
You were using the new DT package, right? https://github.com/rstudio/DT I have not incorporated the Bootstrap theme there yet. If you really hate the current default theme, you may file a feature request there :)
