### ISSUE TITLE
How to make several groups of radioButton mutually exclusive to each other?

### ISSUE THREAD

**Issue by aygons** [rstudio/shiny#782]
Hi All,

I'm trying to build something like this:

shinyUI(fluidPage(
             
            radioButtons("segment1", label = h4("Direct New"),
                         choices = list("ODC" = "Direct New ODC", "ODO" = "Direct New ODO", "ODV" = "Direct New ODV","STD"="Direct New STD")
                         ,selected = NULL),
            hr(),
            radioButtons("segment2", label = h4("FAP New"),
                         choices = list("EPQ" = "FAP New EPQ", "ODC" = "FAP New ODC")
                         ),
            hr(),
            radioButtons("segment3", label = h4("Renewals"),
                         choices = list("ODC" = "All Renew ODC", "ODO" = "All Renew ODO", "ODV" = "All Renew ODV","STD"="All Renew STD"))
)
)

But is there anyway to make input$segment[i] mutually exclusive to each other?

The idea is to segment a list of options and call out the group name(Direct New, FAP New, Renewals). I hope the user can only select one option from the entire list regardless of the group at one time.

I also tried to assign the three sets of radioButtons the same name, in which way the selection is unique across groups. However, Shiny won't switch between different sets of radioButtions. For example, if I assign all three groups to be "segment" and print(input$segment), it will always gives me the value in the first set even though I select something from the second and third sets.

**Comment by wch** [comment]
Sorry, I don't think there's a straightforward way to do this right now in Shiny. You'd probably have to write some custom Javascript to make this work the way you want.
