### ISSUE TITLE
Plots don't clear error messages

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#783]
This seems to be new. If a plotOutput renders an error, and then a successful plot, the error is not cleared.

![image](https://cloud.githubusercontent.com/assets/129551/6874191/aa45e138-d472-11e4-8535-7993b332239c.png)

**Comment by wch** [comment]
I bet this is because I changed the code so that instead of calling `$el.empty()` on the container, it basically does `$img.remove()`. This was so that a brush could persist across image changes. It shouldn't be a difficult fix.

**Comment by wch** [comment]
Test app for future reference. Brush is there to make sure it *doesn't* get cleared when a new image is sent.

```R
shinyApp(
  fluidPage(
    plotOutput("plot", width = 200, height = 200, brush = "foo"),
    actionButton("n", "Go")
  ), 
  function(input, output) {
    output$plot <- renderPlot({
      plot(rnorm(input$n), rnorm(input$n))
    })
  }
)
```
