### ISSUE TITLE
dynamic counter variable with Submit  button in R Shiny

### ISSUE THREAD

**Issue by abhisheknigam04** [rstudio/shiny#786]
I am trying to create a counter variable that gets incremented every time a new SQL query gets fired and a new dataset is created. There are essentially 2 types of inputs to the SQL query  - 1) User selected inputs (directely from the UI)  2) Counter flag which needs to be incremented as soon as theSQL query fires. 
The first set of inputs work fine - I am able to use the values selected by the user from the UI and run the SQL query to create a dataset
I am facing an issue when I'm trying to create a flag which is essentially a counter which counts the no. of times a submit button is pressed (eventually the no. of times a SQL fires to yield a dataset).
The values get updated but the counter flag (c_flag)  doesn't

Below is the UI code snippet - 
library (shiny)
shinyUI(
  fluidPage(
       titlePanel("Store -  Shiny app page"),  
    sidebarLayout(
    sidebarPanel(
      ("Store data to be filtered"),  
                 #take user input
    checkboxGroupInput("Segment",  
              label = h3("Select Segment"),  
              choices = list("Segment A" = "A","Segment B" = "B","Segment C" = "C","Segment D" = "D"),
              selected = 1
                      ),  
    selectInput ("State",label = h3("Select AUS state"),  
                  choices = list("NSW" = "NSW","Victoria" = "Victoria","SA" = "SA","Tasmania" = "Tasmania"                             ),
                  selected = 1
                  ),

```
submitButton("submit"),
br(),
br()    
          # Sidebar panel closes here   
          ),                                           
mainPanel("Values input by user",          
              #print user input              
              verbatimTextOutput("Segment"),
              verbatimTextOutput("State"),              
              verbatimTextOutput("counter"),
              verbatimTextOutput("concat"),
              tableOutput("view")
          )              
            )
  )
```

)

and the Server.R code as under  - 
library (shiny)
library(sqldf)
shinyServer(
  function(input, output){ 
    output$Segment <- renderText(input$Segment)
    output$State <- renderText(input$State)
    counter <- 0
    output$counter <- renderText(counter)

```
#concatenation - Initial user input (FREEZED)
output$concat <- renderText( c(input$Segment,input$State))    
output$view <- renderTable({               
query <- paste0("      
                 select a.*,
                 ('",paste0(counter),"') as c_flag
                 from Store as a
                 Where Segment in ('",paste0(input$Segment,collapse = "','"),"') 
                 and State in ('",paste0(input$State,collapse = "','"),"') 
               ")
sqldf(query)    
})
#if (input$Segment > 0)
counter <- counter + 1  
```

})

Please suggest me if I am headed in the right direction or any alternatives.

**Comment by jcheng5** [comment]
Before or after "counter <- 0", add the line:
makeReactiveBinding("counter")

That will tell Shiny to treat the counter variable as a reactive value.
Alternatively, replace counter <- 0 with v <- reactiveValues(counter = 0)
and replace every reference to counter with v$counter. I often prefer to do
it this way because v$counter <- v$counter + 1 gives you a bit of a clue
that you're doing something reactive.

Also, counter <- counter + 1 should be counter <<- counter + 1. With just a
regular <- you are saying to create a new variable in the scope of the
renderTable expression, instead of updating the counter variable that's
already defined in the parent scope.

**Comment by abhisheknigam04** [comment]
I replaced my query as - 
v <- reactiveValues(counter = 0)
    output$counter <- renderText(v$counter)
    
    #concatenation - Initial user input (FREEZED)
    output$concat <- renderText( c(input$Segment,input$State))    
    output$view <- renderTable({                
    query <- paste0("      
                     select a.*,
                     ('",paste0(v$counter),"') as c_flag
                     from Store as a
                     Where Segment in ('",paste0(input$Segment,collapse = "','"),"') 
                     and State in ('",paste0(input$State,collapse = "','"),"') 
                   ")
    sqldf(query)    
    })
    v$counter <<- v$counter + 1  

and i get an error as  -
Error in .getReactiveEnvironment()$currentContext() : 
  Operation not allowed without an active reactive context. (You tried to do something that can only be done from inside a reactive expression or observer.)

Did I miss anything ?

**Comment by jcheng5** [comment]
Oh I thought

v$counter <<- v$counter + 1

would be inside the renderTable (perhaps the line before "sqldf(query)").
Right?

You can't read a reactive value like v$counter from the top-level of the
shinyServer function; the whole point of reading reactive values is so that
the reactive(), output, or observe() can re-execute when the reactive value
changes. Since you're not inside a reactive(), output, or observe(), Shiny
assumes it's a bug in your code--and indeed, in this case, it seems to be.

**Comment by abhisheknigam04** [comment]
I see your point and it makes sense to me.Thanks for the patience so far.
I have tried to place the increment code for counter within the renderTable content as follows - 
output$view <- renderTable({               
    query <- paste0("      
                     select a.*,
                     ('",paste0(v$counter),"') as c_flag
                     from Store as a
                     Where Segment in ('",paste0(input$Segment,collapse = "','"),"') 
                     and State in ('",paste0(input$State,collapse = "','"),"') 
                   ")
    v$counter <<- v$counter + 1
    sqldf(query) 
    })
However, the problem of dynamically updating the counter variable/object is still there.
The SQL query runs fine and the data is refreshed but the increment of counter by 1 doesn't actually happen. I'm not sure where should I place   v$counter <<- v$counter + 1 within the renderTable.
Do you think it can be achieved without the user input ?

**Comment by abhisheknigam04** [comment]
As a work around, I did this change and it worked..
output$view <- renderTable({        
      if (!file.exists("counter.Rdata")) 
        counter <- 0
      else
        load(file="counter.Rdata")
      counter  <- counter + 1
      save(counter, file="counter.Rdata")               
      query <- paste0("      
                     select a.*,
                     ('",paste0(counter),"') as c_flag
                     from Store as a
                     Where Segment in ('",paste0(input$Segment,collapse = "','"),"') 
                     and State in ('",paste0(input$State,collapse = "','"),"') 
                   ")
    sqldf(query)
    })
Just put the necessary if condition within the renderTable.But I'm sure there'll be a better way to do this..Please share if anyone has any alternate thoughts.

**Comment by Ramanujakalyan** [comment]
@abhisheknigam04  Could you please send me the ui.r and server.r for your first task. (reading a variable from shiny ui). Thanks.

**Comment by alandipert** [comment]
Closing because it appears that the original issue was eventually resolved. Please don't hesitate to comment or create a new issue if I misunderstand.
