### ISSUE TITLE
Updating the R Shiny UI dynamically

### ISSUE THREAD

**Issue by abhisheknigam04** [rstudio/shiny#790]
I was working on a basic data manipulation exercise in which I need to create dynamic UI.
For example - I have a SQL query which leads to creation of a dataset in R. 
Now, based on the schema of the dataset (eg. - no.of rows, column attributes) I want to generate a tab that contains list of check boxes that gets updated every iteration I run.Based on which I can decide I want to keep or delete the outputs.
Any ideas if this is possible ?

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports; for general help questions please use the shiny-discuss mailing list: https://groups.google.com/forum/#!forum/shiny-discuss


See this article: http://shiny.rstudio.com/articles/dynamic-ui.html

Also see the dynamic user interface section here: http://shiny.rstudio.com/gallery/
