### ISSUE TITLE
navbarPage hides shiny server pro logout message

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shiny#791]
My app use a navbarPage as you can see below.

It hides the "username + logout" message of shiny server pro (I reported to support but was asked to submit the problem to shiny: boh?).
The strange thing is that e.g. the progress messages are fine as they are coming above the bar, but the logout is barely visible "under" the navbarPage.

```R
appTitle <- "My app"
#
shinyUI(fluidPage(  theme = shinytheme("cerulean"), 
  includeCSS("./www/checkbox.css"),
  navbarPage(appTitle ,id = "main", 
[etc.]
```

**Comment by jcheng5** [comment]
Can you try adding this CSS?

```r
tags$style(type="text/css", ".shiny-server-account { z-index: 1000; }")
```

Let me know if that doesn't fix it and I'll set up an environment for repro. Thanks.

**Comment by jcheng5** [comment]
BTW, I don't think `fluidPage` and `navbarPage` are intended to be nested--is there a reason you're doing that? (Note that `navbarPage` has the `theme` parameter as well.)

If it's just to give you a handy place to hang `includeCSS`, then maybe just wrap a `tagList()` call around `includeCSS` and `navbarPage`.

**Comment by smartinsightsfromdata** [comment]
@jcheng5 ```tagList()```  wrapped around ```tags$style```,```includeCSS``` and  ```navbarPage``` worked! 

Thanks.  Could you kindly - when you have the time - look at the endless loop with DT please?

**Comment by koseri** [comment]
This issue has re-occurred in shiny server pro since around 1.4.7 and through 1.5.2.764 [at the time I am writing this]. The same solution applies:
```
shinyUI(
  tagList (
    tags$style(type="text/css", ".shiny-server-account { z-index: 1000; }"),

  navbarPage( title = "Shinola",... )
```
