### ISSUE TITLE
[question] sliderInput html source code

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [rstudio/shiny#792]
Hi there,
I'd like to know the html tag corresponding to  `sliderInput` in order to use it in a  customized shiny app. 
For example, to display a DataTable, I usually declare:
```html
<div id="your id here" class="shiny-datatable-output"></div>

```
on the html side

Example2: To display an rCharts figure I use :
```html
<div id="your id here" class="shiny-html-output rChart highcharts"></div>

```

However I can't find any equivalent for `sliderInput` . Note that I have already declared `ion.rangeSlider` (both js and css)

Thanks in advance,

**Comment by wch** [comment]
The easiest way is to create a simple shiny app, open it in a browser, and then view the page source. For example:

```R
 shinyApp(fluidPage(sliderInput("slider", "Slider:", 0, 10, 5)), function(input, output) {})
```
