### ISSUE TITLE
Add support for external links in tabPanels

### ISSUE THREAD

**Issue by Ironholds** [rstudio/shiny#794]
It'd be nice to be able to insert a tabPanel that links directly to a (non-shiny) page (if that already exists, I've not yet worked out how to do that)

**Comment by wch** [comment]
Not sure I understand - what do you mean by a tabPane?

**Comment by Ironholds** [comment]
Typo! My bad; I meant tabPanel()

**Comment by wch** [comment]
If I understand you correctly, I think you'd have to use an iframe for this.

**Comment by Ironholds** [comment]
Are there any examples that you're aware of? Not being able to link people to specific dashboard sub-pages is kinda a pain.
