### ISSUE TITLE
Do we still need to remove slider from jQuery UI

### ISSUE THREAD

**Issue by yihui** [rstudio/shiny#799]
https://github.com/rstudio/shiny/commit/7e12a281f51e047336ba2c501fcac43af5253225

Since we are using the Ion.RangeSlider now, I guess we probably do not have conflicts any more. The problem with a tailored version of jQuery UI is that we may run into trouble when an HTML widget also uses jQuery UI, and the two versions of jQuery UI are not compatible (one with slider and one without).

**Comment by wch** [comment]
Is it possible to fix it with this?
http://stackoverflow.com/questions/6358961/using-multiple-jquery-ui-versions

**Comment by yihui** [comment]
The SO answer looks pretty vague. I don't know why it was accepted. Anyway, the original problem https://github.com/smartinsightsfromdata/rpivotTable/issues/18 has been solved. I was just worrying about other potential cases in which shiny's jQueryUI is picked but the widget packages does use jQueryUI's slider. If we do not really have to remove the slider now, I'd vote for including the full version of jQueryUI to avoid confusion.

**Comment by smartinsightsfromdata** [comment]
@yihui @wch  Sadly the problem of conflicting jquery versions is still there, unresolved in its pernicious essence.

The following example creates problems (sort of resolved, but please read on), as reported (here)[https://github.com/smartinsightsfromdata/rpivotTable/issues/22]

````
library(shiny)
library(rpivotTable)

ui = shinyUI(fluidPage(
  dateRangeInput('dateRange',
                 label = 'Rango de Fechas: yyyy-mm-dd',
                 start = as.Date("2015-01-01"), end = Sys.Date() -1
  ),
  rpivotTableOutput('table' )

))

server = function(input, output){
  output$table <- renderRpivotTable({
    iris %>%
      tbl_df %>%
      filter( Sepal.Width > 3 ) %>%
      rpivotTable
  })
}

shinyApp(ui = ui, server = server)
```

This code works now, aligning rpivotTable to shiny jquery-ui 1.10.4,  but at what cost?

The latest `ggvis 0.4.2` has adopted jquery-ui 1.11.4 and does not work with the rpivottable  conflict on the jquery-ui versions (0.4.1 still does work): I should produce two version of rpivotTable, one to work with ggvis, the other to work with shiny!

I've discussed this issue at high level with @jcheng5  and opened an issue (here)[https://github.com/rstudio/shiny/issues/890] and (here)[https://github.com/rstudio/ggvis/issues/410]

Is there any chance of shedding some light at the end of this particular tunnel?

Thanks!

**Comment by yihui** [comment]
I don't know... Perhaps just let everybody upgrade to a latest full version of jQueryUI? The main problem is that we need thorough testing, and currently we don't have such automatic tests, so there is always risk upgrading these JS libraries.

**Comment by wch** [comment]
I've updated to a full build of jQuery UI in #984. Similarly, ggvis has a full build now. Both have 1.11.4. Can we close this now?

**Comment by yihui** [comment]
I guess we can close it now. @smartinsightsfromdata you can check if the current development version of shiny has fixed your issue in rpivotTable.

**Comment by smartinsightsfromdata** [comment]
@yihui @wch   Just an update.  Aligning rpivotTable to ggvis & shiny jquery / jquery-ui I've resolved the issue with ggvis (thanks again).

On the other hand this specific issue with the dateRangeInput **still stands**.

I get this error at the console:
````
jquery-ui-1.11.4.js:4558    Uncaught TypeError: Cannot read property 'empty' of undefined
````
And this is the code associated:

````
	/* Generate the date picker content. */
	_updateDatepicker: function(inst) {
		this.maxRows = 4; //Reset the max number of rows being displayed (see #7043)
		datepicker_instActive = inst; // for delegate hover events
		inst.dpDiv.empty().append(this._generateHTML(inst)); // <-- the error happens here
		this._attachHandlers(inst);
````

Please advise!

**Comment by smartinsightsfromdata** [comment]
What surprises me is that without rpivotTable, it seems that no jquery-ui is loaded, hence there is no conflict.
With rpivotTable jquery-ui is loaded and I do get the conflict.

No conflict with jquery-ui 1.10.4 (but then I go back to square 0!).

**Comment by wch** [comment]
@smartinsightsfromdata I'm having trouble keeping track of all the entangled issues. Could you file a new one and the exact steps to reproduce your issue?

I tried running your example app above with the latest shiny and rpivottable from github, and get no errors (in Chrome on Linux).

**Comment by smartinsightsfromdata** [comment]
No prob.
