### ISSUE TITLE
Error in setwd(bundleDir) : cannot change working directory

### ISSUE THREAD

**Issue by lauthiamkok** [rstudio/shiny#808]
I keep getting this error when I try to deploy my shiny app,

```
library(shiny)
library(shinyapps)
deployApp()

Uploading application bundle...
Error in setwd(bundleDir) : cannot change working directory
```

Any ideas what is going on?

**Comment by wch** [comment]
This sounds like a shinyapps issue. Could you file it here: https://github.com/rstudio/shinyapps/issues
