### ISSUE TITLE
Gotcha when creating a fluidRow from a list with do.call

### ISSUE THREAD

**Issue by skranz** [rstudio/shiny#809]
Hi,
I often create dynamic shiny apps, where I generate a `fluidRow` from a list of widgets with `do.call`. Below is a simple artifical example:
```r 
 library(shiny)
  # Create one button per person
  persons = list(
    peter=list(id=1,name="Peter"),
    paul=list(id=2,name="Paul")
  )
  btn.li = lapply(persons, function(person) {
    id = paste0("btn_",person$id)
    actionButton(id,label = person$name)
  })
  #names(btn.li) = NULL
  btn.row = do.call(fluidRow,btn.li)

  
  ui = fluidPage(
    title = 'Gotcha Example',
    btn.row,
    textOutput("mytext")
  )
  
  server = function(input, output, session) {
    output$mytext <- renderText({
      num = input$btn_1+input$btn_2
      txt = paste0("You pressed ", num, " times a button")
      txt
    })
  }
  runApp(list(ui=ui,server=server),launch.browser=rstudio::viewer) 
  ```
Unfortunately, when running this example on my computer, no buttons are shown. To make it work, one must uncomment the line
```
  #names(btn.li) = NULL
```
To clear all list names before calling `do.call(fluidRow,btn.li)`. I found it really hard to trace down this problem in my actual application. I wonder whether it is a good idea to change shiny or its documentation to help other users avoid this mistake. Is it intended that fluidRow (or other container functions) does not work here if the passed arguments are named, or could one just change the behavior of fluidRow?

**Comment by wch** [comment]
That is how all the HTML tag functions work: named arguments become properties of the HTML tag, while unnamed arguments become content. For example:

```R
div(1, 2)
# <div>
#   1
#   2
# </div> 

div(a=1, b=2)
# <div a="1" b="2"></div> 
```

`fluidRow` has the same behavior. Perhaps it would make sense to link to the tags help page (e.g., what you get with `?div`, and where it discusses named/unnamed args) from the `fluidRow` help page.

**Comment by skranz** [comment]
Ok, I see that this is a nice design. Thanks for the quick reply.

If nevertheless many people step into the `do.call` trap, then I guess probably the best way to prevent it, would indeed be a link with a brief warning in the documentation, and / or a small example illustrating how to generate a `fluidRow` or `div` from a list.

**Comment by jcheng5** [comment]
BTW you don't even need the do.call. Just fluidRow(btn.li) should work fine--lists are automatically unpacked, for exactly this scenario.
