### ISSUE TITLE
R Shiny selectizeInput server side not initializing correctly

### ISSUE THREAD

**Issue by jwdejong** [rstudio/shiny#814]
When trying to embed the selectize input widget in an Shiny application I ran into the following problem:

The item list isn't initialized with the complete list of items when using `server = TRUE`. Only after entering a character in the searchbox will the items appear. This is contrary to the behaviour when `server = FALSE`. In this case all items appear in the box initially (and this is the behaviour that I want). The reason that I want to use the `server = TRUE` option is that I want to be able to apply formatting to the items and this is not possible when generating the items client side. The example below reproduces the phenomenon with one selectize input using `server = TRUE` and the other with `server = FALSE`. In my opinion the behaviour should be the same in both cases.

Example app.R to reproduce the issue:

```r
library(shiny)

server <- function(input, output, session) {
  updateSelectizeInput(session, 'cars1', server = TRUE, choices = rownames(mtcars))  
  updateSelectizeInput(session, 'cars2', server = FALSE, choices = rownames(mtcars))
}

ui <- fluidPage(
  selectizeInput('cars1', label = "server side", choices = NULL),
  selectizeInput('cars2', label = "client side", choices = NULL)  
  )

shinyApp(ui = ui, server = server)
```
Is this a bug or am I using the widget incorrectly? I am running R version 3.1.3 and Shiny 0.11.1 on Windows 7 64-bit.

I've also posted this issue as a question on stackoverflow: http://stackoverflow.com/questions/29966936/r-shiny-selectizeinput-server-side-not-initializing-correctly/29970532#29970532

**Comment by yihui** [comment]
I was aware of this problem when implementing `updateSelectizeInput()`: https://github.com/rstudio/shiny/blob/4a74f588b9d/R/update-input.R#L437-L439 In the server mode, I don't know what options to display until you type and search in the text box. I just thought a while about this again, and sent a PR #814 to change the behavior so you will see the first 1000 options by default.

**Comment by jwdejong** [comment]
OK thnx, that will solve the issue for me.
