### ISSUE TITLE
Maximum layer hierarchy for the menu

### ISSUE THREAD

**Issue by feiyangdou** [rstudio/shiny#816]
I tried to create a sub menu item under a menusubitem and I found that it didn't show up. Just wonder if I could have a hierarchy of the menu items more than two layer. Thanks!

**Comment by alandipert** [comment]
Hello, sorry to take so long to respond, but I think the answer is no. From `?shinydashboard::menuSubItem`:

> A dashboardSidebar can contain a sidebarMenu. A sidebarMenu contains menuItems, and they can in turn contain menuSubItems. 

There isn't mention of nesting below `menuSubItems`.

If you have additional questions, please don't hesitate to ask them on [shinydashboard/issues](https://github.com/rstudio/shinydashboard/issues).
