### ISSUE TITLE
runExample() is hardwired to the system lib

### ISSUE THREAD

**Issue by rappster** [rstudio/shiny#819]
I just noticed by chance that `runExample()` calls `system.file()` without specifying `lib.loc` which results in the function always looking for the examples folder in the system lib `R.home("library")` even though packrat is enabled and a project-specific version of shiny has been installed.

Nothing serious, but I just thought I'd let you know really quick as this might contradict the packrat paradigm to some extend:

![packrat](https://cloud.githubusercontent.com/assets/1205659/7474030/28d21e0a-f33f-11e4-9f45-8e929e1924cf.png)

Substituting `system.file("examples", package = "shiny")` with `system.file("examples", package = "shiny", lib.loc = .libPaths()[1])` inside `runExample()` should "solve" it.

**Comment by jcheng5** [comment]
Hmmm, you shouldn't need to provide `lib.loc`. @kevinushey, any ideas?

**Comment by jcheng5** [comment]
BTW I can't repro this on my machine.

**Comment by rappster** [comment]
What I did: 
1. At some point, I installed shiny via `install.packages("shiny")` without being in a package project and without having packrat turned on. So it ended up in `R.home("library")`
2. Then I created a new package project that uses packrat, turned it on and installed shiny to the project lib.
3. As I wanted to copy the examples from `~/shiny/examples` to a directory of my package project, I looked at the code of `runExample()` in order to find out where the examples reside. And that's when I noticed that `runExample()` calls `system.file("examples", package = "shiny")` and thus will use the shiny package that has been installed to the system-wide lib.

**Comment by jcheng5** [comment]
Can you report this on [Packrat](https://github.com/rstudio/packrat) instead? Omitting the `lib.loc` argument when calling `system.file` is not supposed to use the system-wide, it's supposed to consult `.libPaths()` in order.

```r
> system.file("examples", package='shiny')
[1] "/home/jcheng/packtest/packrat/lib/x86_64-pc-linux-gnu/3.2.0/shiny/examples"
```

**Comment by rappster** [comment]
Sure, will do.
