### ISSUE TITLE
Plot overlaying image

### ISSUE THREAD

**Issue by rappster** [rstudio/shiny#821]
I played around with [lesson 5](http://shiny.rstudio.com/tutorial/lesson5/) while also displaying the [birgorb.png](http://shiny.rstudio.com/tutorial/lesson2/www/bigorb.png) image from [lesson 2](http://shiny.rstudio.com/tutorial/lesson2/). 

While for other output types the automatic vertical arrangement seems to work fine it seems like its off when a plot follows an image:

![shiny_1](https://cloud.githubusercontent.com/assets/1205659/7476967/408d32e8-f351-11e4-8b62-1dd3c32878d3.png)

UI:

```
shinyUI(fluidPage(
  titlePanel("censusVis"),

  sidebarLayout(
    sidebarPanel(
      helpText("Create demographic maps with
        information from the 2010 US Census."),

      selectInput("var",
        label = "Choose a variable to display",
        choices = c("Percent White", "Percent Black",
          "Percent Hispanic", "Percent Asian"),
        selected = "Percent White"),

      selectInput("image",
        label = "Choose an image to display",
        choices = c("bigorb", "other"),
        selected = "bigorb"),

      sliderInput("range",
        label = "Range of interest:",
        min = 0, max = 100, value = c(0, 100))
    ),

    mainPanel(
      textOutput("text1"),
      br(),
      textOutput("text2"),
      br(),
      uiOutput("ui1"),
      uiOutput("ui2"),
      br(),
      imageOutput("image1", width = "20px", height = "20px"),
      br(),
      plotOutput("map")
    )
  )
))
```

Server:

```
library(maps)
library(mapproj)
source("helpers.R")
counties <- readRDS("data/counties.rds")

shinyServer(function(input, output) {

  output$text1 <- renderText({
    paste("You have selected", input$var)
  })

  output$text2 <- renderText({
    paste("You have chosen a range that goes from",
      strong(input$range[1]), " to ", input$range[length(input$range)])
  })

  output$ui2 <- renderUI({
    p("You have chosen a range that goes from",
      strong(input$range[1]), " to ", input$range[length(input$range)])
  })

  output$ui1 <- renderUI({
    list(a = 1, b = 1:10, c = strong("Hello World!"))
    # p(strong("Hello"), "world")
  })

  getImage <- reactive({
    # print(input$image)
    # img(src = sprintf("%s.png", input$image), height = 72*0.5, width = 72*0.5)
    # sprintf("%s.png", input$image)
    list(src = file.path(getwd(), sprintf("www/%s.png", input$image)),
      alt = "This is alternate text")
  })

  output$image1 <- renderImage({
    getImage()
  }, deleteFile = FALSE)

  output$map <- renderPlot({
    args <- switch(input$var,
      "Percent White" = list(counties$white, "darkgreen", "% White"),
      "Percent Black" = list(counties$black, "black", "% Black"),
      "Percent Hispanic" = list(counties$hispanic, "darkorange", "% Hispanic"),
      "Percent Asian" = list(counties$asian, "darkviolet", "% Asian"))

    args$min <- input$range[1]
    args$max <- input$range[2]

    do.call(percent_map, args)
  })

})

```

**Comment by jcheng5** [comment]
Is the rendering of the orb you're talking about? This seems to be because the imageOutput div is only 20x20 but the image tag you're returning into it is much larger; if you give the renderImage result a `style="width: 20px; height: 20px"` I think it should look correct.

@wch should we have a rule `.shiny-image-output img { width: 100%; height: 100%; }` ? Or maybe `max-width`/`max-height`?

**Comment by jcheng5** [comment]
Actually maybe you're asking why the orb isn't displayed--if you take the width and height off the `imageOutput`, I think it would be.

**Comment by rappster** [comment]
Right, that looks better!

![shiny_2](https://cloud.githubusercontent.com/assets/1205659/7480732/e14cd828-f36a-11e4-9a64-8662d521d8fd.png)

But where/how would I scale the orb correctly if I wanted to while making sure that no overlapping occurs?

**Comment by jcheng5** [comment]
I'd add `style="width: 100px; height: 100px"` to the list you return from `renderImage`.

**Comment by rappster** [comment]
Gotcha. Thanks for the quick replies!

**Comment by alandipert** [comment]
Closing because it appears the original question has been answered; please don't hesitate to comment further or create a new issue if I misunderstand.

**Comment by appropiate** [comment]
This does not seem to work for me. I have an rmarkdown document at the top and an interactive plot at the bottom of a tabPanel that overlap each other because the markdown document has  paragraphs that become thicker and make the document longer as the app window is narrowed. If I set the height of the markdown document high enough so that it doesnt overlap with the plot below when the app window is narrowed, then it would look far apart from the plot when the app window is maximized. Is there a way to keep the distance from each other constant regardless of the app window being narrowed or maximized? here is a modified version of my code for the ui:

```tabPanel("Dataset",                                
                                hr(),
                                tags$iframe(  
                                  src = "summary.html",
                                   width="100%", 
                                   height="550",
                                  scrolling="no",
                                  seamless="seamless",
                                  frameBorder="0"),
                                hr(),
                                plotOutput("myplot", 
                                   width="100%",
                                   height="550")
                        )
```
