### ISSUE TITLE
updateCheckboxGroupInput inconsistency 

### ISSUE THREAD

**Issue by georam** [rstudio/shiny#831]
Hi,
I found a problem when I use the "updateCheckboxGroupInput" with a couple of action buttons to select/deselect all the choices on the group . After updating with "selected=FALSE", all the choices are deselected but the change does not affect the reactive components associated as is the case of selecting all. I know that there are many ways to do this task, my point here is to show the lack of consistency of the "updateCheckboxGroupInput" with the "selected" parameter. Maybe it is no a bug and it is just a feature, but I would like to know if it was designed like that. Here is simplified example that represents the problem:

``` javascript
choices <- letters[1:5]
runApp(list(
  ui = basicPage(
    checkboxGroupInput('chkGrp', 'Options', choices),
    actionButton("all","All"),
    actionButton("none","None"),
    verbatimTextOutput("value")
  ),
  server = function(input, output, session) {
     output$value <- renderPrint({ input$chkGrp })
     observe({
          if ( is.null(input$all) || input$all == 0)
               return()
          updateCheckboxGroupInput(session,"chkGrp",selected=choices )
     })
     observe({
          if ( is.null(input$none) || input$none == 0)
               return()
          updateCheckboxGroupInput(session,"chkGrp",selected=FALSE)
     })
  }
))
```

**Comment by wch** [comment]
One way to make this work right now is to use `selected=character(0)`. We'll have to take a look at whether this is a good solution for general use. If so, we should update the docs; if not, we should come up with a better way.

**Comment by georam** [comment]
It works fine, having that in the documentation will be good but I think it is still necessary to find a better way to do that.
Thank you.

**Comment by alandipert** [comment]
I updated the example and tried with most recent Shiny (1.3.2) and this appears to be fixed:

![update_select](https://user-images.githubusercontent.com/26024/56827599-23287780-6814-11e9-807e-3252f8b5927e.gif)

```R
choices <- letters[1:5]
ui <- basicPage(
    checkboxGroupInput('chkGrp', 'Options', choices),
    actionButton("all","All"),
    actionButton("none","None"),
    verbatimTextOutput("value")
  )
server <- function(input, output, session) {
    output$value <- renderPrint({ input$chkGrp })
    observe({
      if ( is.null(input$all) || input$all == 0)
        return()
      updateCheckboxGroupInput(session,"chkGrp",selected=choices )
    })
    observe({
      if ( is.null(input$none) || input$none == 0)
        return()
      updateCheckboxGroupInput(session,"chkGrp",selected=FALSE)
    })
  }

shinyApp(ui, server)
```
Please don't hesitate to comment further or open a new issue if you I misunderstand or if you are still experiencing the problem.
