### ISSUE TITLE
Please upgrade the 'shiny' package to (at least) version 0.12 (but it is not out yet!)

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shiny#832]
Please see https://github.com/smartinsightsfromdata/rpivotTable/issues/22

Many thanks

**Comment by wch** [comment]
It is out, though binary packages might not be available on all platforms. You might need to do `install.packages('shiny', type='source')`.

See http://cran.r-project.org/web/packages/shiny/index.html

**Comment by Tixierae** [comment]
After modifying a package with C3 widgets (https://github.com/Tixierae/shinyJsTutorials) which I call from my app, and re-installing, I get `ERROR: Please upgrade the 'shiny' package to (at least) version 1.0.5.9000` when executing `runApp()` from RStudio. But this version does not seem to be out. The latest one from http://cran.r-project.org/web/packages/shiny/index.html seems to be `1.0.5`.

Minimal example (hopefully you can reproduce the error)
````
library(shiny)
library(C3) # install via devtools::install_github("tixierae/shinyJsTutorials/tutorials/materials2/C3")

server = function(input,output) {
  output$gauge_risk = renderC3Gauge({
    C3Gauge(value = 15)
  })
}

ui = shinyUI(
  C3GaugeOutput("gauge", height = 150)
)
shinyApp(ui=ui, server=server)
````
actually I get the error just trying to run 

````
ui = shinyUI(
  C3GaugeOutput("gauge", height = 150)
)
````

**Comment by wch** [comment]
@Tixierae you must have have installed some other package that is depending on the development version of shiny.

The dev version of Shiny can be installed with:

```R
install.packages('devtools')
devtools::install_github('rstudio/shiny')
```

**Comment by Tixierae** [comment]
I couldn't install the dev version of Shiny because httpuv installation fails.
So now I'm running my app on ubuntu (was on windows before), and with the CRAN version of shiny I don't have any problem.

**Comment by wch** [comment]
@Tixierae On Windows, you'll need to install Rtools in order to install the development version of httpuv.

**Comment by wch** [comment]
A follow-on to the issues that @Tixierae is seeing.

This message is from:
https://github.com/ramnathv/htmlwidgets/blob/160872d367cc30830e38f0a62783f1d9e296c94b/R/htmlwidgets.R#L442-L451

It sounds like you probably installed the development version of some package, which caused the development version of htmlwidgets to be installed. 

I believe this Shiny version requirement was added in:
 https://github.com/ramnathv/htmlwidgets/commit/201ef8a41e5b663a44bf37205ba8363398f1a36a#diff-35ba4a2677442e210c23a00a5601aba3

My guess is that you are using a development version of plotly. If you have a problem installing httpuv, please file an issue on that repository:
https://github.com/rstudio/httpuv/issues
