### ISSUE TITLE
Can't install from devtools::install_github('rstudio/shinyapps')

### ISSUE THREAD

**Issue by Rewarp** [rstudio/shiny#835]
I am following the steps in shinyapps.io and am stuck at step 2.

```r
> devtools::install_github('rstudio/shinyapps')
Downloading github repo rstudio/shinyapps@master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
  error in running command
```

**Comment by yihui** [comment]
This is probably the wrong place to file this issue. Anyway, does it happen to shinyapps only, or is it a general `devtools::install_github` issue? e.g. does `devtools::install_github('rstudio/shiny')` work?

**Comment by Rewarp** [comment]
Sorry if I filed in in the wrong place. I am honestly not sure how to test the issue,

**Comment by yihui** [comment]
No worries. Do you mean you pasted `devtools::install_github('rstudio/shiny')` as well? And what did you get?

**Comment by Rewarp** [comment]
Yes. I just ran the command you pasted again, and got the same exact output in the OP.

    Downloading github repo rstudio/shiny@master
    Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
      error in running command

**Comment by yihui** [comment]
Okay, then this is not a shiny or shinyapps issue. It should be a devtools issue. The error message does not look informative to me, so I have no idea what's going on there. Sorry. 

Alternatively, though, you can just download the repo https://github.com/rstudio/shinyapps/archive/master.zip, unzip it, and run `R CMD INSTALL` on the unzipped directory, e.g. in R, `system('R CMD INSTALL path/to/shinyapps-master')`
