### ISSUE TITLE
On Windows: Shiny numericInput() does not show up/down arrows in the Viewer

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/shiny#836]
Running on Windows 7

Not sure if this RStudio, Shiny issue. Opened https://rstudio.fogbugz.com/default.asp?4492#24114 for RStudio as well.

Run Shiny example 02_text. In the viewer, up/down arrows are missing, but they are visible when openig the app in browser.

I have tried it with these versions of RStudio and Shiny:

RStudio Version 0.98.1091
RStudio Version 0.98.1103

Shiny 0.10.x
Shiny 0.12.0

**Comment by wch** [comment]
I believe that the presence of the up/down arrows is browser dependent - some browsers have them and some don't.

You can test with example here: http://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_number

**Comment by johng42** [comment]
To be clear, this bug refers to the UI in RStudio.  The up/down controls appear in browsers, but not when running the app in RStudio.

**Comment by jcheng5** [comment]
That's known for RStudio v0.98. Do you mind trying with v0.99? I'm hoping the Qt version upgrade fixed it.

**Comment by johng42** [comment]
I don’t seem to have access to R Studio 0.99 – the page only lets me have access to .098.  Checking for updates says I have the latest version.

**Comment by jcheng5** [comment]
Here you go:
http://www.rstudio.com/products/rstudio/download/preview/

**Comment by johng42** [comment]
That does indeed fix the error.  I cannot tell why, of course, but the problem does not repro in R Studio 0.99

**Comment by fereshtehRS** [comment]
Also verified the fix in 0.99.
