### ISSUE TITLE
Using multiple apps on same host can exhaust browser connection limits

### ISSUE THREAD

**Issue by wch** [rstudio/shiny#842]
If one browser connects to multiple apps on the same host, it can hit a connection limit when using SockJS. For example, Chrome has a maximum of 6 connections to the same host, so if you have more than 6 apps open in different windows/tabs/iframes, then some of them will stop working without giving any indication of why. I've seen this when using multiple apps hosted on shinyapps.io.

With subapps this is worked around by sharing connections, but this doesn't work for apps in separate windows/tabs/iframes.

I found an answer on SO that discusses sharing websocket connections by using local storage. Perhaps something like this could be adapted for SockJS?
  http://stackoverflow.com/a/11458341/412655

**Comment by jcheng5** [comment]
This should probably go on the shiny-server or connect repo, since Shiny doesn't speak anything but websockets.
