### ISSUE TITLE
Addmarker - Change icon

### ISSUE THREAD

**Issue by jsenjuto** [rstudio/shiny#845]
Hi,

I have been having problems with addMarker function in leaflet-shiny. I can not change the default icon by other one (web or local path). Can someone help me?

P.S: Great job!!

map$addMarker(40.41, -3.70, options=list(icon=list(iconUrl='Golf.png')))

Details: Golf.png is inside the "www" folder inside the application.

map$addMarker(40.41, -3.70, options=list(icon=list(             iconUrl='http://img2.wikia.nocookie.net/__cb20110725041802/logopedia/images/8/89/Logo_rolling_stones.png')))          

Thx in advance!!

**Comment by yihui** [comment]
The leaflet package in the [leaflet-shiny repo](https://github.com/jcheng5/leaflet-shiny) has been deprecated. Please use this one instead: https://github.com/rstudio/leaflet
