### ISSUE TITLE
Shiny App - Loading csv with column names from Input Text

### ISSUE THREAD

**Issue by calculus-ask** [rstudio/shiny#851]
I am trying to load csv file with columns names from Input text, if header = FALSE. The textInput in col.names(c() works bit weird. When i entered textInput as "a","b","x" the input text is read as "\"a\",\"b\",\"x\"".

http://stackoverflow.com/questions/30541866/shiny-app-loading-csv-with-column-names-from-input-text

**Comment by wch** [comment]
The shiny-discuss mailing list is the place to ask questions like this.

R is printing it with backslashes to show that the quote characters are characters in the string, and not delimiters for the string. This is called escaping.

For example, if you run this at the console, R will escape all the double-quotes in the string; the double-quotes at the beginning and end of the string indicate the bounds of the string:

```R
> '"a","b","c"'
[1] "\"a\",\"b\",\"c\""
```

But if you use `cat` to display the string directly, it'll print out the string without escaping the quotes, and without providing quotes at the start and end:

```R
> cat('"a","b","c"')
"a","b","c"
```

So the issue you're facing is something else.

**Comment by calculus-ask** [comment]
@wch thanks for the reply..
 tired with your input.. 

library(shiny)

shinyServer(function(input, output,session) 
  {
  output$contents <- renderTable({
  
          if (input$header== TRUE) 
          {
            infile <- input$file1
            if (is.null(input$file1)) {return(NULL)}
            read.csv(infile$datapath)
          }
        else
          {
            infile <- input$file1
            if (is.null(input$file1)) {return(NULL)}
            cols <- renderText({cat(input$value)})
            read.csv(infile$datapath,header=FALSE,col.names=c(cols()))
          }
      
})})

ui.R

library(shiny)
shinyUI(fluidPage(
  
  titlePanel("The Ace!"),
           navbarPage("Calulus@Work",  
            tabPanel("About Tool"
                     ),
            navbarMenu("Data Load",
                        tabPanel("Delimter",
                                 sidebarLayout(
                                   sidebarPanel(fileInput('file1', 'Choose file to upload',
                                               accept = c('text/csv',
                                                 'text/comma-separated-values',
                                                 'text/tab-separated-values',
                                                 'text/plain','.csv','.tsv'
                                               )),
                                     checkboxInput('header', 'Header', TRUE),
                                     textInput("value","Enterhere","")
                                     ),
                                   mainPanel(
                                     tableOutput('contents')))))
                                                
             
             )#navbarPage
  
)#fluidpage
)#shinyUI

Listening on http://127.0.0.1:4297
"a","b","c"
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names
