### ISSUE TITLE
How to pass arguments to a reactive function?

### ISSUE THREAD

**Issue by Make42** [rstudio/shiny#858]
I want to use rstudio/leaflet together with shiny. This works:

      colorstyle <- reactive({
             as.character(input$colorstyle)
      })

      output$mapplot <- renderLeaflet({

            pal <- colorNumeric(
                 palette = colorstyle(),
                 domain = stations_shown()$density
              )

             leaflet::leaflet(stations) %>%
                addTiles() %>%
                addCircles(popup = ~as.character(density), opacity = 1, color = ~pal(density))
      })

However I would also like to get pal outside renderLeaflet(), but when I write

      colorstyle <- reactive({
             as.character(input$colorstyle)
      })

       pal <- reactive({
            pal <- colorNumeric(
                    palette = colorstyle(),
                    domain = stations_shown()$density
            )
            return(pal)
       })

      output$mapplot <- renderLeaflet({

             leaflet::leaflet(stations) %>%
                addTiles() %>%
                addCircles(popup = ~as.character(density), opacity = 1, color = ~pal(density))
      })

I get the error 

       Error in pal(density) : unused argument (density)

I guess it has something to do with the fact that I put an argument into pal with pal(density), and density is not passed over to pal, but I don't know how to get it to work.

**What to do?**

PS: I posted this issue at https://github.com/rstudio/leaflet/issues/114 but I realized that it is  most likely a shiny issue.

**Comment by jcheng5** [comment]
Can you do pal()(density)? I know it seems weird, but the first () is
retrieving the pal function, the second () invokes it.

Also I'd change this:

   pal <- reactive({
        pal <- colorNumeric(
                palette = colorstyle(),
                domain = stations_shown()$density
        )
        return(pal)
   })


to this:

   pal <- reactive({
        colorNumeric(
                palette = colorstyle(),
                domain = stations_shown()$density
        )
   })


just to remove the confusion of the duplicate variable names.

**Comment by Make42** [comment]
Well, who would have thought - this actually worked. Thank you so much!
