### ISSUE TITLE
Problem creating new project with files

### ISSUE THREAD

**Issue by asgr** [rstudio/shiny#860]
I am running the latest RStudio Version 0.99.441 on a Mac with Yosemite (10.10.3). I tried to create a New Project -> New Directory -> R Package. If I don't provide any initial files the project initialises fine, but if I provide any .R functions that I've already made I get a pop-up window saying "Error Creating Project". I also get some text in the R console saying "Error in basename(sourceFiles) : a character vector argument expected".

Just to check, if I re-ran the same steps using older versions of RStudio and the new project is created in a new directory without issue, with the various skeleton files created in the project directory as expected (i.e. partially made manual files etc). package.skeleton also seems to work as normal.

**Comment by adamhsparks** [comment]
I've found this same issue on Yosemite. Thanks for the tip that not including source files works.

**Comment by andymckenzie** [comment]
I'm having the same issue on Yosemite.

**Comment by jjallaire** [comment]
Thanks for reporting. This should now be fixed in our very latest release (v0.99.551).
