### ISSUE TITLE
shiny server gives ERROR: there is no package named â€˜leafletâ€™

### ISSUE THREAD

**Issue by Make42** [rstudio/shiny#862]
I installed shiny server according http://www.rstudio.com/products/shiny/download-server/ and the upper test app on http://localhost:3838/ does work.

I build a shiny app using leaflet in RStudio. When I start a new R session (no variables in the environment, no packages loaded) and press "Run App" in RStudio, the app runs correctly*. Also going to http://127.0.0.1:4741 runs the app correctly.

Now I would like to get both together. I copied my app to o/srv/shiny-server/ and gave the command

      $ sudo start shiny-server

Then I go to http://localhost:3838/MyApp
but I only get the error message

      ERROR: there is no package named â€˜leafletâ€™

I have leaflet installed. Why is that error message there and what should I do to get rid of it and my app to run?

____
*or did, before I updated shiny this morning, but for that I better open a new issue.

**Comment by fereshtehRS** [comment]
Most likely you have installed the package as yourself, in your local library. In order for Shiny Server to have access to the package, you need to install it globally. 

You can use the following command (replace "package_name") to install a package from CRAN globally:
```
sudo su -   -c "R -e \"install.packages('package_name', repos='http://cran.rstudio.com/')\""
```

Or use the following to install from github:
```
sudo su -   -c "R -e \"devtools::install_github('rstudio/package_name')\""
```

**Comment by Make42** [comment]
Thanks for the hint and commands. The full set of commands I used are:

      $ sudo su -
      # myfavoritecranmirror='http://cran.uni-muenster.de/'
      # deb "$myfavoritecranmirror"/bin/linux/ubuntu vivid/
      # apt-get update
      # apt-get install r-base
      # apt-get install gdebi-core
      # gdebi shiny-server-1.3.0.deb
      # R
      > install.packages(devtools)
      > devtools::install_github('rstudio/leaflet')
      > install.packages('shiny', repos='http://cran.rstudio.com/')

So far I still get the error

       The application unexpectedly exited.
       Diagnostic information has been dumped to the JavaScript error console.

but I guess this is because of https://github.com/rstudio/shiny/issues/863
