### ISSUE TITLE
Cannot update a label if the input was created with NULL label

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#868]
If an input was created with a `NULL` label, trying to update the label later on does nothing. Probably because a <label> tag is never created.

Example:

```
runApp(shinyApp(
  ui = fluidPage(
    textInput("test", NULL, ""),
    actionButton("btn", "Button")
  ),
  server = function(input, output, session) {
    observeEvent(input$btn, updateTextInput(session, "test", label = "label"))
  }
))
```

**Comment by alandipert** [comment]
I was able to reproduce this with Shiny 1.3.2, so it remains unfixed.

**Comment by daattali** [comment]
When inputs are crated, if a `NULL` label is provided, then an HTML label tag is not created at all.  

https://github.com/rstudio/shiny/blob/386078d4415da7bbb05b8d63874758d5f6b1672f/R/input-text.R#L39

When an update function is called to update the label, the javascript searches for this (non-existing) label tag

https://github.com/rstudio/shiny/blob/386078d4415da7bbb05b8d63874758d5f6b1672f/srcjs/input_binding_text.js#L31

**Comment by daattali** [comment]
Just to confirm, this is fixed for all inputs, not just text inputs, correct?

**Comment by cpsievert** [comment]
Yep
