### ISSUE TITLE
Rprintf() automatically goes to the first renderPrint()

### ISSUE THREAD

**Issue by ewouddt** [rstudio/shiny#871]
One of the packages I am using in my Shiny app calls C-code in which the command <code>Rprintf()</code> is being used. Its description is as follows: <i>The function Rprintf is exactly like the standard printf function in C except that Rprintf sends its output to the R console so that you can see it when running R </i>

Now I have used <code>print()</code> in my shiny R code for debugging purposes and these prints have always appeared in the Command Prompt. These <code>Rprintf()</code>'s from C don't seem to do the same. They seem to appear in the first <code>renderPrint()</code> you encounter in your Shiny App.

Is this is intentional or is there a way to solve this issue? Because now I am getting unintended information in my renderPrint Output and the package using these Rprintf()'s does not provide a way to disable them.

**Comment by wch** [comment]
Can you supply a reproducible example? Are you saying that the `Rprintf()` isn't called anywhere in the `renderPrint()`, but yet the output gets captured there?

**Comment by ewouddt** [comment]
Thank you for the response. That is exactly what is happening!
 It might be difficult to provide an example without sending my entire code, but I will try to showcase better what is going on.

This part of the code is a part of my server.R which uses uploaded data and the input from some widgets to apply the <code>fabia()</code> function. 
After that a summary is being rendered to <code>verbatimTextOutput("fabplotsummaryFabLP")</code>.

<pre><code>FabLPOutput <- eventReactive(input$runFabLP,{
		validate(need(!is.null(input$uploaddata),"Please upload data"))	
		if(input$seedFabLP != 0){set.seed(input$seedFabLP)}
			withProgress(message="Calculating, please wait...",value=100,{
						non_negative_temp <- switch(input$non_negativeFabLP,"0"=0,"1"=1)
						center_temp <- switch(input$centerFabLP,"0"=0,"1"=1,"2"=2,"3"=3)
						norm_temp <- switch(input$normFabLP,"0"=0,"1"=1,"2"=2)
					out <- fabia(as.matrix(dataInput()),p=input$pFabLP,alpha=input$alphaFabLP,cyc=input$cycFabLP,spl=as.numeric(input$splFabLP),spz=input$spzFabLP,non_negative=non_negative_temp,random=input$randomFabLP,center=center_temp,norm=norm_temp,scale=input$scaleFabLP,lap=input$lapFabLP,nL=input$nLFabLP,lL=input$lLFabLP,bL=input$bLFabLP)
						return(out)
					})
		})

output$summaryFabLP <- renderPrint({
			summary_output <- FabLPOutput()
			return(summary(summary_output))
	})
</code></pre>

Inside this <code>fabia</code> function, a call is being made to a function made in C-code. In this C-code, the <code>Rprintf()</code> function is used as described in my previous post.

Extract from C-code:
<pre><code>
...
	if (i%20==0) {
	    Rprintf("Cycle: %d\r", i);
	    R_CheckUserInterrupt();
	}
   }
   Rprintf("Cycle: %d\n", i);
</code></pre>

![example1](https://cloud.githubusercontent.com/assets/12858201/8212763/e3b1b88e-151d-11e5-91d2-c3a38fb25642.png)

In this first picture, I had the first tab (Summary) open and clicked on Run to execute the fabia function. You can see that on the top of the Print Summary, some additional information about the cycles is appearing. However there is no information in the R Console in the Command Prompt.

![example2](https://cloud.githubusercontent.com/assets/12858201/8212961/199c5886-151f-11e5-87b5-0e68762c7b7a.png)

The second picture is when I had the second tab open and clicked on run. This contains another <code>renderPrint()</code>, unrelated to the first. Again, the same thing happens.

![example3](https://cloud.githubusercontent.com/assets/12858201/8212830/4f21ff5c-151e-11e5-9e2b-708da1fcbb51.png)

In this last example, I have another tab open (before pressing run) with no <code>renderPrint()</code> visible. As you can see in the bottom of the Command Prompt, now some information about these cycles <strong> did </strong> appear. If I would look in the first 2 tabs now, the additional cycle information will not be present on the top of the summary. It only seems to appear when the <code>renderPrint()</code> is visible and when then the fabia (with C-code) is being run.

I hope this clarifies the issue a little bit.

**Comment by wch** [comment]
If I understand your code correctly, you're actually getting the expected behavior.

For example, in this code, `output$txt` calls the reactive `r1()`, which contains a print statement. Because the `print()` is called (indirectly) inside of `renderPrint()`, its output is captured and then sent to the browser as `output$txt`.

```R
shinyApp(
  ui = fluidPage(
    actionButton("go", "Go"),
    verbatimTextOutput("txt")
  ),
  server = function(input, output) {
    r1 <- reactive({
      print(paste("value of input$go is", input$go))
    })
    
    output$txt <- renderPrint({
      r1()
    })
  }
)
```

**Comment by wch** [comment]
Actually, this might be a better demonstration. There are 3 `renderPrint`s that access the same reactive, and the print statement gets sent to one of them, but not always the same one, as you click the button.

```R
shinyApp(
  ui = fluidPage(
    actionButton("go", "Go"),
    verbatimTextOutput("txt1"),
    verbatimTextOutput("txt2"),
    verbatimTextOutput("txt3")
  ),
  server = function(input, output) {
    r1 <- reactive({
      print(paste("value of input$go is", input$go))
    })
    
    output$txt1 <- renderPrint( r1() )
    output$txt2 <- renderPrint( r1() )
    output$txt3 <- renderPrint( r1() )
  }
)
```

This is the _expected_ behavior, though it's worth discussing whether it's desirable. If we don't want this behavior, we'll probably have to capture the print output of reactives and replay them when a cached value is accessed.

**Comment by ewouddt** [comment]
Thank you very much for the explanation. 
I think I do understand the behaviour of print statements inside a reactive a bit better now. I suppose I will have to a bit careful with this in the future. However at the moment it seems there is nothing I can actually do about these extra prints as they are coded deep in the C-code of the R package.

So what was happening in the past picture, was it because no <code>renderPrint</code> was being run, the print was send to the R Console in the prompt?

**Comment by wch** [comment]
The way that `renderPrint()` works is by calling `capture.output()`. This function grabs all the printed output from R. For example:

```R
x <- capture.output({
  print("foo")
})

x
# [1] "[1] \"foo\""
```

If you want to keep the printed output, you should be able to call `capture.output()` in the `reactive()`, which will intercept the `Rprintf()` calls, and pass around that result. Here's an example of nested calls to `capture.output()`:

```R
x <- capture.output({
  y <- capture.output({
    print("foo")
  })
})

x
# character(0)

y
# [1] "[1] \"foo\""
```

**Comment by ewouddt** [comment]
Using the <code>capture.output()</code> in between works brilliantly in my scenario.
It completely fixes the issue I had.

Again, thank you very much for the great help and clarifications!

**Comment by wch** [comment]
Great!
