### ISSUE TITLE
Html radio buttons in a shiny APP doesn't work after Rstudio update

### ISSUE THREAD

**Issue by aygons** [rstudio/shiny#878]
Details borrowed from stackoverflow: http://stackoverflow.com/questions/30512086/html-radio-buttons-in-a-shiny-app

I have the same issue describes above. But I can get it worked locally with the same version of Shiny and Rstudio. Only when running on shiny server, it doesn't work anymore.

**Comment by jcheng5** [comment]
I answered on that post, can you see if that helps?

**Comment by aygons** [comment]
@jcheng5 Thank you Joe! It works well for me now. :+1:
