### ISSUE TITLE
Using observe vs observeEvent

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#882]
This is a discussion I started on the [Google Group](https://groups.google.com/forum/#!searchin/shiny-discuss/attali$20observe/shiny-discuss/Ah47LxpX2wI/am3Gx-s_thQJ), but since it hasn't been resolved and I don't want to lose reference to it, I wanted to post it here so that it's not forgotten and can be further discussed in the future.

**Original post**  
Hi Joe, I didn't want to have a discussion in an unrelated github issue so I'm moving here.

(For everyone else, see https://github.com/rstudio/leaflet/issues/115#issuecomment-111581458)

First of all, I'm sorry if I've been spreading bad advice.

When I first noticed `observeEvent` it seemed useful and I couldn't find too much docs on it or usecases so I used it as I thought made sense. Here's my reasoning for using it, let me know if it's valid or not: I like to use `observeEvent` even when the expr is very simple and only includes one reactive because of two reasons:

1. it takes care of the NULL case and doesn't run when the input is NULL, which is very often the wanted behaviour and saves me from writing `if (is.null(input$x)) return()`

2. I like how it's explicit in terms of exactly what reactive needs to change in order for it to run. I don't need to look at the code inside the expression to see what reactive value is the dependency, I have it as a parameter.

If observeEvent is slower or in any way worse or there are good reasons for not using it, do let me know. Or if my two points are invalid, let me know. That was just my uneducated way of seeing the difference between the two

Thanks 

---

**Joe's response**  
I'm impressed that those are your two reasons--they are the two best reasons I could think of, and #1 didn't occur to me until today.

For #1 I was hoping validate(need(input$x, FALSE)) would be an idiom that got widely adopted not only for observers but in reactives and outputs as well. Now that I put that in writing I see how ridiculous that sounds--it's a lot of tokens for what should really be something as concise as `required(input$x)`. I need to think more about this.

For #2 this is a philosophic difference, I guess. I built reactivity into Shiny because years of both web and desktop UI programming have led me to dread callback hell and the subtle bugs it introduces, and observeEvent is really nothing more than letting you use imperative/callback-style in Shiny's reactive world. Now, there's no question that imperative/callback-style is necessary sometimes--action buttons demand them. But I always get a little squeamish about encouraging imperative idioms outside of narrow cases. The reason for this is because I really believe that thinking reactively is the key to making non-trivial Shiny apps that are robust and can be reasoned about, and observeEvent when used for non-button scenarios can be a crutch that is definitely helpful at first but can delay learning about observers.

I'm curious--both of your reasons would seem to apply to eventReactive just as much as to observeEvent. Do you find yourself often using eventReactive for the same reasons? Or is there something different about the nature of reactive expressions vs. observers that makes eventReactive less appealing?

---

**My last response**  
#1. I must admit I was never an adopter of `validate`. I knew about it since day 1 of learning shiny but I always found it a bit clunky and never seemed to like it, so if I needed to validate an input I prefered to do it myself with `if (is.null())` or whatever other check was necessary. And when observeEvent came along and I saw the `ignoreNULL` param, I thought that was meant to solve my problems :)  I do see many people using validate so it does have its place, I just personally didn't adopt it.

#2. I do see your point on the reactivity vs callback nature of functions. So again, maybe this is just personal preference. I find it simpler and easier to say "when this value changes, I want to run this code".  I realize this is not what you intended shiny to be like but it's more intuitive to me in some use cases and I find the code simpler. I use reactivity more natively when using the `renderFoo` functions - that's one place where being reactive is almost always what I find the most natural and works well. Another time I use `observeEvent` is when I have a more complex expression with many reactive values inside but I only want it to run when one reactive value changes (not necessarily a button). Instead of putting most of the code inside an isolate, it just makes more sense to me personally to say "run this code when this one value changes".  I agree that reactivity is key to shiny and very important to learn, and I'm not saying that these techniques should be necessarily encouraged, but after developing many complex apps this is what works best for me.

#3. I do indeed use eventReactive probably more than the average shiny developer (although I always forget it's not called reactiveEvent - difference naming scheme). But I don't use it as often as observeEvent, I think it's because I prefer to use `reactiveValues` which takes away the need to make reactive variables. Again, this is probably steering very far away from what shiny was meant to do, but I find it's simpler to develop larger apps.

All in all, I find reactivity very useful and a good approach to some things (such as UI rendering and outputs), but for a lot of logic stuff I prefer the callback approach. I don't really actively think of it as being callback instead of reactive - in my mind I just think "instead of being dependent on all the variables inside the expression, I want to only be dependent on the variable that I decide".  I hope that makes sense.

---

I'd love to resolve this or get some more insight at some point, to know whether or not I should continue to be using `observeEvent`/`eventReactive` or if I should use the more traditional approach that everyone else uses.

**Comment by jcheng5** [comment]
I don't think there's anything wrong with what you're doing in the abstract. If there are any specific instances I see in the future where you use observeEvent and I think it's a meaningful improvement to use observe, I'll let you know and we can discuss it then.
