### ISSUE TITLE
Request: textAreaInput

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#884]
I've seen a couple of questions on StackOverflow about text areas from other users and I intend to use it, too. The [current approach](http://stackoverflow.com/a/14452837) seems to be to manually specify the HTML code in R. Would it be worthwhile adding a `textAreaInput` convenience function to Shiny, since multiple users are asking about it ?

**Comment by DrumSergio** [comment]
I will really appreciate it too!

**Comment by DarioS** [comment]
This has been incorporated into version 0.14.
