### ISSUE TITLE
Feature request: divider and dropdown-header in navbarMenu

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#888]
As @yihui [suggested](https://groups.google.com/forum/#!topic/shiny-discuss/JFCFSmAK-YQ) I'm filing a feature request for dividers and dropdown-headers in a navbarMenu.

Below the text from my [question on SO](http://stackoverflow.com/questions/31237120/add-a-divider-and-dropdown-header-to-navbarmenu):

As my shiny app grows I'm running out of space in the navbar. I would like to add a divider and dropdown-header into a navbarMenu to combine some menu items. Adding the html directly doesn't do anything. Wrapping it inside `tabPanel` does insert something but makes the dropdown-header into a link and also adds whitespace that links to ... nothing (see example code below). So not great. Is there another way to do this?

    navbarMenu(
      tabPanel(HTML("<li class='divider'></li><li class='dropdown-header'>example header</li>")),
      tabPanel(HTML("<li class='divider'></li>"))
    )

There seems to have been an SO question by @george-dontas about this at some point or the link inside [this page](http://www.inside-r.org/questions/adding-divider-navbarmenu-shiny) is broken.

**Comment by yihui** [comment]
In earlier versions of shiny when we were using Bootstrap 2, the divider can be generated by any number of dashes like `----`, but it seems this feature was lost during the transition from Bootstrap 2 to 3. Here is the relevant code for Bootstrap 2: https://github.com/rstudio/shinybootstrap2/blob/master/R/tabs.R#L48-L54 Cc @wch

**Comment by wch** [comment]
Unfortunately, Bootstrap 3 dropped support for dividers. See: http://stackoverflow.com/questions/19203816/vertical-divider-dont-work-in-bootstrap-3

**Comment by yihui** [comment]
I think they dropped the _vertical_ dividers. @vnijs Are you asking for horizontal dividers? I think the horizontal dividers are still supported: http://getbootstrap.com/components/#navbar but we dropped this feature in Bootstrap 3.

**Comment by vnijs** [comment]
@yihui and @wch I'm looking for _horizontal_ dividers and dropdown-headers. For an example of the feature see the Formats dropdown at http://rmarkdown.rstudio.com/

**Comment by stevepowell99** [comment]
+1 for horizontal dividers.

**Comment by vnijs** [comment]
@wch are horizontal dividers feasible? As apps, and menus, get bigger this would be very convenient

**Comment by wch** [comment]
@vnijs you're right, I misunderstood the original question. I created a PR for it.

**Comment by vnijs** [comment]
Thanks @wch! Sorry to be greedy but could we also have dropdown-headers?

**Comment by wch** [comment]
Can you point me to an example of what you mean?

**Comment by vnijs** [comment]
HTML:

...
<li class="divider"></li>
<li class="dropdown-header">Base</li>
...

Result:

![image](https://cloud.githubusercontent.com/assets/2998956/14037324/702acfb2-f1ff-11e5-8256-6b9addc0c749.png)

**Comment by wch** [comment]
OK, I've added that to the PR.
