### ISSUE TITLE
how to store data that a user inputs in a Shiny app [through checkboxGroupInput() or textInput()] in a variable in R?

### ISSUE THREAD

**Issue by aditi-arvind** [rstudio/shiny#895]
Say a user inputs 5 words. I want to store them in a list and use that list for further coding. How is it possible to do this?

**Comment by yihui** [comment]
I don't quite understand what you were asking. For a input with id `foo`, `input$foo` is its value in the server function. You can do whatever you want with this value.

For questions, please use the mailing list https://groups.google.com/forum/#!forum/shiny-discuss or StackOverflow: http://stackoverflow.com/tags/shiny
