### ISSUE TITLE
Allow `dateInput` to have an unspecified value

### ISSUE THREAD

**Issue by aronatkins** [rstudio/shiny#896]
It would be nice to allow a `dateInput` control to have an unspecified value. Right now, if you provide `value=NULL`, you get "today" by default.

The use case is one where I want to know if the user has made a explicit choice of a date value. Not choosing a date value could mean that a search is unbounded, for example.

**Comment by hadley** [comment]
`as.Date(NA)` would be a natural value to use here

**Comment by gmeurice** [comment]
I've tried to use the as.Date(NA), but still, when the user erase the date from dateInput widget, the returned value is still Sys.Date(), and not "", as I expected.

How could a user can choose to leave the fields empty (or to erase a wrong date input to leave it empty) whithout systematically returning "Sys.Date()" ?
