### ISSUE TITLE
Allow `radioButtons` to start unselected

### ISSUE THREAD

**Issue by aronatkins** [rstudio/shiny#898]
Right now, if I leave `selected=NULL`, it chooses the first `choices` value and emits that with a `checked="checked"` property.

It would be nice if `radioButtons` were to support a way for no option to be initially selected.

The use case is one where I need to understand if a user is making an explicit choice or if they want this option to remain unspecified.

My other option is to inject an artificial choice (basically, "use default") and let that be the initial selection.

**Comment by wch** [comment]
I think this should work:

```
radioButtons("foo", "Foo", choices= c("a", "b"), selected = character(0))
```

But it may need to be documented better.

**Comment by jcheng5** [comment]
I vaguely recall doing this on purpose, as it seemed bad to put the control in a state that the user could not return to, once they clicked something. The artificial choice approach doesn't have this drawback and also makes the intent more explicit--seems better to me.

**Comment by aronatkins** [comment]
The `selected=character(0)` approach works.

**Comment by aronatkins** [comment]
Feel free to close this issue unless it's helpful to remain as a doc-improvement request.

**Comment by aronatkins** [comment]
@jcheng5 I have no issue with making the "nothing selected" configuration requiring a bit more code to get working. I'm happy with the approach and only wish it were more discoverable.

**Comment by daattali** [comment]
Just voicing my upvote that the solution should be noted in the documentation for radio buttons
