### ISSUE TITLE
Date Slider Skipping some dates

### ISSUE THREAD

**Issue by anthoneytsou** [rstudio/shiny#901]
Hi RStudio,

I've been playing around with the current github version of shiny and have run into a slight problem with the date range slider. I may be using it incorrectly, but I have made a reproducible example below:

```
library(shiny)
testing <- function() {
  shinyApp(
    options = list(launch.browser = TRUE),
    ui = fluidPage(
        sidebarLayout(
          sidebarPanel(
            sliderInput("foo",
                        "Test", 
                        min = as.Date("2014-07-01"),
                        max = as.Date("2014-12-31"),
                        ticks = FALSE,
                        value = c(as.Date("2014-07-01"), as.Date("2014-12-31")))
           ),
          mainPanel(
          )
        )
      ),
      server = function(input, output, session) {
      }
    )
}
testing()
```

Using the above code, when I slide "2014-12-31" one tick to the left, it goes to "2014-12-29", skipping "2014-12-30". Is there a way I can format my slider so it won't skip dates? Thank you!

**Comment by wch** [comment]
I updated to ion.rangeSlider 2.0.12 in cfae8f4, which fixes this problem.  If you could test it out and confirm, I'd appreciate it.

**Comment by anthoneytsou** [comment]
It works perfectly! Thank you so much!
