### ISSUE TITLE
feature request: drag_drop support for selectize

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#902]
The `drag_drop` option for selectize is very useful. Could this be supported out-of-the-box in Shiny? Some examples:

With DT:
https://gist.github.com/vnijs/2e6eec27eaea12beec00

In Radiant (see pivot tab - categorical variables can be drag-and-dropped):
http://vnijs.rady.ucsd.edu:3838/base/?SSUID=43baf81121

See also this earlier comment:
https://github.com/rstudio/shiny/issues/546#issuecomment-57912168

**Comment by yihui** [comment]
Thanks for the report. I'll do it.

**Comment by DarioS** [comment]
In your application, in the Pivot table tab, click in the text box under Total. Now, click on either of the sliders, without necessarily dragging the slider to a new value. They suddenly change to 2 decimal places and 1 row is removed from the tabular display. It is impossible to ever recover all 5 rows of data unless you press the Refresh button of the internet browser to reset the slider to 3 decimal places and show all 5 rows. The sliders have a bug.

**Comment by vnijs** [comment]
Interesting discovery @DarioS. Perhaps you could post this as a separate issue on GitHub?

**Comment by DarioS** [comment]
It has been created as #908

**Comment by vnijs** [comment]
Works! Thanks @yihui

**Comment by yihui** [comment]
Thanks for letting me know!

**Comment by aflyax** [comment]
Can someone give an example of a script that makes this work for selectizeInput? When I implement `drag_drop` currently, it breaks the functionality.

**Comment by vnijs** [comment]
This gist https://gist.github.com/vnijs/2e6eec27eaea12beec00 should work with the Shiny 0.12.2.9000 or higher

**Comment by aflyax** [comment]
This is what I see when I run that script: http://i.stack.imgur.com/Caoha.png

**Comment by aflyax** [comment]
This is what I see when I run that script:
<img width="445" alt="screen shot 2015-08-12 at 3 50 51 pm" src="https://cloud.githubusercontent.com/assets/9397552/9236441/8205083e-410a-11e5-9220-05a2b8024d75.png">

**Comment by vnijs** [comment]
Works fine. You need to install from shiny github or wait till the new version of shiny gets to CRAN. That is why I listed  "... with the Shiny 0.12.2.9000"
