### ISSUE TITLE
Feature request: Allow unique tags using string mangling for environments

### ISSUE THREAD

**Issue by VermillionAzure** [rstudio/shiny#903]
Right now, I'm trying to develop an app in Shiny that facilitates the use of modules:

```
#UI MODULE
module_env$normalization <- new.env()

eval(envir = module_env$normalization, {
  #Create the UI here
  ui_normalization <-
  tabsetPanel(
    tabPanel('Normalization (FPKM)',
      p("normalization"),
      actionButton("var_echo", "Echo variables")
    )
  )

  #Create your initial input/output variables here
  sum_exp <- NULL
  output_sum_exp <- NULL

  #Always register last
  register_module(
    name="Normalization (FPKM)",
    module=ui_normalization,
    env=module_env$normalization,
    inputs=c('sum_exp'),
    outputs=c('output_sum_exp')
  )
})


###SERVER MODULE
eval(envir=module_env$normalization, {

observeEvent(input$var_echo, {
  print(get("sum_exp", module_env$normalization))
})

})
```

As you can see, I'm using lots of reactive variables to make sure that modules stay separate as well as environments. It all works fine, and the input/output between modules works like a charm.

However, the main problem lies when the UI tags overlap--if UI tags from separate modules overlap, this results in events being fired for more than one module at once. This can be bad.

There are a couple of fixes for this:
1. Coral users into using prefixes for their tag names, hoping that different tags don't overlap.
2. Design a string mangling system to ensure that tag names stay unique.

I like the idea of an optional string-mangling system based on environment to enable Shiny users to make tags unique should they start to make modular apps that need encapsulation.

**Comment by VermillionAzure** [comment]
I've been trying to play around with the functions: I can't figure out a way to make the function find the environment from which its called...

```
uniqueid <- function(name, envir = NULL) {
  if(identical(envir, globalenv())) {
    e = envir
  } else if (is.null(envir)) {
    e = parent.env()
  } else if (is.environment(envir)) {
    e = envir
  } else {
    stop("given non-default argument \'envir\' is not an environment")
  }
  
  return(paste(sep = "",
    sub('<environment: (.*)>', '\\1', capture.output(e)),
    ".",
    name
    )
  )
}
```

**Comment by VermillionAzure** [comment]
Here's the final form of the mangling function:
```
mod_id <- function(name, envir = NULL) {
  if(identical(envir, globalenv())) {
    e = envir
  } else if (is.null(envir)) {
    e = parent.frame()
  } else if (is.environment(envir)) {
    e = envir
  } else {
    stop("given non-default argument \'envir\' is not an environment")
  }
  return(paste(sep = "",
    "ID",
    sub('<environment: (.*)>', '\\1', capture.output(e)),
    "__",
    name
    )
  )
}
```

It seems to work quite well.
However, I must say that for some reason, Shiny is not accepting the IDs that I am giving it, even if I use `as.name(paste(sep='', 'input$', mod_id('my_id', env)))`.

**Comment by alandipert** [comment]
Hi, and sorry to take so long to respond 😄 

Since you posted, [Shiny 0.13.0 shipped Modules](https://blog.rstudio.com/2016/01/20/shiny-0-13-0/), which I believe address the same encapsulation problems you do in the code that you posted.

I'm closing since Shiny Modules seem like they would meet your needs. Please don't hesitate to comment further or create a new issue if I misunderstand.
