### ISSUE TITLE
Rstudio gives warnings in default shiny document

### ISSUE THREAD

**Issue by ziyadsaeed** [rstudio/shiny#907]
When you create a project of shiny document (not the shiny app) it starts a default sample file. Rstudio complains that it cannot find input in the scope.
The document runs fine though

![shiny warning](https://cloud.githubusercontent.com/assets/12503225/8814969/6a672e9e-302c-11e5-9734-e8180886173a.png)

**Comment by kevinushey** [comment]
This is for R Markdown documents with embedded Shiny applications? I guess the `input` and `output` parameters are implicitly available in such contexts -- does that sound right?

**Comment by wch** [comment]
Yup, I think that's right.

**Comment by kevinushey** [comment]
We're tracking this in RStudio now; we can leave this issue open and I'll update + close once we have a fix in RStudio. Thanks for reporting!

**Comment by kevinushey** [comment]
The requisite changes have now been made in RStudio, and so will be available in the coming daily builds as well as the next release.
