### ISSUE TITLE
I  have  the  problem

### ISSUE THREAD

**Issue by turs** [rstudio/shiny#911]
I have  problem about  this :
![image](https://cloud.githubusercontent.com/assets/7262606/8850773/64b5690a-317d-11e5-8d99-234aa2564f4c.png)

Because I met a situation: each column page add a same function controls, and control on the home page graphics.I want to reduce  the number of reactive    in  server.r

**Comment by jcheng5** [comment]
I'm sorry, I can't understand the question. Can you try rephrasing?

**Comment by turs** [comment]
I  want  to  do this :
![theone](https://cloud.githubusercontent.com/assets/7262606/9131452/377de56e-3d1e-11e5-8bf9-8f49de7ab484.jpg)
![theone2](https://cloud.githubusercontent.com/assets/7262606/9131461/440cc368-3d1e-11e5-8525-ec35af1ff988.jpg)
 the two controls is used  to control the picture  and  only one reactive in server.r .
 At first I write the wrong code,now  I changed to it.
Thank you for your time to see my this problem .  ‘Shiny ’ are really amazing！
