### ISSUE TITLE
LoadLibrary failure:  The specified module could not be found rJava

### ISSUE THREAD

**Issue by pulkitnandan** [rstudio/shiny#912]
I have a shiny project and I don't how to fix this error which is faced by most of the people on windows. I have tried around 16 combinations viz. 64/32 - bits of java and R  == 4 Combinations, & 4 for path of environment variable JAVA_HOME.  

Here goes the error.

Loading required package: NLP
Loading required package: RColorBrewer
Loading required package: qdapDictionaries
Loading required package: qdapRegex

Attaching package: ‘qdapRegex’

The following object is masked from ‘package:shiny’:

    validate

Loading required package: qdapTools
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/Rohit/Documents/R/win-library/3.2/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  The specified module could not be found.

Error: package or namespace load failed for ‘qdap’

**Comment by wch** [comment]
I think this isn't a problem with shiny, but rather with your installation of qdap. (This issue tracker is for shiny bugs and features.)
