### ISSUE TITLE
Shiny Pausing Between Reactive Functions.

### ISSUE THREAD

**Issue by anttsou** [rstudio/shiny#921]
Hi RStudio,

I have recently run into a problem where there are long pauses between my reactive functions. I originally thought my reactive functions were slow, but I tested that they are individually very quick. Thus, I believe my app's slow speed is occurring between my reactive functions. I have posted my question with some psedo-code here: http://stackoverflow.com/questions/31866202/shiny-pauses-between-reactive-functions 

if you would not mind taking a look. I would appreciate any form of guidance in this matter and would be happy to provide a more detailed example if more information is necessary! Thank you!

**Comment by jcheng5** [comment]
Replied on S.O. Thanks.

**Comment by anttsou** [comment]
Thank you. I will work on making a fully reproducible example.

**Comment by anttsou** [comment]
Hi Joe, When trying to recreate the problem, I confirmed that you were absolutely correct in that renderChart2 was the cause of the lag. I replied on S. O. with a few more details if you wouldn't mind taking a look! Thank you!
