### ISSUE TITLE
dynamically generated tabs with any output break tabsetPanel id updating

### ISSUE THREAD

**Issue by quazinar** [rstudio/shiny#924]
I'm trying to dynamically generate tabs based on user input and show different output depending on the tab selected. Without any output defined in tabPanel, the tabsetPanel id updates and can be used as expected. Once an output (tested textOutput, verbatimTextOutput, showOutput) is added, the tabsetPanel id gets stuck at the id for the first created tab.

As a work-around, I can define an output variable in the ui, then have the server respond to the tab selections by writing different outputs to the same variable, but doing it that way is limiting in a number of ways (complicates activation of code in an observeEvent, output types have to be the same, etc.)

Code to reproduce (note the line that can be commented to fix the behavior):

```R
library(shiny)

ui <- shinyUI(fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectizeInput(
        inputId='id'
        ,choices = NULL
        ,label='id'
        ,multiple=T
      )
    )
    ,mainPanel(
      uiOutput(outputId='dynamicTabs')
      ,textOutput('testing')
    )
  )
))

server <- shinyServer(function(input, output, session) {
  updateSelectizeInput(
    session = session
    ,inputId = 'id'
    ,choices = c('A','B','C','D')
    ,server = F
  )
  
  output$dynamicTabs <- renderUI({
    tabs <- lapply(input$id,function(x){
      tabPanel(
        title = paste0(x,'_Tab')
        ,h3(paste0('Tab showing:',x))
        ,textOutput('example') ####### Comment this line and input$selectedTab outputs correctly
        ,value=x
      )
    })
    do.call(tabsetPanel,c(tabs,id='selectedTab'))
  })
  
  output$testing <- renderText({
    input$selectedTab
  })  
})

shinyApp(ui=ui,server=server)
```

**Comment by harish2rb** [comment]
any update on this issue?

**Comment by wch** [comment]
The problem here is that each of the tabs contains an output named "example", and when there's more than one of these dynamically-generated tabs, there will be multiple outputs on the page named "example". This raises a Javascript exception which interrupts the Shiny update code in the middle of what its doing.

If you run in Chrome and open the Javascript console, you'll see this:
> Uncaught Duplicate binding for ID example

This is expected behavior, although I do wonder if Shiny make the errors more obvious.

**Comment by quazinar** [comment]
Ah yes, I see it now. I think your suggestion for expected behavior is a good one.

For anyone who comes across this in the distant future, this means the problem can be solved by modifying the line with the comment above from 

,textOutput('example')
to
,textOutput(paste0('example',x))

which will then leave the textOutput unique and avoid the error.
