### ISSUE TITLE
Exporting shiny:::httpResponse

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#926]
When using `session$registerDataObj()` as an AJAX-y system, it's usually useful to return an http response using `shiny:::httpResponse`. It feels a bit hacky using a non-exported function, so I was wondering if there's any harm is exposing it

**Comment by yihui** [comment]
I mentioned this to @jcheng5 long time ago, and I guess we just forgot it since there has not been a second person requesting this. Anyway, I'd :+1: on this.

**Comment by dokato** [comment]
👍

**Comment by filipstachura** [comment]
Yep, I can only +1 on this.

**Comment by daattali** [comment]
This has been implemented in #2970
