### ISSUE TITLE
Dynamically created Submit buttons don't work

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#95]
Events are bound too early

**Comment by jcheng5** [comment]
@bborgesr Did you add the P1 tag? This feels more like close/wontfix to me.

**Comment by bborgesr** [comment]
@jcheng5 I have no idea how the P1 tag got added here. I just added the by-shiny-team by searching for the our names and marking all open issues submitted by one of us.

**Comment by jcheng5** [comment]
OK.

I don't think we can actually deprecate submitButton, but we can continue to discourage its use. In  any case, I'll close this bug.
