### ISSUE TITLE
Default reactive domain missing in shiny session callbacks

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#956]
(Originally reported [on Google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/shiny-discuss/_-9piBSa7kw/IHXQDfzo-PMJ))

When inside one of `session`'s callback functions (`onFlush`/`onFlushed`/`onEnded`), `getDefaultReactiveDomain()` returns `NULL`

```
foo <- function() {
  cat(str(getDefaultReactiveDomain()))
}

shinyApp(
  ui = fluidPage(),
  server = function(input, output, session) {
    foo()
    session$onFlush(foo)
    session$onSessionEnded(foo)
    session$onFlushed(foo)
  }
)
```

Joe mentioned that perhaps all that needs to be done is wrap those calls in a `withReactiveDomain()`

**Comment by daattali** [comment]
I've noticed in v0.13.0 that this is mostly fixed: I can use `getDefaultReactiveDomain()` inside `session$onFlush()` or `session$onFlushed()`, but not inside `session$onSessionEnded()`.  I'm not sure if this is deliberate, or is the `session` object actually destroyed by the time the `onSessionEnded` callback is called and thus it wouldn't make sense to refer to a session?

**Comment by daattali** [comment]
Wrapping the few lines that get called from the session end callback in a `withReactiveDomain()` as Joe suggested seems to work.

Specifically, wrapping [these 6 lines](https://github.com/rstudio/shiny/blob/b658983fb8e52234d4365699e09b132eb1048692/R/shiny.R#L517-L522) with `withReactiveDomain(self, ... )`

I'm not sure if that's desired behaviour or not so I won't make a PR unless I'm told this is ok

**Comment by jcheng5** [comment]
(Can you tell we're going through the bug backlog? 😊 )

I don't remember if leaving off `onSessionEnded` was intentional, but, can you think of a good reason you'd still want the session? At this point, 1) the websocket is closed--you can't communicate with the client, 2) the close callbacks have been called and won't be called again, so you can't use it to automatically clean up reactive things.

**Comment by daattali** [comment]
Wow, "waiting for reply" label, you guys are getting so organized! I've definitely been getting a lot of Joe Cheng on GitHub messages today, it's nice to see all my old issues aren't forgotten :)


This bug report was made because [someone wanted to use shinyjs in onFlushed](https://github.com/daattali/shinyjs/issues/39), which has been fixed since.  So when I filed the bug report here I just mentioned all the callback functions , with the `onsessionended` being the one that still doesn't work, but I think that's fine

**Comment by jcheng5** [comment]
Great, thanks Dean!
