### ISSUE TITLE
Subsetting dataframe and storing in reactiveValues() seems inconsistant

### ISSUE THREAD

**Issue by Stophface** [rstudio/shiny#958]
Thats how I create my first `reactiveValues()`

    myDataSet <- reactiveValues(data = NULL)

I have an `actionButton`. When that is clicked this line is executed:

        observeEvent(input$go, {
                myDataSet$data <- go-df
        })

`go-df` is a dataframe with a few NA`s spread in the rows (but not many)!

I wait for further input from the `ui.R` for subsetting. I store the subsetted results again in `reactiveValues`.

        dataSetAbsolute <- reactiveValues(test1= NULL, test2= NULL)

        observe({
                dataSetAbsolute$test1<- subset.data.frame(x = myDataSet$data,
                                                              subset = myDataSet$data$columnx %in% input$chosenbyuser
                                                              %>% na.omit(.))
        })

That *seems*  to work right. To check I do `str(dataSetAbsolute $test1)` to see whats in there and what I get is rather confusing.

> 'data.frame':	0 obs. of  22 variables:

It lists everything and everything is empty exept for three columns. **Then**, this is followed by 

> 'data.frame':	9 obs. of  22 variables:

There, everything is filled how it is supposed to be. 

How can I understand that?!
Why are there two dataframes behind `dataSetAbsolute$test1`?
Do I missunderstand how `reactiveValues()` work and what they are there for?!

**Comment by wch** [comment]
Hi, the [shiny-discuss](https://groups.google.com/forum/#!forum/shiny-discuss) list is the place to ask general questions like this.
