### ISSUE TITLE
reactiveValues() creates on first assignment object of class NULL -> causes dependicies to crash

### ISSUE THREAD

**Issue by Stophface** [rstudio/shiny#959]
Reproducable example:

**server.R**

    library(shiny)

    shinyServer( function(input, output, session) {
  
        myDf <- reactiveValues(myData = NULL)
        
        problematicDf <- reactiveValues(test = NULL)
        
        observeEvent(input$myButton, {
                myDf$myData <- df
        })
        
        
        observe({
                output$myTestUi <- renderUI({
                        selectInput(inputId = 'mySelection', 
                                    label = 'Selection', 
                                    choices = levels(myDf$myData$z),
                                    multiple = T,
                                    selected = c(levels(myDf$myData$z)[1])
                        )
                })
        })
        
        
        observe({
                problematicDf$test <- subset(myDf$myData, ((myDf$myData$z %in% input$mySelection)))
        })
        
        
        observe({
                str(problematicDf$test)
        })

        observe({
                as.matrix(x = problematicDf$test)
        })

    })

**ui.R** 

    library(shiny)

    shinyUI( bootstrapPage( 
        
        h3("Push the button"),
        actionButton(inputId = "myButton",
                     label = "clickMe"),
        
        h4("Split Merkmal"),
        uiOutput("myTestUi")

    ))

**global.R**

    df <- data.frame(x = 1:10, y = 10:1, z = letters[1:10])
    df$z <- as.factor(df$z)

This gives me:

    NULL
    [1] "NULL"
    NULL
    Warning: Unhandled error in observer: 'data' must be of a vector type, was 'NULL'
    observe({
        as.matrix(x = problematicDf$test)
    })

Only looking at the output of 

    observe({
      str(problematicDf$test)
      print(class(problematicDf$test))
      print(problematicDf$test$z)
    })

after clicking on the `action Button`, without the `as.matrix`, I get:

    NULL
    [1] "NULL"
    NULL
    'data.frame':	0 obs. of  3 variables:
     $ x: int 
     $ y: int 
     $ z: Factor w/ 10 levels "a","b","c","d",..: 
    [1] "data.frame"
    factor(0)
    Levels: a b c d e f g h i j
    'data.frame':	1 obs. of  3 variables:
     $ x: int 1
     $ y: int 10
     $ z: Factor w/ 10 levels "a","b","c","d",..: 1
    [1] "data.frame"
    [1] a
    Levels: a b c d e f g h i j

That is problematic. As you can see it creates first a `df` which is sort of empty, with placeholders, of `class = NULL`. And then, it fills this. However, it seems that other `reactive functions`, waiting for the `problematicDf$test` to be created kick in *as soon* as the `class = NULL`is created. They do not update afterwards anymore. They only update when another selection is made in the `ui.R`.
This causes (in my case) the program to crash since I need to keep on working and subsetting etc. with the so created `data.frame`.

How to handle this?!
I could include an `if else` and check for `is.null()`. But it seems to me that this is an unelegant way.

**Comment by jcheng5** [comment]
I don't really understand the scenario, but let me give you a general answer. If `problematicDf` is going to be used all over, yet it starts out in an uninitialized/unsafe state, then wrap it with a reactive:

```r
safeDfTest <- reactive({
  validate(need(problematicDf$test, FALSE))
  problematicDf$test
})
```

Then everywhere that reads `problematicDf$test` should instead refer to `safeDfTest()`. (Anywhere that /writes/ to `problematicDf$test` should continue to write directly to it.)

That first `validate/need` call will ensure that problematicDf$test is not null; if it is null, then it will cleanly abort the entire call stack up to the level of the observer or output, without complaining about errors.

There is more information about the validate/need calls here: http://shiny.rstudio.com/articles/validation.html I would love any feedback on whether or not the article helps clear things up. validate/need is very useful and powerful but I'm afraid that it is not intuitive, I don't think I did a good job making that particular API easy to understand.

**Comment by Stophface** [comment]
Maybe I did not make my point clear enough. I though the idea of reactiveValues() is to create a reactive object. Meaning, I change my data on user input which I then put in the reactiveValues(), it should trigger a chain of events. That happens, BUT the first thing it sends to my other depending functions (observers and reactive) is an object of class NULL while instead it should send my subsetted data. And this beahviour causes my depending function to crash, since they cannot work with an object of clas NULL. And the point is, it should not be an object of class NULL since I selected something (as you can see in my code). 

Making the validate before seems pointless here, since there should not something of class NULL come back, because, something is chosen!

**Comment by wch** [comment]
The observers and reactives get triggered with the initial values of `problematicDf$test` and `myDf$test`. The initial values of those are `NULL`, (and `class(NULL)` is `NULL`).

**Comment by Stophface** [comment]
Yes, exactly. Thats what I try to point out. Why are they NULL?! They should not be NULL since I selected something in the ui.R (`selected = c(levels(myDf$myData$z)[1])`). That seems rather unlogical to send *first* a NULL value and then something which I selected.

**Comment by wch** [comment]
It's logical if you understand how Shiny works. The content of the `renderUI` needs to be sent to the client, then the client updates the input values and sends them back, and then the server receives the updated input values and can process them. All of that takes time. During that time, the default `NULL` value that you specified is used.

You could put something like this in reactives or observers (this is a fairly common pattern):

A couple unrelated things to note: I'm not sure why you wrapped the the `renderUI` in an `observe()`. That shouldn't be necessary. Also, using `subset` in reactives/observers is not recommended and could cause unexpected problems problems. It's better to use `[`-bracket indexing instead. From the `subset` help page:

> This is a convenience function intended for use interactively. For programming it is better to use the standard subsetting functions like [, and in particular the non-standard evaluation of argument subset can have unanticipated consequences.

**Comment by Stophface** [comment]
Hm, sure its logical if you put it into the context how shiny works. But to me, that seems rather unuseful. It says here (http://shiny.rstudio.com/reference/shiny/latest/reactiveValues.html) that "When you read a value from it, the calling reactive expression takes a reactive dependency on that value, and when you write to it, it notifies any reactive functions that depend on that value". Notifying with NULL, causing dependencies to crash seems like a rather unuseful function here. Meeting the problem by wrapping that again into a reactive function (observe() or reactive()) just to catch the NULL seems to me like its not working as it inteded to be. 

However, thanks for sticking with it!
