### ISSUE TITLE
hclust unused arguments

### ISSUE THREAD

**Issue by lopezavila69** [rstudio/shiny#960]
Hello everyone,

I am doing some text mining tasks after an actionButton is clicked, within an observeEvent function.

One of the tasks is display a cluster dendogram using hclust. For instance, I have tried to change its
title and x label axis defautls. However, I experience an "unused arguments" error:

rv$dendogramFit <- hclust(distMatrix, method = "ward.D", main = "My Title", xlab = "My X Axis")

Warning in run(timeoutMs) :
  Unhandled error in observer: unused arguments (main = "My Title", xlab = "My X Axis")
observeEvent(input$searchTmButton)
ERROR: [on_request_read] connection reset by peer

For the moment, I will leave them with their defaults, as it seem to work 

Thanks in advance.

**Comment by yihui** [comment]
Please consult the help page `?hclust`. `main` and `xlab` are not arguments of `hclust`, but arguments of the `plot()` method on the `hclust` object instead.

**Comment by lopezavila69** [comment]
OK, reviewed. Thanks you @yihui
