### ISSUE TITLE
installation procedure (Cygwin)

### ISSUE THREAD

**Issue by lormitech** [rstudio/shiny#964]
The installation procedure for the 'shiny' R package fails on Cygwin.
The 'shiny' R package imports the 'httpuv' R package. The 'httpuv' R package use the barrier interface (pthread_barrier). Since Cygwin does not currently support the barrier interface, the installations of the two R packages fail.

**Comment by jcheng5** [comment]
Sorry, cygwin isn't supported. Is it possible for you to use the regular MinGW builds of R, as distributed by CRAN?

**Comment by lormitech** [comment]
No problem. I wanted just to report it for the benefit of other users.
