### ISSUE TITLE
add keyboard_step to updateSliderInput arguments

### ISSUE THREAD

**Issue by AlunHewinson** [rstudio/shiny#972]
Ion.RangeSlider allows one to specify the size (in percentage) of keyboard steps on a slider (see http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html)
Currently, in Shiny, we cannot specify this programatically.  It is only possible by making an index.html file with the keyboard step hard-coded in, for example:

```
<input class="js-range-slider" id="topNDate" data-type="double"
  data-min="1385856000000" data-max="1438297200000"
  data-from="1385856000000" data-to="1438297200000"
  data-step="86400000" data-grid="true" data-grid-num="9.66666"
  data-grid-snap="false" data-prettify-separator=","
  data-keyboard="true" data-keyboard-step="1"
  data-drag-interval="true" data-data-type="date" data-time-format="%F"/>
```

Ideally this property would be exposed to both `sliderInput()` and `updateSliderInput()`, so when setting and changing the max and min of a sliderInput, the keyboard-step can be precisely controlled.

**Comment by daattali** [comment]
There is already a milestone (of 12.2 which is passed, so hopefully it'll be implemented soon) on a similar issue
#866

**Comment by wch** [comment]
This option has been removed from ion.rangeSlider as of version 2.2.0.
