### ISSUE TITLE
KISS principle on the server.R | global.R side

### ISSUE THREAD

**Issue by Stophface** [rstudio/shiny#973]
I want to stick with the KISS (keep it simple, stupid) principle within my shiny app (http://code.tutsplus.com/tutorials/3-key-software-principles-you-must-understand--net-25161).

So I created a folder and subfolders and saved peaces of my code uses in the `server.R` into functions and `.R` files.
Here two examples of two saved `.R` files:

    output$myChoices <- renderUI({
        selectInput(inputId = 'x', 
                    label = 'y', 
                    choices = levels(myDataSet$df$z),
                    multiple = T
        )
    })

or

    absoluteMatrix <- reactive({
        lifeChar <- switch(as.integer(input$something),
                       "abc",
                       "def",
                       "ghi",
                       "jkl",
                       "mno"
         )
    
         if( (myBoolean$absolute == TRUE) && (length(input$xy) != 0) ){
        
            if( (length(input$gh) == 0) ) {
                return(myData()[,grepl(lifeChar, names(myData()))] %>% 
                           na.omit %>% 
                           as.matrix)
            
            } else if( (length(input$gh) != 0) ) {
                return(myDataKD()[,grepl(lifeChar, names(myDataKD()))] %>% 
                           na.omit %>% 
                           as.matrix)
            } 
        }
    })

In the `server.R` I wrote the following
 
    library(shiny)
    source("onLoad.R")
   
      shinyServer(function(input, output, session) {
    
         sourceRecursive("/.../")

     })

In the `onLoad.R` file the function `sourceRecursive` is defined:

     #check folder and all subfolders for .R files
     #source() them! 
     sourceRecursive <- function(path) {
          dirs <- list.dirs()
          files <- dir(pattern = "^.*[Rr]$", include.dirs = FALSE)
          for (f in files)
              source(f)
          for (d in dirs)
              sourceRecursive(d)
       }

But, that did not do the trick. It seems that it does not load the files. That is not an issue - I am aware of that. I thought I might get some hints here how to handle that.

**Comment by wch** [comment]
Normally you would want to use `source(local=TRUE)`, but that probably won't work as expected when you're calling `source()` from another function. See http://shiny.rstudio.com/articles/scoping.html

This version of `sourceRecursive` may help evaluate in the correct environment, but I haven't tested:

```R
 sourceRecursive <- function(path, env = parent.frame()) {
      dirs <- list.dirs()
      files <- dir(pattern = "^.*[Rr]$", include.dirs = FALSE)
      for (f in files)
          source(f, local = env)
      for (d in dirs)
          sourceRecursive(d, env)
   }
```
