### ISSUE TITLE
Using "source(local=TRUE)" more than once doesn't work

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/shiny#977]
Reported in this support ticket:

https://rstudioide.zendesk.com/agent/tickets/14761

This article:
http://shiny.rstudio.com/articles/scoping.html

mentions the following:
```
# Objects in this file are shared across all sessions
source('all_sessions.R', local=TRUE)

shinyServer(function(input, output) {
  # Objects in this file are defined in each session
  source('each_session.R', local=TRUE)

  output$text <- renderText({
    # Objects in this file are defined each time this function is called
    source('each_call.R', local=TRUE)

    # ...
  })
})
```

But they claim:
```
That didn't seem to work for me- it looks like if I run two source(local=TRUE) commands in succession the second one can't access variables created in the first? 
```

I haven't tried that, but didn't want to lose this issue, if it is an actual issue.

**Comment by jcheng5** [comment]
(cc @garrettgman)

If you want variables defined in the sourced file to be available outside of the sourced file, you need to do `local = environment()` instead of `local = TRUE`.

We'll have a better story around this soon, when my modules work makes it onto master.
