### ISSUE TITLE
Running simple shiny examples crashes RStudio v0.99.724 Preview on Windows 8.1 with RRO 3.2.2

### ISSUE THREAD

**Issue by dreammaster38** [rstudio/shiny#978]
Hi,

i have a problem on using shiny with the latest preview versions of RStudio.

Everytime if i try to run a simple shiny example RStudio crashes to desktop.
If i try to run the sample from the R console it works.

Here are my system specs:

* Windows 8.1 64Bit
* RStudio v0.99.724 Preview
* Revolution analytics RRO 3.2.2

My session info:

R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.12.2.9003   RevoUtilsMath_3.2.2

loaded via a namespace (and not attached):
[1] R6_2.1.1          htmltools_0.2.6   tools_3.2.2       Rcpp_0.12.1       rstudio_0.98.1091 digest_0.6.8     
[7] xtable_1.7-4      httpuv_1.3.3      mime_0.4

RSession log:
15 Oct 2015 12:20:24 [rsession-Thomas] ERROR system error 109 (Closed pipe); OCCURRED AT: virtual void rstudio::session::NamedPipeHttpConnection::close() C:\Users\Administrator\rstudio\src\cpp\session\http\SessionNamedPipeHttpConnectionListener.hpp:198; LOGGED FROM: virtual void rstudio::session::NamedPipeHttpConnection::close() C:\Users\Administrator\rstudio\src\cpp\session\http\SessionNamedPipeHttpConnectionListener.hpp:198

Code sample:

server.R:
palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
  "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))

shinyServer(function(input, output, session) {

  # Combine the selected variables into a new data frame
  selectedData <- reactive({
    iris[, c(input$xcol, input$ycol)]
  })

  clusters <- reactive({
    kmeans(selectedData(), input$clusters)
  })

  output$plot1 <- renderPlot({
    par(mar = c(5.1, 4.1, 0, 1))
    plot(selectedData(),
         col = clusters()$cluster,
         pch = 20, cex = 3)
    points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
  })

})

ui.R:
shinyUI(pageWithSidebar(
  headerPanel('Iris k-means clustering'),
  sidebarPanel(
    selectInput('xcol', 'X Variable', names(iris)),
    selectInput('ycol', 'Y Variable', names(iris),
                selected=names(iris)[[2]]),
    numericInput('clusters', 'Cluster count', 3,
                 min = 1, max = 9)
  ),
  mainPanel(
    plotOutput('plot1')
  )
))

run with (with server.R and ui.R from above in sub-dir 'simple'):
library("shiny")
runApp("simple")

Thanx for help
Thomas

**Comment by dmpe** [comment]
Hi @dreammaster38 ,
Usuall suggestion is to upgrade everything to the newest versions. Now, it is not reproducible to me. 
```
library("shiny")

palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
          "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))

server <- function(input, output) {

  # Combine the selected variables into a new data frame
  selectedData <- reactive({
    iris[, c(input$xcol, input$ycol)]
  })

  clusters <- reactive({
    kmeans(selectedData(), input$clusters)
  })

  output$plot1 <- renderPlot({
    par(mar = c(5.1, 4.1, 0, 1))
    plot(selectedData(),
         col = clusters()$cluster,
         pch = 20, cex = 3)
    points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
  })

}

ui <- shinyUI(pageWithSidebar(
  headerPanel('Iris k-means clustering'),
  sidebarPanel(
    selectInput('xcol', 'X Variable', names(iris)),
    selectInput('ycol', 'Y Variable', names(iris),
                selected=names(iris)[[2]]),
    numericInput('clusters', 'Cluster count', 3,
                 min = 1, max = 9)
  ),
  mainPanel(
    plotOutput('plot1')
  )
))

shinyApp(ui, server)
```

**Comment by dreammaster38** [comment]
H i dmp3,

thanx for having a look into it even if my issue is pretty old now ;)

I alwaays did update all things including R-Studio to thje newest version. But anyway i can't reproduce the issue anymore. Maybe it got fixed in mean time....

Best regards
Thomas
