### ISSUE TITLE
dateInput.setValue doesn't convert to UTC (due to a breaking change in Chrome)

### ISSUE THREAD

**Issue by vkapartzianis** [rstudio/shiny#987]
Minimal Example
---
Server is on UTC time. Client is on GMT+1 time. Using the following app.R
``` R
shinyApp(
  ui = fluidPage(
    helpText(paste("Sys.Date() returns:",Sys.Date())),
    dateInput("selectorTest",label=NULL,max=Sys.Date(),value=Sys.Date())
  ),
  server = function(input, output) {
  }
)
```
I get the following results

![screen shot 2015-10-21 at 13 33 53](https://cloud.githubusercontent.com/assets/1918344/10636558/6b55a394-77f8-11e5-8d40-bb6ebcc2344c.png)

Possible Fix
---
I believe that's because the control's `setValue` function doesn't convert the input date to UTC. Current code is
``` javascript
  // value must be an unambiguous string like '2001-01-01', or a Date object.
  setValue: function(el, value) {
    var date = this._newDate(value);
    // If date is invalid, do nothing
    if (isNaN(date))
      return;

    $(el).find('input').datepicker('update', date);
  },
```
and converting the date to UTC seems to resolve the problem:
``` javascript
  // value must be an unambiguous string like '2001-01-01', or a Date object.
  setValue: function(el, value) {
    var date = this._newDate(value);
    // If date is invalid, do nothing
    if (isNaN(date))
      return;

    date = this._dateAsUTC(date);
    $(el).find('input').datepicker('update', date);
  },
```

**Comment by vkapartzianis** [comment]
I researched this further, the problem seems to be due to a breaking change in Chrome, see "[Issue 543320:	Breaking ES6 change: Date.parse treats '2015-10-14' as local time](https://code.google.com/p/chromium/issues/detail?id=543320&q=new%20date%20UTC&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified)".

**Comment by vkapartzianis** [comment]
I think it's best to avoid browser-specific interpretations altogether, and pass an "ISO 8601 Extended Format" string to the control, from Shiny. See http://es5.github.io/#x15.9.1.15 for details.

**Comment by wch** [comment]
On my reading of the ISO 8601 Extended Format docs, it seems that YYYY-MM-DD (which is what Shiny sends) conforms to that format. Since the bug appears to be fixed in Chrome, I'm closing this issue.
