### ISSUE TITLE
conflict between shiny dateRangeInput and rpivotTable

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shiny#989]
(re-submit at @wch request)

The problem is reproduced on the current version of shiny in dev `devtools::install_github("rstudio/shiny")`.

There are two versions of rpivotTable to test:

This version **does work** with the `dateRangeInput` example below, but it is the one that had issues with ggvis etc.
It uses `jquery 1.11.0` and `jquery-ui 1.10.4`.
````
devtools::install_github("smartinsightsfromdata/rpivotTable", ref='master')
````

This other version **does not work**  with the `dateRangeInput` example below, but it is the one that is aligned with the latest dev version of shiny & qgvis.
It uses `jquery 1.11.3` and `jquery-ui 1.11.4`.
````
devtools::install_github("smartinsightsfromdata/rpivotTable", ref='dev')
````

This is the testing code:

````
library(shiny)
library(rpivotTable)
library(dplyr)
ui = shinyUI(fluidPage(
  dateRangeInput('dateRange',
                 label = 'Rango de Fechas: yyyy-mm-dd',
                 start = as.Date("2015-01-01"), end = Sys.Date() -1
  )
  , rpivotTableOutput('table' )
  
))

server = function(input, output){
  output$table <- renderRpivotTable({
    iris %>%
      tbl_df %>%
      filter( Sepal.Width > 3 ) %>%
      rpivotTable
  })
}

shinyApp(ui = ui, server = server)
````

With `devtools::install_github("smartinsightsfromdata/rpivotTable", ref='dev')` I get this error at the console:

````
jquery-ui-1.11.4.js:4558    Uncaught TypeError: Cannot read property 'empty' of undefined
````
And this is the code associated:

````
	/* Generate the date picker content. */
	_updateDatepicker: function(inst) {
		this.maxRows = 4; //Reset the max number of rows being displayed (see #7043)
		datepicker_instActive = inst; // for delegate hover events
		inst.dpDiv.empty().append(this._generateHTML(inst)); // <-- the error happens here
		this._attachHandlers(inst);
````

**Comment by wch** [comment]
I think this is fixed now in the development version of Shiny.
