### ISSUE TITLE
brush mapping error.

### ISSUE THREAD

**Issue by jackolney** [rstudio/shiny#998]
Hi,

I'm having trouble getting a ggplot to zoom by using plotOutput() and a brush.
If I print out the brush object I get:
``` R
$xmin
[1] 0.6990286

$xmax
[1] 1.04

$ymin
[1] 0.7376

$ymax
[1] 1.04

$mapping
named list()

$domain
$domain$left
[1] -0.04

$domain$right
[1] 1.04

$domain$bottom
[1] -0.04

$domain$top
[1] 1.04


$range
$range$left
[1] 0

$range$right
[1] 700

$range$bottom
[1] 399

$range$top
[1] -1


$log
$log$x
NULL

$log$y
NULL


$direction
[1] "xy"
```
And the fault appearing to be with mapping, as the scale on the y and x axis are much larger than 1 (talking 1e+6). So I'm guessing that the brush hasn't latched onto the mapping of the x and y axis and is hence giving by some proportion of the plot.

Is there a way of manually assigning the `brush$mapping$x` and `brush$mapping$y` attributes?

Many thanks in advance.

**Comment by wch** [comment]
Can you supply a simple reproducible example?

**Comment by jackolney** [comment]
Sure.
``` R
require(shiny)
require(ggplot2)

app <- shinyApp(

 ui = fluidPage(
    plotOutput("plot",
        dblclick = "plotOne_dblclick",
        brush = brushOpts(
            id = "plotOne_brush",
            clip = TRUE,
            resetOnNew = TRUE)
        )
 ),

 server = function(input, output) {

    plot.range <- reactiveValues(x = NULL, y = NULL)

    output$plot <- renderPlot( {
        o <- ggplot(cars,aes(x=speed,y=dist))
        o <- o + geom_point()
        o <- o + coord_cartesian(xlim = plot.range$x, ylim = plot.range$y)
        print(o)
        }
    )

    observeEvent(input$plotOne_dblclick, {
        brush <- input$plotOne_brush
        print(brush)
        if (!is.null(brush)) {
            plot.range$x <- c(brush$xmin, brush$xmax)
            plot.range$y <- c(brush$ymin, brush$ymax)
        } else {
            plot.range$x <- NULL
            plot.range$y <- NULL
        }
    })
}
)
runApp(app)
```

So, I've actually figured it out. It's to do with the way that I build my plot. If I create the plot like this:
``` R
ggplot(cars,aes(x=speed,y=dist)) + 
geom_point() + 
coord_cartesian(xlim = plot.range$x, ylim = plot.range$y)
```
Then the mapping element of brush finds the x and y of the plot and zoom works fine.

**Comment by wch** [comment]
Oh, I think the issue is that you used `print(o)` instead of simply returning `o`. There was a note about this in `plotOutput`, but I just added another one in `renderPlot`, in be1081a.

**Comment by akconley** [comment]
Thank you! This has been driving me nuts! I can't believe such a simple error was giving me so much grief. Everything worked perfectly once I got rid of "print".

**Comment by ginolhac** [comment]
Same here. But, was stuck because of `plot(p)` which has the same nasty effect as `print(p)`.
Using `p` solved the issue.
Thanks a lot!

**Comment by npondel** [comment]
Thank you for this thread!  Spent 2 days trying to figure out why my brush mapping didn't work.

It was due to ending `renderPlot` with `plot(my_ggplot)`.  Everything worked once I ended the `renderPlot` with just `my_ggplot`
